### ISSUE TITLE
Error when alter table change number shards 

### ISSUE THREAD

**Issue by brucemen711** [crate/crate#10028]
I create table with the following sql:
CREATE TABLE IF NOT EXISTS "doc"."hello" (
   "id" INTEGER,
   "avg_value" DOUBLE PRECISION,
   "total_value" BIGINT
)
CLUSTERED INTO 30 SHARDS
WITH (
   "allocation.max_retries" = 10,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = true,
   codec = 'default',
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-2',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = 'fs',
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = '1'
)

After that, i insert 53 million records. Then i run this sql to increase number of shards.
1. alter table hello set ("blocks.write" = true);
2. alter table my_table set (number_of_shards = 60);

The sql is success but CrateDB Admin shows that:
![image](https://user-images.githubusercontent.com/54098579/83344602-31a86300-a333-11ea-9b2b-5fd67ca67bfb.png)

I run the following sql and it shows errors:
select * from sys.allocations where current_state != 'STARTED' limit 100;
![image](https://user-images.githubusercontent.com/54098579/83344610-5ac8f380-a333-11ea-96fa-0bf91b27932c.png)

Please tell me why this happened and how to fix this.
Thanks.

**Comment by brucemen711** [comment]
I try many times and this alway happend. 
If i change number of shard right after create table then it works fine.

**Comment by marregui** [comment]
Hi,

Can you confirm that this is what you are doing?:

1.- Create the table
2.- Insert the 53M records
3.- Wait for the operation to complete
4.- Set `blocks.write=true`
5.- Alter to increase shards
6.- Set `blocks.write=false`

as per [here](number_of_routing_shards)?

Could I see some logs?, 

Thank you in advance

**Comment by brucemen711** [comment]
Yes, i do exactly the same and always get the same error.
The log is on /var/log/messages and it only shows:

May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,240][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97263]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,240][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97263]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,240][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97261]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,240][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97261]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,244][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97264]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,245][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97264]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,260][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97265]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,260][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97265]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,270][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97266]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,271][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97266]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,285][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97267]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,285][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97267]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,296][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97268]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,297][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97268]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,309][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97270]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,310][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97270]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,335][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97272]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,335][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97272]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,360][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97269]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,361][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97269]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,362][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97271]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,362][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97271]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,362][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97273]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,362][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97273]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,377][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97274]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,377][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97274]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,385][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97275]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,397][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97275]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,402][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97277]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,403][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97277]
May 31 11:52:05 bigdata105 crate: [2020-05-31T11:52:05,421][WARN ][o.e.t.TransportService   ] [Pizzo Filone] Transport response handler not found of id [97278]

**Comment by brucemen711** [comment]
When i run this sql: select * from sys.allocations where current_state != 'STARTED' limit 100;
It shows that:

![image](https://user-images.githubusercontent.com/54098579/83431694-f3f62800-a461-11ea-9351-ca0888e41ca7.png)

**Comment by marregui** [comment]
How many nodes have you got?

Do any of the hints in [here](https://www.datadoghq.com/blog/elasticsearch-unassigned-shards/) sound plausible?.

**Comment by brucemen711** [comment]
I have 3 nodes in total. Should i add more node ? Thanks.

**Comment by marregui** [comment]
In the CREATE statement, you define `CLUSTERED INTO 30 SHARDS` and do **not** define the [number_of_routing_shards](https://crate.io/docs/crate/reference/en/latest/sql/statements/create-table.html?highlight=number_of_routing_shards#number-of-routing-shards). This is a requirement. 
I have uploaded 54M entries to the `hello` table and I can confirm that you cannot upscale above 30, how did you achieve it?, I must be missing something.

I played going down to 10 and back up to 30 shards, which took 5 and 3.5 minutes. While the shards where in transit, the health of my cluster was `warning`, which means `all primary shards are started && at least on replicated shard is not started`. I could see in the Admin UI the flux of shards and their change of state. When the system stabilised the health went back to `good`, which means `all shards (primary and replicated) are started`

The `critical` health check means `at least one primary shard is not started`.

Your table is defined to have two replicas in cluster mode, `number_of_replicas = '0-2'`, so your 60 shards are in reality a sum total of 120 shards. See the approach to [upscale here](https://crate.io/docs/crate/reference/en/latest/general/ddl/alter-table.html?highlight=shards#increase-the-number-of-shards).

Regarding the logs, these entries are unrelated but suggest the transport layer is timing out heavily, which suggests constrained resources. What is your hardware setup?, how much RAM are you setting the instances with?, what network bandwidth do you have between nodes?.

**Comment by marregui** [comment]
Hi @brucemen711 ,

how are you doing?, any success?

Best regards

**Comment by brucemen** [comment]
Thanks you @marregui.
I will give it a try. Currently, I'm using 3 node, 16GB,8core per node.

**Comment by brucemen** [comment]
I had alter table set number_of_routing_shards more than 30 shard ( 120 ) then i run this query: alter table my_table set (number_of_shards = 60). After that, table cant be queried anymore, the same error above.

**Comment by marregui** [comment]
I am running out of ideas... I would need to see the server logs, to have a more accurate picture. Could you zip the logs folder of a crate instance (containing the "disaster-scenario") and make them available?.
