### ISSUE TITLE
Add support for global 'g' flag on `regexp_matches`

### ISSUE THREAD

**Issue by marregui** [crate/crate#10041]
This [friendly guy](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/expression/scalar/regex/RegexMatcher.java) ignores global setting when used in the context of scalar function `regexp-matches`.

**Postgres**:

```
select regexp_matches('#abc #def #ghi', '(#[^\s]*)', 'g');
 regexp_matches
----------------
 {#abc}
 {#def}
 {#ghi}
(3 rows)
```

**CrateDB**:

```
select regexp_matches('#abc #def #ghi', '(#[^\s]*)', 'g');
 ['#abc']
----------
 {"#abc"}
(1 row)
```

**Use case**:
https://community.crate.io/t/regexp-matches-with-global-flag-returns-wrong-data/232/2

**Comment by seut** [comment]
This is a documented behaviour as CrateDB uses Lucene Regular Expressions on `regexp_matches`. See https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#regular-expression-functions and https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#flags.
