### ISSUE TITLE
Improve Discovery section note on cluster behaviour with default config file

### ISSUE THREAD

**Issue by marregui** [crate/crate#10058]
**Use case**:

[This](https://community.crate.io/t/3-node-cluster-not-forming-after-install-azure-ubuntu-vms/426/2?u=miguel.arregui). 

If you install CrateDB and run it on a default config file, without `cluster.initial_master_nodes`, and then you reconfigure it and want to setup a cluster, you need to detach the node (potential risk of data loss), or delete the data.

There is a note [here](https://crate.io/docs/crate/reference/en/latest/config/cluster.html#discovery): 

```
If a node was started once using single-node, it will never join any cluster even if the configuration is changed. It is possible to force the node to forget its current cluster state by using the crate-node CLI tool. However, be aware that this may result in data loss.
```

**Feature description**:

We should update this note to also note that this happens once the node was started with default config. 

We should also update [this](https://crate.io/docs/crate/reference/en/latest/concepts/shared-nothing.html#discovery) section to include the note.

**Comment by mechanomi** [comment]
thanks for the report, @marregui! someone from the @crate/docs team will get back to you on here
