### ISSUE TITLE
Bad performance for INSERT INTO y SELECT DISTINCT valX FROM x

### ISSUE THREAD

**Issue by proddata** [crate/crate#10082]
**CrateDB version**:
4.1.6

**Environment description**:
CrateDB Cloud (Dev-Instance - 3 nodes are / 3 CPUs / 3GB Ram
(Though also tested with more performant clusters)

**Problem description**:

When inserting values from a distinct select on another table the performance is really bad. It takes 20s for 50 distinct values to be inserted in an empty table. For reference the insert of values selected with a limit is instant.

It seems like this performance issues scales almost linearly with the number of entries in the source table. For large datasets (e.g. 300 mio) the insert won't finish after 30 minutes, even though the SELECT DISTINCT is done in less than a minute.

**Steps to reproduce**:

```SQL
CREATE TABLE doc.bigtable (txt TEXT);
CREATE TABLE doc.smalltable (txt TEXT);

-- Insert 50 distinct text values
INSERT INTO bigtable (txt) VALUES ('TEXT00'),('TEXT01'),...,...,('TEXT48'),('TEXT49');

-- Repeat till 5 million text values (50 distinct);
INSERT INTO bigtable (txt) SELECT txt FROM bigtable;

SELECT DISTINCT txt FROM bigtable limit 100;
-- SELECT OK, 50 rows in set (0.730 sec)

INSERT INTO smalltable (txt) SELECT DISTINCT txt FROM bigtable limit 100;
-- INSERT OK, 50 rows affected (19.085 sec)



-- more tests:
INSERT INTO smalltable (txt) VALUES ('TEXT00'),('TEXT01'),...,...,('TEXT48'),('TEXT49');
-- INSERT OK, 50 rows affected (0.121 sec)

INSERT INTO smalltable (txt) SELECT txt FROM bigtable LIMIT 50;
-- INSERT OK, 50 rows affected (0.137 sec)

INSERT INTO smalltable (txt) SELECT DISTINCT txt FROM bigtable WHERE _docid % 100 = 0;
-- INSERT OK, 50 rows affected (0.868 sec)


-- with 10 Mio Rows
SELECT DISTINCT txt FROM bigtable limit 100;
-- SELECT OK, 50 rows in set (1.337 sec)

INSERT INTO smalltable (txt) SELECT DISTINCT txt FROM bigtable limit 100;
-- INSERT OK, 50 rows affected (38.101 sec)
```

**Comment by mfussenegger** [comment]
We fixed this with https://github.com/crate/crate/pull/10091 which we also backported, so it will be released with 4.1.7
