### ISSUE TITLE
Unclear Documentation - Authentication - default configuration 

### ISSUE THREAD

**Issue by proddata** [crate/crate#10119]
###  Documentation feedback

 
- Page title: Authentication
- Page URL: https://crate.io/docs/crate/reference/en/latest/admin/auth/index.html
- Source: https://github.com/crate/crate/blob/master/docs/admin/auth/index.rst

---

From the documentation right now it is unclear, what the default config for authentication for standard deployments is (packages, docker images, etc.)

> By default, the boolean setting auth.host_based.enabled is false and therefore host based authentication is disabled. In this instance, the CrateDB cluster allows any unauthenticated connections.

then two paragraphs later ..
> The crate.yml that is shipped with CrateDB explicitly enables host based authentication and defines a set of sane rules, which take effect in case HBA and Enterprise features are enabled.

Also the crate.yml shipping with linux packages is different from the default docker ones.

**Comment by mfussenegger** [comment]
@proddata Would you be up for creating a PR that clarifies these parts?

**Comment by proddata** [comment]
@mfussenegger I can help, but I am unsure about some technicalities. E.g. is it possible to use password authentication with HBA disabled?

**Comment by mfussenegger** [comment]
> is it possible to use password authentication with HBA disabled?

No, if you disable HBA and create a user with password, the user will be able to login without password.

**Comment by mechanomi** [comment]
@proddata can you check https://github.com/crate/crate/pull/10861/commits/06292aac971f863b7e4c02e870f907dcba1cc228 to see if this change adequately addresses this issue?
