### ISSUE TITLE
Unknown function: pg_function_is_visible(p.oid)

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10132]
**Problem description**:

Using `conn.getMetaData().getProcedures("", "", "");` in PostgreSQL JDBC fails with:

```
Unknown function: pg_function_is_visible(p.oid)
```

The full query is:

```sql
SELECT NULL AS PROCEDURE_CAT,
n.nspname AS PROCEDURE_SCHEM,
p.proname AS PROCEDURE_NAME,
NULL,
NULL,
NULL,
d.description AS REMARKS,
2 AS PROCEDURE_TYPE,
p.proname || '_' || p.oid AS SPECIFIC_NAME
FROM
    pg_catalog.pg_namespace n,
    pg_catalog.pg_proc p
    LEFT JOIN pg_catalog.pg_description d ON (p.oid = d.objoid)
    LEFT JOIN pg_catalog.pg_class c ON (d.classoid = c.oid
            AND c.relname = 'pg_proc')
    LEFT JOIN pg_catalog.pg_namespace pn ON (c.relnamespace = pn.oid
            AND pn.nspname = 'pg_catalog')
WHERE
    p.pronamespace = n.oid
    AND pg_function_is_visible(p.oid)
ORDER BY
    PROCEDURE_SCHEM,
    PROCEDURE_NAME,
    p.oid::text
```

**Comment by marregui** [comment]
Hi, I have encountered the same problem when I connect with the postgres c client to CrateDB:

```
$ psql -h localhost -p 5433 -U crate
psql (11.5, server 10.5)
Type "help" for help.

crate=> \dt
ERROR:  Unknown function: pg_catalog.pg_table_is_visible(c.oid)
crate=>
```

**Comment by mfussenegger** [comment]
> Hi, I have encountered the same problem when I connect with the postgres c client to CrateDB:
> 
> ```
> $ psql -h localhost -p 5433 -U crate
> psql (11.5, server 10.5)
> Type "help" for help.
> 
> crate=> \dt
> ERROR:  Unknown function: pg_catalog.pg_table_is_visible(c.oid)
> crate=>
> ```

The issue here was about `pg_function_is_visible`, I think for `pg_table_is_visible` you could create a new issue if it doesn't exist yet.

Closing this one because https://github.com/crate/crate/pull/10286 was merged.
