### ISSUE TITLE
Null entries in INFORMATION_SCHEMA.columns ORDINAL_POSITION cause failure in PowerBi

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10148]
**CrateDB version**: master

Selecting a table in PowerBI with `null` values in `ordinal_position` in `information_schema.columns` results in an error:

![screenshot](https://user-images.githubusercontent.com/38700/86015174-84079d00-ba21-11ea-9c85-a852ff593490.png)

Last query executed is:

```SQL
SELECT
    COLUMN_NAME,
    ORDINAL_POSITION,
    IS_NULLABLE,
    CASE WHEN (data_type LIKE '%unsigned%') THEN
        DATA_TYPE || ' unsigned'
    ELSE
        DATA_TYPE
    END AS DATA_TYPE
FROM
    INFORMATION_SCHEMA.columns
WHERE
    TABLE_SCHEMA = 'sys'
    AND TABLE_NAME = 'segments'
ORDER BY
    TABLE_SCHEMA,
    TABLE_NAME,
    ORDINAL_POSITION
```

There are `NULL` entries for the object columns:

```
+-----------------+------------------+-------------+-----------+
| column_name     | ordinal_position | is_nullable | data_type |
+-----------------+------------------+-------------+-----------+
| attributes      |                1 | TRUE        | object    |
| committed       |                2 | TRUE        | boolean   |
| compound        |                3 | TRUE        | boolean   |
| deleted_docs    |                4 | TRUE        | integer   |
| generation      |                5 | TRUE        | bigint    |
| memory          |                6 | TRUE        | bigint    |
| node            |                7 | TRUE        | object    |
| num_docs        |                8 | TRUE        | integer   |
| partition_ident |                9 | TRUE        | text      |
| primary         |               10 | TRUE        | boolean   |
| search          |               11 | TRUE        | boolean   |
| segment_name    |               12 | TRUE        | text      |
| shard_id        |               13 | TRUE        | integer   |
| size            |               14 | TRUE        | bigint    |
| table_name      |               15 | TRUE        | text      |
| table_schema    |               16 | TRUE        | text      |
| version         |               17 | TRUE        | text      |
| node['id']      |             NULL | TRUE        | text      |
| node['name']    |             NULL | TRUE        | text      |
+-----------------+------------------+-------------+-----------+
```

This relates to https://github.com/crate/crate/issues/10163 and one question is if children of object columns should be listed at all in the current form

**Comment by joemoe** [comment]
what does this issue mean from a user perspective?
how is the functionality degraded?

**Comment by mfussenegger** [comment]
> what does this issue mean from a user perspective?
> how is the functionality degraded?

The tables cannot be used at all as far as I could tell.

**Comment by proddata** [comment]
> This relates to #10163 and one question is if children of object columns should be listed at all in the current form

I think we have to list them in some way if we want to use them with standard postgres tools and be able to use the GUI query builders?!

**Comment by mfussenegger** [comment]
> > This relates to #10163 and one question is if children of object columns should be listed at all in the current form
> 
> I think we have to list them in some way if we want to use them with standard postgres tools and be able to use the GUI query builders?!

Maybe, maybe not.
We have to be careful here and come up with a solution that works with a multitude of tools and also client drivers.

Yes, one option would be to list them and output the column names with a dot notation. CrateDB disallows using dots in column names, so it wouldn't conflict with other top-level columns. PostgreSQL allows column names to include dot characters, so it wouldn't be too surprising for tools from a read perspective. Any child column of objects would appear as a regular column.

But that also has the impact that tools that use some form of reflection detects all the columns and doesn't know that columns with dots are child columns of other object columns. So they may generate insert statements like `INSERT INTO tbl (obj, obj.x, obj.y) ...`. This would lead to errors and could break existing working applications. 


PostgreSQL also contains record types and the `JSONB` / `JSON` types. We need to have a look at those as well as they're potential options on how we could expose our object type.

**Comment by seut** [comment]
Just started on this topic and at first found out that, at least by default (but I think this is not configurable),  PostgreSQL won't list any nested childs of columns of type `json`/`jsonb` inside `information_schema.columns`, just the top columns are listed.

**Comment by proddata** [comment]
@seut the syntax for accessing JSON(B)s is also different though. Neither is there a schema mechanism for JSONs in Postgres (or is there?). So it wouldn't even be possible to list them, as you could have properties with the same name, but different data types

**Comment by seut** [comment]
> the syntax for accessing JSON(B)s is also different though.

Yes sure, but this is a bit out of scope for this topic as we could implement the related operators and functions.

As @mfussenegger already pointed out, looking at `json`/`jsonb` as part of this topic makes sense to see how we could optimize our object type exposure in general to support postgresql compatibility (and thus postgresql compatible tools) which would influence how this topic could be solved.

**Comment by proddata** [comment]
@seut sure :)

Might also have to look at Postgres composite types, as objects in CrateDB can IMHO be seen as something in between JSONB and Composite Types.

And composite types come with dot notation ... which would be nice to have 😄

**Comment by seut** [comment]
We have fixed this and also enabled full PowerBI support of column of type object by supporting quoted subscript expression (https://github.com/crate/crate/issues/10163). Sub-columns can be selected in PowerBI just like normal columns now.

See mainly:
 * https://github.com/crate/crate/pull/10490
 * https://github.com/crate/crate/pull/10485
