### ISSUE TITLE
Object(dynamic) is described as `not_indexed ` which is missleading

### ISSUE THREAD

**Issue by kamejosh** [crate/crate#10153]
###  Documentation feedback

 
- Page title: Data types
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html
- Source: https://github.com/crate/crate/blob/master/docs/general/ddl/data-types.rst

---

When reading the documentation for the `Object` type the dynamic object is described like this:

> They will have the type that was guessed by their inserted/updated value and they will always be not_indexed which means they are analyzed with the plain, which means as-is.

When searching the documentation for `not_indexed` or following the link to [plain](https://crate.io/docs/crate/reference/en/latest/general/ddl/analyzers.html#plain-analyzer) and then navigation to [fulltext indices](https://crate.io/docs/crate/reference/en/latest/general/ddl/fulltext-indices.html#plain-index-default) it say that:

> An index of type plain is indexing the input data as-is without analyzing. Using the plain index method is the default behaviour but can also be declared explicitly:

which for me sounds like that plain means `not_tokenized` but still `indexed` which makes more sense when looking at the behavior of the object (dynamic). 
Also this only is true for `Text` fields or is this also applied to fields of other types?

**Comment by mechanomi** [comment]
thanks for the issue report, @kamejosh!

**Comment by autophagy** [comment]
@kamejosh This has now been clarified and is currently up to date on master. Thank you for reporting!
