### ISSUE TITLE
Use double quotes for whole column name, when querying object attributes

### ISSUE THREAD

**Issue by proddata** [crate/crate#10163]
**Use case**:
Right now if I want to query a object attribute in crateDB I have to use

``` SQL
SELECT objectName['attributeName'] FROM table;
--or
SELECT "objectName"['attributeName'] FROM table;
```

Although from the SQL-Syntax-perspective **objectName['attributeName']** is the whole column name. And column names in PostgreSQL and other SQL syntaxes can be encapsulated in double quotes.
For tools with postgres support, they might be able to read the object attribute columns, from the schema, but querying might not work if they encapsulate this names in double quotes automatically (like Grafana does)

**Feature description**:

I would like to be able to query object attribute columns like this:
``` SQL
SELECT "objectName['attributeName']" FROM table;
```
This should increase the compatibility with some tools encapsulating column names in double quotes.

**Comment by mfussenegger** [comment]
> Although from the SQL-Syntax-perspective objectName['attributeName'] is the whole column name

This is not really true. The column name is `objectName`. `['attributeName]` is a subscript expression. Which is similar to an operator or a function call. This is similar to the [record access syntax](https://www.postgresql.org/docs/current/rowtypes.html#ROWTYPES-ACCESSING) (which we also support, - with 4.2 I think)

There quoting the full expression is also not valid:

```
# select (pg_get_keywords()).word;
Time: 0.948 ms
# select "(pg_get_keywords()).word";
ERROR:  42703: column "(pg_get_keywords()).word" does not exist
```

Can you elaborate on the tools (which ones?) and which steps lead to problems?

**Comment by proddata** [comment]
I am referring to the **information_schema.columns** table, where the String **objectName['attributeName']** is the **column_name**

Grafana is using that table and encapsulates the column names (see [example](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/meta_query.ts#L43)) 

Right now you have to manually write the queries and can't really use the UI:

![image](https://user-images.githubusercontent.com/23557193/86341802-11800280-bc57-11ea-90fe-c244da465a18.png)

**Comment by proddata** [comment]
this is also the case for **[looker](https://looker.com/)** and probably other BI tools
![image](https://user-images.githubusercontent.com/23557193/86344307-6bce9280-bc5a-11ea-8685-0fb779bd02c2.png)

**Comment by proddata** [comment]
Actually the above behaviour seems to originate from a potential bug in the `quote_ident()` function

```SQL
cr> SELECT quote_ident(column_name) FROM information_schema."columns" WHERE column_name LIKE '%[%' LIMIT 1;                                                                                                      
+--------------------------+
| quote_ident(column_name) |
+--------------------------+
| "settings['blocks']"     |
+--------------------------+
```

**Comment by proddata** [comment]
With the fix of `quote_ident` the problem is solved for **Grafana**.
However **Looker** adds the double quotes in code and not using the  `quote_ident` function ...

```sql
SELECT table_schema, table_name, column_name, data_type FROM information_schema.columns
WHERE table_schema IN ('doc') AND table_name IN ('test') ORDER BY table_name
```

**Comment by seut** [comment]
Although it's syntactically not completely correct, as @mfussenegger pointed out, we've decided to add support for quoted subscript expression to improve usability and client compatibility.
See https://github.com/crate/crate/pull/10485.

Thank you for bringing this up.
