### ISSUE TITLE
"COPY FROM" is bypassing type validation

### ISSUE THREAD

**Issue by quodt** [crate/crate#10186]
**CrateDB version**:
4.1.7

**Environment description**:

 - local CrateDB instance
 - Number of nodes: 1

**Problem description**:

By inserting data with `COPY FROM ...` from S3 it is possible to write string values (tested with empty strings) into boolean columns. By querying such data `SQLActionException[SQLParseException: Can't convert "" to boolean]` is returned. I haven't tested this issue with different types or different values.

**Steps to reproduce**:

```
# run crate
docker run -ti --rm -p 4200:4200 crate:4.1.7

# create a table with a boolean column
create table x (y boolean);

# create a json file to be imported inside the container. Note the string value
echo '{"y": ""}' > /tmp/x.json

# import that file
COPY x FROM 'file:///tmp/x.json';

# Try to query the data
select * from x
```

**Comment by mfussenegger** [comment]
This is currently [documented behavior](https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-from.html#type-casts-and-constraints)

> CrateDB does not check if the column’s data types match the types from the import file. It does not cast the types but will always import the data as in the source file. Furthermore CrateDB will only check for primary key duplicates but not for other Column Constraints like NOT NULL.

But I guess we should consider changing that behavior to avoid issues like this.
