### ISSUE TITLE
Add node to node encryption

### ISSUE THREAD

**Issue by bputt** [crate/crate#10192]
**Use case**: I would like to secure the traffic between nodes (typically the traffic on port 4300)

**Feature description**: Ideally, non-enterprise feature :) but more or less, some configuration that allows me to specify a cert/key/ca-bundle/tls version. Essentially similar to how searchguard works within ES

I understand you have ssl today, but that's between a client and the query node, no actual encryption between nodes appears to be documented right?

**Comment by mfussenegger** [comment]
> I understand you have ssl today, but that's between a client and the query node, no actual encryption between nodes appears to be documented right?

Yes, this is right.

**Comment by seut** [comment]
Feature is implemented and released with CrateDB 4.6 thus closing this issue.
