### ISSUE TITLE
Cant use ON CONFLICT DO UPDATE statement with nested object column in PK

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10196]
**CrateDB version**: 4.1.8

**Problem description**:
I have table with object column.
One of object's nested column also used in PRIMARY KEY.
I trying to save data to it using INSERT INTO ON CONFLICT DO UPDATE, but parser raise exception.
I tried different ways, but does not found any worked.

**Steps to reproduce**:
```
create table test (
    a object as (
        b string, 
        c string
    ), 
    d string, 
    e string, 
    primary key(a['b'], d)
);
```
`>>> Table TEST created.`

I think - this query should works.
```
insert into test (a, d, e) values ({ b = '1', c = '2' }, '3', '4') on conflict (a['b'], d) do update set e = excluded.e;
```
**`SQL Error: ERROR: SQLParseException: line 1:82: no viable alternative at input 'on conflict (a['`**

I tried other queries - they also failed:

```
insert into test (a, d, e) values ({ b = '1', c = '2' }, '3', '4') on conflict (a, d) do update set e = excluded.e;
```
**`SQL Error: ERROR: SQLParseException: Conflict target ([a, d]) did not match the primary key columns ([a['b'], d])`**

```
insert into test (a, d, e) values ({ b = '1', c = '2' }, '3', '4') on conflict ([a['b'], d]) do update set e = excluded.e;
```
**`SQL Error: ERROR: SQLParseException: line 1:81: no viable alternative at input 'on conflict (['`**

**Comment by mfussenegger** [comment]
As a workaround you could use `ON CONFLICT ("a.b")`:

```sql
cr> create table tbl (o object as (id int primary key, x int));
CREATE OK, 1 row affected  (0.284 sec)

cr> insert into tbl (o) values ({id=1, x=10}) on conflict ("o.id") do update set o['x'] = o['x'] + 1;
INSERT OK, 1 row affected  (0.088 sec)
cr> insert into tbl (o) values ({id=1, x=10}) on conflict ("o.id") do update set o['x'] = o['x'] + 1;
```

We'll look into enabling the normal subscript expression as well.
