### ISSUE TITLE
Kill Jobs feature for CrateDB Cloud

### ISSUE THREAD

**Issue by MarkRatFelt** [crate/crate#10207]
**Use case**: Customers of us want to be able to kill jobs that started and aren't finished yet. Right now, this is possible just with the crate user, but, since they are using the AWS cluster (CrateDB Cloud), they don't have access to the crate user.

**Feature description**: We need to implement something that lets other users kill jobs. Maybe as a privilege.

**Comment by mfussenegger** [comment]
In CrateDB 4.3.0 users will have privileges to kill statements they invoked themselves - see https://github.com/crate/crate/pull/10225
