### ISSUE TITLE
KILL command is not available on CrateDB Cloud 

### ISSUE THREAD

**Issue by WolfgangHerbst** [crate/crate#10209]
###  Documentation feedback

 
- Page title: KILL
- Page URL: https://crate.io/docs/crate/reference/en/latest/sql/statements/kill.html
- Source: https://github.com/crate/crate/blob/master/docs/sql/statements/kill.rst

---

Hi Team, 

To avoid mistaken situations with the user, it should be unambiguous clear that the KILL command ist not working on CrateDB Cloud.

**Comment by mfussenegger** [comment]
Related to https://github.com/crate/crate/issues/10207

**Comment by proddata** [comment]
In CrateDB 4.3.0 users have privileges to kill statements they invoked themselves - see https://github.com/crate/crate/pull/10225
_Originally posted by @mfussenegger in https://github.com/crate/crate/issues/10207#issuecomment-658831459_

**Comment by mechanomi** [comment]
@proddata thanks for the clarification on this. I interpret your comment to mean that once CrateDB Cloud is running 4.3 (which it might already be doing? I cannot find an easy way to check) the `KILL` statement will be supported

accordingly, I added a note to this document warning that the statement is only supported on clusters running CrateDB versions 4.3 and above. I suspect that we can remove this at some point in the future when it is no longer likely that a customer is running an earlier version

please see https://github.com/crate/crate/pull/10861/commits/6d3fab8a7f9fca7c856d9fb200e35175f6caeaae and let me know if I have interpreted this incorrectly

**Comment by proddata** [comment]
@mechanomi

The `KILL` statement was available before as well, however only the super-user `crate` had the needed privileges to execute it. From 4.3 onwards all user can kill their own statements.

**Comment by mechanomi** [comment]
@proddata okay thx! new changeset here: https://github.com/crate/crate/pull/10861/commits/6ae0064fc16a365d73ed3b85c6460ecd0a515762

**Comment by proddata** [comment]
@mechanomi 
looks fine to me, though with the next major, this note probably could be dropped again : /
