### ISSUE TITLE
CrateDB package for Ubuntu Focal Fossa (20.04)

### ISSUE THREAD

**Issue by olavski** [crate/crate#10204]
**CrateDB version**: 4.2.x

**Environment description**: Ubuntu Focal Fossa (20.04)

**Problem description**:
This page (https://crate.io/docs/crate/howtos/en/latest/deployment/linux/ubuntu.html 3) states that CrateDB maintains packages for Ubuntu Focal Fossa (20.04) but I cannot see any available packages for Ubuntu 20 here: https://cdn.crate.io/downloads/deb/stable/dists/

Is it possible to release packages for Ubuntu Focal Fossa (20.04)?

**Comment by mfussenegger** [comment]
> Is it possible to release packages for Ubuntu Focal Fossa (20.04)?

Yes, we'll add it to our build process.

**Comment by mfussenegger** [comment]
We added it to the build process and re-built the packages for 4.2.0 (which are currently still testing) - https://cdn.crate.io/downloads/deb/testing/dists/

**Comment by olavski** [comment]
Thanks for the quick response! 

Would it be possible to release stable packages for 4.1.x?

**Comment by mfussenegger** [comment]
> Would it be possible to release stable packages for 4.1.x?

We meanwhile promoted 4.2.x to stable, do you still need the package for 4.1.x?

**Comment by olavski** [comment]
Any stable version is good! Thank you very much!
