### ISSUE TITLE
Internal periodic ANALYZE in 4.1 can cause a significant increase in load compared to 4.0

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10240]
In 4.1.0 to 4.1.8, 4.2.0 and 4.2.1, CrateDB internally invokes a `ANALYZE` every 1 hour.

On clusters with large data sets this can cause a significant extra load.

Here is an example:

![screenshot](https://user-images.githubusercontent.com/38700/87761763-52107c00-c812-11ea-8166-a34c22a90462.png)

The first line marks the upgrade from 4.0 to 4.1. At the second line the `stats.service.interval` was increased from one hour to 24 hours using `SET GLOBAL PERSISTENT "stats.service.interval" = '24h'`

I'd recommend to manually increase the service interval on such clusters to reduce the load. Or even disable it and run `ANALYZE` manually after large imports or when the cluster is otherwise under light load.

**Comment by bputt-e** [comment]
@mfussenegger if we run the command ```SET GLOBAL PERSISTENT "stats.service.interval" = '24h'``` is it going to run every 24 hours at the time I set it, so if I run the command at 2pm, will it run it everyday at 2pm or is it random?

**Comment by mfussenegger** [comment]
> @mfussenegger if I run the command `SET GLOBAL PERSISTENT "stats.service.interval" = '24h'` is it going to run every 24 hours at the time I set it, so if I run the command at 2pm, will it run it everyday at 2pm or is it random?

Yes, it will run every 24 hours at the time you set it. (Or when a node is restarted, ~24h after the restart)
