### ISSUE TITLE
Cant drop snapshot

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10259]
**CrateDB version**: 4.8.1

**Problem description**:
I have local repository (one backup folder shared between all nodes).
Some time ago I needs to restore table from snapshot.
I dropped original table, and execute `RESTORE SNAPSHOT xxx TABLE yyy`;
I forgot to setup `wait_for_completion = true` parameter, so query executed quickly.
I found problem and after a few seconds I droped this table (during `RESTORE SNAPSHOT` works in background). 
Then I tried to repeat `RESTORE SNAPSHOT xxx TABLE yyy` command, but it was failed with same result as below.

I restart cluster (one node by one), but it was not help me.

At now I cant drop old snapshots..
`drop snapshot bck.bck202007010500`
`>> ERROR: ConcurrentSnapshotExecutionException: [bck:bck202007010500/ZlHwR2o4QdCRV8AFI9KcOA] cannot delete snapshot during a restore`

**Comment by mfussenegger** [comment]
I tried to reproduce this, but for me running another restore after the table was deleted works:


```
cr> drop table uservisits;
DROP OK, 1 row affected  (3.810 sec)

cr> restore snapshot nuc.uservisits table uservisits;
RESTORE OK, 1 row affected  (0.494 sec)

cr> drop table uservisits;
DROP OK, 1 row affected  (0.039 sec)

cr> create snapshot nuc.uservisits_new table uservisits with (wait_for_completion = true);
SQLActionException[RelationUnknown: Relation 'uservisits' unknown]

cr> restore snapshot nuc.uservisits table uservisits with (wait_for_completion = true);
RESTORE OK, 1 row affected  (1872.135 sec)
```


Can you reliably reproduce the behavior on some test environment on your side?

**Comment by shm-dmitry** [comment]
@mfussenegger 

I reproduced error locally (sorry, the first description was not accurate).

I have table with 200k rows ( 300 MB of data)
![Screenshot_20200724_124539](https://user-images.githubusercontent.com/19342331/88379418-94eec880-cdab-11ea-9605-dad4886bef7b.png)

At first - I renamed it
`alter table doc.catalog rename to catalog_new;`
`>> Table DOC.CATALOG altered.`

Next - I start restoring this table from snapshot and very quickly rename created table.
`restore snapshot bck.test table doc.catalog;`
`>> Snapshot RESTORE restored.`
`alter table doc.catalog rename to catalog_old;`
`>> Table DOC.CATALOG altered.`

After this table shows with `CRITICAL` health status. No data actually restored into it.
![table_broken](https://user-images.githubusercontent.com/19342331/88379762-23fbe080-cdac-11ea-970f-d4bfeff5c942.png)

I drop this table.
`drop table doc.catalog_old;`
`>> Table DOC.CATALOG_OLD dropped.`

And at now I cant restore it:
`restore snapshot bck.test table doc.catalog;`
`>>> ERROR: ConcurrentSnapshotExecutionException: [bck:test/Sx51gAUvSoGPU0CGS3XWoA] Restore process is already running in this cluster`

**Comment by mfussenegger** [comment]
Okay, I managed to reproduce it. We will try to come up with a way to resolve the issue.

**Comment by mfussenegger** [comment]
Locally with a single node a restart fixes the issue for me. 

Will see what can be done with a clustered setup.

**Comment by mfussenegger** [comment]
In a clustered setup restarting the active master node also fixed the issue for me.
Will do some further tests to ensure that really is always the case.

**Comment by shm-dmitry** [comment]
@mfussenegger , I restart active master node, but problem was not solved.

**Comment by mfussenegger** [comment]
> I restart active master node, but problem was not solved.

Yes, in sub-sequent tests it also didn't solve it for me. A full restart (stopping all nodes, then starting them again) - did solve it.

I'll see if that is a reliable approach or if there is a better solution to mitigate the problem. But it will take some time.

**Comment by mfussenegger** [comment]
@shm-dmitry Is a full restart an option for you?

It seems to reliably fix the problem for me and I don't see another option to fix it that doesn't involve a code change.

**Comment by shm-dmitry** [comment]
@mfussenegger , yes, I can use full-restart of cluster. 
I will execute this on this week at night.
Thank you.

**Comment by shm-dmitry** [comment]
@mfussenegger 
Full cluster restart helped to me.
Thank you.

**Comment by mfussenegger** [comment]
Glad that it worked. :+1:
