### ISSUE TITLE
Inserting into table with clustering based on a object's property fails in 4.2.x

### ISSUE THREAD

**Issue by PhilippJust** [crate/crate#10270]
**CrateDB version**: 4.2.1

**Environment description**:

 - Docker: version 19.03.8
 - Problem can be reproduced without docker: 
    - Haven't checked that but I find it very likely

**Problem description**:
Consider a simple table that uses clustering based on an object's property such as
```SQL
CREATE TABLE objects (complex object(strict) AS (id INT, name TEXT)) CLUSTERED BY (complex['id']) into 4 shards;
```
When trying to insert a simple row like:
```SQL
INSERT INTO objects VALUES ({id=4, name='George'});
```
We run into this error:
`SQLActionException[SQLParseException: Clustered by value is required but is missing from the insert statement]`
Which seems to be incorrect as the `id` was given.

The same query works with version 4.1.8

If we leave out the clustering in 4.2.1, it also works.
```SQL
CREATE TABLE objects_unclustered (complex object(strict) as (id int, name text));
INSERT INTO objects_unclustered VALUES ({id=4, name='George'});
```

**Comment by mfussenegger** [comment]
Thank you for the report. We've a fix pending (https://github.com/crate/crate/pull/10273) which will be released with 4.2.2
