### ISSUE TITLE
Select by primary key does not find a row.

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10302]
**CrateDB version**: 4.1.8

**Problem description**:
I have table with 4-columns PK.
I trying to select row by PK, and receive empty result.

**Steps to reproduce**:
```
CREATE TABLE test (           
   "id" TEXT,      
   "region_level_1" TEXT,                
   "marker_type" TEXT,                   
   "is_auto" BOOLEAN,                     
   PRIMARY KEY ("id", "region_level_1", "marker_type", "is_auto")                    
)
```
`>> Table TEST created.`

```
insert into test (id, region_level_1, marker_type, is_auto) values ('1', '2', '3', false);
```

`>> 1 row inserted.`

```
select * from test where id = '1' and region_level_1 = '2' and marker_type = '3' and is_auto = false;
```
**`>> no rows returned!`**

When I change any `=` to `LIKE` - query finds the row:
```
select * from test where id LIKE '1' and region_level_1 = '2' and marker_type = '3' and is_auto = false;
```
`>> 1 rows found`

**Comment by mfussenegger** [comment]
Thank you for the bug report.

We'll have a fix for this in the 4.2.3 release (https://github.com/crate/crate/pull/10307)
Turns out this happens as soon as one of the columns used in the primary key definition is of type `boolean`
