### ISSUE TITLE
Cross Data Center Replication

### ISSUE THREAD

**Issue by weswam** [crate/crate#1034]
I am working on a project that requires cross data center replication for failover in the event of the loss of a complete region. I have reviewed the available documentation and the comments within the config files of crate itself but I am not seeing much information on this topic.

An example of a setup would be:

2 DCs (East and West)
2 Crate Nodes per Data Center linked via a Secure VPN

I can easily setup the replication between nodes over the VPN but I am not seeing anyway to make the replication DC aware. Ideally I would want one full set of the data to live in each data center for failover in the event of a full loss of one of the two regions.

Is this possible on crate? If so how would you configure crate to be aware of the multiple regions for replication?

**Comment by sahil98541** [comment]
How to do this across 2 data centres for version 1.0.2?
I have a lab instance consisting 6 nodes across 2 zones as described in 
https://crate.io/docs/crate/guide/en/latest/scaling/multi-zone-setup.html

When i start replication (number of replication =3 ) shard suppose 100 should start 400 shards .
But replication isnt working only 25% replicated data (i.e original copy with 100 shrads running) 

Please advice
