### ISSUE TITLE
Expose more JMX metrics

### ISSUE THREAD

**Issue by scjimenez** [crate/crate#10371]
**Out of a CAB interview** 

Expose the following JMX metrics as those are part of a customers monitoring and the customer is using its own SQL exporter:
* Primary shards 
  * Replica shards
  * Unassigned
  * Recovering
  * Shard size
  * Table size

**Comment by chaudum** [comment]
One other thing that comes to my mind are node checks. Especially the disk watermark node checks are worth monitoring.

**Comment by scjimenez** [comment]
Thanks for that addition @chaudum, much appreciated
