### ISSUE TITLE
Use table function alias if return type is a base type

### ISSUE THREAD

**Issue by seut** [crate/crate#10387]
When a table function is returning a base type, the table function name should be returned. If the table function is aliased the  alias should be used.

From the PostgreSQL documentation (https://www.postgresql.org/docs/12/queries-table-expressions.html#QUERIES-TABLEFUNCTIONS):
*If column aliases are not supplied, then for a function returning a base data type, the column name is also the same as the function name. For a function returning a composite type, the result columns get the names of the individual attributes of the type.*

Examples:

```
SELECT * FROM unnest([1, 2]) AS my_func;

SELECT my_func FROM unnest([1, 2]) AS my_func;
```

Expected:
```
+---------+
| my_func |
+---------+
|       1 |
|       2 |
+---------+
```

Current:
```
+------+
| col1 |
+------+
|    1 |
|    2 |
+------+
```

For example, Grafana uses this functionality to analyzes the schema and search for metrics.
This query (part) is used and does not work as CrateDB complains with **Column s unknown**:
```
SELECT quote_ident(table_name) FROM information_schema.tables WHERE 
table_schema IN (
  SELECT
    CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
  FROM
    generate_series(
      array_lower(string_to_array(current_setting('search_path'),','),1),
      array_upper(string_to_array(current_setting('search_path'),','),1)
    ) as i,
    string_to_array(current_setting('search_path'),',') s
) ORDER BY table_name;
```

**Comment by jeeminso** [comment]
I need a clarification, specifically regarding `unnest`.

My understanding is that this issue implicitly drops the support for `colN` from table functions. Because of this, selecting individual columns from `unnest` with multiple array args will no longer work.

e.g.
```sql
cr> select * from unnest([1,2],[1,2,3])as f;
+------+---+
|    f | f |
+------+---+
|    1 | 1 |
|    2 | 2 |
| NULL | 3 |
+------+---+
#cannot select col1, col2
```
Postgres also cannot select each columns but it handles this situation with `ROWS FROM` construct:
>The special table function UNNEST may be called with any number of array parameters, and it returns a corresponding number of columns, as if UNNEST (Section 9.18) had been called on each parameter separately and combined using the ROWS FROM construct.
```sql
postgres=# select f from unnest(array[1,2], array[1,2,3]) as f;
   f   
-------
 (1,1)
 (2,2)
 (,3)
(3 rows)
```
Should I try to implement `ROWS FROM` construct similar to Postgres before proceeding or should I come up with a work around designed for `unnest`?
