### ISSUE TITLE
Clarify whether ignored fields are indexed

### ISSUE THREAD

**Issue by mechanomi** [crate/crate#10407]
###  Documentation feedback

 
- Page title: Data types
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html
- Source: https://github.com/crate/crate/blob/4.2/docs/general/ddl/data-types.rst

---

@quodt said:

> A question about ignored: The docs https://crate.io/docs/crate/reference/en/4.2/general/ddl/data-types.html#ignored do not mention explicitly if the fields from the example num_pages and font_size are getting indexed…because I think they are, right?

@seut said:

> they are indexed. only new fields without explicit definition aren't

this is an important detail and should be mentioned

**Comment by mfussenegger** [comment]
There's already a PR in progress addressing this. https://github.com/crate/crate/pull/10405
