### ISSUE TITLE
Crate 4.2.x is not available for older Linux distros via apt

### ISSUE THREAD

**Issue by proddata** [crate/crate#10403]
**CrateDB version**:
4.2.x

**Environment description**:
Ubuntu 18.04 LTS

**Problem description**:

No crate apt-packages > 4.1.8 are available for older Ubuntu versions

see also https://cdn.crate.io/downloads/deb/stable/pool/main/c/crate/

**Steps to reproduce**:

```apt install crate```

**Comment by mfussenegger** [comment]
Thank you for the hint. We've rebuild the packages and they're now available for amd64
