### ISSUE TITLE
subquery problem?

### ISSUE THREAD

**Issue by makebest** [crate/crate#10411]
**CrateDB version**:
CrateDB 4.2.2 (built 4b8e399/2020-07-31T07:28:17Z, Linux 3.10.0-957.21.2.el7.x86_64 amd64, OpenJDK 64-Bit Server VM 14.0.2+12)

**Environment description**:
 - JVM version: OpenJDK 64-Bit Server VM 14.0.2+12
 - Kernel:  Linux 3.10.0-957.21.2.el7.x86_64 amd64
 - Distribution: cat /etc/os-release
 - Number of nodes; 4
 

**Problem description**:
 i suspected that the problem is caused by too many fields in the subquery .
 report an error when executing sql in step 3:
     

> SQL state [XX000]; error code [0]; ERROR: IndexOutOfBoundsException: Index 26 out of bounds for length 26; nested exception is io.crate.shade.org.postgresql.util.PSQLException: ERROR: IndexOutOfBoundsException: Index 26 out of bounds for length 26

 report an error in step 4:
     

> SQL state [XX000]; error code [0]; ERROR: Error in ClassCastException; nested exception is io.crate.shade.org.postgresql.util.PSQLException: ERROR: Error in ClassCastException

 when i replace   `(select * from test ) `   to  `test`,it is work

**Steps to reproduce**:
(1) create a table
```
CREATE TABLE IF NOT EXISTS  test (
   "type" TEXT ,    
   "product" TEXT ,
   "country" TEXT,
   "state" TEXT,
   "county" TEXT,
   "city" TEXT,
   "level1" integer  , 
   "level2" integer ,  
   "level3" integer ,      
   "level4" integer  , 
   "level5" integer ,  
   "level6" integer ,      
   "level7" integer,
  "level8" integer,
  "level9" integer,
  "level10" integer,
  "level11" integer
 
);
```
 (2) insert some data
```
insert into test values('out','Apple','USA','CA','Sonoma','Petaluma',1,1,1,1,1,1,1,1,1,1,1);
insert into test values('in','Apple','USA','CA','Sonoma','Petaluma',2,2,2,2,2,2,2,2,2,2,2);
insert into test values('out','Orange','USA','CA','Sonoma','Petaluma',1,1,1,1,1,1,1,1,1,1,1);
insert into test values('in','Orange','USA','CA','Sonoma','Petaluma',2,2,2,2,2,2,2,1,1,1,1);
```
(3) execute SQL (with order by) 
```
SELECT *
FROM (
	SELECT type
		,product
		,country
		,state
		, county
		 ,city
		,sum(level1) as count1
		,sum(level2) as count2
		,sum(level3) as count3
		,sum(level4) as count4
		,sum(level5) as count5
		,sum(level6) as count6
		,sum(level7) as count7
	FROM (select * from test ) a1
	where product='Apple'
	GROUP BY type
		,product
		,country
		,state
		,county
		,city		
	) a
JOIN (
	SELECT type
		,product
		,country
		,state
		, county
		,city
		,sum(level1) as count1
		,sum(level2) as count2
		,sum(level3) as count3
		,sum(level4) as count4
		,sum(level5) as count5
		,sum(level6) as count6
		,sum(level7) as count7
	FROM (select * from test ) a2
	where product='Orange'
	GROUP BY type
		,product
		,country
		,state
		,county
		,city	
	) b ON (
		a.state = b.state
		OR a.city = b.city
		)
ORDER BY a.count1
```
(4) execute SQL (without order by) 
```
SELECT *
FROM (
	SELECT type
		,product
		,country
		,state
		, county
		,city
		,sum(level1) as count1
		,sum(level2) as count2
		,sum(level3) as count3
		,sum(level4) as count4
		,sum(level5) as count5
		,sum(level6) as count6
		,sum(level7) as count7
	FROM (select * from test ) a1
	where product='Apple'
	GROUP BY type
		,product
		,country
		,state
		,county
		,city		
	) a
JOIN (
	SELECT type
		,product
		,country
		,state
		, county
		,city
		,sum(level1) as count1
		,sum(level2) as count2
		,sum(level3) as count3
		,sum(level4) as count4
		,sum(level5) as count5
		,sum(level6) as count6
		,sum(level7) as count7
	FROM (select * from test ) a2
	where product='Orange'
	GROUP BY type
		,product
		,country
		,state
		,county
		,city	
	) b ON (
		a.state = b.state
		OR a.city = b.city
		)
```

**Comment by mfussenegger** [comment]
Looks like there is a bug in the column pruning logic. It tries to remove columns that are selected in a inner query (`(select * from test )` ) but not used in an outside query. 

That's why changing the inner query to just `test` works - it causes it to by-pass the broken logic.

We're working on a fix that will be available in the next 4.2 release.
