### ISSUE TITLE
Broken link in primitive types list

### ISSUE THREAD

**Issue by matthijskrul** [crate/crate#10445]
###  Documentation feedback

 
- Page title: Data types
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html
- Source: https://github.com/crate/crate/blob/4.2/docs/general/ddl/data-types.rst

---

The link https://crate.io/docs/crate/reference/en/4.2/general/ddl/data-type-text in the list of 'primitive types' is a broken link and gives a 404.

**Comment by mfussenegger** [comment]
Fixed via https://github.com/crate/crate/pull/10729
