### ISSUE TITLE
A table with a small amount of data takes a long time to select

### ISSUE THREAD

**Issue by wangDong524** [crate/crate#10483]
**CrateDB version**:
3.0.2

 - JVM version:1.8.0_231
 - Kernel:Linux localhost.localdomain 3.10.0-693.el7.x86_64 
 - Distribution: centos7
 - Number of nodes:5
in one cluster:
table1: 6 Configured Shards ,4 Replicas ,57.9 Million records,96.7 GB 
table2: 6 Configured Shards ,4 Replicas , 57.9 Million records,41.2 GB 
problem:  The select time of Table 2 is much slower than that of Table 1

**Comment by mfussenegger** [comment]
Transfered the first question [to the discussions](https://github.com/crate/crate/discussions/10482)
