### ISSUE TITLE
Bug in select query

### ISSUE THREAD

**Issue by hramezani** [crate/crate#10494]
**CrateDB version**:
4.2.3
python-crate : 0.21.1

**Environment description**:
- Docker: 19.03.12
 - Problem can be reproduced without docker: 
    - [x] yes

**Problem description**:

**Steps to reproduce**:

Table definition:
```sql
CREATE TABLE test (
        ts1 TIMESTAMP,
        ts2 TIMESTAMP,
        ts3 TIMESTAMP
);
```

When I use python-crate for query:
```python
with connect() as conn:
    cur = conn.cursor()
    cur.execute("""select SUM(case when (ts1 - COALESCE(ts2, ts3)) / 1000.0 < ? then 1 else 0 end) as a from test""")
```

I get this error:
```
crate.client.exceptions.ProgrammingError: SQLActionException[UnhandledServerException: java.lang.UnsupportedOperationException: Can't handle Symbol [Reference: ts1]]
```

Note: with `CratedDB 4.0.12`, everything is fine.

**Comment by seut** [comment]
@hramezani Thank you for reporting. We've fixed this, fix will be part of the next 4.2.5 hotfix release.
