### ISSUE TITLE
Remove Guava dependency from server module

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10510]
We should remove [Guava](https://guava.dev/) as a dependency from the server module.

Most of the functionality we used from Guava are provided by the JDK by now.
The stuff that is missing from the JDK has mostly been added in the utilities we inherited from Elasticsearch, due to their decision to remove Guava completely.
Any functionality that we use which isn't present in the JDK can be copied over and integrated into our code base.

The main motivation is to de-clutter the namespace and remove some mental decision making (e.g., should one use MoreObjects vs Objects and so on).

**Comment by alexmehta** [comment]
is this still needed? If so I would like a stab at removing some guava dependencies.

**Comment by mfussenegger** [comment]
This was actually completed recently. Thanks for asking.
