### ISSUE TITLE
Support for first(returnField,searchField) and last(returnField,searchField) function

### ISSUE THREAD

**Issue by proddata** [crate/crate#10528]
**Use case**:
In timeseries use cases one might often want to get the latest or first value for a specific device/machine/thing.
This can be achieved with sub-queries, which might become rather cumbersome and/or slow.

Therefore it would be convenient to have a (fast) function that returns the value of another field/column when searching for the max/min value of another column.

**Feature description**:

```js
first(returnField, searchField)
last(returnField, searchField)
```
`first()` returns the value of column `returnField` where `searchField` is the minimum.
`last()` returns the value of column `returnField` where `searchField` is the maximum.

e.g. get the latest reported speed for every device:
```SQL
SELECT device, last(speed, ts)
FROM data
GROUP BY device;
```

(slow) workaround:
```SQL
SELECT device, speed
FROM data a,
     (
         SELECT max(ts) AS ts, device
         FROM data
         GROUP BY device
     ) b
WHERE (a.ts = b.ts)
  AND (a.device = b.device)
```

---

Some DBs call these `max_by` and `min_by`

**Comment by hlcianfagna** [comment]
There is another faster workaround 

select device,
split_part(max(CONCAT (date_format(ts),',',CAST(speed  AS STRING)))
/* optionally FILTER(WHERE speed  IS NOT NULL)
to mimic IGNORE NULLS OVER ... */
, ',', 2)::DOUBLE AS last_speed_in_groupbybucket_over_orderby_ts
FROM data
GROUP BY device

**Comment by proddata** [comment]
Another approach:
```sql
CREATE OR REPLACE FUNCTION pos_max(ts ARRAY(TIMESTAMP))
RETURNS long
LANGUAGE JAVASCRIPT
AS
'function pos_max(ts) {
   return ts.reduce((iMax, x, i, arr) => x > arr[iMax] ? i : iMax, 0);
}';

SELECT device, ARRAY_AGG(speed)[pos_max(ARRAY_AGG(ts)]
FROM devices.readings
GROUP BY 1;
```

With 120Mio records / 3000 devices 
- JOIN: 119 seconds 🐌
- CONCAT / SPLIT: 15.5 seconds  🚀
- UDF: 30 seconds 🚄

_just the max timestamp per device: 7.5 seconds_

**Comment by proddata** [comment]
```sql
WITH CTE AS (SELECT device_id, MAX(time) time FROM devices.readings group by 1)
SELECT r.*
FROM devices.readings r JOIN CTE using(device_id,time)
where r.time in (SELECT time FROM cte)
limit 3000;
```
CTE/JOIN: 12 seconds on the same set 🚀🚀

**Comment by matriv** [comment]
@proddata do we also need `first`/`last` aliases for those?

**Comment by proddata** [comment]
[Timescale](https://docs.timescale.com/api/latest/hyperfunctions/last/), [SingleStore](https://docs.singlestore.com/managed-service/en/reference/sql-reference/time-series-functions/first.html), [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-aggs.html#sql-functions-aggs-first) use `FIRST/LAST`
Presto uses `max_by / min_by`
Clickhouse uses `argMax / argMin`
Druid uses `LASTWITHTIME / FIRSTWITHTIME`
Influx uses `last()/first()`

I don't have a super strong preference 🤷 
@matriv
