### ISSUE TITLE
SQLActionException when importing .csv with empty values

### ISSUE THREAD

**Issue by proddata** [crate/crate#10563]
**CrateDB version**:
4.2.4

**Environment description**:
Mac OS 10.15.6
bundled JVM
local installation

**Problem description**:

When Inserting empty/null values from a .csv an exception occurs when selecting on the imported data.

**Steps to reproduce**:

.csv to import
```csv
val,tex
1,"Hallo"
2,"Welt"
,"test"
null,"Test"
````

```sql
CREATE TABLE x (val INTEGER, tex TEXT);
```

```sql
COPY x FROM '/Users/xxx/test.csv'
-- COPY OK, 3 rows affected (0.030 sec)
```

```sql
SELECT * FROM x
-- SELECT ERROR (0.000 sec)
-- SQLActionException[SQLParseException: For input string: ""]
```

**Comment by kovrus** [comment]
@proddata I can't reproduce the issue with the select statement.
With the data you provided only one record cannot be inserted, see:

```
~> cr8 run-crate latest-stable -- @crash --hosts {node.http_url} <<EOF                                                                                                       
CREATE TABLE x (val INTEGER, tex TEXT);
COPY x FROM '/Users/kov/test.csv' RETURN SUMMARY;
REFRESH TABLE x;
SELECT * FROM x;
EOF
# run-crate
===========

Psql      : 127.0.0.1:5432
Http      : 127.0.0.1:4200
Transport : 127.0.0.1:4300
Cluster ready to process requests


# @crash
========

CONNECT OK
CREATE OK, 1 row affected  (0.522 sec)
+--------------------------------------------------------+----------------------------+---------------+-------------+--------------------------------------------------------------------------------------+
| node                                                   | uri                        | success_count | error_count | errors                                                                               |
+--------------------------------------------------------+----------------------------+---------------+-------------+--------------------------------------------------------------------------------------+
| {"id": "ZNJK4K5kQAajj1zP3PwFMg", "name": "Schrotkopf"} | file:///Users/kov/test.csv |             3 |           1 | {"failed to parse field [val] of type [integer]": {"count": 1, "line_numbers": [4]}} |
+--------------------------------------------------------+----------------------------+---------------+-------------+--------------------------------------------------------------------------------------+
COPY 1 row in set (0.172 sec)
REFRESH OK, 1 row affected  (0.136 sec)
+------+-------+
|  val | tex   |
+------+-------+
|    1 | Hallo |
| NULL | test  |
|    2 | Welt  |
+------+-------+
SELECT 3 rows in set (0.057 sec)
```

**Comment by proddata** [comment]
@kovrus 

really strange
If I do it within **crash**, everything works as expected.
If I run the query in the **admin-ui** I get the error

```SQL
-- SELECT ERROR (0.000 sec)
-- SQLActionException[SQLParseException: For input string: ""]
```

**Comment by proddata** [comment]
This also seem to only happen, when importing with `COPY FROM`.
Inserting and querying on (numeric) columns with `null` values works as expected.

**Comment by kovrus** [comment]
@autophagy maybe you have an idea why it is broken in Admin UI? Shall we move this issue to https://github.com/crate/crate-admin?

**Comment by proddata** [comment]
@kovrus 
Actually it seems like this is a database problem after all ...
https://community.crate.io/t/importing-nulls-from-a-csv-with-copy-from/493/4

**Comment by kovrus** [comment]
So the current problem arises when a client queries CrateDB via HTTP with https://crate.io/docs/crate/reference/en/4.2/interfaces/http.html?highlight=http#column-types. The issue happens when CrateDB tries to implicitly cast an empty string to a numeric data type. The cast semantic is correct in this case, CrateDB should not be able to cast an empty string to a numeric value. The root cause of this problem is the way `COPY FROM` parse and interprets CSV empty strings, now both`,` and `"",""` result in a tuple with two empty strings, which would not work for all the cases. It is hard to provide some generic fix for it, we are looking into the direction of enabling a user to define the CSV parser semantic, e.g. mapping the empty string to null, configuring delimiters, etc. Similar feature requests already exist, see https://github.com/crate/crate/issues/7260. We are thinking of targeting it in some of the future minor releases.

For now, depending on the size of your dataset, maybe it worth looking into https://csvkit.readthedocs.io/en/latest/tutorial/3_power_tools.html#csvsql-and-sql2csv-ultimate-power
to generate a table schema.

**Comment by proddata** [comment]
In regards with compatibility with PostgreSQL (https://www.postgresql.org/docs/13/sql-copy.html) I would suggest to change the standard behaviour  of interpreting `,` as tuple of null values and supply an option `NULL` with potential parameter to thread `,` as empty strings.

**Comment by proddata** [comment]
Looking at [Jackson-dataform-csv](https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-csv/latest/com/fasterxml/jackson/dataformat/csv/CsvSchema.html) looks like you either can 
threat ```,,``` and ```"","",""``` as empty strings (by default)
or as `null` when defining `CsvSchema` with `withNullValue("")`

**Comment by mfussenegger** [comment]
> Looking at [Jackson-dataform-csv](https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-csv/latest/com/fasterxml/jackson/dataformat/csv/CsvSchema.html) looks like you either can
> threat `,,` and `"","",""` as empty strings (by default)
> or as `null` when defining `CsvSchema` with `withNullValue("")`


Yes. The problem is that it's also a breaking change - for people who previously imported empty strings they'd start being imported as null value.

That's the reason we want to do this with a syntax extension and as a feature. We want to give users the option to specify how to treat empty strings.

**Comment by amotl** [comment]
Hi there,

I just picked up this discussion and correlated it with [1], where [2] is also referenced. On this matter, there is also [3] and [4].

Coming from there, there is an expression like
```
COPY table FROM '/path/to/file.csv' WITH (FORMAT CSV, DELIMITER ';', FORCE_NULL (field1, field2, field3));
```

Will we also support this `FORCE_NULL` option when bringing this improvement to CrateDB?

With kind regards,
Andreas.

[1] https://stackoverflow.com/questions/45892420/postgresql-copy-empty-string-as-null-not-work
[2] https://www.postgresql.org/docs/current/sql-copy.html
[3] https://dba.stackexchange.com/questions/211721/keep-empty-string-instead-of-null-for-copy-command
[4] https://github.com/MIT-LCP/mimic-code/issues/81

**Comment by proddata** [comment]
From what I know the default [PG behaviour](https://www.postgresql.org/docs/13/sql-copy.html)
- threats `,` as two `null` values
- threats `"",""` as two empty strings

that being said imho for numeric columns both variants should lead to `null` values
