### ISSUE TITLE
Unable to load data after changing table chunking

### ISSUE THREAD

**Issue by owen-gxz** [crate/crate#10583]
**CrateDB version**: 4.2.4

**Environment description**:

 - Docker:  Docker version 18.06.3-ce, build d7080c1
 - Problem can be reproduced without docker: 
    - [x] yes
    - [ ] no -> Consider reporting the issue in https://github.com/crate/docker-crate instead

**Problem description**:
My table can't be loaded when I change the partition using the [document](https://crate.io/docs/crate/reference/en/4.2/general/ddl/alter-table.html#increase-the-number-of-shards)     
I have 1.7 billion data in my table      
now When I wanted to delete this table, I found that I couldn't delete it:
error: 
```
SQLActionException[OperationOnInaccessibleRelationException: The relation "doc.orders" doesn't support or allow DROP operations.]

```
When I want to change the block size， error:
```
SQLActionException[NullPointerException in org.elasticsearch.action.admin.indices.shrink.TransportResizeAction$1.lambda$onResponse$0(TransportResizeAction.java:108)]
```

**Steps to reproduce**:
1: write 1.7Bil data to table,
2: alter table my_table set ("blocks.write" = true);
3: alter table my_table set (number_of_shards = 24); (but it error: SQLActionException[IllegalStateException: the number of routing shards [4] must be a multiple of the target shards [24]])
4. alter table my_table set ("blocks.write" = false);
5. docker restart crate

**Comment by mfussenegger** [comment]
I'm not able to reproduce the issue. Are you able to reproduce this realiably every time?

Were there any other errors in the log?
