### ISSUE TITLE
Performance Improvement - COUNT aggregation on tables with alias

### ISSUE THREAD

**Issue by proddata** [crate/crate#10586]
**Use case**:
When doing a COUNT aggregation on a table with a table alias:
```sql
SELECT COUNT(*) FROM doc.timeseries t limit 100;
-- 58.895 ms
```
the aggregation takes significantly more time, than doing the same aggregation without alias:
```sql
SELECT COUNT(*) FROM doc.timeseries limit 100;
-- 0.237 ms
```
Some DB-Tools (e.g. datagrip) automatically add aliases by default when using auto-completion. 

---

The performance difference can be explained by the query plan

```
SELECT COUNT(*) FROM doc.timeseries t limit 100;
Limit[100::bigint;0]
  └ HashAggregate[count(*)]
    └ Rename[] AS t
      └ Collect[doc.timeseries | [] | true]

```
vs
```
SELECT COUNT(*) FROM doc.timeseries limit 100;
Limit[100::bigint;0]
  └ Count[doc.timeseries | true]
```

**Feature description**:
Use the same/similar optimisation for count aggregations with table aliases

[Optimisation for 2nd case (already in place)](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/planner/optimizer/rule/MergeAggregateAndCollectToCount.java)

**Comment by mfussenegger** [comment]
Thank you for pointing this out.  Added an optimisation rule for this case: https://github.com/crate/crate/pull/10588
