### ISSUE TITLE
Cant save region with empty area inside.

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10612]
**CrateDB version**: 4.1.8

**Problem description**:
I have a ring shaped region.
I trying to save it into DB, but it does not saved.
After some retries I received error `SQL Error: ERROR: InvalidShapeException: Self-intersection at or near point (37.84217194054628, 56.00012017299194, NaN)`
Maybe it is related to [this](https://github.com/pelias-deprecated/quattroshapes/issues/16).

**Steps to reproduce**:
`create table test (a geo_shape);`
> `Table TEST created.`

`insert into test (a) values ( {type='MultiPolygon', coordinates=[[[[37.85614,56.012203],[37.8479,56.017574],[37.84481,56.006443],[37.842407,56.000492],[37.83039,55.981483],[37.819748,55.95958],[37.815285,55.947277],[37.815285,55.94343],[37.81906,55.943047],[37.8891,55.926125],[37.886353,55.882244],[37.916565,55.862984],[37.986603,55.808228],[37.98935,55.779663],[37.93167,55.77889],[37.92206,55.751076],[37.934418,55.713963],[37.924805,55.70932],[37.91931,55.66674],[37.933044,55.569805],[37.875366,55.56592],[37.779236,55.553493],[37.604828,55.524742],[37.500458,55.52863],[37.4469,55.55039],[37.31369,55.620243],[37.240906,55.676037],[37.227173,55.72015],[37.214813,55.76576],[37.310944,55.880703],[37.291718,55.923817],[37.29309,55.935356],[37.30133,55.973797],[37.335663,56.000687],[37.374115,56.01604],[37.40982,56.027554],[37.449646,56.03369],[37.50595,56.02295],[37.533417,55.997612],[37.560883,55.993004],[37.657013,55.97303],[37.81357,55.943047],[37.821465,55.962654],[37.831764,55.98475],[37.845154,56.004524],[37.847214,56.018536],[37.841034,56.017574],[37.71881,56.05747],[37.586975,56.08966],[37.482605,56.08353],[37.18048,56.041363],[37.131042,56.00683],[37.070618,55.9492],[37.019806,55.856045],[37.011566,55.80051],[37.006073,55.73639],[37.03766,55.663643],[37.148895,55.546505],[37.227173,55.49597],[37.29721,55.464844],[37.341156,55.450825],[37.37549,55.432907],[37.586975,55.40329],[37.661133,55.414986],[37.762756,55.42278],[37.875366,55.485855],[37.953644,55.507637],[38.000336,55.54495],[38.03604,55.569805],[38.082733,55.610935],[38.13492,55.638073],[38.15689,55.662094],[38.16925,55.706997],[38.18161,55.735615],[38.22281,55.794334],[38.224182,55.852192],[38.16101,55.904575],[38.092346,55.95612],[37.926178,55.993004],[37.85614,56.012203]]]]} )`

> Sometimes this execution will return `0 rows inserted.`, sometimes - `SQL Error: ERROR: InvalidShapeException: Self-intersection at or near point (37.84217194054628, 56.00012017299194, NaN)`

**Comment by kovrus** [comment]
It seems that this `MultiPolygon` shape is not valid, see 6.1.14 in https://portal.opengeospatial.org/files/?artifact_id=25355 for the `MultiPolygon` assertions and in-/valid examples. You would probably have to adjust intersecting boundaries of the shape or use the `Polygon` shape with interior and exterior rings, see 6.1.11.1 in https://portal.opengeospatial.org/files/?artifact_id=25355 for more details and examples.

![image](https://user-images.githubusercontent.com/7442373/95579855-a2286480-0a36-11eb-87a1-b0bb31a6e722.png)
![image](https://user-images.githubusercontent.com/7442373/95580154-24b12400-0a37-11eb-8928-75e1cee08c9f.png)

**Comment by shm-dmitry** [comment]
@kovrus  Thank you
