### ISSUE TITLE
Problem with min + max float values

### ISSUE THREAD

**Issue by mikethebeer** [crate/crate#10618]
**CrateDB version**: 4.2.5

**Problem description**:

According to my research on floating-point numbers so far the min + max representation of a `float` value on JVM is equal to`-3.4028235e38`. This value cannot be ingested to Crate, however, it gets returned once a slightly smaller value is ingested instead.

So maybe the return value is due to some floating-point rounding arithmetic problems, which you always get. Moreover I ask, why it's not possible to insert the lower bound max float value of `-3.4028235e38` ?

**Steps to reproduce**:

```sql
cr> create table samples (val float); 
cr> insert into samples values (-3.4028235e38::float);                                                                                                                                         
SQLActionException[SQLParseException: Cannot cast `3.4028235E38` of type `double precision` to type `real`]
cr> insert into samples values (-3.4028234e38::float);                                                                                                                                         
INSERT OK, 1 row affected  (0.020 sec)
cr> select val from samples;                                                                                                                                                                   
+----------------+
|            val |
+----------------+
| -3.4028235e+38 |
+----------------+
SELECT 1 row in set (0.007 sec)
```

**Comment by mfussenegger** [comment]
The min value is different:

```
jshell> Float.MIN_VALUE
$1 ==> 1.4E-45

jshell> Float.MAX_VALUE
$2 ==> 3.4028235E38
```


Casts from double to float can also have a precision loss.

Does your use-case allow to go with `double precision`?

**Comment by mikethebeer** [comment]
I'm not referring to the smallest positive non-zero MIN_VALUE of the JVM which is `1.4e-45`. I'm looking for the smallest negative float value, which should be `-3.4028235e38`.

So my assumption would be that if I cast a `double` to `float` then the outcome should be accepted by the DB parser/analyzer as well if it's JVM based.

```
jshell> (float)-3.4028235E38
$3 ==> -3.4028235E38
```

**Comment by mfussenegger** [comment]
Ah of course, you're right. Thank you for the pointers and the reproduction.

Will be fixed with https://github.com/crate/crate/pull/10623

**Comment by mikethebeer** [comment]
@mfussenegger thanks for support and fixing it that fast.
