### ISSUE TITLE
Remove the unnecessary symbols in code examples

### ISSUE THREAD

**Issue by proddata** [crate/crate#10611]
**Use case**:
I want to be able to copy and paste code from out documentation into my (sql) console.
This isn't possible right now, as there are leading dots with new lines like so:
![image](https://user-images.githubusercontent.com/23557193/94796923-b7224980-03df-11eb-8058-9e58b033e664.png)

**Feature description**:
Only use valid code in examples and move any additional info in valid comment syntax e.g.:

```sql
CREATE FUNCTION my_subtract_function(integer, integer)
RETURNS integer
LANGUAGE JAVASCRIPT
AS 'function my_subtract_function(a, b) { return a - b; }';
-- CREATE OK, 1 row affected  (... sec)
```

**Comment by adithyaakrishna** [comment]
@proddata Can I work on this?

**Comment by seut** [comment]
The symbols (the dots) are needed as our documentation is tested via the python doctest suite. One possible solution could be to add a `copy to clipboard` button under each statement which would copy it without the doctest syntax (the dots).

@adithyaakrishna We are always happy about any contributions.

**Comment by adithyaakrishna** [comment]
Okay got it, I hope its okay If I can take some time and do this as I want it to be perfect without any errors 🚀

**Comment by proddata** [comment]
> The symbols (the dots) are needed as our documentation is tested via the python doctest suite. One possible solution could be to add a `copy to clipboard` button under each statement which would copy it without the doctest syntax (the dots).

Unsure if this is super developer unfriendly or developer friendly 🤔

**Comment by mfussenegger** [comment]
We could also try out using `testcode` and `testoutput` directives: https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-testcode

That might allow us to leave out the dots

**Comment by proddata** [comment]
Since we now integrated the copy-button, I will close this 🙂
