### ISSUE TITLE
Ubuntu (18.04 bionic) apt repository broken

### ISSUE THREAD

**Issue by proddata** [crate/crate#10625]
**CrateDB version**:
Latest

**Environment description**:
Ubuntu 18.4 LTS Fresh Install

**Problem description**:
There seems to be a problem with the Ubuntu 18.04 (bionic) repositories.
CrateDB currently can't be installed

**Steps to reproduce**:

```sh
$ wget https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate
$ sudo apt-key add DEB-GPG-KEY-crate
$ sudo add-apt-repository "deb https://cdn.crate.io/downloads/deb/stable/ $(lsb_release -cs) main"

$ sudo add-apt-repository "deb-src https://cdn.crate.io/downloads/apt/stable/ $(lsb_release -cs) main"
--> Error: 'deb-src https://cdn.crate.io/downloads/apt/stable/ bionic main' invalid
```

---

** Alternative** ( following https://crate.io/docs/crate/howtos/en/latest/deployment/linux/ubuntu.html#configure-apt)

```sh
$ sudo touch /etc/apt/sources.list.d/crate-stable.list
$ source /etc/os-release && echo $UBUNTU_CODENAME
bionic
$ sudo nano /etc/apt/sources.list.d/crate-stable.list 
```

/etc/apt/sources.list.d/crate-stable.list 
```sh
deb https://cdn.crate.io/downloads/deb/stable/ bionic main
deb-src https://cdn.crate.io/downloads/deb/stable/ bionic main
```

```sh
$ sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic InRelease         
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease     
Hit:4 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease                         
Get:5 https://cdn.crate.io/downloads/deb/stable bionic InRelease [1845 B]                       
Get:6 https://cdn.crate.io/downloads/deb/stable bionic/main amd64 Packages [600 B]
Fetched 2445 B in 1s (4194 B/s)   
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://cdn.crate.io/downloads/deb/stable bionic InRelease' does not seem to provide it (sources.list entry misspelt?)
```

**Comment by mechanomi** [comment]
I did some investigation into this issue with @proddata on Slack. here's what I found:

the https://cdn.crate.io/downloads/deb/stable/dists/bionic/InRelease file only lists the amd64 packages. there's no mention of the source packages, despite them (apparently) being available if you browse the APT repository directly (see https://cdn.crate.io/downloads/deb/stable/dists/bionic/main/)

my guess is that at some point, a command has been run to update the APT repo that has caused it not to advertise the source packages any more. fixing this should fix the issue

my suggested workaround for the time being is to remove the `deb-src` line from your `sources` file and see if that works. but I am not familiar with how CrateDB is packaged, so this might not work

**Comment by mechanomi** [comment]
also perhaps worth noting: from my previous experience managing an APT repo (many, many years ago) it was unfortunately quite easy to end up with an inconsistent state like this because (at the time--I am not certain it is still the same today) the management tooling did not clean up old files that were no longer being used/advertised. I distinctly remember having to completely rebuild the repo on a regular basis to work around that issue

**Comment by mechanomi** [comment]
unassigned myself because this needs someone from the distribution team to look at it. I'm afraid I can't help you any more than this surface level debugging!!

**Comment by kovrus** [comment]
@proddata seems like there is some bug in sources packaging. You can temporarily work around it by ignoring  `deb-src` or commenting it out in `/etc/apt/sources.list.d/crate-stable.list`.

**Comment by kovrus** [comment]
@proddata seems like there is some bug in sources packaging. You can temporarily work around it by ignoring deb-src or commenting it out in /etc/apt/sources.list.d/crate-stable.list.

**Comment by proddata** [comment]
closed by https://github.com/crate/crate-howtos/pull/253
