### ISSUE TITLE
Anomalous traffic using community edition

### ISSUE THREAD

**Issue by chicco785** [crate/crate#10645]
**CrateDB version**:

4.1.8 community versus enterprise

**Problem description**:

We created docker images for community version [1] and experienced an incredible increase of inter-node traffic compared to enterprise edition, so we have been wondering if between enterprise and community version of crate there is any difference that could cause that.

[1] https://github.com/orchestracities/crate-ce

**Comment by seut** [comment]
There shouldn't be any difference between CE and Enterprise.
Anything related in the logs?

**Comment by chicco785** [comment]
Nothing I could notice, really, and we are using the same configuration in both cases

**Comment by chicco785** [comment]
Any recommended way to "trace" better the issue?

**Comment by seut** [comment]
You could enable Recovery (https://github.com/orchestracities/crate-ce/blob/master/config/log4j2.properties#L16)  and Discovery (https://github.com/orchestracities/crate-ce/blob/master/config/log4j2.properties#L20) trace logs.

Could you maybe provide your used configuration?

**Comment by chicco785** [comment]
thx @seut 
at the moment we switched to enterprise, but we will create a test instance to with your log configuration.

here is the configuration we are using in our k8s cluster over aws:

```
    Command:
      /docker-entrypoint.sh
      -Cnode.name="$POD_NAME"
      -Ccluster.name=${CLUSTER_NAME}
      -Cnetwork.host="0.0.0.0"
      -Cdiscovery.seed_providers=srv
      -Cdiscovery.srv.query=_cluster._tcp.crate-crate.prod.svc.cluster.local
      -Ccluster.initial_master_nodes=crate-crate-0,crate-crate-1,crate-crate-2
      -Cgateway.recover_after_nodes=${RECOVER_AFTER_NODES}
      -Cgateway.recover_after_time=10s
      -Cgateway.expected_nodes=${EXPECTED_NODES}
      -Chttp.cors.enabled=true
      -Chttp.cors.allow-origin=*
      -Cpath.repo="/backup"
    State:          Running
      Started:      Tue, 13 Oct 2020 21:58:39 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1800m
      memory:  5Gi
    Requests:
      cpu:     300m
      memory:  2Gi
    Environment:
      CRATE_HEAP_SIZE:       3g
      EXPECTED_NODES:        3
      CLUSTER_NAME:          quantumleap
      RECOVER_AFTER_NODES:   3
      MINIMUM_MASTER_NODES:  2
      POD_NAME:              crate-crate-0 (v1:metadata.name)
```

while traffic seems lower lower than with community deployment, is still higher that what was there with version 3.x.
any significant changes between 3.x and 4.x that can increase significantly traffic? may this be related to table format?

**Comment by seut** [comment]
@chicco785 Could you describe a bit more what "incredible increase of inter-node traffic" means to you in numbers? Also what kind of traffic increased, any insights?

> any significant changes between 3.x and 4.x that can increase significantly traffic? 
Since 4.0, CrateDB uses the Zen2 consensus implementation of Elasticsearch which slightly increase traffic on master election. Other than that, nothing really changed causing any traffic increase.
If master election does not succeed, ongoing retries could cause slightly more traffic, this could be also seen inside the logs.

> may this be related to table format?
No, the table format (do you mean the Lucene version?) should not be related.

**Comment by chicco785** [comment]
> @chicco785 Could you describe a bit more what "incredible increase of inter-node traffic" means to you in numbers? Also what kind of traffic increased, any insights?
> 
> > any significant changes between 3.x and 4.x that can increase significantly traffic?
> 
> Since 4.0, CrateDB uses the Zen2 consensus implementation of Elasticsearch which slightly increase traffic on master election. Other than that, nothing really changed causing any traffic increase.
> If master election does not succeed, ongoing retries could cause slightly more traffic, this could be also seen inside the logs.
> 
> > may this be related to table format?
> 
> No, the table format (do you mean the Lucene version?) should not be related.

@seut I meant the index format (at first we didn't migrate table format from crate 3.x to crate 4.x) actually, now we did, and it seems it maybe related to that as well.

**Comment by amotl** [comment]
Dear @chicco785,

we wish you a happy new year and much success with FIWARE/QuantumLeap for 2021.

We are kondoing some of our open issues and currently don't see any actionable item within this issue. Do you mind if we close it? However, feel free to answer anytime if you get any more insights.

With kind regards,
Andreas.
