### ISSUE TITLE
integer overflow raised from SQL with math operations

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10648]
**CrateDB version**: 4.2.6

**Problem description**:

After upgrading from 4.1.8 to 4.2.6 I found some SQL was broken.
I found problem in mathematical operations.

**Steps to reproduce**:

`select 31*24*60*60*1000;`
>> **`ERROR: SQLParseException: integer overflow`**

`select CURRENT_TIMESTAMP - 31*24*60*60*1000;`
>> **`ERROR: SQLParseException: integer overflow`**

I found workaround:
`select CURRENT_TIMESTAMP - 31*24*60*60*1000::long;`
>> (all OK)

**Comment by mfussenegger** [comment]
This was one of the breaking changes in 4.2.0 that we had to make to fix issues as [this one](https://github.com/crate/crate/issues/9652)

From the release notes:

> - Numeric literals fitting into the ``integer`` range are now treated as
> ``integer`` literals instead of ``bigint`` literals. Thus a statement like
> ``select 1`` will return an ``integer`` column type. This shouldn't be an
> issue for most clients as the ``HTTP`` endpoint uses ``JSON`` for
> serialization and PostgreSQL clients usually use a typed ``getLong``.

> A consequence of this change is that arithmetic with literals used in
> statements will also happen within the ``integer`` range, and it can lead to
> an ``integer overflow`` if the result does not fit into the ``integer``
> range. For example, a calculation like ``365 * 24 * 60 * 60 * 1000`` needs to
> be explicitly cast into the ``bigint`` range to avoid an ``integer
> overflow``. This can be done like this: ``365::bigint * 24 * 60 * 60 *
> 1000``. If working with timestamps it is recommended to instead use the more
> readable ``interval`` type instead: ``'1 year'::interval``.

**Comment by shm-dmitry** [comment]
OK, thanks.
I read breaking changes, but did not expect it to work in this case.
Originally - `CURRENT_TIMESTAMP` is `long`, and I expected 2nd argument will auto-casted to `long`

**Comment by mfussenegger** [comment]
> Originally - CURRENT_TIMESTAMP is long, and I expected 2nd argument will auto-casted to long

This is not the case because the multiplications are evaluated before the subtraction. 

For your example Something like `select CURRENT_TIMESTAMP - '31 days'::interval;` or `select CURRENT_TIMESTAMP - '1 month'::month` should work.

**Comment by shm-dmitry** [comment]
@mfussenegger, thanks! I was not aware of this construction.
