### ISSUE TITLE
DML operations executes too long time after upgrading 4.1.8 -> 4.2.6

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10650]
**CrateDB version**: 4.2.6

**Problem description**:
I upgraded cluster 4.1.8 -> 4.2.6, and I see DML SQL queries executed infinite time.

Select - executes quickly

![Screenshot_20201012_182224](https://user-images.githubusercontent.com/19342331/95763580-e0808680-0cb7-11eb-9cbf-b5bbb817b368.png)

Delete - started and cant be finished.
![Screenshot_20201012_182438](https://user-images.githubusercontent.com/19342331/95763779-30f7e400-0cb8-11eb-8a24-2b81fe1dc26e.png)

I tried OPTIMIZE this table.
I tried CLOSE / OPEN this table.
I tried full cluster restart.
I tried re-create table.

A newly created test table - same result.

Nothing helps me.

**Comment by shm-dmitry** [comment]
I created test table, insert one row into it, tried to delete or update this table several times, and then drop table.
I `kill` all sessions from screen.
But they does not disappear.

![Screenshot_20201012_184254](https://user-images.githubusercontent.com/19342331/95765561-bda3a180-0cba-11eb-906a-8e7fedf8a9a4.png)

**Comment by mfussenegger** [comment]
Could you post the table schema and the cluster configuration including heap size settings?

I cannot reproduce the problem

**Comment by shm-dmitry** [comment]
Cluster config:
```
path.data: /opt/crate/data
path.repo: /opt/crate/repo

network.host: 0.0.0.0

node.name: "crate02"
node.master: true
node.data: true
node.attr.rack_id: 3data

cluster.routing.allocation.awareness.attributes: rack_id

discovery.seed_hosts:
    - crate00:4300
    - crate01:4300
    - crate02:4300
    - crate03:4300
    - crate04:4300

cluster.initial_master_nodes:
    - crate00
    - crate01
    - crate02
    - crate03
    - crate04

gateway.expected_nodes: 5
gateway.recover_after_nodes: 3

auth.host_based.enabled: false

cluster.name: ev

stats.enabled: true

psql.port: 5432

thread_pool.search.size: 100

```

Table in first screenshot
```
CREATE TABLE IF NOT EXISTS "doc"."catalog_favorites" (
   "added" TIMESTAMP WITH TIME ZONE,
   "catalog_id" TEXT,
   "is_active" BOOLEAN,
   "source" TEXT,
   "user_id" TEXT,
   "user_order" INTEGER,
   PRIMARY KEY ("catalog_id", "user_id", "source")
)
CLUSTERED INTO 6 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-1',
   refresh_interval = 10,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'ALL'
)
```

Thread dump in attach:
[threaddump.txt](https://github.com/crate/crate/files/5370220/threaddump.txt)

I downgraded to 4.1.8 (with particall data-loss), so I cant reproduce this at now.

My steps:

1. I have cluster with 5 nodes.
2. I upgrade one nodes and awaits for a `Health` back to `green`
3. Then I upgrade next node.
4. After 3-4 nodes was upgraded I saw this problem (maybe it appear and earlier - I dont sure), but... It was too later to stop :) and I thinked this tied with segment upgrading process.
5. After full cluster upgraded it goes to `readonly` state... All DML was frozed.
6. I execute next script for all tables. It took some time:
```
....
OPTIMIZE TABLE doc.catalog_favorites with (only_expunge_deletes = true);
OPTIMIZE TABLE doc.catalog_favorites with (upgrade_segments = true);
OPTIMIZE TABLE doc.catalog_favorites;
...
```
7. I hoped problem will be solved after script finished... But it was not helps.
8. At night I re-created cluster with downgraded version, restored last snapshot and apply changes using `COPY TO / COPY FROM` for a mandatory tables.

According to my observations at the time of the accident:
After full-cluster-restart system back to normal state for a 1-2 minute.

I used this test script as healthcheck: 
`CREATE TABLE test (x int);`
`INSERT INTO test (x) values (1);`
`DELETE FROM test;`

Then all reproduced (healthcheck script frozes on DELETE step) again.

Frozed operations: `DELETE` and `UPDATE`.
`SELECT`, `INSERT` and `DROP TABLE` works fine.
Session with `DELETE` and `UPDATE` could not be killed. (KILL 'xxx'; was finished successfully, returned classic message "2 rows affected", but actually changes nothing).
There was only one way to kill this sessions - node restart.

DELETE and UPDATE frozed on data-access only.
For empty table DELETE and UPDATE executes successfully.
There was no difference - what table/schema is used - it always reproduced.
There was also no difference what lucene version on index.

There no a difference on witch node I execute DML - it always frozed.

After cluster works in this mode for a some time - nodes began restarts.
At that moment `SELECT COUNT(*) FROM SYS.JOBS` showed 400-500 frozen SQLs.

It looks like a global lock acquired and was not released, but I was not found any in thread dump.

**Comment by seut** [comment]
@shm-dmitry Thank you for this information.
Additionally, could you please tell us on which version this table was created while running the 4.1.8 cluster?
```select version from information_schema.tables where table_name = 'catalog_favorites' ```

**Comment by shm-dmitry** [comment]
@seut 
```
upgraded: 4.1.8
created: 4.0.6
```

**Comment by seut** [comment]
@shm-dmitry Ok thanks. I forgot to ask for another important information, the lucene segments version:
```
select * from sys.segments where table_name = 'catalog_favorites'; 
```
Could you provide us this as well please?

**Comment by shm-dmitry** [comment]
@seut 
See in attach
[export.xlsx](https://github.com/crate/crate/files/5383602/export.xlsx)

**Comment by seut** [comment]
@shm-dmitry I cannot see any issues based on the information you provided nor can we reproduce this. We also have a test suite in place to validate rolling upgrades between minor versions (https://github.com/crate/crate-qa/blob/master/tests/bwc/test_rolling_upgrade.py)
Anything related inside the logs? Specially when the cluster goes into a `readonly` state, some logs should pop up including a reason for it.
