### ISSUE TITLE
Support for Aggregations on arrays

### ISSUE THREAD

**Issue by proddata** [crate/crate#10662]
**Use case**:
As a user  I want to use common aggregation functions like `min`,`max`,`avg`,`count`,`sum`, etc. on arrays in CrateDB without first unnesting those arrays (which can be to memory-intensive for tables with fairly large arrays).

_This is already possible using user defined functions, but can be cumbersome, as you need to implement those udfs for different data types one by one._

**Feature description**:

```SQL
SELECT array_max([1,2,3]); --> 3
SELECT array_min([1,2,3]); --> 1
```

Also it should be possible to use further aggregations on 
```SQL
SELECT MAX(array_max(array_column));
```

**Comment by mfussenegger** [comment]
Just to clarify, `array_max` and `array_min` in your example wouldn't be aggregation functions, but rather scalar functions, right?

Is performance the main concern?

**Comment by proddata** [comment]
good point ... yes I meant scalar functions.
That being said one could even think of expanding aggregation functions to handle numeric arrays 🤔 

---

not necessarily performance
something like 
```sql
SELECT MAX(UNNEST(values)) FROM table;
``` 
with `values` being a column of a numeric array type, is of course not possible.

You either would need a sub select
```sql
SELECT MAX(unnested_values) FROM
(SELECT UNNEST(values) as unnested_values FROM table) t;
```
which can't be used in generated columns. And from what I remember I had some memory trouble with bigger tables and large arrays, resulting in errors.

or use a udf
```sql
SELECT MAX(udf_array_max(values)) FROM table;
```
which also seem to be faster, than the unnest route

---

so in theory udfs are fine and directly baking it in would be more a convenience thing.

**Comment by AlexDelPab** [comment]
Also need the ability to sum all values of an array and then call another aggregate function on that result for sliding windows.

**Comment by jayeff** [comment]
Recent additions of array functions:

* `array_to_string` https://github.com/crate/crate/pull/11308
* `array_min` / `array_max` https://github.com/crate/crate/pull/11314
* `array_sum` https://github.com/crate/crate/pull/11336
