### ISSUE TITLE
Rethinking the ingestion and discharging subsystem

### ISSUE THREAD

**Issue by amotl** [crate/crate#10668]
Dear people of CrateDB,

first things first: Thank you so much for your excellent work conceiving and maintaining CrateDB.

I recognized that a generic ingestion subsystem has been added to CrateDB core through #6046, #6059, #6061, #6073, #6100, #6139, #6209, #6217, #6256 and #7458 the other day, with specific implementations for MQTT and Azure Event Hubs as source elements, CrateDB being the sink. However, it has been removed again through #8096, #8150, #8256 and #8307. I am not voting to bring it back, but rather to think about it again from a distance and share some thoughts about it.

Also, others have signaled respective interest within #6945, #7241 and #7459. As it accidentally happened to me to get my hands dirty with Kafka just recently, I would like to start the discussion around that.

While @mfussenegger recommended to use [kafka-connect-jdbc](https://docs.confluent.io/current/connect/kafka-connect-jdbc/), I would like to emphasize this is only the half side of the story when looking at a full blown and efficient Kafka Connector. Specifically, I am looking at the **source connector** here:

> Data is loaded by periodically executing a SQL query and creating an output record for each row in the result set.
>
> -- https://docs.confluent.io/current/connect/kafka-connect-jdbc/source-connector/

On the other hand, things like [Kafka Connect for Azure Cosmos DB](https://github.com/microsoft/kafka-connect-cosmosdb) and the [MongoDB Kafka Connector](https://github.com/mongodb/mongo-kafka) implement their source connectors by subscribing to the update feed of the database in order to publish this data to a Kafka topic without having to poll the database.

This resonates well with two other discussions within #1376 and #2822 about the ability to push query results or any changes to database records back to any registered clients, essentially implementing SQL TRIGGERS and LISTEN/NOTIFY.

@mfussenegger's comment at https://github.com/crate/crate/issues/1376#issuecomment-496214639 is definitively a good argument when other event-driven system components are around, which is common within ingest-only IoT-like use cases. However, I still see different use cases like [3]. Considering it will take a significant amount of effort to implement this, I am not expecting any wizardry. But maybe it will be worth to reconsider for the 5.x.x release series?

With kind regards,
Andreas.

[1] https://github.com/microsoft/kafka-connect-cosmosdb/blob/dev/doc/README_Source.md
[2] https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed
[3] https://devblogs.microsoft.com/cosmosdb/change-feed-unsung-hero-of-azure-cosmos-db/
[4] https://docs.mongodb.com/kafka-connector/current/kafka-source/
[5] https://docs.mongodb.com/manual/changeStreams/

**Comment by mfussenegger** [comment]
Thank you for the feedback.

As you've already mentioned, the functionality that we added and later removed was primarily concerned with CrateDB being used as **sink**, not as source.


We still see [3] as a use case and some kind of data change feed system or [sql triggers and listen/notify (1376)](https://github.com/crate/crate/issues/1376) is still something we want to do eventually.


However, we also primarily see simpler pipelines in the form of 

```
Kafka/EventHub  → Some enrichment → CrateDB
```


More complex systems like

```
Kafka/EventHub  → enrichmentA → CrateDB → enrichmentB → CrateDB
                                                     (→ Kafka again)
```

Are not that common. And in many cases it would be better to re-design them to be closer to the first variant.

Still, there are cases where a change feed would be immensely helpful and that's why we still have it on the roadmap.

**Comment by mfussenegger** [comment]
Going to close this and consider https://github.com/crate/crate/issues/1376 as the authoritive "change data capture" issue.
