### ISSUE TITLE
Add sys check for number of shards to warn about cluster.max_shards_per_node limit

### ISSUE THREAD

**Issue by jayeff** [crate/crate#10741]
**Use case**:

As a CrateDB user I want to be warned before I reach the cluster.max_shards_per_node limit so that I can take preventive actions.

**Feature description**:

Once the cluster.max_shards_per_node limit is reached no new partitions can be created and a SQLParseException is thrown. Especially for tables partitioned on timestamps new partitions are usually created in the middle of the night.

To increase visibility and enable easier monitoring of this potential production problem I suggest we add a cluster health check which turns the status to warning once a certain threshold is reached.

Probably something similar to [NumberOfPartitionsSysCheck](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/expression/reference/sys/check/cluster/NumberOfPartitionsSysCheck.java#L35) would be useful.

**Comment by mfussenegger** [comment]
Not sure if checks are the right thing for monitoring or alerting. At least not alone.
But I guess this related a bit to https://github.com/crate/crate/issues/10371 - which is about exposing the number of shards per JMX

**Comment by jayeff** [comment]
I agree, exposing the raw number of shards per JMX would be the better solution for monitoring&alerting.

Regarding discoverability of potential issues adding a cluster health check warning/error is potentially still helpful as CrateDB users maybe aren't aware of all things which should be monitored.

**Comment by mkleen** [comment]
The raw number of stats are already exposed by jmx https://github.com/crate/crate/commit/e10337a630c19d6a6d235f4d4a15b15948083679 Do we need another syscheck here ?

**Comment by mkleen** [comment]
What would be a good behavior for the check ? It should be probably have some sort of threshold. When a certain percentage of the maximum number of shards is reached the check should move to invalid. Should it be configurable or set to a fixed value e.g. 80 % ?

**Comment by jayeff** [comment]
@mkleen IMO I think 85% - 90% for yellow status would be appropriate. I'm unsure if we need a red status for this check. Probably useful if it's configurable as well.

On a related note:  I believe we could remove [`NumberOfPartitionsSysCheck`](https://github.com/crate/crate/blob/141189c5447f2b2fada0478cf1e36d12a23dca76/server/src/main/java/io/crate/expression/reference/sys/check/cluster/NumberOfPartitionsSysCheck.java#L34) when we close this issue.

The `NumberOfPartitionsSysCheck` indirectly warns about too much shards as well but uses number of partitions to determine number of shards. Currently triggers when numbers of partitions hits 1000.

> The total number of partitions of one or more partitioned tables should
> not be greater than 1000. A large amount of shards can significantly reduce performance.

This will never trigger on smaller clusters because default setting of `cluster.max_shards_per_node` will prevent creating more than 1000 partitions. On bigger clusters having 1000+ partitions would be fine when shards per node stays below 1000.

**Comment by mkleen** [comment]
@jayeff great, thanks a lot for this input.
