### ISSUE TITLE
casting a 'timestamp without timezone' into a 'bigint' and query with npgsql

### ISSUE THREAD

**Issue by at-besa** [crate/crate#10785]
**CrateDB version**:
4.2.4 (self hosted) and 4.3.1 (azure hosted)

**Problem description**:
We are using the npgsql driver (5.0.0) for ASP.NET Core 5, and if i want to do following:
`SELECT _cast(created, 'bigint') as time FROM mytable`
The column created is from type: `TIMESTAMP WITHOUT TIME ZONE` 

But the result datatype of the column 'time' is string, according to the cast and the npgsql documentation it should be int64 (long)
[https://www.npgsql.org/doc/types/basic.html](https://www.npgsql.org/doc/types/basic.html)

I also tried it with the previous version of the npgsql driver 4.1.4, the same thing happens. I therefore assume its not a problem of the driver, its the resulting datatype of the column itself. If i would not do the cast the representation datatype of thies field would be DateTime, which is ok but most likely bad to calculate with. If i would convert the column afterwards its pretty "complicated" and shows up a bad performance:
`long time = new DateTimeOffset((DateTime)row["time"]).ToUnixTimeMilliseconds();`
this would create a new object for each entry in the table, as its not possible to directly cast or convert the row in a different way (as far as i know).

the documentation show that the internal representation of timestamp is bigint, so the cast should work perfect:
[https://crate.io/docs/crate/reference/en/4.3/general/ddl/data-types.html#timestamps](https://crate.io/docs/crate/reference/en/4.3/general/ddl/data-types.html#timestamps)

**Steps to reproduce**:
`CREATE TABLE IF NOT EXISTS "mytable" (
    "id" TEXT NOT NULL primary key,
    "created" TIMESTAMP WITHOUT TIME ZONE GENERATED ALWAYS AS current_timestamp);`

`INSERT INTO mytable(id) VALUES('veryspecialid');`

execute the following select as a DBCommand like done in this example:
[https://www.npgsql.org/doc/index.html](https://www.npgsql.org/doc/index.html)
`SELECT _cast(created, 'bigint') as time FROM mytable`

**Comment by proddata** [comment]
it seems like casting with `::` works as expected 
maybe you can use that as work-around till this is fixed
```sql
SELECT created :: bigint as time FROM mytable```

**Comment by mfussenegger** [comment]
Functions prefixed with `_` are considered internal and shouldn't be used.
In this case, `_cast` acts as a "soft" cast, that only does something if really required.
How did you become aware of this function?



As already pointed out by @proddata, to do proper casts you have to use the `::` syntax or the `CAST` function:

```sql
SELECT
    cast(created AS bigint),
    pg_typeof(cast(created AS bigint)),
FROM
    mytable;
```

**Comment by at-besa** [comment]
the :: works like a charm. We will use this for the npgsql querys.
i became aware of the function because casts of an autogenerated column are shown in the management ui with the _cast operator, like thown in this screenshot:
[https://imgur.com/a/hsX8tex](https://imgur.com/a/hsX8tex)
