### ISSUE TITLE
Performance regression for normal select with order by

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10816]
![image](https://user-images.githubusercontent.com/38700/100232910-4c961180-2f29-11eb-881f-f35f4f7e398e.png)

I think around that time we updated Lucene.
We should investigate this before the 4.4 release.

Running the benchmark case from [crate-benchmarks](https://github.com/crate/crate-benchmarks) with git bisect as described [here](https://github.com/mfussenegger/cr8#find-regressions) may be a good option to find the commit that introduced the regression.

**Comment by mfussenegger** [comment]
Some regex queries got slower around the same time:


![image](https://user-images.githubusercontent.com/38700/100233972-b82cae80-2f2a-11eb-9051-342c3e3ade2e.png)

**Comment by mkleen** [comment]
This regression was introduced by upgrading to the new lucene version (https://github.com/crate/crate/pull/10740) Lucene 8.7.0 compresses more aggressively to optimize for retrieving stored fields for random access and sacrifies that with the performance in ordered retrieval. Related pr/issues from elasticsearch: 

https://github.com/elastic/elasticsearch/issues/62024
https://github.com/elastic/elasticsearch/pull/62509
