### ISSUE TITLE
Ability to backup and restore custom cluster metadata

### ISSUE THREAD

**Issue by chaudum** [crate/crate#10822]
**Use case**:

In case of a cluster failure I would like to be able to restore custom cluster metadata from a backup.

This includes metadata such as:

* VIEWS
* USERS (sys.users)
* PERMISSIONS (sys.privileges)
* UDFs
* ANALYZERS

**Feature description**:

A possible way would be to always include the metadata in snapshots, and be able to add a keyword in the `RESTORE SNAPSHOT` statement, e.g. `RESTORE SNAPSHOT repository_name.snapshot_name METADATA WITH (...)`, additionally to `TABLE` and `ALL`. Alternatively every metadata kind has its own keyword, such as `VIEWS`, `USERS`, etc.

**Comment by seut** [comment]
@chaudum We've implemented this by https://github.com/crate/crate/pull/11149 which will be part of the next 4.5 release.
Thank you for this great feature request and description.
