### ISSUE TITLE
Drop object names from returned column name when querying objects' fields

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#10834]
**Use case**:
Querying an object's fields returns its object name as part of the returned column name. 
Sometimes it is confusing, like the case below that you need to re-specify the objects name:
```SQL
create table tbl (col object(strict) as (nested_col text));
select col['nested_col'] from (select col['nested_col'] from tbl) as A;
+-------------------+
| col['nested_col'] |
+-------------------+
+-------------------+
```
Also, it is necessary, in order to be able to do something like :
```SQL
cr> create table cpy as select col['nested_col'] from tbl;
CREATE OK, 0 rows affected  (2.616 sec)
cr> select * from cpy;
+------------+
| nested_col |
+------------+
+------------+
```
This is the current Posgres behaviour :
```SQL
postgres=# select * from (select (col).r,(col).i from tbl) as A;
 r | i 
---+---
(0 rows)
```

**Feature description**:
the idea is to be able to:
```SQL
create table tbl (col object(strict) as (nested_col text));
select nested_col from (select col['nested_col'] from tbl) as A;
+------------+
| nested_col |
+------------+
+------------+
```

**Comment by mfussenegger** [comment]
Currently you've to use an alias to change the column name manually. In your example you'd probably want to use something like this:

```sql
create table cpy as select col['nested_col'] as nested_col from tbl;
```

Changing this would be a major breaking change, and I'm not if it is warranted.

**Comment by mfussenegger** [comment]
Closing this as wontfix for now. There hasn't been any other interesting and it would be a breaking change.
