### ISSUE TITLE
Partitions by value in web console

### ISSUE THREAD

**Issue by alexanderjarvis** [crate/crate#1085]
Just a quick feature suggestion:

It could be useful if the partitions which are shown in the tables view of the admin web console showed the value of the partition. For example instead of the Ident string '043j2d1g6go3g' which is used internally by Crate if it displayed the value of that partition (and be able to sort by value/ident) that would be useful.

At the moment I have a good idea of which a partition is because you can already sort by Ident but it's not particularly easy to identify a partition in the middle of the table where you have a partition for each day in time series data.

Other than this suggestion I just want to say that it's really great to see the visibility of each partition as it allows you to see the data growth per day for a particular table (if partitioned by day of course).

Thanks,
Alex

**Comment by chaudum** [comment]
this feature is being implemented since version `0.50.0`
see: https://github.com/crate/crate/blob/master/CHANGES.txt#L479-L480
