### ISSUE TITLE
restore snapshot with multiple partition provided restore only last partition in the list

### ISSUE THREAD

**Issue by WalBeh** [crate/crate#10868]
**CrateDB version**:
4.2.7

**Environment description**:
7 Node cluster (cloud deployment)

**Problem description**:
Running 
```sql
restore snapshot "repo"."snapshot1" table doc.sample PARTITION (
 g_ts_month = '1585699200000', 
 g_ts_month = '1588291200000',
 g_ts_month = '1590969600000',
 g_ts_month = '1593561600000',
 g_ts_month = '1596240000000',
 g_ts_month = '1598918400000',
 g_ts_month = '1601510400000',
 g_ts_month = '1604188800000'
) with (wait_for_completion = true);
```
completes, but does **only** restore the **last** partition from the command. In my case `1604188800000`. The other partitions are not restored. After looking at the documentation I think this should have restored all partitions provided.

regards,
Walter

**Comment by seut** [comment]
As stated here https://crate.io/docs/crate/reference/en/4.3/sql/statements/restore-snapshot.html#synopsis, the correct synopsis for restoring multiple partitions is
`TABLE <table_name> PARTITION (parted_col1=..., parted_col2=..., ...), <table_name> PARTITION (...), ...`.

So in your case the correct syntax is:
```
restore snapshot "repo"."snapshot1" table 
  doc.sample PARTITION (g_ts_month = '1585699200000'), 
  doc.sample PARTITION (g_ts_month = '1588291200000'),
  doc.sample PARTITION (g_ts_month = '1590969600000'),
  doc.sample PARTITION (g_ts_month = '1593561600000'),
  doc.sample PARTITION (g_ts_month = '1596240000000'),
  doc.sample PARTITION (g_ts_month = '1598918400000'),
  doc.sample PARTITION (g_ts_month = '1601510400000'),
  doc.sample PARTITION (g_ts_month = '1604188800000')
) with (wait_for_completion = true);
```
