### ISSUE TITLE
COPY TO with upper case column names adds extra double quotes

### ISSUE THREAD

**Issue by jayeff** [crate/crate#10875]
**CrateDB version**: tested against 4.3.2 & current master

**Problem description**:

When using [`COPY TO`](https://crate.io/docs/crate/reference/en/4.3/sql/statements/copy-to.html) on tables with columns with upper case letters and `column` parameter defined the JSON includes unwanted escaped double quotes (e.g.: `"\"Name\"":"FOO"`)

**Steps to reproduce**:

```
DROP TABLE IF EXISTS copy_test;
CREATE TABLE IF NOT EXISTS copy_test ("Name" STRING, "Name_lower" GENERATED ALWAYS AS lower("Name"), "address" STRING) CLUSTERED INTO 1 SHARDS;
INSERT INTO copy_test ("Name", "address") VALUES ('FOO', 'bar');
REFRESH TABLE copy_test;
```

**These produce unwanted escaped double quotes**

```
COPY copy_test ("address", "Name", "Name_lower", "_id") TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"address":"bar","\"Name\"":"FOO","\"Name_lower\" AS lower(\"Name\")":"foo","_id":"zlQfhHYBk0sDoCvU5lso"}
```

```
COPY copy_test ("Name") TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"\"Name\"":"FOO"}
```

**These work as expected**

```
COPY copy_test ("address") TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"address":"bar"}
```

```
COPY copy_test TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"address":"bar","Name_lower":"foo","Name":"FOO"}
```

Thanks to @amotl for supporting me with investigating this issue 🙏

**Comment by proddata** [comment]
also seen, but not mentioned:
generated columns get exported as `"example AS  func(col2)"`
should be `"example"` imho

---

```sql
CREATE TABLE t1 (example GENERATED ALWAYS AS func(col2), col2 TEXT)
```

**Comment by seut** [comment]
Thank you for the detailed report, we can reproduce this bug.

**Comment by jayeff** [comment]
@seut As @proddata mentioned generated columns are also affected. I included it in the example but didn't highlight it specifically. 

```
COPY copy_test ("Name_lower") TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"\"Name_lower\" AS lower(\"Name\")":"foo"}
```

If you use of of the [reserved key words](https://crate.io/docs/crate/reference/en/4.3/sql/general/lexical-structure.html#key-words-and-identifiers) you also get the extra escaped double quotes.

```
COPY copy_test ("desc") TO DIRECTORY '/Users/johannes/temp/copy/' WITH (format='json_object');

Output:
{"\"desc\"":"short"}
```

Can you check if these cases are already covered by your PR #10878?

**Comment by seut** [comment]
> Can you check if these cases are already covered by your PR

Yes it does, see https://github.com/crate/crate/pull/10878/files#diff-b76fcdb970980667239add295cecd68bf96f26660c6210f294e5e60028d43240R378.

**Comment by jayeff** [comment]
Thanks @seut. Again impressive cycle time from issue report to fix merged 🚀
