### ISSUE TITLE
Folder wildcard support for `COPY FROM` s3

### ISSUE THREAD

**Issue by jayeff** [crate/crate#10915]
**Use case**:

As a CrateDB user I want to copy data from all files in multiple folders in S3 with a single `COPY FROM` command into CrateDB.

**Feature description**:

> We have the following s3 folders structure with files: bucket/year=2020/month=[1-12]/day=[1-31]/hour=[1-24]/file[N].gz.
> I want to copy all files for example from bucket/year=2020/month=12/ folder using one command

Wildcard works for filenames: ```COPY target FROM 's3://{aa:bb}@bucket/year=2020/month=12/day=10/hour=12/*.json```

It would be great if CrateDB could support wildcards for folder names as well.

`COPY FROM` with `file` already supports `*` wildcard for folder names (but this is undocumented behaviour):
```COPY target FROM '/temp/*/*.json```

**Comment by mfussenegger** [comment]
I think the core logic for this would be in 

https://github.com/crate/crate/blob/42feeb35823918a5f7b4411184dbe7bd355f8ebc/server/src/main/java/io/crate/execution/engine/collect/files/S3FileInput.java#L54-L70

**Comment by jeeminso** [comment]
@jayeff Hello Johannes, with my change, folder level wildcards should work for both S3 and file scheme and they are documented as well. I would much appreciate if you could help confirming whether my change behaves as expected. Thank you

**Comment by jeeminso** [comment]
@jayeff Hi Johannes, thanks for helping. Have you had a chance to look?

**Comment by jeeminso** [comment]
performed some manual testing, details provided in the issue resolving this.
