### ISSUE TITLE
Improve sharding section, mention `number_of_routing_shards` setting

### ISSUE THREAD

**Issue by seut** [crate/crate#10989]
###  Documentation feedback

 
- Page title: Sharding
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/ddl/sharding.html
- Source: https://github.com/crate/crate/blob/4.4/docs/general/ddl/sharding.rst

---

The sharding section mentions that the shard size can be changed later on. But this is only possible if the setting `number_of_routing_shards` was set on initial table creation and has a multiple value of the number of shards setting.

This is currently only mentioned a bit hidden inside the [Increase Shards](https://crate.io/docs/crate/reference/en/4.4/general/ddl/alter-table.html#increase-the-number-of-shards) documentation.

**Comment by amotl** [comment]
Hi. If this is a common or occasional pitfall, it might satisfy putting that documentation snippet into an `.. admonition` or `.. attention` directive in order to highlight this better.
