### ISSUE TITLE
Feature request regex in where clause

### ISSUE THREAD

**Issue by megastef** [crate/crate#1098]
I would love to see the possibility to include in a where clause in update statement the possibility to use a regular expression applied to the _source field (not to the index, like in Elasticsearch). The action would run distributed in the CRATE cluster.

e.g. something like this
```
update traffic_log set appname = 'Facebook' where host matches "/.*\.facebook\.\w{2-6}/"
```

Even better would be to create field values dynamically by using regex parameter extraction
```
update traffic_log set user = '$1' where url matches "/login=(.+)/"
```
That would be a big step forward in our data enrichment solutions, which currently query, collect/extract new data and update in a separate action. 

The background is that we got already a collection of regular expression. In case we move that to CRATE we would need to define "like" searches instead of Regex (the above is a simple example) - or continue with a separate matching engine.

**Comment by seut** [comment]
@megastef 
We've now implemented support for using column references inside update statement, it's already in our master repo.
So your example use-case can be achieved by:
```
update traffic_log set user = regexp_matches(url, 'login=(.+)')[1] where url like '%login=%';
```

Or, if you'd prefer regex over LIKE (but as @dobe mention, LIKE is much faster):
```
update traffic_log set user = regexp_matches(url, 'login=(.+)')[1] where url ~ '.*login=(.+)');
```

This feature will be released within our next major release.

**Comment by otisg** [comment]
@seut - what is happening at the Lucene level when this sort of update statements are run?  Docs get deleted and re-added with new fields?

**Comment by seut** [comment]
@otisg Assignments are evaluated outside of Lucene and then the whole updated document is sent to Lucene's update api including the document version the assignment evaluation was operating on. If a version conflict occurs, we retry the whole operation(fetch doc, evaluate assignments, update doc) up to 3 times before a version conflict exception is raised to the user.

**Comment by megastef** [comment]
Hi, forgot to give feedback on this. :star2::star2::star2::star2::star2:

```
insert into log1 (url) values ('http://server?login=stefan')
update log1 set user = regexp_matches(url, 'login=(.+)')[1] where url like '%login=%';
select * from log1 limit 100;
```
![bildschirmfoto 2015-04-29 um 21 02 31](https://cloud.githubusercontent.com/assets/7289505/7399008/18ee6222-eeb3-11e4-946f-b5b869e2dc3f.png)
