### ISSUE TITLE
Improve regression testing for CrateDB

### ISSUE THREAD

**Issue by amotl** [crate/crate#11019]
Hi there,

we are currently looking into how we can improve regression testing for CrateDB. While we are maintaining a comprehensive suite of test cases already, we can always do better in order to increase coverage on all ends.

As a quick overview, there is
- the test suite which is integrated into the main code base [1].
- a benchmark test suite used to compare performance between different CrateDB versions [2].
- a QA-style test harness [3] which runs integration tests using different clients of CrateDB. It also includes the comprehensive logictest suite of SQLite [4].
- different test cases on behalf of various subprojects on the `crate` organization [5], like `crash`, `crate-python`, `crate-jdbc`, `crate-npgsql` and so forth.

The best thing would be to extend those test cases by integrating test suites of different downstream projects implementing real world usage scenarios. On this matter, it would be perfect if those projects would include the nightly releases of CrateDB into their CI test matrix, either by reaching out to the nightly tarballs [6] or by using the Docker image `crate/crate:nightly` [7].

So, we want to humbly encourage all people and organizations using CrateDB to collaborate on this matter. We will be happy to help.

With kind regards,
Andreas.

[1] https://github.com/crate/crate/tree/master/server/src/test
[2] https://github.com/crate/crate-benchmarks
[3] https://github.com/crate/crate-qa
[4] https://sqlite.org/sqllogictest
[5] https://github.com/crate
[6] https://cdn.crate.io/downloads/releases/nightly/
[7] https://hub.docker.com/r/crate/crate

**Comment by mfussenegger** [comment]
Closing this as it was only for information and there is no actionable item for us.
