### ISSUE TITLE
Support for named PRIMARY KEY constraints

### ISSUE THREAD

**Issue by proddata** [crate/crate#11025]
**Use case**:
PostgreSQL allows not only `CHECK` constraints, but also `PRIMARY KEY` constraints to be named.
This is not totally obvious from the PostgreSQL docs [1], but is used by e.g. Thingsboard [2].

**Feature description**:

e.g. the following is valid pgsql syntax:
```sql
CREATE TABLE t (
    txt TEXT,
    CONSTRAINT txt_pk PRIMARY KEY(txt)
);
```
however leads to an error within CrateDB
`[XX000] ERROR: line 3:23: mismatched input 'PRIMARY KEY' expecting 'CHECK'`

---

Currently only non-named `PRIMARY KEY` constraints are supported
```sql
CREATE TABLE t (
    txt TEXT,
    PRIMARY KEY(txt)
);
```

[1][https://www.postgresql.org/docs/13/ddl-constraints.html](https://www.postgresql.org/docs/13/ddl-constraints.html)
[2][https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/sql/schema-entities.sql](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/sql/schema-entities.sql)

**Comment by proddata** [comment]
Also [TypeORM](https://typeorm.io/#/) uses named primary key constraints.

**Comment by hlcianfagna** [comment]
This is also used by Entity Framework Core

**Comment by amotl** [comment]
Hi. @andnig and me also discovered this when attempting to run [MLFlow] with CrateDB, which uses SQLAlchemy to submit corresponding SQL DDL statements.

- https://github.com/crate/crate-python/issues/573#issuecomment-1706887556

[MLFlow]: https://mlflow.org/
