### ISSUE TITLE
[Bug] NULL is returned instead of 0 on max-aggregation with docs of value 0 only

### ISSUE THREAD

**Issue by proddata** [crate/crate#11056]
**CrateDB version**:
4.4.1

**Environment description**:
CrateDB Cloud

**Problem description**:
NULL is returned instead of 0 on max-aggregation with docs of value 0 only

**Steps to reproduce**:

```sql
CREATE TABLE t1 (
    x TEXT,
    y DOUBLE PRECISION
);

INSERT INTO t1 VALUES ('a',0),('a',0),('a',0),('b',1),('b',1),('b',1),('c',0),('c',1),('b',2),('b',3);

SELECT x, y FROM t1;
```
![image](https://user-images.githubusercontent.com/23557193/108847622-3529fb80-75e0-11eb-82c4-3dd476fc0de8.png)

```sql
SELECT x, MAX(y) FROM t1 GROUP BY x;
```
![image](https://user-images.githubusercontent.com/23557193/108847572-25121c00-75e0-11eb-9654-213502832c72.png)

**Comment by mfussenegger** [comment]
Thank you for the report and reproduction steps. This will be fixed with the next 4.4 release.
