### ISSUE TITLE
INNER JOIN with empty (system) table gets stuck

### ISSUE THREAD

**Issue by amotl** [crate/crate#11089]
See https://github.com/crate/crate/issues/11089#issuecomment-789909334

---

Hi there,

while working on [`crate-admin`](https://github.com/crate/crate-admin) with CrateDB 4.5.0-SNAPSHOT, I found a minor issue when Admin UI inquires the number of shards available.

Admin UI expects a zero-length result to display a `There are no shards.` message. However, CrateDB returns a result with one record. I will outline the query that is used and the outcome with an example using [`crash`](https://github.com/crate/crash).

```
cr> SELECT 
  shards.id, table_name, schema_name, partition_ident, state, primary, format('%s.%s', schema_name, table_name) AS fqn, 
  format('%s.%s.%s', schema_name, table_name, partition_ident) AS key, 
  nodes.id AS node_id, nodes.name AS node_name 
FROM sys.shards RIGHT JOIN sys.nodes AS nodes ON shards.node['id'] = nodes.id 
ORDER BY key, node_id, shards.id;

+------+------------+-------------+-----------------+-------+---------+-----------+----------------+------------------------+--------------------+
|   id | table_name | schema_name | partition_ident | state | primary | fqn       | key            | node_id                | node_name          |
+------+------------+-------------+-----------------+-------+---------+-----------+----------------+------------------------+--------------------+
| NULL |       NULL |        NULL |            NULL |  NULL |    NULL | null.null | null.null.null | pB4UJax7Q8edYiwpzCU1iw | Großer Rettenstein |
+------+------------+-------------+-----------------+-------+---------+-----------+----------------+------------------------+--------------------+
```

Should the query be amended in some way or is this something which might be improved within CrateDB itself?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Thank you very much for your suggestion to use an inner join here. After trying that like
```sql
SELECT 
  shards.id, table_name, schema_name, partition_ident, state, primary, format('%s.%s', schema_name, table_name) AS fqn, 
  format('%s.%s.%s', schema_name, table_name, partition_ident) AS key, 
  nodes.id AS node_id, nodes.name AS node_name 
FROM sys.shards INNER JOIN sys.nodes AS nodes ON shards.node['id'] = nodes.id 
ORDER BY key, node_id, shards.id;
```

I would like to report back that this query never returns (freezes) on an empty database, i.e. a freshly started instance of CrateDB.

**Comment by mfussenegger** [comment]
@amotl Looks like there is a planner bug. I'll try to come up with a fix.

Meanwhile you might want to change the query and remove the join altogether. The columns used from `sys.nodes` are both already part of `sys.shards` (There is `node['id']` and `node['name']` in `sys.shards`)

I could imagine that the intention of the original left outer join was to also get the node name despite no shards being available, potentially to avoid making another dedicated `sys.nodes` query.

**Comment by amotl** [comment]
> Looks like there is a planner bug. I'll try to come up with a fix.

Thank you.

> Meanwhile you might want to change the query and remove the join altogether. The columns used from `sys.nodes` are both already part of `sys.shards` (There is `node['id']` and `node['name']` in `sys.shards`)

Sure, that sounds more than reasonable.

> I could imagine that the intention of the original left outer join was to also get the node name despite no shards being available, potentially to avoid making another dedicated `sys.nodes` query.

That might well be the case, see the attached screenshot. However I believe it will do no harm to only display this when shards actually have been created. The node name can be inspected on Admin UI's "cluster view" even on empty clusters without any tables.

---

![image](https://user-images.githubusercontent.com/453543/110496916-443b9e00-80f6-11eb-80fa-243652d15730.png)
