### ISSUE TITLE
Grant users read access to pg_catalog by default

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#11111]
**Use case**:

PostgreSQL clients by default often query tables within the `pg_catalog` schema when a connection is established.

Currently if a user is created, the administrator might only think of granting privileges for schemas and tables created by users, and forget about `pg_catalog`.

The end result is that some clients work and others don't, which is not an ideal experience.
A good example of the weird behavior is the `current_schemas` scalar, which currently returns an error if the user lacks permission:

```
MissingPrivilegeException[Missing privilege for user 'dummy']
```

**Feature description**:

Any user should be able to query tables in the `pg_catalog` table.
But we have to take care that the users only see records they have permissions to see.

**Comment by proddata** [comment]
Probably also read permissions on `sys`-tables should be within the default privileges.

e.g. if a user has read (DQL) privileges on a specific table and uses **crash** to connect, the user gets greeted by
```io.crate.exceptions.SchemaUnknownException: Schema 'sys' unknown``` 😟

**Comment by jeeminso** [comment]
I am going to work on this issue and will focus on the first part, regarding pg_catalog to begin with.

Just to confirm, we are not trying to grant DQL automatically, instead to bypass the privileges mechanism so that it cannot be revoked nor show up on queries like `select * from SYS.PRIVILEGES`.

**Comment by jeeminso** [comment]
> e.g. if a user has read (DQL) privileges on a specific table and uses **crash** to connect, the user gets greeted by
> `io.crate.exceptions.SchemaUnknownException: Schema 'sys' unknown` worried

Hello @proddata, I am trying to reproduce this behaviour.

```SQL
cr> create user newuser;
CREATE OK, 1 row affected  (0.038 sec)
cr> grant dql on table sys.cluster to newuser;
GRANT OK, 1 row affected  (0.029 sec)

$ crash -U newuser; 
CONNECT OK
```
If I understand you correctly, I should see an exception not `CONNECT OK` ? 
Thanks

**Comment by proddata** [comment]
@jeeminso 
I meant, that if you give a user only permission to a certain schema like 
```sql
cr> GRANT DQL ON SCHEMA myprivateschma to newuser;
```

you explicitly have to also set `DQL` on `sys.cluster`, otherwise you get the exception with `crash`.

**Comment by seut** [comment]
@proddata 
I also cannot reproduce the issue with `crash` with a fresh user which has no additional privileges.

```
cr> create user user1 with (password = 'foo');
CREATE OK, 1 row affected  (0.038 sec)

$ crash -U user1
Password: 
CONNECT OK
```

This behaviour also reflects the code at `crash` https://github.com/crate/crash/blob/master/crate/crash/command.py#L412.
So a user does not need to have any privileges on `sys.cluster` to connect with `crash`.

Granting access to the `sys` schema or only to `sys.cluster` to any user by default would leak system/cluster information.

**Comment by seut** [comment]
So lets close this issue as it also was explicitly about `pg_catalog` privileges and this is already solved by #11282.
Please create a dedicated issue related to the `sys` schema or tables if there is still a use-case for that. But I think rather than open up anything in that direction, issues should handled elsewhere like e.g. at  `crash`.

**Comment by proddata** [comment]
@seut fine with me :)
I just realised, that the exception is only shown, when the verbose flag `-v` is set within **crash**

i.e.
```
$ crash -U user1 -v
```

**Comment by seut** [comment]
@proddata Ok thanks for that info. Not sure why `crash` wants to access `sys` in that case, we should follow up here and get the concrete query `crash` is using in that case. And based on that decide how we'll tackle this.

**Comment by seut** [comment]
`crash` issues following queries against the `sys` schema when used with `-v` (verbose):

```
 SELECT description AS "Failed Check"
        FROM sys.checks
        WHERE passed = false
        ORDER BY id ASC
```

```
SELECT description as "Failed Check", count(*) as "Number of Nodes"
        FROM sys.node_checks
        WHERE passed = false
          AND acknowledged = false
        GROUP BY description
        ORDER BY description asc
        ``` 
        
As the result of these queries also leak cluster/node information, instead of letting any user access it, I suggest we should patch crate to print meaningful information instead of the `SchemaUnknownException`.

**Comment by mfussenegger** [comment]
> As the result of these queries also leak cluster/node information, instead of letting any user access it, I suggest we should patch crash to print meaningful information instead of the SchemaUnknownException.

I wonder if we should open up parts of `sys` by default as well. Some thoughts:

- It's weird that users get a `Schema sys is unknown` error if they lack the permission - the system schema is documented, so users know that it has to exist.
- Consistency with `information_schema` and `pg_catalog` (→ Treat all system schemas the same)
- `sys.shards` contains information related to tables the user has access to. Currently the user can either gain permission on the whole table with `DQL` privileges (seeing other users tables too) or none. There is no option for "only users records". Same for `sys.segments`. Downside is that the user would gain information about the cluster configuration (data path)

**Comment by seut** [comment]
> sys.shards contains information related to tables the user has access to. Currently the user can either gain permission on the whole table with DQL privileges (seeing other users tables too) or none. There is no option for "only users records". Same for sys.segments.

Yes I agree that it would be good an consistent to allow any user access to these tables, so the can get information out of tables they have access to. 

> Downside is that the user would gain information about the cluster configuration (data path)

I think that is a hard blocker, specially inside multi-tenant cluster, it could be a security issue to leak such information to any user.
