### ISSUE TITLE
Problems starting CrateDB on Windows

### ISSUE THREAD

**Issue by amotl** [crate/crate#11110]
@nkev reported at https://github.com/crate/crate/pull/11101#issuecomment-793505283:

- Page title: Quick Install on Windows
- Page URL: https://crate.io/docs/crate/tutorials/en/latest/install-run/windows.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/install-run/windows.rst

I'm not sure if this is relevant to this issue but I followed the instructions in URL above to install `crate-4.4.2` on Windows 10 but no matter what I do I get the error `JAVA_HOME environment variable must be set` The `JAVA_HOME` variable **is** set:

```BASH
PS C:\WINDOWS\system32> cd "C:\Users\me\Downloads\crate-4.4.2"
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2> $env:JAVA_HOME
C:\Program Files\Java\jdk-11.0.10
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate.bat
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2>
```
I tried restarting the computer and also tried `crate.bat` instead with the same result. What am I doing wrong?

_Originally posted by @nkev in https://github.com/crate/crate/issues/11101#issuecomment-793505283_

**Comment by amotl** [comment]
Hi Nuri,

recently, I investigated a problem around invoking `crate-node.bat` on Windows at #11101. For this purpose, I created a recipe about how to invoke CrateDB conveniently even when running on a Unix-like system [1].

By using that recipe, I was able to verify that running `crate.bat` worked without any issues. We will have to investigate more closely why it wouldn't work on your end.

Attaching to that, I would like to point out that CrateDB ships a bundled variant of the Java runtime. Thus, `JAVA_HOME` does not have to be set beforehand at all. Maybe you can verify if it would magically starts working if it is not defined?

With kind regards,
Andreas.

[1] https://gist.github.com/amotl/69046c2c4a8e6744b1d6cde3f9523119

**Comment by amotl** [comment]
There is a line `for %%I in ("%SCRIPT_DIR%..") do set CRATE_HOME=%%~dpfI` at the beginning of `crate.bat`. If that line would not be executed properly, then the `CRATE_HOME` directory can not be determined correctly. In turn, this could lead to the situation you are observing.

```powershell
PS C:\opt\crate> ./bin/crate
JAVA_HOME environment variable must be set
```

In order to get hold of the problem, you might be able to add a `test.bat` next to `crate.bat`, like
```bat
SETLOCAL EnableDelayedExpansion

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set CRATE_HOME=%%~dpfI
```

On my system, this would correctly yield
```powershell
PS C:\opt\crate> ./bin/test

C:\opt\crate>SETLOCAL EnableDelayedExpansion
C:\opt\crate>set SCRIPT_DIR=C:\opt\crate\bin\
C:\opt\crate>for %I in ("C:\opt\crate\bin\..") do set CRATE_HOME=%~dpfI
C:\opt\crate>set CRATE_HOME=C:\opt\crate
```

**Comment by amotl** [comment]
Hi again,

as @proddata mentioned at https://github.com/crate/crate/pull/11101#issuecomment-793513979:

> Did you download the Windows specific package?

... I am inclined to believe that you might have downloaded the tarball, which does not include a bundled Java runtime. So, may I humbly ask you to try again using [1] which was released just a few hours ago?

With kind regards,
Andreas.

[1] https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.4.2.zip

**Comment by nkev** [comment]
Thank you so much for your prompt support on this.

> I would like to point out that CrateDB ships a bundled variant of the Java runtime.

Yes, but the unzipped contents of the `crate-4.4.2` folder did not contain the bundled JDK:

![image](https://user-images.githubusercontent.com/5410916/110550976-cbd1ed00-8188-11eb-9368-6ae6691fb040.png)

After getting the error `JAVA_HOME environment variable must be set` I had no choice but to install Oracle Java 11. For your reference, the new download link you provided above does contain a bundled JDK.

>In order to get hold of the problem, you might be able to add a test.bat next to crate.bat and share its output here.

For your reference, here are the results of your `test.bat` script above in the initial (old) download:
```BASH
C:\Users\me\Downloads\crate-4.4.2 old\bin>SETLOCAL EnableDelayedExpansion
C:\Users\me\Downloads\crate-4.4.2 old\bin>set SCRIPT_DIR=C:\Users\me\Downloads\crate-4.4.2 old\bin\
C:\Users\me\Downloads\crate-4.4.2 old\bin>for %I in ("C:\Users\me\Downloads\crate-4.4.2 old\bin\..") do set CRATE_HOME=%~dpfI
C:\Users\me\Downloads\crate-4.4.2 old\bin>set CRATE_HOME=C:\Users\me\Downloads\crate-4.4.2 old
```

> So, may I humbly ask you to try again using [1] which was released just a few hours ago?

Yes, of course. I downloaded it and noticed it now has the bundled JDK. After restarting Powershell and running `./bin.crate` I got a different error below. An important point is my Windows Home directory is actually obfuscated in above posts as `me`. My real Home directory is my full name, which has a space between the first and last name. This may be causing an issue with paths in your script:

```BASH
PS C:\Users\Nuri Surname> cd "C:\Users\Nuri Surname\Downloads\crate-4.4.2"
PS C:\Users\Nuri Surname\Downloads\crate-4.4.2> ./bin/crate
'""C:\Users\Nuri' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\Nuri Surname\Downloads\crate-4.4.2>
```
Running your test.bat script in the new download `crate-4.4.2\bin` folder returns:

```BASH
C:\Users\Nuri Surname\Downloads\crate-4.4.2>SETLOCAL EnableDelayedExpansion
C:\Users\Nuri Surname\Downloads\crate-4.4.2>set SCRIPT_DIR=C:\Users\Nuri Surname\Downloads\crate-4.4.2\bin\
C:\Users\Nuri Surname\Downloads\crate-4.4.2>for %I in ("C:\Users\Nuri Surname\Downloads\crate-4.4.2\bin\..") do set CRATE_HOME=%~dpfI
C:\Users\Nuri Surname\Downloads\crate-4.4.2>set CRATE_HOME=C:\Users\Nuri Surname\Downloads\crate-4.4.2
```

**Comment by amotl** [comment]
Dear Nuri,

thank you for your feedback, your report is very valuable to us. Just recently, we have been able to improve the situation with spaces in directory names for Unix platforms on behalf of #10845, but apparently we missed out on taking care about the Windows platform.

I have been able to come up with a quick fix and want to kindly ask you if you can make sense of that in order to apply the changes outlined in this diff to your `crate.bat` file.
```patch
--- crate.bat.dist	2021-03-10 01:19:54.000000000 +0100
+++ crate.bat	2021-03-10 01:20:18.000000000 +0100
@@ -53,7 +53,7 @@

   SET LOGGC=!GC_LOG_DIR!\gc.log

-  SET JAVA_OPTS=!JAVA_OPTS! -Xlog:gc*,gc+age=trace,safepoint:file=\"!LOGGC!\":utctime,pid,tags:filecount=!GC_LOG_FILES!,filesize=!GC_LOG_SIZE!
+  SET JAVA_OPTS=!JAVA_OPTS! -Xlog:gc*,gc+age=trace,safepoint:file="!LOGGC!":utctime,pid,tags:filecount=!GC_LOG_FILES!,filesize=!GC_LOG_SIZE!
 )

 REM Disables explicit GC
@@ -104,7 +104,7 @@
     )
 )

-set JAVA_HOME="%CRATE_HOME%\jdk"
+set JAVA_HOME=%CRATE_HOME%\jdk
 if not exist !JAVA_HOME! (
     ECHO JAVA_HOME environment variable must be set! 1>&2
     EXIT /B 1
```

Please let me know how that goes.

With kind regards,
Andreas.

**Comment by nkev** [comment]
I think I have deleted enough files now for the installation to continue because it has gone under the low disk watermark and resharding (although there are no tables):

```BASH
[2021-03-10T15:22:04,674][INFO ][o.e.c.r.a.DiskThresholdMonitor] [Pointe Blanche] low disk watermark [85%] exceeded on [VsTVNne4Qu-iY_yeeMCl0Q][Pointe Blanche][C:\Users\Nuri Surname\Downloads\crate-4.4.2\data\nodes\0] free: 56.1gb[11.8%], replicas will not be assigned to this node
[2021-03-10T15:22:34,675][INFO ][o.e.c.r.a.DiskThresholdMonitor] [Pointe Blanche] rerouting shards: [one or more nodes has gone under the high or low watermark]
```
The issue is, Powershell has been sitting on that last line for over an hour now.  Is this normal?

The installation seems to have worked far enough for CrateDB to run:

![image](https://user-images.githubusercontent.com/5410916/110580827-867be280-81bd-11eb-817d-bb9e280f2fc9.png)

Also, on the same LAN as this Windows desktop, I have my MacBook Pro running version v4.4.1 Trial (versus v4.4.2 Community on Windows). I was hoping they would automatically see each other and form a cluster. The MacBook has a single `iss` table from the getting started sample with only 3 records in it, but the Windows machine tables are empty because the cluster is not formed.

**Comment by amotl** [comment]
Dear Nuri,

we just integrated #11121, which will fix the start issue on Windows when using directory names with spaces for the next release of CrateDB. Again, thank you very much for reporting this flaw to us.

Currently, I can't say much to the `low disk watermark` warning you might observe to be somehow sticky. In order to get more insights about it, I want to humbly ask you to share this on our community forum [1].

Attaching to your last question, I deliberately diverted that into #11125. However, the community forum [1] might also be the more appropriate place to discuss such questions.

I hope you are satisfied with my responses to that so far. So, let's close this issue for the sake of being resolved on the main issue raised here.

Thank you very much again and with kind regards,
Andreas.

[1] https://community.crate.io/
