### ISSUE TITLE
How to let CrateDB nodes form a cluster

### ISSUE THREAD

**Issue by amotl** [crate/crate#11125]
At #11110, after sorting out some issues around starting CrateDB on Windows (thank you again!), @nkev added another question:

> On the same LAN as this Windows desktop, I have my MacBook Pro running version v4.4.1 Trial (versus v4.4.2 Community on Windows). I was hoping they would automatically see each other and form a cluster. The MacBook has a single `iss` table from the getting started sample with only 3 records in it, but the Windows machine has no tables (nothing synced from the MacBook) because the cluster has not formed yet. Should I install v4.4.2 Community on my MacBook Pro?

_Originally posted by @nkev in https://github.com/crate/crate/issues/11110#issuecomment-794909833_

**Comment by mfussenegger** [comment]
I think how to form a cluster is described quite well in the documentation: https://crate.io/docs/crate/howtos/en/latest/clustering/index.html

**Comment by amotl** [comment]
Thank you for pointing that out, Mathias. So, Nuri, can I humbly ask you to follow that guidelines about how to _configure the bootstrapping process_ for multi-node setups [1] and then report back to us?

Apparently, you will have to take care of three steps to properly adjust the `discovery.seed_hosts`, `cluster.initial_master_nodes` and `gateway` settings in your configuration files.


[1] https://crate.io/docs/crate/howtos/en/latest/clustering/multi-node-setup.html#manual-bootstrapping
