### ISSUE TITLE
Make negating boolean expressions adhere to the SQL standard

### ISSUE THREAD

**Issue by amotl** [crate/crate#11154]
Hi there,

while reviewing #11144, I crossed the way of a documentation remark about negating boolean values [1]. There, the documentation says:

> The result of NOT (NULL) in a WHERE clause that operates on user tables will produce inconsistent but deterministic results (NULL or TRUE) depending on the specifics of the clause. This does not adhere to standard SQL three-valued-logic and will be fixed in a future release.

I just wanted to converge this into an issue in order not to loose track of it.

With kind regards,
Andreas.

[1] https://github.com/crate/crate/blob/4.4.2/docs/general/dql/selects.rst#not

**Comment by mfussenegger** [comment]
I'm not sure if this is even still a problem. I think we handle the cases where the `NULL`/`FALSE` distinction matters correctly.

@seut do you know if we still have some edge cases where the behavior doesn't match the standard?

**Comment by seut** [comment]
@mfussenegger No I'm not aware any more edge cases, I think we just forgot to remove this paragraph.
