### ISSUE TITLE
changes in the error reporting of executemany ?

### ISSUE THREAD

**Issue by chicco785** [crate/crate#11179]
**CrateDB version**:
4.4.2

**Problem description**:

When calling an executemany insert (using python driver) with previous versions of crate (4.1 eg),
when any of the row insertion was failing an ProgrammingError exception was returned.
Now even though all rows are failing, there is no exception, simply the rowCount is a negative number.

Is that intended?

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
Yes there was a behavior change about this in 4.2.0. From the release notes:

> Bulk ``INSERT INTO ... VALUES (...)`` statements do not throw an exception
>  any longer when one of the bulk operations fails. The result of the execution
> is only available via the ``results`` array represented by a row count for
>  each bulk operation.


https://github.com/crate/crate/blob/57744c7157f1bcbdb58677d7401b48118aedcbff/docs/appendices/release-notes/4.2.0.rst#L63-L66
