### ISSUE TITLE
Problem on SHOW CREATE TABLE (4.5) and ALTER ... ADD COLUMN (4.4.3 & 4.5) when fulltext index columns are present.

### ISSUE THREAD

**Issue by MikeMaxFR** [crate/crate#11216]
Hi,

I just tried a “SHOW CREATE TABLE” on version 4.5 which can’t be replayed (i spare you the table parameters) :

```
CREATE TABLE IF NOT EXISTS "doc"."books" (
   "id" INTEGER,
   "author" TEXT,
   "author_ft" TEXT INDEX USING FULLTEXT,
   "book_title" TEXT,
   "column_name" TEXT,
   "book_title_ft" TEXT INDEX USING FULLTEXT,
   PRIMARY KEY ("id"),
   INDEX "author_ft" USING FULLTEXT ("author"),
   INDEX "book_title_ft" USING FULLTEXT ("book_title")
)
....
```

Indexes are specified Twice … so CrateDB says :

![image](https://user-images.githubusercontent.com/17073394/113988324-a4d20e00-984f-11eb-99a7-1fe025226114.png)

But on version 4.4.3, the same table show me this for the SHOW CREATE TABLE statement :

```
CREATE TABLE IF NOT EXISTS "doc"."books" (
  "id" INTEGER,
  "author" TEXT,
  "book_title" TEXT,
  "column_name" TEXT,
  PRIMARY KEY ("id"),
  INDEX "author_ft" USING FULLTEXT ("author"),
  INDEX "book_title_ft" USING FULLTEXT ("book_title")
)
...
```

Which works fine.

So it seems the SHOW CREATE TABLE statement is buggy on the 4.5 version.

**But in both 4.4.3 and 4.5 version**,  the ALTER… ADD COLUMN creates INDEX FULLTEXT columns as real columns :

Try to create this table :

```
CREATE TABLE IF NOT EXISTS "doc"."books" (
  "id" INTEGER,
  "author" TEXT,
  "book_title" TEXT,
  PRIMARY KEY ("id"),
  INDEX "author_ft" USING FULLTEXT ("author"),
  INDEX "book_title_ft" USING FULLTEXT ("book_title")
);
```

And then :

`ALTER TABLE "doc"."books" ADD COLUMN "column_name" TEXT;`

You will see that every fulltext indexed columns are now real columns … (seen on 4.4.3 and 4.5 but not verified on older version)

**Comment by jayeff** [comment]
I was able to reproduce this. 

Regression from 4.0.12 to 4.1.1 

Minimal example:

```CREATE TABLE IF NOT EXISTS "test" ("author" TEXT, INDEX "author_ft" USING FULLTEXT ("author"));```

SHOW CREATE TABLE test:
```
CREATE TABLE IF NOT EXISTS "doc"."test" (
   "author" TEXT,
   INDEX "author_ft" USING FULLTEXT ("author") WITH (
      analyzer = 'standard'
   )
)
```

Add column:
```ALTER TABLE "test" ADD COLUMN "column_name" TEXT;```

SHOW CREATE TABLE test:
```
CREATE TABLE IF NOT EXISTS "doc"."test" (
   "author" TEXT,
   "author_ft" TEXT INDEX USING FULLTEXT WITH (
      analyzer = 'standard'
   ),
   "column_name" TEXT,
   INDEX "author_ft" USING FULLTEXT ("author")
)
```

Only named indexes are affected. Creating a table like so `CREATE TABLE IF NOT EXISTS "test_2" ("author" TEXT INDEX USING FULLTEXT);` does not have this issue.

**Comment by mfussenegger** [comment]
Thank you for the detailed report and reproduction steps. We are working on a fix which will be included in the next hotfix release.

I'm not sure yet if this is a reporting issue with the SHOW CREATE TABLE statement or whether the ALTER TABLE ADD COLUMN is extending the schema in a way it shouldn't. If the latter is the case, the hotfix will only prevent this from happening for new ADD COLUMN statements, but might not be able to repair the tables already affected.
