### ISSUE TITLE
authentication, SSL

### ISSUE THREAD

**Issue by norosa** [crate/crate#11255]
# Pitch

## Why

We have the following docs in the main reference:

- SSL
- Authentication

These docs:

- Could do with a rewrite
- Do not adequately cover the material 
- Mix up reference info with tutorials

## What

I propose:

- Rewrite this content from scratch
- Expand it to cover more of the material (so it's easier for people with no experience to get going, and has more stuff for experts too)
- Move the tutorial content off to the guide

I also propose to maybe:

- Produce one or more tutorial style blog posts

**Comment by seut** [comment]
Don't see a need to do something here, please reopen with concrete issues and suggestions if needed.
