### ISSUE TITLE
user management and privileges

### ISSUE THREAD

**Issue by norosa** [crate/crate#11256]
# Pitch

## Why

Should follow this batch:

https://trello.com/c/KXNYAVLf/309-docs-rewrite-authentication-ssl

We have the following docs in the main reference:

- User management
- Privileges

These docs:

- Could do with a complete rewrite
- Could do with some tutorial-style content in the guide

## What

I propose:

- To rewrite both sections of the docs
- Produce some tutorial-style content for the guide

I also propose to maybe:

- Produce one or more tutorial style blog posts (see https://trello.com/c/GlaSqIeX/261-user-mgmt-in-cratedb)

## Who

- Naomi (primary)
- SUPPORT ENGINEER (?)

**Comment by seut** [comment]
Don't see a clear urge to do something here, please reopen with concrete issues and suggestions if needed.
