### ISSUE TITLE
Support for PG array_to_string() - concat elements of an array to string / text with a delimiter

### ISSUE THREAD

**Issue by proddata** [crate/crate#11284]
**Use case**:
Support for PG array_to_string() function in CrateDB.

This now can be done as workaround with an UDF for TEXT:

```sql
CREATE OR REPLACE function array_to_string(array(TEXT),TEXT)
RETURNS TEXT
LANGUAGE JAVASCRIPT
AS 'function array_to_string(arr, delimiter) { return Array.prototype.join.call(arr, delimiter);}';
```

```sql
SELECT array_to_string(['a','b','c'],',');
```

**Feature description**:

There is an array_to_string() function that concats elements with a delimiter (optionally replace `NULL` values 

From PostgreSQL

> array_to_string ( array anyarray, delimiter text [, null_string text ] ) → text
>Converts each array element to its text representation, and concatenates those separated by the delimiter string. If null_string is given and is not NULL, then NULL array entries are represented by that string; otherwise, they are omitted.
> array_to_string(ARRAY[1, 2, 3, NULL, 5], ',', '*') → 1,2,3,*,5

**Comment by mfussenegger** [comment]
Isn't this [string_agg](https://crate.io/docs/crate/reference/en/4.5/general/builtins/aggregation.html#string-agg-column-delimiter) ?

**Comment by proddata** [comment]
> Isn't this string_agg ?

`array_to_string` would be a scalar function
It really would be the counterpart to [string_to_array()](https://crate.io/docs/crate/reference/en/master/general/builtins/scalar-functions.html#string-to-array-string-separator-null-string)

One would have to unnest the array to use `string_agg()` first, which might not work with different length arrays in a recordset

**Comment by mfussenegger** [comment]
Right, of course. I got things mixed up.

**Comment by BaurzhanSakhariev** [comment]
All aggregation functions will be supported for arrays after closing [10662](https://github.com/crate/crate/issues/10662) which is in progress now. 

If I understand correctly, supporting `string_agg ` for `array ` type closes this issue as well, doesn't it?

**Comment by proddata** [comment]
@BaurzhanSakhariev 

array_to_string() would be a scalar function, similar to #10662 i.e. basically an extensions to the other aggregations in there
