### ISSUE TITLE
Add time bucketing function `time_bucket(<interval>,<timestamp>)` || `date_bin(<interval>,<timestamp>)`

### ISSUE THREAD

**Issue by proddata** [crate/crate#11310]
**Use case**:
Right now one can only use `date_trunc()` to easily define time buckets. `date_trunc()` only supports predefine time intervals like **1** minute, **1 hour**, etc. . In time-series use cases it is often necessary to define different time bucket sizes like e.g. '5 minutes' or '20 minutes'

a workaround for this is the - error prone - integer division on the timestamp e.g.
```sql
SELECT 
(ts / ( 300 * 1000)) * 300 * 1000 AS "bucket",
avg(metric)
FROM data
GROUP BY bucket
ORDER BY bucket DESC LIMIT 10;
```

**Feature description**
Have the ability to pass other time bucket sizes / intervals to `date_trunc()`, e.g. `date_trunc('5 minutes',ts)` or have a separate `time_bucket(INTERVAL,TIMESTAMP)` function that takes an interval e.g. `'5 minutes'` and a timestamp as input and returns the corresponding bucket (i.e. a timestamp that has the starting value of the bucket)

```sql
SELECT
time_bucket('5 minutes', ts) AS "bucket",
avg(metric)
FROM data
GROUP BY bucket
ORDER BY bucket DESC LIMIT 10;
```

---

Timescale time_bucket() function
[TS docs](https://docs.timescale.com/api/latest/analytics/time_bucket/)
[GH implementation](https://github.com/timescale/timescaledb/blob/master/src/time_bucket.c)

**Comment by seut** [comment]
We should clarify upfront the scope of what arguments to support.

**Comment by proddata** [comment]
For compatible reasons, I think it would be fine if it follow TS ...

Suggestion:
## Must

`time_bucket(bucket_interval, timestamp)`
- **bucket_interval** `INTERVAL`
   a CrateDB time interval for bucketing timestamps. e.g. `'5 minutes'::INTERVAL` or `'2 months 3 days'` 
- **timestamp** `TIMESTAMP`
   a CrateDB timestamp to bucket)
   e.g. `time_bucket('5 minutes', '2021-05-11T14:00:09.285Z')`
   -> `ts: 1620741609285 bucket: 1620741600000`	

`time_bucket(bucket_interval, timestamp)`
- **bucket_interval** `BIGINT`
   a CrateDB time bigint for bucketing timestamps. e.g. `300000` (5 minutes) 
- **timestamp** `BIGINT`
   a CrateDB time bigint for bucketing timestamps. e.g. `1620741609285` 
   e.g. `time_bucket(300000, 1620741609285)`
   -> `ts: 1620741609285 bucket: 1620741600000`	

---
---

## Optional

`time_bucket(bucket_interval, timestamp, offset)`
- **bucket_interval** `INTERVAL`
   a CrateDB time interval for bucketing timestamps. e.g. `'5 minutes'::INTERVAL` or `'2 months 3 days'` 
- **timestamp** `TIMESTAMP`
   a CrateDB timestamp to bucket
- **offset** `INTERVAL `
   a CrateDB interval to offset all buckets
   e.g. `time_bucket('5 minutes', '2021-05-11T14:00:09.285Z','-150 seconds')`
   -> `ts: 1620741609285 bucket: 1620741450000`	

`time_bucket(bucket_interval, timestamp, origin)`
- **bucket_interval** `INTERVAL`
   a CrateDB time interval for bucketing timestamps. e.g. `'5 minutes'::INTERVAL` or `'2 months 3 days'` 
- **timestamp** `TIMESTAMP`
   a CrateDB timestamp to bucket
- **origin** `TIMESTAMP`
   a CrateDB interval to offset all buckets
   e.g. `time_bucket('5 minutes', '2021-05-11T14:00:09.285Z','2021-01-03T00:00:00.000Z')`
   -> `ts: 1620741609285 bucket: 1620741450000`	

+ eqv. for `BIGINT`

**Comment by mfussenegger** [comment]
I'd say we keep the scope minimal for now and only support `time_bucket( interval, timestamp)` 

Unless I'm missing something, the offset can be applied using regular arithmetic and the other variants can be accomplished using explicit casts.

We can always extend it later as concrete use-cases arise

**Comment by BaurzhanSakhariev** [comment]
should the null handling be the same as date_trunc? 

`select DATE_TRUNC('day', null) `- returns null
`select DATE_TRUNC(null, CURRENT_TIMESTAMP)`  - returns null
`select DATE_TRUNC(null, null)` - returns null

**Comment by mfussenegger** [comment]
> should the null handling be the same as date_trunc?
> 
> `select DATE_TRUNC('day', null) `- returns null
> `select DATE_TRUNC(null, CURRENT_TIMESTAMP)` - returns null
> `select DATE_TRUNC(null, null)` - returns null

yes

**Comment by BaurzhanSakhariev** [comment]
default origin is unix 0, Thursday, 01.01.1970 - should be there an option to provide custom origin for easier bucketing by weeks?
with origin = unix ts 0, time_bucket('1 week'::INTERVAL, '1969-01-09T00:00:00Z'::timestamp without time zone) returns -31449600000 which is Thursday, 02.01.1970.

**Comment by proddata** [comment]
PostgreSQL 14 seems to implement a `date_bin()` function, that would be quite similiar.

https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-BIN

**Comment by proddata** [comment]
`date_bin()` has an `origin` parameter.
I think this should be optional, however it might be good to follow the example and use `2001-01-01` (monday) as origin for calculations, rather than `1970-01-01` (thrusday) to avoid issues with `week`-Intervals
