### ISSUE TITLE
Set default value for number_of_routing_shards to provide scalability by default

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11320]
**Use case**:
Set default value for [number-of-routing-shards](https://crate.io/docs/crate/reference/en/4.5/sql/statements/create-table.html#sql-create-table-number-of-routing-shards) so that even if users forget to set this parameter, they can scale later on.  

**Feature description**:
Use multiply of shards as a default value for `number-of-routing-shards`.

Requirements to multiplier  - max X, so that `shards * X <= 500`? 
If initial number of shards is already high then do not scale to huge number like 5000 but if it's too small like 3 there should be enough room for future scaling up.

**Comment by proddata** [comment]
Seems like ES since v7.0 sets max to 1024 by default.
`X` probably should be a multiple of 2 

https://www.elastic.co/guide/en/elasticsearch/reference/7.x/index-modules.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_document_distribution_changes

**Comment by BaurzhanSakhariev** [comment]
related
https://github.com/elastic/elasticsearch/commit/fadbe0de08313d42494da34f7a4ba5e437622173
https://github.com/elastic/elasticsearch/commit/bd7efa908ab69831757d45ca7519c286097777dc

**Comment by BaurzhanSakhariev** [comment]
Let's hold it for while https://github.com/elastic/elasticsearch/issues/48863

**Comment by BaurzhanSakhariev** [comment]
Let's hold it for while https://github.com/elastic/elasticsearch/issues/48863, case when a `routing_partition_size` is specified needs special handling

**Comment by seut** [comment]
> Let's hold it for a while, case when a `routing_partition_size` is specified needs special handling, see [elastic/elasticsearch#48863 (comment)](https://github.com/elastic/elasticsearch/issues/48863#issuecomment-952660243)

We've never exposed the `routing_partition_size` setting, so the issue isn't relevant for us.
