### ISSUE TITLE
Cratedb VS Clickhouse 

### ISSUE THREAD

**Issue by cmdares** [crate/crate#11331]
Large scale machine data and database selection.
Under the same hardware resources, we compare the performance of cratedb and Clickhouse insertion and complex query.
I hope the community can give pertinent suggestions.
thanks.

**Comment by proddata** [comment]
Hi @cmdares 

I would kindly ask you to move any such discussion to:
https://community.crate.io/
where we can help you with any questions regarding optimising query and ingest performance with CrateDB.

this repository is only for feature request and bug-reports directly related to CrateDB.

best regards
proddata
