### ISSUE TITLE
Select on unnested sub-select return zero rows when unnested column identifier is not part of select stmt

### ISSUE THREAD

**Issue by proddata** [crate/crate#11333]
**CrateDB version**:
CrateDB 4.5

**Environment description**:
local (macOS)

**Problem description**:

*Don't really know if this is really a bug or an edge case*

Select on unnested sub-select return zero rows when unnested column identifier is not part of select stmt

**Steps to reproduce**:

```sql
CREATE TABLE bug (txt TEXT, arr ARRAY(TEXT));
INSERT INTO bug VALUES ('test', ['t1','t2']);
```

```sql
SELECT sub.txt FROM (SELECT txt, UNNEST(arr) ar FROM bug) sub limit 100;
-- or
SELECT txt FROM (SELECT txt, UNNEST(arr) ar FROM bug) sub limit 100;
--SELECT OK, 0 records returned (0.001 seconds)
```

```sql
SELECT arr FROM (SELECT txt, UNNEST(arr) ar FROM bug) sub limit 100;
-- or
SELECT * FROM (SELECT txt, UNNEST(arr) ar FROM bug) sub limit 100;
-- SELECT OK, 2 records returned (0.001 seconds)
````

**Comment by mfussenegger** [comment]
This is a bug. I suspect it's caused by our column pruning optimization.

Will have a closer look and come up with a fix for the next 4.5. hotfix release
