### ISSUE TITLE
LogConfigurator warning

### ISSUE THREAD

**Issue by amotl** [crate/crate#11345]
Hi there,

this is just a report about a minor thing I observed while working on a task related to packaging.

I discovered this warning related to the `LogConfigurator` managing the logging configuration on the CrateDB log when being started on CentOS after being installed from the official package repository:
```
$ journalctl -u crate

May 03 14:40:20 localhost.localdomain crate[25679]: [2021-05-03T14:40:20,974][WARN ][o.e.c.l.LogConfigurator  ] [Pflerscher Tribulaun] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
May 03 14:40:21 localhost.localdomain crate[25679]: /etc/crate/log4j2.properties
```

With kind regards,
Andreas.

**Comment by mfussenegger** [comment]
This is a problem with the log4j configuration bundled in the RPM. Opened a PR to change that.
