### ISSUE TITLE
ON CONFLICT DO UPDATE SET WHERE condition error

### ISSUE THREAD

**Issue by 651016236** [crate/crate#11387]
**CrateDB version**:
4.5.1

**Environment description**:
 - Docker: version 19.03.8

**Problem description**:
![image](https://user-images.githubusercontent.com/5875767/118628847-95a39000-b7ff-11eb-88d3-b28fdf24e054.png)
but document
![image](https://user-images.githubusercontent.com/5875767/118628914-a48a4280-b7ff-11eb-810a-edb997d8090a.png)

**Comment by mfussenegger** [comment]
Thank you for the report.

I think this is confusing in the docs. `WHERE` there isn't meant as a supported clause, but rather used to describe `conflict_targets` and `assignments`.
The `WHERE` clause is currently not supported in the `ON CONFLICT` context.

**Comment by 651016236** [comment]
Thank you very much, looking forward to the official integration of this feature
