### ISSUE TITLE
Different behaviour with aliased integer column in group by

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11414]
**CrateDB version**: 4.5.1

**Problem description**:

I created a table with an integer column which I group by. When this column is aliased the behaviour is different if the query includes a `LIMIT` or not. See steps to reproduce below for details.

Please note that no exception is _not_ thrown with a text column. I did not test the other data types.

I'm not sure what the expected behaviour would be in this case but I would expect it to be consistent across different data types and to be independent of `LIMIT`.

**Steps to reproduce**:

Create table
```
create table test_as_int (a int);
```

With limit:
```
select a as b from test_as_int group by a limit 10;
=> UnsupportedFeatureException[Can't handle Symbol [Reference: a]]

explain select a as b from test_as_int group by a limit 10;
Eval[a AS b]
  └ TopNDistinct[10::bigint;0 | [a]]
    └ Collect[doc.test_as_int | [] | true] 
```

Without `limit`
```
select a as b from test_as_int group by a;
=> SELECT 0 rows in set (0.001 sec)

explain select a as b from test_as_int group by a;
Eval[a AS b]
  └ GroupHashAggregate[a]
    └ Collect[doc.test_as_int | [a] | true] 
```

As comparison the same with text:
```
create table test_as_int (a int);
select a as b from test_as_text group by a;
=> SELECT 0 rows in set (0.001 sec)
select a as b from test_as_text group by a limit 10;
=> SELECT 0 rows in set (0.001 sec)
```

**Comment by mfussenegger** [comment]
Fixed via https://github.com/crate/crate/pull/11430 

Thank you for the bug report.
