### ISSUE TITLE
Varying performance for group by queries

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11413]
**CrateDB version**: 4.5.1

**Environment description**: macOS; started with `cr8`

**Problem description**:

Recently a performance problem was reported in the [Crate.io Community](https://community.crate.io/t/limited-performance-during-query/668/13). I downloaded the provided snapshot and could reproduce the same behaviour.

Further queries did show differences in query duration which I don't fully understand:

Unlimited group by
```
$> echo "select f from doc.test5kk_025 group by f;" | cr8 timeit --host http://localhost:4200 -w 5 -r 10
Runtime (in ms):
    mean:    6962.284 ± 116.587
```

Limited group by
```
$> echo "select f from doc.test5kk_025 group by f limit 1000000;" | cr8 timeit --host http://localhost:4200 -w 5 -r 10
Runtime (in ms):
    mean:    2905.901 ± 34.236
```

Unlimited group by with values doubled
```
$> echo "select f*2 as ff from doc.test5kk_025 group by ff;" | cr8 timeit --host http://localhost:4200 -w 5 -r 10
Runtime (in ms):
    mean:    1188.969 ± 79.297
```

Limited group by with values doubled
```
$> echo "select f*2 as ff from doc.test5kk_025 group by ff limit 1000000;" | cr8 timeit --host http://localhost:4200 -w 5 -r 10
Runtime (in ms):
    mean:    3831.521 ± 21.244
```

The table has 5 million integer/bigint records (range of records between 18-5456946) with around 790k distinct numbers.

**Questions**:

- Why is "Limited group by" twice as fast as "Unlimited group by"?
- Why is "Unlimited group by with values doubled" over 5 times as fast as "Unlimited group by"?

**Steps to reproduce**:

Create Table statement:
```
CREATE TABLE IF NOT EXISTS "doc"."test5kk_025" (
   "f" BIGINT DEFAULT NULL
)
CLUSTERED INTO 35 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   codec = 'default',
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-1',
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = 'fs',
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "write.wait_for_active_shards" = '1'
)
```

See the linked community post for a dataset to reproduce my results.

**Comment by mfussenegger** [comment]
The `with limit` variant is faster because it uses an optimized plan:


```
cr> explain select f from doc.test5kk_025 group by f limit 1000000;
+-------------------------------------------+
| EXPLAIN                                   |
+-------------------------------------------+
| TopNDistinct[1000000::bigint;0 | [f]]     |
|   └ Collect[doc.test5kk_025 | [f] | true] |
+-------------------------------------------+
```

I guess the intuition is that it shouldn't matter if the limit is bigger than the result-set, but in practice it does because the `TopNDistinct` can avoid a merge step that is necessary without it. In the regular GROUP BY operator we first group and aggregate on the shard level, and then need to merge the results of each shard together. (Assuming a single node)


As for the multiply/no multiply difference, I cannot reproduce that.



```
V1: Without multiply; V2: with multiply
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     5947.365 ±  109.184 |   5722.326 |   5950.086 |   6029.328 |   6062.938 |
|   V2    |     5989.272 ±   79.720 |   5877.447 |   5969.755 |   6033.520 |   6156.371 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   0.70%                           +   0.33%
There is a 66.00% probability that the observed difference is not random, and the best estimate of that difference is 0.70%
The test has no statistical significance
```



Here's the full script I used to compare results:


```
PID=$(jps | awk '/CrateDB/ { print $1 }' | head -n 1)
#jcmd $PID JFR.start name=recording duration=1m filename=$(pwd)/profile.jfr settings=profile


~/apps/async-profiler/profiler.sh start $PID
echo 'select f * 2 from doc.test5kk_025 group by f' | cr8 timeit --host http://localhost:4200 -w 3 -r 10 -of json | jq '.runtime_stats.samples[]' -r | tee /tmp/perf_multiply.txt
~/apps/async-profiler/profiler.sh stop $PID -f /tmp/flamegraph_multiply.html
firefox /tmp/flamegraph_multiply.html


~/apps/async-profiler/profiler.sh start $PID
echo 'select f from doc.test5kk_025 group by f' | cr8 timeit --host http://localhost:4200 -w 3 -r 10 -of json | jq '.runtime_stats.samples[]' -r | tee /tmp/perf_field.txt
~/apps/async-profiler/profiler.sh stop $PID -f /tmp/flamegraph_field.html
firefox /tmp/flamegraph_field.html


~/apps/async-profiler/profiler.sh start $PID
echo 'select f from doc.test5kk_025 group by f limit 1000000' | cr8 timeit --host http://localhost:4200 -w 3 -r 10 -of json | jq '.runtime_stats.samples[]' -r | tee /tmp/perf_limit.txt
~/apps/async-profiler/profiler.sh stop $PID -f /tmp/flamegraph_limit.html
firefox /tmp/flamegraph_limit.html



echo "V1: Without multiply; V2: with multiply"
./compare_measures.py --old /tmp/perf_field.txt --new /tmp/perf_multiply.txt

echo "V1: Without limit; V2: with limit"
./compare_measures.py --old /tmp/perf_field.txt --new /tmp/perf_limit.txt
```

**Comment by kamcio181** [comment]
Hi @mfussenegger 
Thank you for the response. Regarding optimization with limit, could you give more information about situation when merge step is avoided? Is it good practice to always set limit even if it is way too big for expected results just to increase performance? Will it result in faster execution for all cases?

Regarding issue with doubling I can see that you are grouping by f but you should group by doubled value, ie.
'select f * 2 as ff from doc.test5kk_025 group by ff'

**Comment by mfussenegger** [comment]
> Regarding issue with doubling I can see that you are grouping by f but you should group by doubled value, ie.
'select f * 2 as ff from doc.test5kk_025 group by ff'

Ah right, thanks for the pointer. Now I can reproduce the difference. Will take a closer look at it.


> Regarding optimization with limit, could you give more information about situation when merge step is avoided? Is it good practice to always set limit even if it is way too big for expected results just to increase performance? Will it result in faster execution for all cases?


I think it depends on the cardinality ratio. With few unique values, the extra merge step may result in a performance improvement because it is possible to parallelize the operations on the shard level.
Ideally we'd tune the optimizer to choose the better execution plan.

**Comment by mfussenegger** [comment]
Turns out that the performance difference between GROUP BY on `f * 2` and `f` is due to the different values which lead to different hashing and collisions in the underlying Map implementation we use for the grouping operation.

@jayeff last test with the projected table also shows this.

>> I think it depends on the cardinality ratio. With few unique values, the extra merge step may result in a performance improvement because it is possible to parallelize the operations on the shard level.
>
> The number of distinct values is the same between the normal and doubled set of values. So is it maybe related to the specific range of values?

My comment there was in regards to when using TopNDistinct vs. using regular GroupBy.

**Comment by kamcio181** [comment]
@mfussenegger 
thank you for your response. Could you tell me what implementation of hashing function are you using? 
Is it possible to use own hashing function? Ie. based on https://github.com/Cyan4973/xxHash

**Comment by mfussenegger** [comment]
> @mfussenegger
> thank you for your response. Could you tell me what implementation of hashing function are you using?
> Is it possible to use own hashing function? Ie. based on https://github.com/Cyan4973/xxHash


Currently we use either the JDK `HashMap`, which calculates the index like this:

```java
        int h;
        return (key == null) ? 0 : (h = key.hashCode()) ^ (h >>> 16);
```


Where the hashCode for long values is implemented like this:


```java
    public static int hashCode(long value) {
        return (int)(value ^ (value >>> 32));
    }
```


In some cases we instead use the `LongObjectHashMap` implementation from netty, which has a similar implementation:



```java
    /**
     * Returns the hashed index for the given key.
     */
    private int hashIndex(long key) {
        // The array lengths are always a power of two, so we can use a bitmask to stay inside the array bounds.
        return hashCode(key) & mask;
    }

    /**
     * Returns the hash code for the key.
     */
    private static int hashCode(long key) {
       return (int) (key ^ (key >>> 32));
    }
```

With the given test data I didn't notice much of a difference between the two.


It would be possible to create another Map implementation which supports custom hashing methods.

**Comment by kamcio181** [comment]
@mfussenegger 
It would be great if we could pick hash implementation. I have compiled crate 4.5.1 replacing hashCode function in LongObjectHashMap with xxhash implementation from lz4 lib
`    private static final XXHash32 XX_HASH_32 = XXHashFactory.fastestInstance().hash32();
    private static final int SEED = 0x9747b28c;
    /**
     * Returns the hash code for the key.
     */
    private static int hashCode(long key) {
        return XX_HASH_32.hash(Longs.toByteArray(key), 0, Long.BYTES, SEED);
    }
`
The times has dropped from 11.6s to 3.4 which is bigger than 2.2s which I have received on doubled keys. Probably hashing overhead is quite big. Also I have tried Long2ObjectOpenHashMap from fastutill and have received results in 2.8s. 
Maybe imprementation from netty is not the best The crate may use;) 
It would be great if you could evaluate other hashMaps, ie fastutil or eclipse-collections in case of performance, memory footprint and collision managing

**Comment by kamcio181** [comment]
@mfussenegger 
is there ETA for checking other hashMap implementations?

**Comment by mfussenegger** [comment]
> @mfussenegger
> is there ETA for checking other hashMap implementations?

No

**Comment by mfussenegger** [comment]
@kamcio181 short update here. Looks like we're going to work on this for the 4.8 release

**Comment by kamcio181** [comment]
@mfussenegger that's great news, thanks for handling this. Could you update me with some short description of solution you have used once you pick one?

**Comment by mfussenegger** [comment]
> @mfussenegger that's great news, thanks for handling this. Could you update me with some short description of solution you have used once you pick one?

Sure

**Comment by BaurzhanSakhariev** [comment]
Hi @kamcio181, we evaluated more different map options and some performed better on your data set but none perform consistently better than current implementation over all test data sets.
