### ISSUE TITLE
Remove hdfs support for snapshot repositories

### ISSUE THREAD

**Issue by mkleen** [crate/crate#11424]
The hdfs support for snapshot repositories to store snapshot data in a hadoop file system seems to have no users.

https://crate.io/docs/crate/reference/en/4.5/sql/statements/create-repository.html?highlight=hdfs#hdfs

Current issues with the plugin:

- The plugin pulls in a lot of external dependencies
- The plugin is not very well tested and not actively developed 

The plugin could be removed or handled over as community code to reduce maintenance.

**Comment by norosa** [comment]
does CrateDB support writing/reading snapshots from NFS mounts? the docs don't mention this

I ask for two reasons:

- NFS mounts do not provide POSIX file system behavior (e.g., atomicity). this means that for some purposes, they are unsuitable
- if Crate is able to handle NFS, that would mean that we support any data storage that can be mounted as an NFS mount (that includes [HDFS](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsNfsGateway.html)). we could mention this in the docs and list some common/useful NFS mount options
