### ISSUE TITLE
Support `$$` Dollar-quoted String Constants

### ISSUE THREAD

**Issue by proddata** [crate/crate#11512]
**Use case**:

> _**From postgresql.org**_
> While the standard syntax for specifying string constants is usually convenient, it can be difficult to understand when the desired string contains many single quotes or backslashes, since each of those must be doubled. To allow more readable queries in such situations, PostgreSQL provides another way, called “dollar quoting”, to write string constants.

replace
``` sql
INSERT INTO a_table (txt) VALUES ('Quotes shouldn''t be doubled')
```
with
``` sql
INSERT INTO a_table (txt) VALUES ($$ Quotes shouldn't be doubled $$)
```

---

replace
``` sql
INSERT INTO a_job_table (job) VALUES (
'INSERT INTO "tab_A"
    SELECT * FROM tab_b
    WHERE col1 = ''a'''
)
```
with
``` sql
INSERT INTO a_job_table (job) VALUES (
$$ INSERT INTO "tab_A"
    SELECT * FROM tab_b
    WHERE col1 = 'a'
$$
)
```

---

replace
```sql
CREATE FUNCTION symmetric_point(point geo_point)
RETURNS geo_point
LANGUAGE JAVASCRIPT
AS 
'function symmetric_point (point, angle) {
      var x = - point[0],
          y = - point[1];
      return ''POINT ('' + x + '', '' + y +'')'';
   }';
```
with
```sql
CREATE FUNCTION symmetric_point(point geo_point)
RETURNS geo_point
LANGUAGE JAVASCRIPT
AS 
$function$
function symmetric_point (point, angle) {
      var x = - point[0],
          y = - point[1];
      return 'POINT (' + x + ', ' + y +')';
   }
$function$;
```

**Feature description**:

> _**From postgresql.org**_
> A dollar-quoted string constant consists of a dollar sign ($), an optional “tag” of zero or more characters, another dollar sign, an arbitrary sequence of characters that makes up the string content, a dollar sign, the same tag that began this dollar quote, and a dollar sign. For example, here are two different ways to specify the string “Dianne's horse” using dollar quoting:

Support `$$` as alternative  for string constants

```sql
$$Dianne's horse$$
$SomeTag$Dianne's horse$SomeTag$
```

also see postgres implementation:
https://www.postgresql.org/docs/13/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

**Comment by jeeminso** [comment]
Hello @proddata, do we expect the nested version to be supported as part of this issue?

```
It is possible to nest dollar-quoted string constants by choosing different tags at each nesting level. This is most commonly used in writing function definitions. For example:

$function$
BEGIN
    RETURN ($1 ~ $q$[\t\r\n\v\\]$q$);
END;
$function$

```

**Comment by proddata** [comment]
No, I didn't consider nesting and don't think it is important, as we don't support plpgsql functions (yet).
@jeeminso
