### ISSUE TITLE
Unexpected behavior casting string literals to `ARRAY(INTEGER)`

### ISSUE THREAD

**Issue by nomicode** [crate/crate#11533]
I have split this issue into three sections:

- My attempts to cast a string literal to an integer array in CrateDB which ultimately require double cast (`::ARRAY(TEXT)::ARRAY(INTEGER)`) (which is not what is documented and is perhaps not the intended most-concise syntax)

- A note about the docs saying that the `::ARRAY()` syntax is for compatibility with PostgreSQL when, in fact, PostgreSQL does not support this syntax

- A note about casting string literals to an integer array in PostgreSQL (which uses the `::INTEGER[]` syntax instead of `::ARRAY(INTEGER)`)

## Casting to an integer array in CrateDB requires a double cast

The [current docs](https://crate.io/docs/crate/reference/en/4.5/general/ddl/data-types.html#array-constructor) indicate that I should be able to cast from a string literal to an array. The example provided in the docs does work:

```
cr> SELECT '{ab, CD, "CD", null, "null"}'::array(text) AS arr;
+----------------------------------+
| arr                              |
+----------------------------------+
| ["ab", "CD", "CD", null, "null"] |
+----------------------------------+
SELECT 1 row in set (0.002 sec)
```

However, if I try to do this with an array of integers, I get an error:

```
cr> SELECT '{1, 2}'::ARRAY(INTEGER) AS arr;
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

The explicit `CAST` syntax fails with the same error:

```
cr> SELECT CAST('{1, 2}' AS ARRAY(INTEGER));
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

This attempt to quote the integer values fails:

```
cr> SELECT '{"1", "2"}'::ARRAY(INTEGER) AS arr;
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

I expected the query above to fail, because I am using string syntax instead of integer syntax, and then trying to cast to an integer array. However, I thought I would try, in case I was missing something.

For what it's worth, the explicit `CAST` syntax fails with the same error:

```
cr> SELECT CAST('{"1", "2"}' AS ARRAY(INTEGER));
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

This does not produce an error:

```
cr> SELECT '{1, 2}'::ARRAY(TEXT) AS arr;
+------------+
| arr        |
+------------+
| ["1", "2"] |
+------------+
SELECT 1 row in set (0.003 sec)
```

However, I end up with an array of strings (as expected, but ultimately, not what I want).

For what it's worth, the explicit `CAST` syntax fails with the same error:

```
cr> SELECT CAST('{1, 2}' AS ARRAY(TEXT)) AS arr;
+------------+
| arr        |
+------------+
| ["1", "2"] |
+------------+
SELECT 1 row in set (0.002 sec)
```

Also, for the record, the two queries above are equivalent to:

```
cr> SELECT string_to_array('1,2', ',') as arr;
+------------+
| arr        |
+------------+
| ["1", "2"] |
+------------+
SELECT 1 row in set (0.001 sec)
```

The only way of getting it to work that I could find is this:

```
cr> SELECT '{1, 2}'::ARRAY(TEXT)::ARRAY(INTEGER) AS arr;
+--------+
| arr    |
+--------+
| [1, 2] |
+--------+
SELECT 1 row in set (0.002 sec)
```

Having to double cast seems counter-intuitive (i.e., unexpected) to me. Arguably, it disagrees with the docs, because they seem to *imply* that you can cast using the ``::`` syntax to any type of array. At the very least, if this is the intended most-concise syntax, the current docs omit this information.

This also works:

```
cr> SELECT '{1, 2}'::ARRAY(TEXT)::INTEGER[] AS arr;
+--------+
| arr    |
+--------+
| [1, 2] |
+--------+
SELECT 1 row in set (0.002 sec)
```

For what it's worth, the double-cast technique works with explicit `CAST` syntax too:

```
cr> SELECT
        CAST(
            '{1, 2}' AS ARRAY(TEXT)
        )::ARRAY(INTEGER) AS arr_1,
        CAST(
            '{1, 2}' AS ARRAY(TEXT)
        )::INTEGER[] AS arr_2;
+--------+--------+
| arr_1  | arr_2  |
+--------+--------+
| [1, 2] | [1, 2] |
+--------+--------+
SELECT 1 row in set (0.003 sec)
```

```
cr> SELECT
        CAST(
            CAST(
                '{1, 2}' AS ARRAY(TEXT)
            ) AS ARRAY(INTEGER)
        ) AS arr_1,
        CAST(
            CAST(
                '{1, 2}' AS ARRAY(TEXT)
            ) AS INTEGER[]
        ) AS arr_2;
+--------+--------+
| arr_1  | arr_2  |
+--------+--------+
| [1, 2] | [1, 2] |
+--------+--------+
SELECT 1 row in set (0.003 sec)
```

However, you cannot cast directly to `INTEGER[]`:

```
cr> SELECT '{1, 2}'::INTEGER[];
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

```
cr> SELECT CAST('{1, 2}' AS INTEGER[]);
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

I tried with some different string formats:

```
cr> SELECT 'ARRAY[1, 2]'::INTEGER[];
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

```
cr> SELECT '[1, 2]'::INTEGER[];
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

```
cr> SELECT '1, 2'::INTEGER[];
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

## PostgreSQL compatibility and the `::ARRAY()` syntax

Maybe worth noting: The docs say that the `::ARRAY()` syntax exists for PostgreSQL compatibility. However, all of the queries that use this syntax fail for PostgreSQL.

```
nomi=# SELECT '{ab, CD, "CD", null, "null"}'::array(text) AS arr;
ERROR:  syntax error at or near "array"
```

```
nomi=# SELECT '{1, 2}'::ARRAY(INTEGER) AS arr;
ERROR:  syntax error at or near "ARRAY"
```

```
nomi=# SELECT '{"1", "2"}'::ARRAY(INTEGER) AS arr;
ERROR:  syntax error at or near "ARRAY"
```

```
nomi=# SELECT '{1, 2}'::ARRAY(TEXT) AS arr;
ERROR:  syntax error at or near "ARRAY"
```

```
nomi=# SELECT '{1, 2}'::ARRAY(TEXT)::INTEGER[] AS arr;
ERROR:  syntax error at or near "ARRAY"
```

```
nomi=# SELECT '{1, 2}'::ARRAY(TEXT)::ARRAY(INTEGER) AS arr;
ERROR:  syntax error at or near "ARRAY"
```

## Casting to an integer array in PostgreSQL using `::INTEGER[]`

In PostgreSQL, you can use the `'{1, 2}'::INTEGER[]` syntax, like so:

```
nomi=# SELECT
     arr,
     pg_typeof(arr) AS arr_type,
     arr[1] AS arr_first_val
FROM (
    SELECT '{1, 2}'::INTEGER[] AS arr
) as t;
  arr  | arr_type  | arr_first_val
-------+-----------+---------------
 {1,2} | integer[] |             1
(1 row)
```

Sorry for the convoluted query. I wanted to unambiguously demonstrate the result array, confirmation of its type, and the ability to select an element.

For what it's worth, this "proof" query works for the CrateDB `::ARRAY(TEXT)::ARRAY(INTEGER)` construct demonstrated before:

```
cr> SELECT
         arr,
         pg_typeof(arr) AS arr_type,
         arr[1] AS arr_first_val
    FROM (
        SELECT '{1, 2}'::ARRAY(TEXT)::ARRAY(INTEGER) AS arr
        UNION ALL
        SELECT '{1, 2}'::ARRAY(TEXT)::INTEGER[] AS arr
    ) as t
+--------+---------------+---------------+
| arr    | arr_type      | arr_first_val |
+--------+---------------+---------------+
| [1, 2] | integer_array |             1 |
| [1, 2] | integer_array |             1 |
+--------+---------------+---------------+
SELECT 2 rows in set (0.050 sec)
```

CrateDB, however, does not work with `::INTEGER[]` alone, as PostgreSQL does:

```
cr> SELECT
         arr,
         pg_typeof(arr) AS arr_type,
         arr[1] AS arr_first_val
    FROM (
        SELECT '{1, 2}'::INTEGER[] AS arr
    ) as t;
SQLParseException[Cannot cast expressions from type `text` to type `integer_array`]
```

**Comment by mfussenegger** [comment]
> A note about the docs saying that the ::ARRAY() syntax is for compatibility with PostgreSQL when, in fact, PostgreSQL does not support this syntax

I think this is just unfortunate structuring in the documentation. The note regarding the compatibility is in regards to the array constructor syntax `ARRAY[...]` not in regards to the cast.


> However, if I try to do this with an array of integers, I get an error:

I think for now we should clarify that the `text → array` conversion only works for text and not for array types.

We can consider to extend that, *if* a concrete use-case arises, but until there is one I wouldn't extend the functionality. The recommended way to use arrays is via parameter placeholders, followed by the array constructor syntax.
