### ISSUE TITLE
Support node switch to SSL/no-SSL depending where the other node is in multi-zone setup.

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11546]
dual mode is not supported anymore, see https://github.com/crate/crate/issues/11545.

If encryption for inter-zone communication is needed, every node must support SSL as communications are point-to-point and node can connect to another node in another zone. However, node might switch to no-SSL communication if peer node is in the same zone.

**Comment by BaurzhanSakhariev** [comment]
Implementation thoughts:

As communications are point to point, all nodes must have SSL enabled if encryption is needed (multi zone cluster case).

As SSL is guaranteed by config (we will add this to multi cluster docs or other relevant place) it's possible to do handshake first (add SslHandler), than update `HostBasedAuthHandler` to check `autheticationType` and if it's trust, then remove not only  `HostBasedAuthHandler` itself but inserted previously `SSLHandler`.

**Comment by BaurzhanSakhariev** [comment]
Current implementation:

Default behavior - no encryption, transport.mode=legacy.
If users want encryption, they must set [trasnport.mode=on (see Tip)](https://crate.io/docs/crate/reference/en/master/admin/ssl.html) and [ssl =on method cert in HBA ](https://crate.io/docs/crate/reference/en/master/admin/auth/hba.html#node-to-node-communication) but encryption will be used for all connections.

4.7

 _"SSL for inter-zone exchange, no-SSL inside zone"_

 use HBA and methods trust/cert and subnet masks to split cluster into nodes as suggested in [ initial implementation docs](https://github.com/crate/crate/pull/11353/files#diff-068a24ef8c4490ccc059c02a8bfa68b075441f7b64c4072468f9ac3850b44e6dR213) 
 
 1. Default behavior - no encryption, transport.mode=off. Legacy mode can be removed, for transport protocol
 we can use 
```
if (AuthSettings.AUTH_HOST_BASED_ENABLED_SETTING.get(settings) && sslMode != OFF ) 
```
instead of `if (AuthSettings.AUTH_HOST_BASED_ENABLED_SETTING.get(settings) && sslMode != LEGACY ) `
We don't use method password for transport protocol, so it's either cert or trust. 
if ssl is off, another valid method is trust which is equivalent of not having HbaHandler at all so we can safely use `!=OFF`

2. If users want encryption, they must set `transport.mode = on `and configure keystore on **ALL** nodes - as communications are point to point - same as current implementation. As a consequence, users must add an HBA entry for transport but it's not breaking change as encryption is not default. We would need to add to docs that HBA with (zone subnet + trust) lets to switch to non-SSL inside zones. Then we can restore example with HBA subnet config and suggest to leverage trust/cert to switch to non-SSL.

To sum up:
- No breaking changes, default config would work
- drop legacy mode
- restore HBA example showing how to configure zones

Implementation details:
HostBasedAuthHandler presence means that `transport = on` and SSLHandler was inserted previously into the pipeline. We can update it to remove SSLHandler if `authenicationtype` is `trust`. 

If encryption is needed and some nodes have SSL enabled but users forget to enable SSL on some node, incoming SSL connections would fail with[ SSL is not enabled](https://github.com/crate/crate/commit/d03221b2abc89e29578a7ec5f128988e577afc42#diff-2ddded9587e2d801d53abb61a04e593a27f9ff287471149d8182bc77c0993c67R796)
and outgoing plaintext connections would case failure on ssl enabled nodes "not an SSL/TLS record" so users can easily figure out which node is misconfigured.

**Comment by mfussenegger** [comment]
Closing this for now as this afaik hasn't come up as a requirement again.

Please leave feedback if there is a concrete use-case for this
