### ISSUE TITLE
Support PostgreSQL's FETCH clause

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#11540]
**Use case**:
Certain PostgreSQL-compatible tools send queries with a `FETCH` clause to the server:
```
SELECT *
FROM usertable
ORDER BY ycsb_key
FETCH FIRST 2 ROWS ONLY;
```
In this particular case, the query originates from the [YCSB](https://github.com/brianfrankcooper/YCSB/) benchmark suite.

On PostgreSQL, the query succeeds. On CrateDB, the query fails as the `FETCH` clause is not supported.

**Feature description**:
PostgreSQL supports a `FETCH` clause as part of its `SELECT` [command](https://www.postgresql.org/docs/13/sql-select.html):
```
SELECT [...]
    [ LIMIT { count | ALL } ]
    [ OFFSET start [ ROW | ROWS ] ]
    [ FETCH { FIRST | NEXT } [ count ] { ROW | ROWS } { ONLY | WITH TIES } ]
```

According to the documentation, it's part of the SQL standard:
> SQL:2008 introduced a different syntax to achieve the same result, which PostgreSQL also supports.

Except for the `WITH TIES` part, the same functionality can be achieved in CrateDB via a `LIMIT` clause. But special treatment is needed in client tools like YCSB that make use of `FETCH` to restore compatibility with CrateDB.

**Comment by matriv** [comment]
I'd like to take a look at this.

**Comment by matriv** [comment]
Opened a new [issue](https://github.com/crate/crate/issues/12607)  for supporting the `WITH TIES`.
