### ISSUE TITLE
Selecting on non-existing object-properties, leads to an error instead of returning null

### ISSUE THREAD

**Issue by proddata** [crate/crate#11575]
**CrateDB version**:
4.5.3 / 4.6

**Environment description**:
cloud / local

**Problem description**:
Selecting on non-existing object-properties, leads to an error instead of returning null. This is not quite consistent with selecting on object-properties in a table, which in case an object doesn't contain a property, returns `null` instead.

The idea would be to use it to directly ingest JSONs into a table and make use of parameterised queries / prepared statements.

**Steps to reproduce**:

```sql
SELECT ''::OBJECT['x'];
--> Error! SQLParseException[The object `{}` does not contain the key `x`]
SELECT '{"x":1}'::OBJECT['y'];
--> Error! SQLParseException[The object `{x=1}` does not contain the key `y`]
``` 

```sql
SELECT col1['x'], col1['y'], col1['z']
FROM UNNEST(['{"x":1,"y":2}','{"y":2,"z":3}']::ARRAY(OBJECT));
--> Error! ColumnUnknownException[Column col1['x'] unknown]
```

not a problem:
```sql
SELECT col1['y']
FROM UNNEST(['{"x":1,"y":2}','{"y":2,"z":3}']::ARRAY(OBJECT));
--> SELECT OK, 2 records returned (0.001 seconds)
```

with tables it typically isn't a problem if properties don't exist within objects:
```sql
CREATE TABLE obj (obj OBJECT(DYNAMIC));
INSERT INTO obj (obj) VALUES ('{"x":1,"y":2}'),'{"y":2,"z":3}');
SELECT obj['x'], obj['y'], obj['z'] FROM obj;
--> SELECT OK, 2 records returned (0.001 seconds)
```

relates to https://github.com/crate/crate/issues/6553

**Comment by mfussenegger** [comment]
This is somewhat related to https://github.com/crate/crate/issues/6553 and https://github.com/crate/crate/issues/9383

We could consider extending how we create the type information for `unnest`, so that the `object` will contain columns based on all rows.
