### ISSUE TITLE
Array comparisons with varchar(n) arrays are slow due to casting

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11603]
### CrateDB version

4.6.1

### Observed behavior

Running queries with array comparisons (`IN` / `ANY` / `ALL`) on limited varchar arrays are slower than array comparisons on a text array column. This is due to implicit cast from varchar to text.

### Steps to Reproduce

Table:

```
create table any_test (content array(varchar(1)));]
```

Create sample data:

```
mkjson --num 100000 content="array(fromRegex('[a-z]'),fromRegex('[a-z]'),fromRegex('[a-z]'))"  | cr8 insert-json --table any_test --hosts localhost:4200
```

Query:

```
select count(*) from any_test where 'a' = any(content);
```

Explain:

```
Limit[100::bigint;0]
  └ Count[doc.any_test | ('a' = ANY(_cast(content, 'array(text)')))]
```

When casting `a` to be a varchar(1) the query is as fast as a text array comparison

```
select count(*) from any_test where 'a'::varchar(1) = any(content);
```

`ALL` and `IN` show the same behaviour.

**Comment by mfussenegger** [comment]
Thanks for the report. This will be fixed with the next 4.6 release
