### ISSUE TITLE
Cannot invoke "org.elasticsearch.common.bytes.BytesReference.length()" because "bytes" is null

### ISSUE THREAD

**Issue by amotl** [crate/crate#11600]
### CrateDB version

`>=4.3.0`

#### Run and connect to CrateDB
While we are using CrateDB 4.6.1 here, we verified that it worked with CrateDB 4.2.6 and regressed with CrateDB 4.3.0 already.
```bash
docker run -it --rm --publish=4200:4200 --publish=5432:5432 crate/crate:4.6.1
```

```bash
psql postgres://crate@localhost:5432
```

#### Invoke SQL statements
We trimmed this down, originally coming from the test suite of `crate-iot-config` and reported by @thdud1744, thanks!
```sql
DROP TABLE IF EXISTS testdrive;

CREATE TABLE IF NOT EXISTS testdrive (
    id TEXT PRIMARY KEY, 
    name TEXT, 
    template TEXT, 
    d OBJECT(IGNORED), 
    INDEX name_search USING FULLTEXT(name) WITH (analyzer = 'standard')
) CLUSTERED INTO 1 SHARDS WITH ( number_of_replicas='0', column_policy='strict' );

-- Insert and query data, filtering by attribute in OBJECT field. This produces the expected results.
INSERT INTO testdrive (id, name, template, d) VALUES ('testing-007', 'testing 007', 'machine', '{"serial":"007","model":"SDB160"}');
REFRESH TABLE testdrive;
SELECT * FROM testdrive WHERE testdrive.d['serial'] = '007';

-- Purging the table's content and querying again fails badly. It should just say "0 rows" here.
DELETE FROM testdrive;
REFRESH TABLE testdrive;
SELECT * FROM testdrive WHERE testdrive.d['serial'] = '007';
```

### Expected Result

```
 id | name | template | d
----+------+----------+---
(0 rows)
```

### Actual Result

```
ERROR:  Cannot invoke "org.elasticsearch.common.bytes.BytesReference.length()" because "bytes" is null
```

---

/cc @thdud1744, @quodt, @WalBeh

**Comment by amotl** [comment]
FYI: The same error message, `Cannot invoke "org.elasticsearch.common.bytes.BytesReference.length()" because "bytes" is null` was reported by @shm-dmitry at #10851, where we haven't been able to find an appropriate reproduction.

**Comment by BaurzhanSakhariev** [comment]
same scenario works if I remove "IGNORED" keyword, i.e let new fields be indexed. It's not resolving the issue, it still has to be addressed just an observation/workaround

**Comment by mfussenegger** [comment]
Although this will be fixed with the next hotfix release I'd recommend to change the schema if `testdrive.d['serial']` is often used in predicates.

Querying on nested columns of a `OBJECT(IGNORED)` type is very expensive as those are not indexed.
