### ISSUE TITLE
We are seeing dangling index after dropping a table

### ISSUE THREAD

**Issue by nazar200** [crate/crate#11620]
### CrateDB version

4.1.8

### CrateDB setup information

Number Nodes: 74

### Steps to Reproduce

We have dropped the tables from the cluster.

got the below error in the master log.

stdout.log:[2021-07-15T10:04:17,089][WARN ][o.e.g.DanglingIndicesState] [master-xxxxx] [[doc..partitioned.table.04732dhg64qj2c1k60o30c1g/NYtx6xcTRM2Gf2LXueH0KQ]] can not be imported as a dangling index, as index with same name already exists in cluster metadata
[[doc..partitioned.table.04732dhg64qj2c1k60o30c1g/NYtx6xcTRM2Gf2LXueH0KQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state

and we see many shards in "UNASSIGNED".

### Expected Result

We expect all tables and its shards will get removed.

### Actual Result

Table got cleared but not the shards details

**Comment by proddata** [comment]
Hi Nazar, @nazar200 

The repo is for feature requests or reproduce-able bug reports only.

I would kindly ask you to move the question to https://community.crate.io/ or if you have an ongoing support contract with Crate.io, contact us through the official support channels.

Best regards
Georg
