### ISSUE TITLE
ERROR: IllegalStateException

### ISSUE THREAD

**Issue by zhangyatao123456** [crate/crate#11636]
**Use case**:
ERROR: IllegalStateException
**Feature description**:
执行语句
ALTER TABLE s_56.d_695_codes SET (number_of_shards = 1);
错误信息：
ERROR: IllegalStateException: index s_56.d_695_codes must have all shards allocated on the same node to shrink index

怎么样看了这个
https://crate.io/docs/crate/reference/en/4.6/sql/statements/alter-table.html#sql-alter-table-reroute
不知道怎么使用啊！

**Comment by amotl** [comment]
Hi @zhangyatao123456,

thanks for writing in. @jayeff responded to your request at https://github.com/crate/crate/issues/11576#issuecomment-893247576 already. Hope this helps!

With kind regards,
Andreas.

**Comment by zhangyatao123456** [comment]
如何移动 SHARD 啊，能提供一个示例吗？
