### ISSUE TITLE
Update to Lucene 8.9.0 and adapt doc value compression

### ISSUE THREAD

**Issue by mkleen** [crate/crate#11647]
The update to Lucene 8.9.0 caused a performance regression https://github.com/crate/crate/commit/573bd2feb9052f9a83c01bd36cfb3c7485d0e9d3 and was therefore reverted.

The change https://issues.apache.org/jira/browse/LUCENE-9663 caused the regression and is active when doc value compression `Lucene80DocValuesFormat.Mode.BEST_COMPRESSION` is enabled, which is the default configuration for CrateDB. 

We should measure the performance and storage size implications to switch to `Lucene80DocValuesFormat.Mode.BEST_SPEED` to be able to update to Lucene 8.9.0

**Comment by mfussenegger** [comment]
Done with https://github.com/crate/crate/pull/11658 and https://github.com/crate/crate/pull/11659

We'll get further results for any performance implications via the nightly benchmarks.
