### ISSUE TITLE
Support setting a different endpoint for COPY TO / FROM for DNS-style S3 bucket adresses

### ISSUE THREAD

**Issue by proddata** [crate/crate#11654]
**Use case**:
I want to be able to export data from CrateDB using `COPY TO / FROM` with (AWS) S3-compatible technologies like Minio, so that I don't rely on AWS for my storage setup.

**Feature description**:
With AWS SDK the endpoint defaults to `<bucket>.s3.amazonaws.com`.  In order to use my Minio S3 bucket, I am able to enter my own endpoint in the URI for COPY FROM / TO commands. The ability to use AWS S3 is not affected.

---

Origin:  https://community.crate.io/t/export-table-using-copy-to-command-to-alternate-s3-endpoint/246/4

S3 Client Helper: https://github.com/crate/crate/blob/b8f5bfc1ae1d34b0426f2a01217fde663505225b/server/src/main/java/io/crate/external/S3ClientHelper.java

**Comment by protosam** [comment]
Would be nice to rely on S3 compatible storage. Google Cloud Platform storage has S3 compatibility, there's Digital Ocean, Linode, and Vultr as well that offer S3 compatible object storage as well.

As-is, I am using s3fs as a bandaid with `file://`.

**Comment by protosam** [comment]
Looks like changes would be needed somewhere in these files.

https://github.com/crate/crate/blob/df77bd0147b960da9e905351dc6a8c833c5ac26b/server/src/main/java/io/crate/execution/engine/export/OutputS3.java#L91

https://github.com/crate/crate/blob/df77bd0147b960da9e905351dc6a8c833c5ac26b/server/src/main/java/io/crate/external/S3ClientHelper.java#L88-L118

**Comment by mfussenegger** [comment]
Somewhat related to this - which can be done either before or as a follow-up: We should move the COPY/FROM/TO S3 related logic outside of `server` into a dedicated module.

We already have [FileInputFactory](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/engine/collect/files/FileInputFactory.java) and [FileInput](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/engine/collect/files/FileInput.java) 

Currently there are loaded via the [FileCollectModule](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/engine/collect/files/FileCollectModule.java) but we could turn this into a `CopyPlugin` or so which uses a pull pattern.

**Comment by proddata** [comment]
@mfussenegger do you think it might be possible to reuse the files shares from the snapshot repositories?

**Comment by mfussenegger** [comment]
> @mfussenegger do you think it might be possible to reuse the files shares from the snapshot repositories?

It would be feasible to factor out some common base between the two, but not sure if we'd gain enough from that to warrant putting in the effort.

**Comment by emres** [comment]
> Would be nice to rely on S3 compatible storage. Google Cloud Platform storage has S3 compatibility, there's Digital Ocean, Linode, and Vultr as well that offer S3 compatible object storage as well.
> 
> As-is, I am using s3fs as a bandaid with `file://`.

In addition to the above, there are also other S3-compatible storage systems such as [Nutanix Object Storage](https://www.nutanix.com/products/objects) which I'm using in one of my clients (so far it works as expected with utilities such as [s5cmd](https://github.com/peak/s5cmd) and [Cyberduck](https://cyberduck.io/).)

Therefore it'll be very good if CrateDB provides enough flexibility with different S3-compatible object storage systems.

**Comment by jeeminso** [comment]
Closing this issue, all necessary changes are now merged.

The scope of this issue was to delegate the provided s3 endpoints to AWS SDK. There still could be problems between SDK and the s3 compatible storage, ex) #12094. So, please try this feature with the latest nightly build.

The latest nightly build can be found at: https://cdn.crate.io/downloads/releases/nightly/
The steps to install and run: https://crate.io/docs/crate/tutorials/en/latest/install.html#ad-hoc-unix-macos-windows
Also have a few sample copy from/to statements, [here](https://github.com/crate/crate/pull/12052#issue-826108977) and [here](https://github.com/crate/crate/pull/12052#issuecomment-1027158755).

Thank you!
