### ISSUE TITLE
RepositoryVerificationException

### ISSUE THREAD

**Issue by zhangyatao123456** [crate/crate#11657]
### CrateDB version

4.2.1

### CrateDB setup information

在创建cratedb 2个节点 创建快照的时候
创建语言：create repository mysnapdata2 type fs with (location='/data/crate/snapdata', compress=true);
错误如下：
![image](https://user-images.githubusercontent.com/20138947/129525307-68bd4e3a-0c23-4a56-ac0c-efc851f16faa.png)

### Steps to Reproduce

dd

### Expected Result

ss

### Actual Result

SQLActionException[RepositoryVerificationException: [mysnapdata2] [[f8HD24feSH2WC0269ciKkA, 'RemoteTransportException[[172.16.21.9][172.16.21.9:4300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[mysnapdata2] a file written by master to the store [/data/crate/snapdata] cannot be accessed on the node [{172.16.21.9}{f8HD24feSH2WC0269ciKkA}{uV7viSI_Tj6dTxKz7L4sCw}{172.16.21.9}{172.16.21.9:4300}{http_address=172.16.21.9:4200}]. This might indicate that the store [/data/crate/snapdata] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];']]]

**Comment by seut** [comment]
The exception message `a file written by master to the store [/data/crate/snapdata] cannot be accessed on the node [{172.16.21.9}{f8HD24feSH2WC0269ciKkA}{uV7viSI_Tj6dTxKz7L4sCw}{172.16.21.9}{172.16.21.9:4300}{http_address=172.16.21.9:4200}]. This might indicate that the store [/data/crate/snapdata] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node` already indicates possible issues. Please check mentioned problems first.

If it still does not solve your issue and you think this is a bug, please report back with detailed environment information and reproduction steps.

We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please checkout https://crate.io/support/ for support options.

**Comment by zhangyatao123456** [comment]
上面的问题已经解决！是要做nfs这个东西！

**Comment by zhangyatao123456** [comment]
在问一个问题！
添加写的节点无法数据重新平衡！我本来有4个节点，现在添加一个新的节点，查看监控，这个数据节点已经在集群里了，但是查看监控发现Started==0数据也没有改变，但是我创建写的表，数据可以分配到新的节点上来，为什么老的数据不能平衡呢？
