### ISSUE TITLE
OperationOnInaccessibleRelationException

### ISSUE THREAD

**Issue by zhangyatao123456** [crate/crate#11665]
### CrateDB version

4.2.1

### CrateDB setup information

执行第一次 
drop table  "s_148"."d_1154_words" 
告诉我已经成功，我去查询监控，这个表并没有被删除！
![image](https://user-images.githubusercontent.com/20138947/130204002-d43bebd4-0fd6-4c1e-8a15-4a47cd77f896.png)
我就在执行一次
drop table  "s_148"."d_1154_words" 
![image](https://user-images.githubusercontent.com/20138947/130204100-03a5bf71-5a5a-45ab-ae30-e57a51619b2a.png)
就出现了这个问题！

### Steps to Reproduce

ee

### Expected Result

ee

### Actual Result

ee

**Comment by proddata** [comment]
Hi @zhangyatao123456 

Did you remove one node before trying to delete the table?
Was the cluster disk space running full?

My current theory would be, that the table only had one shard residing on a node, that was not gracefully removed from the cluster.

**Comment by jayeff** [comment]
closing this due to no further input. please re-open if this issue still persists
