### ISSUE TITLE
Regression for `RESTORE SNAPSHOT ... USERS` from 4.5.5 to 4.6.x

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11671]
### CrateDB version

4.6.1

### CrateDB setup information

local

### Steps to Reproduce

Create user, repository and snapshot:

```
CREATE USER test1;

CREATE REPOSITORY azurerepo TYPE azure
WITH (account = '<account>', container = '<container>', key ='<key>');

CREATE SNAPSHOT azurerepo.backup1 ALL;
```

Drop user:
```
DROP USER test1;
```

Restore users from snapshot:
```
RESTORE SNAPSHOT azurerepo.backup1 USERS;
```

### Expected Result

```
SELECT name FROM sys.users;
-- crate
-- test1
```

### Actual Result

```
SELECT name FROM sys.users;
-- crate
```

### Additional notes

`RESTORE SNAPSHOT azurerepo.backup1 USERS;` does work with 4.5.5
`RESTORE SNAPSHOT azurerepo.backup1 ALL | METADATA;` does restore user test1 on 4.6.x

**Comment by seut** [comment]
@jayeff Thanks for reporting, we can reproduce it and working on a fix.
