### ISSUE TITLE
Expose actual partition values in `sys.snapshots` table in order to identify partitions

### ISSUE THREAD

**Issue by proddata** [crate/crate#11700]
**Use case**:
As a CrateDB user I want to make use of the snapshot feature to keep old data in a cold compressed state in a storage repository, to keep my cluster size moderate.

```sql
CREATE REPOSITORY repo TYPE fs WITH (location='my_snap', compress=true); 
```

```sql
CREATE TABLE tab (txt TEXT, month INT) PARTITIONED BY(month);
INSERT INTO tab VALUES ('Hello',1);
```

```sql
CREATE SNAPSHOT repo.snap_1 TABLE my_snap with ("wait_for_completion"=true);
--> snapshot contains partition 1 only
```

```sql
INSERT INTO tab VALUES ('World',2);
```

```sql
DELETE FROM tab WHERE part = 1;
```

```sql
CREATE SNAPSHOT repo.snap_2 TABLE my_snap with ("wait_for_completion"=true); 
--> snapshot contains partition 2 only
```

and so on ...

---

A few month later I might want to check some older data and restore only the data for month 1.
If I know which snapshot contains data for `month=1` I can restore it with the following:

```sql
RESTORE SNAPSHOT repo.snap_1 table my_snap PARTITION (month=1); 
```

**Feature description**:

Similiar to ` information_schema.table_partitions` the table `sys.snapshots` should also include the actual partition values and not only the hashed `partition_ident`.

Then it would be possible to check which months are stored within the snapshot repository by using e.g.

```sql
SELECT * FROM sys.snapshots
```

**Comment by mfussenegger** [comment]
Sounds good. Any suggestions for the format?

We already got `tables` as `string[]` and `concrete_indices` as `string[]`. Maybe `table_partitions` as `array(object(table text, values string[]))` ?
We may lack the meta data information of the table, so we don't know the column names of the partitions and can only provide the values. (`information_schema.table_partitions` exposes a key-value map for the partition values)

**Comment by proddata** [comment]
By `values string[]` you mean the hashed partition idents? 

Afaik `information_schema.table_partitions` only holds information for currently existing partitions, but not those which only exist in a snapshot. e.g. (only part = [2,3])
```sql
cr> SELECT table_schema, table_name, partition_ident, values  
     FROM information_schema.table_partitions;  
+--------------+------------+-----------------+-------------+
| table_schema | table_name | partition_ident | values      |
+--------------+------------+-----------------+-------------+
| doc          | my_snap    | 04134           | {"part": 2} |
| doc          | my_snap    | 04136           | {"part": 3} |
+--------------+------------+-----------------+-------------+
SELECT 2 rows in set (0.000 sec)
```

```sql
cr> SELECT concrete_indices, tables FROM sys.snapshots;                                                                                                                                                                 
+--------------------------------------------------------------------------------------------+-----------------+
| concrete_indices                                                                           | tables          |
+--------------------------------------------------------------------------------------------+-----------------+
| [".partitioned.my_snap.04132", ".partitioned.my_snap.04136", ".partitioned.my_snap.04134"] | ["doc.my_snap"] |
+--------------------------------------------------------------------------------------------+-----------------+
SELECT 1 row in set (0.001 sec)
```

i.e. in order to find the latest snapshot (or check if it even exists) for `part=1` I would either try to bruteforce restore them or need the actual partition values `{"part": 1}`
