### ISSUE TITLE
Installation of CrateDB on multiarch VM throwing error 

### ISSUE THREAD

**Issue by msbt** [crate/crate#11701]
### CrateDB version

4.6.1

### CrateDB setup information

Not really a bug, but I tried installing CrateDB following the steps here on a linux VM (virtualbox) and the add repo command didn't go through:
https://crate.io/docs/crate/tutorials/en/latest/install.html#configure-package-repository

### Steps to Reproduce

Follow instructions on https://crate.io/docs/crate/tutorials/en/latest/install.html#configure-package-repository on an Ubuntu 20.04 VM.

After 
`sudo add-apt-repository "deb https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"`
it threw this error
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://cdn.crate.io/downloads/deb/stable focal InRelease' doesn't support architecture 'i386'

According to this post https://askubuntu.com/a/741411 this results from multiarch system and can be fixed by specifically adding `[arch=amd64]` in the sources link (instead of removing the 32 bit architecture which might crash some other applications). So instead we could use this:
`sudo add-apt-repository "deb [arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"`

For reference
```
$ uname -a
Linux ubuntu-VirtualBox 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg --print-foreign-architectures
i386

$ dpkg --print-architecture
amd64
```

### Expected Result

Smooth installation.

### Actual Result

Adding the sources link resulted in the error above.

**Comment by amotl** [comment]
Hi Matthias,

thanks for the report. I've just submitted https://github.com/crate/crate-tutorials/pull/73 in order to improve the situation.

With kind regards,
Andreas.

**Comment by amotl** [comment]
The update to the documentation has been merged, see [1].

[1] https://crate.io/docs/crate/tutorials/en/latest/install.html#configure-package-repository
