### ISSUE TITLE
Failed to insert the value of objects into table (Is cratedb support the storage of an array of object ? ).

### ISSUE THREAD

**Issue by Ajaysamdyan** [crate/crate#11710]
### CrateDB version

4.6

### Steps to Reproduce

1. CREATE TABLE my_table_arrays ( tags array(text), objects array(object as (age integer, name text)));
2. INSERT INTO my_table_arrays ( tags array(text), objects array(object as (age, name))) value ('27', 'AJAY');
3. CREATE TABLE my_table13 ( title text,  author object as ( name text, birthday timestamp with time zone )); 
4. INSERT INTO my_table13 (  title text,  author object as ( name text, birthday timestamp with time zone )) value ('27', 'AJAY');

### Expected Result

The insert query should be executed successfully without showing any error.

### Actual Result

I have found various excerptions during execution of insert query statement for both dynamic and strict cases.
I just want to know that is there any way to insert the array of objects value in the table or is it possible to store the object value in both dynamic and strict cases. 
If yes than , please provide me the exact insert query.

**Comment by BaurzhanSakhariev** [comment]
Hi @Ajaysamdyan , thanks for your report.

Column type after `INTO table_name` is not needed, i.e. `INSERT INTO my_table_arrays (tags, objects)...` is enough.

All columns listed in the `INTO` clause must have corresponding values - in the example above there is 27, AJAY which I believe values for age and name but no values for tags. For arrays we need to enclose values into square brackets. More details about inserting objects can be found in the [Inserting Objects](https://crate.io/docs/crate/reference/en/4.6/general/ddl/data-types.html#object-literals) section of documentation.

If skipping tags was the intention, we either don't mention them in the `INTO` clause: 
` INSERT INTO my_table_arrays (objects) values ([{age = 27, name = 'AJAY'}]);   `

 or provide some value (can be [] or null)

  `INSERT INTO my_table_arrays (tags, objects) values (null, [{age = 27, name = 'AJAY'}]); ` 
`  INSERT INTO my_table_arrays (tags, objects) values ([], [{age = 27, name = 'AJAY'}]);    `

**Comment by Ajaysamdyan** [comment]
Hi @BaurzhanSakhariev , Thank you for your quick response. Yes, it is working now.

**Comment by Ajaysamdyan** [comment]
Hi @BaurzhanSakhariev . Can you please tell me that do new versions of Crate support inserting and then querying an arbitrary JSON array?.   In other words, would this work with a recent version of Crate
CREATE  TABLE t (x array)
INSERT INTO t (x) VALUES ( [ 1, "yo!", true, { k = 2, h = 'foo' } ] )

and if does, then how can you query column x.

Thanks in advance.

**Comment by proddata** [comment]
Hi @Ajaysamdyan 

This repository is mostly for actual feature requests or reproducible bug reports.
Please use https://community.crate.io/ for questions using CrateDB or contact the official Crate.io support.

---

- All array elements must have the same data type, which determines the inner type of the array
- CrateDB currently does only support JSON-String / properties embedded in curly brackets `{ }`

Your best workaround would be to use a `ARRAY(TEXT)` and filter/cast on query.

also see https://github.com/crate/crate/issues/11714
