### ISSUE TITLE
Lacking PostgreSQL compatibility in DataGrip

### ISSUE THREAD

**Issue by rafaelasantana** [crate/crate#11726]
Dear CrateDB team, 

I am using DataGrip and trying to connect to CrateDB (version 4.6.1) with the PostgreSQL JDBC driver. 

SImilarly to https://github.com/crate/crate/issues/11697, when I try to connect I get the exception **ERROR: Relation 'pg_catalog.pg_locks' unknown.**

Although the connection to CrateDB can be established using the crate-jdbc driver, the compatility to PostgreSQL could be improved.

Kind regards,

Rafaela

**Comment by mfussenegger** [comment]
Thanks for the report.

We'll have to add (an empty) https://www.postgresql.org/docs/current/view-pg-locks.html 

For potential contributors, this can be done similar to how it was done in https://github.com/crate/crate/pull/11706

**Comment by proddata** [comment]
The full query is
```sql
select L.transactionid::varchar::bigint as transaction_id
from pg_catalog.pg_locks L                                                                               
where L.transactionid is not null                                                                        
order by pg_catalog.age(L.transactionid) desc                                                            
limit 1;
```

i.e. also the `pg_catalog.age(<timestamp>)` function is missing
see https://www.postgresql.org/docs/13/functions-datetime.html
