### ISSUE TITLE
Canceling queries via JDBC doesn't work

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#11723]
### CrateDB version

4.6.1

### CrateDB setup information

PostgreSQL JDBC driver 42.2.23
DBeaver 21.2.0
DataGrip 2021.2.2

### Steps to Reproduce

In both [DBeaver](http://dbeaver.io) and [DataGrip](https://www.jetbrains.com/datagrip/) (using JDBC to connect to CrateDB), it can be observed that canceling a running query doesn't actually cancel the query. Instead, it keeps running.

Steps to reproduce:
1. Write any SELECT query that will run for a couple of seconds and execute it (depending on the data you have available locally)
2. While the query is still running, click the button in the tool's UI for canceling the query

I debugged the PostgreSQL JDBC driver and could identify that canceling the query in both tools triggers a call of [QueryExecutorBase#sendQueryCancel()](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/core/QueryExecutorBase.java#L169). The `cancelPid` attribute is `0`, so the execution of the function terminates early due to this check:
```java
    if (cancelPid <= 0) {
      return;
    }
```

When running the same test against a PostgreSQL server, it can be seen that `cancelPid` is set to the correct PID and the query gets terminated.

### Expected Result

The query terminates shortly after canceling.

### Actual Result

The query keeps running until the result set is returned.

**Comment by mfussenegger** [comment]
We'll have to implement the cancellation parts of the wire protocol: (https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.9). Currently that is missing.

**Comment by proddata** [comment]
> We'll have to implement the cancellation parts of the wire protocol: (https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.9). Currently that is missing.

That explains a lot 😬
