### ISSUE TITLE
NPE on INSERT into column in altered table

### ISSUE THREAD

**Issue by heyoka** [crate/crate#11722]
### CrateDB version

4.5.1

### CrateDB setup information

Number of nodes: 3
12 GB heap

### Steps to Reproduce

```
CREATE TABLE IF NOT EXISTS "doc"."0x001" (
   "ts" TIMESTAMP WITHOUT TIME ZONE,
   "stream_id" TEXT,
   "01_01" OBJECT,
   "01_02" OBJECT,
   "01_03" OBJECT,
....
"ts_partition" TIMESTAMP WITHOUT TIME ZONE GENERATED ALWAYS AS _cast(date_trunc('quarter', 'UTC', "ts"), 'timestamp without time zone')
)
CLUSTERED BY ("stream_id") INTO 6 SHARDS
PARTITIONED BY ("ts_partition")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   codec = 'default',
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-1',
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = 'fs',
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "write.wait_for_active_shards" = '1'
) 
```

Inserting works ok so far, then altered table:
`alter table "doc"."0x001" add column "02_0815" OBJECT;`

everything still works ok, but after a view days, we cannot insert into the new column 02_0815 anymore:
error: NullpointerException[null], code: 5000, trace: Java.Lang.NullpointerException
We insert via http and do not always get this error, but most of the time Status 200, and rowcount(s) : -2
Also tried inserting via the AdminUI, same result, NullpointerException[null] !
But: inserting into all the other columns still works !

Tried to create another OBJECT column in this table, same result.
At this point the table has: 

- 707 columns
- 132 MIO records
- Size 19.1 GB
- Shards 48

The sys.jobs_log table shows the insert statements, but error column is always null.

We then created another table with just 1 OBJECT column (and the other columns from the first table): inserting works as expected.

### Expected Result

INSERTING works or get a decent error message.

### Actual Result

error: NullpointerException[null], code: 5000, trace: Java.Lang.NullpointerException

**Comment by heyoka** [comment]
Data we try to insert:
```
INSERT INTO "0x001" (ts, stream_id, "02_0815") VALUES (1631103743512,'341af56b2ccd533124e2caa0add16dde',
{"sen-z2Right" = 0,
"sen-z2Left" = 7526,
"sen-Sen60V" = 65,
"WARM-Cnt_lt"=0,
"Temp-MIN"=18,
"Temp-MAX"=38,
"Temp-Current"=28,
"PLA-SearchCnt_lt"=34800,
"PLL-SucAllCnt_lt"=26,
"PLL-FailAllCnt_lt"=1064,
"FISH-PickCnt_lt"=0,
"FDRO-SucAllCnt_lt"=26,
"FDRO-FailAllCnt_lt"=1064,
"ERRH-TOCnt_lt"=0,
"ERRH-TICnt_lt"=0,
"ERRH-RACnt_lt"=0}
);
```

**Comment by seut** [comment]
@heyoka Thanks for the report. Would be really great if you could send us the related stacktrace. While using the HTTP interface this can be gathered by adding `error_trace=true` to the URL, see https://crate.io/docs/crate/reference/en/4.6/interfaces/http.html#error-handling.

**Comment by heyoka** [comment]
@seut As written above, the contents of the error_trace field in the response is exactly : ` java.lang.NullPointerException\\n` nothing more

**Comment by heyoka** [comment]
For clarification: the number of columns I posted above is the result of
```sql
select COUNT(*)
from information_schema.columns
where table_schema = 'doc' and table_name = '0x001'
```
707

We do NOT have more than 700 OBJECT(DYNAMIC) columns in the table

**Comment by BaurzhanSakhariev** [comment]
Probably related to [4594](https://github.com/crate/crate/issues/4594) - it's also NPE with code `5000`.

**Comment by proddata** [comment]
Tried to replicate this with a restore of the affected table with 
```
NullPointerException[Cannot invoke “Object.equals(Object)” because “sourceValue”
```
when trying to insert
