### ISSUE TITLE
Postgres ssl doesn't seem to be enforcing ssl

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#11760]
### CrateDB version

4.6.3

### CrateDB setup information

Num nodes: 15
Heap (master=8g, data=30g, ingest=12g, query=30g)

Crate.yml (relevant part)

```
psql.enabled: false
psql.port: 5432

transport.tcp.compress: true

ssl.transport.mode: on
ssl.keystore_filepath: /path/to/file.p12
ssl.keystore_password: password123
ssl.keystore_key_password: password123
ssl.truststore_filepath: /path/to/file.p12
ssl.truststore_password: password456
ssl.http.enabled: true
ssl.psql.enabled: true
```

### Steps to Reproduce

We're using HAProxy to connect to the multiple query/ingest nodes and for whatever reason, haproxy won't talk to crate's psql unless we remove the ssl portion. HTTP works as expected.

Our simple haproxy config for this purpose:

```
listen http-crate-psql
  bind: *:5432
  mode tcp
  option psql-check user crate
  timeout server 15m
  balance leastconn
  server one my-crate-one.my-fqdn:5432 check ssl crt /path/to/mycert.pem ca-file /path/to/mycert.crt ssl-min-ver TLSv1.2 verify required
  server two my-crate-two.my-fqdn:5432 check ssl crt /path/to/mycert.pem ca-file /path/to/mycert.crt ssl-min-ver TLSv1.2 verify required
```

If I remove the SSL portions to postgres in the haproxy config, it connects/works as-expected and that's with the ```ssl.psql.enabled: true```

### Expected Result

I expect haproxy to connect to crate's psql port with ssl and allow me to start sending queries

### Actual Result

The healthchecks fail (and yes, I've tried removing them) and haproxy fails to connect to crate's postgres port

**Comment by BaurzhanSakhariev** [comment]
Hello,

thanks for your report. 

What's your HBA config? Could you please try adding 

```
1:
        protocol: pg
        ssl: on
```
to your HBA config? 

Please keep ssl related configs (path/password and `ssl.psql.enabled: true`) in `config.yml` while doing step from above. 

Feel free to use another key if "1" is already busy.

**Comment by bputt-e** [comment]
We're not using HBA. Our simple flow below outlines how we plan on communicating with crate.

Our java apps (using jdbc driver) -> HAProxy -> Crate

Currently, our java apps/haproxy live in kubernetes and we don't plan on having crate run inside of k8s. If HAProxy doesn't cooperate with crate, then we'll most likely run the crate query/ingest nodes (non-data/ non-master) inside k8s

**Comment by BaurzhanSakhariev** [comment]
Could you please share the logs from non-working setup?

As per [docs](https://crate.io/docs/crate/reference/en/4.6/admin/ssl.html), HBA is needed to **enforce** SSL on PG protocol.

Having HBA enabled with one entry - `protocol:pg`, `ssl:on` without specifying user and address would require SSL for any PG wire connection coming from arbitrary host and from arbitrary user.

**Comment by bputt-e** [comment]
I see now, thanks for providing insight.

After adding the section below, I get the error ```Password authentication failed for user=my-user.my.fqdn.com from connection=/x.x.x.x```...The user ```my-user.my.fqdn.com``` is the DN of the cert. We're trying to get that to authenticate w/out a password. I've added the user to the cluster

```
CREATE USER "my-user.my.fqdn.com";
GRANT ALL PRIVILEGES TO "my-user.my.fqdn.com";
```

```
auth:
  host_based:
    enabled: true
    config:
      0:
        protocol: transport
        ssl: on
        method: cert
      1:
        protocol: pg
        ssl: on
      2:
        protocol: http
        ssl: on
```

**Comment by BaurzhanSakhariev** [comment]
Thanks for the details. Is it full HBA config, no other entries? 

I forgot to say,  `method: cert` is also needed for entires 1 and 2 - and [common name of the certificate has to match username](https://crate.io/docs/crate/reference/en/4.6/admin/auth/methods.html#client-certificate-authentication-method).

After seeing "Password authentication failed" I thought you might have a password entry in HBA but probably it's incorrect logging message - created a [PR](https://github.com/crate/crate/pull/11768) to address that. By default, if `method` is not specified, `trust` methods gets picked up - I think trust method should have been shown in the logs.

"Password authentication failed ... for user... from connection... message is shown in Http request handler - it looks like crate getting connection on http. Also another thing that caught my attention is "for user my-user.my.fqdn.com" whereas HAProxy does `psql-check` as user `crate. 

Could you elaborate a bit more on you HAproxy config, what's the more detailed expected flow?

**Comment by bputt-e** [comment]
Once I saw the log that specified the user coming from the cert, I modified the HAProxy conf ```option psql-check user for user my-user.my.fqdn.com``` and that didn't fix the issue.

Haproxy config:

```
listen http-crate-psql
  bind: *:5432
  mode tcp
  option psql-check user my-user.my.fqdn.com
  timeout server 15m
  balance leastconn
  server one my-crate-one.my-fqdn:5432 check ssl crt /path/to/mycert.pem ca-file /path/to/mycert.crt ssl-min-ver TLSv1.2 verify required
  server two my-crate-two.my-fqdn:5432 check ssl crt /path/to/mycert.pem ca-file /path/to/mycert.crt ssl-min-ver TLSv1.2 verify required
```

Crate logs (which oddly enough, doesn't error for postgres)...HTTP works, but postgres doesn't

```
[i.c.a.HttpAuthUpstreamHandler] [my-crate-one]Password authentication failed for user=my-user.my.fqdn.com from connection=/x.x.x.x
```

**Comment by BaurzhanSakhariev** [comment]
> psql.enabled: false

Could you enable it while keeping other configs?

> I modified the HAProxy conf for user my-user.my.fqdn.comThe 
> user my-user.my.fqdn.com is the **DN** of the cert

Could you try another cert where username is the [CN](https://crate.io/docs/crate/reference/en/4.6/admin/auth/methods.html#client-certificate-authentication-method) of the cert?

> 1:
        protocol: pg
        ssl: on
      2:
        protocol: http
        ssl: on
        
 Could you also add 
 `method: cert `
 to those entries?

**Comment by bputt-e** [comment]
I was able to verify psql works with the cert, so it seems to be an haproxy issue where it doesn't understand how to interact with postgres as the logs specify the protocol being used is ```1.1``` when psql uses ```3.0```

We're working on switching to pgpool which I'm sure will work just fine...Appreciate all your help!
