### ISSUE TITLE
Adding columns/properties to `OBJECT(IGNORED)` leads to inconsistencies 

### ISSUE THREAD

**Issue by proddata** [crate/crate#11790]
**Use case**:

When adding indexed object properties to `OBJECT(IGNORED)` columns, one might end up with inconsistent results

only records after index was added get returned
```sql
CREATE TABLE test_obj (obj OBJECT(IGNORED)) CLUSTERED INTO 1 SHARDS;

INSERT INTO test_obj VALUES ({a=1});

SELECT * FROM test_obj WHERE obj['a'] = 1;
-- SELECT OK, 1 record returned (0.005 seconds)

ALTER TABLE test_obj ADD COLUMN obj['a'] LONG;

SELECT * FROM test_obj WHERE obj['a'] = 1;
-- SELECT OK, 0 records returned (0.002 seconds)
```

only records after index was added get used in aggregation
```sql
INSERT INTO test_obj VALUES ({b=1});

SELECT * FROM test_obj WHERE obj['b'] = 1
-- SELECT OK, 1 record returned (0.003 seconds)

ALTER TABLE test_obj ADD COLUMN obj['b'] LONG INDEX OFF;

INSERT INTO test_obj VALUES ({b=3});

SELECT SUM(obj['b']) FROM test_obj 
-- result: 3 | expected 4
```

**Feature description**:

Options:
- Prevent adding object properties to `OBJECT(IGNORED)` if values have been inserted before
- Document behaviour
- fall back to "table scan" for records that have been added before

**Comment by mfussenegger** [comment]
> Prevent adding object properties to OBJECT(IGNORED) if values have been inserted before

Given that we literally ignore anything written to `object(ignored)`, we don't really know if values have been inserted before. (And changing that would add a performance cost)

> fall back to "table scan" for records that have been added before

Similar problem as above. We don't know if records were added beforehand, so we'd always have to do table scans on ignored object columns, even if an index starts showing up.

Documenting the behavior almost seems like the best option, considering the impact of the others.

**Comment by seut** [comment]
I've added a note to the related documentation which probably closes this issue? See https://github.com/crate/crate/commit/bfad79c601d84fb52aaefc1b4655ec98b8206dd7, please check @proddata & @mfussenegger.
