### ISSUE TITLE
Add support for GROUP BY on array columns

### ISSUE THREAD

**Issue by proddata** [crate/crate#11796]
### CrateDB version

4.6.4

### CrateDB setup information

local 1 node

### Steps to Reproduce

```sql
CREATE TABLE dist (array_text ARRAY(TEXT)) CLUSTERED INTO 1 SHARDS;
```

```sql
INSERT INTO dist VALUES (['a','b']),(['a']),(['a']);
```

```sql
SELECT UNNEST(array_text)
FROM (
SELECT DISTINCT array_text
FROM dist ) sub
```

### Expected Result

a
b
a

### Actual Result

```
Error!

UnsupportedFeatureException[Cannot GROUP BY type: text_array]
```

**Comment by BaurzhanSakhariev** [comment]
Hi, thanks for reporting it. 

Arrays should be comparable - do they have to be comparable up to permutation precision, i.e 
`[a,b,c] == [c,b,a]` or not?

**Comment by seut** [comment]
At PostgreSQL, the result set differs from the described expected results:
```
postgres=# CREATE TABLE dist (array_text TEXT[]);
CREATE TABLE
postgres=# INSERT INTO dist VALUES (array['a','b']),(array['a']),(array['a']);
INSERT 0 3
postgres=# SELECT UNNEST(array_text)
FROM (
SELECT DISTINCT array_text
FROM dist ) sub;
 unnest 
--------
 a
 a
 b
(3 rows)

postgres=# SELECT DISTINCT array_text
postgres-# FROM dist;
 array_text 
------------
 {a}
 {a,b}
(2 rows)
```

**Comment by BaurzhanSakhariev** [comment]
Closed in https://github.com/crate/crate/pull/12755. 

Arrays which differ only by elements permutation are considering as different (aligned with PostgreSQL 14).
