### ISSUE TITLE
Create fold_array_unique aggregate function

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11795]
**Use case**:

Users might want to get only unique values across all arrays in all rows.

Workaround `SELECT DISTINCT UNNEST(array_column) FROM tab;` in some cases not good as `UNNEST` gets applied first and `DISTINCT` has to operate with huge amount of data - and if final number of unique values is small keeping aggregated state small can leverage that to reduce memory usage. 

If final number of uniques is very low, like 100-1000 and total amount of rows*elements_per_row is much more than that we can significantly reduce memory usage with some small overhead of adding into _small_ HashSet. 

**Feature description**:
 
`fold_array_unique(column:array of comparable)`

`SELECT fold_array_unique(array_col) FROM tab` returns same result as  `SELECT DISTINCT UNNEST(array_col) FROM tab` 

```
['a','b','c']
['b','c']
['a']
['d']
```
would result to
`['a','b','c','d'] `

fold_array_unique works like if `array_agg` had unique parameter and unfolded arrays like `flatMap` does in Java.

If users know that almost all values across all rows are unique than DISTINCT UNNEST might be better as overhead for keeping state unique would be also big.

**Comment by mfussenegger** [comment]
I don't think there is much to be gained by a `fold_array_unique` function. At least not as a means to optimize `SELECT DISTINCT UNNEST(array_column) FROM tab;`

unnest operates lazy (one row at a time is projected into a set of rows). The `distinct` is consuming the source lazy as well. So there is no unnecessary intermediate materialization happening.

Think of it as `xs.stream().flatMap(unnest).toSet()`. If anything, a dedicated array-uniqueness function in-between would add redundancy and could end up slowing down the whole operation.
