### ISSUE TITLE
Bulk queries`COPY FROM / TO` should have an `wait_for_completion` option

### ISSUE THREAD

**Issue by proddata** [crate/crate#11791]
## Use case
Bulk queries like `COPY FROM / TO` might run for a very long time (up to hours). Right now, one would not get any confirmation, that a query was successfully started. Also load balancers or other network issues, might interrupt the connection, which makes it impossible to determine if a `COPY` statement partially failed (e.g. some records could not be inserted)

## Feature description

- have an option `wait_for_completion` similar to `CREATE SNAPSHOT` for bulk queries like `COPY FROM / TO`

## Potential follow up

- have an option to route the "SUMMARY" to a system table e.g. `sys.bulk_jobs_log` or include the result in `sys.jobs_log`

**Comment by mfussenegger** [comment]
The second part is also a bit related to https://github.com/crate/crate/issues/11748

**Comment by proddata** [comment]
BTW Postgres 14 just added `pg_stat_progress_copy` 😬 
https://www.postgresql.org/docs/14/progress-reporting.html#COPY-PROGRESS-REPORTING

Altough `COPY` works a bit different in PG
