### ISSUE TITLE
Add `array_append` scalar function

### ISSUE THREAD

**Issue by seut** [crate/crate#11907]
**Use case**:

Adding an array element to an existing array inside the database without the need to select the array first and update the full array value afterwards.

```
CREATE TABLE t1 (id INTEGER, tags ARRAY(TEXT));
INSERT INTO t1 (id, tags) VALUES (1, ['database']);
```

```
UPDATE t1 SET
  tags = array_append(tags, 'search engine')
WHERE id = 1;
``` 

**Feature description**:

Add support for the `array_append ( anycompatiblearray, anycompatible )` scalar function which appends an element to the end of an array.
See https://www.postgresql.org/docs/current/functions-array.html

**Comment by proddata** [comment]
I think having an `array_slice( <anycompatiblearray> , begin, end)` would then also make sense 😬 

> array_slice() returns a copy of a portion of an array into a new array selected from start to end (end not included) where start and end represent the index of items in that array

and would e.g. allow keeping the last 10 elements:

```sql
UPDATE t1 SET
  tags = array_append(array_slice(excluded.tags,1,10), 'search engine');
WHERE id = 1;
```
