### ISSUE TITLE
Add `array_slice` scalar function

### ISSUE THREAD

**Issue by proddata** [crate/crate#11910]
**Use case**:
Selecting a subset of array elements of an existing array inside the database without the need to unnest the array first or use a user-defined function.

```sql
CREATE TABLE t1 (id INTEGER, tags ARRAY(TEXT));
INSERT INTO t1 (id, tags) VALUES (1, ['database','search engine','document store']);
```

```sql
SELECT array_slice(tags,2,3) FROM t1;
--> ['search engine','document store']

SELECT array_slice(tags,2) FROM t1;
--> ['search engine','document store']
```

**Feature description**:

Add support for the `array_slice ( <anycompatiblearray>, begin [, end] )` scalar function which array_slice() returns a copy of a portion of an array into a new array selected from start to end (end not included) where start and end represent the index of items in that array

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

---

an alternative would be to follow the standard PostgreSQL array slicing:
```sql
=> select (array[1,2,3,4,5,6])[2:5];
   array   
-----------
 {2,3,4,5}
(1 row)
```

See https://www.postgresql.org/docs/current/arrays.html#ARRAYS-ACCESSING

---

similar to #11907

**Comment by seut** [comment]
As we in general target for PostgreSQL compatibility, we should follow their implementation specification.

**Comment by seut** [comment]
Supporting PG's array slicing syntax would require some effort inside the parser and expression analyzer, so I think we could add support for the functionality first by adding a `array_slice ( <anycompatiblearray>, begin [, end] )` scalar like @proddata suggested and adding the PG syntax support later on.
