### ISSUE TITLE
Add URL data type

### ISSUE THREAD

**Issue by robd003** [crate/crate#11941]
**Use case**: It would be *really useful* to have a URL data type that would verify that a URL is correctly formatted when being inserted and more importantly let you do operations like GROUP BY url(path, url_field_name) efficiently.

**Feature description**: Validate URL upon insertion / update. Automatically store the URL in a way so that the parts of the URL are easily accessible and indexed efficiently. Turning the querystring into key/value pairs that you could easily search would be immensely helpful.

Parts of the URL that should be indexed:

- scheme
- hostname
- domain
- port
- path
- querystring parameters (take ?this=that&color=blue&validate should turn into key value pairs that can be searched with a WHERE clause easily or used in a GROUP BY)
- hash fragment

Lastly it would be great to automatically decode any [percent encoded](https://en.wikipedia.org/wiki/Percent-encoding) values.

Presently I've had to split up URLs into a bunch of TEXT fields when storing them in Crate and it seems like not a great way to do things.

**Comment by helenap** [comment]
this would be so useful!

**Comment by fahimermo** [comment]
I need this

**Comment by proddata** [comment]
so would a `url_parse(<string>)` function, that parses url string to an object like
```sql
OBJECT(STRICT) AS (
  scheme TEXT,
  hostname TEXT,
  domain TEXT,
  port INTEGER,
  path ARRAY(TEXT),
  parameters OBJECT(DYNAMIC) AS (
     key1 TEXT
 ),
 uri_fragment TEXT
)
```

be what you are looking for?

**Comment by robd003** [comment]
The main thing is I'd like to be able to do GROUP BY on parts of a URL. Can crate efficiently do GROUP BY on object subscripts?

Having url_parse that would automatically insert into an object like that would be useful.

I really want to make sure that everything is stored in a way so that I'm not having to parse each URL when doing a GROUP BY or being stuck with doing source look-ups that would be slower than using an index.

**Comment by proddata** [comment]
> The main thing is I'd like to be able to do GROUP BY on parts of a URL. Can crate efficiently do GROUP BY on object subscripts?

Absolutely, Object properties behave pretty much the same as columns in terms of performance.

> Having url_parse that would automatically insert into an object like that would be useful.

something like that would be possible:

```sql
CREATE TABLE x (
   url TEXT,
   url_parsed OBJECT GENERATED ALWAYS AS url_parse(url)
```

> I really want to make sure that everything is stored in a way so that I'm not having to parse each URL when doing a GROUP BY or being stuck with doing source look-ups that would be slower than using an index.

Unless you use `OBJECT(IGNORED)` without defining any fields, object properties are always indexed the same way columns are. That is one of the key features of CrateDB ;)

**Comment by robd003** [comment]
@proddata sounds like a solid solution

**Comment by proddata** [comment]
> querystring parameters (take ?this=that&color=blue&validate should turn into key value pairs that can be searched with a WHERE clause easily or used in a GROUP BY)

How to handle duplicates keys?
e.g. `?id=1&id=2`
put values always in arrays?

> domain

also not sure about extracting domains from host :/ 

> path

also rather keep the path a String and use a fulltext index with a  [path-hierarchy-tokenizer](https://crate.io/docs/crate/reference/en/4.8/general/ddl/analyzers.html#path-hierarchy-tokenizer)

```sql
cr> SELECT uri_parse('https://user:pw@testing.crate.io:4200/?foo=bar1&foo2=bar2#ref') as uri;                                                            
+--------------------------------------+
| uri                                  |
+--------------------------------------+
| {                                    |
|     "fragment": "ref",               |
|     "hostname": "testing.crate.io",  |
|     "password": "pw",                |
|     "path": "/",                     |
|     "port": 4200,                    |
|     "query": {                       |
|         "foo": "bar1",               | 
|         "foo2": "bar2"               |
|     },                               |
|     "scheme": "https",               |
|     "user": "user"                   |
| }                                    |
+--------------------------------------+
```

**Comment by robd003** [comment]
Comments inline

> > querystring parameters (take ?this=that&color=blue&validate should turn into key value pairs that can be searched with a WHERE clause easily or used in a GROUP BY)
> 
> How to handle duplicates keys? e.g. `?id=1&id=2` put values always in arrays?

I think putting the values in an array makes sense. From your example

```sql
cr> SELECT uri_parse('https://user:pw@testing.crate.io:4200/?foo=bar1&foo2=bar2&foo2=lets_go_to_another_bar#ref') as uri;                                                            
+--------------------------------------+
| uri                                  |
+--------------------------------------+
| {                                    |
|     "fragment": "ref",               |
|     "hostname": "testing.crate.io",  |
|     "domain": "crate.io",  |
|     "password": "pw",                |
|     "path": "/",                     |
|     "port": 4200,                    |
|     "query": {                       |
|         "foo": "bar1",               | 
|         "foo2": ["bar2", "lets_go_to_another_bar"]       |
|     },                               |
|     "scheme": "https",               |
|     "user": "user"                   |
| }                                    |
+--------------------------------------+
```

> 
> > domain
> 
> also not sure about extracting domains from host :/

Domain extraction is actually pretty trivial with Google's Guava. Take a look at [com.google.common.net.InternetDomainName](https://guava.dev/releases/snapshot/api/docs/com/google/common/net/InternetDomainName.html)

Example:

```
import com.google.common.net.InternetDomainName;
import java.net.URL;

public final class URLFunction {

    private static String getDomain(String url_input) {
        if (url_input.length() == 0) {
            return val;
        }

        URL url = new URL(url_input);
        String host = url.getHost();
        InternetDomainName domain_name = InternetDomainName.from(host).topPrivateDomain();
        return new String(domain_name);
    }
}
```

> 
> > path
> 
> also rather keep the path a String and use a fulltext index with a [path-hierarchy-tokenizer](https://crate.io/docs/crate/reference/en/4.8/general/ddl/analyzers.html#path-hierarchy-tokenizer)
> 
> ```sql
> cr> SELECT uri_parse('https://user:pw@testing.crate.io:4200/?foo=bar1&foo2=bar2#ref') as uri;                                                            
> +--------------------------------------+
> | uri                                  |
> +--------------------------------------+
> | {                                    |
> |     "fragment": "ref",               |
> |     "hostname": "testing.crate.io",  |
> |     "password": "pw",                |
> |     "path": "/",                     |
> |     "port": 4200,                    |
> |     "query": {                       |
> |         "foo": "bar1",               | 
> |         "foo2": "bar2"               |
> |     },                               |
> |     "scheme": "https",               |
> |     "user": "user"                   |
> | }                                    |
> +--------------------------------------+
> ```

**Comment by robd003** [comment]
@proddata & @mfussenegger any chance this could be added to the 5.0 release?

**Comment by robd003** [comment]
@mfussenegger is this under `io.crate.module.ExtraFunctionsModule` ?

Where would I look to get started?
