### ISSUE TITLE
Add an array_position function

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#11943]
**Use case**:
Add the ability to search for an element in an array and retrieve back the array index.
As per the [PostgreSQL documentation](https://www.postgresql.org/docs/current/functions-array.html):
> array_position ( anycompatiblearray, anycompatible [, integer ] ) → integer
>
> Returns the subscript of the first occurrence of the second argument in the array, or NULL if it's not present. If the third argument is given, the search begins at that subscript. The array must be one-dimensional. Comparisons are done using IS NOT DISTINCT FROM semantics, so it is possible to search for NULL.
> array_position(ARRAY['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'], 'mon') → 2

**Feature description**:
several values are grouped in an array:
```sql
CREATE TABLE metrics(
    ts timestamp,
    values_sensor1 ARRAY(INTEGER),
    values_sensor2 ARRAY(INTEGER)
);

INSERT INTO metrics VALUES (NOW(), [1, 3, 7, 4], [9, 8, 0, 2]);
```

Possible query involving `array_position`:
```sql
-- find out if a value is contained in an array
SELECT array_position(values_sensor1, 10) IS NULL
FROM metrics;
-- expected output: true

-- find the position of an existing element
SELECT array_position(values_sensor1, 3)
FROM metrics;
-- expected output: 2
```
Especially if there is a correlation between `values_sensor1` and `values_sensor2` (i.e. values recorded at the same time are stored at the same index), `array_position` would enable queries identifying the position of a known element in the first array, and then querying the second array at the same position.

**Comment by seut** [comment]
Implemented by #12249 and part of our next feature release. Thank you for reporting.
