### ISSUE TITLE
COPY TO Command fails for large table

### ISSUE THREAD

**Issue by sourabhswain** [crate/crate#12035]
### CrateDB version

4.6.6

### CrateDB setup information

Number of nodes : 3
CRATE_HEAP_SIZE: 2g

### Steps to Reproduce

Running COPY "TABLE_NAME" TO DIRECTORY "DIRECTORY_NAME" WITH (compression='gzip') for a table  with 9 million records. 

### Expected Result

COPY OK

### Actual Result

The UI says "Error 1 Object Object
![Error](https://user-images.githubusercontent.com/6239837/149215825-24fe85a3-d6a5-4043-99ca-f564e9b91cb2.jpeg)
"

**Comment by jayeff** [comment]
@sourabhswain Can you enable "Show error trace" (3rd checkbox above SQL input area) and run the query and please share the output with us?

Which OS are you using? Does the folder exist? Is it writable?

**Comment by amotl** [comment]
Dear Sourabh,

thank you for writing in. Depending on the outcome from what @jayeff asked for, can I ask you to also file a corresponding issue at https://github.com/crate/crate-admin about the UI flaw that it will croak with `[object Object]` instead of providing a more meaningful error message?

With kind regards,
Andreas.

**Comment by sourabhswain** [comment]
@jayeff Please find the attached screenshot. The stack trace is also empty unfortunately. I am using Windows OS and yes the folder exists and is writable since I tried running the command for different tables which worked.
![crate_error](https://user-images.githubusercontent.com/6239837/149667782-063b196c-0204-48f2-ba3e-9c141238c939.PNG)

**Comment by mfussenegger** [comment]
Can you try executing the statement in [crash](https://github.com/crate/crash) (started with `--verbose`) instead of the admin ui?

Are there any errors in the logs?

**Comment by mfussenegger** [comment]
Closing this due to lack of feedback.

If you can provide more information please let us know. We'd re-open this and look into it.
