### ISSUE TITLE
Documentation: Unclear/misleading timezone behaviour of `NOW()`/`CURRENT_TIMESTAMP`

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#12064]
### CrateDB version

4.6.6

### Steps to Reproduce

The [documentation](https://crate.io/docs/crate/reference/en/master/general/builtins/scalar-functions.html#current-timestamp) of `CURRENT_TIMESTAMP` reads:
> The return value of expressions CURRENT_TIMESTAMP and CURRENT_TIME depends on the system clock and the JVM implementation.

To me, this suggests that the returned timestamp is not always reflecting UTC, but depends on the system/JVM time zone.

The `CURRENT_TIME` documentation however says that is it UTC:
> The CURRENT_TIME expression returns the time in microseconds since midnight UTC

Running CrateDB with different time zone settings (changing the system time zone and/or passing `-Duser.timezone`) shows no change in `CURRENT_TIMESTAMP` behavior, suggesting it is always UTC.

### Expected Result

If `CURRENT_TIMESTAMP` indeed always returns UTC, it should be said so explicitly.

### Actual Result

Confusion on whether `CURRENT_TIMESTAMP` constantly returns UTC or not 🙂

**Comment by BaurzhanSakhariev** [comment]
https://github.com/crate/crate/issues/10037 says that `In CrateDB the system time zone is always UTC`

referring to https://crate.io/docs/crate/reference/en/4.6/general/ddl/data-types.html#timestamps
in particular, to this sentence
>Internally, timestamp values are mapped to the UTC milliseconds since 1970-01-01T00:00:00Z stored as bigint.

I do agree that it's not clear though, will make a PR
