### ISSUE TITLE
Insert into from other table doesn't get completed

### ISSUE THREAD

**Issue by rjbaat** [crate/crate#12091]
### CrateDB version

4.6.7

### CrateDB setup information

I have a cluster with 3 nodes with 3 gb memory and 2 gb heap size setup.

### Steps to Reproduce

The first 57 partitions with data I copy from one table to another go as expected. But the last 8 partitions won't completely transfer. Somehow the data is partially transferred. 

### Expected Result

I expect to be able to insert into the new table that is exact the same as the old table and transfer it partition by partition. 

### Actual Result

Somehow after a certain amount of time the transfer is stuck. I don't see any errors in the logs, the interface is also still showing it is running, but no new data is added in the partition when I look at it, and the file size of the partition is also not increased. 

The total amount is around 39 million records with a file size of 16 gb.

**Comment by proddata** [comment]
```sql
SELECT * FROM sys.jobs
```
all `INSERT INTO` jobs finished?

---

Generally speaking the bug report feature is only intended for reproducible bug reports.
For questions about the usage of CrateDB I would like to refer you to https://community.crate.io/

**Comment by rjbaat** [comment]
@proddata i checked indeed and there where some left open.
But I also tried to kill them and tried to kill all. But they also stay in the sys.jobs. I would expect them to be gone immediately.

I understand, but isn't this a bug?

**Comment by mfussenegger** [comment]
> I understand, but isn't this a bug?

sounds like it might be. Were there any errors in the logs?

**Comment by proddata** [comment]
@rjbaat Are both tables using the same table schema?
Could it be, that there are some conflicts ... also see: https://github.com/crate/crate/issues/12218

**Comment by mfussenegger** [comment]
Closing this due to lack of feedback.

If you can provide more information please do and we'll reopen this and look into it.
