### ISSUE TITLE
support COPY TO Google Cloud Storage with HTTP upload requests

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#12094]
### CrateDB version

master

### Steps to Reproduce

```sql
# an issue with AWS SDK with GCS but for HTTP upload requests only
cr> copy t to directory 's3://access:secret@storage.googleapis.com:80/bucket/prefix' with (protocol ='http');
SdkClientException[Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: E34BC177904528CD2943E6EC6B13B6AE in hex) didn't match hash (etag: e397913c092fa4f3a6636b6fda0a1679 in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (bucketName: bucket, key: prefix/t_3_.json, uploadId: ABPnzm6BEfmBbGiMczWH-jUZYQPESapcH993xp7I1MKyBBJ9OublFgW5wVLXlTM06VXvK, partNumber: 1, partSize: 10)]
```

### Expected Result

successful upload

### Actual Result

SdkClientException

**Comment by jeeminso** [comment]
the cause seems to be the [differences in GCS API and S3](https://cloud.google.com/storage/docs/migrating):
> 

In Amazon S3, V4       signatures can be used to authenticate uploads that use chunked       transfer encoding. | In the Cloud Storage XML API, chunked transfer encoding and       V4 signatures cannot currently be used simultaneously. Some Amazon S3       tools use chunked transfer encoding along with signatures by default;       you should disable chunked transfer encoding in such cases.
-- | --

possible workarounds are, 1)  to disable chunked transfer or 2) to use `https`.

**Comment by mfussenegger** [comment]
I think it is okay that we require HTTPS for Google cloud storage. We should recommend HTTPS anyways. I'd close this as wontfix

cc @jweberpm
