### ISSUE TITLE
Extend PRIVILEGES to follow Postgres RBAC

### ISSUE THREAD

**Issue by proddata** [crate/crate#12109]
**Use case**:

In the SQL standard, there is a clear distinction between users and roles, but this is not followed by PostgreSQL

- PostgreSQL manages database access permissions using the concept of roles. A role can be thought of as either a database user, or a group of database users, depending on how the role is set up.
- CrateDB follows PostgreSQL already quite closely, with one of the main differences, that CrateDB does not allow the inheritance of roles.

in Postgres `CREATE ROLE`, `CREATE USER`, `CREATE GROUP` can be used synonymous.

**Feature description**:

- Extend CrateDB Authorisation to also accept  `CREATE ROLE`
- Allow the inheritance of **roles** by users 

`CREATE ROLE name;`

`GRANT role_name TO role_specification1, ... ;`
`REVOKE role_name FROM role_specification1, ... ;`

also see https://www.postgresql.org/docs/14/role-membership.html for details

--- 

## Open Questions

- [ ] Is CREATE GROUP required for compatiblity? If so - which tools? It's just an alias in PostgreSQL and not part of the SQL Standard. If it's not needed, we shouldn't add it now. See https://www.postgresql.org/docs/current/sql-creategroup.html

**Comment by jayeff** [comment]
Once support for roles is added I think adding support for [`SET ROLE`](https://www.postgresql.org/docs/current/sql-set-role.html) in a follow-up task would be helpful (e.g. Flyway expects it, I believe other tools also)

**Comment by mfussenegger** [comment]
Another use case for roles is to set default settings: 

```
ALTER ROLE { role_specification | ALL } [ IN DATABASE database_name ] SET configuration_parameter { TO | = } { value | DEFAULT }
ALTER ROLE { role_specification | ALL } [ IN DATABASE database_name ] SET configuration_parameter FROM CURRENT
ALTER ROLE { role_specification | ALL } [ IN DATABASE database_name ] RESET configuration_parameter
ALTER ROLE { role_specification | ALL } [ IN DATABASE database_name ] RESET ALL
```

See https://www.postgresql.org/docs/current/sql-alterrole.html

This would be useful to set options like  [statement_timeout](https://github.com/crate/crate/issues/13242) for client applications which don't support setting it via connection option or `SET SESSION` statement. Exposing these as cluster level setting (https://github.com/crate/crate/pull/14045) has the downside that it affects all connections.

Examples are https://www.cluvio.com/ or Grafana. The connection dialogs don't support setting options:

![image](https://user-images.githubusercontent.com/38700/235639984-6d56cc19-55ea-45eb-a51b-705453ddfc2f.png)

**Comment by seut** [comment]
For the first iteration we will limit the scope to implement:
 - `CREATE ROLE [INHERIT]`       (we will implement the the default option `INHERIT` but no other option)
 - `DROP ROLE`
 - `GRANT ROLE`
 - `REVOKE ROLE`

**Comment by mfussenegger** [comment]
> In the SQL standard, there is a clear distinction between users and roles, but this is not followed by PostgreSQL

The distinction is actually not that clear, and I think what PostgreSQL does is somewhat within the boundaries of the Standard.  Here is what SQL-99 defines:

https://github.com/crate/sql-99/blob/c8848117d60e60aa9ba1132813f32ad91a99af6c/docs/chapters/15.rst?plain=1#L42-L55


https://github.com/crate/sql-99/blob/c8848117d60e60aa9ba1132813f32ad91a99af6c/docs/chapters/15.rst?plain=1#L679-L697

https://github.com/crate/sql-99/blob/c8848117d60e60aa9ba1132813f32ad91a99af6c/docs/chapters/15.rst?plain=1#L200-L215

**Comment by matriv** [comment]
- [ ] sys.roles table
- [ ] grant roles to users
- [ ] Documentation
- [ ] sql_features.tsv
- [ ] crate-qa tests

**Comment by matriv** [comment]
- [x] Parser changes
- [x] Analyzer + Plan changes for ROLEs
- [x] Introduce `RolesMetadata` but continue reading `UsersMetadata` to be able to restore old snapshots
- [x] sys.roles table
- [x] pg_roles table -> populate
- [x] introduce `USERMANAGEMENT` to restore all users,roles and their privileges
- [x] grant roles to users
- [x] information_shema tables: https://www.postgresql.org/docs/current/infoschema-applicable-roles.html, https://www.postgresql.org/docs/current/infoschema-role-table-grants.html, etc. Opened a followup issue to track those: https://github.com/crate/crate/issues/15268
- [x] Migrate `UserPrivilegesMetadata` into `RolesMetadata`.
- [ ] Documentation
- [x] ROLE keword in crash
- [x] ROLE keyword in admin-ui (was already there)
- [x] sql_features.tsv
- [x] crate-qa tests
- [ ] include new release of crash including ROLE keyword addition.
