### ISSUE TITLE
Support for `SHOW DateStyle;`

### ISSUE THREAD

**Issue by proddata** [crate/crate#12104]
**Use case**:
Postgres compatible tools like Datagrip, DBeaver, etc. want to get (and sometimes set e.g. Azure Data Studio) the **datestyle** used by the database. It seems like there is already some implementation for that. 

**Feature description**:
As a db tool engineer I want to be able to fetch the set datestyle of a database to be know how to interpret dates in my tool.

extra: ability to **set** different date-styles (maybe as noop)

```sql
SHOW datestyle;
```

```sql
SHOW ALL;
```

**Comment by proddata** [comment]
@mfussenegger 

That's what I tried and worked. I would think this should be implemented similar to `PG_SERVER_VERSION` in
https://github.com/crate/crate/blob/05be94e1b100c9786b3689baaa13689b6642e7bd/server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java#L469

**Comment by theshashankpal** [comment]
Hey @proddata is this issue still open?
Can you assign this to me?
Since it is my first contribution towards FOSS this issue seems to be a good start for my Journey towards FOSS contribution.

**Comment by matriv** [comment]
@theshashankpal Thank you for your interest in contributing, but in this case there is already an open PR for this: https://github.com/crate/crate/pull/12426 Please choose another open issue that you'd like to work on.

Thank you!
