### ISSUE TITLE
Flaky table refresh behaviour

### ISSUE THREAD

**Issue by proddata** [crate/crate#12102]
### CrateDB version

4.7.0 (also with older versions

### CrateDB setup information

single node / multi node

### Steps to Reproduce

It is not possible to 100% recreate this every time

1. `CREATE TABLE`
2. `INSERT` some date
3.  wait a few seconds
4. `SELECT` on table

```sql
CREATE TABLE testtable (
   obj OBJECT(IGNORED)
);
```
wait a few seconds

```sql
INSERT INTO testtable (obj) VALUES ({a=1,b=2}),({c=1,b=2}),({a=1,c=2});
```

wait a few seconds

```sql
SELECT * FROM testtable limit 100;
-- SELECT OK, 0 records returned (0.388 seconds)
```
I would expect that query to take longer, because a refresh needs to be triggered, however it then should return also the recent data. Typically I would not expect data older than 1 second to be missing from a `SELECT`

run query again right after

```sql
SELECT * FROM testtable limit 100;
-- SELECT OK, 3 records returned (0.002 seconds)
```

### Expected Result

- `SELECT` takes a bit longer, because refresh needs to be run, before returning results
- All data is returned

### Actual Result

- `SELECT` takes a bit longer, because refresh needs to be run, before returning results
- **No data is returned**

**Comment by mkleen** [comment]
I tried that now multiple and i cannot reproduce it. In which environment do you run it ?

**Comment by proddata** [comment]
> I tried that now multiple and i cannot reproduce it. In which environment do you run it ?

I could see that behaviour both locally, as well as on a multi node cluster. I will try to make a recording.

For me the most important part to understand is, if the assumption is correct:
That if a refresh has not happened for e.g. 60 seconds, that a table would definitely get refreshed on a `SELECT` and should return results.

**Comment by proddata** [comment]
Really frustrating.I just experienced that behaviour again, but can't really replicate it

1) create new table with 2 replicas (3 node cluster)
2) start long running `INSERT INTO`
3) while insert into is running do a `SELECT`
 -> takes ~10 sec (i.e. it seems like refresh is happening)
-> 0 rows
4) another `SELECT` 
 -> takes ~10 sec (i.e. it seems like refresh is happening)
-> 0 rows
5) another `SELECT` 
-> instant 
-> x million rows

**Comment by remear** [comment]
I'm experiencing similar behavior with my multi-node cluster. I have a service that inserts a record every minute as a marker for the next run.

Given 1 shard, 0 replicas, the latest record seems to be consistently returned.

Given 1 shard and 1 replica, often a record other than the latest will be returned. Queries via the Crate UI also demonstrate this behavior. The frequency of an incorrect record being returned seems increase with more replicas.

Specifically calling refresh before the select nor after the insert made no noticeable difference.

Setting `write.wait_for_active_shards` to `all` or a specific number of shards made no noticeable difference.

I experienced this on 4.6.6 and still experience it on 4.7.1.

Example table structure:

```SQL
CREATE TABLE jobs (
    id TEXT PRIMARY KEY NOT NULL,
    type_of TEXT NOT NULL,
    ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    query_ts_start TIMESTAMP WITHOUT TIME ZONE,
    query_ts_stop TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    duration INTEGER,
    status TEXT NOT NULL,
    details TEXT INDEX OFF,
    error_details TEXT INDEX OFF
) CLUSTERED INTO 1 SHARDS WITH ("number_of_replicas" = '3', "number_of_routing_shards"='2', "write.wait_for_active_shards"='4');
```

**Comment by remear** [comment]
I tested with a nightly build, `4.8.0-SNAPSHOT-58e2745` but didn't notice any change in behavior. I'm inclined to say #12228 didn't affect the issue I'm seeing. /cc @mfussenegger

With the same table config, I don't see this flakey behavior with a local single node cluster. Since the single node cluster lacks replicas, this makes me think the issue I'm experiencing is more specific to replicas.

**Comment by proddata** [comment]
@remear 

A workaround should be to set the refresh interval for a table to a fixed value (e.g. 1000[ms])

**Comment by remear** [comment]
Setting the refresh interval on the table has been a stable workaround so far. Thanks!

**Comment by proddata** [comment]
Seems like this is a (somewhat flaky) way to reproduce this issue

```sql
DROP TABLE IF EXISTS source_table;
DROP TABLE IF EXISTS sink_table;
CREATE TABLE source_table (txt TEXT, db DOUBLE);
CREATE TABLE sink_table (txt TEXT, db DOUBLE);
-- Timeout for 45 seconds ...
INSERT INTO source_table (txt,db) SELECT 'Hello World', 10 FROM generate_series(0,1,1);
Timeout for 5 seconds ...
INSERT INTO sink_table SELECT txt, db FROM source_table;
Timeout for 5 seconds ...
SELECT * FROM source_table LIMIT 100;
Rows:  0
SELECT * FROM sink_table limit 100;
Rows:  0
```

Both row counts should be 2 in this case
Tested on a 3 node cluster
