### ISSUE TITLE
Mix up database vs. catalog vs. schema - `current_database()` should return `'doc'` or database needs to be called `'crate'`

### ISSUE THREAD

**Issue by proddata** [crate/crate#12107]
CrateDB does not support the concepts of multiple **databases** / **catalogs**, but only support schemas / namespaces for tables and other database objects. The default namespace of CrateDB is `doc`, but also the default database for CrateDB is called `doc`.  PostgreSQL on the other hand uses `postgres` as default database name and `public` as default schema / namespace.

CrateDB uses `doc` for catalog/database, except in `pg_catalog` tables and `current_database()`

|  | CrateDB | PostgreSQL | 
| - | - | - | 
| default database name |doc | postgres |
| `current_database()` |**crate** | postgres   |
| `select datname from pg_catalog.pg_database;`|**crate** | postgres | 
| `information_schema.***.table_catalog` | doc,pg_catalog,sys,...| postgres |
| default schema/namespace | doc | public |
| `current_schema()`  |doc | public  |

**Suggestion**
- Change/unify the database/catalog name to `crate`
- Keep the default schema & namespace as `doc`

This changes might actually break the CrateDB JDBC driver / DBeaver connector

**Comment by mfussenegger** [comment]
What's `default database name` referring to?

**Comment by proddata** [comment]
> What's `default database name` referring to?

I think it is in almost all of our documentation we are referring to use `doc` as database name for any (postgres) connection (see https://crate.io/docs/crate/clients-tools/en/latest/) 
I am not sure if this has any technical implications at all.

However `current_database()` should be in line with table_catalog, or should it not be?

**Comment by proddata** [comment]
I think part of the confusion comes from
https://crate.io/docs/crate/reference/en/4.8/interfaces/postgres.html#database-selection

> Since CrateDB uses schemas instead of databases, the database parameter sets the default schema name for future queries. If no schema is specified, the schema `doc` will be used as default.

However in lots of `information_schema` tables the `schema` is used as `catalog`.
In a PostgreSQL world the `catalog` should be `'crate'` not the schema

---

So there are 2 points to this

1) Should `'crate'` (As the only catalog/database) consistently be used across tables / functions. Which it currently is not
2) Should the connection really used to set the current schema or should it rather be left to using connections settings like e.g. `currentSchema` in case of JDBC

**Comment by proddata** [comment]
The adjustments to `crate` as default catalog have been largely done.
For the different behaviour regarding the `search_path` I created another issue: https://github.com/crate/crate/issues/13472
