### ISSUE TITLE
Support for upper cased letters in quoted schema identifiers

### ISSUE THREAD

**Issue by proddata** [crate/crate#12110]
**Use case**:
As a CrateDB user I want to be able to use upper cased letters as a table schema identifier, so that I can use the same style in table identifiers, as I do for columns.

**Feature description**:

```sql
CREATE TABLE "CamelCase".not_snake (txt TEXT);
```

**Comment by proddata** [comment]
relevant for [Dataiku](https://www.dataiku.com/de/)

**Comment by jeeminso** [comment]
To my understanding we would **not** want to allow:

```
cr> create table "Information_schema".t (a int);
cr> create table "DOC".t (a int);
```

**Comment by matriv** [comment]
Thx for reporting this improvement @proddata, it has been implemented with #13528

**Comment by BaurzhanSakhariev** [comment]
It seems like there are couple of follow ups to do: https://github.com/crate/crate/pull/13528#issuecomment-1411426039

**Comment by matriv** [comment]
yep, I see, just from the PR title this seemed finished, but also fine to keep it open until everything is addressed, thx!

**Comment by proddata** [comment]
@matriv Am I understanding it correctly, that the `_` underscore part is missing? If so, I think it might make more sense to create a separate issue.

**Comment by matriv** [comment]
Not important, as you like, if it's more clear with a separate issue, you could open it.

**Comment by proddata** [comment]
> Not important, as you like, if it's more clear with a separate issue, you could open it.

I created a new issue: https://github.com/crate/crate/issues/13578 and close this
