### ISSUE TITLE
crateDB support third party analyzer

### ISSUE THREAD

**Issue by wangDong524** [crate/crate#12145]
**Use case**:
Previous versions of crateDB supported third party analyzer the same as  Elasticsearch,But the Elasticsearch REST API has been removed in Version 4.0.0. How can I use third party analyzer in cratedb after version 4.0.0
**Feature description**:
 crateDB supported third party analyzer like  Elasticsearch

**Comment by seut** [comment]
See https://crate.io/docs/crate/reference/en/4.7/general/ddl/fulltext-indices.html#sql-ddl-custom-analyzer.

Please use the [Discussions](https://github.com/crate/crate/discussions) or https://community.crate.io/ for questions in future, issues are dedicated to feature requests and bug reports.
