### ISSUE TITLE
Show when tables are locked with blocks.read_only_allow_delete in Admin UI

### ISSUE THREAD

**Issue by robd003** [crate/crate#12270]
**Use case**: Currently if a node hits the high water mark for disk usage all tables will be locked with blocks.read_only_allow_delete and there is nothing to indicate that this happened in the Admin UI

**Feature description**: Put something to indicate that tables are locked in blocks.read_only_allow_delete mode and allow the user to click a button to resolve this. (Especially useful to apply this to ALL tables and not make the user do manual `ALTER TABLE tablename SET ("blocks.read_only_allow_delete" = FALSE);` for each table

**Comment by robd003** [comment]
One other idea is to _**automatically**_ unlock the tables ones the file system goes below the high water mark

**Comment by proddata** [comment]
> One other idea is to automatically unlock the tables ones the file system goes below the high water mark

This has already been merged into the master branch https://github.com/crate/crate/pull/12214 and should be available soon
