### ISSUE TITLE
RuntimeException when filtering on an unnested nested subscript 

### ISSUE THREAD

**Issue by proddata** [crate/crate#12352]
### CrateDB version

4.7.1

### CrateDB setup information

does not matter

### Steps to Reproduce

```sql
CREATE TABLE IF NOT EXISTS "doc"."test" (
   "a" ARRAY(OBJECT(DYNAMIC) AS (
      "b" ARRAY(TEXT)
   ))
)
```

```sql
SELECT _id, r.b FROM
(SELECT _id, UNNEST(a) b
FROM doc.test) r
WHERE 'hello' = r.b;
```

### Expected Result

0 rows

### Actual Result

```
Error
RuntimeException[com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'hello': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (StringReader); line: 1, column: 6]]
```

**Comment by jeeminso** [comment]
Hello @proddata, can we clarify the `Expected Result`? I think it could be something like ```SQLParseException[Cannot cast `'hello'` of type `text` to type `object`]```, since it is text to object comparison.

Similar to: 
```
cr> create table t12 (b boolean);
CREATE OK, 1 row affected  (0.477 sec)

cr> select * from t12 where b = 'hello';
SQLParseException[Cannot cast `'hello'` of type `text` to type `boolean`]
```

**Comment by proddata** [comment]
Oh ... I think I just messed up 🙈 

What I meant to write is: 

```sql
SELECT
    _id,r.b
FROM
    (
        SELECT
            _id,
            UNNEST(a) b
        FROM
            doc.test
    ) r
WHERE
    'hello' = any(r.b ['b'])
```

which works. I tricked myself with bad naming and nesting 

---

I am uncertain if we need a more detailed error message and would rather close it for now.
