### ISSUE TITLE
`ANALYZE` should be able to run with `AL` (admin) privileges 

### ISSUE THREAD

**Issue by proddata** [crate/crate#12383]
**Use case**:
As an admin user - without access to a super user - I still want to be able to run `ANAYLZE`.

_note: it is already possible to adjust `stats.service.interval` and indirectly trigger `ANALYZE`_

---

**Feature description**:
`ANALYZE` is allowed with `AL` privileges.

https://crate.io/docs/crate/reference/en/4.7/sql/statements/analyze.html

**Comment by mfussenegger** [comment]
https://github.com/crate/crate/blob/6386f0383f0c92e17562090c0aad4158f91fd14b/server/src/main/java/io/crate/auth/AccessControlImpl.java#L245 probably needs to implement `visitAnalyze`. Tests are in https://github.com/crate/crate/blob/6386f0383f0c92e17562090c0aad4158f91fd14b/server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java#L64
