### ISSUE TITLE
crateDB

### ISSUE THREAD

**Issue by yogeshac** [crate/crate#12401]
### CrateDB version

4.6.2

### Steps to Reproduce

create cratedb repository

### Expected Result

crate.client.exceptions.ProgrammingError: SQLActionException[RepositoryException: [] [autotat_repo] failed to create repository]

when i create the repository getting this error , how to resolve this issue 

### Actual Result

crate.client.exceptions.ProgrammingError: SQLActionException[RepositoryException: [] [autotat_repo] failed to create repository]

when i create the repository getting this error , how to resolve this issue

**Comment by proddata** [comment]
Hi yogeshac,

Please use https://community.crate.io/ for community support requests.
This GitHub repository is for reproducible bug reports and feature request only.

Also I noticed you posted on https://stackoverflow.com/questions/72026890/cratedb-repository-creation
where I was asking for more information.

best regards
@proddata
