### ISSUE TITLE
CrateDB package for Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by proddata** [crate/crate#12411]
- Ubuntu 22.04 LTS (Jammy Jellyfish) has been released
- Ubuntu 16.04 LTS (Xenial Xerus) Hardware and maintenance support has ended.

**Request**
Make packages for Ubuntu 22.04 LTS available and remove 16.04 LTS from supported distros.

also see:
https://ubuntu.com/about/release-cycle

**Comment by mfussenegger** [comment]
The latest packages have been published for Ubuntu 22.04
