### ISSUE TITLE
support  post json with HTTP upload requests

### ISSUE THREAD

**Issue by qiuweili123** [crate/crate#12423]
like  this:
curl --location-trusted  -H "format: json"   -T user_record.json  http://127.0.0.1:8040/api/user

**Comment by mfussenegger** [comment]
I am not sure if this fits with the product vision. We focus on the SQL interface and don't really have plans to extend the HTTP endpoints further.

I'll leave this open but adding something like this currently has a very low priority.

**Comment by mfussenegger** [comment]
We discussed this some more and concluded that it is not something that we'll want to add.

What we can imagine doing is to instead add some variant of `COPY` that allows uploading files from the client side (The current version requires the files to be on the server nodes, or on some external location via HTTPS/S3, ..)
