### ISSUE TITLE
Can't build query from constant column in subselect 

### ISSUE THREAD

**Issue by proddata** [crate/crate#12448]
### CrateDB version

4.7.1

### CrateDB setup information

3 node cluster
tool: gooddata (goodata.com)

### Steps to Reproduce

```sql
create table t01 (val long, grp long);
insert into t01 values (1,1),(2,1),(3,2);

select sum(val), grp, true as b from t01
group by grp;
-- returns 2 rows

select * from (
	select sum(val), grp, true as b from t01
	group by grp
) it
where b
-- SQL Error [XX000]: ERROR: Can't build query from symbol true AS b
```

### Expected Result

2 rows

### Actual Result

SQL Error [XX000]: ERROR: Can't build query from symbol true AS b

**Comment by seut** [comment]
We've fixed this by #12474. Thank you for reporting.
