### ISSUE TITLE
Add `has_schema_privilege` system information function

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#12457]
**Use case**:
The [Progress DataDirect PostgreSQL ODBC driver](https://www.progress.com/odbc/postgresql) sends the following query to obtain primary key information, including a call to `has_schema_privilege` that currently doesn't exist:

```sql
SELECT g AS cat, 
       n.nspname          AS SCHEMA, 
       c.relname          AS NAME, 
       a.attname          AS colnam, 
       i.conkey[s.n]      as kseq, 
       i.conname          AS NAME 
FROM   current_database() g, 
       pg_catalog.pg_namespace n, 
       pg_catalog.pg_class c, 
       pg_catalog.pg_attribute a, 
       pg_catalog.pg_constraint i, 
       ( 
              SELECT * 
              FROM   generate_series(1,32,1)
       ) s(n) 
WHERE  c.oid=i.conrelid 
AND    n.oid=c.relnamespace 
AND    i.contype='p' 
AND    a.attrelid=i.conrelid 
AND    a.attnum=i.conkey[s.n] 
AND    (NOT a.attisdropped) 
AND    has_schema_privilege(n.oid,'USAGE') 
AND    c.relname = 'persons' 
AND    a.attrelid = '"persons"'::regclass
```

**Feature description**:
See [PostgreSQL](https://www.postgresql.org/docs/14/functions-info.html):
> has_schema_privilege ( [ user name or oid, ] schema text or oid, privilege text ) → boolean
> Does user have privilege for schema? Allowable privilege types are CREATE and USAGE.

**Comment by BaurzhanSakhariev** [comment]
I updated `SELECT g.current_database AS cat` to `SELECT g AS cat` as the former is not working and the latter is working and taken from the original report.
