### ISSUE TITLE
Performance issue, once every 24h. 

### ISSUE THREAD

**Issue by rjbaat** [crate/crate#12470]
### CrateDB version

4.6.7

### CrateDB setup information

I have 2 clusters, for 2 different customers. Both experience the same problem.

- Cluster is hosted in a k8s cluster with 3 nodes. 
- Cluster 1 has 7g Heap with k8s limit to 10Gi
- Cluster 2 has 2g Heap with k8s limit to 3Gi
- Both of them are snapshotting to S3 every hour
- Both of them are deleting old snapshots every hour

### Observed behavior

Now both cluster have at a interval of +/- 24h a performance issue. Where we do see spikes in the throughput and IOPS. The logs don't say much other then this around the time: Found stale root level blobs ... Cleaning them up.

Is there a internal process in Crate that does some syncing of cleanup once every 24h that can lock the cluster for a bit?

### Steps to Reproduce

I am not sure what the cause is or how to reproduce, other then setting up a cluster with a script triggering a hourly snapshot and hourly cleanup.

### Maintainer notes

- We could add some throttling for the ANALYZE operation to reduce the impact it has.

**Comment by seut** [comment]
Yes by default the cluster is collecting statistic information of all tables every 24h. See https://crate.io/docs/crate/reference/en/4.8/config/cluster.html#stats-service-interval.
These statistics are used to optimize execution plans and to fill the `pg_stats` table, see https://crate.io/docs/crate/reference/en/4.8/admin/system-information.html#pg-stats.

You can disable it by adjusting the `crate.yml` config or during runtime by:

`SET GLOBAL 'stats.service.interval'=0;` 

In future, please consider using our community at https://community.crate.io/ for support questions in the first place. Thank you.

**Comment by seut** [comment]
I'll close the issue for now. If you still experience issues like that, please re-open.

**Comment by rjbaat** [comment]
@seut Thnx for your quick reply! I will check it out and in future I will go to the the community first 👍🏻.

**Comment by seut** [comment]
I've re-opened it cause I wonder that collecting the statistic causes a significant high load, can you give us a bit more information what higher load you experience?
for example: cluster is idling but stats collecting causes 100% for a short period...

**Comment by rjbaat** [comment]
@seut thnx for your reply. 
I have collected some charts from Grafana and attached them. 

![CPU](https://user-images.githubusercontent.com/2822419/167370846-b8fc2ab5-afd4-4aea-a79e-1b7881ac45f7.png)
![Memory](https://user-images.githubusercontent.com/2822419/167370852-a6d29b8a-afb0-4ae6-b60a-f2e65e9e18be.png)
![Throughput](https://user-images.githubusercontent.com/2822419/167370853-f4bf526d-81c2-43e0-bda2-e5531d004092.png)
![IOPS](https://user-images.githubusercontent.com/2822419/167370855-604cc4ee-6c7b-49c1-809c-6906b31e7e55.png)


The cpu doesn't seam to be affected that much.
The interesting thing on the Memory part is that it drops a bit. So it looks like its cleaned up. Maybe by garbage collector? 

The most interesting charts are the IOPS and Throughput. So i am wondering that maybe the crate cluster itself is not that affected but the network is quite saturated so user request to the platform using crate as db won't get through. Maybe you have a better understanding of what can cause the slow requests to the platform? Maybe it's also a combination of cleaning old snapshots and on the same time running the stats collection and serving queries to our platform. 

Also I wanted to try to disable the stats collection at all. But iam not sure it that has significant consequences to the crate database behavior. Is it safe to do?

Because I don't think I can set a specific time for the stats collection, like only at night. Or is it the same behavior as he ANALYSE command referred to: https://crate.io/docs/crate/reference/en/4.8/sql/statements/analyze.html#analyze. So I can disable it and maybe manually run the ANALYSE command at night. 
Is this a function that must be run on a good performing cluster?

**Comment by seut** [comment]
> Because I don't think I can set a specific time for the stats collection, like only at night. Or is it the same behavior as he ANALYSE command referred to: https://crate.io/docs/crate/reference/en/4.8/sql/statements/analyze.html#analyze. So I can disable it and maybe manually run the ANALYSE command at night.

Yes exactly, it will just trigger `ANALYZE`. So running this statement once every 24h at a specific time will do the same and you'll have more control over it.

> Is this a function that must be run on a good performing cluster?

In general yes, in details it depends on the queries you run. Currently, mostly join and grouping query (sub) plans are optimized using these stats, but in future probably more optimizer will use it.

**Comment by mfussenegger** [comment]
Kinda related to https://github.com/crate/crate/issues/10240 and https://github.com/crate/crate/pull/10239

**Comment by rjbaat** [comment]
@seut thnx. I will implement the ANALYSE then, to have more control over when this is running.

**Comment by BaurzhanSakhariev** [comment]
Hi @rjbaat, we added a new setting `stats.service.max_bytes_per_sec` in https://github.com/crate/crate/pull/13046. It will be released in CrateDB 5.1 and can be used to throttle `ANALYZE` statements.
