### ISSUE TITLE
Support `sum` on values of type interval

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#12480]
**Use case**:

Get the total duration over many events. Something like `select sum(age(ended, started)) from myevents` or `select sum(ended - started) from myevents` - depending on https://github.com/crate/crate/issues/12479

See https://github.com/crate/crate/blob/dc3ce297b1597d482949a2e57479890feb3adbf4/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java#L67-L98 for current supported sum overloads

**Comment by BaurzhanSakhariev** [comment]
Do we need to specify how we sum intervals? Let's say we split February into 20 and 8 days, then answer is:
1. sum of interval vectors (sec1, min1, hour1, etc) + (sec2, min2, hour2, etc) `-> returns 28 days`
2. date-aware/interval specific sum `-> returns 1 month, what age would return for [01.02-28.02]`

I think `#1` is fine? `#2` is more complex as we would need to keep things in memory to fold intervals (can be even overlapping, i.e repeat example intervals and cover February multiple times). 

However, with `#1` we can have answer like `45 days, 1 month` - i.e smaller time units are not necessarily grouped into larger units while it's always the case for the single interval.

**Comment by BaurzhanSakhariev** [comment]
it's sum with grouping, so 45 days, 1 month is not possible.

```
 select '15 days'::interval + '30 days'::interval + '1 month'::interval;                                                                                                                                             
+-------------------------------+
| 'P1M6W3D'::interval           |
+-------------------------------+
| 1 mon 6 weeks 3 days 00:00:00 |
+-------------------------------+
```

**Comment by matriv** [comment]
Postgres doesn't seem to increase to the next bigger unit, for days and smaller units but it overflows:
```
postgres=# select interval '6 months 17 days 22 hours' + interval '7 months 14 days 4 hours';     
           ?column?            
-------------------------------
 1 year 1 mon 31 days 26:00:00
(1 row)
postgres=# select interval '6 months 17 days 22 hours' + interval '7 months 14 days 4 hours';  
           ?column?            
-------------------------------
 1 year 1 mon 31 days 26:00:00
(1 row)

postgres=# select interval '2 years 6 months 17 days 22 hours' + interval '1023 years 27 months 12 weeks 27 days 108 hours';  
               ?column?               
--------------------------------------
 1027 years 9 mons 128 days 130:00:00
(1 row)
```

at least it seems that sum behaves as normal addition:
```
postgres=# insert into s values(interval '2 years 6 months 17 days 22 hours'),('1023 years 27 months 12 weeks 27 days 108 hours');
INSERT 0 2
postgres=# select sum(i) from s;
                 sum                  
--------------------------------------
 1027 years 9 mons 128 days 130:00:00
(1 row)

postgres=# insert into s values(interval '2 years 123 months 117 days 122 hours');
INSERT 0 1
postgres=# select sum(i) from s;
              sum              
-------------------------------
 1040 years 245 days 252:00:00
(1 row)
```
