### ISSUE TITLE
Ability to cast `TEXT` values to `CHAR`

### ISSUE THREAD

**Issue by proddata** [crate/crate#12512]
**Use case**:
PostgreSQL compatibility / Schema retrieval on JDBC/ODBC (Progress) driver site

**Feature description**:

```sql
Select 'A'::CHAR 
-- returns A

Select 'AB'::CHAR    
-- returns A 
```

**Comment by proddata** [comment]
It also seems like the numeric to char casting deviates from PostgreSQL

PostgreSQL 14:
```sql
# SELECT 13::char;
 bpchar 
--------
 1
```

CrateDB 4.8
```sql
# SELECT 13::char;
 int 
--------
 13
```

**Comment by seut** [comment]
Currently we've added `char` as an alias to our long-existing numeric `byte` data type which follows numeric cast semantics. This explains the current cast semantics, but they are clearly wrong for `char`.

But the `byte` type also lacks the possibility to cast from a `TEXT` type (just not exposed maybe by mistake, implementation is there). Even if we'd fix that, it would result in a different result than the expected cast for `char` as it would try to parse the given text value to a numeric value (thus `'123'::byte` -> 123 while `'foo'::byte` raises a numeric parse error). 

I think we should create a dedicated `char` type implementation to fix the casting behaviour.

**Comment by seut** [comment]
We decided to go for a) for now.
Implementing a storable `character(length)` type could be done as a followup.

**Comment by seut** [comment]
fyi: we went with c) and implemented a fully supported `character` type by https://github.com/crate/crate/commit/1866a331f90aaaeabc6a789a2c11cee2aac5c611
