### ISSUE TITLE
Changing `codec` on existing partitions appears to have no effect

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#12629]
### CrateDB version

4.8.0

### Steps to Reproduce

1. Create a partitioned table:
    ```sql
    CREATE TABLE IF NOT EXISTS "tmp"."conditions" (
          "time" TIMESTAMP WITH TIME ZONE NOT NULL,
          "device_id" TEXT,
          "temperature" DOUBLE PRECISION,
          "humidity" DOUBLE PRECISION,
          "partition_key" INTEGER
     )
     PARTITIONED BY ("partition_key");
    ```
2. Insert some data to create a partition (should be enough data to notice the effect of compression later on)
3. Change the partitions' codec:
    ```sql
    ALTER TABLE tmp.conditions PARTITION (partition_key = 1) CLOSE;
    ALTER TABLE tmp.conditions PARTITION (partition_key = 1) SET (codec = 'best_compression');
    ALTER TABLE tmp.conditions PARTITION (partition_key = 1) OPEN;
    ```
4. Verify the codec was changed:
     ```sql
     SELECT settings['codec']
     FROM information_schema.table_partitions
     WHERE table_schema = 'tmp'
       AND table_name = 'conditions';
    ```
    Returns: `best_compression` 
5. To be on the safe side (not sure if needed), also run `OPTIMIZE TABLE tmp.conditions`

*Observation*
After changing `codec`, the table size doesn't decrease. Creating a copy of the same data with `codec = 'best_compression'` set during `CREATE TABLE` shows that the partition size is noticeably smaller if compression is applied successfully. Therefore, it seems as if compression with the workflow above isn't actually changed.

Also see the related [community discussion](https://community.crate.io/t/optimizing-storage-for-historic-time-series-data/762/4).

### Expected Result

Not sure if changing the codec on an existing partition is supposed to work, but I would expect one of the following outcomes:
1. The partition size does decrease
2. There is an error message stating that changing `codec` for existing partitions isn't supported

### Actual Result

Compression doesn't change, even after waiting for a few hours.

**Comment by seut** [comment]
@hammerhead A changed `codec` of a table/partition will only take effect after it's segments have been merged. This can be forced by using the [`OPTIMIZE`](https://crate.io/docs/crate/reference/en/4.8/sql/statements/optimize.html) statement. Have you tried that?

**Comment by seut** [comment]
@hammerhead 
> Changing codec on non-partitioned tables seems not possible, is this correct?

No this looks like a bug, there isn't any reason to forbid that for whole tables. Also as you mentioned, the behaviour is contradicting.
