### ISSUE TITLE
Ability to use fully qualified names i.e. `catalog` when specifying db objects

### ISSUE THREAD

**Issue by proddata** [crate/crate#12658]
**Use case**:

PosgreSQL client compatibility (e.g. Trino)
SQL compliance

**CrateDB**
```sql
CREATE TABLE doc.x (txt TEXT)
SELECT crate.doc.x.txt FROM crate.doc.x
```

**PostgreSQL**
```sql
postgres=# CREATE TABLE public.x (txt TEXT);
CREATE TABLE
postgres=# SELECT postgres.public.x.txt FROM postgres.public.x;
 txt 
-----
(0 rows)
```

[From PostgreSQL docs](https://www.postgresql.org/docs/14/ddl-schemas.html)
> `database.schema.table`
> can be used too, but at present this is just for pro forma compliance with the SQL standard. If you write a database name, it must be the same as the database you are connected to.

https://crate.io/docs/sql-99/en/latest/chapters/18.html#table-name

**Comment by hammerhead** [comment]
To elaborate a bit more on the impact regarding Trino:

Specifically `INSERT` statements are affected by this. In earlier Trino versions, setting the connection URL to `jdbc:postgresql://localhost:5432/` (omitting a database name) used to be a workaround, but in more recent versions, Trino apparently attempts to always put a database name into the table identifier.

Therefore, `INSERT INTO doc.t1 VALUES (1);` will fail with all possible combinations:
* `jdbc:postgresql://localhost:5432/` -> `INSERT INTO "u1"."doc"."t1" ("a") VALUES (1)` (missing database name substituted by Trino with the username 🤔)
* `jdbc:postgresql://localhost:5432/doc` -> `INSERT INTO "doc"."doc"."t1" ("a") VALUES (1)`
* `jdbc:postgresql://localhost:5432/crate` -> `INSERT INTO "crate"."doc"."t1" ("a") VALUES (1)`

`SELECT` statements from Trino still work, they use the simple `schema_name.table_name` identifier pattern.

Tested with Trino version 387.

**Comment by proddata** [comment]
Also relevant for **dbt**

```sql
SELECT *
FROM "doc"."dbt_gtraar"."my_first_dbt_model"
WHERE "id" = 1
LIMIT 500
```

I this case also https://github.com/crate/crate/pull/12652 is relevant
checking against the constant `DB_NAME` imho is really only possible with the above PR.
Otherwise it should probably just be ignored.
