### ISSUE TITLE
Feature request: Encryption at rest

### ISSUE THREAD

**Issue by KevinBLT** [crate/crate#12665]
Hello everyone, 

I am considering switching our MariaDB Galera cluster to CreateDB. The main reason is the sharding model (which will hopefully save some storage capacity since it's not replicated fully on every server) and the easier scaling model. Although I would need this feature to have a full replacements without a degradation in the security area. Many solutions only offer this in their "enterprise version" but I almost always find them far too expensive for a small company like ours.

**Use case**:
Often it's a requirement for cyber security audits to have "encryption at rest" enabled for the database - at least when it contains sensitive data. It would be nice to have it enabled for CrateDB

**Feature description**:  
Mostly enable a secret key in a cratedb config and files/blocks on disk would be be encrypted/decrypted before they are written to disk/loaded into memory.

Is this anywhere on the roadmap actually?

Thanks and have a nice day

Kevin

**Comment by proddata** [comment]
Hi @KevinBLT 

Many deployments nowadays run on Kubernetes with encrypted PVCs, which provides encryption at rest on a cluster level.

Implementing it on the node / database level, would probably require for that functionality to be added to Lucene. There are open issues for this:
https://issues.apache.org/jira/browse/LUCENE-6966
https://issues.apache.org/jira/browse/LUCENE-9379
However I don't think that they will be implemented soon.

So the current recommendation is to either use OS level or disk level encryption.

**Comment by KevinBLT** [comment]
Hi @proddata

Thanks for the information - I understand!  
So I would consider encryption the specific values on application level where necessary.

Otherwise, if it will be there at a later point in time by Lucene, it would still be awesome :-)
