### ISSUE TITLE
`pg_get_userbyid()` should return actual user/role name

### ISSUE THREAD

**Issue by proddata** [crate/crate#12678]
**Use case**:
>pg_catalog.pg_get_userbyid(N.datdba) as "owner"

`pg_catalog.pg_get_userbyid` always returns `crate` - I think it needs to be updated to return actual user name by oid.

_Originally posted by @BaurzhanSakhariev in https://github.com/crate/crate/issues/12677#issuecomment-1169629376_

**Comment by BaurzhanSakhariev** [comment]
For potential contributors:

It can be done similar to `has_schema_privilege`:

non-compiled version can get `UserLookup` from the `NodeContext`, see
https://github.com/crate/crate/blob/88113a477d313358af68e1bfed53e79940ecaa47/server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java#L285  

compiled version is create in `compile()` which accepts `UserLookup` directly, see https://github.com/crate/crate/blob/88113a477d313358af68e1bfed53e79940ecaa47/server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java#L223
