### ISSUE TITLE
Possible bug with `array_length` function

### ISSUE THREAD

**Issue by amotl** [crate/crate#12689]
### CrateDB version

4.8.1

### CrateDB setup information

```
docker run --rm -it --publish=4200:4200 --publish=5432:5432 crate:4.8.1 -Cdiscovery.type=single-node
```

### Steps to Reproduce

```sql
create table tbl (id int primary key, xs int[]);
insert into tbl (id, xs) values (1, [1, 2, 3]), (2, null), (3, []);
refresh table tbl;
select *, array_length(xs, 1) from tbl;
```

### Expected Result

```text
+----+-----------+---------------------+
| id | xs        | array_length(xs, 1) |
+----+-----------+---------------------+
|  1 | [1, 2, 3] |                   3 |
|  2 | NULL      |                   0 |
|  3 | []        |                   0 |
+----+-----------+---------------------+

```

### Actual Result

```text
+----+-----------+---------------------+
| id | xs        | array_length(xs, 1) |
+----+-----------+---------------------+
|  1 | [1, 2, 3] |                   3 |
|  2 | NULL      |                NULL |
|  3 | []        |                NULL |
+----+-----------+---------------------+
```

### Different perspective
```
cr> select * from tbl where array_length(xs, 1) = 0;
+----+----+
| id | xs |
+----+----+
+----+----+
SELECT 0 rows in set (0.003 sec)
```

### References
- https://github.com/crate/crate/issues/9398#issuecomment-1169750540
- https://github.com/crate/crate/pull/12688

**Comment by amotl** [comment]
While exploring this area, I noticed another thing I would like to share in this context. I don't know if this is a convenience behavior or if it would classify as ambiguity and would need an improvement. Please let me know if this needs to be a different issue instead, then I will transfer it.
```
cr> select * from tbl where xs is null;
+----+------+
| id | xs   |
+----+------+
|  2 | NULL |
|  3 | []   |
+----+------+
```

**Comment by amotl** [comment]
Following up on @mfussenegger's response at https://github.com/crate/crate/issues/9398#issuecomment-1169750540: Would that also be a valid query to match empty or unassigned values in `array`-type columns, without needing the `array_length` function at all? Is it inefficient?

```
cr> select * from tbl where xs is null or xs = [];
+----+------+
| id | xs   |
+----+------+
|  2 | NULL |
|  3 | []   |
+----+------+
```

**Comment by amotl** [comment]
Oh I see. @seut outlined both of my observations at https://github.com/crate/crate/issues/9398#issuecomment-559750730 already.

**Comment by seut** [comment]
@amotl 
This does not look like a bug to me, but expected behaviour.
For example, PG is behaving the same:

```
postgres=# create table t2 (id int, i int[]);
CREATE TABLE
postgres=# insert into t2 values (1, null), (2, array[1,2]), (3, array[]::integer[]);
INSERT 0 3
postgres=# \pset null 'NULL'
Null display is "NULL".
postgres=# select id, array_length(i, 1) from t2;
 id | array_length 
----+--------------
  1 |         NULL
  2 |            2
  3 |         NULL
(3 rows)
```

**Comment by seut** [comment]
I'll close this, as it works as expected. Please reopen if there is a concrete reason why the current behaviour should be changed.

**Comment by amotl** [comment]
Oh I see. I didn't exercise it with PostgreSQL, apologies. I would say we close this issue then, but maybe let's add a comment to https://github.com/crate/crate/issues/9398#issuecomment-1169750540 that the `array_length(xs, 1) = 0` expression will not work?
