### ISSUE TITLE
CREATE SERVER / FOREIGN DATA WRAPPER

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#12686]
## Use case

Adding another server or storage (blob store) to CrateDB (Either another CrateDB cluster, or a JDBC compatible data source) to transparently query data from the other system.
E.g could connect to PostgreSQL for reads, to have interop with a system supporting transactions

This subsumes several other issues:

- https://github.com/crate/crate/issues/8914
- https://github.com/crate/crate/issues/9065
- https://github.com/crate/crate/issues/6945

## Full Feature description

- [CREATE SERVER](https://www.postgresql.org/docs/current/sql-createserver.html)
- [CREATE FOREIGN TABLE](https://www.postgresql.org/docs/current/sql-createforeigntable.html)
- [CREATE FOREIGN DATA WRAPPER](https://www.postgresql.org/docs/current/sql-createforeigndatawrapper.html)
- [postgres_fwd](https://www.postgresql.org/docs/current/postgres-fdw.html)
- [Foreign data wrappers](https://wiki.postgresql.org/wiki/Foreign_data_wrappers)

## Subset for an initial version

- Create server
- Create foreign table
- Single built-in JDBC foreign data wrapper. No CREATE FOREIGN DATA WRAPPER
- None of the other statements
- No write support

## Open Question

- [DROP SERVER](https://www.postgresql.org/docs/current/sql-dropserver.html) in initial version?

## Notes, Thoughts and ideas

- We probably need at least one built-in wrapper, JDBC might be a good candidate?
  - Would we include concrete JDBC drivers by default?
- Could we utilize JNI/Project panama features to support existing PostgreSQL foreign data wrapper implementations?
- Could be an option to support querying files in CSV or PARQUET format, or snapshots (e.g. hosted via S3 or HTTP)
- Could be a solution for cold storage (query snapshots)

**Comment by helenap** [comment]
This will be incredibly useful!

**Comment by jahanzaib10** [comment]
Agree, would be really helpful!

**Comment by mfussenegger** [comment]
Merged an initial version with https://github.com/crate/crate/pull/15472, but there are still some follow ups to do:

- [ ] option validation for create server
- [ ] option validation for create foreign table
- [ ] `information_schema.foreign_table_options`
- [ ] `information_schema.foreign_server_options`
- [ ] `information_schema.user_mappings`

Performance related

- [ ] Predicate push down

And some more internal aspects:

- [ ] service loader for fdw
- [ ] unified `tables` in cluster state metadata
    - [ ] StreamInput/StreamOutput storage of cluster state metadata instead of xcontent

---

Not necessarily all in scope for the next feature release

**Comment by mfussenegger** [comment]
Created a few more issues as potential follow ups:

- https://github.com/crate/crate/issues/15717
- https://github.com/crate/crate/issues/15718
- https://github.com/crate/crate/issues/15720
