### ISSUE TITLE
Ability to skip rows in `COPY FROM` when importing `csv` files

### ISSUE THREAD

**Issue by proddata** [crate/crate#12872]
**Use case**:
- To allow importing files that might have comments or empty lines in the begininng
- To allow to skip header columns in `csv` files in headers together with a custom column list / the use of ordinal numbers.

```csv
val1,val2
1,2
```

```sql
CREATE TABLE t1 (
   v1 INTEGER,
   v2 INTEGER
);

-- val1 is mapped to v1 / val2 is mapped to v2
COPY t1 FROM 's3://test_bucket/test.csv'
WITH (FORMAT='csv', SKIP=1, HEADER=false)

-- val1 is mapped to v2 / val2 is mapped to v1
COPY t1 (v2, v1) FROM 's3://test_bucket/test.csv'
WITH (FORMAT='csv', SKIP=1, HEADER=false)
```

There is no real workaround as of now, other then editing the `.csv` and remove the header or import into a table with the same column names.

**Feature description**:

Have a `SKIP` option for `COPY FROM` which allows to specify the number of rows to be skipped while importing a file.
Default value: `0`.

```sql
COPY table1 FROM 's3://test_bucket/test.csv'
WITH ( FORMAT='csv', SKIP=2)
-- will skip the first 2 rows and treat the 3rd row as header column
```

```sql
COPY table1 FROM 's3://test_bucket/test.csv'
WITH ( FORMAT='csv', SKIP=1, HEADER=false)
-- will skip the first row and treat the 2nd row as regular column
```

**How are others handling this:**
- Cockroach has a `SKIP` option for `IMPORT INTO`
   https://www.cockroachlabs.com/docs/stable/import-into.html
- SQL Server has a `FIRSTSTROW`
  allowing to specify the first row to be processed

---

a different approach would be to change the behaviour of the `HEADER = true` option within CrateDB to not use the column names in the `csv` and instead always use ordinal numbers or the provided column list. (i.e. just skipping the first row) This would be more in line with PostgreSQL behaviour, however also would be a breaking change.

---
edit:
Alternative 2 would be a `Mapping = false` option that deactivates the mapping between columns in csv and cratedb tables and behave like PostgreSQL

**Comment by amotl** [comment]
Hi @jeeminso,

thanks for submitting #13231. Can I ask you to demonstrate the new feature/syntax on behalf of an example SQL statement? 

Afterwards, if @proddata confirms it works for his use-cases on behalf of some sample data, and using a nightly release, I think it will be safe to close this issue.

With kind regards,
Andreas.

**Comment by jeeminso** [comment]
Sure, thanks for looking into it. I hope this is enough.

```
$ echo -e "id\n1\n2\n3" > /tmp/t.csv
$ cat /tmp/t.csv 
id  <-- to be skipped
1   <-- to be skipped
2
3

cr> create table t (id int);
CREATE OK, 1 row affected  (0.190 sec)
cr> copy t from '/tmp/t.csv' with (header = false, skip = 2, format = 'csv') return summary;
+--------------------------------------------------------+-------------------+---------------+-------------+--------+
| node                                                   | uri               | success_count | error_count | errors |
+--------------------------------------------------------+-------------------+---------------+-------------+--------+
| {"id": "xp2jbVQ5T9KYoGzQVTLTVg", "name": "Hirschkopf"} | file:///tmp/t.csv |             2 |           0 | {}     |
+--------------------------------------------------------+-------------------+---------------+-------------+--------+
COPY 1 row in set (0.399 sec)
cr> select * from t;
+----+
| id |
+----+
|  3 |
|  2 |
+----+
SELECT 2 rows in set (0.038 sec)

```

**Comment by seut** [comment]
@amotl We usually close request as soon as they are done. If the solution doesn't fix the requested use-case, the user can re-open the issue anytime with new insights.
