### ISSUE TITLE
Add support for merging two objects into a new one

### ISSUE THREAD

**Issue by proddata** [crate/crate#12979]
### Problem Statement

I came across this, when looking into the[ CrateDB Telegraf Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/cratedb/cratedb.go). Telegraf / Influx uses `tags` (key/value) and a `name` to identify a collection of metrics.

e.g.
```json
{
    "name": "device_A",
    "timestamp": 1662553982746,
    "tags": {
        "sensors": "speed_temperature"
    },
    "metrics": {
        "temperature": 21,
        "speed": 200
    }
}
```
However it can also happen, that this is split up into multiple messages:

```json
{
    "name": "device_A",
    "timestamp": 1662553982746,
    "tags": {
        "sensors": "speed_temperature"
    },
    "metrics": {
        "speed": 200
    }
}
{
    "name": "device_A",
    "timestamp": 1662553982746,
    "tags": {
        "sensors": "speed_temperature"
    },
    "metrics": {
        "temperature": 21
    }
}
```
as with Influx as target those metrics would just get merged. With the CrateDB adapter however, the 2nd insert would lead to an error message as it uses a simple `INSERT INTO` and the schema uses a PRIMARY KEY for `tags`, `name` and `timestamp`.

```sql
CREATE TABLE IF NOT EXISTS table_name (
	"hash_id" LONG INDEX OFF,
	"timestamp" TIMESTAMP,
	"name" STRING,
	"tags" OBJECT(DYNAMIC),
	"fields" OBJECT(DYNAMIC),
	"day" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', "timestamp"),
	PRIMARY KEY ("timestamp", "hash_id","day")
```

An option might be to not use primary keys after all, however streaming messaging inputs often can't guarantee exactly once delivery of messages.

---

In order to not drop the information, one option would be to merge the objects into a new objects with a scalar function / UDF:

```sql
CREATE TABLE t1 (
   pk TEXT PRIMARY KEY,
   obj OBJECT(DYNAMIC)
);

INSERT INTO t1 (pk, obj) VALUES ('a', {a = 1});

INSERT INTO t1 (pk, obj) VALUES ('a', {b = 2})
ON CONFLICT (pk) 
DO UPDATE SET  obj = object_merge(obj, excluded.obj);
```

Using UDFs in the telegraf plugin however is not viable, as it can't be guaranteed to be supported by the databases.

### Possible Solutions

Expose Javas `Map.merge()` as scalar function `object_merge(<object>,<object>)` merging the second object into the first one (overriding duplicate properties).

```sql
CREATE TABLE t1 (
   pk TEXT PRIMARY KEY,
   obj OBJECT(DYNAMIC)
);

INSERT INTO t1 (pk, obj) VALUES ('a', {a = 1});

INSERT INTO t1 (pk, obj) VALUES ('a', {b = 2})
ON CONFLICT (pk) 
DO UPDATE SET  obj = object_merge(obj, excluded.obj);
```

### Considered Alternatives

UDF using `Object.assign()`

```sql
CREATE FUNCTION object_merge(obj1 OBJECT, obj2 OBJECT)
RETURNS OBJECT
LANGUAGE JAVASCRIPT
AS 'function object_merge(obj1, obj2) {
    return Object.assign(obj1,obj2);
}';

SELECT object_merge({a=1},{b=2}) ;
-- {"a":1,"b":2}

```

**Comment by proddata** [comment]
PostgreSQL has the `||` (concatenate) operator also available for `JSONB` Values

> from https://www.postgresql.org/docs/9.5/functions-json.html
> concatenate two jsonb values into a new jsonb value
>
> **Note**: The || operator concatenates two JSON objects by generating an object containing the union of their keys, taking the second object's value when there are duplicate keys. All other cases produce a JSON array: first, any non-array input is converted into a single-element array, and then the two arrays are concatenated. It does not operate recursively; only the top-level array or object structure is merged.

```sql
'["a", "b"]'::jsonb || '["a", "d"]'::jsonb → ["a", "b", "a", "d"]

'{"a": "b"}'::jsonb || '{"c": "d"}'::jsonb → {"a": "b", "c": "d"}

'[1, 2]'::jsonb || '3'::jsonb → [1, 2, 3]

'{"a": "b"}'::jsonb || '42'::jsonb → [{"a": "b"}, 42]
```

**Comment by seut** [comment]
@proddata Thank you for this well described request. I've changed the title to reflect the outcome one want to archive instead of mentioning a possible implementation as you also mentioned different options.
I actually would prefer concatenate operators like PG does over a scalar but we could also end up in implementing both.

**Comment by proddata** [comment]
The concatenate operator is already implemented for `array` values

i.e.
```sql
SELECT
  [1,2] || [3],
  array_cat([1,2], [3])
```
already works

for coherence one might also think about implementing concatenating `array` with `scalar` values, as an alternative to `array_append`
```sql
SELECT
  [1,2] || 3,
  array_append([1,2], 3)
```
