### ISSUE TITLE
Release packages for RHEL / CentOS 8 and 9

### ISSUE THREAD

**Issue by proddata** [crate/crate#13000]
### Problem Statement

Provide (yum/rpm) releases packages for RHEL and CentOS 8 and 9 (and other compatible Linux distributions)

**Comment by amotl** [comment]
Hi.

I've just verified the situation on both _CentOS Linux 8_ and _CentOS Stream 9_. While the canonical setup guidelines for Red Hat based systems [^1] seem to work successful on CentOS 8, importing the GPG key fails on CentOS 9. 

On the most recent release of CentOS 9, it reports:
```
[root@racker-centos-9 /]# rpm --import https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate: key 1 import failed.
```

On an earlier release, it just reported:
```
[root@racker-centos-9 /]# rpm --import https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate
error: https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate: key 1 import failed.
```

With kind regards,
Andreas.

[^1]: https://crate.io/docs/crate/tutorials/en/latest/self-hosted/red-hat.html

**Comment by BaurzhanSakhariev** [comment]
See https://github.com/elastic/elasticsearch/issues/85876 and https://github.com/elastic/elasticsearch/issues/85876

**Comment by seut** [comment]
We've changed our signing key to support (and prefer) the SHA512 algorithm using the great example at https://github.com/chrisberkhout/sha1-key-fix/blob/master/SHA1KeyFix.ipynb.
The public key at `https://cdn.crate.io/downloads/yum/RPM-GPG-KEY-crate` was updated also, so installations on RHEL 8/9 should work now.

**Comment by amotl** [comment]
Excellent. Thank you very much.

**Comment by matriv** [comment]
For future reference:
We tested and verified that:
- with the updated key, `.rpm` and `.deb` users with the old public key can install new packages, signed with the updated private key.
- `.rpm` and `.deb` new users, who download the new public key can also install old packages, signed with the old private key.
