### ISSUE TITLE
Expressions evaluated for automatic column names when constant

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13026]
### CrateDB version

5.0.1

### Steps to Reproduce

create table testexpeval (a int);
insert into testexpeval select 1;
select a/2 from testexpeval;
select 1.0/2 from testexpeval;

### Expected Result

If the idea is to use the expression as column name then the expected column names would be "a/2" and "1.0/2"

(JFYI PostgreSQL always evaluates the expression even if the result set is empty but it does not use it for column names)

### Actual Result

One column called "a/2" in the first case and "0.5" in the second case
This could be problematic when the expression would trigger an error or when the column names are used downstream without sanitisation

**Comment by mfussenegger** [comment]
Is this an actual issue for some legitimate use-case?

Otherwise I'd close this as wont-fix. Good practice is to use aliases to address expressions containing arithmetic or function calls.

**Comment by hlcianfagna** [comment]
Hi, this came out in the context of a discussion around https://crate.io/docs/crate/reference/en/4.8/interfaces/postgres.html#expressions
there are no requests about this connected with actual production use cases I am aware of

**Comment by mfussenegger** [comment]
Closing this for now.  If a compatibility issue pops up because of this please let us know /re-open
