### ISSUE TITLE
JSON formatted crash -c output

### ISSUE THREAD

**Issue by crucial7** [crate/crate#1304]
Hi,

It would be nice if there is a way to make crash output the -c data as a JSON format, similar to the way the HTTP Endpoint does the output.

Thanks,
- Sheriff

**Comment by chaudum** [comment]
the latest version of crash supports multiple output formats
https://github.com/crate/crash/commit/a9dfe2e19ce6d40361397c801e7fdd5ae07b77f8

download from pypi: https://pypi.python.org/pypi/crash
