### ISSUE TITLE
Regression in `information_schema.key_column_usage`?

### ISSUE THREAD

**Issue by amotl** [crate/crate#13102]
### CrateDB version

crate/crate:nightly (still works on 5.0.1)

### CrateDB setup information

```
docker pull crate/crate:nightly
docker run --rm -it --publish=4200:4200 crate/crate:nightly -Cdiscovery.type=single-node -Ccluster.routing.allocation.disk.threshold_enabled=false
```
vs.
```
docker run --rm -it --publish=4200:4200 crate/crate:5.0.1 -Cdiscovery.type=single-node -Ccluster.routing.allocation.disk.threshold_enabled=false
```

### Steps to Reproduce

```console
crash <<SQL
  CREATE TABLE testdrive ("id" TEXT PRIMARY KEY);
  SELECT column_name FROM information_schema.key_column_usage WHERE table_name = 'testdrive' AND table_catalog = 'doc';
SQL
```

### Expected Result

```
cr> CREATE TABLE testdrive ("id" TEXT PRIMARY KEY);
CREATE OK, 1 row affected  (0.217 sec)
cr> SELECT column_name FROM information_schema.key_column_usage WHERE table_name = 'testdrive' AND table_catalog = 'doc';
+-------------+
| column_name |
+-------------+
| id          |
+-------------+
SELECT 1 row in set (0.006 sec)
```

### Actual Result

```
cr> CREATE TABLE testdrive ("id" TEXT PRIMARY KEY);
CREATE OK, 1 row affected  (0.235 sec)
cr> SELECT column_name FROM information_schema.key_column_usage WHERE table_name = 'testdrive' AND table_catalog = 'doc';
+-------------+
| column_name |
+-------------+
+-------------+
SELECT 0 rows in set (0.080 sec)
```

**Comment by seut** [comment]
My fault, the `table_catalog` was using the `table_schema` value until now, which was wrong and we fixed it recently. See the related breaking changes entry https://crate.io/docs/crate/reference/en/master/appendices/release-notes/unreleased.html#breaking-changes.

**Comment by amotl** [comment]
All right. The query is coming from initial introspection queries run by the `dataset` package, see https://github.com/crate/crate-python/issues/456. Chances are that it may break integration with other tools as well, when they are running similar introspection queries?

**Comment by seut** [comment]
Ah right, seems like the query at our SQLAlchemy dialect for resolving the primary key constraint is wrong as it uses the `table_catalog` column with the `schema` argument. We must fix this query to use the `table_schema` column instead.
https://github.com/crate/crate-python/blob/master/src/crate/client/sqlalchemy/dialect.py#L270

**Comment by amotl** [comment]
Hi again,

this issue has been converged into a patch to the Python driver, see https://github.com/crate/crate-python/pull/459. As far as I can see, no other relevant/popular driver for CrateDB needs to be updated.

With kind regards,
Andreas.
