### ISSUE TITLE
Selecting empty arrays vs. NULL values when using non-primitive inner-types OBJECT and GEO_SHAPE

### ISSUE THREAD

**Issue by amotl** [crate/crate#13100]
### CrateDB version

5.0.1

### CrateDB setup information

```
docker run --rm -it --publish=4200:4200 crate/crate:5.0.1 -Cdiscovery.type=single-node -Ccluster.routing.allocation.disk.threshold_enabled=false
```

### Steps to Reproduce

I am using this `cratedb-check-empty-array.sh`.

```console
crash <<SQL
    DROP TABLE IF EXISTS testdrive;
    CREATE TABLE testdrive (details ARRAY(OBJECT));
    INSERT INTO testdrive (details) VALUES ([]);
    INSERT INTO testdrive (details) VALUES (NULL);
    REFRESH TABLE testdrive;
    SELECT count(*) AS count_array_is_null FROM testdrive WHERE details IS NULL;
SQL
```

### Expected Result

`IS NULL` does not match empty arrays.

### Actual Result

`IS NULL` also matches empty arrays. Regarding the example above, `count_array_is_null` is `2`, as it matches both example records.

### References

- https://github.com/crate/crate/pull/12704
- https://community.crate.io/t/cratedb-getting-the-count-of-null-values-excluding-empty-arrays/1245

**Comment by amotl** [comment]
Other than this, when invoking the reproduction program, you will find that the evaluation of the `WHERE details = []` constraint croaks on CrateDB 4.7.3 and higher with
```
SQLParseException[Cannot search on field [details] since it is not indexed.]
```

It still works on CrateDB 4.6.7. Let me know if this should go into a different issue.

**Comment by seut** [comment]
Btw. it works correctly when **NOT** using an array of objects but a non-composite inner type instead like e.g. `ARRAY(INT)`.
```
 crash <<SQL
    DROP TABLE IF EXISTS testdrive;
    CREATE TABLE testdrive (details ARRAY(INT));   
    INSERT INTO testdrive (details) VALUES ([]);
    INSERT INTO testdrive (details) VALUES (NULL);
    REFRESH TABLE testdrive;
    SELECT count(*) AS count_array_is_null FROM testdrive WHERE details IS NULL;
    SELECT count(*) AS count_array_equals_empty FROM testdrive WHERE details = [];
SQL
```

**Comment by amotl** [comment]
Hi again,

I've amended the title of this issue to better reflect the facts. Also, there is the [`cratedb-empty-array-special-type.py`](https://gist.github.com/amotl/48f927570cb37787b656f7704cb538a7) program now, which can be used to exercise the problem space.

- `python cratedb-empty-array-special-type.py null` shows that the `WHERE details IS NULL` check only does not work correctly on `ARRAY(OBJECT)` and `ARRAY(GEO_SHAPE)` column definitions, where it includes both records (`count(*)=2`).

- `python cratedb-empty-array-special-type.py equality` shows that the `WHERE details = []` check croaks on `ARRAY({IP,OBJECT,GEO_SHAPE,BIT})` column definitions.
  - IP: `NullPointerException[Cannot invoke "org.apache.lucene.index.SortedSetDocValues.advanceExact(int)" because "docValues" is null]`
  - OBJECT: `SQLParseException[Cannot search on field [details] since it is not indexed.]`
  - GEO_SHAPE: `UnsupportedFeatureException[NYI: geo_shape]`
  - BIT: `UnsupportedFeatureException[NYI: bit]`

With kind regards,
Andreas.

**Comment by BaurzhanSakhariev** [comment]
Hi @amotl, thanks for the detailed report! 

In the first revision I saw report on `OBJECT` column having the same issue.

Also, `IS NOT NULL` has the same issue
SELECT count(*) AS count_array_is_null FROM testdrive WHERE details IS NOT NULL returns 0 instead of 1 (same for non-array OBJECT column, 0 instead of 1.)

Those issues have the same root cause so will be address in a single patch.
