### ISSUE TITLE
JobKilledException when importing compressed files

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13113]
### CrateDB version

5.0.1

### Steps to Reproduce

`CREATE TABLE testgzip (n INTEGER);`
`INSERT INTO testgzip (n) SELECT * FROM generate_series(1,50);`
`COPY testgzip TO DIRECTORY 'file:///cratesnapshots/testgzip20221010/' WITH ( compression='gzip',format='json_object') ; 
/* use a directory that works for you */`
`DROP TABLE testgzip;`
`CREATE TABLE testgzip (n INTEGER);`
`COPY testgzip FROM 'file:///cratesnapshots/testgzip20221010/testgzip_0_.json.gz' WITH ( wait_for_completion = true,fail_fast=true ,compression=true,format='json',shared=true)   RETURN SUMMARY;`
/* that is just one of the files */

-- extract the .json from the .gz
`COPY testgzip FROM 'file:///cratesnapshots/testgzip20221010/testgzip_0_.json' WITH ( wait_for_completion = true,fail_fast=true ,compression=false,format='json',shared=true)   RETURN SUMMARY;`

### Expected Result

Rows should be imported when running against the .gz file same as when running against the extracted .json file

### Actual Result

The `COPY FROM` the .gz file fails with
`JobKilledException[Job killed. NODE: crate-1 [URI: file:///cratesnapshots/testgzip20221010/testgzip_0_.json.gz, ERRORS: {Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens at [Source: (byte[]) ...`

The `COPY FROM` the extracted file succeeds

I am also able to reproduce the problem manually creating a .json file and gziping it, and I can reproduce it both with a local drive and with Azure blob storage.

**Comment by seut** [comment]
The allowed values for the `compression` option of the `COPY FROM` commands are `null` and `gzip`. Using `gzip` will result in successfully imported data in your examples.
See also relevant documentation https://crate.io/docs/crate/reference/en/5.0/sql/statements/copy-from.html#compression.

Seems like we are missing a proper validation of the `compression` values, but I suggest to create a new issue related to that.
