### ISSUE TITLE
Cannot set default values for array cols

### ISSUE THREAD

**Issue by matriv** [crate/crate#13148]
### CrateDB version

5.1.0

### Steps to Reproduce

```
cr> create table test (
          id int  not null primary key,
          def int[] default [1,2]
        );
CREATE OK, 1 row affected  (1.703 sec)
```
```
cr> insert into test(id) values(1);
INSERT OK, 1 row affected  (0.054 sec)
```

### Expected Result

```
cr> select * from test;
+----+-------+
| id | def   |
+----+-------+
|  1 | [1,2] |
+----+-------+
SELECT 1 row in set (0.007 sec)
```

### Actual Result

```
cr> select * from test;
+----+------+
| id | def  |
+----+------+
|  1 | NULL |
+----+------+
SELECT 1 row in set (0.007 sec)
```

**Comment by matriv** [comment]
It's also not allowed to have a default value for objects:
```
create table test (
          id int  not null primary key,
          def object default {"a"='lala'});
MapperParsingException[Failed to parse mapping: Mapping definition for [def] has unsupported parameters:  [default_expr : {"a"='lala'}]]
```

**Comment by BaurzhanSakhariev** [comment]
We cover objects in `testCreateTableWithDefaultExpressionAsCompoundTypes` but in the example above schema is unknown while in the test case `key` is a known column - maybe has smth to do with that.

**Comment by BaurzhanSakhariev** [comment]
default value for arrays is fixed in https://github.com/crate/crate/pull/14007.

We will create a new issue for the case when trying to specify a default value to a unknown column

**Comment by BaurzhanSakhariev** [comment]
Dedicated issue to track bad error message with objects https://github.com/crate/crate/issues/14018
