### ISSUE TITLE
Array construction from subquery only respecting order if ORDER BY column is selected

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13197]
### CrateDB version

5.1.0

### CrateDB setup information

CRATE_HEAP_SIZE=1G

### Steps to Reproduce
`select height from sys.summits order by height desc LIMIT 3;`
`select array(select height from sys.summits order by height desc LIMIT 3);`
`select country from sys.summits order by height desc LIMIT 3;`
`select array(select country from sys.summits order by height desc LIMIT 3);`
/* based on the example from https://crate.io/docs/crate/reference/en/5.0/sql/general/value-expressions.html */

### Expected Result

4808,4634,4545
[4808,4634,4545]
"FR/IT","CH","CH"
["FR/IT","CH","CH"]

### Actual Result

4808,4634,4545
[4808,4634,4545]
"FR/IT","CH","CH"
--> ["CH","CH","FR/IT"] <--

This is problematic for downsampling functions which rely on the order of the input array.

**Comment by hlcianfagna** [comment]
I confirmed PostgreSQL respects the order in these cases

**Comment by matriv** [comment]
Indeed this is reproducable, it seems to be some error in analysis:
```
cr> create table lala(a int, name string);
CREATE OK, 1 row affected  (1.628 sec)
cr> insert into lala values(1, 'andreas'),(2, 'marios'),(3, 'spyros');
INSERT OK, 3 rows affected  (0.117 sec)
```
```
cr> explain select array(select name from lala order by a desc);
+----------------------------------------------+
| EXPLAIN                                      |
+----------------------------------------------+
| MultiPhase                                   |
|   └ Eval[(SELECT name FROM (doc.lala))]      |
|     └ TableFunction[empty_row | [] | true]   |
|   └ Eval[name]                               |
|     └ OrderBy[name ASC]                      |
|       └ Collect[doc.lala | [name, a] | true] |
+----------------------------------------------+
EXPLAIN 1 row in set (2.947 sec)
cr> select array(select name from lala order by a desc);
+---------------------------------+
| (SELECT name FROM (doc.lala))   |
+---------------------------------+
| ["andreas", "marios", "spyros"] |
+---------------------------------+
SELECT 1 row in set (12.869 sec)
```

If we order on the selected column the order (desc) is preserved:
```
cr> explain select array(select name from lala order by name desc);
+--------------------------------------------+
| EXPLAIN                                    |
+--------------------------------------------+
| MultiPhase                                 |
|   └ Eval[(SELECT name FROM (doc.lala))]    |
|     └ TableFunction[empty_row | [] | true] |
|   └ OrderBy[name DESC]                     |
|     └ Collect[doc.lala | [name] | true]    |
+--------------------------------------------+
EXPLAIN 1 row in set (2.520 sec)
cr> select array(select name from lala order by name desc);
+---------------------------------+
| (SELECT name FROM (doc.lala))   |
+---------------------------------+
| ["spyros", "marios", "andreas"] |
+---------------------------------+
SELECT 1 row in set (3.722 sec)
```

Notice, that in the first case the ordering happens on `name ASC` instead on `a DESC`

**Comment by matriv** [comment]
This change of the order by comes from `LogicalPlanner#tryOptimizeForInSubquery()` method where it removes existing order by and replaces it with a natural ordering, assuming that we are in an `IN` or `= ANY()` predicate.

By debugging I haven't found an easy/elegant way to know if we are in an IN (or ANY) predicate, or in this case not, so skip this optimization.

**Comment by mfussenegger** [comment]
> By debugging I haven't found an easy/elegant way to know if we are in an IN (or ANY) predicate, or in this case not, so skip this optimization.

We could set a hint in the `ExpressionAnalyzer` in the `IN` / `ANY` cases on the context that the inner sub-query is order-insensitive, and then set a property on the `SelectSymbol` based on that.

**Comment by matriv** [comment]
Thx, I will try that!
