### ISSUE TITLE
Node crashes with `OutOfMemoryError` instead of throwing `CircuitBreakingException` on `percentile` aggregation

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13198]
### CrateDB version

5.0.2

### CrateDB setup information

Number of nodes: 3
CrateDB heap size: 10 GB

### Steps to Reproduce

On a large table, run an aggregation query using `percentile` (here the NYC Taxi trips table):
```sql
select pickup_datetime, percentile(trip_distance, 0.50), vendor_id
from nyc_taxi.trips
group by 1, 3
order by 3 limit 100;
```

The table has 1,7 billion rows (392 GB). The issue was originally reported by a customer on a smaller table (147 million rows, 20 GB).

The heap dump from the customer is available (CrateDB Cloud cluster).

Trying a different aggregation method (e.g. `SUM`) doesn't cause a node crash and instead throws a `CircuitBreakingException`.

### Expected Result

No nodes crash, if too much memory is consumed, a `CircuitBreakingException` is thrown.

### Actual Result

One of the nodes crashes with `java.lang.OutOfMemoryError: Java heap space`.

**Comment by mfussenegger** [comment]
Thanks for the report, should be fixed with https://github.com/crate/crate/pull/13207
