### ISSUE TITLE
search_path order not honoured for pg_catalog functions

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13218]
### CrateDB version

5.1.0

### Steps to Reproduce

`CREATE FUNCTION public.version() RETURNS TEXT
LANGUAGE JAVASCRIPT
AS 'function version() {return "PostgreSQL 10.5";}';`

`SET search_path TO public, pg_catalog;`

`SELECT version();`

### Expected Result

"PostgreSQL 10.5"

as in PostgreSQL
(tested with
`CREATE FUNCTION version() RETURNS TEXT AS $$ BEGIN RETURN 'This is from the public schema'; END $$ LANGUAGE 'plpgsql';`
)

### Actual Result

CrateDB 5.1.0 (built 5c9617d/2022-10-11T09:39:39Z, Linux 5.19.0-23-generic amd64, OpenJDK 64-Bit Server VM 18.0.2+9)

Please note this works for `pg_catalog` tables, it seems to be an issue only for functions. 
Repro'ed also with a mock `generate_series`.

**Comment by proddata** [comment]
CrateDB
```sql
CONNECT OK
cr> SHOW search_path;                                                                                                           
+-----------------+
| setting         |
+-----------------+
| pg_catalog, doc |
+-----------------+
SHOW 1 row in set (0.013 sec)
cr> SET search_path TO public;                                                                                                  
SET OK, 0 rows affected  (0.006 sec)
cr> SHOW search_path;                                                                                                           
+--------------------+
| setting            |
+--------------------+
| pg_catalog, public |
+--------------------+
SHOW 1 row in set (0.006 sec)
```

PostgreSQL 14
```
gtraar=# SHOW search_path;
   search_path   
-----------------
 "$user", public
(1 row)

gtraar=# SET search_path TO public;
SET
gtraar=# SHOW search_path;
 search_path 
-------------
 public
(1 row)
```

**Comment by matriv** [comment]
makes sense, if you explicitly define the order you expect to be respected.

**Comment by mfussenegger** [comment]
Afaik it's intentional that you cannot shadow built-ins with user defined functions
