### ISSUE TITLE
`pg_catalog` in search_path behaves different if explicitly set by user or implicitly set by crate

### ISSUE THREAD

**Issue by proddata** [crate/crate#13232]
### CrateDB version

5.0.1

### Steps to Reproduce

```sql
cr> SHOW search_path;                                                                                                                                      
+-----------------+
| setting         |
+-----------------+
| pg_catalog, doc |
+-----------------+
SHOW 1 row in set (0.005 sec)

cr> SET search_path TO pg_catalog, doc;                                                                                                                    
SET OK, 0 rows affected  (0.002 sec)

cr> SHOW search_path;                                                                                                                                      
+-----------------+
| setting         |
+-----------------+
| pg_catalog, doc |
+-----------------+

cr> CREATE TABLE ta01 (t TEXT);                                                                                                                            
SQLParseException[Cannot create relation in read-only schema: pg_catalog]
SHOW 1 row in set (0.007 sec)

cr> SET search_path TO doc;                                                                                                                                
SET OK, 0 rows affected  (0.001 sec)

cr> SHOW search_path;                                                                                                                                      
+-----------------+
| setting         |
+-----------------+
| pg_catalog, doc |
+-----------------+
SHOW 1 row in set (0.006 sec)

cr> CREATE TABLE ta01 (t TEXT);                                                                                                                            
CREATE OK, 1 row affected  (0.484 sec)
```

### Expected Result

Both implicitly set and explicitly set search_path behave the same

### Actual Result

they don't

**Comment by matriv** [comment]
Is this still the case, after: https://github.com/crate/crate/pull/13223

**Comment by mfussenegger** [comment]
> Is this still the case, after: #13223 ?

Very likely, that change only affected function resolution.

In this case it's caused by:

https://github.com/crate/crate/blob/a8604bf19b7dee721f95d7cd889a57b36b1e03d6/server/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java#L59-L60

and:

https://github.com/crate/crate/blob/a8604bf19b7dee721f95d7cd889a57b36b1e03d6/server/src/main/java/io/crate/metadata/SearchPath.java#L89-L95

Which on a first glance looks like it was intentional

**Comment by proddata** [comment]
@mfussenegger 
I came across this, when checkin DBeaver with CrateDB 5.1 and `crate` as db/catalog name in the connection.
It seems like DBeaver is generating a `SET seach_path pg_catalog, pg_catalog, crate` from first fetching the current search_path from CrateDB. In PostgreSQL the default search_path is `"$user", public`, however you don't need to specify `pg_catalog` to acutally use tables/function from it.

So I don't really know yet if the different behaviour for explicit/implicit  setting is a problem, or having it in the search_path to begin with. (On a different note `doc` similar to `public` should probably implicitly be set)

```sql
gtraar=# SHOW search_path;
   search_path   
-----------------
 "$user", public
(1 row)

gtraar=# SELECT oid  FROM pg_class LIMIT 1;
  oid  
-------
 16396
(1 row)
```

**Comment by mfussenegger** [comment]
@proddata can you try if https://github.com/crate/crate/pull/13244 would solve the issue?

**Comment by proddata** [comment]
> @proddata can you try if #13244 would solve the issue?

only to some degree. i.e. the `pg_catalog` is not problematic anymore, but it seems like DBeaver is still adding the selected schema twice :/ 

DBeaver is running the following (with PostgreSQL connection).

```sql
SELECT current_schema(),session_user
SHOW search_path
SET search_path = doc,doc
```
I took a change looking at the DBeaver code, but it isn't really 

---

_edit:_ 🤦  ... ok this happens also with PG15 
```sql

**Comment by proddata** [comment]
Testing with current master again ..

- host: `localhost`
- db: `crate`
- user: `crate`

leads DBeaver to select `pg_catalog` as selected `schema`

<img width="213" alt="image" src="https://user-images.githubusercontent.com/23557193/205322957-c1619a8b-af99-4368-9618-5045ec583f5f.png">

which leads to the following `search_path` set in the dbeaver console:
```sql
pg_catalog, pg_catalog, crate
```

Choosing `schema` doesn't even list `pg_catalog` ...
<img width="634" alt="image" src="https://user-images.githubusercontent.com/23557193/205323165-2eee61a9-7b8b-44d6-8aed-e48297a9a1c1.png">

Manually selecting `doc` leads to the following `search_path` within the console
```sql
doc, pg_catalog, crate
```

_Note: (`crate` is coming from the pg connection taking the `db_name` as "default_schema")_
 

---

So the current DBeaver logic seems to take the current search path and prepends the schema selected by the client. Why this ends up to be `pg_catalog` is a good question, however https://github.com/crate/crate/pull/13244 definitely helps.

🤷
