### ISSUE TITLE
Ability to set a `statement_timeout` on the server site (and as session setting)

### ISSUE THREAD

**Issue by proddata** [crate/crate#13242]
### Problem Statement

To prevent long running queries - especially does not used anymore - from blocking resources on a CrateDB cluster, it would be good to have the option to set a statement timeout. This e.g. could happen, when a complex query has been started by a 3rd party tool, which the user does not fully have control over (e.g. BI tools)

### Possible Solutions

PostgreSQL and Cockroach have a `statement_timeout` (and various others https://www.postgresql.org/docs/15/runtime-config-client.html), which can be set for a cluster and as session setting.

**Description**
`statement_timeout` (integer)
Is a cluster setting, that allows to specify a time in milliseconds before a query is automatically canceled.
`0` is the default value and turns canceling off. This could also take `INTERVAL` values as an input.

Optional:
Be able to override this setting in a session, to explicitly run a longer query.
```sql
SET statement_timeout TO '60 minutes'::INTERVAL
```

**_To be discussed:_**
Should this only be relevant for `DQL` queries?

### Considered Alternatives

If the client does not support query timeouts on the protocol level, that use wire protocol canceling (which only a few do) first fetching data from `sys.jobs_log` and then using `KILL <job_id>` would be an approach. However you would need to do this with the `crate` superuser and do a scheduling outside of CratDB that checks for long running queries.

**Comment by mfussenegger** [comment]
We implemented `statement_timeout` as cluster and session setting and now allow setting session settings via the startup options for clients using the PostgreSQL wire protocol. See:

- https://github.com/crate/crate/pull/13980
- https://github.com/crate/crate/pull/14025
- https://github.com/crate/crate/pull/14045
