### ISSUE TITLE
COPY FROM retry logic does not handled SocketTimeout when parsing CSV header

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#13276]
### Problem Statement

CSV headers are read by `bufferedReader.readLine()` instead of `fileReadingIterator.getline()` which does not retry when `SocketTimeoutException` occurs.

**Comment by jeeminso** [comment]
Just leaned that [skip option](https://crate.io/docs/crate/reference/en/5.3/sql/statements/copy-from.html#skip) is affected as well. If the number of lines to skip is large, the chances of socket exceptions grow making this higher priority.

**Comment by mfussenegger** [comment]
I think this changed with https://github.com/crate/crate/pull/14625/
