### ISSUE TITLE
Crate-5.1.0 release Cursor Expected Result

### ISSUE THREAD

**Issue by Jiew23** [crate/crate#13301]
Hi there,

I was using the new cursor support to read a 17.2G file. Below is the time taken to read the entire file.

1. If reading 1,000,000 rows at a time: it took 6.223 hours to read the entire file.
2. If reading 10,000,000 rows at a time: it took 5.955 hours to read the entire file.

Below is the code I was using:

![code](https://user-images.githubusercontent.com/69634587/203884964-952e3b8c-d370-4c66-bbca-5e40ed031a58.png)

Could you please advise the expected time for reading the 17.2G file or any changes needs to be made to my code for efficiency? 

Thank you so much!

**Comment by BaurzhanSakhariev** [comment]
Hi @Jiew23, could you please try running without `print` (printing large volumes of data is quite expensive). And maybe let's move start time a bit lower, after creating a connection so that connecting time is not included.

**Comment by proddata** [comment]
For reference (tested with node.js and local single node)
for 30 Mio records (5.4 GiB) dataset

```sql
FETCH 10000 FROM this_cursor;
```
takes roughly 85 seconds to fetch all records


```sql
FETCH 100000 FROM this_cursor;
```
takes roughly 87 seconds to fetch all records
