### ISSUE TITLE
Consolidate `number_of_replicas`

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#13324]
Currently there are two names for it `number_of_replicas` and `index.number_of_replicas` where the latter originated from Elasticsearch and the former is for CrateDB. The names could be misused and cause bugs like https://github.com/crate/crate/pull/13296.

**Comment by seut** [comment]
This is not related to `number_of_replicas` but to all index settings instead. Changing the settings names would require a migration which I'm not sure if this is really worth doing.

**Comment by jeeminso** [comment]
Thanks for clarifying @seut.
