### ISSUE TITLE
Interrupted snapshots take a long time to expire

### ISSUE THREAD

**Issue by SStorm** [crate/crate#13376]
### Problem Statement

If you have a snapshot running that you interrupt in some way (i.e. restarting the node that is doing it), restarting the snapshot will fail with a `ConcurrentSnapshotExecutionException`. It currently takes 60 minutes for this state to expire, which is a pretty long time to wait. 

### Possible Solutions

How is the snapshot lock maintained, any way to manually remove it?

**Comment by seut** [comment]
Since CrateDB `5.2.0`, concurrent snapshot creations are supported (related commit https://github.com/crate/crate/commit/1242400cfe07d656b21fdaceb49a41558029367a) so this issue seems to be solved. The maximum allowed concurrent snapshot creation operations are `1000`.
