### ISSUE TITLE
Postgres 10.5 is deprecated and client tools are not connecting

### ISSUE THREAD

**Issue by robd003** [crate/crate#13398]
### Problem Statement

When trying to connect to CrateDB from the current version of Django it will complain that Postgres 10.5 has been deprecated and you can only connect to version 11 and above.

Postgres themselves deprecated version 10 back in November: https://www.postgresql.org/support/versioning/

Crate should appear as a "supported" Postgres database so client tools will connect without issues.

### Possible Solutions

Change the wire protocol version to 11

https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java#L193-L194

**Comment by BaurzhanSakhariev** [comment]
Closed by https://github.com/crate/crate/pull/13399. Thanks @robd003!
