### ISSUE TITLE
Bump Postgres Wire Protocol version to 14 or 15 

### ISSUE THREAD

**Issue by proddata** [crate/crate#13418]
### Problem Statement

With https://github.com/crate/crate/pull/13399 the reported PostgreSQL version has been bumped to `11`.
However also PostgreSQL version `11` will be EOL by the November 2023 and therefore not supported by some 3rd party tools.

> from https://www.postgresql.org/support/versioning/
> 
> Version | Current minor | Supported | First Release | Final Release
> -- | -- | -- | -- | --
> 15 | 15.1 | Yes | October 13, 2022 | November 11, 2027
> 14 | 14.6 | Yes | September 30, 2021 | November 12, 2026
> 13 | 13.9 | Yes | September 24, 2020 | November 13, 2025
> 12 | 12.13 | Yes | October 3, 2019 | November 14, 2024
> 11 | 11.18 | Yes | October 18, 2018 | **November 9, 2023**

Therefore I would suggest to go with a newer version (e.g. `14` or `15`) straight away.
Being aware that, PG 15 is "only" 3 months old, and some tools might not support  to be discussed.

- [ ] check / update the `pg_catalog` tables to adhere to the new post v10 schemas
- [ ] check for regression in compatibility test suites

**Comment by amotl** [comment]
Given that we observe that CrateDB is sometimes used for ages without upgrading, I also think it should be done sooner than later, if it does not cause any other harm.
