### ISSUE TITLE
Support comparison operators on BIT type

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#13434]
Query like `SELECT B'100' > B'10'` should work and return `true`. 

Other comparison operators, such as `>=`, `<=`, `<` should work as well.

Currently it fails with error:
`Unknown function: (B'100' > B'10'), no overload found for matching argument types: (bit, bit)`

**Comment by proddata** [comment]
> Query like SELECT B'100' > B'10' should work and return false.

should return `true` 😉

**Comment by BaurzhanSakhariev** [comment]
> > Query like SELECT B'100' > B'10' should work and return false.
> 
> should return `true` 😉

thanks, fixed the description.

**Comment by mfussenegger** [comment]
Closing this for now as there haven't been any upvotes or similar requests.

(Not a "never", if you have a concrete use-case for this please leave a comment explaining it)
