### ISSUE TITLE
Introduce an XML data type

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13441]
### Problem Statement

Some APIs provide/require data in XML format rather than JSON, and it can be convenient to store XML directly in the database, query it together with relational data, and eventually retrieve XML results directly from the database.

(question from the audience at Big Data Europe 2022)

### Possible Solutions

Something along the lines of https://learn.microsoft.com/en-us/sql/relational-databases/xml/xml-data-type-and-columns-sql-server?view=sql-server-ver16
or https://www.postgresql.org/docs/current/datatype-xml.html

### Considered Alternatives

XML data can currently be stored on a `TEXT` column and processed client side.

With XML parsing client-side we can also store the data into an `OBJECT` column, benefiting from indexing.

It is also possible (with some limitations) to convert XML to JSON and back
https://stackoverflow.com/questions/48788722/json-to-xml-using-javascript
https://github.com/bramstein/xsltjson/ + https://johannburkard.de/software/xsltjs/

**Comment by mfussenegger** [comment]
Closing this for now as there are no plans to add a XML type.

(This is not a "never" - if there's enough demand/feedback we might reconsider)
