### ISSUE TITLE
`FETCH RELATIVE` behaviour deviates from PostgreSQL 

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13460]
### CrateDB version

5.2.0 -SNAPSHOT-9d4b4bd

### CrateDB setup information

Single node started with `docker run`

### Steps to Reproduce

```
create table testcursor (a int);

insert into testcursor select * from generate_series(1, 10);

FETCH ABSOLUTE 5 FROM order_cursor;

FETCH RELATIVE 5 FROM order_cursor;

FETCH RELATIVE -5 FROM order_cursor;
```

### Expected Result

```
FETCH RELATIVE 5 FROM order_cursor;
```
--> One row with the value 10
```
FETCH RELATIVE -5 FROM order_curso
```
--> One row with the value 5

### Actual Result

```
FETCH RELATIVE 5 FROM order_cursor;
```
-->5 rows with values from 6 to 10
```
FETCH RELATIVE -5 FROM order_curso
```
--> ```SQLParseException[line 1:16: mismatched input '-' expecting {<EOF>, ';'}]```

**Comment by matriv** [comment]
@hlcianfagna Thanks a lot for reporting the issue, the fix has been merged in both `master` and `5.2`.
It would be great to play around and check that everything works ok now.
