### ISSUE TITLE
Support for sorting in `COPY TO`

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13490]
### Problem Statement

A recurrent JSON export is needed with records sorted with a given criteria.

### Possible Solutions

I appreciate this is challenging given the distributed nature of the system, but here are some ideas:
- support `COPY TO` from a view or `SELECT` query like PostgreSQL does from version 9
- support a dedicated `ORDER BY`, or sorting column parameter in `COPY TO`
- support a [FOR JSON](https://learn.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver16) clause in queries to get the output in JSON format

### Considered Alternatives

A custom export script can be used.

Another option could be to use an external ETL tool.

**Comment by mfussenegger** [comment]
Another option would be to use [crash](https://github.com/crate/crash/). It can output the result as json, json_row or csv. For example:

```
↪  crash --hosts localhost:4200 -c "select x from generate_series(1, 10) t(x) order by x desc" --format json_row 2> /dev/null
{"x": 10}
{"x": 9}
{"x": 8}
{"x": 7}
{"x": 6}
{"x": 5}
{"x": 4}
{"x": 3}
{"x": 2}
{"x": 1}
```

But it currently buffers the full result before writing it out

**Comment by mfussenegger** [comment]
@hlcianfagna Is the workaround to go with crash good enough, or do you still think this requires a server side solution?

**Comment by hlcianfagna** [comment]
I am happy with the `crash` workaround, thank you @mfussenegger

**Comment by mfussenegger** [comment]
Thanks. I'm going to close this for now as there are no concrete plans to extend COPY TO. Might re-open this if there's more demand for this
