### ISSUE TITLE
Allow overriding a cluster-wide default allocation setting for specific tables/partitions

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13529]
### Problem Statement

Use case
---------
There is a three-node cluster that is already in operation and contains data. Now, a fourth node should be added later on as a cold node (with a slow disk). Initially and in the future by default, all data should remain on the hot nodes. The nodes are configured with `node.attr.storage=hot/cold`.

Problem
--------
Before adding the cold node, every table needs to be configured with `ALTER TABLE x SET ("routing.allocation.require.storage" = 'hot');` to prevent reallocation to the newly added cold node. Depending on the number of tables, this can be tedious work, and is also error-prone (easy to forget when creating new tables in the future).

As another approach, there is the cluster-wide `cluster.routing.allocation.require.storage` that could be set to `hot` as a default value and then get overridden on a table/partition-level with `ALTER TABLE` for those tables/partitions that should transition to the cold node. But this doesn't work, it's not possible to override the cluster-wide setting:
```sql
-- allocates to hot nodes due to cluster allocation setting
CREATE TABLE t1 (a INTEGER);

-- try to reallocate/override previous allocation
ALTER TABLE t1 SET ("routing.allocation.require.storage" = 'cold');

-- nothing has changed, all shards are still on the hot nodes
SELECT decisions FROM sys.allocations WHERE table_name = 't1'
-- returns for the cold node: node does not match cluster setting [cluster.routing.allocation.require] filters [storage:"hot"]
```

### Possible Solutions

Have a cluster-wide default allocation setting that can be overridden for specific tables/partitions.

ElasticSearch has a `node.roles` implementation: https://www.elastic.co/blog/elasticsearch-data-lifecycle-management-with-data-tiers

**Comment by mfussenegger** [comment]
> ElasticSearch has a node.roles implementation: https://www.elastic.co/blog/elasticsearch-data-lifecycle-management-with-data-tiers

A potential alternative for this would be to add tags to `data.paths` which can be used in a similar way in combination with the allocation includes/excludes.
Opposed to node specific roles it would have the advantage that a single node could have mixed disk types. Making it more flexible while still allowing for the same kind of setup with dedicated slow storage nodes.

**Comment by mkleen** [comment]
We said we'd only allow overriding the cluster setting with a table/index setting. Anything else in regards to storage/node paths is out-of-scope.
