### ISSUE TITLE
Support for case sensitive table names

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13524]
### Problem Statement

NB: this is separate from the existing tickets regarding schema names.

By default, Dataiku names tables combining upper and lower case labels resulting in mixed case names.

On `CREATE TABLE` CrateDB currently (5.3.0 snapshot from 2023/01/25) rejects mixed case names if the names are in quotes.

### Possible Solutions

- Support for case sensitive table names, for instance `CREATE TABLE "Camelcase" (a int);` should create a table called "Camelcase"

**Comment by seut** [comment]
Relates to #12110.

**Comment by jeeminso** [comment]
Addressed by https://github.com/crate/crate/pull/13528, closing.
