### ISSUE TITLE
Support for `_` / underscore in quoted schema identifiers

### ISSUE THREAD

**Issue by proddata** [crate/crate#13578]
### Problem Statement

[Rudderstack](https://www.rudderstack.com/docs/reverse-etl/postgresql/#granting-permissions) is trying to use a schema with `_` underscore

```sql
GRANT ALL ON SCHEMA "_rudderstack" TO RUDDER;
```

Follow up to https://github.com/crate/crate/issues/12110

### Possible Solutions

support underscore in quoted schema identifiers.

e.g.
```sql
CREATE TABLE "_my_schema".my_table (a INT):
```

### Considered Alternatives

n/a (changes in 3rd party tool)

**Comment by matriv** [comment]
Should it also be allowed to prefix with `_` even without double quotes?

**Comment by matriv** [comment]
(Probably not: https://www.postgresql.org/docs/8.1/sql-syntax.html#SQL-SYNTAX-IDENTIFIERS just double checking to be safe)

**Comment by proddata** [comment]
@matriv 

Hm ... sounds according to the docs, it should also be possible

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) **or an underscore (_).**

This part doesn't refer to quoted identifiers, which

> can contain any character other than a double quote itself.

```sql
postgres=# CREATE TABLE _a (a INT);
CREATE TABLE

postgres=# CREATE TABLE "_a" (a INT);
ERROR:  relation "_a" already exists

postgres=# SELECT table_name FROM information_schema.tables where table_schema = 'public' LIMIT 10;
 table_name 
------------
 _a
(1 row)
```


https://www.postgresql.org/docs/15/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
