### ISSUE TITLE
Issue with PostgreSQL Wire Protocol (Binary) with Elixir Postgrex driver.

### ISSUE THREAD

**Issue by cocoaway** [crate/crate#13587]
### CrateDB version

5

### CrateDB setup information

Number of nodes : 1 
Runs as docker container
CRATE_HEAP_SIZE:4g

### Problem description

[Postgrex](https://github.com/elixir-ecto/postgrex) is by far the most used driver with Elixir language to interact with PostgreSQL and main driver for [Ecto](https://github.com/elixir-ecto/ecto) 

Postgrex uses the binary version of the protocol.

CrateDB appears to not properly support queries where Postgrex requests a timestamp.

The error occurs with the driver possibly due to a function name containing spaces.
The driver authors have responded to this [issue](https://github.com/elixir-ecto/postgrex/issues/642) and the bug seems to be CrateDB side.

### Steps to Reproduce

A simple Postgrex query that returns a timestamp is enough to generate the error.

### Actual Result

An error related to Postgrex default types. 

### Expected Result

To be compliant with requests based on PostgreSQL Wire Protocol (Binary) 
[See the open bug](https://github.com/elixir-ecto/postgrex/issues/642) at Postgrex GitHub.

**Comment by proddata** [comment]
Hi @cocoaway 

Thanks for reporting this 🤟 

---

Other than CrateDB not supporting all PG Types yet, there seem to be 2 issues here
- `typsend` includes an underscore `_` in pgsql
- `timestamp` type (i.e. without time zone) is reported as `timestamp` in pgsql, not `timestamp without time zone` (CrateDB)


```sql
postgres=# SELECT typname, typsend FROM pg_type WHERE typname LIKE 'time%';
   typname   |     typsend      
-------------+------------------
 time        | time_send
 time_stamp  | timestamptz_send
 timestamp   | timestamp_send
 timestamptz | timestamptz_send
 timetz      | timetz_send
(5 rows)
```

```
cr> SELECT typname, typsend FROM pg_type WHERE typname LIKE 'time%';                                                                                                                                       
+-----------------------------+---------------------------------+
| typname                     | typsend                         |
+-----------------------------+---------------------------------+
| timestamptz                 | timestamptzsend                 |
| timestamp without time zone | timestamp without time zonesend |
| timetz                      | timetzsend                      |
+-----------------------------+---------------------------------+
SELECT 3 rows in set (0.045 sec)
```

**Comment by matriv** [comment]
@cocoaway Thx for reporting this issue!
It has been fixed and will be available with the next releases.

**Comment by cocoaway** [comment]
Thank you for promptly handling this issue.
I can't wait for the 5.2 docker image to be available.

Luca M.
