### ISSUE TITLE
Port remaining `ConcurrentSnapshotsIT` test cases

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#13613]
`ConcurrentSnapshotsIT` is still missing several test cases from ES v7.10.2

- [ ] testQueuedDeletesWithOverlap
- [ ] testQueuedOperationsOnMasterRestart
- [ ] testQueuedOperationsOnMasterDisconnect
- [x] testQueuedOperationsOnMasterDisconnectAndRepoFailure
- [ ] testQueuedOperationsAndBrokenRepoOnMasterFailOver
- [ ] testQueuedSnapshotOperationsAndBrokenRepoOnMasterFailOver
- [ ] testQueuedSnapshotOperationsAndBrokenRepoOnMasterFailOver2
- [ ] testQueuedSnapshotOperationsAndBrokenRepoOnMasterFailOverMultipleRepos
- [x] testMultipleSnapshotsQueuedAfterDelete
- [x] testQueuedSnapshotsWaitingForShardReady
- [x] testBackToBackQueuedDeletes
- [x] testQueuedOperationsAfterFinalizationFailure
- [x] testStartDeleteDuringFinalizationCleanup
- [x] testEquivalentDeletesAreDeduplicated
- [x] testMasterFailoverOnFinalizationLoop
- [x] testStatusMultipleSnapshotsMultipleRepos
- [x] testInterleavedAcrossMultipleRepos
- [x] testMasterFailoverAndMultipleQueuedUpSnapshotsAcrossTwoRepos
- [x] testConcurrentOperationsLimit

See:

- https://github.com/crate/crate/pull/13478
- https://github.com/crate/crate/pull/13483

**Comment by jeeminso** [comment]
FYI, `testEquivalentDeletesAreDeduplicated` seems flaky
[1_Test CrateDB SQL on ubuntu-latest.txt](https://github.com/crate/crate/files/10882776/1_Test.CrateDB.SQL.on.ubuntu-latest.txt)

**Comment by matriv** [comment]
@jeeminso Thx, I think this: https://github.com/crate/crate/pull/13755 will address the issue.

**Comment by mfussenegger** [comment]
Remaining cases can't easily ported due to missing repositoryData cache. Closing this for now
