### ISSUE TITLE
Update single array value

### ISSUE THREAD

**Issue by karynzv** [crate/crate#13649]
### Problem Statement

The update of a single value/element in an array is not supported.

### Possible Solutions

```
CREATE TABLE arr (arr ARRAY(INT));                                                                                                
INSERT INTO arr VALUES ([1,2,3,4]); 
+-----------------+
| arr             |
+-----------------+
| [1, 2, 3, 4]    |
+-----------------+                                                                                              
UPDATE arr SET arr[1] = 0;
+-----------------+
| arr             |
+-----------------+
| [1, 0, 3, 4]    |
+-----------------+ 
```

### Considered Alternatives

For now, there are two known workarounds, one is using UDF listed [here](https://community.crate.io/t/a-collection-of-useful-user-defined-functions-udfs/773) or using `array_slice` as such:
```
CREATE TABLE a01 (arr ARRAY(INT));                        

INSERT INTO a01 VALUES ([1,2,7,4,5]);  
+-----------------+
| arr             |
+-----------------+
| [1, 2, 7, 4, 5] |
+-----------------+

UPDATE a01 SET arr = arr[1:2] || [3] || arr[4:5];
+-----------------+
| arr             |
+-----------------+
| [1, 2, 3, 4, 5] |
+-----------------+
```

**Comment by BaurzhanSakhariev** [comment]
Hi @karynzv, thanks for creating a feature request!

Documents are immutable in Lucene and thus update is basically delete+insert.  Real in-place update is not possible and this feature can be implemented only as a syntactic sugar for listed workarounds.

However, updating single element of an array is supported in PostgreSQL https://www.postgresql.org/docs/current/arrays.html#ARRAYS-MODIFYING

So it might be implemented for compatibility reasons.
