### ISSUE TITLE
MissingPrivilegeException instead of "Unknown function" when using non-admin user

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13750]
### CrateDB version

5.2.2

### Problem description

Misleading error message

Possibly related with https://github.com/crate/crate/issues/13561

### Steps to Reproduce

```sql
CREATE USER permissionstest WITH (password='pwd123');
GRANT DQL,DML,DDL ON SCHEMA doc TO permissionstest;
```

```bash
crash -U permissionstest
```

```sql
select doc.nonexistingfunction();
```

### Actual Result

`MissingPrivilegeException[Missing privilege for user 'permissionstest']`

### Expected Result

`io.crate.exceptions.UnsupportedFeatureException: Unknown function: doc.nonexistingfunction()`

same as when using the `crate` user

**Comment by jeeminso** [comment]
Thank you @hlcianfagna. I believe https://github.com/crate/crate/pull/13744 should resolve this.
