### ISSUE TITLE
class_cast_exception for sorting text columns

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#13753]
### CrateDB version

4.8.4

### CrateDB setup information

24 data nodes: 16cpu, 128gb ram, 60gb heap
3 master nodes: 8gb heap
2 query nodes: 30gb heap
2 ingest nodes: 30gb heap

### Problem description

When issuing a sort query, I get the following error back. It only appears to happen to columns that are text whereas numeric columns it works fine

### Steps to Reproduce

Table has ~300 columns, but the query looks something like

```
select colA, colB['foo'] as "bar', colB['acme'] as "abc", colB['aaa'] as "bbb".... order by "bar" asc nulls first
```

### Actual Result

This is the error returned

```
NotSerializableExceptionWrapper[class_cast_exception: class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.String(org.apache.lucene.util.BytesRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')]
```

### Expected Result

Query to work

**Comment by mfussenegger** [comment]
Thanks for the report. I believe this was fixed with https://github.com/crate/crate/pull/13235. Could you try with the latest version?

**Comment by bputt-e** [comment]
Will look into upgrading, just not sure if/when that'll occur.

**Comment by bputt-e** [comment]
@mfussenegger  can you backport this to 4.8.4?

**Comment by proddata** [comment]
> @mfussenegger can you backport this to 4.8.4?

We usually backport to older versions only if there is an active subscription to our services. If you have any concerns, please don't hesitate to reach out to me georg (at) crate.io or open a request at https://support.crate.io/. Perhaps we can work together to find a solution.

**Comment by matriv** [comment]
@bputt-e is there any update on this? have you tried upgrading?

**Comment by bputt-e** [comment]
@matriv not yet, plan to upgrade it mid april

**Comment by bputt-e** [comment]
upgrading resolved our issue

**Comment by matriv** [comment]
Thx for letting us now @bputt-e !
