### ISSUE TITLE
inserting data to crate tables from csv file through cascading pipeline 

### ISSUE THREAD

**Issue by pandeyp** [crate/crate#1379]
I am trying to insert JSON tuples to a crate data through cascading. Since crate's HTTP Rest API can be enabled by setting es.api.enabled: true on crate.yml can I use existing EsTap provided in jar of https://github.com/elasticsearch/elasticsearch-hadoop to insert tuples to crate tables as we have been doing with elasticsearch? What would be the required modifications to elasticsearch-hadoop jar?

Any help on this will be much appriciated,

Prasanna.
##

**Comment by benjaminrigaud** [comment]
Converting MySQL csv to json with csv2json.py is really slow. It would be great if we could import CSV directly.

**Comment by dobe** [comment]
you are right, we have this on our backlog already, i will prioritize this a bit higher, but i cannot give you an estimate when this will make it into our sprints. we would also appreciate any contributions.

**Comment by benjaminrigaud** [comment]
I would be happy to contribute :) But I didn't write Java for years.
How one would develop that? Would that be a plugin?

**Comment by theappbanq** [comment]
I would like to work on this, is there any rules to follow for the contributors like code style and etc?

**Comment by dobe** [comment]
that's great! see https://github.com/crate/crate/blob/master/CONTRIBUTING.rst for further information.

**Comment by matriv** [comment]
`COPY FROM` using csv files has been implemented with: https://github.com/crate/crate/pull/6830 and is already available with CrateDB `3.0.0` (currently testing)
