### ISSUE TITLE
Behaviour of `COALESCE` with multiple data types differs from PostgreSQL

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13820]
### CrateDB version

5.2.3

### CrateDB setup information

Single-node standard Docker deployment

### Problem description

According to the [documentation](https://crate.io/docs/crate/reference/en/5.2/general/builtins/scalar-functions.html#coalesce-first-arg-second-arg), `COALESCE` requires all parameters to be of the same data type:
> The coalesce function takes **one or more arguments of the same type** and returns the first non-null value of these. The result will be NULL only if all the arguments [evaluate](https://crate.io/docs/crate/reference/en/5.2/appendices/glossary.html#gloss-evaluation) to NULL.

The documentation doesn't state what happens in case arguments aren't of the same data type, but in PostgreSQL, it fails:
```
psql (15.2 (Ubuntu 15.2-1.pgdg22.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

postgres=# CREATE TABLE tc (a FLOAT, b INTEGER, c BOOLEAN);
CREATE TABLE
postgres=# SELECT c.*, COALESCE(a, b, c)
FROM tc c;
ERROR:  COALESCE types double precision and boolean cannot be matched
LINE 1: SELECT c.*, COALESCE(a, b, c)
                                   ^
```

### Steps to Reproduce

In CrateDB, the same scenario executes successfully, with a cast to `boolean`:
```
cr> CREATE TABLE tc (a FLOAT, b INTEGER, c BOOLEAN);
CREATE OK, 1 row affected  (0.194 sec)
cr> SELECT c.*, COALESCE(a, b, c)
    FROM tc c;
+---+---+---+-------------------------------------------------------+
| a | b | c | coalesce(_cast(a, 'boolean'), _cast(b, 'boolean'), c) |
+---+---+---+-------------------------------------------------------+
+---+---+---+-------------------------------------------------------+
SELECT 0 rows in set (0.024 sec)
cr> SELECT c.*, COALESCE(c, b, a)
    FROM tc c;
+---+---+---+-------------------------------------------------------+
| a | b | c | coalesce(c, _cast(b, 'boolean'), _cast(a, 'boolean')) |
+---+---+---+-------------------------------------------------------+
+---+---+---+-------------------------------------------------------+
SELECT 0 rows in set (0.004 sec)

```

### Actual Result

The `COALESCE` call executes successfully with an implicit type cast. The cast to `boolean` can be surprising, as it's not the documented behavior of requiring all parameters to be of the same type.

### Expected Result

The `COALESCE` call fails, as with PostgreSQL. Or if there is an intentional deviation from PostgreSQL, the type conversion schema is documented accordingly.

**Comment by hammerhead** [comment]
At a second glance, it looks like also in PostgreSQL calling `COALESCE` with different data types is not strictly forbidden. E.g, `COALESCE(FLOAT, INTEGER)` works fine. The main difference in the case above is, that given the specific combination of data types, PostgreSQL throws an error, but CrateDB decides to cast to `BOOLEAN`.

**Comment by matriv** [comment]
I think that we'd need to adjust the documentation, as far as I know we try to do our best to cast instead of directly fail. `COALESCE` should behave similarly to `greatest, `least`, ` x IN (value1, value2, etc.)` or the:
```
CASE expression
     WHEN value THEN result
     [WHEN ...]
     [ELSE result]
END
```
variant,  where the values are of different types.

**Comment by matriv** [comment]
Yeah, and if I remember correctly this was by choice to follow the Java way where even for floating points `0.0` is casted to `false`.

**Comment by matriv** [comment]
@hammerhead Is it fine to keep the behaviour as is and just improve the docs?

**Comment by hammerhead** [comment]
Yes, sounds good!

**Comment by matriv** [comment]
@hammerhead Thx for reporting! docs have been updated.
