### ISSUE TITLE
Support Azure Blob Storage in `COPY TO`/`COPY FROM`

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13852]
### Problem Statement

Users running in an Azure environment cannot easily use Azure Blob Storage as the source/target of data exports from CrateDB when using `COPY TO`/`COPY FROM`. Only `s3` and `file` are supported right now.

### Possible Solutions

Similarly to how Azure Blob Storage is supported already in `CREATE REPOSITORY`, add that as an option for `COPY TO`/`COPY FROM` as well.

### Remarks

- Using async API would be nice, but would require changes to the copy framework
- Support for secret key and SAS tokens for authentication.
- Support for the ability to provide secrets separately from the URI to use parameterised values.
- Support for glob patterns

**Comment by matriv** [comment]
just FYI: There is a workaround with minio: https://medium.com/@jmaitrehenry/add-s3-capabilities-to-azure-blob-storage-using-miniofirst-of-all-why-cant-we-use-azure-api-73a61952294a

**Comment by panyamravi** [comment]
Hi, please support Azure Blob Container as well - as it helps us.

**Comment by seut** [comment]
We may consider using [OpenDAL](https://opendal.apache.org/) for this implementation (and maybe switch other in future to it as well if it works well).

**Comment by BaurzhanSakhariev** [comment]
>Both for file, as well as for s3 we overwrite existing files.

> i.e. I would go with option 2. If we want to add the option to change this behaviour we might want to expose it for all copy to targets separately.

Thanks for checking. 
If in case we need customizing overwrite behaviour, we would depend on https://github.com/apache/opendal/issues/5024

**Comment by BaurzhanSakhariev** [comment]
Feature will be available in 5.9 release.
