### ISSUE TITLE
Merge Limit and Sort operators together into a TopN operator

### ISSUE THREAD

**Issue by mkleen** [crate/crate#13869]
Limit and Sort can be merged together into a TopN operator.

https://github.com/prestodb/presto/commit/a1c30e6985876b09a28c22ad0729881b1744857d

**Comment by seut** [comment]
@mkleen We already use a `OrderedLimitAndOffsetProjection` (exeuction implementation `SortingLimitAndOffsetProjector`) which does limiting and sorting in one operations. What is missing here?

**Comment by mkleen** [comment]
Thanks for the feedback. I wasn't aware we are doing this already. Seems like the logic is embedded into the `Order` Operator itself. I was just looking for some low-hanging fruits from presto.
