### ISSUE TITLE
[pgcompat] `psycopg.errors.InternalError_: Cannot find portal: <name>`

### ISSUE THREAD

**Issue by amotl** [crate/crate#13885]
### CrateDB version

5.2

### CrateDB setup information

Standard Docker install.
```console
docker run --rm -it --publish=4200:4200 --publish=5432:5432 crate:5.2
```

### Problem description

When trying to use server-side cursors with [Psycopg 3](https://www.psycopg.org/psycopg3/docs/), we observed an exception, while the same code apparently works with PostgreSQL.
```python
psycopg.errors.InternalError_: Cannot find portal: foobar
```

### Steps to Reproduce

There is an example program at [example_psycopg_server_cursor.py](https://gist.github.com/amotl/597b3d4fad7b55d3d4524ba3407dfd28). It can be invoked like this, on both CrateDB and PostgreSQL.

```console
# Run CrateDB
docker run --rm -it --publish=4200:4200 --publish=6432:5432 crate

# Run PostgreSQL
docker run --rm -it --publish=5432:5432 --env "POSTGRES_HOST_AUTH_METHOD=trust" postgres:15

# Acquire and invoke demo program
wget https://gist.githubusercontent.com/amotl/597b3d4fad7b55d3d4524ba3407dfd28/raw/example_psycopg_server_cursor.py
pip install psycopg
python example_psycopg_server_cursor.py postgresql
python example_psycopg_server_cursor.py cratedb
```

The patch at https://github.com/crate/crate-qa/pull/250 can also be used to reproduce the problem.

### Actual Result

```python
Traceback (most recent call last):
  File "/path/to/example_psycopg_server_cursor.py", line 117, in <module>
    run_variant(sys.argv[1])
  File "/path/to/example_psycopg_server_cursor.py", line 113, in run_variant
    example.run()
  File "/path/to/example_psycopg_server_cursor.py", line 71, in run
    self.query()
  File "/path/to/example_psycopg_server_cursor.py", line 98, in query
    cur.execute("SELECT * FROM testdrive;")
  File "/path/to/.venv/lib/python3.10/site-packages/psycopg/server_cursor.py", line 295, in execute
    raise ex.with_traceback(None)
psycopg.errors.InternalError_: Cannot find portal: foobar
```
```java
CONTEXT:  io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:162)
io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:151)
io.crate.protocols.postgres.Messages.sendErrorResponse(Messages.java:190)
io.crate.protocols.postgres.PostgresWireProtocol$MessageHandler.channelRead0(PostgresWireProtocol.java:300)
io.crate.protocols.postgres.PostgresWireProtocol$MessageHandler.channelRead0(PostgresWireProtocol.java:277)
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
```

### Expected Result

No exception should happen, and the example program should work.

### References
- https://github.com/crate/crate-qa/pull/250

**Comment by proddata** [comment]
Probably related to https://github.com/crate/crate/issues/13857 as `server_cursor.py` queries that very table

**Comment by mfussenegger** [comment]
Merging this into https://github.com/crate/crate/issues/13857

**Comment by matriv** [comment]
I had a quick look into this, I didn't see any query to `pg_cursors`, instead I saw asking for portal named `"foobar"` (same name as the CURSOR declared), and it fails after the DECLARE CURSOR statement. Could you please check it as well @mfussenegger ?

**Comment by mfussenegger** [comment]
Thanks for mentioning. I had another quick look and it really is a separate issue.

The client sends BEGIN as statement, followed by `DECLARE` and then tries to use the `describe` message on a portal named `foo`.
Currently in CrateDB portals and cursors are separate, it appears as if the client expects them to be the same thing?

```
method=describe type=P portalOrStatement=
method=execute portalName= maxRows=0
method=parse stmtName= query=BEGIN paramTypes=[]
method=bind portalName= statementName= params=[]
method=describe type=P portalOrStatement=
method=execute portalName= maxRows=0
method=sync deferredExecutions=0
method=parse stmtName= query=DECLARE "foo" CURSOR FOR select 1 paramTypes=[]
method=bind portalName= statementName= params=[]
method=describe type=P portalOrStatement=
method=execute portalName= maxRows=0
method=describe type=P portalOrStatement=foo
```


(And smaller reproduction:)

```python
import psycopg # pip install psycopg
conn = psycopg.connect("host=localhost port=5432 user=crate")
cur = conn.cursor(name="foo")
cur.execute("select 1")
```

**Comment by proddata** [comment]
> Currently in CrateDB portals and cursors are separate, it appears as if the client expects them to be the same thing?

From my understanding of the documentation both protocol-level and explicitly created cursors would use portals in PostgreSQL.

> https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
> _Named portals can also be created and accessed at the SQL command level, using DECLARE CURSOR and FETCH._

**Comment by mfussenegger** [comment]
> Named portals can also be created and accessed at the SQL command level, using DECLARE CURSOR and FETCH.

Thanks for pointing this out. There is a pending fix now to allow protocol level access to cursors created via statements (https://github.com/crate/crate/pull/13916), but this would imply we'd also need to support the other way around. - Statement access to protocol level created cursors. 

Something to follow up on.

**Comment by amotl** [comment]
Thank you very much for addressing this issue so quickly. 💯
