### ISSUE TITLE
NullPointerException when using `NOT LIKE` with `OBJECT` casted to `TEXT`

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13936]
### CrateDB version

5.2.5

### CrateDB setup information

Single node

### Problem description

When manually querying rows with complex objects with flexible schemas and nested columns sometimes is easier to cast the object to a string and use `LIKE`
`LIKE` seems to work fine but `NOT LIKE` triggers a `NullPointerException`

### Steps to Reproduce

```sql
CREATE TABLE mytbl (myobj OBJECT(DYNAMIC));

--> inserting data is optional to reproduce the error - same error with an empty table and with different kinds of data

SELECT myobj FROM mytbl WHERE (myobj::TEXT) LIKE '%value1%';
--> this works

SELECT myobj FROM mytbl WHERE (myobj::TEXT) NOT LIKE '%value1%';
```

### Actual Result

```
NullPointerException[Query must not be null]
```

### Expected Result

0 rows if testing with an empty table

**Comment by hlcianfagna** [comment]
Tested with `crate/crate:nightly-5.4.0-20230405` and got the same error message.

**Comment by matriv** [comment]
Thx for reporting this issue @hlcianfagna ! The fix will be available with the next hotfix release.
