### ISSUE TITLE
Basic Cross-join Elimination

### ISSUE THREAD

**Issue by mkleen** [crate/crate#13948]
### Problem statement:

When tables are joined without join conditions the result is a cross-join. In general, a cross-join is almost never desired because the multiplied rows are expensive to calculate and usually later filtered out anyway.

Take the following query:

```
SELECT * FROM a, b, c WHERE a.x = c.x AND c.x = b.x;
```

The join order of the query is `a`, `b`, `c`. Therefore table `a` will be joined with table `b` without a join condition which results in a cross-join. Fortunately the table order of the query can be adapted to eliminate the cross-join:
```
SELECT * FROM a, c, b WHERE a.x = c.x AND c.x = b.x; 
```

Now the order is `a`, `c`, `b`  and both joins are inner joins.

### Approach:

Building a join-graph with the following structure:

- Nodes are relations which are joined together
- Edges are equi-join conditions between relations

```
SELECT * FROM a, b, c WHERE a.x = c.x AND c.x = b.x;
```

becomes:

```mermaid
flowchart LR
   A-- a.x = c.x --- C
   C-- c.x = b.x --- B
```

Cross-joins are now eliminated because there won't be an edge between nodes when there is no equi-join. We just need to traverse the graph now to retrieve the new order. Any graph traversal algorithm could be used here. 

Based on https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/EliminateCrossJoins.java

**Comment by mkleen** [comment]
With the current re-ordering logic of join pairs, this does not add any benefit.

**Comment by mkleen** [comment]
Reopen it for discussion.

**Comment by matriv** [comment]
I think it would be nice to at least extract the existing optimization into a rule.

**Comment by mfussenegger** [comment]
This is done with https://github.com/crate/crate/pull/14685, right?

**Comment by mkleen** [comment]
> This is done with #14685, right?

Yes it is.
