### ISSUE TITLE
bin/crate CLI parsing

### ISSUE THREAD

**Issue by l7s** [crate/crate#13973]
### CrateDB version

5.3.0

### CrateDB setup information

none

### Problem description

It seems on Linux (Debian 11 in my case) parsing of CLI parameters in `bin/crate` is broken. Trying to pass any of the parameters described here [1] results in error `Error parsing arguments!`

[1] https://crate.io/docs/crate/reference/en/5.3/cli-tools.html#synopsis

### Steps to Reproduce

1. Download crate-5.3.0.tar.gz
2. `tar xvf crate-5.3.0.tar.gz`
3. `cd crate-5.3.0`
4. `bin/crate -h`

### Actual Result

```
No arg for -h option
Error parsing arguments!
```

### Expected Result

Usage information is printed in the console.

**Comment by mfussenegger** [comment]
Thanks for reporting. We've got a fix for the next hotfix releases (https://github.com/crate/crate/pull/13984)

**Comment by l7s** [comment]
Although `-h` is working as expected now, command `./bin/crate -d -p /tmp/crate.pid` which I would expect to start crate as a daemon and write PID file to `/tmp/crate.pid` results in error:

```
Illegal option -d
Error parsing arguments!
```

**Comment by proddata** [comment]
> Although `-h` is working as expected now, command `./bin/crate -d -p /tmp/crate.pid` which I would expect to start crate as a daemon and write PID file to `/tmp/crate.pid` results in error:
> 

Those options were removed with 5.3
https://github.com/crate/crate/pull/13269

**Comment by l7s** [comment]
So there is no way to make `crate` write it's PID to a file now? Crate.io docs give examples such as `kill -TERM `cat crate.pid`
` which in fact are now obsolete?

**Comment by mfussenegger** [comment]
> So there is no way to make `crate` write it's PID to a file now? Crate.io docs give examples such as `kill -TERM `cat crate.pid` ` which in fact are now obsolete?

You could use something like `bin/crate & echo $! > "/tmp/crate.pid"` 

Can you point us to the doc examples so we can update them?
