### ISSUE TITLE
Misleading error message when inserting `OBJECT`s and auto-casting fails

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13989]
### Problem Statement

Given a table with a `REAL` column inside an `OBJECT`:
```sql
CREATE TABLE a (b OBJECT(DYNAMIC) AS (c REAL));
```

Trying to insert a `BOOLEAN` fails:
```python
from crate import client

connection = client.connect(["http://localhost:4200"])

cursor = connection.cursor()
cursor.execute("INSERT INTO a VALUES (?)", [({"c": True},)])
```

The failure itself is ok, but the error message is this one:
```
crate.client.exceptions.ProgrammingError: SQLParseException[Cannot cast value `[{c=true}]` to type `object`]
```

We were debugging a more complex real-world case, where this error message was hard to understand for the following reasons:
1. It doesn't describe the actual reason. `{c=true}` itself is a valid object, so `Cannot cast to type object` put us onto the wrong track that something was wrong with the object itself (in our case, the object was much more complex).
2. It doesn't name the target column on which the error occurred. One cannot clearly identify the offending column if there are several `OBJECT` columns with identical/similar subcolumns.
3. If the `OBJECT` value has a large number of attributes, it is not clear for which of the attributes the casting failed

### Possible Solutions

Depending on what is technically possible, change the error message, so that it says something in the direction of:
```
Cannot cast value `true` to type `real` for column b['c']
```

**Comment by matriv** [comment]
Thx a lot for reporting this issue, it has been fixed and will be available with the next hotfix release(s)
