### ISSUE TITLE
Unclear behaviour of `INDEX OFF` for partition keys

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13998]
### CrateDB version

5.3.0

### CrateDB setup information

single node

### Problem description

When specifying `INDEX OFF` on a column that is also used as a partition key, `SHOW CREATE TABLE` doesn't show the `INDEX OFF` for that column.

### Steps to Reproduce

```sql
-- INDEX OFF on both columns
CREATE TABLE a (
  t TIMESTAMP INDEX OFF,
  t_day TIMESTAMP GENERATED ALWAYS AS DATE_TRUNC('day', t) INDEX OFF
)
PARTITIONED BY (t_day);

SHOW CREATE TABLE a;
```
Returns:
```sql
CREATE TABLE IF NOT EXISTS "doc"."a" (
   "t" TIMESTAMP WITHOUT TIME ZONE INDEX OFF,
   "t_day" TIMESTAMP WITHOUT TIME ZONE GENERATED ALWAYS AS _cast(date_trunc('day', "t"), 'timestamp without time zone')
)
CLUSTERED INTO 4 SHARDS
PARTITIONED BY ("t_day")
WITH ([...]) 
```

### Actual Result

See above, a table with no more `INDEX OFF` on the column `t_day`.

### Expected Result

Not sure if it is a bug with `SHOW CREATE TABLE`, or if indexing must be enabled for partition keys.

However, there are no hints in [Partitioned tables](https://crate.io/docs/crate/reference/en/5.3/general/ddl/partitioned-tables.html), [Generated columns](https://crate.io/docs/crate/reference/en/5.3/general/ddl/generated-columns.html), or [CREATE TABLE](https://crate.io/docs/crate/reference/en/5.3/sql/statements/create-table.html#partitioned-by) about a requirement on indexing if a column is used for partitioning (and no primary key is defined).

**Comment by mfussenegger** [comment]
PARTITION BY columns are not stored with the documents and there is never an index for them. Their value is part of the partition ident.

`INDEX OFF` doesn't apply to them because of that.

**Comment by matriv** [comment]
Thx a lot for reporting this @hammerhead ! Docs have been updated.
