### ISSUE TITLE
Not all session parameters can be configured in JDBC connections

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14008]
### CrateDB version

5.3.0

### Problem description

The [PostgreSQL JDBC driver documentation](https://jdbc.postgresql.org/documentation/use/#connection-parameters) specifies that connection parameters can be specified like this:

```java
Properties props = new Properties();
props.setProperty("options", "-c search_path=test,public,pg_catalog -c statement_timeout=90000");
Connection conn = DriverManager.getConnection(url, props);
```

When connecting to CrateDB and attempting to change any of the [session parameters](https://crate.io/docs/crate/reference/en/5.3/config/session.html), it appears only to be possible to configure `search_path` in the way described above. For any other session parameter, the connection property is ignored.

Relates to a community issue: https://community.crate.io/t/error-on-unknown-object-key-setting-specifics/1460

### Steps to Reproduce

```java
import java.sql.*;
import java.util.Properties;

public class App {
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:postgresql://localhost/crate?user=u1&password=u1&ssl=false";
        Properties props = new Properties();

        props.setProperty("options", "-c error_on_unknown_object_key=false");
        Connection conn = DriverManager.getConnection(url, props);

        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SHOW error_on_unknown_object_key");
        rs.next();
        System.out.println(rs.getBoolean("setting"));
    }
}
```

Changing `search_path` in the same way works fine, though.

### Actual Result

Prints `true`.

### Expected Result

All session parameters are changeable, so the output is `false`.

**Comment by mfussenegger** [comment]
Thanks for pointing out. This will be supported with https://github.com/crate/crate/pull/14025 in the next feature release.
