### ISSUE TITLE
Add attgenerated to pg_attribute

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14036]
### Problem Statement

As the emulated PostgreSQL version is now reported to be 14 instead of 11 Metabase expects attgenerated in pg_attribute

### Possible Solutions

Implement the column as in https://www.postgresql.org/docs/current/catalog-pg-attribute.html

### Considered Alternatives

Shadow the version function to report a lower PostgreSQL version

**Comment by matriv** [comment]
Keep in mind that PostgreSQL has `s` for the generated cols because they are stored, while for CrateDB they're "virtual", so I'm not sure how to treat this, should we use `' '` or `'s'` ?

**Comment by proddata** [comment]
> Keep in mind that PostgreSQL has `s` for the generated cols because they are stored, while for CrateDB they're "virtual", so I'm not sure how to treat this, should we use `' '` or `'s'` ?

Generated columns are always stored in CrateDB

**Comment by matriv** [comment]
:man_facepalming: thx!

**Comment by matriv** [comment]
@hlcianfagna Thx a lot for reporting this, the column has been added to master.
