### ISSUE TITLE
Cherry-Pick Postgres Wire Protocol update so Django works again

### ISSUE THREAD

**Issue by robd003** [crate/crate#14047]
### CrateDB version

5.3.1

### CrateDB setup information

Any crate cluster

### Problem description

Django fails to connect to the current release of Crate.

```
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.0).
```

### Steps to Reproduce

Start Crate, add Crate DB URI to Django settings, try to start Django.

### Actual Result

```
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.0).
```

### Expected Result

Pull request was already merged to master, but wasn't cherry-picked into the 5.3 branch.

If we can cherry-pick this commit into 5.3 then we won't have deprecation issues with clients: https://github.com/crate/crate/commit/5b6458b20779a1429fa5724c447bbb9b779298e9

**Comment by robd003** [comment]
Hey @mfussenegger could we push this in the release of Crate 5.3.2?

**Comment by mfussenegger** [comment]
We had some other clients break because they now also expect new columns on pg_catalog tables. See https://github.com/crate/crate/pull/13959 & https://github.com/crate/crate/pull/14039

Because of that I'd rather not backport the change. Is it possible for you to stay on a Django version that still supports PostgreSQL 11.0?

**Comment by robd003** [comment]
Ah, I saw them merged to master and figured they'd be part of the 5.3.x release

Any timeline for when 5.4 will be out?

**Comment by BaurzhanSakhariev** [comment]
> Any timeline for when 5.4 will be out?

Roughly end of June (there will be feature freeze mid June)

**Comment by robd003** [comment]
Awesome, thanks @BaurzhanSakhariev

I'll try to get Django added to the crate-qa repository over the weekend. (Long overdue, I know...)

**Comment by matriv** [comment]
@robd003 I'm closing this since it's planned to be released. Feel free to re-open if you encounter problems with upcoming CrateDB `5.4`.
