### ISSUE TITLE
Automated Snapshots

### ISSUE THREAD

**Issue by robd003** [crate/crate#14042]
### Problem Statement

Ideally I could set up a snapshot schedule within CrateDB so that every night a backup would occur

### Possible Solutions

https://github.com/quartz-scheduler/quartz

### Considered Alternatives

Currently looking at running a Kubernetes Cronjob to start a container with `crash` to run `CREATE SNAPSHOT backups.${date +%F} ALL WITH (wait_for_completion=true);`

**Comment by proddata** [comment]
Automatic snapshot management is part of [CrateDB Cloud](https://console.cratedb.cloud/) and [CrateDB Edge (for Kubernetes)](https://crate.io/docs/cloud/tutorials/en/latest/edge/index.html) already. There are currently no plans to integrate this into CrateDB itself.
