### ISSUE TITLE
Apache Arrow Flight SQL protocol to speed up huge data exchange for analytical purpose

### ISSUE THREAD

**Issue by igor-suhorukov** [crate/crate#14040]
### Problem Statement

CrateDB support only PostgreSQL wire protocol support now to leverage existing infrastructure and drivers.
Please consider support of [Apache Arrow Flight SQL](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/) endpoint. It allows you make one step ahead in analytical use case and easy integration with ML framework and [cuDF](https://github.com/rapidsai/cudf) based on Apache Arrow in memory columnar format.

There are existing client side open source [JDBC](https://github.com/apache/arrow/tree/main/java/flight/flight-sql-jdbc-core) and [ODBC](https://docs.dremio.com/software/drivers/arrow-flight-sql-odbc-driver/) drivers for Apache Arrow Flight SQL server.

**Comment by mfussenegger** [comment]
Sounds interesting but there are currently no plans to add support for another protocol.
