### ISSUE TITLE
Implement substring(string from pattern)

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14061]
### Problem Statement

CrateDB does not currently have the
substring(string from pattern)
scalar function from PostgreSQL
Metabase uses this in some cases

### Possible Solutions

Implementing it as defined in https://www.postgresql.org/docs/9.1/functions-string.html

### Considered Alternatives

The UDF below, **but this requires the tool to pass `string,pattern` instead of `string FROM pattern`**

```sql
CREATE FUNCTION substring(TEXT,TEXT) 
RETURNS TEXT
LANGUAGE JAVASCRIPT
AS 'function substring(string, pattern) {
    const regex = new RegExp(pattern);
    const match = string.match(regex);
    return match ? match[0] : null;}';
```

**Comment by mfussenegger** [comment]
We added the `substring(string from pattern)` variant with https://github.com/crate/crate/pull/14609.

The `substring(string from pattern for escape)` variant is still missing. Is that also used by Metabase?
