### ISSUE TITLE
interval_format

### ISSUE THREAD

**Issue by robd003** [crate/crate#14075]
### Problem Statement

It would be really nice to have a way to pretty print an interval time just like with date_format

### Possible Solutions

Example: column contains 828019000

SELECT interval_format(interval_col) from data;

Returns: "1 week 2 days 14 hours and 19 seconds"

### Considered Alternatives

Attempted to use pg_catalog.age() but it only wants to accept timestamps not intervals

**Comment by matriv** [comment]
Can you please explain a bit more what exactly are you looking for?
INTERVAL is not a stored type, you cannot define a table column with INTERVAL data type:
```
cr> CREATE TABLE t(a interval);                                                                                                                                                                                                  
SQLParseException[Cannot use the type `interval` for column: a]
```
The output of the interval for crash is this:
```
cr> SELECT now() - '2023-01-01 00:00:00'::timestamp;                                                                                                                                                                             
+-----------------------------------------------------------------------+
| (_cast(now(), 'timestamp without time zone') - 1672531200000::bigint) |
+-----------------------------------------------------------------------+
| 4 mons 6 days 07:20:43.376                                            |
+-----------------------------------------------------------------------+
SELECT 1 row in set (0.020 sec)
```

**Comment by robd003** [comment]
@matriv I have a lot of durations stored as integers and I wanted an easy way to format them so I didn't have to do it in the client side application.

**Comment by matriv** [comment]
Got it, thanks! So you want a function that converts milliseconds into intervals.
Would a simple `CAST(int_col AS INTERVAL)` (or `int_col::interval``) be enough?

**Comment by mfussenegger** [comment]
Isn't this [to_char(interval, text)](https://crate.io/docs/crate/reference/en/5.3/general/builtins/scalar-functions.html#to-char-expression-format-string) ?

**Comment by matriv** [comment]
As I understand, @robd003, wants mainly to convert long (millis) to interval, so the `to_char()` won't work as expected for such a case:
```
cr> select to_char(101234, 'YYYY MM DD HH12:MI:SS.FF3') as interval;                                                                                                                                                             
+-------------------------+
| interval                |
+-------------------------+
| 1970 01 01 00:01:41.234 |
+-------------------------+
SELECT 1 row in set (0.002 sec)
```

**Comment by mfussenegger** [comment]
Closing this given it has a somewhat reasonable solution:

```sql
select to_char((x || ' minutes')::interval, 'YYYY MM DD HH12:MI:SS') from tbl
```

To make the integer -> interval conversion easier, we could look into adding `make_interval` like in PostgreSQL:

```
make_interval ( [ years int [, months int [, weeks int [, days int [, hours int [, mins int [, secs double precision ]]]]]]] ) → interval
```

But that could go into a new issue.
