### ISSUE TITLE
DROP TABLE IF EXISTS failing when using FQNs with non admin user

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14070]
### CrateDB version

5.3.1 and crate/crate:nightly-5.4.0-20230503

### CrateDB setup information

Single node

### Problem description

When using dbt it is reasonable to configure it to use a dedicated user, not the crate superuser
When building models it routinely attempts `DROP TABLE IF EXISTS`
It refers to tables by FQN, which in theory should work following https://github.com/crate/crate/pull/12816 
but it fails with `Invalid index name`

### Steps to Reproduce

```sql
--as user=crate
DROP TABLE IF EXISTS "doc"."does_not_exist";
--> DROP OK, 0 rows affected  (0.001 sec)
--> NB *0* rows
DROP TABLE IF EXISTS "crate"."doc"."does_not_exist";
--> DROP OK, 1 row affected  (0.060 sec)
--> NB *1* row

create user user1 with (password='pwd123');
GRANT DQL,DDL,DML TO user1;
```
```bash
crash -U user1
```
```sql
DROP TABLE IF EXISTS "doc"."does_not_exist";
--> DROP OK, 0 rows affected  (0.001 sec)
DROP TABLE IF EXISTS "crate"."doc"."does_not_exist";
--> SQLParseException[Invalid index name: crate.doc.does_not_exist]
```

### Actual Result

```
SQLParseException[Invalid index name: crate.doc.does_not_exist]
```

### Expected Result

```
DROP OK, 0 rows affected  (0.000 sec)
```
or
```
DROP OK, 1 row affected  (0.060 sec)
```

**Comment by matriv** [comment]
@hlcianfagna thx for reporting, FYI it's also wrong for `crate` admin user, it returns `1` row affected, and it logs an error in the server logs.

**Comment by matriv** [comment]
The fix has been merged and will be available with the next hotfix release.
Once again, thanks @hlcianfagna for reporting.
