### ISSUE TITLE
Allow certain users (other than the crate superuser) to see queries from other users in sys.jobs and sys.jobs_log

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14126]
### Problem Statement

In a large organisation there may be multiple admins.
Some of these admins may not have access to connect as `crate` or security policies may mandate that they use nominative accounts for all admin tasks and operations involving the access to sensitive data.
At the same time the environment may be complex and connecting with multiple application accounts to query `sys.jobs_log` with each of them to find out which account is running what may not be practical or feasible.
It may also be desired to have a monitoring system with access to the queries being run without permissions to perform any DDL or DML itself.

### Possible Solutions

* Allow this for users with `ALL PRIVILEGES` or with `AL`
* introduce a new dedicated privilege
* introduce a system view that could be queried to see who is/was connected alongside a TVF for jobs/jobs_log accepting credentials or some kind of token as parameter

### Considered Alternatives

* Have an ETL job running as crate polling `sys.jobs_log` to a location where permissions can be granted as needed
* Use `stats.jobs_log_persistent_filter` and a SIEM

**Comment by hlcianfagna** [comment]
Confirmed that the "Administration Language" (`AL`) privilege is also not sufficient to see queries from other users.

**Comment by proddata** [comment]
relates to https://github.com/crate/crate/issues/11420

**Comment by seut** [comment]
We plan to support this by allowing this for users with  `AL` privilege.
We may followup to check if it's feasible to assign privileges on individual system tables without giving full `AL` privileges.

**Comment by proddata** [comment]
Giving direct access to all others users logs could potentially leak information, e.g. when statements are not run using prepared statements / parameter substitution.

**Alternative 1**
An alternative might be to allow the superuser `crate` to create a `VIEW` like:

```sql
CREATE VIEW my_jobs AS
SELECT * FROM sys.jobs
WHERE username NOT IN ('crate','system')
```

By default in PostgreSQL the view would be run with the owners permission:

> https://www.postgresql.org/docs/current/sql-createview.html
> By default, access to the underlying base relations referenced in the view is determined by the permissions of the view owner. In some cases, this can be used to provide secure but restricted access to the underlying tables. 

---

**Advantage**:
- No direct change in the user permissions.

**Disadvantage**: 
- Admin UI would still just show the metrics based on the actual users permissions


---

**Alternative 2**
All `AL` users can see all non-superusers stmts / logs. This would still allow to run stmts in a safe manner directly on the cluster using the superuser and show all metrics in the Admin UI with the actual cluster load.
