### ISSUE TITLE
Sample errors for COPY FROM RETURN SUMMARY

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#14133]
### Problem Statement

If you try to import a large file and get the settings wrong - e.g. not setting the right delimiter for CSV - you'll currently get an error per row. At a certain file size, the amount of errors will be so large that you'll always run into a circuit breaker exception.

In 4.x this apparently worked differently and it short-circuited: https://github.com/crate/crate/issues/14287

### Possible Solutions

Sample the errors so you'll get at most 100 or so?

**Comment by hlcianfagna** [comment]
> Sample the errors so you'll get at most 100 or so?
Or stop the import after a certain number of errors maybe?

**Comment by erik777** [comment]
I was very happy with v4 behavior for importing, which seemed to list the top errors.  You nail those.  Re-run.  Then you see more.  Repeat until your import is 100% successful.  No matter what, it tells you the total success and total error count, even when it doesn't list all errors.  If you can just return v4 behavior, that would be great.

**Comment by proddata** [comment]
Should `fail_fast` set to `true` by default?
https://crate.io/docs/crate/reference/en/5.3/sql/statements/copy-from.html#id22
