### ISSUE TITLE
Cannot match ? with ILIKE only works with LIKE

### ISSUE THREAD

**Issue by robd003** [crate/crate#14167]
### CrateDB version

5.3.1

### CrateDB setup information

Any cluster

### Problem description

If trying to match content in a field with `ILIKE` and including a ? in the match it will fail. Only works with `LIKE`

### Steps to Reproduce

SELECT field1 FROM something.table WHERE field1 ILIKE '%\?thing%'

### Actual Result

Returns all rows instead of matching

### Expected Result

Return only rows that match the substring '?thing' in a case insensitive manner.

**Comment by matriv** [comment]
`?` is not the correct wildcard to match a single character, you want to use: `_`, please check: https://crate.io/docs/crate/reference/en/5.3/general/dql/selects.html#like-ilike for more info.

example:
```
cr> select * from t1;                                                                                                                                                                                                                
+---------+
| s       |
+---------+
| Marios  |
| Andreas |
+---------+
SELECT 2 rows in set (0.003 sec)
cr> select * from t1 WHERE s LIKE '_ario_';                                                                                                                                                                                          
+--------+
| s      |
+--------+
| Marios |
+--------+
SELECT 1 row in set (0.004 sec)
cr> select * from t1 WHERE s LIKE '_ARIO_';                                                                                                                                                                                          
+---+
| s |
+---+
+---+
SELECT 0 rows in set (0.004 sec)
cr> select * from t1 WHERE s ILIKE '_ARIO_';                                                                                                                                                                                         
+--------+
| s      |
+--------+
| Marios |
+--------+
SELECT 1 row in set (0.003 sec)
```

**Comment by matriv** [comment]
Apologies, if I didn't understand the issue correctly, please re-open if so.

**Comment by robd003** [comment]
I'm not trying to use ? as a wildcard. I'm trying to match a query string.

Please re-open the issue.

**Comment by matriv** [comment]
Sure.
Can you please give more info though on the string that you've expected to match?

**Comment by robd003** [comment]
No problem.

```SELECT href from some.table WHERE href LIKE '%\?%'``` will return valid rows that match '?' being included in the row

```SELECT href from some.table WHERE href ILIKE '%\?%'``` will return all rows without the match happening.

I'm using ILIKE because I'm searching for a case insensitive string after the ? character, but the above should reproduce the bug.

**Comment by matriv** [comment]
@robd003 Thx a lot for reporting the issue and the additional info, apologies for the initial misunderstanding, the issue has been fixed and will be available with the next hotfix release.
