### ISSUE TITLE
`CREATE REPOSITORY`: Compatibility with Oracle Cloud S3

### ISSUE THREAD

**Issue by amotl** [crate/crate#14177]
### Problem Statement

CrateDB currently might only support virtual host-style access to S3 buckets. Unfortunately, this style does not work for Oracle Cloud S3, because they do not auto-provision SSL certificates for this endpoint, but recommend to use path-based access instead.

This request originated from the report by `@iames` at [Snapshot repository certificate error with Oracle Cloud S3](https://community.crate.io/t/snapshot-repository-certificate-error-with-oracle-cloud-s3/1461). Thank you very much!

### Possible Solutions

I think it would be nice to obtain the S3 bucket address per URL, instead of using separate `base_path` and `bucket` arguments.

### See also
- GH-13879

**Comment by BaurzhanSakhariev** [comment]
A setting allowing to force the use of the path style access pattern 
has been implemented in https://github.com/crate/crate/pull/15222 by @meteoiker, thanks a lot!

According to Iker, using this setting makes it possible to `CREATE REPOSITORY` with Oracle Cloud S3
https://community.cratedb.com/t/snapshot-repository-certificate-error-with-oracle-cloud-s3/1461/8
