### ISSUE TITLE
camel notation for fields

### ISSUE THREAD

**Issue by lrondanini** [crate/crate#1421]
Hello,

not sure this is a bug but I cannot seem to be able to query fields when in camel notation.

For example, if I have a field named "name" and a field named "lastName" and I run a simple
SELECT name, lastName FROM users

the query works but I dont get any result for the field "lastName" (is empty). But, if I run a 
SELECT \* FROM users

all the fields seem correctly populated but the "lastName" field has 2 instances, one with the correct name (with the aspected value) and another one all lower case (empty).

I don't understand if it's a mistake on my side or a problem related to the analyzer used to store field names in ES.

I can provide full code example if needed.

Thanks,
Luca

**Comment by RVN-BR** [comment]
I'm understanding that Crate is narmalizing fieldnames to lowercase when selecting?  Is there any doc that explains this?  Our MySQL has camel case tables and other mixed case tables and column names.  After importing I noticed that my crate table had double the fields, 1 set with all lowercase, and no data...

I'm now reimporting with all lowercase names to see if that works better...

**Comment by chaudum** [comment]
example: https://github.com/crate/crate/issues/2078#issuecomment-105943869
