### ISSUE TITLE
Nested array storage supported/not-supported depending on statement.

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#14251]
### CrateDB version

5.3

### Problem description

Regression from 5.2. Looks like nested array is possible to store in a concrete way (insert from values) but is nt possible in some other ways.

### Steps to Reproduce

`create table t(a int) with (column_policy='dynamic')  `

**looks like insert from values can store nested arrays in 5.3**

```
insert into t(a, nest_arr) values (1, [[1,2,3]]);                                                                                                                                                                  
INSERT OK, 1 row affected  (0.246 sec)

cr> select * from t;                                                                                                                                                                                                    
+---+-------------+
| a | nest_arr    |
+---+-------------+
| 1 | [[1, 2, 3]] |
```

**insert from sub-query cannot store nested array in 5.3** 
(but with different error message than 5.2 so it could be also improved)

```
insert into t(a, nest_arr) (select 1, [[1,2,3]] from sys.cluster);                                                                                                                                                  
SQLParseException[The type 'integer_array_array' of the insert source '[[1, 2, 3]]' is not convertible to the type 'bigint_array' of target column 'nest_arr']
```

### Actual Result

by docs nested arrays storage is not supported.
https://crate.io/docs/crate/reference/en/5.3/general/ddl/data-types.html#nested-arrays

>Nested arrays cannot be used directly in column definitions (i.e. ARRAY(ARRAY(DOUBLE)) is not accepted), 

but there is at least one way to achieve that.

### Expected Result

Either 
1.  really support nested array storage (insert from subquery should not fail) and update docs
2. make insert from values fail. And maybe improve error message for insert-from-subquery as well.

if go with 2, then this is behavior on 5.2:

```
cr> create table t(a int) with (column_policy='dynamic');                                                                                                                                                               
CREATE OK, 1 row affected  (1.606 sec)
cr> insert into t(a, nest_arr) values (1, [[1,2,3]]);                                                                                                                                                                   
ElasticsearchParseException[nested arrays are not supported]
cr> insert into t(a, nest_arr) (select 1, [[1,2,3]] from sys.cluster);                                                                                                                                                  
INSERT OK, 0 rows affected  (0.016 sec)
cr> select * from t;                                                                                                                                                                                                    
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.030 sec)
```

**Comment by mfussenegger** [comment]
Fixed with https://github.com/crate/crate/pull/14324 and also created a issue to add support: https://github.com/crate/crate/issues/14328
