### ISSUE TITLE
heap and parser errors on import

### ISSUE THREAD

**Issue by erik777** [crate/crate#14287]
### CrateDB version

5.3

### CrateDB setup information

docker

### Problem description

When trying to import a 2.6G file in v5.3, with heap set as high as 3g, it would run OutOfMemoryError. Up to 6g, and it failed on a circuit breaker. Yet, I can import the same vile in v 4.5.4 with only 500m heap.

Discovered the issue was that when you have a parse error, it just gobs up memory like crazy in v5. With v4, it correctly ends with a parser error with RETURN SUMMARY, even with only 500g heap. When I fixed the parser error, I was able to import with 1g heap with v5, and successfully with v4 with 500m heap. I did not try lower than 1g with v5.

### Steps to Reproduce

Create JSON.  leave out the end quote on an attribute (this resulted from an incorrect SED).  Create a ton of rows until you have a very large file to import.  Alternatively, if you have a large file you can import, just use SED to get rid of a closing quote on a property name.  

### Actual Result

In description.  Sorry, didn't capture the exact error when I had a parser error.  Just reporting so you can get v5 as good as v4.  

### Expected Result

no OOM or circuit breaker.  a good summary of the number of rows with a parser error.  My import had 3594282 errors when it failed, and 3594282 successes when it worked.

**Comment by mfussenegger** [comment]
Thanks for the report. We have an issue about this already https://github.com/crate/crate/issues/14133
