### ISSUE TITLE
Generated Columns using deterministic functions are not validated on inserts to partitioned tables

### ISSUE THREAD

**Issue by proddata** [crate/crate#14304]
### CrateDB version

5.3.2

### Steps to Reproduce

```sql
CREATE TABLE validation (ts TIMESTAMP, ts_y GENERATED ALWAYS AS date_trunc('year',ts)) PARTITIONED BY (ts_y)
INSERT INTO validation (ts,ts_y) SELECT null, now();
SELECT * FROM validation;
ts | ts_y
-- | --
NULL | 1687438607180 (2023-06-22T12:56:47.180Z)

```

It works as expected on non-partitioned tables

### Actual Result

```
INSERT OK, 1 record affected (0.423 seconds)
```

### Expected Result

Exception or rejected records
```
INSERT OK, 0 records affected (0.007 seconds)
```

**Comment by BaurzhanSakhariev** [comment]
Hi @proddata, thank for reporting. Checked on 5.2.8, was the same behavior on this version. But I think it has to be validated, similar to non-partitioned tables.

**Comment by BaurzhanSakhariev** [comment]
There are actually more problematic scenarios with the same root case, see https://github.com/crate/crate/pull/14305#issuecomment-1605357855, they need to be double checked and tackled with a single fix.

**Comment by BaurzhanSakhariev** [comment]
Hi @proddata, thanks again for reporting, we fixed this and some other related bugs.
