### ISSUE TITLE
Expose KnnVectorField + Query for semantic search applications

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#14319]
### Problem Statement

CrateDB has a pretty powerful search functionality with `MATCH` and scoring, but for some applications it would be nice if it could support semantic search functionality as well.

My own example use-case:

I index articles that I found interesting and where I think I may want to reference them later into CrateDB. I also generate a summary using [txtai](https://github.com/neuml/txtai)

CrateDB could support storing embeddings/vectors created using such libraries to enable querying the data later.

### Possible Solutions

Expose [KnnFloatVectorField](https://lucene.apache.org/core/9_6_0/core/org/apache/lucene/document/KnnFloatVectorField.html) as a new data type and [KnnFloatVectorQuery](https://lucene.apache.org/core/9_6_0/core/org/apache/lucene/search/KnnFloatVectorQuery.html)

Anything related to creating these vectors would be out-of-scope.

### Considered Alternatives

- Use existing `MATCH` functionality
- Store as regular float array - But then you cannot query it.

**Comment by andnig** [comment]
Having a database which can handle texts and provides an interface for both sparse and dense vector search would be very helpful for anything "LLM and document" related.
I'm currently working on several topics around Chatbots for Customer Support teams which basically require to index unstructured data (pdf, docx) and create smaller chunks for the LLM to use. Customer service teams then can utilize a chat interface to ask "I have a problem with my Verdichter, what can I do?" (or something like that) - and key for that to work is that one needs to retrieve the correct text chunk which is then sent to the LLM.
I started using only HNSW index search and the results were sort of fine, but especially on highly domain-specific topics, the retrieval results were rather poor (which is somehow to be expected if you look at how the transformers are trained which generated the embeddings used for these index searches).
So currently I'm experimenting with several hybrid approaches, one being quite brute force "fetch 3 chunks using hnsw" and "3 chunks using bm25". Having a single database which provides an interface for both would be quite helpful.

With regards to what I could find so far: The more domain-specific the knowledge is (like machining, production, etc) you need to retrieve, the more you want to rely on hybrid searches, as the embedding models are not well suited for that kind of vectors. This might change in the future when embedding models get better in "zero-shot" capabilities, but for know it seems to be the way to go.

**Comment by mfussenegger** [comment]
Implemented via:

- https://github.com/crate/crate/pull/14437
- https://github.com/crate/crate/pull/14489
- https://github.com/crate/crate/pull/14493
