### ISSUE TITLE
Support nested arrays

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#14328]
### Problem Statement

Currently something like:

```sql
CREATE TABLE tbl (xs int[][])
```

Is not supported.
The storage system in CrateDB would support storing multi-dimensional arrays, and it is via object array / object nesting already possible to create a schema that effectively results in nested arrays.

Based on https://github.com/crate/crate/pull/14324 it looks like the main component responsible for the restriction is actually the create/alter table analyzer.

### Possible Solutions

Rework the components to support arbitrary nesting.

### Considered Alternatives

- Keep not supporting nested arrays?

**Comment by jeeminso** [comment]
We should consider a proper fix for https://github.com/crate/crate/issues/13990 before supported nested arrays? Also updating arrays by elements for nested arrays should be done as a follow up.

**Comment by seut** [comment]
Current estimation is based on the assumption that this is mostly only a `ArrayTypeParser` limitation. If the assumption is wrong and more work has to be done, we should re-discuss before proceeding.

**Comment by romseygeek** [comment]
This is mostly implemented by #15211, with the exception of support for dynamic nested arrays.  Maybe we should close this and open a follow-up issue to decide if we want to work on dynamic support?

**Comment by matriv** [comment]
> This is mostly implemented by #15211, with the exception of support for dynamic nested arrays. Maybe we should close this and open a follow-up issue to decide if we want to work on dynamic support?

Agree, please open another issue to track the dynamic object support, thx!

**Comment by romseygeek** [comment]
I opened https://github.com/crate/crate/issues/15545
