### ISSUE TITLE
UPDATE statement not adhering to filters in the WHERE clause

### ISSUE THREAD

**Issue by tellezb** [crate/crate#14347]
### CrateDB version

4.8.4

### CrateDB setup information

No special configuration that I've identified. Reproduced on the following environments:

3-node cluster running in Docker on AWS ec2
1-node instance running in Docker in WSL Ubuntu

### Problem description

When executing an UPDATE statement, the record updates even if the filter criteria is not fully satisfied. From what I can tell, if the UPDATE has any clause in the WHERE which matches the primary key of the table, then the update occurs; even if other filters should prevent it.

This results in data to be updated when it shouldn't be.

This doesn't seem to be an issue in version 3.3.5.

### Steps to Reproduce
```sql
create table test (id int, alias STRING, primary key (id));
insert into test (id, alias) values (1, 'test');

select alias from test where id = 1; -- results in ‘test’
update test set alias = 'uh oh' where id = 1 and alias = 'something else';
select alias from test where id = 1; ; -- results in ‘uh oh’
```

drop table test;

### Actual Result

The update statement in the example above updates the record, even though the filter for 'something else' should have prevented it.

### Expected Result

The update statement in the example above **does not** update the record since the filter for 'something else' prevents it.

**Comment by matriv** [comment]
Thx @tellezb for reporting this, the fix has been merge and will be available with the next hotfix release.
