### ISSUE TITLE
schema is not respected in function references in views

### ISSUE THREAD

**Issue by proddata** [crate/crate#14382]
### CrateDB version

5.3.3

### Problem description

Not sure if this is a bug, but the schema is lost in VIEWs if the search_path is changed (e.g. through providing a database name using pg-connections)

### Steps to Reproduce

```sql
CREATE FUNCTION my_func()
    RETURNS BOOLEAN
    LANGUAGE JAVASCRIPT
    AS $$function my_func(){
        return true
    }$$;

CREATE VIEW my_view AS SELECT my_func();
```

```
SELECT * FROM doc.my_view;
+------+
| true |
+------+
| TRUE |
+------+

cr> set search_path to 'crate';
SET OK, 0 rows affected  (0.006 sec)
```

### Actual Result

```
cr> SELECT * FROM doc.my_view;
UnsupportedFunctionException[Unknown function: my_func()]
```

### Expected Result

```
cr> SELECT * FROM doc.my_view;
+------+
| true |
+------+
| TRUE |
+------+
SELECT 1 row in set (0.026 sec)
```

**Comment by hlcianfagna** [comment]
Well spotted, I confirmed that in PostgreSQL the view continues to work after changing the `search_path`.

**Comment by matriv** [comment]
As I understand, we need to save the `search_path` value at the moment of view creation, together with the view, to make this feasible.

**Comment by proddata** [comment]
@matriv Is the view stored "as-is" or in an analysed manner? If it is the latter, should it not always just use the fqn ?

**Comment by proddata** [comment]
I think the trouble is, that the `VIEW` would have a different `search_path` than the actual query the user is running. Don't know if that is problematic?


```sql
SET search_path 'my_schema';
SELECT * FROM my_table JOIN the_view ON ...
```

**Comment by matriv** [comment]
True, if we attempt the 1st approach, to save a `search_path` together with the sql statement on a view, that `search_path` should apply only the sql statement of the view and not to the query `userX` is executing, which might refer to other objects (tables, views, function) for which `userX's` `search_path` should apply.

Therefore, I think the solution with `fqn` which you brought up (thx!) is the the way to go, so it's very clear when you query the `information_schema` and `pg_views`, to see exactly which objects the view uses.
