### ISSUE TITLE
replace or update on duplicate key support

### ISSUE THREAD

**Issue by bububa** [crate/crate#1443]
Is there any plan to support REPLACE or INSERT ... ON DUPLICATE KEY UPDATE .... query?

**Comment by seut** [comment]
@bububa we've published a 0.47 (testing) release which supports ``INSERT ... ON DUPLICATE KEY UPDATE``. See also https://crate.io/docs/en/latest/sql/dml.html?highlight=duplicate%20key#on-duplicate-key-update.
