### ISSUE TITLE
Creating subscriptions fails if connection string has a slash

### ISSUE THREAD

**Issue by SStorm** [crate/crate#14445]
### CrateDB version

5.3.3

### Problem description

Attempting to create a subscription like this:
```sql
create subscription test connection 'crate://test.some.cluster.net/?mode=pg_tunnel&user=bla&password=bla' publication test;
```

will result in the following error:
```
IllegalStateException[CrateException 'class io.crate.exceptions.InvalidArgumentException' not supported by privileges exception validator]
```

This is very confusing and does not explain to the user what they did wrong. 

It seems to be caused by the slash before `?mode` - it works fine without it.

It would be nice to support connection strings with a slash in them, as they are still valid URIs. If that's not possible, at least a proper exception would be nice. 

### Steps to Reproduce

As above.

### Actual Result

Error

### Expected Result

Success

**Comment by BaurzhanSakhariev** [comment]
1. Allow slash (if possible) - `ConnectionInfo.fromURL` needs to be patched.
2. Show `InvalidArgumentException` for non-superusers - `MaskSensitiveExceptions.visitCrateException `needs to be patched

**Comment by matriv** [comment]
@BaurzhanSakhariev Regarding `2.` I think the behavior is correct:
```
$> crash --host "localhost:4200" --user crate
CONNECT OK
cr> CREATE USER matriv;
CREATE OK, 1 row affected  (0.078 sec)
cr>                                                                                                                                                                                             
Bye!


$> crash --host "localhost:4200" --user matriv
CONNECT OK

cr> CREATE SUBSCRIPTION sub CONNECTION 'crate://example.com/db' publication pub1;
MissingPrivilegeException[Missing 'AL' privilege for user 'matriv']
cr>                                                                                                                                                                                             
Bye!

> crash --host "localhost:4200" --user crate
CONNECT OK

cr> GRANT AL TO matriv;
GRANT OK, 1 row affected  (0.069 sec)
cr> CREATE SUBSCRIPTION sub CONNECTION 'crate://example.com/db' publication pub1;
InvalidArgumentException[Database argument "db" is not supported inside the connection string: crate://example.com/db]
```
So we get to see url errors once you have permissions.

**Comment by matriv** [comment]
correct, apologies!

**Comment by BaurzhanSakhariev** [comment]
Merge triggers issue close but there will be a follow up, reopened it.

**Comment by matriv** [comment]
@SStorm thx for reporting this issue! Fix will be available with next hotfix release(s).
