### ISSUE TITLE
Allow the use of tarball files as readonly snapshot repositories

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14474]
### Problem Statement

In environments with lots of nodes, tables, and shards, where lots of snapshots are taken, repositories may have many many files, it is handy for administrators to archive these repositories as tarball files but then these need to be extracted somewhere when a restore is needed.

### Possible Solutions

Add support for `CREATE REPOSITORY` to work with tarball (and/or other archive formats)

### Considered Alternatives

- Extract the tarball and create a repository pointing to the folder with the extracted files as usual.
- Use utilities at OS/platform level to mount the archive as a folder

**Comment by mfussenegger** [comment]
Closing this for now as this would introduce lots of complexity and there's an easy workaround: Extract the tarball again.
