### ISSUE TITLE
Provide Ubuntu packages for aarch64

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14486]
### Problem Statement

Looking to deploy CrateDB on AWS Graviton or Hetzner Ampere machines running Ubuntu it would be convenient to have a .deb package for this architecture.

### Possible Solutions

Add steps to our distribution build process to also cover this architecture

### Considered Alternatives

Use the tarball package

**Comment by mfussenegger** [comment]
We updated our packaging setup and the release pipelin to include ARM64 deb packages.

 Starting with 5.5.1 they're available in a new debian repository: https://cdn.crate.io/downloads/debian/stable/
