### ISSUE TITLE
PLAIN INDEX on multiple fields creates FULLTEXT INDEX instead

### ISSUE THREAD

**Issue by matriv** [crate/crate#14532]
### CrateDB version

5.5.0

### Steps to Reproduce

https://github.com/crate/crate/blob/master/server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java#L345
https://github.com/crate/crate/blob/master/server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java#L372

### Actual Result

`USING PLAIN (col_a, col_b)` results in FULLTEXT index

### Expected Result

`USING PLAIN (col_a, col_b)` should result in a PLAIN index

**Comment by proddata** [comment]
I thought this is intended:
https://crate.io/docs/crate/reference/en/5.4/general/ddl/fulltext-indices.html#defining-a-composite-index

**Comment by matriv** [comment]
Then I think we should not allow `plain` for multiple cols.
Alternatively (but imho less nice), make it clear in the docs that even if `plain` is used, the index is `fulltext`.

**Comment by matriv** [comment]
As discussed, `INDEX plain` is just a shortcut for `INDEX using fulltext with (analyzer = 'keyword')` so we keep allowing it and clarified in the docs.

thx @proddata for your help!
