### ISSUE TITLE
Setting standard_conforming_strings to on should not result on an UnsupportedFeatureException

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14560]
### CrateDB version

5.4.1

### Problem description

`standard_conforming_strings` is a session setting concerning the treatment of backslashes in string literals.
It was introduced in https://github.com/crate/crate/pull/13949 as a read only setting which always returns `on`.
`ompgsql` connects with `-c standard_conforming_strings=on` which results on an `UnsupportedFeatureException`
Trying to set it to the current value should be ignored gracefully.

### Steps to Reproduce

```sql
SET standard_conforming_strings='on';
```

### Actual Result

```
UnsupportedFeatureException["standard_conforming_strings" cannot be changed.]
```

### Expected Result

```
postgres=# SET standard_conforming_strings='on';
SET
```

**Comment by hlcianfagna** [comment]
In the specific case of `ompgsql` this can be worked around specifying `conninfo` (requires `rsyslog` v8.2202 or later) but the same issue may affect other tools.

**Comment by proddata** [comment]
`'on'` is a boolean value in PostgreSQL.
So one might also would want to support `1,'yes','true',TRUE` in all kinds of variations 

```sql
SET standard_conforming_strings = on;
SET standard_conforming_strings = 'oN';
SET standard_conforming_strings = 'YeS';
SET standard_conforming_strings = true;
SET standard_conforming_strings = 1;

SHOW standard_conforming_strings;
 standard_conforming_strings 
-----------------------------
 on
```
