### ISSUE TITLE
Regex comparison issues on FT indexed field?

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14572]
### CrateDB version

5.4.1

### CrateDB setup information

Single node

### Problem description

Got a table with a full text indexed text field.
I know I can use `MATCH` on this field, but for a special query I specifically want to use regex expressions with the ~ comparison operator (I need to look for specific patterns in the original text not tokens - but I also want to do proper full text search on this same data).
The results I am getting are a bit confusing, it seems it is allowed to use the ~ operator on a full text indexed field but it behaves in a very different way to a normal field, could you check if this is a bug or if some clarification is needed in the documentation?
Thank you.

### Steps to Reproduce

```sql
CREATE TABLE searchtest(a TEXT,b TEXT INDEX USING FULLTEXT);
INSERT INTO searchtest(a,b) VALUES 
('   abcdef  ','   abcdef  '),
('   ABCDEF  ','   ABCDEF  '),
('   abc  def  ','   abc  def  '),
('   ABC  DEF  ','   ABC  DEF  ');
```

### Actual Result

```sql
SELECT * FROM searchtest WHERE a ~ '.*ABC.*DEF.*'; --> only upper case entries found
SELECT * FROM searchtest WHERE a ~ '.*abc.*def.*'; --> only lower case entries found;
SELECT * FROM searchtest WHERE b ~ '.*ABC.*DEF.*'; --> nothing found
SELECT * FROM searchtest WHERE b ~ '.*abc.*def.*'; --> only finds entries without spaces between the words, both upper and lowercase
```

### Expected Result

The ~ yields the same results on normal TEXT fields and fields indexed with FT.

**Comment by matriv** [comment]
Yep it needs clarification, in order to achieve both you need to create the table like this:
```
CREATE TABLE searchtest(a TEXT,b TEXT, INDEX ft USING FULLTEXT(b));
```
so to have b indexed as `keyword` without tokenization and analysis
and use `ft` for full text searches

**Comment by matriv** [comment]
@hlcianfagna Could you please take care of the docs improvement?
