### ISSUE TITLE
Update by primary key should return either the updated document or the "_version" value

### ISSUE THREAD

**Issue by hasnainjaved** [crate/crate#1463]
Hello,

It would be nice to return either the updated document or the "_version" value when a row is updated. An additional query has to be made just to get the "_version" value of the updated document.

Kind Regards.
Hasnain.
##

**Comment by mfussenegger** [comment]
We recently added the RETURNING clause for UPDATE (and INSERT), both will be released with 4.2. (https://github.com/crate/crate/pull/9434)
