### ISSUE TITLE
Allow explicitly nullable columns in CREATE TABLE

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14633]
### Problem Statement

When migrating data from other systems we may have `CREATE TABLE` statements with columns explicitly declared as nullable, this is allowed in PostgreSQL but it results on a `SQLParseException` in CrateDB

```sql
create table test1 (a int null);
```

### Possible Solutions

Recognize `NULL` on that position and ignore it (nullable columns is the default in CrateDB)

### Considered Alternatives

Manually edit the `CREATE TABLE` statements to remove the occurrences of `NULL`

**Comment by dshunter107** [comment]
Hello, I am a newcomer to github, but I have an idea of how I would work on this. Could you tell me any more about this. For example, which packages or classes do you recommend that I look at to resolve this issue.

**Comment by seut** [comment]
@dshunter107 A good starting point for general development is our developer documentation at https://github.com/crate/crate/tree/master/devs/docs.

For this concrete issue, our SQL ANTLR parser needs to be adjusted to allow an optional column constraint `NULL` at the column definition. see https://github.com/crate/crate/blob/master/libs/sql-parser/src/main/antlr/SqlBaseParser.g4#L675.

Thank you a lot for your contribution.

**Comment by hlcianfagna** [comment]
Just a quick note on the workaround of manually removing the occurrences of `null`, this can be done in bulk with a regex replace: `(?<!not )null`

**Comment by saikiran76** [comment]
can I work on this?

**Comment by matriv** [comment]
@saikiran76 There is already work in progress for this: https://github.com/crate/crate/issues/14633, so please pick up something else, thank you for your interest in contributing to CrateDB.
