### ISSUE TITLE
Support for `IS DISTINCT FROM` and `IS NOT DISTINCT FROM` operators

### ISSUE THREAD

**Issue by proddata** [crate/crate#14644]
### Problem Statement

Using Tableau to build visualizations and reports off CrateDB with the PostgreSQL connection, the lack of native support  for the comparison operators "IS DISTINCT FROM" and "IS NOT DISTINCT FROM" has been identified. These operators, available in PostgreSQL, facilitate the treatment of `NULL` as an ordinary value, leading to more intuitive comparisons, especially in scenarios where `NULL` values are frequent. The absence of this feature leads to a broken user experience in tools like Tableau.

[PostgreSQL's documentation](https://www.postgresql.org/docs/current/functions-comparison.html) offers the following definitions:

> - **datatype IS DISTINCT FROM datatype → boolean**  
>     Not equal, treating null as a comparable value.  
>     Examples:  
>     `1 IS DISTINCT FROM NULL → t` (rather than NULL)  
>     `NULL IS DISTINCT FROM NULL → f` (rather than NULL)
> 
> - **datatype IS NOT DISTINCT FROM datatype → boolean**  
>     Equal, treating null as a comparable value.  
>     Examples:  
>     `1 IS NOT DISTINCT FROM NULL → f` (rather than NULL)  
>     `NULL IS NOT DISTINCT FROM NULL → t` (rather than NULL)

#### Example

```sql
-- Create table statement for a hypothetical `products` table
CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    name TEXT,
    manufacturer TEXT DEFAULT NULL
);

-- Insert some sample data
INSERT INTO products (id, name, manufacturer) VALUES (1, 'Laptop', 'TechCorp');
INSERT INTO products (id, name, manufacturer) VALUES (2, 'Mobile', NULL);
INSERT INTO products (id, name) VALUES (3, 'Tablet');
INSERT INTO products (id, name, manufacturer) VALUES (4, 'Monitor', 'TechCorp');
INSERT INTO products (id, name, manufacturer) VALUES (5, 'Mobile', 'GadgetInc');

-- Use the "IS DISTINCT FROM" operator
-- Find all products that don't have 'TechCorp' as the manufacturer or have NULL as the manufacturer
SELECT * FROM products WHERE manufacturer IS DISTINCT FROM 'TechCorp';

-- Use the "IS NOT DISTINCT FROM" operator
-- Find all products that have 'TechCorp' as the manufacturer or have NULL as the manufacturer
SELECT * FROM products WHERE manufacturer IS NOT DISTINCT FROM 'TechCorp';
```

### Possible Solutions

Implement "IS DISTINCT FROM" and "IS NOT DISTINCT FROM" Operators**: Native support for these operators in CrateDB, closely emulating the behavior found in PostgreSQL.

Also part of SQL 1999:

https://github.com/crate/sql-99/blob/c8848117d60e60aa9ba1132813f32ad91a99af6c/docs/chapters/29.rst?plain=1#L1137-L1198

### Considered Alternatives

No alternative for Tableau (other then custom connector)

### Example:

Example query from Tableau demonstrating the use-case, that was generated while trying to apply a sort, which leads to an exception in Tableau and a broken UX

```sql
SELECT "data_table"."product_name" AS "product",
  SUM("data_table"."pricing_currency") AS "sum:cost_in_pricing_currency:ok"
FROM "product_data"."data_table" "data_table"
  INNER JOIN (
  SELECT "data_table"."product_name" AS "product",
    "data_table"."service_family_name" AS "service_family"
  FROM "product_data"."data_table" "data_table"
  WHERE ((CAST(TRUNC(EXTRACT(MONTH FROM "data_table"."end_date")) AS INTEGER) = 7) AND ("data_table"."subscription" = 'crate'))
  GROUP BY 1, 2
  HAVING (SUM("data_table"."cost_usd") >= 4.9999999999999503)
) "temp_table" ON (("data_table"."product_name" IS NOT DISTINCT FROM "temp_table"."product") AND ("data_table"."service_family_name" IS NOT DISTINCT FROM "temp_table"."service_family"))
WHERE ((CAST(TRUNC(EXTRACT(MONTH FROM "data_table"."end_date")) AS INTEGER) = 7) AND ("data_table"."subscription" = 'crate'))
GROUP BY 1
```

**Comment by marstein** [comment]
I would be interested in building this. Some questions:

How would the part executing the operations (from the `ExpressionAnalyzer`) on the rows be implemented? As `Scalar`, as `Operator`, or as `Function`? It is really a predicate, so would a `Predicate` base class be more fitting? 

Many thanks, Martin

**Comment by marstein** [comment]
Hello,
I have implemented this first as a function, and then as an Operator, to benefit from the work already done for Operators. This works, but I get in trouble with the Lucene query. It seems to be a lot of work to implement the Lucene query. I assume this was done as performance improvement. Does it from the maintainers' point of view make sense to port the equal-operators Lucene query functionality to "is distinct"? 
Thanks!

**Comment by jeeminso** [comment]
Hi @marstein sorry for the late response.

> Does it from the maintainers' point of view make sense to port the equal-operators Lucene query functionality to "is distinct"?

I think we could try to call appropriate eqOperator methods from isDistinct operator instead of porting them.

By the way, implementing `toQuery`(generating lucene query) is like an optimization step that could be done as a follow up. Implementing `evaluate` would be enough to have a fully functioning `is distinct` operator.

**Comment by marstein** [comment]
> I think we could try to call appropriate eqOperator methods from isDistinct operator instead of porting them.
> 
> By the way, implementing `toQuery`(generating lucene query) is like an optimization step that could be done as a follow up. Implementing `evaluate` would be enough to have a fully functioning `is distinct` operator.

Very good. I'll prepare a proposal along those lines, and then propose the `toQuery` method as an extension. (It seems to me as if it could be just like 'not equal' without the `FieldExists`, but there is a lot more code dealing with other concerns that I don't quite understand yet.)

**Comment by marstein** [comment]
I believe my PR is done. Please review, @jeeminso @matriv or @mfussenegger 
Thanks

**Comment by proddata** [comment]
Thank you @marstein 🙇
