### ISSUE TITLE
Extend Optimizer to push Limits down to more plans

### ISSUE THREAD

**Issue by mkleen** [crate/crate#14714]
## Outer-Joins (and Cross-join?)

```
        Limit
          |
         Join
        /    \
       lhs   rhs
```

```
        Limit
          |
         Join
        /     \
       limitA  limitB
        |      |
       lhs    rhs


limitA: If join is left or outer
limitB: If join is right or outer
```

## References

- https://github.com/apache/arrow-datafusion/blob/main/datafusion/optimizer/src/push_down_limit.rs
- https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughUnion.java
- https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java

**Comment by hlcianfagna** [comment]
> Limits can be safely pushed down
Only if there is no `OFFSET`

**Comment by mfussenegger** [comment]
Pushing limit below order would change semantics:


```
[b, c, a] -> limit 2 -> [b, c] -> order by -> [b, c]
[b, c, a] -> order by -> [a, b, c] -> limit 2 -> [a, b]
```


For union it needs to copy the limit, instead of moving.

I'm also not sure about the joins, both outer join and cross join can create new rows so it would need at least to copy the limit, but I'm also not sure if that's safe. Do you have a reference to optimizations in other DBs?

**Comment by mkleen** [comment]
> Pushing limit below order would change semantics:
> 
> ```
> [b, c, a] -> limit 2 -> [b, c] -> order by -> [b, c]
> [b, c, a] -> order by -> [a, b, c] -> limit 2 -> [a, b]
> ```
> 
> For union it needs to copy the limit, instead of moving.
> 
> I'm also not sure about the joins, both outer join and cross join can create new rows so it would need at least to copy the limit, but I'm also not sure if that's safe. Do you have a reference to optimizations in other DBs?

Yes, have a look at https://github.com/apache/arrow-datafusion/blob/main/datafusion/optimizer/src/push_down_limit.rs

**Comment by mfussenegger** [comment]
Looks like they copy the limit for union and outer join, and for order they merge it into a "topN", we do the same already when we build an execution plan.

**Comment by decoder746** [comment]
Can I and @theartpiece, get assigned to this issue?

**Comment by mfussenegger** [comment]
Sure. I'd suggest to focus on one of the two transformations first - either union or outer joins - not both immediately.

You can have a look at existing similar rules to get an idea:

https://github.com/crate/crate/blob/97f8021cd1f5f560d7a0551dd54259b81b7b11f8/server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathRename.java#L41-L67

https://github.com/crate/crate/blob/97f8021cd1f5f560d7a0551dd54259b81b7b11f8/server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathEval.java#L41-L67

**Comment by theartpiece** [comment]
Hi @BaurzhanSakhariev, we're working on it. Thanks so much for following up. We really appreciate your patience.

Kind regards

**Comment by BaurzhanSakhariev** [comment]
Hi @decoder746, @theartpiece do you need any help with this? 

I'm asking because this issue has a high priority and we would need to take over soon.
