### ISSUE TITLE
Add a length() function to compute length of string types?

### ISSUE THREAD

**Issue by bhaskarb2014** [crate/crate#1476]
How can I find out the length of a string type in Crate, something like the following (in MySQL):

SELECT LENGTH(string_field) L, COUNT(*) FROM my_table GROUP BY L;

**Comment by chaudum** [comment]
@bhaskarb2014 
we've added your requested feature to out backlog!

**Comment by kovrus** [comment]
@bhaskarb2014 we have implemented char_length, bit_length, and byte_length scalar functions. They are on master now. It will be released in 0.54.0 testing. /cc @joemoe
