### ISSUE TITLE
Improve normalization of intervals

### ISSUE THREAD

**Issue by piotrrzysko** [crate/crate#14798]
### Problem Statement

Currently, interval operations (subtraction, addition, multiplication, average) use `Period:normalizedStandard` for normalization, which has some limitations. For example, as stated in its javadoc, for 1 month 40 days, it returns 1 month 40 days, instead of 2 months 10 days. 

I've implemented a prototype function  that overcomes these limitations and, as a byproduct, helps mitigate overflows while multiplying intervals by integers, as described in https://github.com/crate/crate/pull/14755#discussion_r1338276299. Here is the function's code:

```java

    private static final int DAYS_PER_MONTH = 30;
    private static final int DAYS_PER_YEAR = DAYS_PER_MONTH * 12;
    private static final BigInteger MILLIS_PER_YEAR = BigInteger.valueOf(DAYS_PER_YEAR)
            .multiply(BigInteger.valueOf(DateTimeConstants.MILLIS_PER_DAY));
    private static final BigInteger MILLIS_PER_MONTH = BigInteger.valueOf(DAYS_PER_MONTH)
            .multiply(BigInteger.valueOf(DateTimeConstants.MILLIS_PER_DAY));


    /**
     * Creates a period from the given millisecond duration. The period is of the
     * {@link PeriodType#yearMonthDayTime()} type and is normalized, assuming a
     * 12-month year, 30-day month, 24-hour day, 60-minute hour, and 60-second minute.
     * Examples:
     * <ul>
     * <li>31104000000 ms will be converted to 1 year
     * <li>31103999999 ms will be converted to 11 months 29 days 23 hours 59 minutes 59 seconds 999 milliseconds
     * </ul>
     *
     * @param durationInMillis the duration, in milliseconds
     * @return a normalized period equivalent to the given duration
     * @throws ArithmeticException if the given duration is too large to be represented as a {@link Period}
     */
    public static Period toNormalizedPeriod(BigInteger durationInMillis) {
        BigInteger[] yearsAndRemainder = durationInMillis.divideAndRemainder(MILLIS_PER_YEAR);
        int years;
        try {
            // An ArithmeticException can only be thrown here because the first division reduces the duration to
            // at most 31103999999 milliseconds, which is equivalent to 11 months 29 days 23 hours 59 minutes
            // 59 seconds 999 milliseconds. All of these period components can be safely stored as integers.
            years = yearsAndRemainder[0].intValueExact();
        } catch (ArithmeticException e) {
            throw new ArithmeticException("The number of years is out of the integer range: " + yearsAndRemainder[0]);
        }
        durationInMillis = yearsAndRemainder[1];
        BigInteger[] monthsAndRemainder = durationInMillis.divideAndRemainder(MILLIS_PER_MONTH);
        int months = monthsAndRemainder[0].intValueExact();
        durationInMillis = monthsAndRemainder[1];

        long millis = durationInMillis.longValueExact();
        int days = FieldUtils.safeToInt(millis / DateTimeConstants.MILLIS_PER_DAY);
        millis -= (long) days * DateTimeConstants.MILLIS_PER_DAY;
        int hours = FieldUtils.safeToInt(millis / DateTimeConstants.MILLIS_PER_HOUR);
        millis -= (long) hours * DateTimeConstants.MILLIS_PER_HOUR;
        int minutes = FieldUtils.safeToInt(millis / DateTimeConstants.MILLIS_PER_MINUTE);
        millis -= (long) minutes * DateTimeConstants.MILLIS_PER_MINUTE;
        int seconds = FieldUtils.safeToInt(millis / DateTimeConstants.MILLIS_PER_SECOND);
        millis -= (long) seconds * DateTimeConstants.MILLIS_PER_SECOND;
        return new Period(
                years,
                months,
                0, // weeks
                days,
                hours,
                minutes,
                seconds,
                FieldUtils.safeToInt(millis),
                PeriodType.yearMonthDayTime()
        );
    }
```

The potential problem with this function is its assumption that a year has 360 days. This assumption might seem counterintuitive and is not aligned with CrateDB's current interval comparison implementation. The reasoning behind this assumption has been described in this comment: https://github.com/crate/crate/pull/14755#discussion_r1342330782. As mentioned in the comment, the 360-day year aligns with PostgreSQL, which for

```sql
SELECT justify_interval(interval '365 days');
```

returns 

```
1 years 0 mons 5 days 0 hours 0 mins 0.0 secs
```

whereas for

```sql
SELECT justify_interval(interval '360 days');
```

returns

```
1 years 0 mons 0 days 0 hours 0 mins 0.0 secs
```

On the other hand, as pointed out in https://github.com/crate/crate/pull/14755#discussion_r1342407922, PostgreSQL's interval arithmetic is even more complicated.

I'm happy to work on this issue. However, I'd like to discuss first if the assumption of a year having 360 days is correct.

**Comment by matriv** [comment]
Thank you for opening the issues and the work/investigation from your side @piotrrzysko.
We'll discuss the issue and post any decisions here.

**Comment by matriv** [comment]
@piotrrzysko Do you have the time to investigate a bit how other Databases behave ?
Like MySQL/MS-SQL server/Oracle? (maybe you can use: http://sqlfiddle.com/ and/or https://www.db-fiddle.com/)

**Comment by matriv** [comment]
Thx a lot for all the investigation @piotrrzysko!

I played around a bit myself and overall I think we shouldn't do anything for the time being, if there is some request by users we can always revisit this. My thinking is:

`select interval '2147483648' second` but also for the multiplication of seconds, we don't comply currently with postgres, and those are restrictions that come from Joda's `Period`. To overcome them we need this custom but rather expensive normalization to "promote" to the next unit, where we also don't have a clear view on how to convert, consistently, days to months and years (30?, 365?). After all INTERVAL is a "weird", runtime only, datatype and SQL specs defines 2 different classes of intervals, so those conventions are prevented:
```
There are two classes of intervals. One class, called year-month intervals, has an express or implied datetime precision that includes no fields other than YEAR and MONTH, though not both are required. The other class, called day-time intervals, has an express or implied interval precision that can include any fields other than YEAR or MONTH
```
So if you have an HOUR-SECOND interval and you multiply by an integer then the result should be of the same class, so MONTHs and YEARs are not involved, therefore no conversion according to the spec.

I also found the following sentences in the spec:
```
Arithmetic operations involving values of type datetime or interval obey the natural rules associated with dates and times and yield valid datetime or interval results according to the Gregorian calendar.
```,
```
Interval arithmetic that involves leap seconds or discontinuities in calendars will produce implementation-defined results.
```

@BaurzhanSakhariev @seut What's your take on this?

**Comment by matriv** [comment]
Thx a lot for all the investigation @piotrrzysko!

I played around a bit myself and overall I think we shouldn't do anything for the time being, if there is some request by users we can always revisit this. My thinking is:

`select interval '2147483648' second` but also for the multiplication of seconds, we don't comply currently with postgres, and those are restrictions that come from Joda's `Period`. To overcome them we need this custom but rather expensive normalization to "promote" to the next unit, where we also don't have a clear view on how to convert, consistently, days to months and years (30?, 365?). After all INTERVAL is a "weird", runtime only, datatype and SQL specs defines 2 different classes of intervals, so those conventions are prevented:
```
There are two classes of intervals. One class, called year-month intervals, has an express or implied datetime precision that includes no fields other than YEAR and MONTH, though not both are required. The other class, called day-time intervals, has an express or implied interval precision that can include any fields other than YEAR or MONTH
```
So if you have an HOUR-SECOND interval and you multiply by an integer then the result should be of the same class, so MONTHs and YEARs are not involved, therefore no conversion according to the spec.

I also found the following sentences in the spec:
```
Arithmetic operations involving values of type datetime or interval obey the natural rules associated with dates and times and yield valid datetime or interval results according to the Gregorian calendar.
```

```
Interval arithmetic that involves leap seconds or discontinuities in calendars will produce implementation-defined results.
```

@BaurzhanSakhariev @seut What's your take on this?

**Comment by piotrrzysko** [comment]
Thanks, @matriv. I share your sentiment on that. Either way, if you decide to move forward with this issue at some point, I can try to help :).

**Comment by matriv** [comment]
Thank you @piotrrzysko !
Let's wait for another opinion though.

**Comment by seut** [comment]
@matriv @piotrrzysko 
Thank you a lot for the investigations.
I also share you thoughts on this and additionally agree on leaving it as it for the time being.

**Comment by BaurzhanSakhariev** [comment]
Thanks for providing detailed overview!

Agree to keep it with one minor comment regarding https://github.com/crate/crate/pull/14755#discussion_r1342330782
>Currently, CrateDB returns true for the following query:

>SELECT ('1 year'::interval) = ('365 days'::interval);
>This behavior seems to be reasonable. However, PostgresQL, for the exact same query returns false.
>Apparently, in PostgresQL, one year is considered to have 360 days, because for the following query it returns true:

>SELECT ('1 year'::interval) = ('360 days'::interval);

I think we can use 360 days per year in comparison. (ie revert https://github.com/crate/crate/pull/14124/commits/47030fbfa59a1e58656d54df2dd13d0c80324d94) as it wouldn't imply that we are internally using 1 year = 360 days internally. Query `select interval '1' year + interval '360' day` returns `1 years, 360 days` for CrateDB, Postgres 14, Yugabyte, Timescale, it's not transformed into 2 years. 

But this is anyway outside of the normalization scope.

**Comment by matriv** [comment]
> I think we can use 360 days per year in comparison. (ie revert 
 https://github.com/crate/crate/commit/47030fbfa59a1e58656d54df2dd13d0c80324d94) as it wouldn't imply that we are internally using 1 year = 360 days internally. Query select interval '1' year + interval '360' day returns 1 years, 360 days for CrateDB, Postgres 14, Yugabyte, Timescale, it's not transformed into 2 years.

Since it's only used for comparing 2 intervals, It's ok to leave this as is, doesn't have to do with any normalization, as we use the methods of `Period` for this.

**Comment by matriv** [comment]
Closing this issue, thx again @piotrrzysko for all the detailed investigation.
If there is a request in the future we will revisit it.
