### ISSUE TITLE
Vector Store: Comparing `float_vector` DDL and behavior against other implementations

### ISSUE THREAD

**Issue by amotl** [crate/crate#14800]
## Problem Statement

While working on [integrating LangChain with CrateDB](https://github.com/crate-workbench/langchain/tree/cratedb), based on the pgvector adapter implementation, we discovered a little anomaly when comparing them in the DDL area.

### pgvector
pgvector accepts creating a table like that. Here, the first inserted vector will actually define the vector size.
```sql
create table testdrive (embedding vector);
```

### CrateDB
With CrateDB, when creating a table without specifying the vector size, it will be implicitly defined with a size of `1`.
```sql
create table testdrive (embedding float_vector);
```

### LangChain
In LangChain, the pgvector adapter model looks like this:
```python
embedding: Vector = sqlalchemy.Column(Vector(None))
```
-- https://github.com/langchain-ai/langchain/blob/52bf62354ec5cce030a74a68970df1a0f0b17962/libs/langchain/langchain/vectorstores/_pgvector_data_models.py#L66

In CrateDB, it is difficult to implement, because hardcoding the value here is not appropriate, because the user may want to work with models of different dimensions.
```python
embedding = sqlalchemy.Column(FloatVector(1024))
```
-- https://github.com/langchain-ai/langchain/blob/52bf62354ec5cce030a74a68970df1a0f0b17962/libs/langchain/langchain/vectorstores/cratedb/model.py#L68-L72

**Comment by amotl** [comment]
## Walkthroughs

### pgvector

```shell
docker run --rm -it --publish=5432:5432 \
  --env "POSTGRES_HOST_AUTH_METHOD=trust" \
  ankane/pgvector postgres -c log_statement=all
```
```sql
create extension vector;
create table testdrive (embedding vector);
insert into testdrive (embedding) values ('[1, 2, 3]');
insert into testdrive (embedding) values ('[1, 2, 3, 4]');
insert into testdrive (embedding) values ('[1, 2, 3, 4, 5]');
```


### CrateDB
```shell
docker run --rm -it --name=cratedb --publish=4200:4200 --publish=5432:5432 \
    --env=CRATE_HEAP_SIZE=4g crate/crate:nightly \
    -Cdiscovery.type=single-node
```
```sql
create table testdrive (embedding float_vector);
insert into testdrive (embedding) values ([1]);
```
```sql
insert into testdrive (embedding) values ([1, 2, 3]);
SQLParseException[The number of vector dimensions does not match the field type]
```

**Comment by mfussenegger** [comment]
Thanks for the inputs, but the fixed length is a requirement of the used Lucene type.

**Comment by amotl** [comment]
Thanks. I will investigate how the corresponding Elasticsearch and OpenSearch adapters work in this regard, and report back.

**Comment by matriv** [comment]
> Thanks. I will investigate how the corresponding Elasticsearch and OpenSearch adapters work in this regard, and report back.

https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html#dense-vector-params
*dims is mandatory param*
