### ISSUE TITLE
Vector Store: Provide similarity distance functions as scalar functions

### ISSUE THREAD

**Issue by amotl** [crate/crate#14801]
### Problem Statement

While working on [integrating LangChain with CrateDB](https://github.com/crate-workbench/langchain/tree/cratedb), based on the pgvector adapter implementation, we found the test cases actually use the outcome of the similarity distance function.

On CrateDB, the outcome will influence the `_score` value of a record when querying, so when properly sorting the records, it will yield the correct outcome from an integration perspective. However, there is no way to get hold of the similarity distance, but many applications also use that, beyond "getting/processing the results in the right order / correct precedence".

### References
- https://github.com/crate-workbench/langchain/issues/19
- https://github.com/crate/cratedb-guide/pull/53#discussion_r1537749420

### Possible Solutions

Expose the same function(s) used by Lucene for the KNN search as scalar function(s) to CrateDB SQL, as discussed with @seut and @andnig. Currently, I think the implementation uses cosine distance, but others may be added in the future.

**Comment by BaurzhanSakhariev** [comment]
Same Lucene issue (expose similarity score) - https://github.com/apache/lucene/issues/12252.

Checking the implementation, I think vectore_similarity_score would be a better name + forgot to check same length for vectors https://github.com/apache/lucene/pull/12253/files#diff-55fac07d1f7553c8e87e2841eeb008596d654388f05a4a86133da54076bca6e8R45

**Comment by BaurzhanSakhariev** [comment]
Hi @amotl, vector_similarity based on euclidean distance is implemented in https://github.com/crate/crate/pull/15832.

Not closing this issue as we might need a follow up to cover other distance types (cosine, dot-product. e.t.c)

**Comment by BaurzhanSakhariev** [comment]
As discussed internally, we will expose only euclidean distance based similarity scalar as there is no concrete use case for any other. 

We can reopen this if needed.
