### ISSUE TITLE
`blocks.read_only_allow_delete` needs to be set twice to be active

### ISSUE THREAD

**Issue by proddata** [crate/crate#14825]
### CrateDB version

5.4.3

### CrateDB setup information

single / multi

### Problem description

First alteration of `blocks.read_only_allow_delete` is ignored.

### Steps to Reproduce

```sql
CREATE TABLE x (x TEXT);
INSERT INTO x VALUES ('Hello');
ALTER TABLE x SET ("blocks.read_only_allow_delete" = true);
-- ALTER OK, -1 rows affected (0.031 sec)
INSERT INTO x VALUES ('Hello');
-- INSERT OK, 1 row affected (0.017 sec)
SELECT COUNT(*) FROM x;
+----------+
| count(*) |
+----------+
|        2 |
+----------+

ALTER TABLE x SET ("blocks.read_only_allow_delete" = true); -- ALTER OK, -1 rows affected (0.039 sec)
INSERT INTO x VALUES ('Hello'); -- ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
```

### Actual Result

needs 2 x `ALTER TABLE x SET ("blocks.read_only_allow_delete" = true);`

### Expected Result

should work after 1 call

**Comment by proddata** [comment]
```
CREATE TABLE x (x TEXT);
ALTER TABLE x SET ("blocks.read_only_allow_delete" = true);
ALTER TABLE x SET ("blocks.read_only_allow_delete" = true);
INSERT INTO x VALUES ('Hello');
--ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
```

**Comment by proddata** [comment]
😕 
```sql
cr> drop table x;
DROP OK, 1 row affected (0.078 sec)
cr> CREATE TABLE x (x TEXT);
CREATE OK, 1 row affected (0.381 sec)
cr> ALTER TABLE x SET ("blocks.read_only_allow_delete" = true);
ALTER OK, -1 rows affected (0.065 sec)
cr> INSERT INTO x VALUES ('Hello');
ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
cr> drop table x;
ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
```

**Comment by matriv** [comment]
I even experience the following:
```
cr> INSERT INTO x VALUES ('Hello');
 
ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
cr> INSERT INTO x VALUES ('Hello');
 
INSERT OK, 1 row affected (40.532 sec)
```

So, there an issue here.

**Comment by matriv** [comment]
The issue was introduced with: https://github.com/crate/crate/pull/12214, so what happens is that if we set it to `true`, soon, `DiskThresholdMonitor` will reset it back to false, since no disk usage thresholds are reached. With the aforementioned PR, we didn't introduce the setting https://github.com/elastic/elasticsearch/commit/cd304c4def3e0622666746f9fe54355217131860#diff-697233b32fbd24830c548746773a3013fc03a1cacc6ca877c8d75f0b9f68f751R76 to disable automatic reset. We also didn't update the docs accordingly, currently we state:

in `cluster.rst`
```
Read-only blocks are not automatically removed from the indices if the
disk space is freed and the threshold is undershot. To remove the block,
execute ``ALTER TABLE ... SET ("blocks.read_only_allow_delete" = FALSE)``
for affected tables (see
:ref:`sql-create-table-blocks-read-only-allow-delete`).
```

In `create-table.rst`:
```
When a disk on a node exceeds the
``cluster.routing.allocation.disk.watermark.flood_stage`` threshold, this
block is applied (set to ``true``) to all tables on that affected node. Once
you've freed disk space again and the threshold is undershot, you need to set
the ``blocks.read_only_allow_delete`` table setting to ``false``.
```

So, I see 2 approaches:
1. Introduce the setting to disable the automatic reset, so if users really want to set a table to read-only mode, can do it without having the flag flipped automatically,
2. We change the documentation to describe that this setting is potentially reset automatically.

I'd probably suggest 1. Are there any valid use cases to put a table into read-only_allow-deletes mode (apart from deleting rows to clean up space)?

**Comment by proddata** [comment]
> Are there any valid use cases to put a table into read-only_allow-deletes mode (apart from deleting rows to clean up space)?

The initial idea was to set a table to `read-only_allow-deletes` to first export or snapshot the data at a know state and then being able to remove it, avoiding any potential changes to the table.

**Comment by matriv** [comment]
> > Are there any valid use cases to put a table into read-only_allow-deletes mode (apart from deleting rows to clean up space)?
> 
> The initial idea was to set a table to `read-only_allow-deletes` to first export or snapshot the data at a know state and then being able to remove it, avoiding any potential changes to the table.

There is `blocks.read_only` setting for that, which also doesn't allow deletes.

**Comment by matriv** [comment]
Also, the setting wasn't added by us, since it was added as deprecated already for ES and was later removed, thus making auto-reset non-configurable: https://github.com/elastic/elasticsearch/commit/bc31ea752e9aa21e4112ba7d116ca6c3404c9a28

**Comment by proddata** [comment]
> There is blocks.read_only setting for that, which also doesn't allow deletes.

Which is sub-optimal in the sense that you need to lift the block again. But maybe a more artificial problem.

---

ES writes, that it may automatically be set and lifted (which we also could have in the docs). Or make it explicit, that it is not a setting meant to be used/set by the user.

**Comment by matriv** [comment]
> Which is sub-optimal in the sense that you need to lift the block again. But maybe a more artificial problem.

But if you want to perform a maintenance operation, you don't want to be lifted automatically (talking about `blocks.read_only`)

> ES writes, that it may automatically be set and lifted (which we also could have in the docs). Or make it explicit, that it is not a setting meant to be used/set by the user.

Right, maybe we should just fix our docs accordingly, thx.

Will wait for other opinions and proceed.

**Comment by BaurzhanSakhariev** [comment]
+1 for updating docs.

Regarding 
> Or make it explicit, that it is not a setting meant to be used/set by the user.

We can make it internal and not expose it to the `ALTER TABLE` statements but it would be a breaking change. 

I think it's fine for users to use it but we need to emphasize that it could be reset automatically and maybe can add a hint that `blocks.read_only` is a "stable" alternative.

**Comment by matriv** [comment]
thx @proddata for reporting this, as discussed it has been addressed by fixing the documentation.
