### ISSUE TITLE
Selecting non existing columns

### ISSUE THREAD

**Issue by l7s** [crate/crate#1484]
At the moment Crate.io allows to `SELECT` and use `WHERE` on non existing columns. What I would expect is to see some sort of error. Instead when I run example below, Crate.io "executes" queries with no error/warning:

```
CREATE TABLE test (
  id long primary key,
  first_name string,
  last_name string
);

SELECT email FROM test WHERE phone = '12345' limit 100;

# SELECT OK (0.000 sec) 
```

ngrep below:

```
T 192.168.10.32:50155 -> 192.168.10.32:4200 [AP]
POST /_sql HTTP/1.1.
Accept: application/json, text/plain, */*.
Content-Length: 65.
.
{"stmt":"SELECT email FROM test WHERE phone = '12345' limit 100"}
#
T 192.168.10.32:4200 -> 192.168.10.32:50155 [AP]
HTTP/1.1 200 OK.
Access-Control-Allow-Origin: *.
Content-Type: application/json; charset=UTF-8.
Content-Length: 54.
.
{"cols":["email"],"duration":0,"rows":[],"rowcount":0}
```

**Comment by mfelsche** [comment]
We do have a 0.46 release, though we did not declare it as stable, the latest is 0.46.1. Our testing releases come as tar.gz, .deb and .rpm, so you could use it in production, if that fits your way of deployment. See the tabs further down on https://crate.io/download/ for further infos.

Were you able to test your stuff with the 0.46.1 theoretically, at least in a dev environment?
This would help us make the 0.46 releases more stable.

We will, nonetheless, hurry up, to test and test again to make it stable!

**Comment by l7s** [comment]
I will start testing 0.46.1 in our dev/test environment tomorrow and report back here.

One question: is there any documentation about upgrading Crate.io to a higher version?

Would the below be about right for multi node (6 machines) set up:

On each node:

1. Stop node 
2. Keep `path.data` directory and replace Crate.io binaries with a newer version
3. Start node

The most important aspects I think are:
* is `path.data` files storage format compatible from version to version ?
* will never node (say 0.46.1) join the cluster with nodes still on older version 0.45.6?

**Comment by dobe** [comment]
hi @l7s 

the procedure you showed should work, however if it is possible you should use yum or ppa to maintain the crate installation.

the file storage format remains the same from 0.45 to 0.46, however i recommend stopping the whole cluster when doing major version upgrades. hotfixes can be installed without stopping the cluster, for details see https://crate.io/docs/stable/best_practice/cluster_upgrade.html

regards, bernd

**Comment by chaudum** [comment]
Column policies were introduced in 0.46, so I mark this issue as closed.
Referece: [crate.io](https://crate.io/blog/crate-release-v0-46-5/#support-for-column-policies)
