### ISSUE TITLE
Question: Namespaces or schema per users

### ISSUE THREAD

**Issue by megastef** [crate/crate#1491]
Is there any way to have a set of tables only visible for one user? 
Imagine a SaaS solution with a shared cluster for many customers. 
Is there another mechanism to achieve this (namespace, schema prefix)?

**Comment by megastef** [comment]
To clarify - this is not the question about permission (that could be handled in the frontend).
Its about separate schemas or having a namespace for multiple tables to avoid naming conflicts. 

How to define a schema to do something like this?
select columns from schemaName.table1
As far I know you use e.g. information_schema, sys etc. What about user defined schema names? 
Then for every user a schema could be created (holding multiple tables per account). 
The result would be the possibility to do:
select columns from userName.weblog

**Comment by dobe** [comment]
hi @megastef 

we have that in our current testing release 0.46.x, see https://crate.io/docs/en/latest/sql/ddl.html?highlight=schema#schemas

**Comment by megastef** [comment]
Thx - you saved my day :) getting 0.46.1 ...

**Comment by dobe** [comment]
welcome :) hope to see you at the snowsprint!
