### ISSUE TITLE
System view for open sessions

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14937]
### Problem Statement

When debugging issues with connection pooling, `connections` in `sys.nodes` allows to see the number of open connections, but there are no further details.

### Possible Solutions

It would be nice to have a system view for open sessions which could maybe show handling node, client IP address, user name, time opened, last command sent, session settings, and SSL status.

- [pg_stat_activity](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW)
- sys.sessions?
- ?

**Comment by amotl** [comment]
Hi Hernan,

I like the idea. Is there any blueprint for that, for example how PostgreSQL does it?

With kind regards,
Andreas.

**Comment by hlcianfagna** [comment]
> Is there any blueprint for that, for example how PostgreSQL does it?

Hi, yes, maybe this could be based on `pg_stat_activity`

**Comment by matriv** [comment]
Thank you for this feature request @hlcianfagna.
It has been implemented and will be available with 5.9 release.
