### ISSUE TITLE
Join engine improvements

### ISSUE THREAD

**Issue by mkleen** [crate/crate#14943]
- Add Sorted-Merge-Joins
- Add Group-Joins

References:
https://en.wikipedia.org/wiki/Sort-merge_join
https://link.springer.com/content/pdf/10.1007/s00778-022-00765-x.pdf
http://www.vldb.org/pvldb/vol4/p843-moerkotte.pdf

**Comment by mfussenegger** [comment]
Added the info to https://github.com/crate/crate/issues/13893

**Comment by mfussenegger** [comment]
Added the info to https://github.com/crate/crate/issues/13893
