### ISSUE TITLE
feature request - create table if not exists sql functionality 

### ISSUE THREAD

**Issue by duncanfbell** [crate/crate#1500]
It would be great if you could add "create table if not exists" functionality to allow for table creation script to be idempotent.  

I can work around by checking if the table exists in the information_schema, with something like "SELECT * FROM information_schema.tables WHERE table_name = 'crate' ;" but would be nice to do this check at table creation time.

Some other table querying/describing functionality would also come in useful I think such as "describe table crate;" and "show tables like 'crate';"

**Comment by chaudum** [comment]
hi @duncanfbell 
thanks for getting in contact. I'll put the items into our backlog and discuss it with the team.

**Comment by chaudum** [comment]
@duncanfbell 

for now you could use:
```sql
SELECT * FROM information_schema.tables WHERE schema_name = 'doc';
```
to retrieve the table names from your crate cluster.
and:

```sql
SELECT * FROM information_schema.columns WHERE table_name = 'crate';
SELECT * FROM information_schema.tables WHERE table_name = 'crate';
```
to retrieve information and columns/types from a table.

**Comment by seut** [comment]
the information_schema also supports `like` queries so I don't exactly understand the advantage of a `show tables` command.

**Comment by duncanfbell** [comment]
Ok thanks, I am aware I can use the information_schema to check if a table exists (see my original post?) I think the main argument for adding additional SQL functionality available in other popular relational databases (such as MySQL) to Crate, which is marketed as something to take some of the complications out of databases providing an easy to use SQL style front end, with a very advanced complicated replication/sharded backed "for free"... Adding some probably relatively easy to add normal every day use MySQL commands will make adopting Crate a lot easier for those used to working with MySQL every day.  Someone who has used MySQL on a day to day basis will probably agree that as soon as you get into a MySQL shell, you will have automatic commands you run to try and get your bearings and help navigate, such as "show tables" is normally something I will run immediately when entering a database.. so although there are alternative syntaxes available to produce the same result, these easy short statements are MySQL bread and butter and the type of market you are trying to attract, will probably expect them to exist.

Show tables also supports like queries - http://dev.mysql.com/doc/refman/5.0/en/show-tables.html

Anyway my main request was for "create table if not exists" which I guess could be handled with some kind of exception in my python code.  Is that would you would suggest for creation of tables which already exist, or trying to say insert a blob where the digest is already there?  My testing has been based on a pretty basic python script inserting a lot of data (45G) using os.walk to run through a file system, inserting the blob data and writing a reference table of to keep track of the blob digests.  This works fine, apart from if there is some random error which interrupts the script midway through (network blip or whatever) and then my script needs additional logic to check if the tables or blob data etc exists before trying to insert it.  I am obviously just looking for the easiest way to code this, so having built in methods to check things like this is advantageous for the EU.

Yes I can check if the table exists with something like ... select count(*) from information_schema.tables where table_name = 'table' and schema_name='doc' ; and then only create the table if a zero is returned.. and yes I can check whether to insert my blob data by checking the sha1sum and then doing a select statement against the blob table digest column to check whether to insert it, but some built ins would really take crate to another level with this type of behaviour.

**Comment by mfussenegger** [comment]
Create table if not exists definitely makes sense. It is something I've wanted
a couple of times myself already. But I guess it is a bit of a low priority
feature as it's easy to work around (catch exception as you mentioned).
Contributions would be very welcome.


Regarding the blob insert thing. I am not sure if I understand the issue there
correctly.  If you upload the same blob twice it will return 409 and I think
the python client will simply just return False on the upload method. So it
doesn't result in an exception anyway ?

**Comment by duncanfbell** [comment]
Thanks, I will have a look through you're code, i'm no Java developer, but can't hurt to look.

You're right about the blob insert thing, I just retested my script and it just loops through all the files to upload and doesn't error, or reupload, I just need better error handling to check the associated meta data table I use as running the the script just inserts duplicate results as expected.

**Comment by mfussenegger** [comment]
We'll have support for create table if not exists in the next feature release (0.50).

Can you file a separate issue for show tables if you're still interested  in that?

**Comment by duncanfbell** [comment]
Great thanks for that, I will open a new issue for show tables, as would be a nice short cut widely used in mysql without having to access the information_schema table.

**Comment by duncanfbell** [comment]
FYI https://github.com/crate/crate/issues/2000

Thanks again
