### ISSUE TITLE
Optimize joins to lookup joins if one relation is relative small

### ISSUE THREAD

**Issue by seut** [crate/crate#15003]
### Problem Statement

When joining 2 tables with a join condition, all rows for each tables are processed and then filtered by the join condition afterwards.
Such the underlaying collect operation will be a full table scan (if no further filters are defined).

Example query:
```
SELECT t1.id 
FROM t1
JOIN t2 
  ON t1.id = t2.id
```
Results in full table scans of `t1` and `t2`:
```
| QUERY PLAN                                         |
+----------------------------------------------------+
| Eval[id] (rows=unknown)                            |
|   └ HashJoin[(id = id)] (rows=unknown)             |
|     ├ Collect[doc.t1 | [id] | true] (rows=unknown) |
|     └ Collect[doc.t2 | [id] | true] (rows=unknown) |
+----------------------------------------------------+
```

If there is a large imbalance in size between the two tables and one of the table size is relatively small and the bigger table has an `INDEX` on the column used in the join condition, adding a filter to the large relation to match only rows contained in the second table can significantly improve performance as only a subset of rows of the larger relation is emitted, avoiding a complete table-scan.
This is afaik known as a lookup join.

Example:
```
SELECT t1.id 
FROM (
  SELECT id FROM t1 WHERE id = ANY(SELECT id FROM t2)
) t1
JOIN t2 
  ON t1.id = t2.id
```
Resulting plan:
```
+------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                               |
+------------------------------------------------------------------------------------------+
| Eval[id] (rows=unknown)                                                                  |
|   └ HashJoin[(id = id)] (rows=unknown)                                                   |
|     ├ Rename[id] AS t1 (rows=unknown)                                                    |
|     │  └ MultiPhase (rows=unknown)                                                       |
|     │    └ Collect[doc.t1 | [id] | (id = ANY((SELECT id FROM (doc.t2))))] (rows=unknown) |
|     │    └ OrderBy[id ASC] (rows=unknown)                                                |
|     │      └ Collect[doc.t2 | [id] | true] (rows=unknown)                                |
|     └ Collect[doc.t2 | [id] | true] (rows=unknown)                                       |
+------------------------------------------------------------------------------------------+
```

On a dataset with one table having 1_000_000 rows and the other 10_000 rows, a rough comparison indicates an improvement by ~10x.

<details>
<summary>Benchmarks</summary>

## Setup
```
CREATE TABLE t1 (id int);
CREATE TABLE t2 (id int);

INSERT INTO t1 (id) (SELECT b FROM generate_series(1, 1000000) a(b)); 
INSERT INTO t2 (id) (SELECT b FROM generate_series(1, 10000) a(b)); 
```

## Results
```
% echo 'SELECT t1.id FROM t1 JOIN t2 ON t1.id = t2.id ORDER BY 1 LIMIT 10;' | cr8 timeit --hosts localhost:4200
Runtime (in ms):
    mean:    8533.710 ± 54.553
    min/max: 8234.485 → 9684.405
Percentile:
    50:   8456.683 ± 278.331 (stdev)
    95:   9057.346
    99.9: 9684.405
```
```
% echo 'SELECT t1.id FROM (SELECT id FROM t1 WHERE id = ANY(SELECT id FROM t2)) t1 JOIN t2 ON t1.id = t2.id ORDER BY 1 LIMIT 10;' | cr8 timeit --hosts localhost:4200
Runtime (in ms):
    mean:    974.375 ± 6.049
    min/max: 930.558 → 1094.588
Percentile:
    50:   967.506 ± 30.860 (stdev)
    95:   1034.499
    99.9: 1094.588
```

</details>

The smaller the imbalance between the 2 tables is, the less improvements can be archived by this optimization. Additional, this may hit storage engine (in our case Lucene) limitations on how much clauses can be used, see https://cratedb.com/docs/crate/reference/en/5.4/config/node.html#indices-query-bool-max-clause-count.

Relates to #14820 and #11183.

### Possible Solutions

Implement an optimizer rule to convert joins into lookup joins when there is a large imbalance in size between the two tables.

### Considered Alternatives

Rewrite the query manually.

**Comment by vamsikrishnacse** [comment]
Hi @seut It looks like a good optimization to do with respective join operation. I am new to open source. can you please give me a push about how to get started and make it done. I am new to open source this will help me a lot.

**Comment by vamsikrishnacse** [comment]
@seut  in the process of writing optimization rule for the lookup join it have tried to execute the different formats of the lookup query (which are small changes itself to the query) that you have given ,where the query has given same time of execution as shown in below photos.


The original  :   
`    echo 'SELECT t1.id FROM (SELECT id FROM t1 WHERE id = ANY(SELECT id FROM t2)) t1 JOIN t2 ON t1.id = t2.id ORDER BY 1 LIMIT 10;' | cr8 timeit --hosts localhost:4200`

          100 requests [00:01, 60.06 requests/s]
          Runtime (in ms):
              mean:    15.405 ± 0.134
              min/max: 14.600 → 18.944
          Percentile:
              50:   15.315 ± 0.683 (stdev)
              95:   16.581
              99.9: 18.944

other two formats:
          `echo 'SELECT t1.id FROM t1 JOIN t2 ON t1.id = t2.id WHERE t1.id IN (SELECT id FROM t2) ORDER BY 1 LIMIT 10;' | cr8 timeit --hosts localhost:4200`


      100 requests [00:01, 58.62 requests/s]
      Runtime (in ms):
          mean:    15.636 ± 0.196
          min/max: 14.797 → 23.518
      Percentile:
          50:   15.412 ± 1.001 (stdev)
          95:   16.942
          99.9: 23.518

`echo 'SELECT t1.id FROM t1 JOIN t2 ON t1.id = t2.id WHERE t1.id = ANY(SELECT id FROM t2) ORDER BY 1 LIMIT 10;' | cr8 timeit --hosts localhost:4200`

        100 requests [00:01, 61.03 requests/s]
        Runtime (in ms):
            mean:    15.130 ± 0.081
            min/max: 14.648 → 16.469
        Percentile:
            50:   14.979 ± 0.414 (stdev)
            95:   15.970
            99.9: 16.469


and the optimization rule is where i am trying to read the source code where to include. Here is the pseudo code for lookup join i am looking at with respective the size of two tables:

```
function convertToLookupJoin(original_query):
    if original_query is of the form "SELECT ... FROM t1 JOIN t2 ON t1.id = t2.id ..."
        and join condition is based on equality (t1.id = t2.id)
        and query includes ORDER BY and LIMIT clauses
    then
        size_t1 = getTableSize("t1")
        size_t2 = getTableSize("t2")

        if size_t1 > size_t2 and size_t1 / size_t2 > size_threshold
            transformed_query = "SELECT ... FROM (SELECT id FROM t1 WHERE id = ANY(SELECT id FROM t2)) t1 JOIN t2 ON t1.id = t2.id ..."
            preserve ORDER BY and LIMIT clauses in transformed_query
            return transformed_query
        else if size_t2 > size_t1 and size_t2 / size_t1 > size_threshold
            transformed_query = "SELECT ... FROM (SELECT id FROM t2 WHERE id = ANY(SELECT id FROM t1)) t2 JOIN t1 ON t2.id = t1.id ..."
            preserve ORDER BY and LIMIT clauses in transformed_query
            return transformed_query

    return the original query
```

**Comment by seut** [comment]
@vamsikrishnacse
Your are right, the optimization can be also achieved by adding the filter directly to the query.
I'd slightly favor my initial query as it would replace the relation with a sub-select, this will ensure that the filter will be applied on the table collect operation itself. 
When adding a filter to the original query, pushing down this filter to the relevant relation (and thus eventually on the collect operation) depends on other optimizations rules to be applied. I think this would be much simpler to implement, maybe worth doing as the first iteration.

Implementation wise, we'd create a dedicated optimizer rule to achieve this optimization.
The `RewriteNestedLoopJoinToHashJoin` is a good and simple example of such a rule. I think all rules are worth reading to dive into this topic, see https://github.com/crate/crate/tree/master/server/src/main/java/io/crate/planner/optimizer/rule.

**Comment by mfussenegger** [comment]
Limited variant is implemented with https://github.com/crate/crate/pull/15664

But it only works for:

```
Join
 ├ Collect
 └ Collect
```

- It keeps the join.
- Doesn't work if there are other operators between the join and collect (or with Get/ForeignCollect).


Possible improvements going forward:

- [ ] Lift the concrete Collect restrictions; Should work with any child operators
- [ ] Replace the `applyOptimization` condition. E.g. rule could always apply, and then a cost model decides which variant is used.
- [ ] Drop the parent join if only outputs from one side are used
- [ ] Add a runtime query/bloom-filter push-down . This is complementary and could be used if the rule isn't used.
