### ISSUE TITLE
REGEXP_MATCHES not working on generated columns

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#15077]
### CrateDB version

5.5.0

### CrateDB setup information

Number of nodes: 3

### Problem description

I got a use case where it would be useful to have a generated column with an expression involving `REGEXP_MATCHES`, this does not seem to be working.

### Steps to Reproduce

```sql
CREATE TABLE hernan.test  (
	a TEXT,
	b ARRAY(TEXT) GENERATED ALWAYS AS regexp_matches(a, '(a(.+)z)')
	);
	
INSERT INTO hernan.test (a) 
SELECT 'alcatraz';
```

### Actual Result

0 records affected

### Expected Result

1 record affected

**Comment by hlcianfagna** [comment]
> Would for your use case a regexp_match like the following also work?

Hi, yes, that would have worked. JFYI for the specific use case I had in hand I worked around the issue with an alternative expression with `split_part`, but it could be useful to have this for the future.

**Comment by mfussenegger** [comment]
> > Would for your use case a regexp_match like the following also work?
> 
> Hi, yes, that would have worked. JFYI for the specific use case I had in hand I worked around the issue with an alternative expression with `split_part`, but it could be useful to have this for the future.

I created a dedicated issue: https://github.com/crate/crate/issues/15117
