### ISSUE TITLE
ANALYZE not throttled by `max_bytes_per_sec` configuration

### ISSUE THREAD

**Issue by karynzv** [crate/crate#15072]
### CrateDB version

5.3.3

### CrateDB setup information

CR1 - 3 node cluster
Related settings as below:
`max_bytes_per_sec = 40mb`
`settings['stats']['service']['interval'] = 24h`

Regarding the `pg_stats` table:
```
SELECT schemaname, count(*) FROM pg_catalog.pg_stats GROUP BY schemaname LIMIT 100;                                                                                                                             
+------------+----------+
| schemaname | count(*) |
+------------+----------+
| doc        |     1238 |
+------------+----------+
```

### Problem description

Whenever the automated `ANALYZE` runs, it goes over the 40mb/s as stablished by the default configuration of `max_bytes_per_sec`.

### Steps to Reproduce

This was observed on a production cluster but we didn't manage to reproduce yet.

### Actual Result

Whenever the `ANALYZE` is automatically triggered the cluster goes beyond the 40mb limit
<img width="876" alt="image (1)" src="https://github.com/crate/crate/assets/4229270/71cb4e3e-85ee-43d9-9891-1d2dc94ec83e">

_edit: this cluster stores ~3 TiB (i.e. 1.5 TiB in primaries) and apparently reads through he complete volume in an `ANALYZE` run_

### Expected Result

The throttling configuration should be enforced for the `ANALYZER` preserving other queries responsiveness.

**Comment by mfussenegger** [comment]
I had a look at this, but as far as I can tell the throttle mechanism is generally working.

You can observe this by using different values. For example, in my tests the duration decreased each time I increased the `max_bytes_per_sec`:

I cleaned the fs cache after each run with `echo 3 | sudo tee /proc/sys/vm/drop_caches`

```
cr> set global stats.service.max_bytes_per_sec = '5mb';
SET OK, 1 row affected (0.053 sec)
cr> analyze;
ANALYZE OK, 1 row affected (22.300 sec)


cr> set global stats.service.max_bytes_per_sec = '10mb';
SET OK, 1 row affected (0.019 sec)
cr> analyze;
ANALYZE OK, 1 row affected (11.781 sec)


cr> set global stats.service.max_bytes_per_sec = '20mb';
SET OK, 1 row affected (0.021 sec)
cr> analyze;
ANALYZE OK, 1 row affected (6.389 sec)
```


I made some changes that should reduce the amount of disk hits, and it should make the throttle work a bit more accurately: https://github.com/crate/crate/pull/15078
But that change probably won't be backported.

**Comment by proddata** [comment]
> I had a look at this, but as far as I can tell the throttle mechanism is generally working.

The original post clearly indicates that the throttle mechanism is not functioning as expected.

**Comment by mfussenegger** [comment]
> > I had a look at this, but as far as I can tell the throttle mechanism is generally working.
> 
> The original post clearly indicates that the throttle mechanism is not functioning as expected.

Can you provide minimal reproduction steps then?

**Comment by proddata** [comment]
> > > I had a look at this, but as far as I can tell the throttle mechanism is generally working.
> > 
> > 
> > The original post clearly indicates that the throttle mechanism is not functioning as expected.
> 
> Can you provide minimal reproduction steps then?

It is a bit hard to reproduce this with a minimal example, when it isn't even documented what `ANALYZE` really does or what could affect it's performance. So is it expected, that `ANALYZE` reads > 1 - 2 TiB from disk every day with a cluster ~ storing 3 TiB of data (i.e. roughly 1.5 TiB primaries)?

**Comment by mfussenegger** [comment]
Okay, so what I could verify is that reads on the disks don't correspond to the "application" reads.
The bytes/s rate limit is applied to how the analyze is accessing the values. But disk reads are at a lower level - and how exactly depends on the `store.type` of a table. E.g. for `mmap` the kernel takes care of the file access. Then there's disk page sizes, compression, etc. both which can translate a 1 byte lookup, into a much higher disk read value.

To apply a rate limit closer at the source we'd probably have to wrap the `IndexInput`, but I'm not aware of an easy way to do that.

**Comment by mfussenegger** [comment]
Closing this as the throttle is generally working. https://github.com/crate/crate/pull/15087 should also reduce the number of disk reads.

**Comment by seut** [comment]
> Okay, so what I could verify is that reads on the disks don't correspond 1:1 to the "application" reads. The bytes/s rate limit is applied to how the analyze is accessing the values. But disk reads are at a lower level - and how exactly depends on the `store.type` of a table. E.g. for `mmap` the kernel takes care of the file access. Then there's disk page sizes, compression, etc. both which can translate a 1 byte lookup, into a much higher disk read value.

Maybe worth adding a note related to this to the documentation of the `max_bytes_per_sec` setting?
