### ISSUE TITLE
Update portion of UPSERT statement not working against partitioned tables

### ISSUE THREAD

**Issue by AncilHumph** [crate/crate#15084]
### CrateDB version

4.8.4

### CrateDB setup information

No special configuration that I've identified. Reproduced on the following environments:

3-node cluster running in Docker on AWS EC2
1-node instance running in Docker in WSL Ubuntu

### Problem description

The Update portion of and UPSERT statement is not working against partitioned tables.  Works fine against non-partitioned tables.

This doesn't seem to be an issue in version 3.3.5.

### Steps to Reproduce

```
-- Non-Partitioned Test (works correctly)
CREATE TABLE IF NOT EXISTS non_partitioned_source_table ( 
	id STRING,
	partition STRING,
	name STRING,
	PRIMARY KEY (id, `partition)`
);
CREATE TABLE IF NOT EXISTS non_partitioned_destination_table ( 
	id STRING,
	partition STRING,
	name STRING,
	PRIMARY KEY (id, partition)
);

insert into non_partitioned_source_table values(1,'2000','George');
insert into non_partitioned_source_table values(2,'2001','Frank');

-- Reports 2 records affected after initial INSERTs are made
insert into non_partitioned_destination_table
select *
from non_partitioned_source_table
on conflict(id, partition) do update set
	name = excluded.name;

drop table if exists non_partitioned_source_table;
drop table if exists non_partitioned_destination_table;


-- Partitioned Test (works incorrectly)
CREATE TABLE IF NOT EXISTS partitioned_source_table ( 
	id STRING,
	partition STRING,
	name STRING,
	PRIMARY KEY (id, partition)
)
PARTITIONED BY (partition);
CREATE TABLE IF NOT EXISTS partitioned_destination_table ( 
	id STRING,
	partition STRING,
	name STRING,
	PRIMARY KEY (id, partition)
)
PARTITIONED BY (partition);

insert into partitioned_source_table values(1,'2000','George');
insert into partitioned_source_table values(2,'2001','Frank');

-- Reports 0 records affected after initial INSERTs are made
insert into partitioned_destination_table
select *
from partitioned_source_table
on conflict(id, partition) do update set
	name = excluded.name;

drop table if exists partitioned_source_table;
drop table if exists partitioned_destination_table;
```

### Actual Result

The UPSERT reports 0 records affected (and no records were updated).

### Expected Result

The UPSERT reports n records affected (and records were actually updated).

**Comment by mfussenegger** [comment]
The given example seems to work fine for me, both on 5.5 and 4.8.4

But you'd need to run a `refresh partitioned_source_table` after the inserts, to ensure the records are visible for the select part of the `insert into`.

**Comment by AncilHumph** [comment]
I tried adding REFRESH TABLE commands before the UPSERT and that didn't change the outcome.  No matter how many times you run the UPSERT, it always reports that 2 rows were affected?

**Comment by AncilHumph** [comment]
I know that you haven't confirmed my first issue yet but I've found another one.  Using my sample code, if you modify the UPSERT to explicitly list columns, it will also sometimes not update any records.  For instance if I run this:

```
insert into partitioned_destination_table (id, partition, name)
select id, partition, name
from partitioned_source_table
on conflict(id, partition) do update set
	name = excluded.name;
```

It will update 0 records.  But if I change it to this:

```
insert into partitioned_destination_table (id, name, partition)
select id, name, partition
from partitioned_source_table
on conflict(id, partition) do update set
	name = excluded.name;
```

It tells me 2 records were updated, which is what I expect.  The difference between the two queries is the order of the columns.  The first query lists them in the order that I declared them.  The second query lists them by their ordinal position in the table. This is an issue in both Crate 3.3.5 and 4.8.4.

**Comment by AncilHumph** [comment]
We are trying to upgrade to more recent versions (https://community.cratedb.com/t/cluster-checks-failing-recreate-tables/1019).  However, re-creating tables in order to do so has been very problematic for us as we have a very large and active production environment.  We've created a process to do so, and were originally trying to use UPSERTs to push data from the old tables to the new, but then discovered these issues.

**Comment by hlcianfagna** [comment]
I understand, it is always best to be careful when planning major version upgrades on large production environments. Would you like to have a call with us to discuss this? just in case there may be points you may have missed and alternative approaches we may suggest? https://meetings.hubspot.com/niklas-schmidtmer/talk-to-cratedb

**Comment by mfussenegger** [comment]
Closing this as it seems the problem was 4.8 related and fixed in later versions.

If this is incorrect and the issue still occurs on the latest versions please let us know.
