### ISSUE TITLE
Include shard/partition information in `EXPLAIN ANALYZE` output

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#15101]
### Problem Statement

When debugging performance issues, the `EXPLAIN ANALYZE` output is typically investigated. One of the questions regularly is to understand which partitions or shards have been accessed, for example, to validate if the `WHERE` condition filtered partitions correctly.

Currently, the node ID is shown in the `EXPLAIN ANALYZE` output, but no partition ident or shard ID.

### Possible Solutions

Include the shard ID and partition ident for each operation. The table name can also be relevant in case of dealing with multiple tables in one query (JOINs).

```json
  {
      "QueryDescription": "timestamp:[-9223372036854775808 TO 1700611199000]",
      "Time": 0.008078,
      "PartitionIdent": "04732dpg60qj4d1o60o30c1g",
      "ShardID": 1,
      "TableName": "abc",
      "BreakDown": {
          "match_count": 0,
          "shallow_advance_count": 0,
          "next_doc": 0,
          "match": 0,
          "next_doc_count": 0,
          "score_count": 0,
          "compute_max_score_count": 0,
          "compute_max_score": 0,
          "advance": 0,
          "advance_count": 0,
          "score": 0,
          "build_scorer_count": 23,
          "create_weight": 0.000147,
          "shallow_advance": 0,
          "create_weight_count": 1,
          "build_scorer": 0.007907
      },
      "QueryName": "IndexOrDocValuesQuery"
  }
```

### Considered Alternatives

Not adding additional information 🙂

**Comment by hlcianfagna** [comment]
Workaround: look at the number of elements in the `QueryBreakdown` array, there will be one for each shard accessed, for instance for a table `CLUSTERED INTO 4 SHARDS` with a query hitting 2 partitions the  `QueryBreakdown` array output by `EXPLAIN ANALYZE` will have 8 elements.
