### ISSUE TITLE
Improve three-valued-logic handling for scalar functions

### ISSUE THREAD

**Issue by mkleen** [crate/crate#15122]
Let's define three categories of functions:

- Nullable, this means `NULL` -> `NULL`. We can optimize this case with an additional field exist check query.
- Non-Nullable, this means the function never returns `NULL`. We can use a not-query in that case, without applying 3vl and without applying the field's exist check. 
- Conditional, this means the input `NULL` might result in `NULL`, but it might not. We need to use strict 3vl for them.

Using the feature property we already have might work.

Follow up https://github.com/crate/crate/pull/15104#pullrequestreview-1755171524

**Comment by hlcianfagna** [comment]
> I think this kind/category/behaviour description should become part of the function somehow

FWIW, PostgreSQL has the `proisstrict` flag in `pg_proc`
