### ISSUE TITLE
Inconsistent Results executing multiple statements at once

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15199]
### CrateDB version

5.5.1

### CrateDB setup information

I built crate myself and ran it in docker container, here's the version: `CrateDB 5.6.0-SNAPSHOT (built 76e7ee0/NA, Linux 5.15.0-67-generic amd64, OpenJDK 64-Bit Server VM 21.0.1+12-LTS)`. I could also reproduce it on the latest docker image (5.5.1). I ran with the command `docker run --publish 4200:4200 --publish 5432:5432 crate:latest -Cdiscovery.type=single-node`

### Problem description

I have a question about the following situation:

```sql
cr> DROP TABLE IF EXISTS t1;
    CREATE TABLE t1( c1 INT, PRIMARY KEY(c1));
    INSERT INTO t1 (c1) VALUES (0);

    SELECT * FROM t1;
    SELECT * FROM t1 WHERE t1.c1=0;
    SELECT * FROM t1;
DROP OK, 1 row affected (0.012 sec)
CREATE OK, 1 row affected (0.033 sec)
INSERT OK, 1 row affected (0.001 sec)
+----+
| c1 |
+----+
+----+
SELECT 0 rows in set (0.000 sec)
+----+
| c1 |
+----+
|  0 |
+----+
SELECT 1 row in set (0.010 sec)
+----+
| c1 |
+----+
+----+
SELECT 0 rows in set (0.000 sec)
cr> SELECT * FROM t1;
 
+----+
| c1 |
+----+
|  0 |
+----+
SELECT 1 row in set (0.001 sec)
```

If I execute the queries together with the DDL/DML statements, I'll get unexpected results as shown above: the `SELECT * FROM t1` returns nothing and `SELECT` with a filter returns one row (sometimes also return nothing). However, if I executed the queries separately, I'd get the expected results: the `SELECT * FROM t1` return a row.

Things are similar when using postgres wire protocol (I guess also in JDBC): 

```sql
psql (15.2 (Ubuntu 15.2-1.pgdg22.04+1), server 14.0)
Type "help" for help.

crate=> DROP TABLE IF EXISTS t1;
CREATE TABLE t1( c1 INT, PRIMARY KEY(c1));
INSERT INTO t1 (c1) VALUES (0);

SELECT * FROM t1;
SELECT * FROM t1 WHERE t1.c1=0;
SELECT * FROM t1;
DROP 0
CREATE 1
INSERT 0 1
 c1 
----
(0 rows)

 c1 
----
  0
(1 row)

 c1 
----
(0 rows)

crate=> SELECT * FROM t1;
 c1 
----
  0
(1 row)
```

Kindly let me know if you could reproduce or if I misunderstood/ignored something about crate.

### Steps to Reproduce

As described in the above section.

### Actual Result

Empty table for `SELECT * FROM t1` when executing queries at once.

### Expected Result

Same as when executed separately.

**Comment by seut** [comment]
This looks like related to the [eventually consistency](https://cratedb.com/docs/crate/reference/en/5.5/concepts/resiliency.html#storage-and-consistency) nature of CrateDB. A `SELECT` query which is not using a equality filter on all primary keys (like e.g. `SELECT ... FROM my_table WHERE pk_col = <val>`) is not guaranteed to return all recent written rows. To ensure this, a `REFRESH` must be issued before a  `SELECT` statement.
See also https://cratedb.com/docs/crate/reference/en/5.5/general/dql/refresh.html and https://cratedb.com/docs/crate/reference/en/5.5/sql/statements/refresh.html.
