### ISSUE TITLE
Join optimizations when sources are empty

### ISSUE THREAD

**Issue by mkleen** [crate/crate#15207]
If a logical plan returns 0 rows, the plan can be replaced by an empty relation. An empty relation is a placeholder which represents a logical plan without any rows and the underlying plan will be removed e.g.:

```
Limit[0]
  └ Collect[doc.t1 | [a] | true]  
```
The limit is 0, therefore this plan will never return any rows. The result of the Collect operation is not used, therefore we can convert the plan to an empty relation. This transformation has the benefit that unnecessary operations are avoided and the logical plan is simplified so it can be further optimized. An area where this concept can cause significant improvements is joins, to avoid unnecessary operations. If the underlying sources of a join are empty the following optimizations can be applied:

1. if one side of a cross/inner join is empty, the join result is also empty, and then the join can eliminated with an empty relation:

  ```
  Join[INNER | (a = b)]
    ├ Collect[doc.t1 | [a] | true] (rows=0)
    └ Collect[doc.t2 | [b] | true] (rows=100) 
  ``` 
or  
```  
Join[CROSS]
  ├ Collect[doc.t1 | [a,b] | true] (rows=0)
  └ Collect[doc.t2 | [b,c] | true] (rows=100)    
```

2. If the left side of a left-outer-join is empty, the join result is also empty, then the join can be eliminated with an empty relation:

```
Join[LEFT | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=0)
  └ Collect[doc.t2 | [b] | true] (rows=100)  
```  

3.  If the right side of a right-outer-join is empty, the join result is also empty, then the join can be eliminated with an empty relation:

```
Join[RIGHT | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=100)  
  └ Collect[doc.t2 | [b] | true] (rows=0)  
```  

4. if both sides of a full join are empty, the join result is also empty, then the join can be eliminated with an empty relation:

```
Join[FULL | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=0)  
  └ Collect[doc.t2 | [b] | true] (rows=0)  
```

5. if the right side of a left-outer or full join is empty, the join can be eliminated with a projection with the left side columns and the right side columns replaced with null values:

```
Join[RIGHT | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=100)  
  └ Collect[doc.t2 | [b] | true] (rows=0)   
```
  
or

```  
Join[FULL | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=100)  
  └ Collect[doc.t2 | [b] | true] (rows=0)    
```
  
becomes:  

```  
Eval[a, null]
  └ Collect[doc.t1 | [a] | true]
```

6. if the left side of a right-outer join is empty, the join can be eliminated with a Projection with right side columns and left side columns replaced with null values:

```
Join[RIGHT | (a = b)]
  ├ Collect[doc.t1 | [a] | true] (rows=0)  
  └ Collect[doc.t2 | [b] | true] (rows=100)   
```

becomes:  

```
Eval[null, b]
  └ Collect[doc.t2 | [b] | true]
```
    

Reference:
https://github.com/apache/arrow-datafusion/blob/main/datafusion/optimizer/src/propagate_empty_relation.rs

**Comment by JanaganSaravanan** [comment]
Hi! Is this issue still open ? If it is, I would like to work on this. Thanks

**Comment by mkleen** [comment]
> Hi! Is this issue still open ? If it is, I would like to work on this. Thanks

Hello, 

yes, this issue is still open, but it's not estimated yet. This means complexity and impact are not defined yet. If you are looking for a good first task, I recommend picking one of these https://github.com/crate/crate/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by JanaganSaravanan** [comment]
Thank you, I will look into it.

**Comment by mfussenegger** [comment]
I don't think this optimization is safe to do. The stats can be outdated. Optimizer rules should only affect execution time but never change the results a user gets.
