### ISSUE TITLE
Unexpected result when Concatenating NULL

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15202]
### CrateDB version

CrateDB 5.6.0-SNAPSHOT built 76e7ee0

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The third `SELECT` returns a non-empty result, which is surprising, given that the result of second query is `NULL`. The value of the expression should be `NULL`, and thus the third query should return an empty result.

I built crate myself and run it in docker container, here's the version: `CrateDB 5.6.0-SNAPSHOT (built 76e7ee0/NA, Linux 5.15.0-67-generic amd64, OpenJDK 64-Bit Server VM 21.0.1+12-LTS)`. Things work well on the latest docker image (5.5.1)

### Steps to Reproduce

```sql
CREATE TABLE t1(c0 INTEGER);
INSERT INTO t1 (c0) VALUES (NULL);
REFRESH TABLE t1;

SELECT * FROM t1; -- NULL
SELECT t1.c0!=(1||t1.c0) FROM t1; -- NULL
SELECT * FROM t1 WHERE (t1.c0!=(1||t1.c0)); 
-- Expected: Empty
-- Actual: NULL
```

### Actual Result

NULL

### Expected Result

empty table

**Comment by jeeminso** [comment]
Thank you a lot for reporting bugs from `master` branch. This is fixed by #15229.
