### ISSUE TITLE
Unexpected result when using BETWEEN AND

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15201]
### CrateDB version

CrateDB 5.6.0-SNAPSHOT built 76e7ee0

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The third `SELECT` returns an empty result, which is surprising, given that the result of second query is `TRUE`. The value of the `BETWEEN` expression should always be true, and thus the third query should return the whole table.

I built crate myself and run it in docker container, here's the version: `CrateDB 5.6.0-SNAPSHOT (built 76e7ee0/NA, Linux 5.15.0-67-generic amd64, OpenJDK 64-Bit Server VM 21.0.1+12-LTS)`. I could not reproduce it on the latest docker image (5.5.1)

### Steps to Reproduce

```sql
CREATE TABLE t0(c0 BOOLEAN);
INSERT INTO t0 (c0) VALUES (true);
REFRESH TABLE t0;

SELECT * FROM t0; -- true
SELECT t0.c0 BETWEEN true AND t0.c0 FROM t0; -- true
SELECT * FROM t0 WHERE (t0.c0 BETWEEN true AND t0.c0);
-- Expected: true
-- Actual: empty
```

### Actual Result

empty table

### Expected Result

true

**Comment by jeeminso** [comment]
Thank you for identifying this bug and reporting @suyZhong . This is a regression introduced in `5.6`. 

The scenario can be reduced to:
```
cr> select * from t0 where c0 >= true;                                                                                                      
+----+
| c0 |
+----+
+----+
SELECT 0 rows in set (0.441 sec)
```
Or similarly:
```
cr> select * from t0 where c0 <= false;                                                                                                     
+----+
| c0 |
+----+
+----+
SELECT 0 rows in set (0.009 sec)
```
