### ISSUE TITLE
UPDATE statement not honouring WHERE NOT EXISTS filter when used in conjunction with a filter on PK

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#15282]
### CrateDB version

5.5.2 and nightly-5.6.0-2024-01-05-00-02

### CrateDB setup information

`-Cdiscovery.type=single-node`

### Problem description

Originally reported by jiren on https://community.cratedb.com/t/bug-with-update-statement-using-subselect/1684

The `UPDATE` statement below updates a row it should not. This is only reproducible in the presence of a PK.

### Steps to Reproduce

```sql
CREATE TABLE f2 (id integer primary key, column1 text);

INSERT INTO f2 VALUES (2, '456'), (10, '123');

UPDATE f2
SET column1 = '123'
WHERE id = 2
AND NOT EXISTS (
    SELECT 1
    FROM f2
    WHERE column1 = '123'
);
```

(thanks @hammerhead )

### Actual Result

Updates the row with ID 2

### Expected Result

No rows updated.

**Comment by mfussenegger** [comment]
Thanks for the report. This should be fixed with https://github.com/crate/crate/pull/15293
