### ISSUE TITLE
Performance Regression on UNION benchmark

### ISSUE THREAD

**Issue by mkleen** [crate/crate#15294]
The query `select id, name from articles union all select id, name from colors limit 100000` from `union.toml` has a [performance regression](https://tools.cr8.net/grafana/d/E80m4pn7z/cratedb-benchmarks?orgId=1&var-spec_file=union.toml&var-statement=select%20id,%20name%20from%20articles%20union%20all%20select%20id,%20name%20from%20colors%20limit%20100000&var-statement=select%20id,%20name%20from%20articles%20union%20all%20select%20id,%20name%20from%20colors%20union%20all%20select%20id,%20name%20from%20articles%20union%20all%20select%20id,name%20from%20colors%20order%20by%201,%202%20limit%20400000&var-statement=select%20id,%20name%20from%20articles%20union%20all%20select%20id,%20name%20from%20colors%20order%20by%201,%202%20limit%20100000&var-concurrency=1&from=now-30d&to=now):

![Image 08 01 24 at 14 51](https://github.com/crate/crate/assets/338234/c9bc9d72-77ca-493a-b2b9-eba581d89ed2)

**Comment by mfussenegger** [comment]
Does https://github.com/crate/crate/pull/15212 interfere with the fetch optimization and/or distributed execution?
