### ISSUE TITLE
Unexpected Result when using `IN` 

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15326]
### CrateDB version

CrateDB 5.6.0-SNAPSHOT built 5ff277c

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test cases below. It is unexpected that the third query returns empty result, since the second query returns `TRUE`, which means that the `WHERE` clause in the third query should be evaluated to `TRUE` and thus return the row in the table.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0(c0 VARCHAR, PRIMARY KEY(c0));
INSERT INTO t0 (c0) VALUES (true);
REFRESH TABLE t0;

SELECT * FROM t0; -- t
SELECT (t0.c0 IN (true)) FROM t0; -- TRUE
SELECT * FROM t0 WHERE (t0.c0 IN (true));
-- Expected: t
-- Actual:   empty result
```

### Actual Result

Empty

### Expected Result

t

**Comment by matriv** [comment]
Thx for reporting the issue @suyZhong, it has been fixed and will be available with the next hotfix release.
