### ISSUE TITLE
Unexpected Results Using `NULLIF` with `VARCHAR`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15325]
### CrateDB version

CrateDB 5.6.0-SNAPSHOT built 5ff277c

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The third `SELECT` returns one row (`null`), which is surprising, given that the result of second query is `null`. The value of the `NULLI((t0.c1), NULL))` expression is `null`, and thus the third query should return empty. 

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0( c1 VARCHAR(500));
INSERT INTO t0 (c1) VALUES (NULL);
REFRESH TABLE t0;

SELECT * FROM t0; -- null
SELECT (NOT NULLIF((t0.c1), NULL)) FROM t0; -- null
SELECT * FROM t0 WHERE (NOT NULLIF((t0.c1), NULL));
-- Expected: empty result
-- Actual:   null
```

### Actual Result

NULL

### Expected Result

Empty

**Comment by matriv** [comment]
This is a bug only on current master, tested with `5.5.2` and a correct result (empty) is returned.

**Comment by matriv** [comment]
@suyZhong Thx a lot for reporting the issue, it was applicable only for `master` and it has been fixed.
