### ISSUE TITLE
Fix issue with doc tests and precision descrepancy

### ISSUE THREAD

**Issue by matriv** [crate/crate#15385]
Seems that this doc test is failing on MacOS:
```
File "/Users/romseygeek/projects/crate-5.5/blackbox/docs/general/builtins/scalar-functions.rst", line 2040, in scalar-functions.rst
Failed example:
    cmd.process('select exp(1.0) AS exp')Expected:
    +-------------------+
    |               exp |
    +-------------------+
    | 2.718281828459045 |
    +-------------------+
    SELECT 1 row in set (... sec)
Got:
    +--------------------+
    |                exp |
    +--------------------+
    | 2.7182818284590455 |
    +--------------------+
    SELECT 1 row in set (0.000 sec)
```

postgres 16.1 on my linux returns:
```
matriv=> select exp(1.0) AS exp;
        exp         
--------------------
 2.7182818284590452
(1 row)

```
which rounds to ` 2.718281828459045`, so the linux version (what is currently committed in doc page) matches that.

**Comment by mfussenegger** [comment]
Doctest got ignored with: https://github.com/crate/crate/pull/15407

**Comment by matriv** [comment]
I didn't close it on purpose:
- discuss if we want to use `StrictMath.exp()` 
- find a nice way to skip doc tests without rendering the "ugly" inline comment on html

**Comment by matriv** [comment]
We decided to remove the crash prompt prefix (which denotes a docktest execution) https://github.com/crate/crate/pull/15427, instead of adding the "uggly" skip doctest comment.
