### ISSUE TITLE
Network traffic statistics monitoring

### ISSUE THREAD

**Issue by SStorm** [crate/crate#15391]
### Problem Statement

It is often very useful to know the amount of traffic that a CrateDB node has processed, for example for traffic accounting / billing purposes. The solutions offered by standard monitoring tools (i.e. exported from kubernetes) are often not granular enough.

It would be incredibly useful if CrateDB exported a counter for the total number of bytes processed, by protocol (http, psql, transport). CrateDB already exposes the number of connections from the `sys.nodes` table (i.e. `{"http":{"open":6,"total":36},"psql":{"open":4,"total":5},"transport":{"open":0}}`). 

### Possible Solutions

Extend `sys.nodes` to also offer the total number of bytes processed. This can be a counter using a long data type. When overflowing, it can wrap back to zero (note that this is not a problem for, i.e., prometheus, which handles counters like that).

**Comment by seut** [comment]
After asking more about the problem this should solve, I got this additional information:

> The problem is mainly around accounting cross-container traffic vs to the outside world - we cannot do this (at least, not easily). i.e. no way to distinguish CrateDB transport traffic between nodes from traffic going to the outside world

> We would want both inbound and outbound traffic stats, hope that's not an issue
> With outbound being by far more important.

@SStorm 
The outstanding question I still have: 
Is accounting traffic per protocol then enough as an indicator for inbound vs. outbound traffic? 
Feel fragile to me, especially when using inter-node communication which spawns across the provider boundary e.g. a multi-zone cluster or cluster connected via logical replication (both cases are using the transport protocol).

**Comment by SStorm** [comment]
@seut 

1. Transport protocol nearly always indicates cross zone traffic, we are fine with this.
2. Logical replication never uses the transport protocol in CrateDB Cloud - we always tunnel over pg, so that is not an issue either.

As far as CrateDB Cloud is concerned, pg/http traffic will nearly always indicate outbound traffic. Transport protocol traffic will always indicate cross-zone traffic for clusters of 3 or less nodes, and can be used to estimate cross-zone traffic for clusters with 3+ nodes, which is enough.

**Comment by seut** [comment]
@SStorm @proddata 
For your current use-case, is it enough to expose the traffic statistics via JMX?

**Comment by matriv** [comment]
It has been implemented with https://github.com/crate/crate/pull/15866

**Comment by matriv** [comment]
Jmx Exporter has been updated to expose the new metrics with: https://github.com/crate/jmx_exporter/pull/68

**Comment by proddata** [comment]
> Jmx Exporter has been updated to expose the new metrics with: [crate/jmx_exporter#68](https://github.com/crate/jmx_exporter/pull/68)

Thanks, will plan to test it asap 👍
