### ISSUE TITLE
Remove usages of Mockito

### ISSUE THREAD

**Issue by matriv** [crate/crate#15438]
Based on some short work and investigation to upgrade mockito to >= 5.x.x: https://github.com/crate/crate/pull/15170
It's better to first try and make the code more testable (for example introduce interfaces and implement them as anonymous classes in tests) and replace Mockito, at least where it's easy.

If there are still some remaining usages it will be easier to adapt them to use the new versions of Mockito.
For some more context Mockito >= 5 has changed the default policy for generating mock instances from `subclass` to `proxy` which breaks lots of our tests that use it, and to overcome this, we need to explicitly "ask" for `subclass` mocking.

**Comment by mfussenegger** [comment]
https://github.com/crate/crate/pull/15575 updated mockito to the latest version.

While reducing the amount of mocks we use is desirable and something we should aim for, I don't think it is reasonable to remove it entirely, as it makes some scenarios a lot easier to test than without using it.
