### ISSUE TITLE
Unexpected results when using `AND`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15458]
### CrateDB version

CrateDB 5.7.0-SNAPSHOT built 93ee46e

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Thanks for your effort for all the fixes!

Consider the test case below. It is unexpected that the third query returns empty result, since the second query returns `TRUE`, which means that the `WHERE` clause in the third query should be evaluated to `TRUE` and thus return the row in the table.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0(c0 VARCHAR, c1 INT, PRIMARY KEY(c0));
INSERT INTO t0 (c0, c1) VALUES ('a', 1);
REFRESH TABLE t0;

SELECT * FROM t0; -- a, 1
SELECT NOT ((t0.c0 NOT IN (''))AND(t0.c1!=t0.c1)) FROM t0; -- TRUE
SELECT * FROM t0 WHERE (NOT ((t0.c0 NOT IN (''))AND(t0.c1!=t0.c1)));
-- Expected: a, 1
-- Actual:   empty result
```

It seems like pretty similar to https://github.com/crate/crate/issues/15395? I guess the previous issue has fixed as the test case is working as expected now (on 93ee46e).

In case to better fix the issue, here's another test case which I think is due to the same root cause (`get` and `collect`?), but kindly lemme know if it's caused by another reason.

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c0 VARCHAR, PRIMARY KEY(c0));
INSERT INTO t0 (c0) VALUES ('a');
REFRESH TABLE t0;


SELECT t0.c0 FROM t0;  -- a
SELECT NOT ((t0.c0 != 'b')AND(t0.c0 = 'c')) FROM t0; -- TRUE
SELECT t0.c0 FROM t0 WHERE NOT ((t0.c0 != 'b')AND(t0.c0 = 'c'));
-- expected: a
-- actual: empty table
```

### Actual Result

As mentioned above

### Expected Result

As mentioned above

**Comment by jeeminso** [comment]
Thanks for reporting @suyZhong .

> It seems like pretty similar to https://github.com/crate/crate/issues/15395?

Yes they are supposed to due to the same cause. Initially I attempted to solve it elsewhere (but was reverted). This time the two reports should be handled by the same fix.
