### ISSUE TITLE
Regression on nightly: `The assembled list of ParameterSymbols is invalid. Missing parameters.`

### ISSUE THREAD

**Issue by amotl** [crate/crate#15488]
### CrateDB version

`crate/crate:nightly-5.7.0-2024-01-26-00-02`

### CrateDB setup information

Standard Docker.

### Problem description

Similar to GH-10897, the error message is:
```
(crate.client.exceptions.ProgrammingError)
IllegalStateException[The assembled list of ParameterSymbols is invalid. Missing parameters.]
[SQL: SELECT params.key AS params_key, params.value AS params_value, params.run_uuid AS params_run_uuid 
FROM params 
WHERE 
  params.run_uuid = ? AND 
  params.key = ? AND 
  params.value IS NULL 
LIMIT ?]
[parameters: ('ebda073e99424d038db20200dd37a06d', 'blahmetric', 1)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/7701685602/job/20989123294#step:6:799

It does not happen on all occasions, just in a very specific constellation, like demontrated within the reproducer gist. The error only happens when all conditions are satisfied, i.e. the statements MUST HAVE / USE / CONTAIN:

- DDL: A primary key constraint
- QUERY: Parameters for querying
- WHERE: A parameterized `LIMIT` clause
- WHERE: An `IS NULL` clause fragment on any column
- WHERE: At least one other parameterized query clause on any column

### Steps to Reproduce

On [mlflow-cratedb](https://github.com/crate-workbench/mlflow-cratedb), invoke this test case:
```
pytest -vvv -k test_log_null_param
```

Derived from that test case, there is also a [standalone reproducer gist](https://gist.github.com/amotl/268fab89f44e47daf251ae60173f92f7).

### Actual Result

The test case `test_log_null_param` of mlflow-cratedb started failing.

### Expected Result

The test case continues working, and doesn't break.

## Evaluation / Regression
With `crate/crate:5.6.1`, and subsequent nightly releases, everything was fine. Then, four days ago, that changed.

**Comment by jeeminso** [comment]
Hi @amotl sorry for the trouble I think https://github.com/crate/crate/pull/15468 should fix the problem, please help double check.

**Comment by amotl** [comment]
Hi. It looks like the issue is resolved already. When re-running a corresponding CI job that failed previously, it now signals success again. Thanks!

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/7701685602
