### ISSUE TITLE
Unexpected result when using `REPLACE`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15499]
### CrateDB version

CrateDB 5.7.0-SNAPSHOT built 571d6c6

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the second query returns `a`, because the result of the first query is `a`, and the predicate cannot be evaluated to `TRUE` or `NULL` at the same time. Thus, at least one of the two queries should return empty result.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c0 VARCHAR(500));
INSERT INTO t0 (c0) VALUES ('a');
REFRESH TABLE t0;

SELECT * FROM t0; -- 'a'
SELECT * FROM t0 WHERE (REPLACE(NULL, t0.c0, 'b')) != 'a'; -- 'a' (unexpected) 
SELECT * FROM t0 WHERE (((REPLACE(NULL, t0.c0, 'b')) != 'a') IS NULL); -- 'a'

-- Original test case:
SELECT * FROM t0 WHERE (NOT REPLACE(NULL, ((t0.c0) IS NULL), true)); -- 'a' (Unexpected)
SELECT * FROM t0 WHERE (((NOT REPLACE(NULL, ((t0.c0) IS NULL), true))) IS NULL); -- 'a'
```

### Actual Result

as mentioned above

### Expected Result

as mentioned above

**Comment by jeeminso** [comment]
Thanks for reporting, this is also fixed by https://github.com/crate/crate/pull/15514.
