### ISSUE TITLE
Unexpected result when using `LTRIM`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15498]
### CrateDB version

CrateDB 5.7.0-SNAPSHOT built 571d6c6

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the second query returns 0, because the result of the first query is 0, and the `LTRIM()` cannot be evaluated to `FALSE` or `NULL` at the same time. Thus, at least one of the two queries should return an empty result.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t1;

CREATE TABLE t1(c0 INT, PRIMARY KEY(c0));
INSERT INTO t1 (c0) VALUES (0);
REFRESH TABLE t1;

SELECT  t1.c0 FROM t1; -- 0
SELECT  t1.c0 FROM t1 WHERE LTRIM(NULL, t1.c0) IS NULL; -- 0 
SELECT  t1.c0 FROM t1 WHERE NOT LTRIM(NULL, t1.c0); -- 0 (unexpected)
```

### Actual Result

As mentioned above

### Expected Result

As mentioned above

**Comment by jeeminso** [comment]
Thanks for reporting, this is also fixed by https://github.com/crate/crate/pull/15514.
