### ISSUE TITLE
Table in secondary schema can shadow view in primary schema

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#15516]
### CrateDB version

master, but older versions are affected too

### CrateDB setup information

Single node.

### Problem description

`select * from t1` with `set search_path = a, b` will first search for a table in both a, and b, and then move on to views.

The correct behavior is to first check table and view in `a`, and then check table and view in `b`.

### Steps to Reproduce

```sql
create table b.t1 (x text);
insert into b.t1 (x) values ('table');
refresh table b.t1;

create view a.t1 as (select 'view');

set search_path = a, b;
select * from t1;
```

### Actual Result

table

### Expected Result

view

**Comment by jeeminso** [comment]
Thank you for reporting @mfussenegger. The fix will be available with the next hotfix release.
