### ISSUE TITLE
Notify pgwire clients about parameter changes using `ParameterStatus`

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#15577]
https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-ASYNC
> ParameterStatus messages will be generated whenever the active value changes for any of the parameters the backend believes the frontend should know about. Most commonly this occurs in response to a SET SQL command executed by the frontend

One of the parameter changes that the frontend should know about is on `datestyle` however I do not see  `ParameterStatus` generated from the code below:
```
Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/crate", "crate", "");
Statement stmt = conn.createStatement();
stmt.execute("set datestyle = 'dmy'");
```

Currently the effect is very minor since CrateDB only supports `iso` for `datestyle`. https://cratedb.com/docs/crate/reference/en/5.6/config/session.html

**Comment by mfussenegger** [comment]
Closing this for now - not a priority, no known use-case.

We can re-open this if a concrete case pops up
