### ISSUE TITLE
Unexpected result when using `OR`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#15592]
### CrateDB version

CrateDB 5.7.0-SNAPSHOT built 48bcbc7

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The third `SELECT` returns an empty result, which is surprising, given that the result of second query is `TRUE`. The value of the `WHERE` condition is `TRUE`, and thus the third query should return the whole table. 

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c0 VARCHAR, c1 BOOLEAN, PRIMARY KEY(c0)); -- PK is needed
INSERT INTO t0 (c0, c1) VALUES ('a', true);
REFRESH TABLE t0;

SELECT * FROM t0; -- 'a' TRUE
SELECT (t0.c1) OR (t0.c0 = 'b') FROM t0; -- TRUE
SELECT * FROM t0 WHERE (t0.c1) OR (t0.c0 = 'b');
-- Expected: 'a' TRUE
-- Actual: empty table
```

### Actual Result

Empty

### Expected Result

'a' TRUE

**Comment by matriv** [comment]
Thx a lot for reporting this issue @suyZhong, the fix will be available with the next hotfix release.
