### ISSUE TITLE
Add `reverse` scalar string function.

### ISSUE THREAD

**Issue by surister** [crate/crate#15625]
### Problem Statement

As per https://www.postgresql.org/docs/current/functions-string.html

`reverse(text) -> text`

Example:
`reverse("abcde") -> "edcba"`

`reverse("rotator") -> "rotator"`

This improves PostgreSQL compatibility and in my use case, Tableau.

**Comment by hlcianfagna** [comment]
Workaround:
```sql
CREATE FUNCTION reverse(str TEXT) 
RETURNS TEXT 
LANGUAGE JAVASCRIPT 
AS 'function reverse(str) {return str.split("").reverse().join("");}';
```
