### ISSUE TITLE
Add `strpos` scalar string function.

### ISSUE THREAD

**Issue by surister** [crate/crate#15624]
### Problem Statement

Add `strpos(string, substring) -> int` function, as it exists in PostgreSQL, see https://www.postgresql.org/docs/current/functions-string.html

Example:
`strpos('high', 'ig') -> 2`

`strpos('abracadabra', 'abra') -> 0`

This would improve PostgreSQL and in my use case, Tableau integration.

**Comment by DHRUV6029** [comment]
can i work on this?

**Comment by BaurzhanSakhariev** [comment]
Sure, assigned it to you

**Comment by DHRUV6029** [comment]
Hello, 
Just a small clarification, in postgresql the index starts from 1  strpos('abracadabra', 'abra') -> 0 will be 1 if you run in postgresql db , output will be 0 if there is no match.

so question is do we want to keep 0 indexed or 1 indexed?

**Comment by surister** [comment]
I'd favor postgres compatibility, but core team should advice

**Comment by DHRUV6029** [comment]
I am done with the impl , please let me know if we are to follow postgres compatibility or want to go with 0 index?

**Comment by BaurzhanSakhariev** [comment]
Let's do it PG compatible, 1 based and 0 for no match. 
Thanks!

**Comment by DHRUV6029** [comment]
ok

**Comment by matriv** [comment]
This has been closed by https://github.com/crate/crate/pull/15815
Thx again for the contribution @DHRUV6029 !
