### ISSUE TITLE
Add arithmetic `^` operator, ex: `2^3 = 8`

### ISSUE THREAD

**Issue by surister** [crate/crate#15630]
### Problem Statement

 I don't know if this is already tracked/mentioned somewhere, I couldn't find any reference.

Currently we support the scalar function `power(base, exponent)` but we do not have the inline operator `^` so
`select 2^3;` fails. [docs](https://cratedb.com/docs/crate/reference/en/5.6/general/builtins/arithmetic.html)

It [exists](https://www.postgresql.org/docs/current/functions-math.html) in PostgreSQL, so we can do stuff like:

```
select 0^2; -> 0
select 2^2^2^2; -> 65535
```

This breaks some required functionalities in Tableau.

**Comment by DHRUV6029** [comment]
Hi, Can i work on this issue?

**Comment by BaurzhanSakhariev** [comment]
> Hi, Can i work on this enhancement?

Hi, sure, assigned it to you

**Comment by DHRUV6029** [comment]
Hello , 
Just to Clarify , select 0^2; -> 1.  should be 0 not 1, I checked in  PostgreSQL it gives 0?

**Comment by BaurzhanSakhariev** [comment]
yes,  select 0^2 = 0

in general, 0^x = 0, x^0 = 1.

**Comment by surister** [comment]
> Hello , Just to Clarify , select 0^2; -> 1. should be 0 not 1, I checked in PostgreSQL it gives 0?

Yes, it's a typo my bad.

**Comment by BaurzhanSakhariev** [comment]
one exception - 0^0 is 1. 
It can be undefined in some software but at least it's like that in Postgres https://www.db-fiddle.com/f/drvR9EzyXrBcwgCi7XWbMv/0
