### ISSUE TITLE
Add `sign` function

### ISSUE THREAD

**Issue by surister** [crate/crate#15641]
### Problem Statement

To improve PostgreSQL compatibility add `sign (numeric) → numeric`.

Example:
`
select sign(123); -> 1
`
`
select sign(-4); -> -1
`
`
select sign(0); -> 0
`
`
select sign(null); -> null
`

**Comment by azatyamanaev** [comment]
Hello. Can I work on this issue?

**Comment by BaurzhanSakhariev** [comment]
> Hello. Can I work on this issue?

Hi, sure, assigned it to you.
