### ISSUE TITLE
Documentation feedback on /docs/config/cluster.rst

### ISSUE THREAD

**Issue by karynzv** [crate/crate#15676]
### Documentation feedback

The query `SET GLOBAL "stats.jobs_log_filter" = 'ended - started > 100';` should be updated to use the most recent interval notation. A fix option could be: `SET GLOBAL "stats.jobs_log_filter" = $$ended - started > '5 minutes'::interval$$;`

 
- Page title: Cluster-wide settings
- Page URL: https://cratedb.com/docs/crate/reference/en/latest/config/cluster.html
- Source: https://github.com/crate/crate/blob/5.6/docs/config/cluster.rst

---

**Comment by mfussenegger** [comment]
Thanks for pointing out. Fixing this with https://github.com/crate/crate/pull/15678
