### ISSUE TITLE
Incorrect results on VIEW with subquery, ORDER BY, and row_number

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#15709]
### CrateDB version

5.6.2 and nightly-5.7.0-2024-03-18-00-02

### CrateDB setup information

```
-Cdiscovery.type=single-node
--env CRATE_HEAP_SIZE=1g
```

### Problem description

Querying the view in the steps below filtering on a specific value for field1 returns results with a different value for field1.
Please note the view includes a subquery, an ORDER BY, and a call to row_number, all these 3 elements are superflous and not required, and removing any of those results on the problem not occurring anymore.

### Steps to Reproduce

```sql
CREATE TABLE t1 (ts TIMESTAMP,field1 TEXT,anumber DOUBLE);

INSERT INTO t1 (ts,field1,anumber) VALUES (now(),'abc',1.1);

CREATE VIEW v1
AS
SELECT field1,anumber
FROM (
	SELECT field1
		,row_number() OVER (PARTITION BY date_bin('1 day'::interval,ts, 0) ) "row_number"		
		,anumber
	FROM t1	 
	ORDER BY field1 
	) x;

SELECT * FROM v1 WHERE field1 = 'xyz';
```

### Actual Result

```
+--------+---------+
| field1 | anumber |
+--------+---------+
| abc    |     1.1 |
+--------+---------+
```

### Expected Result

Empty result set

**Comment by mfussenegger** [comment]
Thanks for the report, this should be fixed with https://github.com/crate/crate/pull/15714
