### ISSUE TITLE
-1 rows affected in crash

### ISSUE THREAD

**Issue by zopyx** [crate/crate#1570]
I have a table with id..0...100. Deleting all rows with id>10 works correct but crash seems to report a weird message of "-1 rows affected". This is wrong and misleading.

| 73 | 389017 |
| 74 | 405224 |
| 75 | 421875 |
| 76 | 438976 |
| 77 | 456533 |
| 78 | 474552 |
| 79 | 493039 |
| 80 | 512000 |
| 81 | 531441 |
| 82 | 551368 |
| 83 | 571787 |
| 84 | 592704 |
| 85 | 614125 |
| 86 | 636056 |
| 87 | 658503 |
| 88 | 681472 |
| 89 | 704969 |
| 90 | 729000 |
| 91 | 753571 |
| 92 | 778688 |
| 93 | 804357 |
| 94 | 830584 |
+----+--------+
SELECT 95 rows in set (0.069 sec)
cr> delete from test where id>10;
DELETE OK, -1 rows affected (0.034 sec)
cr> select * from test order by id;
+----+------+
| id | text |
+----+------+
|  0 |    0 |
|  1 |    1 |
|  2 |    8 |
|  3 |   27 |
|  4 |   64 |
|  5 |  125 |
|  6 |  216 |
|  7 |  343 |
|  8 |  512 |
|  9 |  729 |
| 10 | 1000 |
+----+------+
SELECT 11 rows in set (0.032 sec)

**Comment by chaudum** [comment]
Hi @zopyx 

The `DELETE` statement always returns `-1 rows affected`, because Crate does not have the information how many rows were affected. This is a limitation we have from Lucene.

We'll need to document this accordingly in our documentation.

Christian

**Comment by chaudum** [comment]
https://github.com/crate/crash/pull/50

**Comment by chaudum** [comment]
just merged the documentation into master: https://github.com/crate/crash/commit/ee41705304454105ac5d842c71285bfded2c8af5

the docs are available here: https://crate.io/docs/projects/crash/en/latest/cli.html#status-messages
