### ISSUE TITLE
CRATE_HEAP_SIZE config in crate.yml does not start service

### ISSUE THREAD

**Issue by abrilrob** [crate/crate#1571]
Crate version = 46.1 (in debian)
 
If I change crate.yml, adding "CRATE_HEAP_SIZE=10g" or "CRATE_MAX_MEM=10g" the service don't start.

I solved this in the /etc/init.d/crate file, changing "CRATE_MAX_MEM=${CRATE_MAX_MEM-1g}" to "CRATE_MAX_MEM=${CRATE_MAX_MEM-10g}".

**Comment by chaudum** [comment]
hi @robertoabril 
`CRATE_HEAP_SIZE` is actually an environment variable, and the crate init script takes that into account when starting. so you'd need to set it on the host:
```sh
export CRATE_HEAP_SIZE=10g
sudo service crate start
```
see https://crate.io/docs/en/latest/configuration.html#environment-variables
hope this helps!
