### ISSUE TITLE
Implement pg_catalog.pg_matviews

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#15750]
### Problem Statement

Some tools (see labels) run queries that look for this system view.

https://www.postgresql.org/docs/current/view-pg-matviews.html

### Possible Solutions

Implement it empty 

### Considered Alternatives

- For dbt --> use the overrides from https://community.cratedb.com/t/using-dbt-with-cratedb/1566

- [Metabase explicitly looks for the view under pg_catalog](https://github.com/metabase/metabase/blob/aab665719802f5b3871133c2761fb3f04b954d69/src/metabase/driver/postgres.clj#L893) 

```sql
CREATE TABLE pg_catalog.pg_matviews (
	schemaname TEXT,	matviewname TEXT,	matviewowner TEXT,
	tablespace TEXT,	hasindexes BOOLEAN,	ispopulated BOOLEAN,
	definition text	);
```
--> `SQLParseException[Cannot create relation in read-only schema: pg_catalog]`

---

- Relates to https://github.com/crate/crate/issues/10661

**Comment by julant7** [comment]
Hello @hlcianfagna!
I am very interested in this task. Can I take this on?

**Comment by seut** [comment]
@julant7 Sure, I've assigned it to you. Thank you!
