### ISSUE TITLE
`_raw` returns IDs instead of column names

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#15774]
### CrateDB version

5.6.3

### Problem description

Selecting `_raw` used to return column names in older versions, now it returns column IDs.

### Steps to Reproduce

```sql
CREATE TABLE a (b INTEGER);
INSERT INTO a VALUES (1);
SELECT _raw FROM a;
```

### Actual Result

5.6.3:
```
+-----------+
| _raw      |
+-----------+
| {"330":1} |
+-----------+
```

Older versions (e.g. 5.3):
```
+---------+
| _raw    |
+---------+
| {"b":1} |
+---------+
```

### Expected Result

```
+---------+
| _raw    |
+---------+
| {"b":1} |
+---------+
```

**Comment by jeeminso** [comment]
I cannot recall the reasoning but that is intentional. We have a test that validates `_raw` returning oids instead of column names, see https://github.com/crate/crate/blob/b0133fb8fb8156e205ca30a28040d115433bc2eb/server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java#L439-L442

**Comment by hammerhead** [comment]
Yes, I figured it might have been an intentional side-effect when switching to OIDs during the development of DROP COLUMN. In some situations, `_raw` was very handy as a simple way to get a JSON representation of a complete row. It's not directly breaking a significant use case for me, but thought I'd give it a try reporting to see if there is a chance to get it back.

**Comment by jeeminso** [comment]
I see, it looks like we are expected to use `_doc::string` to replace the old `_raw`, https://github.com/crate/crate/pull/14726#discussion_r1337256463.

**Comment by mfussenegger** [comment]
This is intentional and the format of `_raw` is in general considered an implementation detail. With https://github.com/crate/crate/issues/15548 it might even change further.
