### ISSUE TITLE
Add support for CoreOS Easy Development/Testing Cluster installation

### ISSUE THREAD

**Issue by wkharold** [crate/crate#1577]
The CoreOS docs describe an [Easy Development/Testing Cluster](https://coreos.com/docs/cluster-management/setup/cluster-architectures/#easy-development/testing-cluster) which uses a single *etcd* node and a larger collection of *worker* nodes. This setup avoids the need to get a new etcd discovery token every time you restart/reconfigure the cluster. 

Some minor changes are required of the cloud-config.yaml and crate.service unit file to work properly in this environment. The links below capture them.

[cloud-config.yaml](https://gist.github.com/wkharold/8c4aeaca252623d5aae0)
[crate@.service](https://gist.github.com/wkharold/094a37de336a18a34f2a)

Use of the crate@.service unit is as follows:
```console
$ fleetctl submit crate@.service
$ fleetclt start crate@1.service ... crate@N.service
```

**Comment by chaudum** [comment]
hi @wkharold 

thanks for pointing out this option.
we'll look into it and update the docs accordingly!

best, christian

**Comment by spanktar** [comment]
I have updated to docs to reference this on staging. I didn't change the page to use this new method, but I will add another section that does so we can show how the config file needs to change.
