### ISSUE TITLE
JWT: support public keys caching

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#15786]
### Problem Statement

JWK endpoints expose keys which typically are not frequently rotated.
Currently CrateDB requests public keys on each authentication request which might be too expensive.

We could add support of `Cache-Control: max-age` header (value in seconds) to control caching policy per authentication provider.

Some details: 
https://github.com/auth0/java-jwt already supports caching, but we need to cache JwkProvider instances on our own (instead of creating it per request in `jwkProvider`) to actually utilize caching.

**Comment by proddata** [comment]
Isn't this considered a bug, as the caching mechanism was mentioned in the original issue https://github.com/crate/crate/issues/14238 ?

**Comment by seut** [comment]
> Isn't this considered a bug, as the caching mechanism was mentioned in the original issue #14238 ?

Why would this justify to treat this as a bug? AFAIK this is not related to a functional part but rather an optimization. Or is something breaking without a cache in place?

**Comment by proddata** [comment]
> Why would this justify to treat this as a bug? AFAIK this is not related to a functional part but rather an optimization. Or is something breaking without a cache in place?

Sorry, should have been more clear. When we were providing feedback on this feature the assumption was that caching is part of the initial scope and there was maybe just as slight issue why it was not working properly. What is unclear from the documentation: Would the current behavior for every query / `POST`  to `/_sql` fetch the public key from the remote server? That seems excessive and potentially slow down querying by quite a lot.

So not a bug, but rather a non-functional requirement for the initial feature request.

**Comment by proddata** [comment]
We now have JWT in use for some of the cloud cluster. While it does work, it sometimes can feel slugish in terms of response time. I did a small test of running 100 request with basic auth and bearer token (jwt) against the same cluster. The results are somewhat consistent. Generally speaking this is a non-issue if tcp keep alive are used, however since tcp connections are handled by the browser and there is little to no way to influence how the browser is handling connections this still can be an issue.

```
keep-alive enabled

Running test with Basic Auth...
Auth Type: basic
Total time for 100 requests: 3009.28 ms
Average response time: 30.09 ms
Median response time: 28.15 ms

Running test with Bearer Token...
Auth Type: bearer
Total time for 100 requests: 2776.53 ms
Average response time: 27.77 ms
Median response time: 27.30 ms
```

however comes apparent with explicitly disabling tcp keep-alive

```
keep-alive disabled

Running test with Basic Auth...
Auth Type: basic
Total time for 100 requests: 13555.64 ms
Average response time: 135.56 ms
Median response time: 133.90 ms

Running test with Bearer Token...
Auth Type: bearer
Total time for 100 requests: 38600.90 ms
Average response time: 386.01 ms
Median response time: 363.04 ms
```
