### ISSUE TITLE
Architecture image not readable in dark mode

### ISSUE THREAD

**Issue by mitesh-mutha** [crate/crate#15790]
### Problem description

The image [architecture.svg](https://github.com/crate/crate/blob/master/devs/docs/architecture.svg) in the document [CrateDB Architecture](https://github.com/crate/crate/blob/master/devs/docs/architecture.rst) is not readable in dark mode. 

### Steps to Reproduce

Open the link - [CrateDB Architecture](https://github.com/crate/crate/blob/master/devs/docs/architecture.rst). 

### Actual Result

![image](https://github.com/crate/crate/assets/2995314/c0dae5d2-b871-4fc4-af24-603510f1a6dd)

### Expected Result

![image](https://github.com/crate/crate/assets/2995314/262cc3ca-126d-4143-85eb-07e74b126835)

**Comment by matriv** [comment]
Issue has been fixed with: https://github.com/crate/crate/pull/15791

Thanks a lot @mitesh-mutha for reporting and fixing it!
