### ISSUE TITLE
Docker image for 5.5.4 unavailable

### ISSUE THREAD

**Issue by robd003** [crate/crate#15871]
### CrateDB version

5.5.4

### CrateDB setup information

Any Docker / Kubernetes install

### Problem description

The 5.5.4 image is missing, but weirdly the unreleased 5.5.5 image is available, although it's actually the 5.5.4 release

### Steps to Reproduce

`docker pull crate:5.5.4`

### Actual Result

`Error response from daemon: failed to resolve reference "docker.io/library/crate:5.5.4": docker.io/library/crate:5.5.4: not found`

### Expected Result

Released binaries should be available on Docker Hub

**Comment by proddata** [comment]
This is a known issue and happened by mistake:
https://github.com/docker-library/official-images/pull/16181/files#diff-3d54c8667b603b919713cf8a929ff7a68f7f8544a247d2a76c78f3f4af693a1dR11

There is however no "easy" fix for it without disrupting other processes.

**Comment by robd003** [comment]
No worries, just wanted to make sure you guys were aware of the issue

**Comment by matriv** [comment]
thx @robd003! but yes as @proddata said we are aware already of this hiccup.
