### ISSUE TITLE
Disallow setting both balance.index and balance.shard factors to 0

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#15914]
### Problem Statement

Performing the following configuration is allowed:
```sql
set global persistent "cluster.routing.allocation.balance.index" = '0.00f';
set global persistent "cluster.routing.allocation.balance.shard" = '0.00f';
```
However after restarting the nodes the cluster will no longer start and the following entries will appear in the logs:
`failed to apply updated cluster state`
`Balance factors must sum to a value > 0 but was: 0.0`

### Possible Solutions

- Reject changing one of these settings to zero if the other one is already zero

**Comment by matriv** [comment]
thank you @hlcianfagna for reporting this. It has been fixed and will be available with the next hotfix release.
