### ISSUE TITLE
Support `GROUP BY ALL`

### ISSUE THREAD

**Issue by proddata** [crate/crate#15946]
### Problem Statement

When interactively writing queries in CrateDB one needs to specify the list of columns in two locations for aggregations, which can lead to broken queries and pontential bugs.

```sql
SELECT
  col1,
  agg(col2),
  col3
FROM t01;
GROUP BY
  col1, col3;
```

### Possible Solutions

To prevent broken queries and pontential bugs by keeping the SELECT granularity aligned to the GROUP BY granularity one could either add support for `GROUP BY ALL` similiar to [Snowflake](https://docs.snowflake.com/en/sql-reference/constructs/group-by#label-group-by-all-columns), [DuckDB](https://duckdb.org/docs/sql/query_syntax/groupby.html), [ClickHouse](https://clickhouse.com/docs/en/sql-reference/statements/select/group-by#group-by-all) and others

```sql
SELECT
  col1,
  agg(col2),
  col3
FROM t01;
GROUP BY ALL;
```

`ALL` is already a reserved keyword - this wouldn't be a breaking change.

**Comment by mfussenegger** [comment]
Referencing the columns by ordinal is an alternative - although a bit less convenient:

```sql
SELECT
  col1,
  agg(col2),
  col3
FROM t01;
GROUP BY
  1, 3;
```

**Comment by proddata** [comment]
> Referencing the columns by ordinal is an alternative - although a bit less convenient:

Which is even more error-prone when adjusting queries.
But overall this is more about convenience anyway.

**Comment by DHRUV6029** [comment]
Hi, Can i Work on this feature

**Comment by matriv** [comment]
@DHRUV6029 Thx for volunteering to work on this!
Please let us know of any help you might need.

**Comment by DHRUV6029** [comment]
Hello , Thanks for assigning me the task.
I had few queries @mfussenegger mentioned do we need ordinal number refrence or, we just want to support Group by ALL
clause

Thanks

**Comment by proddata** [comment]
@DHRUV6029 Just GROUP BY ALL. Ordinal number references are already implemented.

**Comment by DHRUV6029** [comment]
Hi can you guys help me with files where code for group by is already implemented ?
Thanks

**Comment by mfussenegger** [comment]
> Hi can you guys help me with files where code for group by is already implemented ? Thanks

You'll have to extend the parser grammar to allow for `ALL` as an alternative to the list:

https://github.com/crate/crate/blob/1e92620fc3271f8300501645674f0a83d31dbdac/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4#L192

This then implies that the `QuerySpecification` structure has to change the representation of the GROUP BY:

https://github.com/crate/crate/blob/1e92620fc3271f8300501645674f0a83d31dbdac/libs/sql-parser/src/main/java/io/crate/sql/tree/QuerySpecification.java#L46

Could model this via a `GroupBy` node, or maybe we can introduce a `Either<L, R>`.


The `ALL` case then needs to be resolved to the actual columns in:

https://github.com/crate/crate/blob/1e92620fc3271f8300501645674f0a83d31dbdac/server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java#L415-L419

**Comment by DHRUV6029** [comment]
Thanks  , Will submit a PR by this weekend

**Comment by DHRUV6029** [comment]
hi @mfussenegger @matriv 
I wanted to confirm that group by All clause ignores the non scalar cols in select clause 
eg
SELECT
    col1,
    SUM(col2) as sum_col2,
    col3
FROM t01
GROUP BY ALL;

is Equivalent to 

SELECT
    col1,
    SUM(col2) as sum_col2,
    col3
FROM t01
GROUP BY col1, col3;


col2 is aggregate and should be taken care by Group by all clause?

Thanks

**Comment by matriv** [comment]
That's true, ALL should resolve to col1 and col3.

**Comment by DHRUV6029** [comment]
hello @mfussenegger 
![Image](https://github.com/user-attachments/assets/ff5c2215-cebe-4c08-92b6-2757022c4ada)
for the above table if we have the query

 SELECT  SUM(col2) as sum_col2  FROM t01 GROUP BY 1;
we get expetion SQLParseException[Aggregate functions are not allowed in GROUP BY]

so when we hit a query

 SELECT  SUM(col2) as sum_col2  FROM t01 GROUP BY all;

shlould it be expection or it should be the sum of col2 printed as below
![Image](https://github.com/user-attachments/assets/36b5e596-9a1f-46d5-b247-d6edef5a1d96)

**Comment by proddata** [comment]
I just checked the behavior for BigQuery, Databricks and Snowflake, which all default to treating it like omitting the clause all together

> from https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-groupby.html
> "If no such expression exist GROUP BY ALL is equivalent to omitting the GROUP BY clause which results in a global aggregation."


https://docs.snowflake.com/en/sql-reference/constructs/group-by

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#group_by_all

I.e. since this is afaik not yet defined in ISO SQL I would follow that approach.

**Comment by DHRUV6029** [comment]
@mfussenegger @proddata @mfussenegger 
Just to clarify result should be 
![Image](https://github.com/user-attachments/assets/ba77ec9d-6ce5-4e8c-bbd9-cd024d46e3d1)

**Comment by DHRUV6029** [comment]
hi @mfussenegger @proddata @matriv 
i docs should i add this feature under SQL Statements or Sql Standard with PostgRESql compatibility

![Image](https://github.com/user-attachments/assets/ea9f00b4-3fe0-44ea-ba57-e88977886ece)

**Comment by proddata** [comment]
> Just to clarify result should be

correct

> i docs should i add this feature under SQL Statements or Sql Standard with PostgRESql compatibility

SQL Statements both in the release notes, as well as in the documentation.

https://github.com/crate/crate/blob/master/docs/sql/statements/select.rst#group-by

**Comment by DHRUV6029** [comment]
@mfussenegger @proddata this issue can be closed as PR is already merged

**Comment by proddata** [comment]
@DHRUV6029 
Thank you for contributing to CrateDB 🙇
