### ISSUE TITLE
Insert into column with default value doesnt work "standalone"

### ISSUE THREAD

**Issue by wierdvanderhaar** [crate/crate#15961]
### Problem Statement

Created a table a column with a default value. 
`CREATE TABLE t (a INTEGER DEFAULT 5);`

However, trying to insert a row using the default failed. 

Option 1:

`INSERT INTO t values ();``
Error!
SQLParseException[line 1:23: no viable alternative at input 'values ()']

Option 2:

`INSERT INTO t (a) values ();`
Error!
SQLParseException[line 1:23: no viable alternative at input 'values ()']

Created a 2nd table with an additional column.

`CREATE TABLE t2 (a INTEGER DEFAULT 5, b TEXT);`
`INSERT INTO t2 (b) values ('test') ;`

`select * from t2 limit 100;`
a	b
5	 test

`INSERT INTO t2 (a) values () ;`
Error!
SQLParseException[line 1:28: no viable alternative at input 'values ()']

### Possible Solutions

Maybe supporting DEFAULT like they do in Postgres could be a possible solution. As described here: [https://github.com/crate-workbench/typeorm/issues/3][]

**Comment by matriv** [comment]
I'm closing this in favor of: https://github.com/crate/crate/issues/14575
PostgreSQL also doesn't accept empty values list:
```
matriv=> create table t(a int default 10);
CREATE TABLE
matriv=> insert into t values();
ERROR:  syntax error at or near ")"
LINE 1: insert into t values();
                             ^
```

**Comment by matriv** [comment]
matriv=> create table t(a int default 10);
CREATE TABLE
matriv=> insert into t values();
ERROR:  syntax error at or near ")"
LINE 1: insert into t values();
                             ^
