### ISSUE TITLE
Unexpected results when using system information functions

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16026]
### CrateDB version

CrateDB 5.8.0-SNAPSHOT built 0dcd1a0

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the last query returns `-1`, because the result of the second query is NULL, which means that the WHERE clause in the last query should be evaluated to NULL and thus the row should be filtered.

I also observed similar issues in `CURRENT_SETTING` and `PG_GET_FUNCTION_RESULT`

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c1 INTEGER);
INSERT INTO t0(c1) VALUES (-1);
REFRESH TABLE t0;

SELECT * FROM t0; -- -1
SELECT (NOT ((PG_ENCODING_TO_CHAR(t0.c1))<(false))) FROM t0; -- NULL
SELECT * FROM t0 WHERE (NOT ((PG_ENCODING_TO_CHAR(t0.c1))<(false)));
-- Expected: empty table
-- Actual: -1
```

### Actual Result

-1

### Expected Result

empty table

**Comment by jeeminso** [comment]
Thanks for reporting @suyZhong! The fix will be available in `5.7.2`.
