### ISSUE TITLE
Unexpected result when using `CURRENT_SETTING`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16062]
### CrateDB version

CrateDB 5.8.0-SNAPSHOT built 894df21

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The query using `CURRENT_SETTING` with `t0.c0 LIKE t0.c0` and applying the `NOT` operator should result in a NULL value. Consequently, the `WHERE` clause should filter out all rows, resulting in an empty result set. However, the actual result set includes the row with the value 'a', which indicates misbehavior.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES ('a');
REFRESH TABLE t0;

SELECT * FROM t0; -- 'a'
SELECT (NOT CURRENT_SETTING(1, t0.c0 LIKE t0.c0)) FROM t0; -- NULL
SELECT * FROM t0 WHERE (NOT CURRENT_SETTING(1, t0.c0 LIKE t0.c0));
-- Expected: empty result set
-- Actual: 'a'
```

### Actual Result

'a'

### Expected Result

empty result set

**Comment by matriv** [comment]
Thx for reporting @suyZhong !
We've missed to fix current_setting for the overloaded version with 2 args. Fix will be available with the next hotfix release.
