### ISSUE TITLE
Allow dots in field names

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16063]
### Problem Statement

CrateDB currently does not allow dots as part of field names:
```sql
CREATE TABLE test ("field.name" INT);
CREATE TABLE test ("field" OBJECT AS ("field.name" INT));
```
```
InvalidColumnNameException["field.name" contains a dot]
```

### Possible Solutions

Allow dots in field names when identifier names are quoted as in https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by seut** [comment]
Unfortunately, my previous out come isn't correct. We use the dotted representation of nested object columns, e.g. `my_obj.my_inner_column` for the sql subscript representation of `my_obj[my_inner_column]` inside our table metadata if this column is declared as a primary key, routing column or partition column.

Thus we currently have indeed internal blockers and would have to change theses internal representations first.
One solution could be to store a nested object column as a list representation (e.g. ['my_obj', 'my_inner_column'], similar to how our `ColumnIdent` represent this.

**Comment by mfussenegger** [comment]
https://github.com/crate/crate/issues/11939 might already affect some of the metadata. Maybe worth re-estimate after it is done.

**Comment by henrikingo** [comment]
Just leaving a note here as this is valid opinion and potential outcome of ongoing discussion, but is not mentioned in this ticket yet: 

A quite possible alternative is that we are of the opinion that table names, column names nor field names should *NOT* allow dots. Note that even if MongoDB allows that, their own documentation actually has this as not recommended. (Mongodb compatibility / alignment was used as a justfication.)

**Comment by henrikingo** [comment]
I will close this for now, it's ok to reopen if we ever encounter a user with a compelling need for this.

So far everyone we talk to has responded that they are ok with using some other character than a dot, and in some cases the data with a dot in field names was some old data that was ok to discard.

**Comment by amotl** [comment]
Hi. Let me add [another signal](https://github.com/crate/mlflow-cratedb/issues/289#issuecomment-4163552562) from the MLflow framework when it tries to save spans to the database backend. The operation currently fails, because MLflow writes fields including dots to a column we reconfigured to use `OBJECT(DYNAMIC)` instead of PostgreSQL's `JSONB` type.
```python
InvalidColumnNameException["mlflow.llm.model" contains a dot]
```
```
2026/03/31 17:35:02 DEBUG mlflow.tracing.export.mlflow_v3: Failed to log span to MLflow backend: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(crate.client.exceptions.ProgrammingError) InvalidColumnNameException["mlflow.llm.model" contains a dot]
[SQL: INSERT INTO spans (trace_id, experiment_id, span_id, parent_span_id, name, type, status, start_time_unix_nano, end_time_unix_nano, content, dimension_attributes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING spans.duration_ns]
[parameters: ('tr-94070d3db469c12957e8bcfc37aaa473', '1774971293013', '02c5971cc1fb5581', 'faf3283e43717676', 'generate_response', 'LLM', <SpanStatusCode.OK: 'OK'>, 1774616953125687944, 1774616953368581944, '{"trace_id": "lAcNPbRpwSlX6Lz8N6qkcw==", "span_id": "AsWXHMH7VYE=", "parent_span_id": "+vMoPkNxdnY=", "name": "generate_response", "start_time_unix_n ... (850 characters truncated) ... \": \\"assistant\\", \\"content\\": \\"You can use mlflow.sklearn.log_model() or similar functions to log models. They get saved with the run.\\"}"}}', {'mlflow.llm.model': 'gemini-3-pro'})]
```

Maybe you can share some good news that it might be easier to do today than it was two years ago?
