### ISSUE TITLE
Add role session setting defaults 

### ISSUE THREAD

**Issue by mkleen** [crate/crate#16074]
### Problem Statement

 We have a use-case where a session setting should be set as default for a certain role.  We recently added an optimizer rule which is disabled by default https://github.com/crate/crate/pull/16049. This means if a user wants to apply it, the rule needs to be enabled by a session setting on each session:

```
 SET optimizer_equi_join_to_lookup_join = true
```
It is currently not possible to enable this optimizer rule for benchmarks because setup/teardown and each concurrent connection have separate sessions.

### Possible Solutions

Provide role session setting defaults https://www.postgresql.org/docs/current/sql-alterrole.html
```
ALTER ROLE crate SET optimizer_equi_join_to_lookup_join = true
```

This bounds the session setting to the role and works then across all sessions for the given role. For the benchmarks this can then be set/unset in the setup/teardown routines and will remain for the whole benchmark.

### Considered Alternatives

Another option would be to support settings in the URL (similar to PostgreSQL startup parameter support).

**Comment by mfussenegger** [comment]
Setting `statement_timeout` in tools that don't provide connection options is another use-case for this. See https://github.com/crate/crate/issues/12109#issuecomment-1531221328

**Comment by matriv** [comment]
Findings:

- Postgres doesn't apply user settings when switching users with `SET SESSION AUTHORIZATION`:

(`search_path` is set to `myschema` for user `u1`)
```
$ psql -U u postgres                                                                                
psql (16.2)
Type "help" for help.

postgres=# SET SESSION AUTHORIZATION u1;
SET
postgres=> select * from t1;
ERROR:  relation "t1" does not exist
LINE 1: select * from t1;
                      ^
postgres=> 
\q

$ psql -U u1 postgres                                                                                
psql (16.2)
Type "help" for help.

postgres=> select * from t1;
 a 
---
 1
 2
(2 rows)
```

- Postgres doesn't apply inheritance of session settings:
`t1` belongs to `myschema`, and `u1`'s search_path has been modified with:
`ALTER USER u1 SET search_path='myschema';`
so `u1` has it, and can query `t1` wihtout schema prefix but `u2` has the default `search_path` despite the GRANT.
```
$ psql -U postgres 
psql (16.2)
Type "help" for help.

postgres=# GRANT u1 to u2;
GRANT ROLE
postgres=# 
\q


$ psql -U u1 postgres
psql (16.2)
Type "help" for help.

postgres=> select * from t1;
 a 
---
 1
 2
(2 rows)

postgres=> show search_path;
 search_path 
-------------
 myschema
(1 row)

postgres=> 
\q

$ psql -U u2 postgres
psql (16.2)
Type "help" for help.

postgres=> select * from t1;
ERROR:  relation "t1" does not exist
LINE 1: select * from t1;
                      ^
postgres=> show search_path;
   search_path   
-----------------
 "$user", public
(1 row)
```
