### ISSUE TITLE
Allow FDW user mapping against roles

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16119]
### Problem Statement

Trying to use `CREATE USER MAPPING` against a role as opposed to a normal user currently results on a misleading `RoleUnknownException`.
As a DBA I would like to be able to configure a user mapping against a role so that any user that belongs to a role can access the foreign server tables with the given credentials without me having to configure the mapping for each individual user, which also means I need to deal with the foreign credentials every time and I need to update them multiple times if they change.

### Possible Solutions

Allow mapping against roles

### Considered Alternatives

Keep track of which users need to access the foreign server resources and create individual user mappings for each.

**Comment by mfussenegger** [comment]
Is something like this supported in PostgreSQL?

A user can be granted more than one role which means there would need to be some rules in regards to which mapping takes precedence.

Potential workaround:
- Create one user for fdw
- Create views with that user that re-expose the foreign tables

**Comment by proddata** [comment]
> Is something like this supported in PostgreSQL?

No, PostgreSQL [allows the following](https://www.postgresql.org/docs/current/sql-createusermapping.html):

> `CREATE USER MAPPING [ IF NOT EXISTS ] FOR { user_name | USER | CURRENT_ROLE | CURRENT_USER | PUBLIC }`

where `USER | CURRENT_ROLE | CURRENT_USER` are equal to the current user, while `PUBLIC` specifies a user mapping to be used when there is no user-specific mapping is applicable.

- This also is followed by e.g. DB2 and Greenplum.
- SQL Server is using Linked Servers and also either allows `NULL`  (which is equivalent to `PUBLIC`) or a specific user.
 
---

I would tend to allow `CREATE USER MAPPING FOR PUBLIC` and control access to foreign tables via user privileges and/or use a VIEW as described above.

**Comment by mfussenegger** [comment]
Closingin favour of https://github.com/crate/crate/issues/16166

**Comment by hlcianfagna** [comment]
> SQL Server is using Linked Servers and also

Just to clarify something, this is a bit different in MSSQL, mapping is with server logins, but a server login can be an AD group, so the premise of this feature request is respected, as a DBA I do want to avoid configuring permissions for individual accounts as people come and go and change teams and I need to make sure permissions are not only provisioned quickly but also removed right away when no longer needed.
