### ISSUE TITLE
Allow the use of EXPLAIN ANALYZE on queries with scalar subselects

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16120]
### Problem Statement

Trying to see the execution details of a query and where time is going, to make adjustments for better performance, it would be useful to be able to see `EXPLAIN ANALYZE` output for queries such as:

```sql
EXPLAIN ANALYZE
WITH constants AS (
		SELECT 'machine1' AS servername
		)
SELECT *
FROM sys.nodes
WHERE hostname = (
		SELECT servername
		FROM constants
		);
```

### Possible Solutions

Lift the restriction currently leading to
```
UnsupportedFeatureException[EXPLAIN ANALYZE does not support profiling multi-phase plans, such as queries with scalar subselects.]
```

### Considered Alternatives

Hard-coding the "constants" and analyzing the individual parts of the query, however we cannot confirm the actual execution of the composed query would follows the same plan.

**Comment by seut** [comment]
@hlcianfagna We've implemented this with #16579, please check the PR description on how sub-query execution timings will appear inside the output.
