### ISSUE TITLE
SQLParseException on query with subqueries with latest nightly 

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16124]
### CrateDB version

nightly-5.8.0-2024-06-09-00-02 built f0174b1

### CrateDB setup information

CRATE_HEAP_SIZE=1g
discovery.type=single-node

### Problem description

There seems to be a regression on the latest nightly, see repro steps below.
This same query works without issues on 5.7.1

### Steps to Reproduce

```sql
create table table1 (field1 int);
insert into table1(field1) values (1);
refresh table table1;

create table table2 (field1 int);
insert into table2(field1) values (1);
refresh table table2;

create table table3 (field1 int,field2 text);
insert into table3(field1,field2) values (1,'abc');
refresh table table3;


SELECT (
		SELECT CONCAT (
				table2.field1::TEXT
				,(
					SELECT table3.field2
					FROM table3
					WHERE table3.field1 = table2.field1 limit 1
					)
				)
		FROM table2
		WHERE table2.field1 = table1.field1
		) AS table2_Details
FROM table1;
```

### Actual Result

```
SQLParseException[Couldn't create execution plan from logical plan because of: Couldn't find (SELECT field2 FROM (doc.table3)) in SourceSymbols{inputs={field1=INPUT(1)}, nonDeterministicFunctions={}}:
Eval[concat(cast(field1 AS text), (SELECT field2 FROM (doc.table3)))] (rows=unknown)
  └ Limit[2::bigint;0::bigint] (rows=unknown)
    └ Filter[true] (rows=unknown)
      └ CorrelatedJoin[field1, field1] (rows=unknown)
        └ Collect[doc.table2 | [field1] | (field1 = field1)] (rows=unknown)
        └ SubPlan
          └ Eval[field2] (rows=unknown)
            └ Limit[2::bigint;0::bigint] (rows=unknown)
              └ Limit[1::bigint;0] (rows=unknown)
                └ Collect[doc.table3 | [field2] | (field1 = field1)] (rows=unknown)]
```

### Expected Result

```
 table2_details 
----------------
 1abc
(1 row)
```

**Comment by hlcianfagna** [comment]
Tried fadbaf0 (May 15th) and this was working

**Comment by hlcianfagna** [comment]
A bit more context as there may be something more going on, the repro query in this ticket is a simplified version of a more complex query I am trying to run. 

- In 5.7.1 and fadbaf0 
   - the query in this ticket: works
   - my actual query: fails with a stack trace very similar to the one from https://github.com/crate/crate/issues/15901 (an issue I came across on a completely different context) 
- In 3a9fd77 (`nightly-5.8.0-2024-05-23-00-02`) - which got the fix for #15901 
   - the query in this ticket: still works
   - my actual query: fails with an error message very similar to the one on this issue.
- In f0174b1 (`nightly-5.8.0-2024-06-09-00-02`)
   - the query in this ticket: does not work anymore
   - my actual query: fails with a very similar message to 3a9fd77 (now a Collect retrieves less fields)

**Comment by amotl** [comment]
Hi. The [Build Status](https://cratedb.com/docs/crate/clients-tools/en/latest/status.html) page, demonstrating CI run outcomes of integration tests with 3rd party software, also has a few red fringes. I didn't investigate more closely, but it might be related.

@BaurzhanSakhariev investigated that issue, which might be unrelated to yours, and added a [corresponding card](https://github.com/orgs/crate/projects/21?pane=issue&itemId=66358387). If its totally unrelated, it looks like we currently observe multiple regressions.

**Comment by BaurzhanSakhariev** [comment]
Same as https://github.com/orgs/crate/projects/21?pane=issue&itemId=66358387, if I revert https://github.com/crate/crate/pull/16079, query works.
