### ISSUE TITLE
Support `ALTER SERVER` to change connection url

### ISSUE THREAD

**Issue by proddata** [crate/crate#16164]
### Problem Statement

User mappings and foreign tables rely on a foreign server, which means you cannot change or fix a connection string once a user mapping or foreign table is created. Additionally, testing a foreign server is only truly possible after these elements are added.

### Possible Solutions

Support `ALTER SERVER` similiar to PostgreSQL:
 
```
ALTER SERVER name OPTIONS ( SET url 'jdbc:postgresql://example.com:5432/')
```

### Considered Alternatives

dropping foreign tables, user mappings and foreign server, then recreate all of them.

**Comment by seut** [comment]
@proddata Thank you for reporting. It's implemented by #17131 and will be released with the upcoming `5.10` feature release.
