### ISSUE TITLE
Unexpected result when using `DEFAULT` during creating table

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16173]
### CrateDB version

CrateDB 5.8.0-SNAPSHOT built 7a1ca39

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the following test case. A discrepancy is observed when filtering results using a boolean comparison in a `WHERE` clause. The boolean condition `(t1.c1 >= 1)=((t1.c1 = t1.c1)AND(t0.c1 <= t0.c1))` evaluates to `TRUE` when selected directly, but fails to return any rows when used in the `WHERE` clause.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;

CREATE TABLE  t0 (c1 INT NOT NULL DEFAULT 1);
CREATE TABLE  t1 (c1 INTEGER);
INSERT INTO t0(c1) VALUES (1);
INSERT INTO t1(c1) VALUES (2);
REFRESH TABLE t0;
REFRESH TABLE t1;

SELECT * FROM t0, t1; -- 1 2
SELECT (t1.c1 >= 1)=((t1.c1 = t1.c1)AND(t0.c1 <= t0.c1)) FROM t0, t1; -- TRUE
SELECT * FROM t0, t1 WHERE (t1.c1 >= 1)=((t1.c1 = t1.c1)AND(t0.c1 <= t0.c1));
-- Expected: 1 2
-- Actual: Empty table
```

if removing the `DEFAULT`, I will get 
```sql
CREATE TABLE  t0 (c1 INT);
-- ...
SELECT * FROM t0, t1 WHERE (t1.c1 >= 1)=((t1.c1 = t1.c1)AND(t0.c1 <= t0.c1));
-- UnsupportedFeatureException[Can't handle Symbol [SimpleReference: c1]]
```

Not sure if it's expected.

### Actual Result

Empty table

### Expected Result

1 2

**Comment by BaurzhanSakhariev** [comment]
Thanks for reporting @suyZhong!

It's a regression introduced in 5.6.3. 

Workaround for CrateDB>=5.6.3: disable hash join by `SET enable_hashjoin = false`.
