### ISSUE TITLE
Unexpected result when using `PG_GET_PARTKEYDEF`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16172]
### CrateDB version

CrateDB 5.8.0-SNAPSHOT built 7a1ca39

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The query using PG_GET_PARTKEYDEF and applying the NOT operator should result in a NULL value. Consequently, the WHERE clause should filter out all rows, resulting in an empty result set. However, the actual result set includes the row with the value 1, which indicates misbehavior.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE TABLE t0 (c0 INTEGER) ;
INSERT INTO t0(c0) VALUES (1);
REFRESH TABLE t0;

SELECT * FROM t0; -- 1
SELECT (NOT (PG_GET_PARTKEYDEF(t0.c0))) FROM t0; -- NULL
SELECT * FROM t0 WHERE (NOT (PG_GET_PARTKEYDEF(t0.c0)));
-- Expected: empty table
-- Actual: 1
```

### Actual Result

1

### Expected Result

Empty table

**Comment by matriv** [comment]
Thx a lot for spotting and reporting this @suyZhong, the fix will be available with the next hotfix release.
