### ISSUE TITLE
Unexpected result when using `FORMAT_TYPE`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16225]
### CrateDB version

CrateDB 5.8.0-SNAPSHOT built da0993c

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

The expression using `FORMAT_TYPE` and applying the `!=` operator should return `TRUE`. Consequently, the WHERE clause should not filter out the row. However, the actual result set does not include the row with the value NULL, which indicates misbehavior.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE  t0 ( c1 INTEGER) ;
INSERT INTO t0(c1) VALUES (NULL);
REFRESH TABLE t0;

SELECT * FROM t0; -- NULL
SELECT ('text' != FORMAT_TYPE(3, t0.c1)) FROM t0; -- TRUE

SELECT * FROM t0 WHERE ('text' != FORMAT_TYPE(3, t0.c1));
-- Expected: NULL
-- Actual: empty table
```

### Actual Result

Empty table

### Expected Result

NULL

**Comment by matriv** [comment]
Thx for reporting yet another issue with null handling in the WHERE clause for functions, @suyZhong !
It has been fixed and will be available with the next hotfix release.
