### ISSUE TITLE
Queries on unknown/missing sub-columns of objects should return `null` by default and not return an exception

### ISSUE THREAD

**Issue by proddata** [crate/crate#16259]
### Problem Statement

The ability to work with JSON(-like) data in CrateDB offers the flexibility to handle loosely defined data schemas. However, CrateDB often raises a `ColumnUnknownException` when querying an undefined sub-column or when the selected property is not present in all objects. While not strictly following either this behaviour seems to deviate from both PostgreSQL, as well as the ISO SQL Standard for JSON values.

### ISO / IECTR 19075-6
The standard defines `JSON_VALUE` as operator to extract an scalar from a JSON Value and the following default behaviour:
> NULL ON EMPTY means that the result of JSON_VALUE is the null value.

>  If  <JSON value empty behaviour> is not specified, then NULL ON EMPTY is implicit.
>  If  <JSON value error behaviour> is not specified, then NULL ON ERROR is implicit

### PostgreSQL Behaviour
```sql
CREATE TABLE js_tab (js JSON, jsb JSONB);
SELECT js -> 'y' AS "json", jsb -> 'y' AS "jsonb" FROM js_tab;
 json | jsonb 
------+-------
 NULL | NULL
```

[Documentation](https://www.postgresql.org/docs/current/functions-json.html)

> "The field/element/path extraction operators return NULL, rather than failing, if the JSON input does not have the right structure to match the request; for example if no such key or array element exists."

> "The jsonpath operators @? and @@ suppress the following errors: missing object field or array element, unexpected JSON item type, datetime and numeric errors. The jsonpath-related functions described below can also be told to suppress these types of errors. This behavior might be helpful when searching JSON document collections of varying structure."

### Possible Solutions

Return `null` by default on unknown columns / selections on missing properties.

Potentially this could be achieved by making `error_on_unknown_object_key` default to `false` instead of `true` and/or allow this to be set on the cluster level.

**Comment by mfussenegger** [comment]
Isn't `error_on_unknown_object_key` + https://github.com/crate/crate/issues/16074 good enough?

`object` type is custom, what PostgreSQL or Standard says about `JSON` is irrelevant here. That matters once we start supporting `JSON` / `JSONB` storage and the other SQL standard JSON query operations.

The general idea is that sub-columns of an object are regular columns, so they should behave like columns.

**Comment by mfussenegger** [comment]
Closing this in favour of https://github.com/crate/crate/issues/14828

**Comment by proddata** [comment]
> Isn't error_on_unknown_object_key + https://github.com/crate/crate/issues/16074 good enough?

From a user perspective there is a big difference between a default behaviour vs a setting that isn't easy to find/set.
Also #16074 raises the question why this can't be set as cluster / connections defaults as others are doing. i.e. I see it as a limited mitigation. 

> object type is custom, what PostgreSQL or Standard says about JSON is irrelevant here.

It is not entirely accurate to dismiss the relevance of PostgreSQL or standard SQL specifications. CrateDB targets similar use cases, which means users come with expectations shaped by their experiences with other systems. 

> The general idea is that sub-columns of an object are regular columns, so they should behave like columns.

While it is somewhat understandable for objects with dynamic or strict schemas, where all column information is implicitly available, this does not hold true for `object(ignored)`. This type is intended for objects with varying or unknown schemas, and the behavior and expectations are different in this context.

Additionally, considering that objects with dynamic mapping only alter the schema when data is received, two clusters with the same base schema could behave differently. A query might work on one cluster while raising an exception on the other.

> The exception is object(ignored), changing that is tracked with https://github.com/crate/crate/issues/14828

Based on the original description in #14828, the proposed changes could worsen the situation by raising more exceptions. Your comment on [issue #14828](https://github.com/crate/crate/issues/14828#issuecomment-2199712714) highlights a core issue, but it remains unclear from the description if or how this issue will be resolved.
