### ISSUE TITLE
Missing Maven dependencies for Java client

### ISSUE THREAD

**Issue by devoncrouse** [crate/crate#1628]
```
<dependency>
  <groupId>io.crate</groupId>
  <artifactId>crate-client</artifactId>
  <version>0.45.6</version>
</dependency>
```

Looking at the pom from bintray, there are no dependencies defined, but at least `io.netty` seems to be required.

**Comment by chaudum** [comment]
hi @devoncrouse 

the `crate-client.jar` already contains all it's required dependencies.
netty lives in the `org.jboss.netty.*` namespace.
