### ISSUE TITLE
Request for feature [array comparison]

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [crate/crate#1630]
I think it would be great to be able to use a query to compare if arrays match for e.g.

    SELECT * FROM foo WHERE bar = [1,2,3,4];

Where bar is an integer array and will only return results which contain [1,2,3,4].

Thanks!

**Comment by dobe** [comment]
hi @Ewan-GrandSlam 

the exact match is currently not possible, but you can search for containment with ANY and SOME 
see https://crate.io/docs/stable/sql/queries.html#any-array

regards, bernd

**Comment by Ewan-GrandSlam** [comment]
Hey @dobe -

Unfortunately ANY does not meet my requirements as I do have to have an exact array match (in what should hopefully be a single query) - I talked to a fellow over on the IRC and they said they will look into  adding in this feature.

Hopefully this does come to fruition as it would be a wondrous help in what I need to do.

**Comment by devoncrouse** [comment]
+1

**Comment by mfussenegger** [comment]
hi @Ewan-GrandSlam 

we've talked in IRC and I've actually managed to sneak that feature into 0.47 (our current testing release) (see https://github.com/crate/crate/pull/1636)

Keep in mind that this kind of query cannot fully operate on the index. 
Although the implementation works in a way that it will pre-filter the result, but this only helps if only few rows contain the terms of the array. 
There is also an optimization/fix coming in 0.47.1 that will further improve that pre-filtering  (see https://github.com/crate/crate/pull/1652)

**Comment by Ewan-GrandSlam** [comment]
Thank you very much!
