### ISSUE TITLE
Feature request: display friendly partition names

### ISSUE THREAD

**Issue by devoncrouse** [crate/crate#1632]
Java 1.7.0_60
Crate 0.45.7

Looks like a hash of the partition value is used for naming the ES index and in the partition display on Crate's admin UI. The value used to create that hash is in information_schema.table_partitions; might be a nice feature to display that instead, and make it easier to determine which data is contained by a given index/partition.

**Comment by mfussenegger** [comment]
I guess this is a duplicate of https://github.com/crate/crate/issues/1085 or do you mean something else?

**Comment by devoncrouse** [comment]
Nope, sorry I missed the other one. Closing.
