### ISSUE TITLE
Allow  users with `AL` privileges to manage session settings defaults for other users

### ISSUE THREAD

**Issue by proddata** [crate/crate#16379]
### Problem Statement

The feature to alter session settings default has been implemented with this PR: [#16345](https://github.com/crate/crate/pull/16345). It was implemented in a way that only a superuser can change this setting for other users.

There should be a way for an user with `AL` privileges to change the defaults for other users. Imagine a user created solely for visualization/query purposes, where you want to set a `statement_timeout` without having access to the user or that user's password. As an AL user, you could delete that user, recreate it, log in, change the setting, share the credentials, and ask the end user to change them again, but this is a big inconvenience. For some users, a central default for all users, as described in [#16315](https://github.com/crate/crate/pull/16315), might be an alternative, but this would not solve the issue of centrally administering other users.

While changing session settings might be possible as a superuser, in many managed or distributed environments, accessing CrateDB with superuser privileges is only possible with access to the machine, which is often managed by others rather than CrateDB itself. CrateDB's and PostgreSQL's privilege systems are still quite different, especially in terms of administrative privileges, with the limitation that the superuser is basically only safely accessible from the host machine itself, while in PostgreSQL any user can be granted SUPERUSER privileges similar to AL.

### Possible Solutions

Allow users with `AL` privileges to alter session settings defaults with `ALTER ROLE ... SET ...`.
This is in line with administrating privileges for other users with `GRANT ... TO ...`

**Comment by mfussenegger** [comment]
Yes the permission topic is still open, no need for additional tracking here.
