### ISSUE TITLE
Extra flags to provide further details on failed records on HTTP endpoint bulk insertion

### ISSUE THREAD

**Issue by karynzv** [crate/crate#16435]
### Problem Statement

Currently, whenever a bulk insertion partially or fully fails it is hard to understand what went wrong. For that, the recommended approach is to rerun each record individually to get further insights into what happened.
At some point, due to memory concerns, many error messages were removed, which resulted in little to none errors being reported on bulk insertions.

### Possible Solutions

Use extra flags on the bulk request to adjust the error reporting behavior of the bulk operation

### Considered Alternatives

Currently, the recommended approach is to rerun each record individually to get further insights into what went wrong.

**Comment by mfussenegger** [comment]
Relates to https://github.com/crate/crate/issues/12218
