### ISSUE TITLE
Success `statusCode` for failed bulk inserts with HTTP endpoint

### ISSUE THREAD

**Issue by karynzv** [crate/crate#16433]
### CrateDB version

5.7.1

### CrateDB setup information

Local single node deployment

### Problem description

given a batch insert that fully or partially fails, the `statusCode` is always `200`. For single inserts you may get 400 for failed insertions, but for batch cases, it always returns as successful (200).
I'd expect the `400` code at least for the complete fail case.

### Steps to Reproduce

1 - Create table:
``` 
CREATE TABLE locations (
      id INT, 
      name TEXT, 
      kind TEXT, 
      description TEXT
)
```

2 - Batch insert:
```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO locations (id, name, kind, description)
          VALUES (?, ?, ?, ?)",
  "bulk_args": [
    [1337, "Earth", "Planet", "An awesome place to spend some time on."],
    [1338, "Sun", "Star", "An extraordinarily hot place."],
    ["error", "Titan", "Moon", "Titan, where it rains fossil fuels."]
  ]
}
EOF
```

3 - check the `statusCode` on the response

### Actual Result
```
"crate_response": {
    "body": {
        "cols": [],
        "duration": 10.722357,
        "results": [
            {
                "rowcount": -2
            },
            {
                "rowcount": -2
            },
            {
                "rowcount": -2
            }
        ]
    },
    "duration": 381.178,
    "statusCode": 200
}
```
### Expected Result
```
"crate_response": {
    "body": {
        "cols": [],
        "duration": 10.722357,
        "results": [
            {
                "rowcount": -2
            },
            {
                "rowcount": -2
            },
            {
                "rowcount": -2
            }
        ]
    },
    "duration": 381.178,
    "statusCode": 400
}
```

**Comment by mfussenegger** [comment]
The exact behavior here depends on how/where exactly the statement is failing. For bulk operations execution-runtime errors are currently deliberately reports via the rowcounts, so getting a 200 instead of 400 is intentional.

This relates a bit to https://github.com/crate/crate/issues/12218
