### ISSUE TITLE
Table with dynamic column policy is silently failing first insert if it includes an empty array

### ISSUE THREAD

**Issue by proddata** [crate/crate#16470]
### CrateDB version

5.9.0 / 5.7.3

### CrateDB setup information

single node

### Problem description

When using a dynamic column policy, the first insert silently fails if it includes both an empty array and another new column.

### Steps to Reproduce

```sql
cr> create table t001 (id TEXT PRIMARY KEY) WITH (column_policy = 'dynamic');
CREATE OK, 1 row affected (0.628 sec)

cr> INSERT INTO t001 (id,a,b) VALUES ('abc',[],'Text');
INSERT OK, 0 rows affected (0.077 sec)

cr> INSERT INTO t001 (id,a,b) VALUES ('abc',[],'Text');
INSERT OK, 1 row affected (0.023 sec)
```

### Actual Result

```sql
+-----------------------------------------------------+
| SHOW CREATE TABLE doc.t001                          |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."t001" (           |
|    "id" TEXT NOT NULL,                              |
|    PRIMARY KEY ("id")                               |
| )                                                   |
| CLUSTERED BY ("id") INTO 4 SHARDS                   |
| WITH (                                              |
|    column_policy = 'dynamic'                       |
| )                                                   |
+-----------------------------------------------------+
```
- The first insert fails, but schema is adjusted:
```sql
+-----------------------------------------------------+
| SHOW CREATE TABLE doc.t001                          |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."t001" (           |
|    "id" TEXT NOT NULL,                              |
|    "b" TEXT,                                        |
|    PRIMARY KEY ("id")                               |
| )                                                   |
| CLUSTERED BY ("id") INTO 4 SHARDS                   |
| WITH (                                              |
|    column_policy = 'dynamic'                       |
| )                                                   |
+-----------------------------------------------------+
```

- The second inserts succeeds, schema stays the same:
```sql
+-----------------------------------------------------+
| SHOW CREATE TABLE doc.t001                          |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."t001" (           |
|    "id" TEXT NOT NULL,                              |
|    "b" TEXT,                                        |
|    PRIMARY KEY ("id")                               |
| )                                                   |
| CLUSTERED BY ("id") INTO 4 SHARDS                   |
| WITH (                                              |
|    column_policy = 'dynamic'                       |
| )                                                   |
+-----------------------------------------------------+
```

### Expected Result

First insert of record succeeds

**Comment by jeeminso** [comment]
Looks like here is what is causing the insert failure:
https://github.com/crate/crate/blob/ec7c846f61cb4e9c0c4b41bbdec10696bf37d3ae/server/src/main/java/io/crate/execution/dml/Indexer.java#L587-L591

**Comment by matriv** [comment]
From the first look, I believe that we cannot insert the 1st row, since we cannot guess the type of the array with an empty array value. I think the fix should be to just remove the if block: https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/dml/DynamicIndexer.java#L82 and throw the exception.

**Comment by matriv** [comment]
> Looks like here is what is causing the insert failure:
> 
> https://github.com/crate/crate/blob/ec7c846f61cb4e9c0c4b41bbdec10696bf37d3ae/server/src/main/java/io/crate/execution/dml/Indexer.java#L587-L591

thx @jeeminso, that's the aftermath, the root cause is that we haven't generated a new column `b` for the table, because we cannot guess the type.

**Comment by proddata** [comment]
> thx @jeeminso, that's the aftermath, the root cause is that we haven't generated a new column b for the table, because we cannot guess the type.

we cannot guess the type of `a=[]`, but `b='Text'`

**Comment by matriv** [comment]
thx for reporting @proddata! issue has been fixed and will be available with the next hotfix release.
