### ISSUE TITLE
Behaviour of numeric scale and casting inconsistent / unspecified

### ISSUE THREAD

**Issue by proddata** [crate/crate#16478]
### CrateDB version

5.9.0-2024-07-19

### Problem description

`NUMERIC(p,s)`

From the documentation it is not quite clear what the min/max values of `p` and `s` is, nor what rules exist between them. Also no overflow (e.g. `123::NUMERIC(2)`) or rounding behavior (`123.12::NUMERIC(4,1)`) is defined.

The SQL standard says that the scale (`s`) must be smaller or equal then the precision (`p`). i.e. `0 <= s <=p`
PostgreSQL allows to deviate from that behavior (since v15) and allows  `s` to be bigger or smaller than `p` as well.

`NUMERIC(3, 5)` -> allowed input values ` -0.00999` to `0.00999`
⚠️ `0.01::NUMERIC(3,5) -> ERROR:  numeric field overflow`)

`NUMERIC(2, -3)` -> allowed input values ` -99000` to `99000`
⚠️ `12345::NUMERIC(2,-3) -> 12000`

### Steps to Reproduce

```sql
SELECT 123.123::NUMERIC(4,3) as res;
SELECT 0.01::NUMERIC(3,5) as res;
SELECT 12345::NUMERIC(2,-3);
SELECT 1.23::NUMERIC(2,1) + 1.23::NUMERIC(2,2);
```

### Actual Result

```sql
   res   
---------
 123.100 --> (!) NUMERIC(6,3)

   res   
---------
 0.01000

ERROR:  line 1:22: no viable alternative at input 'SELECT 12345::NUMERIC(2,-'

ERROR:  SignatureBinder.iterativeSolve does not converge after 4 iterations.
```

### Expected Result

```
ERROR:  numeric field overflow

ERROR:  numeric field overflow

 res 
-----
  12000

??????
```

**Comment by mfussenegger** [comment]
Clarified some parts with https://github.com/crate/crate/pull/16516 and https://github.com/crate/crate/pull/16516


- 1 & 2) I'd tend to keep the behavior for now but leave it undefined/undocumented until there's a concrete use-case for either direction
- 3) Added a restriction for negative scale
- 4) Can't reproduce the SignatureBinder error, but `numeric(2, 2)` is also no longer allowed.  With `1.23::NUMERIC(2,1) + 1.23::NUMERIC(3,2)` it appears to work

**Comment by proddata** [comment]
> For 1 & 2. I'd tend to keep the behavior for now but leave it undefined/undocumented until there's a concrete use-case for either direction

Don't you consider this as bug?

```sql
cr> CREATE TABLE t001  (num NUMERIC (4,2));
cr> INSERT INTO t001 VALUES (100.01);
cr> SELECT * FROM t001;
+-------+
|   num |
+-------+
| 100.0 |
+-------+
```

**Comment by matriv** [comment]
With NUMERIC support added to math functions (see: https://github.com/crate/crate/pull/16818, https://github.com/crate/crate/pull/16824, https://github.com/crate/crate/pull/16825), we return a generic `NUMERIC` with null precision and null scale, which doesn't allow for the result of those functions to be directly inserted into a table column:

```
cr>  create table num(x numeric(4, 2));
CREATE OK, 1 row affected (0.023 sec)
cr> insert into num select sqrt(12.34::numeric(4,2));
INSERT OK, 0 rows affected (0.016 sec)
cr> insert into num select sqrt(12.34::numeric(4,2))::numeric(38, 30);
INSERT OK, 1 row affected (0.011 sec)
cr> select * from num;
+------+
|    x |
+------+
| 3.51 |
+------+
SELECT 1 row in set (0.907 sec)
```
(1st insert fails)

**Comment by matriv** [comment]
@proddata Thx for reporting these issue. The fix will be available with the upcoming hotfix releases.
