### ISSUE TITLE
UDFs with parameters incorrectly looked up with names all lowercase when used in GENERATED column

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16549]
### CrateDB version

5.8.1

### CrateDB setup information

Number of nodes: 1

### Problem description

Trying to refer to an UDF with a camel case name in a generated column expression seems to work only if no parameters are passed

### Steps to Reproduce

```sql
CREATE FUNCTION "cAmEL1"()
RETURNS INT
LANGUAGE JAVASCRIPT
AS
$$	function cAmEL1() {	return 1;} $$;

CREATE TABLE tbl1 (		
		a TEXT,
		c GENERATED ALWAYS AS "cAmEL1"()
	);
--> OK
	
CREATE FUNCTION "cAmEL2"(field1 TEXT)
RETURNS INT
LANGUAGE JAVASCRIPT
AS
$$	function cAmEL2(field1) {return 1;} $$;

CREATE TABLE tbl2 (			
		a TEXT,
		c GENERATED ALWAYS AS "cAmEL2"(a)
	);
```

### Actual Result

```
UnsupportedFunctionException[Unknown function: doc.camel2(doc.tbl2.a)]
```
NB "camel2" all lowercase

### Expected Result

Table created ok

**Comment by matriv** [comment]
Thx for reporting this issue @hlcianfagna, it has been fixed and will be available with the next hotfix release.
