### ISSUE TITLE
Unexpected results when matching empty string with indexing disabled

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16567]
### CrateDB version

CrateDB 5.9.0-SNAPSHOT built a97d13e

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the last query returns an empty result, because the result of the second query is TRUE, which means that the WHERE clause in the last query should be evaluated to TRUE and thus return the row in the table.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE  TABLE  t0(c0 VARCHAR(500) INDEX OFF, PRIMARY KEY(c0)); -- INDEX OFF is important
INSERT INTO t0(c0) VALUES ('');
REFRESH TABLE t0;

SELECT t0.c0 FROM t0; -- ''
SELECT (t0.c0 LIKE '') FROM t0; -- TRUE
SELECT t0.c0 FROM t0 WHERE (t0.c0 LIKE '');
-- Expected: ''
-- Actual: empty table
```

### Actual Result

empty table

### Expected Result

one row

**Comment by matriv** [comment]
Thank you for reporting the issue @suyZhong ! The fix will be available with the next hotfix release.
