### ISSUE TITLE
Cluster-Level JWT Configuration

### ISSUE THREAD

**Issue by proddata** [crate/crate#16597]
### Problem Statement

Currently, CrateDB allows [JWT configuration on a per-user basis](https://cratedb.com/docs/crate/reference/en/latest/sql/statements/create-user.html#with). Each user must be set up individually with specific JWT settings, such as the issuer (iss), audience (aud), and username (username). 

```sql
CREATE USER john WITH (jwt = {"iss" = 'https://example.com', "username" = 'test@example.com', "aud" = 'test_aud'})
```

This approach becomes cumbersome when managing multiple users, especially in larger clusters. Additionally, it complicates cluster restoration, as each user’s JWT configuration must be manually reapplied, increasing the risk of errors. Also this prevents from using SQL commands like `CREATE USER` without knowledge about the complete JWT/JWK setup.

### Possible Solutions

A more efficient solution would be to allow JWT settings to be configured globally at the cluster level. By adding the relevant JWT configuration to the cluster’s configuration file `crate.yml`, it would eliminate the need for user-specific setups. For example, the configuration could look like:

```yaml
external_auth: 
  jwt:
    iss: https://example.com
    aud: test_aud
```

With this setup, any user can authenticate using JWT, provided the JWK supplies a valid token where the "username" matches the CrateDB user. This approach also simplifies the process of restoring clusters, as it avoids the need to reconfigure individual user settings. If a user has a custom JWT setup  (`CREATE USER john WITH (jwt =...)`)., it could override the global settings, ensuring that the change remains non-disruptive.

This approach also facilitates user mapping scenarios, where CrateDB Cloud users (or users from other external authentication providers) can be mapped to database users. By enabling this route, it reduces the risk of errors associated with the per-user level setup and removes the need for users to know specific JWT setup requirements when creating users with the `CREATE USER` command.

### Considered Alternatives

The only alternative is setting up JWT configurations individually for each user. This is error-prone, makes cluster restoration and automated user management more complex. 

--- 

### Implementation Details

- Per user configs (`CREATE USER xyz WITH ( jwt = ...)`) remains supported
- Per user configs override global configuration
- The CrateDB username is extracted from the `username` field in the provided JWT token.

also see PR: https://github.com/crate/crate/pull/16763/files

**Comment by mfussenegger** [comment]
One question here is how to deal with per user configs if there is a global jwt configuration. Options I see:
- User config overrides global config
- User config is ignored
- User config is an error and not allowed. (Might break snapshot restore - would either have to ignore or remove the config?)

Behavior could also be an additional setting (but I'd defer that to add it once we've a requirement for a different behavior. Whatever behavior we choose now can become the default once a setting would be added)

**Comment by proddata** [comment]
1. **User config overrides global config** – I think this is the preferred and least invasive solution. If a user has a custom JWT setup (e.g., `CREATE USER john WITH (jwt = ...)`), it would override the global settings, ensuring that the change remains non-disruptive.
2. **User config is ignored** – This could work as well, as the cluster administrator can decide which authentication method to use. However, it would lead to a user experience where you can set a configuration on the user, but it is ignored, which might be confusing.
3. **User config is an error and not allowed** – Since this would break many managed clusters and require fixes, I would strongly vote against this option.

**Comment by tomach** [comment]
> @tomach wdyt?

I would prefer option 1 as well. Most important thing is, that the changes do not break the setup for existing users which were already created `WITH (jwt = ...)`  after an upgrade to a version which supports the cluster-level config then.

**Comment by henrikingo** [comment]
I have a question from a security point of view:

On the face of it, this looks like a shared user, which is bad security. However, what we have here is:

* Each person still has their own username and password in the external system (issuer) example.com. Individual persons can change their password or be disabled by admin. So this is good.
* How will it work on the CrateDB side? Even if having one common user with necessary permissions etc is convenient, from an auditing perspective we would still want to know who specifically logged in. I assume this is satisfied with logging the username from the JWT json object? Will the JWT username ever be visible somewhere else? Should it?

**Comment by mfussenegger** [comment]
It's not a shared user, it's delegating authentication to an external service. (Yes, you're delegating trust - but that's not different to SSO). We're still doing the authorization.

All it means is that all users implicitly gain the JWT option - using the globally configured server.

**Comment by BaurzhanSakhariev** [comment]
- By default, old (user) jwt config is enabled. No change in functionality.
- When global setting is enabled, disable the old functionality.
- Long term, deprecate user jwt config

To be defined: Errors: CREATE / ALTER USER jwt=... when global config is enabled or warning
