### ISSUE TITLE
Filtering by `LIKE ANY` with array of regexes does not work

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#16593]
### CrateDB version

latest master

### Problem description

Please see the steps to reproduce.

### Steps to Reproduce

```
cr> create table t (a text[]);
CREATE OK, 1 row affected (0.189 sec)

cr> insert into t values (['a_', 'aa_']);
INSERT OK, 1 row affected (0.083 sec)

cr> select * from t where 'ab' like any(a);
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.024 sec)
```

### Actual Result

```
+---+
| a |
+---+
+---+
SELECT 0 rows in set (0.011 sec)

```

### Expected Result

```
+---------------+
| a             |
+---------------+
| ["a_", "aa_"] |
+---------------+
SELECT 1 row in set (0.005 sec)

```

**Comment by seut** [comment]
@jeeminso 
Maybe you just have a typo, but `'ab' like any(a)` will never match `a_` or `aa_`

**Comment by seut** [comment]
@jeeminso 
So yes `'a' like any(a)` will not match `a_` or `aa_`.
But this looks to my like expected behaviour, also PG behaves the same:

```
postgres=# create table t (a text[]);
CREATE TABLE
postgres=#  insert into t values (array['a_', 'aa_']);
INSERT 0 1
postgres=# select * from t where 'a' like any(a);
 a 
---
(0 rows)
```

**Comment by jeeminso** [comment]
```
postgres=# select * from t where 'a' like any(a);
```
you have a typo `'a'` > `'ab'`
Could you check https://www.db-fiddle.com/f/mandEVmvi6gRYL2yTQnHaK/0?

**Comment by seut** [comment]
Ah ok, I missed that the pattern is the stored value `a_`. sorry!

**Comment by jeeminso** [comment]
We need coherent picture of any/all behaviours, this will be handled as part of https://github.com/crate/crate/issues/16619, closing. https://github.com/crate/crate/pull/16605#issuecomment-2358193581
