### ISSUE TITLE
CrateDB 4.2bis: HTTP bulk operations and error handling with INSERT statements

### ISSUE THREAD

**Issue by amotl** [crate/crate#16617]
### CrateDB version

4.2 and higher

### CrateDB setup information

Standard Docker, single-node.
```
# CrateDB 4.1
docker run --rm -it --name=cratedb --publish=4200:4200 --env=CRATE_HEAP_SIZE=2g \
  crate:4.1 -Cdiscovery.type=single-node

# CrateDB 4.2
docker run --rm -it --name=cratedb --publish=4200:4200 --env=CRATE_HEAP_SIZE=2g \
  crate:4.2 -Cdiscovery.type=single-node
```

### Problem description

Relating to the [HTTP Bulk operations](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#bulk-operations) interface, and its [error handling](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling), we may have observed a few regressions already present since version 4.2.

Most probably, we are doing something wrong, so, at the same time of sharing this report, we are asking for better advise. The outcome might be improved documentation when applicable.

### References
- GH-12218
- GH-16433

### Steps to Reproduce

Install crash and HTTPie. Then, use a program `triage.sh` like this:
```shell
crash -c "drop table if exists t01;"
crash -c "create table t01 (name string, id int);"
http "127.0.0.1:4200/_sql?error_trace=true" \
  stmt="INSERT into t01 (name, id) values (?,?)" \
  bulk_args:='[["Mars", 1341], ["Sun", "foo"]]' --print bB
crash -c "refresh table t01;"
crash -c "select * from t01;"
```

- Per `bulk_args`, the INSERT operation will use the bulk endpoint.
- To receive extended error information, it also uses `error_trace=true`.
- The bulk payload includes two records, where the first one is valid as it matches the schema, but the second one is invalid because the string `foo` cannot be cast to `int`.

#### CrateDB <= 4.1
Previous CrateDB versions returned an [error code](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-codes) description if any of the records fails to insert.
```json
{
    "error": {
        "code": 4003,
        "message": "SQLActionException[ColumnValidationException: Validation failed for id: Cannot cast 'foo' to type integer]"
    }
}
```

#### CrateDB >= 4.2
Current CrateDB versions return a response of that shape:
```
{
    "cols": [],
    "duration": 31.547579,
    "results": [
        {
            "rowcount": -2
        },
        {
            "rowcount": -2
        }
    ]
}
```

### Evaluations

- CrateDB versions <= 4.1 respected the `error_trace` request option, later versions do not.

- CrateDB versions <= 4.1 returned an [error code description like advertised](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling), later versions do not. Is it advisable to update the documentation correspondingly, or can the error code / description message snippet be brought back in one way or another?

- ~~The documentation section about [bulk errors](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#bulk-errors) on the documentation suggests that there might be different `{"rowcount": ...}` items in the response, reflecting which record failed? We haven't been able to observe those kinds of responses up until now. Apparently, the result for **every record** is just `{"rowcount": -2}`, even for valid ones.~~

- ~~The same documentation section about [bulk errors](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#bulk-errors) suggests per~~
  > ~~Every bulk operation will be executed, independent if one of the operation fails.~~

  ~~that bulk operations may succeed partially, where valid records are inserted, while invalid ones are not. We have not been able to observe this. In our experiments, a failing batch does not insert valid records at all.~~

**Comment by amotl** [comment]
Hi. Sure enough, we now have been able to find bulk operations where both `{"rowcount": -2}` and `{"rowcount": 1}` bulk response items are returned from CrateDB.

On behalf of an I/O adapter for MongoDB, this patch evaluates that bulk response in order to discover the query parameters aka. records that failed, to be able to submit them sequentially, in order to relay relevant error messages to the user.

- https://github.com/crate/cratedb-toolkit/pull/262

In this spirit, partial bulk operations work well. We didn't investigate more closely why some bulk operations may fail completely, while others succeed partially. When we can come up with a concise reproducer, we will share it here.

**Comment by mfussenegger** [comment]
This was an intentional change:

https://github.com/crate/crate/blob/54105287c92be84a29d223e18a7e29ef676e7ae3/docs/appendices/release-notes/4.2.0.rst?plain=1#L53-L56

**Comment by ckurze** [comment]
I was able to reproduce the described initial behaviour that a whole batch of commands if failing, although one of the commands should succeed. Maybe it is related to the kind of error? DuplicateKeyError vs. SQLParseException in the case outlined below.

```
CREATE TABLE insert_test (id TEXT PRIMARY KEY, val OBJECT(DYNAMIC));

-- seed table
INSERT INTO insert_test(id, val) VALUES ('1', '{ "a": 1, "b": { "c": 1}, "d": [{"k": "k1", "v": 1}]}');
```


In the following steps, I want to execute the following inserts in bulk, which should throw the following exceptions (works correctly for single inserts):
```
-- insert works, no error to report
INSERT INTO insert_test(id, val) VALUES ('2', '{ "a": 2, "b": { "c": 2}, "d": [{"k": "k1", "v": 2}]}');

-- DuplicateKeyException[A document with the same primary key exists already]
INSERT INTO insert_test(id, val) VALUES ('2', '{ "a": 2, "b": { "c": 2}, "d": [{"k": "k1", "v": 2}]}');

-- SQLParseException[Cannot cast object element `a` with value `asdf` to type `bigint`]
INSERT INTO insert_test(id, val) VALUES ('3', '{ "a": "asdf", "b": { "c": 3}, "d": [{"k": "k1", "v": 3}]}');

-- SQLParseException[Cannot cast object element `d` with value `[{v=test, k=k1}]` to type `object_array`]
INSERT INTO insert_test(id, val) VALUES ('4', '{ "a": 4, "b": { "c": 4}, "d": [{"k": "k1", "v": "test"}]}');
```

Deleting existing rows from the table with id > 1 and bulk inserting only those with id=2 shows one success, one failure (as expected):
```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "DELETE FROM insert_test WHERE id > ?",          
  "args": [1]   
}                                                                                
EOF                                                                              
{"cols":[],"rows":[[]],"rowcount":1,"duration":1134.6106}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO insert_test(id, val) VALUES (?, ?)",
  "bulk_args": [
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"]
  ]
}
EOF
{"cols":[],"duration":46.493458,"results":[{"rowcount":1},{"rowcount":-2}]}
```

Deleting again and inserting a bulk of three docs leads to all operations failing, whereas the first statement should execute correctly.
```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "DELETE FROM insert_test WHERE id > ?",          
  "args": [1]   
}                                                                                
EOF                                                                             
{"cols":[],"rows":[[]],"rowcount":1,"duration":44.912624}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "SELECT * FROM insert_test"
}
EOF
{"cols":["id","val"],"rows":[["1",{"a":1,"b":{"c":1},"d":[{"v":1,"k":"k1"}]}]],"rowcount":1,"duration":117.64475}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO insert_test(id, val) VALUES (?, ?)",
  "bulk_args": [
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["3", "{ \"a\": \"asdf\", \"b\": { \"c\": 3}, \"d\": [{\"k\": \"k1\", \"v\": 3}]}"]
  ]
}  
EOF
{"cols":[],"duration":23.744835,"results":[{"rowcount":-2},{"rowcount":-2},{"rowcount":-2}]}
                                                      ^^^^

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "SELECT * FROM insert_test"
}
EOF
{"cols":["id","val"],"rows":[["1",{"a":1,"b":{"c":1},"d":[{"v":1,"k":"k1"}]}]],"rowcount":1,"duration":51.676292}
```

**Comment by ckurze** [comment]
Furthermore, adding error_trace=true as outline in the [documentation](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling) does not add error tracing.

```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql?error_trace=true' -d@- <<- EOF
{
  "stmt": "INSERT INTO insert_test(id, val) VALUES (?, ?)",
  "bulk_args": [
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["3", "{ \"a\": \"asdf\", \"b\": { \"c\": 3}, \"d\": [{\"k\": \"k1\", \"v\": 3}]}"]
  ]
}
EOF
{"cols":[],"duration":35.931416,"results":[{"rowcount":-2},{"rowcount":-2},{"rowcount":-2}]}

```

**Comment by amotl** [comment]
> This was an intentional change.

@mfussenegger: Thanks. The main reason about this ticket was to ask whether the documentation should be updated in one way or another, mainly concerned about the error codes and the `error_trace` request option.

> - CrateDB versions <= 4.1 respected the `error_trace` request option, later versions do not.
> - CrateDB versions <= 4.1 returned an [error code description like advertised](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling), later versions do not. Is it advisable to update the documentation correspondingly, or can the error code / description message snippet be brought back in one way or another?

This changelog item does not convey anything about changes to the error code mechanism as outlined in the documentation:

https://github.com/crate/crate/blob/54105287c92be84a29d223e18a7e29ef676e7ae3/docs/appendices/release-notes/4.2.0.rst?plain=1#L53-L56

NB @ckurze: I don't think this qualifies as a https://github.com/crate/crate/labels/bug.

**Comment by ckurze** [comment]
@amotl @henrikingo 

> NB @ckurze: I don't think this qualifies as a [ bug](https://github.com/crate/crate/labels/bug) Clear identification of incorrect behaviour .

Inserting two records leads to the correct results (1st record inserted, 2nd record not inserted and both reported correctly).

Adding a third record that should fail and not being able to insert the first one (although the table has been cleared before) is clearly a bug to me.

Detailled behaviur outlined in [this comment](https://github.com/crate/crate/issues/16617#issuecomment-2365175867)

**Comment by henrikingo** [comment]
@ckurze I believe since your third row errors already at the SQL parsing state, none of the rows get to execute. 

Not familiar with the cratedb implementation, but in general I also wouldn't assume that a batch that does execute will do so in any particular order.

Finally, please don't flip flop the labels. Triaging and prioritizing tickets is the responsibility of the engineering team that receives the ticket. You are welcome to lobby for your case with questions, comments and additional examples.

**Comment by henrikingo** [comment]
@amotl I believe this ticket was originally  to discuss potential need to clarify documentation? Perhaps you could summarize what questions you still have in that area? Just trying to make sure your original questions are addressed.

**Comment by ckurze** [comment]
@henrikingo I created a new issued based on my comment for separate analysis. https://github.com/crate/crate/issues/16683

**Comment by amotl** [comment]
@henrikingo: I was just asking to offer updating the documentation, and wanted to get clarity about those details: a) `error_trace` request option, b) error codes.

- CrateDB versions <= 4.1 respected the `error_trace` request option, later versions do not.

- CrateDB versions <= 4.1 returned an [error code description like advertised](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling), later versions do not. Is it advisable to update the documentation correspondingly, or can the error code / description message snippet be brought back in one way or another?

Citing @ckurze:
> Furthermore, adding error_trace=true as outline in the [documentation](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling) does not add error tracing for bulk inserts, maybe because of the [decision taken in 4.2 to not report errors as outlined above](https://github.com/crate/crate/blob/54105287c92be84a29d223e18a7e29ef676e7ae3/docs/appendices/release-notes/4.2.0.rst?plain=1#L53-L56). Works for single inserts using the args (instead of bulk_args) parameter though. The documentation should outline this fact.

**Comment by amotl** [comment]
I've just submitted a documentation patch based on a few observations shared here.

- https://github.com/crate/crate/pull/16733

**Comment by matriv** [comment]
thank you @amotl !

**Comment by amotl** [comment]
Thanks for your suggestions for improvements. I guess it is safe to close this issue now? Is there anything inside that wants to be improved on behalf of documentation updates, or are we all set now?
