### ISSUE TITLE
Unexpected result when querying partitioned table with `CASE WHEN`

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16614]
### CrateDB version

CrateDB 5.9.0-SNAPSHOT built 848ca13

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the test case below. It is unexpected that the last query returns no row because the result of the second query has three rows of TRUE, which means that the last query should thus return three rows in the table.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t1;

CREATE  TABLE  t1(c0 TEXT, c1 TEXT) PARTITIONED BY (c0);
INSERT INTO t1(c1, c0) VALUES ('B', 'B'), ('C', 'C'), ('D', ''), ('A', 'A');
REFRESH TABLE t1;

SELECT t1.c0 FROM t1; -- '', 'A', 'B', 'C'
SELECT (NOT (CASE t1.c0 WHEN '' THEN TRUE WHEN 'E' THEN ((t1.c1) IS NOT NULL) ELSE t1.c0 > 'a' END )) FROM t1; -- FALSE, TRUE, TRUE, TRUE
SELECT t1.c0 FROM t1 WHERE (NOT (CASE t1.c0 WHEN '' THEN TRUE WHEN 'E' THEN ((t1.c1) IS NOT NULL) ELSE t1.c0 > 'a' END ));
-- Expected: 'A', 'B', 'C' (3 rows)
-- Actual: 0 row
```

### Actual Result

empty table

### Expected Result

Three rows in the table.

**Comment by matriv** [comment]
Thx for reporting @suyZhong ! The issue has been fixed, and the fix will be available with the next hotfix release.
