### ISSUE TITLE
Conflicting column definitions accepted in OBJECT(DYNAMIC)

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16640]
### CrateDB version

5.8.3 , 5.8.2

### CrateDB setup information

Tested both single node and multi-node

### Problem description

Dealing with a complex (and incorrect) `CREATE TABLE` statement, with conflicting field definitions within an `OBJECT(DYNAMIC)`, the issue is not flagged and the field is added to the schema with one of the multiple definitions.

### Steps to Reproduce

```sql
CREATE TABLE tbl1 (obj OBJECT(DYNAMIC) AS (a BOOLEAN,a INT));
```

### Actual Result

```
CREATE OK, 1 row affected (0.298 sec)
cr> SHOW CREATE TABLE tbl1;
+-----------------------------------------------------+
| SHOW CREATE TABLE doc.tbl1                          |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."tbl1" (           |
|    "obj" OBJECT(DYNAMIC) AS (                       |
|       "a" INTEGER                                   |
|    )                                                |
| )                                                   |
```

### Expected Result

```
SQLParseException[column "a" specified more than once]
```

**Comment by seut** [comment]
@hlcianfagna 
We've fixed this by #16642, will be released by the next `5.8.4` hotfix release. Thank you for reporting.
