### ISSUE TITLE
Trying CrateDB without installing on ARM based mac is not possible

### ISSUE THREAD

**Issue by geragray** [crate/crate#16679]
### CrateDB version

Any

### Problem description

Docs refer to a way to try out CrateDB without installing, but it is not possible on ARM based Mac https://cratedb.com/docs/guide/install/adhoc.html#install-adhoc

Github readme refers to the same https://github.com/crate/crate/blob/ad6029c2c6d2bea6a85f58ac3ad70900cf64eee2/README.rst?plain=1#L78

### Steps to Reproduce

Run
`bash -c "$(curl -L https://try.crate.io/)"`

### Actual Result

Get “The architecture: arm64 is not supported” error.

### Expected Result

No error

**Comment by mfussenegger** [comment]
Does the following work on ARM based Mac?:

```
docker run --publish 4200:4200 --publish 5432:5432 --env CRATE_HEAP_SIZE=1g crate -Cdiscovery.type=single-node
```

If so, we could consider dropping the `try.crate.io` script instead of maintaining that too.

**Comment by seut** [comment]
> Does the following work on ARM based Mac?:

Yes this works at my Silicon M3 machine, it uses the linux aarch64 docker image.
```
% docker run --publish 4200:4200 --publish 5432:5432 --env CRATE_HEAP_SIZE=1g crate -Cdiscovery.type=single-node
WARNING: A restricted method in java.lang.foreign.Linker has been called
WARNING: java.lang.foreign.Linker::downcallHandle has been called by org.apache.lucene.store.PosixNativeAccess in an unnamed module
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

Sep 30, 2024 10:05:31 AM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
INFO: Using MemorySegmentIndexInput and native madvise support with Java 21 or later; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
[2024-09-30T10:05:31,126][INFO ][o.e.e.NodeEnvironment    ] [Dent de Perroc] using [1] data paths, mounts [[/data (/dev/vda1)]], net usable_space [14.2gb], net total_space [62.6gb], types [ext4]
[2024-09-30T10:05:31,127][INFO ][o.e.e.NodeEnvironment    ] [Dent de Perroc] heap size [1gb], compressed ordinary object pointers [true]
[2024-09-30T10:05:31,141][INFO ][o.e.n.Node               ] [Dent de Perroc] node name [Dent de Perroc], node ID [-EUNemztSLmJkII1qK38-w], cluster name [crate]
[2024-09-30T10:05:31,142][INFO ][o.e.n.Node               ] [Dent de Perroc] version[5.8.3], pid[1], build[b9e666b/NA], OS[Linux/6.10.4-linuxkit/aarch64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/22.0.2+9]
```

Also an amd64 docker image worked probably due to Apple's Rosetta emulation, I still had CrateDB 5.5.2 amd64 loaded from my old Intel Mac installation before I fetched the latest one:
```
docker run --publish 4200:4200 --publish 5432:5432 --env CRATE_HEAP_SIZE=1g crate -Cdiscovery.type=single-node
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Sep 30, 2024 10:04:26 AM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
INFO: Using MemorySegmentIndexInput with Java 21; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
[2024-09-30T10:04:26,120][INFO ][o.e.e.NodeEnvironment    ] [Piz Sesvenna] using [1] data paths, mounts [[/data (/dev/vda1)]], net usable_space [15.1gb], net total_space [62.6gb], types [ext4]
[2024-09-30T10:04:26,122][INFO ][o.e.e.NodeEnvironment    ] [Piz Sesvenna] heap size [1gb], compressed ordinary object pointers [true]
[2024-09-30T10:04:26,165][INFO ][o.e.n.Node               ] [Piz Sesvenna] node name [Piz Sesvenna], node ID [8UakY73QQv--0S-TOqE_Zg], cluster name [crate]
[2024-09-30T10:04:26,169][INFO ][o.e.n.Node               ] [Piz Sesvenna] version[5.5.2], pid[1], build[1c73478/NA], OS[Linux/6.10.4-linuxkit/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/21.0.1+12-LTS]
```

**Comment by matriv** [comment]
+1 to go ahead with docker.

**Comment by mfussenegger** [comment]
Outcome from refinement: 

- Remove try.crate.io references from readme and docs. Replace with docker run
- No further action for now in regards to Mac ARM64 distribution/packages

**Comment by proddata** [comment]
Could we consider adding ARM builds for the nightly **Docker** images (`crate/crate`)? While **amd64** images do run on Macs, I've experienced significant performance issues in certain cases. Additionally, there are more and more non-Mac machines with ARM-based processors, as well as several generations of ARM-based servers on AWS and other hosting providers.

Also, perhaps we should consider not offering the Mac tarball at all and instead direct users to the Docker image, as it often leads to trust issues with the bundled JVM and isn't particularly user-friendly.

**Comment by mfussenegger** [comment]
try.crate.io are removed from the crate readme and from the guide with https://github.com/crate/cratedb-guide/pull/125 and https://github.com/crate/crate/pull/16712

> Could we consider adding ARM builds for the nightly Docker images (crate/crate)? While amd64 images do run on Macs, I've experienced significant performance issues in certain cases. 

That would depend on having mac-arm tarballs

> Additionally, there are more and more non-Mac machines with ARM-based processors, as well as several generations of ARM-based servers on AWS and other hosting providers.

linux-arm images and tarballs exist for releases. (and are less problematic, because opposed to Mac, Linux CI runners aren't a pain to setup)

Closing this because the original issue has been addressed. Feel free to create an issue to track distribution of Mac ARM tarballs & docker images.

**Comment by proddata** [comment]
> That would depend on having mac-arm tarballs

Why would linux arm docker images depend on having mac-arm tarballs?

> (and are less problematic, because opposed to Mac, Linux CI runners aren't a pain to setup)

How does this relate with the request to have linux arm docker images available?

---

will considering opening another issue

**Comment by mfussenegger** [comment]
> Why would linux arm docker images depend on having mac-arm tarballs?

Based on you mentioning "While amd64 images do run on Mac" in the next sentence I assumed you're talking about mac-arm64 docker images. 

But it's the same for linux-arm64: Docker images depend on having a tarball available. The nightly builds are currently only for linux-x64. But that's easier to extend as we have the Jenkins runners for that.
