### ISSUE TITLE
Unable to INSERT multiline string within OBJECT(IGNORED) from a number of clients

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16676]
### CrateDB version

5.8.3 and nightly-5.9.0-2024-09-25-00-02

### CrateDB setup information

Single node

### Problem description

I have a JSON payload which has multiline strings in some fields.

Perhaps the carriage return should be escaped, but the `curl` statement in the repro steps works so I would have expected running the `INSERT` statements manually would have also worked, but it does not. Perhaps this is a client side issue but I have tested and reproed this with `crash`, the Admin UI, the Cloud SQL console, and with DBeaver.

### Steps to Reproduce

```sql
create table tbl1 (obj object(ignored));
```

```bash
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO tbl1 (obj)
          VALUES (?)",
  "bulk_args": [
    [{"a":"first line
        secondline"}]
  ]
}
EOF
```
```
{"cols":[],"duration":16.358616,"results":[{"rowcount":1}]}
```

```sql
insert into tbl1
select {"a"='first line 
	secondline'};
-- INSERT OK, 1 row affected (0.011 sec)

insert into tbl1
select $$ {"a":"first line 
	secondline"}$$;
```

### Actual Result

```
INSERT OK, 0 rows affected
```

### Expected Result

```
INSERT OK, 1 rows affected
```

**Comment by proddata** [comment]
JSON does not allow unescaped control characters (like newlines, tabs, etc.) in strings. To include control characters, you must use backslash escapes, such as \n for newlines, \t for tabs, etc.

**Comment by hlcianfagna** [comment]
Thank you @proddata , it seems indeed `curl` is altering the payload before sending it, it does not seem to be adding `\n` , but the control character is indeed gone, so CrateDB's behaviour is correct I think, just something to be aware of. Apologies for the confusion.

**Comment by matriv** [comment]
Thx both for figuring it out!
