### ISSUE TITLE
Batched inserts sometimes fail completely, while some of the operations should be excutable

### ISSUE THREAD

**Issue by ckurze** [crate/crate#16683]
Sometmes a whole batch of commands if failing, although one of the commands should succeed. Maybe it is related to the kind of error? DuplicateKeyError vs. SQLParseException in the case outlined below.

```
CREATE TABLE insert_test (id TEXT PRIMARY KEY, val OBJECT(DYNAMIC));

-- seed table
INSERT INTO insert_test(id, val) VALUES ('1', '{ "a": 1, "b": { "c": 1}, "d": [{"k": "k1", "v": 1}]}');
```

In the following steps, I want to execute the following inserts in bulk, which should throw the following exceptions (works correctly for single inserts):
```
-- insert works, no error to report
INSERT INTO insert_test(id, val) VALUES ('2', '{ "a": 2, "b": { "c": 2}, "d": [{"k": "k1", "v": 2}]}');

-- DuplicateKeyException[A document with the same primary key exists already]
INSERT INTO insert_test(id, val) VALUES ('2', '{ "a": 2, "b": { "c": 2}, "d": [{"k": "k1", "v": 2}]}');

-- SQLParseException[Cannot cast object element `a` with value `asdf` to type `bigint`]
INSERT INTO insert_test(id, val) VALUES ('3', '{ "a": "asdf", "b": { "c": 3}, "d": [{"k": "k1", "v": 3}]}');

-- SQLParseException[Cannot cast object element `d` with value `[{v=test, k=k1}]` to type `object_array`]
INSERT INTO insert_test(id, val) VALUES ('4', '{ "a": 4, "b": { "c": 4}, "d": [{"k": "k1", "v": "test"}]}');
```

Deleting existing rows from the table with id > 1 and bulk inserting only those with id=2 shows one success, one failure (as expected):
```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "DELETE FROM insert_test WHERE id > ?",          
  "args": [1]   
}                                                                                
EOF                                                                              
{"cols":[],"rows":[[]],"rowcount":1,"duration":1134.6106}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO insert_test(id, val) VALUES (?, ?)",
  "bulk_args": [
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"]
  ]
}
EOF
{"cols":[],"duration":46.493458,"results":[{"rowcount":1},{"rowcount":-2}]}
```

Deleting again and inserting a bulk of three docs leads to all operations failing, whereas the first statement should execute correctly.
```
curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "DELETE FROM insert_test WHERE id > ?",          
  "args": [1]   
}                                                                                
EOF                                                                             
{"cols":[],"rows":[[]],"rowcount":1,"duration":44.912624}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "SELECT * FROM insert_test"
}
EOF
{"cols":["id","val"],"rows":[["1",{"a":1,"b":{"c":1},"d":[{"v":1,"k":"k1"}]}]],"rowcount":1,"duration":117.64475}

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "INSERT INTO insert_test(id, val) VALUES (?, ?)",
  "bulk_args": [
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["2", "{ \"a\": 2, \"b\": { \"c\": 2}, \"d\": [{\"k\": \"k1\", \"v\": 2}]}"],
    ["3", "{ \"a\": \"asdf\", \"b\": { \"c\": 3}, \"d\": [{\"k\": \"k1\", \"v\": 3}]}"]
  ]
}  
EOF
{"cols":[],"duration":23.744835,"results":[{"rowcount":-2},{"rowcount":-2},{"rowcount":-2}]}
                                                      ^^^^

curl -sS -H 'Content-Type: application/json' \
-X POST '127.0.0.1:4200/_sql' -d@- <<- EOF
{
  "stmt": "SELECT * FROM insert_test"
}
EOF
{"cols":["id","val"],"rows":[["1",{"a":1,"b":{"c":1},"d":[{"v":1,"k":"k1"}]}]],"rowcount":1,"duration":51.676292}
```

_Originally posted by @ckurze in https://github.com/crate/crate/issues/16617#issuecomment-2365175867_

**Comment by henrikingo** [comment]
So I had looked into this a little and it seems to me it is like you suspect, that the SQLParseException prevents the entire block from even starting to execute.

The more general problem is that the bulk inserts are NOT atomic, even if you send them to the database together. If there is one error, it's a bit subjective what a user would expect or prefer to happen to the other rows.

**Comment by matriv** [comment]
Maybe we need to clarify this better in docs? https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#error-handling

**Comment by proddata** [comment]
I believe the main concern isn’t that bulk requests partially fail or succeed, but rather the lack of transparency around why they fail.

Currently, when a bulk request fails, users often have to revert to single inserts or standard requests, which becomes particularly frustrating with “early” failures. For example, if a bulk request contains 10,000 records and one record has an erroneous value, identifying the problematic record may require executing 10,000 individual statements. In contrast, with “late” failures, at least only the erroneous records need to be retried, making the process more efficient. But still it would be better to get at least the error code for why the records failed.

**Comment by matriv** [comment]
Of course, this is described here: https://github.com/crate/crate/issues/16649
I tried to clarify only the distinction of bulk failing as a whole in a pre-execution step, and the partial success when errors are runtime (execution has started).

**Comment by mfussenegger** [comment]
- This https://github.com/crate/crate/issues/16683#issuecomment-2376499787 comment explains the behavior. PR for docs improvement is welcome. - https://github.com/crate/crate/issues/16617#issuecomment-2365175867 still tracks this
- https://github.com/crate/crate/issues/16649 covers adding errors per bulk item
- https://github.com/crate/crate/issues/12218 Covers error reporting improvements despite partial success.

Closing as duplicate

**Comment by amotl** [comment]
@matriv: I've just submitted a documentation patch based on [your suggestion](https://github.com/crate/crate/issues/16683#issuecomment-2376499787). Thanks!

- https://github.com/crate/crate/pull/16733
