### ISSUE TITLE
Log long running queries before they complete

### ISSUE THREAD

**Issue by henrikingo** [crate/crate#16826]
### Problem Statement

When diagnosing cluster overload problems, or a crash, one thing to review is what queries were running on the server at the time of the issue. In particular, a possible reason to an overload situation would be a single long running query, perhaps typed by hand by a user, that consumes all resources. However, since CrateDB logs queries only when they have completed (because it logs duration of the query), then if the cluster was restarted or crashed, the query doesn't complete and is never logged.

Note that it is possible to see currently running queries in `sys.jobs`. However, often the cluster is so overloaded it is not possible to open a connection, nor to query sys.* tables.

### Possible Solutions

Log queries when they have started. Note that it is not necessary to log all queries, rather, for this particular problem statement, it is sufficient to only log the slowest queries. So for example, all queries that are shorter than N seconds, would be logged as normal when they end. Queries that run longer than N seconds would be logged at that point, and then again once they complete.

### Considered Alternatives

for the stated problem, it would also be sufficient to somehow dump all unfinished queries when a node is restarting or crashing. However, this would be unreliable. Especially in OOM cases there's no time for the process to do anything like that. It is killed from the outside and there isn't much we can do a t that point.

**Comment by mfussenegger** [comment]
> it would also be sufficient to somehow dump all unfinished queries when a node is restarting or crashing. However, this would be unreliable. Especially in OOM cases there's no time for the process to do anything like that
This isn't unre

The default configuration of CrateDB tells the JVM to take a heap dump if a node crashes due to an OOM.
This is realiable and the heap dump will contain all queries/operations still running.

The problem is if the node doesn't crash and I'm not sure if a "slow query log" as described here would help. One problem is that if one query is overloading the node - especially if it's due to high memory allocations/GC pressure - it affects other queries running on the node too, so _all_ queries will become slow. 
Then you run into the problem described here: https://github.com/crate/crate/issues/14938

**Comment by henrikingo** [comment]
> it affects other queries running on the node too, so all queries will become slow.

This can be avoided by setting the threshold time high enough. By definition, what we're trying to do here, is to capture queries that caused a cluster crash or restart. So either the slow / long running query happens often, and there are queries in the log that have completed before. Or, it is one (maybe mistyped / mistought) query that didn't complete ever.  It is sufficient to just capture the latter case. In theory the set of queries that would be logged with this feature enabled is small. 

In practice setting the threshold high enough but not too high might be difficult. Of course it could be set dynamically to 0.001% of all queries, or something like that.

**Comment by mfussenegger** [comment]
> This can be avoided by setting the threshold time high enough

I don't see how? If you have a high GC load that affects all queries. Even a `select 1` could start taking up seconds if it has to wait in a queue because all other threads are busy and if GC is eating up all CPU time.

The issue reports indicate that the cluster is often not reachable or that the admin-ui no longer works. That is an indication that ^ is happening - otherwise the cluster would still be responsive.

This is one reason we added `statement_timeout` & `memory.operation_limit` - to cancel queries _before_ they impact the cluster stability. Or the reason we did work like https://github.com/crate/crate/pull/13290


> what we're trying to do here, is to capture queries that caused a cluster crash or restart

Again. Cluster crashing with OOM causes a heap dump to be taken - that has all the information one needs, in a better format than what logs would provide.

**Comment by henrikingo** [comment]
> Again. Cluster crashing with OOM causes a heap dump to be taken - that has all the information one needs, in a better format than what logs would provide.

Yes, this part is clear and solves half of the problem.

> I don't see how? If you have a high GC load that affects all queries. Even a select 1 could start taking up seconds if it has to wait in a queue because all other threads are busy and if GC is eating up all CPU time.

Ok, if it's the case that one  query almost immediately impacts performance of other queries and they all therefor are stuck and accumulating somewhat identical response times, then I agree all those queries would end up in the log. But in this case those queries would nevertheless be delineated in time, so that djring normal operation, there would be little to none log entries, and this would only trigger after system stalled for longer than the threshold.

But focusing on the JFRs then...

In parallel the cloud team is working on automating a stream of JFRs to be stored in Pyroscope and vizualized in Grafana. If we have this, then it seems we don't need additional logging. (This ticket would be redundant, with the exception that logging probably for some user is more convenient/easierl

**Comment by mfussenegger** [comment]
> Ok, if it's the case that one query almost immediately impacts performance of other queries and they all therefor are stuck and accumulating somewhat identical response times, then I agree all those queries would end up in the log

If this weren't the case you could connect to the cluster, query `sys.jobs` and order by duration and get the info you need.
To get to that point, we should rather invest in https://github.com/crate/crate/issues/14068 where I've some new ideas to explore - but what would really help for that would be to have some use-cases/loads we can run that bring a cluster into an unresponsive state

**Comment by mfussenegger** [comment]
To summarize, three scenarios:

- Cluster has high load, but is responsive: Query sys.jobs to figure out what's running or look at always-on JFR/pyroscope profile
- Cluster has high load, is unresponsive but recovers eventually: Look at always-on profiling data or wait until it's recovered and then check sys.jobs_log (maybe configure filters or persistent logging for slow queries to ensure the problematic queries are kept)
- Cluster crashes with OOM: You'll have a heap dump on disk which can be analyzed

**Comment by henrikingo** [comment]
@mfussenegger For the second bullet point, your position is to wait it out and not restart the node?

**Comment by mfussenegger** [comment]
>  For the second bullet point, your position is to wait it out and not restart the node?

Depends of course on the context.
If it's an environment where you can affort waiting - it would allow to query the sys jobs tables afterwards.
If you don't want to / can't wait, it helps to first get all information you can:  JFR + heap-dump
