### ISSUE TITLE
Returned SQLParseException might be incorrect when using a parameterized query.

### ISSUE THREAD

**Issue by proddata** [crate/crate#16947]
### CrateDB version

5.9.2

### CrateDB setup information

single node

### Problem description

It appears that using a parameterized query can partially obscure a type error. I’m not entirely sure if this qualifies as a bug. Additionally, I believe that in many cases, using parameters for the UPDATE SET clause can be avoided by leveraging the excluded table.

### Steps to Reproduce

```sql
CREATE TABLE t01 (
      id TEXT PRIMARY KEY,
      obj OBJECT AS (
        txt ARRAY(TEXT)
      )
    );
 INSERT INTO t01 (id,obj) VALUES ('a', '{"x":"xx","y":["yy"]}');
```

json using http endpoint

```json
{
  "stmt": "INSERT INTO t01 (id,obj) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET obj = ?",
  "args": ["a", {"x":"xx","y":"yy"}, {"x":"xx","y":"yy"}]
}
```

### Actual Result

```json
{
  "error": {
    "message": "SQLParseException[Cannot cast value `{x=xx, y=yy}` to type `object`]",
    "code": 4000
  }
}
```

This might seem like the provided value cannot be case to an `object`, however the issue is the underlying type mismatch of column `y`

### Expected Result

```json
{
  "error": {
    "message": "SQLParseException[Cannot cast object element `y` with value `yy` to type `text_array`]",
    "code": 4000
  }
}
```

as seen with

```json
{
  "stmt": "INSERT INTO t01 (id,obj) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET obj = excluded.obj",
  "args": ["a", {"x":"xx","y":"yy"}]
}
```

**Comment by seut** [comment]
@proddata Thank you for reporting, it's a bug and fixed by #16978. Will be included in the next `5.9.3` hotfix released.
