### ISSUE TITLE
Unexpected result when `RIGHT JOIN` a subquery

### ISSUE THREAD

**Issue by suyZhong** [crate/crate#16951]
### CrateDB version

CrateDB 5.10.0-SNAPSHOT built 87c6dfa

### CrateDB setup information

Manual build following the instructions here: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Consider the following test case. The third query returns an unexpected result: The second query returns `NULL NULL 1`, and the third query with the filter which is the negation should return an empty set. However, one row is fetched.

Besides, PostgreSQL returns `'' NULL 1` for the first query.

### Steps to Reproduce

```sql
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;

CREATE  TABLE  t0(c1 VARCHAR(500));
CREATE  TABLE  t1(c0 VARCHAR(500));
INSERT INTO t0(c1) VALUES ('');
REFRESH TABLE t0;



SELECT * FROM t0, t1 RIGHT  JOIN  (SELECT 1 ) AS sub0  ON true; 
-- CrateDB: NULL NULL 1 
-- Postgres: '' NULL 1

SELECT * FROM t0, t1 RIGHT  JOIN  (SELECT 1 ) AS sub0  ON true WHERE ((t0.c1)>=(t0.c1)); -- NULL NULL 1
SELECT * FROM t0, t1 RIGHT  JOIN  (SELECT 1 ) AS sub0  ON true WHERE (NOT ((t0.c1)>=(t0.c1))); 
-- Expected: empty result
-- Actual: NULL NULL 1
```

### Actual Result

As mentioned above

### Expected Result

As mentioned above.

**Comment by matriv** [comment]
For the first query without the filtering
--------------------------------------
if I insert value `'foo'` in `t0` instead of `''`:
```
matriv=# insert into t0 values('foo');
INSERT 0 1
matriv=# SELECT * FROM t0, t1 RIGHT  JOIN  (SELECT 1 ) AS sub0  ON true;
 c1  | c0 | ?column?
-----+----+----------
 foo |    |        1
(1 row)

matriv=# select * from t0;
 c1
-----
 foo
(1 row)

matriv=# select * from t1;
 c0
----
(0 rows)

matriv=# select * from t0, t1;
 c1 | c0
----+----
(0 rows)

matriv=# SELECT * FROM t0, t1 RIGHT  JOIN  (SELECT 1 ) AS sub0  ON true;
 c1  | c0 | ?column?
-----+----+----------
 foo |    |        1
(1 row)

matriv=# SELECT * FROM (SELECT * FROM t0, t1) as sub1 RIGHT  JOIN  (SELECT 1 ) AS sub2  ON true;
 c1 | c0 | ?column?
----+----+----------
    |    |        1
(1 row)
```
So it seems that postgres gives precedence to `t1 RIGHT JOIN (SELECT 1)`, where as CrateDB follows the left-to-right order of the joins. Need to check with SQL standard if this is defined.

**Comment by matriv** [comment]
Haven't found anything in SQL specification about this behavior. From postgres:
https://www.postgresql.org/docs/current/tutorial-join.html:
```
This syntax pre-dates the JOIN/ON syntax, which was introduced in SQL-92. The tables are simply listed in the FROM clause, and the comparison expression is added to the WHERE clause. The results from this older implicit syntax and the newer explicit JOIN/ON syntax are identical. But for a reader of the query, the explicit syntax makes its meaning easier to understand: The join condition is introduced by its own key word whereas previously the condition was mixed into the WHERE clause together with other conditions.
``` but this seems to not be true based on the example in the previous comment.
additionally: https://www.postgresql.org/docs/17/explicit-joins.html
```
Explicit inner join syntax (INNER JOIN, CROSS JOIN, or unadorned JOIN) is semantically the same as listing the input relations in FROM, so it does not constrain the join order.
```
also contradicts with the behavior.

**Comment by matriv** [comment]
For the second query with the filtering
--------------------------------------
Postgres (using the syntax to ensure the same join order):
```
matriv=# SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE ((t0.c1)>=(t0.c1));
 c1 | c0 | ?column?
----+----+----------
(0 rows)

matriv=# explain verbose SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE ((t0.c1)>=(t0.c1));
                               QUERY PLAN
-------------------------------------------------------------------------
 Nested Loop  (cost=0.00..117.25 rows=7500 width=1036)
   Output: t0.c1, t1.c0, 1
   ->  Seq Scan on public.t1  (cost=0.00..11.50 rows=150 width=516)
         Output: t1.c0
   ->  Materialize  (cost=0.00..12.12 rows=50 width=516)
         Output: t0.c1
         ->  Seq Scan on public.t0  (cost=0.00..11.88 rows=50 width=516)
               Output: t0.c1
               Filter: ((t0.c1)::text >= (t0.c1)::text)
(9 rows)

matriv=# select * from t0 where ((t0.c1)>=(t0.c1));
 c1
-----
 foo


matriv=# SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE NOT ((t0.c1)>=(t0.c1));
 c1 | c0 | ?column?
----+----+----------
(0 rows)

matriv=# explain verbose SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE NOT ((t0.c1)>=(t0.c1));
                               QUERY PLAN
-------------------------------------------------------------------------
 Nested Loop  (cost=0.00..117.25 rows=7500 width=1036)
   Output: t0.c1, t1.c0, 1
   ->  Seq Scan on public.t1  (cost=0.00..11.50 rows=150 width=516)
         Output: t1.c0
   ->  Materialize  (cost=0.00..12.12 rows=50 width=516)
         Output: t0.c1
         ->  Seq Scan on public.t0  (cost=0.00..11.88 rows=50 width=516)
               Output: t0.c1
               Filter: ((t0.c1)::text < (t0.c1)::text)
(9 rows)

matriv=# select * from t0 where NOT ((t0.c1)>=(t0.c1));
 c1
----
(0 rows)
```

CrateDB:
cr> SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE ((t0.c1)>=(t0.c1));
+------+------+---+
| c1   | c0   | 1 |
+------+------+---+
| NULL | NULL | 1 |
+------+------+---+
SELECT 1 row in set (0.010 sec)
cr> explain verbose SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE ((t0.c1)>=(t0.c1));
+------------------------------------------------------+-------------------------------------------------------------+
| STEP                                                 | QUERY PLAN                                                  |
+------------------------------------------------------+-------------------------------------------------------------+
| Initial logical plan                                 | Join[RIGHT | true] (rows=unknown)                           |
|                                                      |   ├ Filter[(c1 >= c1)] (rows=0)                             |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                    |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)       |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)       |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_move_constant_join_conditions_beneath_join | Join[RIGHT | true] (rows=unknown)                           |
|                                                      |   ├ Filter[(c1 >= c1)] (rows=0)                             |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                    |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)       |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)       |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_rewrite_join_plan                          | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ Filter[(c1 >= c1)] (rows=0)                             |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                    |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)       |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)       |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_move_filter_beneath_join                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ Join[INNER | true] (rows=unknown)                       |
|                                                      |   │  ├ Filter[(c1 >= c1)] (rows=0)                          |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)      |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)         |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_move_constant_join_conditions_beneath_join | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ Join[INNER | true] (rows=unknown)                       |
|                                                      |   │  ├ Filter[(c1 >= c1)] (rows=0)                          |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)      |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)         |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_rewrite_join_plan                          | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)             |
|                                                      |   │  ├ Filter[(c1 >= c1)] (rows=0)                          |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)      |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)         |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_merge_filter_and_collect                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)             |
|                                                      |   │  ├ Collect[doc.t0 | [c1] | (c1 >= c1)] (rows=unknown)   |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)         |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ Eval[1] (rows=unknown)                                |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown) |
| optimizer_remove_redundant_eval                      | TableFunction[empty_row | [1] | true] (rows=unknown)        |
| Final logical plan                                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                 |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)             |
|                                                      |   │  ├ Collect[doc.t0 | [c1] | (c1 >= c1)] (rows=unknown)   |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)         |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                      |
|                                                      |     └ TableFunction[empty_row | [1] | true] (rows=unknown)  |
+------------------------------------------------------+-------------------------------------------------------------+
EXPLAIN 9 rows in set (0.009 sec)

cr> select * from t0 WHERE ((t0.c1)>=(t0.c1));
+-----+
| c1  |
+-----+
| foo |
+-----+
SELECT 1 row in set (0.010 sec)



cr> SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE NOT ((t0.c1)>=(t0.c1));
+------+------+---+
| c1   | c0   | 1 |
+------+------+---+
| NULL | NULL | 1 |
+------+------+---+
SELECT 1 row in set (0.014 sec)
cr> explain verbose SELECT * FROM t0 JOIN t1 ON TRUE RIGHT JOIN (SELECT 1) AS sub0  ON true WHERE NOT ((t0.c1)>=(t0.c1));
+------------------------------------------------------+-----------------------------------------------------------------+
| STEP                                                 | QUERY PLAN                                                      |
+------------------------------------------------------+-----------------------------------------------------------------+
| Initial logical plan                                 | Join[RIGHT | true] (rows=unknown)                               |
|                                                      |   ├ Filter[(NOT (c1 >= c1))] (rows=0)                           |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                        |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)           |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)           |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_move_constant_join_conditions_beneath_join | Join[RIGHT | true] (rows=unknown)                               |
|                                                      |   ├ Filter[(NOT (c1 >= c1))] (rows=0)                           |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                        |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)           |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)           |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_rewrite_join_plan                          | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ Filter[(NOT (c1 >= c1))] (rows=0)                           |
|                                                      |   │  └ Join[INNER | true] (rows=unknown)                        |
|                                                      |   │    ├ Collect[doc.t0 | [c1] | true] (rows=unknown)           |
|                                                      |   │    └ Collect[doc.t1 | [c0] | true] (rows=unknown)           |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_move_filter_beneath_join                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ Join[INNER | true] (rows=unknown)                           |
|                                                      |   │  ├ Filter[(NOT (c1 >= c1))] (rows=0)                        |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)          |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)             |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_move_constant_join_conditions_beneath_join | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ Join[INNER | true] (rows=unknown)                           |
|                                                      |   │  ├ Filter[(NOT (c1 >= c1))] (rows=0)                        |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)          |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)             |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_rewrite_join_plan                          | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)                 |
|                                                      |   │  ├ Filter[(NOT (c1 >= c1))] (rows=0)                        |
|                                                      |   │  │  └ Collect[doc.t0 | [c1] | true] (rows=unknown)          |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)             |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_merge_filter_and_collect                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)                 |
|                                                      |   │  ├ Collect[doc.t0 | [c1] | (NOT (c1 >= c1))] (rows=unknown) |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)             |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ Eval[1] (rows=unknown)                                    |
|                                                      |       └ TableFunction[empty_row | [] | true] (rows=unknown)     |
| optimizer_remove_redundant_eval                      | TableFunction[empty_row | [1] | true] (rows=unknown)            |
| Final logical plan                                   | NestedLoopJoin[RIGHT | true] (rows=unknown)                     |
|                                                      |   ├ NestedLoopJoin[INNER | true] (rows=unknown)                 |
|                                                      |   │  ├ Collect[doc.t0 | [c1] | (NOT (c1 >= c1))] (rows=unknown) |
|                                                      |   │  └ Collect[doc.t1 | [c0] | true] (rows=unknown)             |
|                                                      |   └ Rename["1"] AS sub0 (rows=unknown)                          |
|                                                      |     └ TableFunction[empty_row | [1] | true] (rows=unknown)      |
+------------------------------------------------------+-----------------------------------------------------------------+
EXPLAIN 9 rows in set (0.007 sec)

cr> select * from t0 WHERE NOT ((t0.c1)>=(t0.c1));
+----+
| c1 |
+----+
+----+
SELECT 0 rows in set (0.012 sec)
```

There could be an issue with CrateDB and the fact that the filtering in WHERE clause is pushed down to the Collect, where it seems it should stay on top of everything? (after the right join) but:
1.  postgres seems to not do that, but filter on the t0,t1 join, so I don't get why it gives different results
2. with CrateDB it's clear (from explain verbose) that even if we disable any rules, the filtering will remain beneath the right join so it won't filter out any rows.

**Comment by matriv** [comment]
The same issue seems to happen also for the Left Join:
```
cr> SELECT * FROM ((SELECT * FROM generate_series(1, 2, 1)) AS t1 LEFT JOIN (SELECT * from t0 CROSS JOIN t1) as t2 ON TRUE);
+-----------------+-----+-----------------+
| generate_series | c1  | generate_series |
+-----------------+-----+-----------------+
|               1 | foo |               1 |
|               1 | foo |               2 |
|               2 | foo |               1 |
|               2 | foo |               2 |
+-----------------+-----+-----------------+
SELECT 4 rows in set (0.008 sec)
```
