### ISSUE TITLE
Do not allow shadowing IGNORED objects sub-columns

### ISSUE THREAD

**Issue by jeeminso** [crate/crate#17060]
### CrateDB version

latest master

### Problem description

```
create table t (ignored object(ignored));
```
We can add sub-columns to ignored objects explicitly,
```
alter table t add column ignored['a'] int
```
or implicitly,
```
insert into t values ({b=1})
```
```
cr> show create table t;
+----------------------------------------+
| SHOW CREATE TABLE doc.t                |
+----------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."t" ( |
|    "ignored" OBJECT(IGNORED) AS (      |
|       "a" INTEGER                      |  <-- 'b' is missing from the schema
|    )                                   |
| )                                      |
| CLUSTERED INTO 4 SHARDS                |
```
We can shadow `b` with explicit column creation,
```
cr> alter table t add column ignored['b'] text;
ALTER OK, -1 rows affected (0.078 sec)
cr> select * from t;
+-------------+
| ignored     |
+-------------+
| {"b": null} | <-- 1 becames null
+-------------+
SELECT 1 row in set (0.006 sec)
```
But it seems like we can drop the column to recover the original state
```
cr> alter table t drop column ignored['b'];
ALTER OK, -1 rows affected (0.073 sec)
cr> select * from t;
+----------+
| ignored  |
+----------+
| {"b": 1} |
+----------+
SELECT 1 row in set (0.002 sec)
```

### Steps to Reproduce

Please see the problem description.

### Actual Result

`alter table t add column ignored['b'] text` shadows the implicitly added sub columns.

### Expected Result

`alter table t add column ignored['b'] text` to fail.

**Comment by jeeminso** [comment]
Reopening, will find time to double check if below is also an expected behaviour:
```
cr> create table t (o object(ignored) as (a int));
CREATE OK, 1 row affected (1.581 sec)
cr> insert into t values ({b='abc'});
INSERT OK, 1 row affected (0.044 sec)

cr> alter table t rename column o['a'] to o['b'];
ALTER OK, -1 rows affected (0.078 sec)
```

**Comment by seut** [comment]
> Reopening, will find time to double check if below is also an expected behaviour:
> 
> ```
> cr> create table t (o object(ignored) as (a int));
> CREATE OK, 1 row affected (1.581 sec)
> cr> insert into t values ({b='abc'});
> INSERT OK, 1 row affected (0.044 sec)
> 
> cr> alter table t rename column o['a'] to o['b'];
> ALTER OK, -1 rows affected (0.078 sec)
> ```

What is the issue here? Please create a dedicated issue if so because we shadow existing old values by intent due to #16930.
