### ISSUE TITLE
EXPLAIN ANALYSE with INSERT keeps running forever

### ISSUE THREAD

**Issue by lservini** [crate/crate#17159]
### CrateDB version

5.9.2

### CrateDB setup information

Plan: CR3
Nodes: 1
CPU: 8
RAM: 28 GiB
Storage: 128 GiB
CrateDB: v5.9.2

### Problem description

Issuing an INSERT query with EXPLAIN ANALYZE keeps running forever and no way to kill it (KILL and KILL ALL don't work)

### Steps to Reproduce

CREATE TABLE t (id int);

INSERT INTO t (id) VALUES (1);

EXPLAIN ANALYZE INSERT INTO t (id) VALUES (2);

### Actual Result

The query keeps running, but no data is inserted.
You can see it in sys.jobs

### Expected Result

Since EXPLAIN ANALYZE is not supported for INSERT, it should throw an error or ignore EXPLAIN ANALYZE

**Comment by jeeminso** [comment]
The [fix](https://github.com/crate/crate/pull/17167) will be available with `5.9.6` release, Thank you!
