### ISSUE TITLE
Phrase prefix misses certain records

### ISSUE THREAD

**Issue by ibrhmkoz** [crate/crate#17174]
### CrateDB version

5.9.5

### Problem description

CREATE ANALYZER like_analyzer (
  TOKENIZER whitespace,
  TOKEN_FILTERS (
    lowercase
  )
);

Given such an analyzer.

```
SELECT 
    CASE 
        WHEN '0193569a-accf-77b1-9851-9dfce8a6a131' IN (
            SELECT id
            FROM smaller_posts
            WHERE match(keyword_ft, 'foo ba') using phrase_prefix
        ) THEN 'yes'
        ELSE 'no'
    END as is_exist
FROM (SELECT 1) as dummy limit 100;
```

returns `yes`

However, if the table gets larger, it returns 'no'

```
SELECT 
    CASE 
        WHEN '0193569a-accf-77b1-9851-9dfce8a6a131' IN (
            SELECT id
            FROM larger_posts
            WHERE match(keyword_ft, 'foo ba') using phrase_prefix
        ) THEN 'yes'
        ELSE 'no'
    END as is_exist
FROM (SELECT 1) as dummy limit 100;
```

### Steps to Reproduce

Create two tables 
```
create table smaller_posts (
    id varchar primary key,
    content text,
    index keyword_ft using fulltext(content) with (analyzer = 'like_analyzer')
)
```
```
create table larger_posts (
    id varchar primary key,
    content text,
    index keyword_ft using fulltext(content) with (analyzer = 'like_analyzer')
)
```

Add data to both, having more in larger_posts to inflate its size. You'll see the very same query does not match posts in larger_posts while it matches in the smaller_posts table. The larger posts have 47 million data in our case.

### Actual Result

Some records are missed during the match.

### Expected Result

The same records matched in the smaller table should be included in the larger table as well.

**Comment by BaurzhanSakhariev** [comment]
Hi @ibrhmkoz, sorry for the late reply, people are mostly on holidays.

I see you closed the issue, have you resolved it?

**Comment by ibrhmkoz** [comment]
It's resolved after we've increased the value in `max_expansion` in the phrase_prefix.
