### ISSUE TITLE
bug in alter paritioned table

### ISSUE THREAD

**Issue by mikerlynn** [crate/crate#1726]
when you change the # of shards on a paritioned table - like described here - 

https://crate.io/docs/stable/sql/partitioned_tables.html

the health of all table partitions goes critical here: /_plugin/crate-admin/#/tables/doc/TABLENAME and all records go unavailable in the stats there as well.  But everything does seem to work.  Its like it doesnt know there were only suppose to be previously 5 shards and so it thinks some are missing.

to reproduce, creative a partioned table, add date with some parted, then change the # of shards.

**Comment by mfelsche** [comment]
Which version do you use?
We fixed an ALTER TABLE bug that quite resembles your problem in 0.46.5.
If you can, please upgrade.

**Comment by mfelsche** [comment]
As it turns out, this is a admin-ui bug.
It has nothing to do with the fix in 0.46.5.
Thanks for reporting we will take a look at it.

**Comment by chaudum** [comment]
fixing this issue requires changes both in `crate` and in the `crate-admin` project.
https://github.com/crate/crate-admin/pull/99

**Comment by chaudum** [comment]
@mikerlynn 

the fixes are now in `master` and `0.47` branch and will be available with the next hotfix release
