### ISSUE TITLE
Kubernetes discovery support

### ISSUE THREAD

**Issue by pires** [crate/crate#1728]
Given the container/cloud-oriented nature of Crate and [Kubernetes](http://kubernetes.io), it would be great to support Crate discovery on Kubernetes clusters.

Elasticsearch already supports it, but it seems #995 is a blocker.

According to your people, there is a solution planned somewhere in your backlog, so I'm creating this issue to keep up-to-date on that subject.

**Comment by chaudum** [comment]
hi @pires 

service discovery via DNS is now implemented, currently on master.
here's the corresponding PR https://github.com/crate/crate/pull/2067

best,
christian

**Comment by pires** [comment]
DNS is not Kubernetes but OK.

**Comment by chaudum** [comment]
yes, you're right, this is not kubernetes discovery (via API)
however, DNS is one possible way of node discovery on kubernetes clusters.

**Comment by pires** [comment]
DNS is still an add-on and not a first-class citizen of Kubernetes. However, if you rely on Elasticsearch discovery it's easy to implement. See https://github.com/fabric8io/elasticsearch-cloud-kubernetes, it supports DNS as well.

**Comment by offlinehacker** [comment]
By the way, kubernetes has an example with elasticsearch_discovery.go plugin that dynamically generates config for elasticsearch and adds discovered hosts https://github.com/kubernetes/kubernetes/tree/master/examples/elasticsearch

**Comment by pires** [comment]
That is being deprecated.

**Comment by chaudum** [comment]
@pires 
> As of Kubernetes 1.3, DNS is a built-in service launched automatically using the addon manager cluster add-on. A DNS Pod and Service will be scheduled on the cluster, and the kubelets will be configured to tell individual containers to use the DNS Service’s IP to resolve DNS names.
(source: http://kubernetes.io/docs/admin/dns/)

You can find a template utilizing DNS discovery for a Crate cluster here: https://crate.io/a/kubernetes-and-crate/

**Comment by pires** [comment]
Thanks. I'm closing this because I moved forward.
