### ISSUE TITLE
Elasticsearch (lack of) resilience info

### ISSUE THREAD

**Issue by pires** [crate/crate#1729]
Do you have a page where you clearly say which version of Elasticsearch have you merged into your code? It would be of extreme importance to someone following [current Elasticsearch effort](http://www.elasticsearch.org/guide/en/elasticsearch/resiliency/current/) for improving this, which in some cases mean **data-loss**.

**Comment by chaudum** [comment]
hi @pires 

we don't have a place on the website where we show the current ES version yet.
however, we announce the ES version in our changelog (https://github.com/crate/crate/blob/master/CHANGES.txt)

we'll think about how to integrate it on our website.
btw. our website is also open sourced and can be found here: https://github.com/crate/crate-web

best,
christian

**Comment by ChrisChinchilla** [comment]
Closed with https://github.com/crate/crate-web/pull/426
