### ISSUE TITLE
table name cannot be appended to column name in "ON DUPLICATE KEY UPDATE" statement

### ISSUE THREAD

**Issue by nigamashish** [crate/crate#1762]
Here are the steps - 

Create a new table - 
1) create table dumb_table (first_column integer primary key,second_column string, summarycount integer);

2) insert some data - 
insert into dumb_table (first_column,second_column, summarycount) values (2023,’myname’,1)

3) Execute select query (It works) 
select * from dumb_table where dumb_table.first_column=2023 limit 100;

4) Execute Insert with ON DUPLICATE KEY UPDATE (It fails)
insert into dumb_table (first_column,second_column, summarycount) values (2023,'myname',1) ON DUPLICATE KEY UPDATE dumb_table.summarycount=VALUES(dumb_table.summarycount) + dumb_table.summarycount
Exception - SQLActionException[Column reference "dumb_table.summarycount" has too many parts. A column must not have a schema or a table here.]

5) Execute Insert with ON DUPLICATE KEY UPDATE after removing table name prefix (It works)
insert into dumb_table (first_column,second_column, summarycount) values (2023,'myname',1) ON DUPLICATE KEY UPDATE summarycount=VALUES(summarycount) + summarycount;

I think we should support adding table name prefix with the column names.

**Comment by mfelsche** [comment]
We deliberately decided to not support the full-qualified referencing of the column used in the insert statement as it is kind of redundant as you can't legally refer to other tables than the one you insert into (and update in case of a duplicate key). We wanted to be as close to MySQL here as possible and stuck to its documentation (https://dev.mysql.com/doc/refman/5.7/en/insert.html) which says ```col_name``` is 
only supported.
Nonetheless, MySQL 5.6 supports:

```
create table t (
  id int primary key,
  name text
  );
insert into t (id, name) values (1, 'foo'), (1, 'bar') on duplicate key update t.name=values(t.name);
```

Do you really need to reference columns fully qualified (with table name) ?
Or would it be rather a convenience?

**Comment by nigamashish** [comment]
It is not a mandatory requirement for us. In fact, we already have a workaround of not appending table name in this query.

**Comment by mfussenegger** [comment]
Closing this for now for the reasons pointed out by @mfelsche
