### ISSUE TITLE
IP Type validation is broken

### ISSUE THREAD

**Issue by Bondza** [crate/crate#1781]
I am trying to store events in a table where one column contains an ip address which resulted in a lot of errors. Because according to Crate i was trying to insert invalid IP addresses.

So i tried this:
```sql
create table test (data string, ip_addr ip);
insert into test (data, ip_addr) values ('aa', '199.199.199.199');
insert into test (data, ip_addr) values ('aa', '199.199.199.200');
```

The first two commands work fine, but the last one results in an exception:

```
SQLActionException[Validation failed for ip_addr: Failed to validate ip [199.199.199.200], not a valid ipv4 address]
```

So it seems like all IP addresses containing one or more octet with a value above 199 is considered an invalid IP.

I am using this [docker image](https://registry.hub.docker.com/_/crate/) running on Ubuntu 14.04, and I tried using both version ```0.46``` and ```0.47```.

I ran it like this:
```
sudo docker run -d -p 4200:4200 -p 4300:4300 crate
```

**Comment by chaudum** [comment]
hi @Bondza 

this issue has been fixed in `0.47.7`
for full release notes see https://github.com/crate/crate/blob/0.47/CHANGES.txt
