### ISSUE TITLE
Quantiles Aggregation

### ISSUE THREAD

**Issue by ChrisChinchilla** [crate/crate#1791]
To allow for some accumulation of statistical-like data we should add support for Quantile aggregation of data.

There is a Java project available - https://github.com/tdunning/t-digest that may do most of the work and just need integration into Crate.

Otherwise it may better to undertake this task at a SQL level.

_Copied from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/crateio/Pa8t0Y6Q5n8/0NMN8VTv_1YJ_

**Comment by bogensberger** [comment]
Hi @ChrisChinchilla,

just merged percentile aggregation to master: https://github.com/crate/crate/commit/0263df5614e885f339f83819c5ae494556ac5593
