### ISSUE TITLE
Fetching column_policy values for tables

### ISSUE THREAD

**Issue by ChrisChinchilla** [crate/crate#1795]
Add the ability to fetch the current value of 'refresh_interval' and 'column_policy' from 'information_schema.tables' for a particular table.

The values can then be read by issuing something along the lines of:

`select * from information_schema.tables;`

**Comment by mfussenegger** [comment]
Closing this as this is part of the 0.51 release: https://github.com/crate/crate/blob/0.51/CHANGES.txt
