### ISSUE TITLE
IN query fails with NULL value in list

### ISSUE THREAD

**Issue by jukart** [crate/crate#1802]
According to this [GIST](https://gist.github.com/jukart/7bed9370f54235608802) the IN query fails by returning all colums if a NULL value is in the list: ``stars IN (NULL)``

I am using version 0.47.7 installed with ``bash -c "$(curl -L try.crate.io)"``

**Comment by jukart** [comment]
Oh, I should also note that this works in 0.48.0

**Comment by mfussenegger** [comment]
Thanks for reporting.
Fixed this in https://github.com/crate/crate/commit/14ad0c395c6d1a59c9cfc0b630337d2df08af7f6 

Should be out with the next 0.47 hotfix release.
