### ISSUE TITLE
Normalise table_name when querying information_schema

### ISSUE THREAD

**Issue by quodt** [crate/crate#1804]
When creating one table the table_name get normalised:

create table CamelCase (id String);

Querying the table also normalises the table_name:

select * from CamelCase;

But querying the information_schema where the table_name is given as literal does not normalise the table_name:

select count(*) from information_schema.tables where table_name='CamelCase';
0

select count(*) from information_schema.tables where table_name='camelcase';
1

used version: 0.48.0
os: scientific linux

**Comment by mfussenegger** [comment]
This is intended (but also confusing :( ) behaviour.
The SQL-92/99/2008 Standard states that identifiers should be case-insensitive unless quoted. This is actually the case in Crate. 

We've documented that [here](https://crate.readthedocs.org/en/latest/sql/reference/lexical_structure.html)

Unfortunately this seems to be a common source of confusion. As seen in https://github.com/crate/crate/issues/1648#issuecomment-73373665 , https://github.com/crate/crate/issues/1421 and https://github.com/crate/crate/issues/1370
