### ISSUE TITLE
Add support for developing with eclipse IDE

### ISSUE THREAD

**Issue by salyh** [crate/crate#1805]
Setup and configure eclipse plugin for gradle so that project can be developed also with eclipse IDE (instead of idea only).

**Comment by mfussenegger** [comment]
Sounds good. Do you want to create a PR for that?

**Comment by salyh** [comment]
Hi Mathias, i already tried this but didn't get it to work. Not well experienced with gradle so far.
If your interested i can share my non-working attempts but i don't know if this is really useful.
