### ISSUE TITLE
Build error :sql:compileJava FAILED

### ISSUE THREAD

**Issue by catroot** [crate/crate#1837]
Is i`m the one who "happy" to catch these? 

/crate/sql/src/main/java/io/crate/lucene/QueryBuilderHelper.java:91: error: incomparable types: Object and boolean
            return new TermQuery(new Term(columnName, value == true ? "T" : "F"));
                                                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:sql:compileJava FAILED

FAILURE: Build failed with an exception.

**Comment by mfelsche** [comment]
have you been doing?

```
git submodule init
git submodule update
```

to load the es upstream submodule?

**Comment by mfelsche** [comment]
which java version do you use?

**Comment by catroot** [comment]
| have you been doing?
| git submodule init
| git submodule updatejava version "1.8.0_40"
yes, i did.

Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by mfelsche** [comment]
We still develop with java 7.
Switching to java8 is on our roadmap, but we have to fix up our elasticsearch fork too.
So, stay tuned, we will fix this soon.
Or maybe you could help us fixing those compile issues in the meantime?

**Comment by catroot** [comment]
Fix compiling issue doesn`t mean correctness in production.
Compile process will continue with taking true in quotes like "true", making them a string, but what are the strings doing in a boolean fields value?
There are many further compile errors on the go.

**Comment by mfelsche** [comment]
thanks for reporting. 
we are already looking at it.

Boolean values are stored as Strings 'T' or 'F' in lucene, that's why there are strings.

**Comment by mfussenegger** [comment]
With https://github.com/crate/crate/pull/1841 it is now possible to compile and run the tests from with java8.

Correctnes hasn't really been a problem for production. There were mainly testing issues where the tests expected the result to be in a certain order (which in java8 has changed due to the underlying HashMap behaviour)
