### ISSUE TITLE
0.48.1 defaultSchema and _sql endpoint

### ISSUE THREAD

**Issue by krzaczek** [crate/crate#1893]
Hi,

I've been trying to test crate 0.48.1 new feature - setting defaultSchema. From what i've figured out from the java client ... to set the default schema one need to send na "_s" header with the schema name ...

According to this https://github.com/crate/crate/blob/c971358505822e3d1c5f6ba638a0aca525799656/sql/src/main/java/io/crate/action/sql/SQLBaseRequest.java#L118 it should work just by setting the "_s" header in the request. Am I missing something ?

Crate version
```json
#curl 127.0.0.1:4200?pretty
{
  "ok" : true,
  "status" : 200,
  "name" : "Michael Twoyoungmen",
  "version" : {
    "number" : "0.48.1",
    "build_hash" : "5fb193cbde0c019237cd0385a800f7c29567086e",
    "build_timestamp" : "2015-04-09T11:37:20Z",
    "build_snapshot" : false,
    "es_version" : "1.4.4",
    "lucene_version" : "4.10.3"
  }
}
```

Let's crate a table "my_table" in custom schema "test1"

```json
#curl -sXPOST '127.0.0.1:4200/_sql?pretty' -d '
{ 
    "stmt":"create table test1.my_table ( column1 integer )" 
}'
{
  "cols" : [ ],
  "duration" : 168,
  "rows" : [ ],
  "rowcount" : 1
}
```

Now selecting from the table with schema name specified in the sql statement

```json
#curl -sXPOST '127.0.0.1:4200/_sql?pretty' -d '
{ 
    "stmt":"select * from test1.my_table"
}'
{
  "cols" : [ "column1" ],
  "duration" : 3,
  "rows" : [ ],
  "rowcount" : 0
}
```

Selecting from my_table and setting defaultSchema in _s header

```json
#curl -sXPOST -H "_s: test1" '127.0.0.1:4200/_sql?pretty' -d '
{
    "stmt":"select * from my_table"
}'
{
  "error" : {
    "message" : "SQLActionException[Table 'my_table' unknown]",
    "code" : 4041
  }
}
```

**Comment by mfelsche** [comment]
We did not expose setting the default schema via HTTP yet.
The SQLBaseRequest from the commit you mentioned is a representation of a transport request that is only sent by the java client via tcp (per default on port 4300).

If you want to set it with crate 0.48.1 you have to use the java client.

**Comment by krzaczek** [comment]
I thought so .... thx for the info. I'm using crate.io in PHP with crate-pdo .. so will have to wait till it's gonna be available through HTTP endpoint.

**Comment by chaudum** [comment]
hi @krzaczek 
the new `crate-pdo` release [0.4.0](https://packagist.org/packages/crate/crate-pdo#0.4.0) supports now default schema in PDO connection string, e.g.

```php
$dsn = 'crate:localhost:4200/my_schema';
$connection = new PDO($dsn, null, null, null);
```

See also [documentation](http://crate-pdo.readthedocs.org).

However, the [feature on the server side](https://github.com/crate/crate/commit/d162409872b46c3a91fb052907af2867cecc666e) is only in master, which means that is going to be released with the upcoming testing version (`0.55.0`). If you use Crate <= `0.55.0` the schema from the DSN will be ignored!

**Comment by krzaczek** [comment]
@chaudum great news :D

**Comment by mfussenegger** [comment]
Closing this since the feature has been implemented (although still not released)

**Comment by nsandeepa** [comment]
Gryff
