### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by megastef** [crate/crate#1925]
Hi,

just wanted to install latest version (on Mac OS X) using the bash script and got this error:
```
bash -c "$(curl -L install.crate.io)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6309  100  6309    0     0   7723      0 --:--:-- --:--:-- --:--:--  7722
mknod: node type must be 'b' or 'c' or 'w'.
```

**Comment by chaudum** [comment]
hi @megastef 

thanks for reporting! we'll look into the issue.

**Comment by chaudum** [comment]
@megastef 
Note that the install script is not meant for installation on OSX (Darwin), but only on Linux systems (e.g. Debian, RedHat, ...), however, there's a check for OSX in the script, but it never gets there ;)

**Comment by megastef** [comment]
I had no issues with it in the past, maybe this are new things recently added to optimize it for Linux?  What do you recommend for Mac (dev env).

**Comment by chaudum** [comment]
you can use `bash -c "$(curl -L try.crate.io)"` for development environments

**Comment by chaudum** [comment]
@megastef 
the script is fixed and now correctly reports that installation on OSX is not supported.

https://github.com/crate/crate-utils/pull/10
