### ISSUE TITLE
COPY FROM reports success even when the file does not exist

### ISSUE THREAD

**Issue by reversefold** [crate/crate#1928]
I was trying to import some data through `crash` with statements like this:
```
COPY table FROM '/tmp/table.json';
```
and `crash` reported success but no records imported. The file path was correct but I did not realize at the time that the files needed to be on the server machine and wouldn't be read from the machine that `crash` was running on. If crate had reported an error (file not found) this would have been easier to diagnose.

**Comment by dobe** [comment]
hi @reversefold 

COPY FROM runs on each crate server node. in some cases the files to import only exist on a few nodes in the cluster, therefore some nodes don't import anything and ignore the fact that the file is not on their local path. throwing an error in such a case would not allow such scenarios. however, the number of affected rows reflects how many records have been imported, which should be zero in your case.

supporting to pipe data directly from the client to the server is on our roadmap. for now you need to upload the file to one or more server nodes.

**Comment by reversefold** [comment]
Hmmm, that makes some sense, I see now that data is dumped per-node and can be loaded per-node, but if the file exists on no nodes, it would still make sense to me for this to be an error.
