### ISSUE TITLE
COPY FROM does not always work with data written by COPY TO

### ISSUE THREAD

**Issue by reversefold** [crate/crate#1936]
I've dumped some data from a crate table with COPY TO and reading it right back with COPY FROM gives me the error "A primary key value must not be NULL". As far as I can tell, there are no entries in the file which have an empty primary key value.

**Comment by dobe** [comment]
could you please provide some details on your data and the statements you issued

thx, bernd

**Comment by reversefold** [comment]
I would be happy to once I have access to the skyhigh crate project so that
I'm not putting details into a public issue.

On Sun, Apr 26, 2015 at 11:25 PM, Bernd Dorn <notifications@github.com>
wrote:

> could you please provide some details on your data and the statements you
> issued
>
> thx, bernd
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crate/crate/issues/1936#issuecomment-96519028>.
>



-- 
Justin Patrin
Developer Extraordinaire
