### ISSUE TITLE
Feature request/enhancement show/describe tables

### ISSUE THREAD

**Issue by duncanfbell** [crate/crate#2000]
Instead of having to query the information_schema

https://crate.io/docs/stable/sql/information_schema.html

... it would be nice if features commonly available and used in mysql like "show tables", "describe table" and "show tables like ..." were available in crate.

**Comment by spanktar** [comment]
+1 I habitually use this query and then remember that I have to go to the information schema.

**Comment by chaudum** [comment]
@duncanfbell 
```sql
SHOW CREATE TABLE table_name
```
is implemented since version `0.51.x`

We've put `SHOW TABLES` into the backlog, too.

**Comment by mfussenegger** [comment]
SHOW TABLES has been added in 0.54: https://github.com/crate/crate/blob/0.54/CHANGES.txt#L170
