### ISSUE TITLE
 Elasticsearch HTTP REST API not enabled; again

### ISSUE THREAD

**Issue by rayNymous** [crate/crate#2037]
hi. i getting 
```
 [2015-05-17 17:13:20,482][INFO ][io.crate.rest.CrateRestFilter] Elasticsearch HTTP REST API not enabled
```
message in logs,but i have also
```
es.api.enabled: true
```
in crate.yml

i heard that if i enable REST.api api i'll be able to run kibana 4 with crate. but, i can't enable it
https://groups.google.com/forum/#!msg/crateio/FbX-XkCcdzY/6BvI_oM4WH0J/FbX-XkCcdzY/6BvI_oM4WH0J

can somebody help me?

and it may be important. i got crate from aur on archlinux. not from git. version 0.48.5-1

**Comment by mfussenegger** [comment]
Just tried it aut with the latest package from AUR and for me it works fine.

Just to make sure. You edited `/etc/crate/crate.yml` and restarted crate afterwards?

**Comment by rayNymous** [comment]
yes. and i did it couple times already. i'll try one more time

**Comment by rayNymous** [comment]
it works. i just remove crate and config directory, and merge it again. sorry and  thanks for reply.
