### ISSUE TITLE
Missing crash in yum distribution

### ISSUE THREAD

**Issue by bububa** [crate/crate#2062]
Missing crash in yum distribution

**Comment by dobe** [comment]
hi @bububa 

the reason why we don't distribute crash with the server installation is that we don't want a dependency to python for every node in the cluster. the solution would be to have a seperate package for crash, we have this on our list of todos.

as a workaround you could use the standalone version of crash as explained at https://pypi.python.org/pypi/crash , you can download it from  https://cdn.crate.io/downloads/releases/crash_standalone_latest make it executable and run it.
