### ISSUE TITLE
Issues with csv2json script...

### ISSUE THREAD

**Issue by RVN-BR** [crate/crate#2078]
I'm having some issues with csv2json script... Does anyone have any experience?  (I'd honestly be looking for something a bit less hacky...)...

We cant apply FILE permissions on our SQLs so doing a select into file wont work... I was able to extract a csv which I assume is correct as I have used in many other apps for importing... I have also double-checked it is UTF8, but keep getting a weird error with csv2json that doesnt really say anything...

```
bash-3.2$ ./csv2json.py --columns CustomerID:int ClientID:int EMail:string Name:string FieldA:string FieldB:string FieldC:string FieldD:string FieldE:string FieldF:string FieldG:string FieldH:string FieldI:string FieldJ:string FieldL:string FieldM:string FieldN:string FieldO:string FieldP:string FieldQ:string FieldR:string FieldS:string FieldT:string FieldU:string date:timestamp dateupdate:timestamp vol/tmp/query_result.csv vol/tmp/query1.json
Traceback (most recent call last):
  File "./csv2json.py", line 83, in <module>
    convert(args.infile, args.outfile, args.columns)
  File "./csv2json.py", line 55, in convert
    function_seq = [(c[0], converter.get_impl(c[1])) for c in cols]
IndexError: list index out of range
```

```
bash-3.2$ cat vol/tmp/query_result.csv | python csv2json.py --columns CustomerID:int ClientID:int EMail:string Name:string FieldA:string FieldB:string FieldC:string FieldD:string FieldE:string FieldF:string FieldG:string FieldH:string FieldI:string FieldJ:string FieldL:string FieldM:string FieldN:string FieldO:string FieldP:string FieldQ:string FieldR:string FieldS:string FieldT:string FieldU:string date:timestamp dateupdate:timestamp
Traceback (most recent call last):
  File "csv2json.py", line 83, in <module>
    convert(args.infile, args.outfile, args.columns)
  File "csv2json.py", line 64, in convert
    row[k] = impl(row[k])
ValueError: invalid literal for int() with base 10: '\xef\xbb\xbf"CustomerID"'
```

example of CSV... tried with 1 line, 2 lines, 5 lines, 1000 lines... all fail the same... tried with and without column headers...

```
114,15,"rob@email.com","Roobert","","","","","","","","","","","","","","","","","","","","",0,1159457795000
200467,1345,"rob2@email.com","Roobert second","","","","","","","","","","","","","","","","","","","","",0,0
```

Any ideas?  I'd like to validate some crate functionality and performance before I decide if Crate can be used for us or if we should just stick with plain ES for now...

**Comment by RVN-BR** [comment]
Nevermind.... It was a stupid thing....

What happened is that CSV2JSON doesnt support "NULL" as values.  So these must be replaced.  

In my case, it began with a NULL problem, and as I tried to debug it I changed encoding to see if that would affect things and never changed it back...  Please ignore the stupidty... :o

**Comment by RVN-BR** [comment]
I believe there is an issue with the converter...  I had to convert my NULL values to 0, as it was a timestamp field.  If it was a string field, however, a 0 would be incorrect.  MySQL exports as NULL, so csv2json should correct considering for the fieldtype imo?

Another idea would be to ignore fieldnames on line 1 if these occur....

**Comment by RVN-BR** [comment]
I have mostly normalized the data (had to leave lots of data behing in mysql... but csv2json just isnt playing nice with converting types...)  Also had issue with accented characters, despite having UTF8 set, and having the file in utf8... csv2json hiccups.... It also doesnt recognized escaped quotes... anyways, I'll have to try something else... if anyone has suggestions.

For now I was able to import a fairly "standard" numerical dataset... I also had to drop the primary key on the table as crate always says SQLActionException[A primary key value must not be NULL] even though there is no null value in the json impoty... (I tried with a single record)...

**Comment by chaudum** [comment]
hi @RVN-BR 
I have to admit that our csv2json script is quite rudimentary, and only solves a basic conversion from mysql csv dumps to crate json.
- `NULL` values are possible, they need to be exported as `\N` in csv (https://github.com/crate/crate-utils/blob/master/migrations/mysql/csv2json.py#L61)
- you're right that the PK constraint in Crate is also a not-null constraint (https://crate.io/docs/en/latest/sql/ddl.html#constraints)
- we'll need to take a look at character encoding (do you have an example that fails?)
- the `csv2json` script supports different quote characters, but this is not exposed as an argument yet (https://github.com/crate/crate-utils/blob/master/migrations/mysql/csv2json.py#L47) will add that functionality.

**Comment by RVN-BR** [comment]
Thanks @chaudum I guess i'm going to close this issue for now... I will try and get that line that was causing the issue again... Accents seem to be going in fine, and I couldnt immediately see any weird char in the line that failed (it was 1 record amidst 400k), so it was a bit weird... again, with mysql2xxxx I got it working with that same record out of the box...

Can you point me, if you dont mind, in the correct direction in terms of naming conventions?  I see that crate often favors lowercases if the fieldnames arent "quoted"... should I just quote them when creating the table and thats all, or should I take care to always export column names as lowercase and create in lower?

**Comment by chaudum** [comment]
@RVN-BR 

if you want to avoid any problems, the best thing would be to do **only** lower case column names.
otherwise, always double quote column names if you need to retain camel case.
if you don't quote camel case names Crate will convert it to lower case internally. This example might help.

```sql
create table my_table (id integer, "myCamelCaseCol" string, yourCamelCaseColumn string);
CREATE OK (0.826 sec)

insert into my_table (id, "myCamelCaseCol", yourCamelCaseColumn) values (1, 'foo', 'bar');
INSERT OK, 1 row affected (0.028 sec)

select * from my_table;
+----+----------------+---------------------+
| id | myCamelCaseCol | yourcamelcasecolumn |
+----+----------------+---------------------+
|  1 | foo            | bar                 |
+----+----------------+---------------------+
SELECT 1 row in set (0.011 sec)

select id, mycamelcasecol, yourcamelcasecolumn from my_table;
SQLActionException[Column mycamelcasecol unknown]

select id, "myCamelCaseCol", yourcamelcasecolumn from my_table;
+----+----------------+---------------------+
| id | myCamelCaseCol | yourcamelcasecolumn |
+----+----------------+---------------------+
|  1 | foo            | bar                 |
+----+----------------+---------------------+
SELECT 1 row in set (0.009 sec)
```

**Comment by RVN-BR** [comment]
@chaudum Right, but it wont convert to lowercase when importing from json... so thats a little "snafu" to be contended with...  Its minor (a questions of Select MyField as myfield) but I have a couple of pretty large (wide) tables but its a once-done process...

I'll move my more general questions into the crate group... as I already have an extensive post there :)

**Comment by chaudum** [comment]
@RVN-BR you're right, that can be a bit confusing. it's only mentioned in a note in the documentation: https://crate.io/docs/stable/sql/dml.html#import-export
> Furthermore, column names in your data are considered case sensitive (as if they were quoted in a SQL statement).

**Comment by seanr** [comment]
I'm running into the same issue and the data set I have is huge - 6GBs.  I can't possibly pick through it.  This script needs to be much more forgiving.  At the very least if could point out the line causing the issue.  Alternatively, I need a better tool.  This is some BS that has cost me an entire evening with absolutely no useful result. :-(((((

**Comment by seanr** [comment]
BTW, has nothing to do with field names.  That's a red herring.
