### ISSUE TITLE
Problem with IP lookups

### ISSUE THREAD

**Issue by l7s** [crate/crate#2112]
Hi, unless I am missing something obvious there seems to be an issue (tested in v. 0.48.6) with IP lookups. To reproduce the bug:

1. Create table:

<code>CREATE TABLE ip_test (ip_addr ip);</code>

2. Add document:

<code>INSERT INTO ip_test VALUES ('192.168.1.10');</code>

3. Perform a lookup:

<code>SELECT * FROM ip_test WHERE ip_addr = '192.168.1.10';</code>

The above returns no results.

Regards,
Chris

**Comment by chaudum** [comment]
hi @l7s 
thanks for reporting the issue!
there's a pull request https://github.com/crate/crate/pull/2114

I'll let you know when the fix is released!

**Comment by l7s** [comment]
Hi, would you be able to provide ETA when new released will become available?

**Comment by chaudum** [comment]
hi @l7s 
sorry, I completely forgot to tell you that it has been released already.
it's available in `0.49.3` https://github.com/crate/crate/blob/0.49.3/CHANGES.txt#L38
