### ISSUE TITLE
Can JOINS be performed on ElasticSearch using Crate ?

### ISSUE THREAD

**Issue by sumanth232** [crate/crate#2118]
Our company wants to perform JOIN operation on the data in ElasticSearch, which isn't allowed in ElasticSearch. Can we achieve this using Crate ?

**Comment by pdonorio** [comment]
+1

**Comment by sumanth232** [comment]
Crate does not support JOINs. 
Its mentioned in the FAQ -  https://crate.io/docs/faq/

```
Q: Does Crate support JOINs?

Not yet. JOINs are on our roadmap and we try to do them the right way in usual quality and well performing.
For a lot of use cases there are other ways to achieve the same result as with JOINs. The best way to start is to take a look at the ARRAY and OBJECT data types to denormalise your data.
```

**Comment by chaudum** [comment]
hi @sumanth232 

Our latest testing release `0.53.0` has a first, basic support for `INNER JOIN`s (see: https://crate.io/docs/en/latest/sql/joins.html) We're working on improving performance and adding more complete support for `JOIN`s.
We're going to update the website accordingly!

Best,
Christian
