### ISSUE TITLE
setting default schema name with JDBC Url doesn't work with create tabe

### ISSUE THREAD

**Issue by proofy** [crate/crate#2119]
If I'm setting JDBC Url to something like 
 jdbc:crate://localhost:4300/myschema
and there isn't this schema jet, I can't create a table with SQL:
 create table mytable
into the schema myschema. That would be the normal way to do this with other databases.
I have this problem with a generic ETL Tool.

**Comment by mfussenegger** [comment]
Which Crate version are you using?
Do you receive any error or message or what exactly does `can't create a table` mean?

**Comment by proofy** [comment]
it was the newest version of crate.
I have tried to write a test to show the problem
https://github.com/proofy/crate-jdbc/blob/master/src/test/java/io/crate/client/jdbc/integrationtests/CrateNewTableTest.java

**Comment by chaudum** [comment]
hi @proofy 

I've used your test to check if the table is created, but I could not reproduce that the table was NOT created.
However, I had to change your test setup a bit, since the table information is not immediately available in the information schema.
However, you can still insert data into the table immediately.

I am curious what the ETL tool exactly does. Is it required to query the information schema after table creation?

```java
    @Test
    public void testConnectionWithCustomSchemaAndPrepareStatement() throws Exception {
        String schemaName = "my_schema";
        String tableName = "my_table";
        Connection conn = DriverManager.getConnection(String.format("jdbc:crate://%s/%s", hostAndPort, schemaName));

        PreparedStatement pstmt = conn.prepareStatement(
                String.format("create table %s (first_column integer, second_column string)", tableName));
        assertThat(pstmt.execute(), is(false));

        // we can insert data, so the table exists
        pstmt = conn.prepareStatement(
                String.format("insert into %s (first_column, second_column) values (42, 'testing')", tableName));
        assertThat(pstmt.execute(), is(false));
        pstmt = conn.prepareStatement(String.format("refresh table %s", tableName));
        pstmt.execute();
        pstmt = conn.prepareStatement(
                String.format("select * from %s", tableName));
        assertThat(pstmt.execute(), is(true)); // there should be a return value
        ResultSet rSet2 = pstmt.getResultSet();
        assertThat(rSet2.next(), is(true)); // there should be a result
        assertThat(rSet2.getInt(1), is(42));
        assertThat(rSet2.getString(2), is("testing"));

        // check information schema
        pstmt = conn.prepareStatement(
                String.format("select schema_name, table_name from information_schema.tables where table_name='%s'", tableName));
        assertThat(pstmt.execute(), is(true)); // there should be a return value
        ResultSet rSet = pstmt.getResultSet();
        assertThat(rSet.next(), is(true)); // there should be a result
        assertThat(rSet.getString(1), is(schemaName));
        assertThat(rSet.getString(2), is(tableName));
    }
```

**Comment by chaudum** [comment]
see: https://github.com/crate/crate-jdbc/commit/85a39cb2e59b55c097595315254532d0636e6947

**Comment by proofy** [comment]
ok, thanks, it seems that you have to make a __refresh table__ before querying data after insert.
That's a little bit tricky at the beginning using CRATE ;), because the error message says something that there is no table.
It's a layer 8 problem - close this.

**Comment by chaudum** [comment]
FYI https://crate.io/docs/stable/sql/refresh.html
