### ISSUE TITLE
crash: csv (or any other) output style possible ?

### ISSUE THREAD

**Issue by michabbb** [crate/crate#2165]
thanks

**Comment by mfelsche** [comment]
Please take a look here: https://crate.io/docs/projects/crash/en/0.13.0/formats.html it is shipped with crate since 0.49.0

**Comment by michabbb** [comment]
@mfelsche but this brings me to the question: where do i get notified about such (great) updates ?
is there anywhere a details changelog ? i am really missing this, since i had some very terrible bugs in the past, its important for me to get notified about important changes... or improvements like "format" at crash....
