### ISSUE TITLE
Strange Error Message

### ISSUE THREAD

**Issue by mamod** [crate/crate#2305]
This was a bit confusing at first, when tried to delete a blob with invalid sha1 hex digest
I got the following error

```js
{"error" : "InvalidIndexNameException[[_blobs] Invalid index name [_blobs], must not start with '_']", "status" : 400 }
```

example request URI
``http://127.0.0.1:4200/_blobs/myblobs/invaliddigest``

Beside being strange, it also has different error format than /_sql requests ``{"error": {"message":"...","code":4093}  }``

**Comment by chaudum** [comment]
hi @mamod 
thanks for reporting. we'll take a look at the issue asap.
best,
christian

ps: if you'd like to contribute, we'd be happy to support you :)

**Comment by mamod** [comment]
Thank you,
I really would like to contribute to such a great project, unfortunately I have zero java experience :(

On the other hand I contributed by creating a perl client library https://github.com/mamod/DBD-Crate :)

Thanks again, and please keep up the great work.

**Comment by chaudum** [comment]
@mamod wow, great project! may we gonna list that on our client library page on the website (https://crate.io/docs/clients/)?

**Comment by mamod** [comment]
@chaudum please do, I'll be grateful :)

**Comment by ChrisChinchilla** [comment]
Hi @mamod added to our staging site here - https://staging.crate.io/docs/clients/

Let me know if you have any issues with the listing.

**Comment by mamod** [comment]
looks great, happy to see the **camel** in the list :) thanks

**Comment by ChrisChinchilla** [comment]
Great @mamod it should be live, but something still seems to be caching the old version of the page on our live site :(

**Comment by mfussenegger** [comment]
Closing this. The error messages have been improved with https://github.com/crate/crate/pull/2321
