### ISSUE TITLE
c++?

### ISSUE THREAD

**Issue by mojovski** [crate/crate#2346]
Dear Crate IO team, can I use c++ as a client to store and to query my binary data? :)

**Comment by chaudum** [comment]
hi @mojovski 
we don't have a C++ client yet, but we're happy to take contributions :-)
available clients are listed here: https://crate.io/docs/clients/

best, christian

**Comment by mojovski** [comment]
Ok. Where do I start? Are there any docs on how I can start?

**Comment by chaudum** [comment]
hi @mojovski 
unfortunately, we don't have a spec for writing client libraries. however, it is not really difficult :)

crate provides a REST endpoint which you can use to send JSON POST requests to; see: https://crate.io/docs/stable/sql/rest.html
as a reference, you can take a look a the python client (https://github.com/crate/crate-python https://crate.io/docs/projects/crate-python/stable/client.html)

hope this helps for a start

best, christian

**Comment by mamod** [comment]
I'm working on a c client which uses [duktape javascript](https://github.com/svaarala/duktape) c engine to simplify things, I'm going to make it c++ compatible, project should be on github in a couple of days, so if you have no problem dealing with a little bit of JavaScript (mostly for setting options and custom fetching methods), plus some overhead because of embedding duktape, then I'll be happy to ping you once the project is online.

**Comment by mojovski** [comment]
thanks for all the comments and propositions (@mamod).
Actually, the query speed performance plays an important role for me. Thus, using a http request would be probably too slow. Do you have any numbers when the request is sent from the same machine?

**Comment by chaudum** [comment]
hi @mojovski 
We don't have any numbers about the overhead of the HTTP request. What type of application do you have that requires such speed? We've never had performance problems using HTTP, though.
The only way to speed up the connection and bypass HTTP is to use the Java client, which talks the internal server transport protocol.
Best,
Christian

**Comment by joemoe** [comment]
hi @mamod, how's your progress on the duktape implementation? we're really interested on how your doing there. best, johannes

**Comment by mamod** [comment]
@joemoe I did some work at [crate-c](https://github.com/mamod/crate-c), the code need to be cleaned up and some more functionality to be added but this should not be a hard task, if you are interested then I'll be more than happy to work on it this weekend :)

**Comment by chaudum** [comment]
@mamod we don't want to stress you :) however, let us know when you feel comfortable with your implementation. then we're going to put that onto our [clients page](https://crate.io/docs/clients/) (if you allow us to do so).
