### ISSUE TITLE
Array or object query fails on namespaced table

### ISSUE THREAD

**Issue by SpareShade** [crate/crate#2369]
Hello,
Thank you for the great product!

I'm using 0.50.1 and it seems that it is not possible to query 'array' or 'object' data types on namespaced tables.

Recreating the schema without the namespace the same queries work perfectly.

**Comment by mfussenegger** [comment]
Just tried to reproduce this but seems to work.


    cr> create table f.foo (tags array(string), obj object);

    cr> insert into f.foo (tags, obj) values (['foo', 'bar'], {"test" = 'val'});
    INSERT OK, 1 row affected (0.135 sec)
    cr> select * from f.foo;
    +-----------------+----------------+
    | obj             | tags           |
    +-----------------+----------------+
    | {"test": "val"} | ["foo", "bar"] |
    +-----------------+----------------+

    cr> select obj, tags from f.foo;
    +-----------------+----------------+
    | obj             | tags           |
    +-----------------+----------------+
    | {"test": "val"} | ["foo", "bar"] |
    +-----------------+----------------+


Am I missing something here?

**Comment by mfussenegger** [comment]
I think I figured it out - is your issue that e.g. dynamic column updates aren't reflected?

    select obj['test'] from f.foo;
    SQLActionException[Column obj['test'] unknown]

**Comment by mfussenegger** [comment]
If this was indeed your problem it is being fixed with the next release (see https://github.com/crate/crate/pull/2370)

If it is something else please feel free to re-open and provide some more information on how we can reproduce it.

**Comment by SpareShade** [comment]
Hi,
thanks for looking into this, and huh! you are right, this is a false alarm.

my use case is something like:
```
select * from client.profile where 'my@email.com'=any(social_profiles['email'])

(ie. social_profiles array(object as  ...))
```
I'm not sure what I was doing wrong, but now, it just works !! :) 

by the way the following works for me:
```select obj['test'] from f.foo;```
