### ISSUE TITLE
crate source code compile question

### ISSUE THREAD

**Issue by tzou** [crate/crate#2373]
Dear Crate IO team,
    I downloaded crate source code and compile in Linux env. Steps below:
    cd crate-master;
    ./gradlew -v
    ./gradlew clean
    ./gradlew build
    
    last step recommanded errors below:
  crate-master/core/src/main/java/io/crate/ClusterId.java:24: error: package org.elasticsearch.common.io.stream does not exist
import org.elasticsearch.common.io.stream.StreamInput;
   
Obviously it reports that the dependency of es does not exist.

My question is : do crate support gradle compile by crate source code? how?

many thanks!

**Comment by dobe** [comment]
hi @tzou 

i assume with "downloaded" you mean you did a git clone of this repository. if this is the case you need to   also checkout the submodules like this:
```
git submodule update --init
```

Also detailed build instructions can be found under https://github.com/crate/crate/blob/master/DEVELOP.rst

best, bernd

**Comment by tzou** [comment]
@dobe 
I just downloaded crate by zip pkg and compile in linux, No .git directory exists when I unzip crate pkg.

I seems that using cmd "git clone https://github.com/crate/crate.git " can download .git directory dependency, but download crate by pkging zip don't have.

**Comment by dobe** [comment]
it is not possible to compile from the branch zip archive from github. for an installation from the tarball see https://crate.io/docs/stable/installation.html

if you really want to build crate on your own you need to follow the instructions described in https://github.com/crate/crate/blob/master/DEVELOP.rst

**Comment by tzou** [comment]
@dobe 
ok...I know what you mean.
thanks.
