### ISSUE TITLE
master branch build failure

### ISSUE THREAD

**Issue by Vadi** [crate/crate#2417]
Not sure why, build is miserably failing. Anyone working on this?

**Comment by mfussenegger** [comment]
Did you follow the [DEVELOP.rst](https://github.com/crate/crate/blob/master/DEVELOP.rst) ?

The build on master is/should be fine (except one flaky test, which should be fixed with https://github.com/crate/crate/pull/2416)

**Comment by Vadi** [comment]
That answers my problem. Thanks.
