### ISSUE TITLE
Crate crashes on OpenVZ

### ISSUE THREAD

**Issue by l7s** [crate/crate#2461]
Hi, we have just upgraded from 0.4.86 to 0.50.3 and after couple of minutes after start nodes are crashing with error in console as in http://pastebin.com/xvx7SGkw and error report in http://pastebin.com/c5bdgAtX

Any suggestions how to troubleshoot this further appreciated.

Regards,
Chris

**Comment by dobe** [comment]
we will try to reproduce this, did you also upgrade java with this upgrade?

**Comment by l7s** [comment]
No, didn't upgrade Java or made any changes to the system. All we did is replaced crate

**Comment by mfussenegger** [comment]
Is it possible for you to try with a different java version? E.g. 1.7.0_85 or 1.8.0_51 are used on our staging/dev environments.

As I understood it this error occurs on ALL of your nodes?

**Comment by l7s** [comment]
Yes, I can run with different java. Sorry for a dumb question but can you provide a link to download 1.8.0_51 as official page:

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

has 8u60 only and no "archive" or "older releases"

**Comment by mfussenegger** [comment]
1.8.0_51 is from the centOs repos. I guess 8u60 should be fine too for a test to see if the problem is specific to your current java version

**Comment by l7s** [comment]
Changed JRE to 8u60 and so far one node crashed with error report http://pastebin.com/TCDdB7ga

**Comment by l7s** [comment]
another node just crashed http://pastebin.com/Z9yw4hrW with error report http://pastebin.com/FYu6G4pG

**Comment by mfussenegger** [comment]
Seems like this is related to https://github.com/elastic/elasticsearch/issues/9582 and https://github.com/elastic/elasticsearch/issues/11062 where sigar causes issues in an OpenVZ environment.

Current workaround is to remove the lib/sigar folder. There will be a couple of (harmless) NPE's if the sys.nodes table is queried, but we'll have a bugfix for that soonish.

**Comment by chaudum** [comment]
Hi @l7s 

With the dependency upgrade to Elasticsearch 2.x the sigar library will be removed, too. We currently don't know when this will happen, though. Until then it is necessary to do the workaround @mfussenegger suggested.

Best,
Christian
