### ISSUE TITLE
subselects: Get total count from group by case 

### ISSUE THREAD

**Issue by Sirenia** [crate/crate#2479]
example :

``` sql
select count(*) as tweets ,user_id from tweet group by user_id having count(*) = 1;
```

How can I get total count from this case .

In mysql I can use sub query 

``` sql
select count(*) from (select count(*) as tweets ,user_id from tweet group by user_id having count(*) = 1);
```
##

**Comment by mfussenegger** [comment]
This is currently not possible as Crate doesn't support subselects yet.

You'll have to do the count on client side as a workaround.

**Comment by Sirenia** [comment]
@mfussenegger Thanks replay
Yes I do this on client side this moment .But I don't know how to limit (I current use a big number).

**Comment by mfussenegger** [comment]
1.0. contains subquery improvements - among them support for global aggregations. So your example query works now.

```
select count(*) from (select count(*) as tweets ,user_id from tweet group by user_id having count(*) = 1) as t;
```
