### ISSUE TITLE
databases support for access control / isolation / multi-tenant

### ISSUE THREAD

**Issue by n3ziniuka5** [crate/crate#2503]
Right now a single crate instance is a single database and you can only create tables in it. It would be nice to be able to have multiple databases under a single instance.

`./bin/crash` - selects the default database
`create database my_db`

`./bin/crash my_db` - selects `my_db` database
`create table my_table`
##

**Comment by n3ziniuka5** [comment]
I just found that it support schemas: https://crate.io/docs/stable/sql/reference/create_table.html
Should that be used instead?

**Comment by mfelsche** [comment]
yes, for namespacing purposes there are already ![custom schemas](https://crate.io/docs/stable/sql/ddl.html#schemas).
but there is no access control.

**Comment by n3ziniuka5** [comment]
would be nice to have both - databases and schemas, like in PostgreSQL

**Comment by mfelsche** [comment]
what would be your main use case for that feature?
what do you want to achieve with databases? where is the extra value for you?

**Comment by n3ziniuka5** [comment]
Isolation and access control. Currently there is no access control, but even without that, isolation can be beneficial. 

For example, if I run many applications with their own databases on the same instance, non of them should be able to access or modify the data in any other database.

**Comment by jeteon** [comment]
Perhaps run separate instances for now and get the isolation from using different port numbers? Its something I'm running into too but with testing so I kinda wanted the exact same database.

I think for now the basic answer is that you need a layer between your application and crate that manages things like access and isolation and uses Crate more as a pure data store than anything. These things aren't too difficult to achieve with some firewall rules and a proxy server that can enforce the rules for you.

**Comment by mfussenegger** [comment]
There is now [User support](https://crate.io/docs/crate/reference/en/latest/sql/administration/user_management.html) and [Access control via Privileges](https://crate.io/docs/crate/reference/en/latest/sql/administration/privileges.html) in Crate (2.1) 

Although we don't have a "database" entity, the privilege control works on a schema level.

**Comment by mfussenegger** [comment]
Closing this for now. As mentioned in the previous comment we do have user support and access control via privileges on a schema level. At the moment we don't plan to add an additional "database" entity.
