### ISSUE TITLE
COPY TO exporting partial data

### ISSUE THREAD

**Issue by khalidsalomao** [crate/crate#2565]
`COPY TO` **without** the optional parameter `DIRECTORY` exports data from only one shard. I took some time to figure that out....

In my case, the table have 12 shards and the output was to S3, and the generated file had only 1/12 of the total rows.

If the parameter `DIRECTORY` is provided, all data is exported to S3, generating 12 files.

Tested with version 0.51.2
OS: Ubuntu 14.04

**Comment by mfelsche** [comment]
HI @khalidsalomao,
this is actually expected behaviour and documented in the ![COPY TO REFERENCE](https://crate.io/docs/stable/sql/reference/copy_to.html) and the ![EXPORTING DATA DOCUMENTATION](https://crate.io/docs/stable/sql/dml.html#exporting-data).

Data is exported from all shards in parallel, overriding each other.

**Comment by khalidsalomao** [comment]
Thanks @mfelsche, it was my mistake (for some reason I thought that was one file per node instead of per shard...).

But, since almost always the index will have multiple shards, this overwrite behavior will cause many mistakes like mine, shouldn't the `DIRECTORY` option be the default behavior?

Also, in regards to the parallelism, an interesting feature would be to turn off the parallelism and have only 1 resulting file.

AWS Redshift has this option for the `UNLOAD` command: [unload](http://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html)

What do you think about these features:

1. Make `DIRECTORY` option the default.

2. `COPY TO` with parallelism off to generate only one file (serializing the output of each shard).

3. New parameter: accept a `SELECT` query as parameter so that the query output is written to file (similar with the Redshift `UNLOAD`).

**Comment by mfelsche** [comment]
Thanks for the suggestions.
COPY TO is indeed somewhat irritating in this regard.

We will add your point 2. to our backlog, the third one was actually already there, so it gets higher priority.
We will discuss internally the first option. We will definitely fix this, but we are not sure how, yet.

We will keep you posted on this.

**Comment by khalidsalomao** [comment]
Hi @mfelsche, thanks for the feedback!

**Comment by joemoe** [comment]
hi @khalidsalomao, in 0.54 we added the possibility to add a `WHERE` clause to the `COPY TO` statement. this should solve your #3. https://crate.io/docs/reference/en/latest/sql/reference/copy_to.html#where-clause

**Comment by chaudum** [comment]
hi @khalidsalomao 
If you think @joemoe 's answer solved the initial problem, feel free to close this issue.
Concerning your suggestions (1. and 2.): we don't have them on our roadmap at the moment, but we're happy to take contributions ;-)

**Comment by khalidsalomao** [comment]
:+1:
