### ISSUE TITLE
support append to array on update (set array_field += new_element)

### ISSUE THREAD

**Issue by gmrodrigues** [crate/crate#2566]
It would be great if was possible to append to array (set array_field += new_element) on update instead  of doing the append operation client side and then update the whole array

**Comment by chaudum** [comment]
Hi @gmrodrigues 

Thanks for your suggestion. We'll put [array functions / operators](http://www.postgresql.org/docs/9.1/static/functions-array.html) into our backlog.
Unfortunately, we cannot estimate when this is going to be implemented. However, you're very welcome to contribute :)

Best,
Christian

**Comment by dobe** [comment]
closing this, since it is implemented with https://github.com/crate/crate/pull/2619
