### ISSUE TITLE
No graceful-stop possible - an upstart problem with Ubuntu 14.04?

### ISSUE THREAD

**Issue by BernhardGruen** [crate/crate#2577]
Hello,

while trying to upgrade my test-cluster from 0.50.5 to 0.50.6 I experienced a problem. The corresponding documentation is the "Best Practice" documentation for "Zero Downtime Upgrades". 
It seems that you can't use the documented "graceful-stop" command with Ubuntu 14.04 and its upstart init system.

Every time I try the "graceful-stop" I get the following error:
![image](https://cloud.githubusercontent.com/assets/9251824/9882982/e1176910-5bd7-11e5-98a2-38e78a05e4f3.png)

That document also states that one can use a 'kill -USR2' on the PID of the running crate instance. But it seems that crate will restart the instance immediately after because of the "respawn" policy defined in the upstart script.

Is there any way to solve this - maybe by patching the file /etc/init/crate.conf (the actual upstart script for crate)?

Best regards,

Bernhard J. M. Grün

**Comment by Samuman** [comment]
I came across exactly the same problem earlier today with Ubuntu 14.04. I first tried graceful-stop, but I also got the same warning. -USR2 seems to do the trick but it also restarts the server immidiately, which seems to make graceful stop useless.

**Comment by celaus** [comment]
Hi, thanks for noticing, unfortunately Ubuntu seems to prefer to use upstart over sysinit, hence the script in /etc/init.d/ points to upstart, which does not support our graceful-stop command. 
```
$ ls -l /etc/init.d/crate
lrwxrwxrwx 1 root root 21 Sep 15 05:33 /etc/init.d/crate -> /lib/init/upstart-job
```

We will be looking into this, for now you can use [debian's sysinit](https://gist.github.com/celaus/f9975d5984a0b89b407b) script and remove crate from upstart. 


Cheers, Claus
