### ISSUE TITLE
How to integrate plugins Elasticsearch

### ISSUE THREAD

**Issue by yeyongyong** [crate/crate#2579]
plugins url： https://github.com/medcl/elasticsearch-analysis-mmseg

**Comment by chaudum** [comment]
hi @yeyongyong 

Even though Crate is using ES under the hood, Crate has its own plugin mechanism (see [Plugins](https://crate.io/docs/en/latest/plugins.html) documentation and [example plugin](https://github.com/crate/crate-example-plugin)).

If the ES plugin is developed against the ES source (and not against the ES jar - which has shaded namespaces) then it should be very easy to convert an Elasticsearch plugin into a Crate plugin.

Hope this helps!
