### ISSUE TITLE
Return count of total possible hits to a query, in addition to the limited items to be fetched

### ISSUE THREAD

**Issue by ghenom** [crate/crate#2582]
There are certain scenarios in which this is useful, instead of querying twice. Especially for time critical user experience.

In elastic search this is done by default. They return the first 10 hits, while giving a count of the total possible hits.
In crate sql we have to use: select * from XYZ, and then select count(*), which could waste time.

**Comment by chaudum** [comment]
Hi @ghenom 

We try to be as SQL compliant as possible with Crate. Returning the total possible hits for a query is very specific to Elasticsearch and its usage as a search engine. There is also the problem, that showing the total possible results is also not possible/very inefficient for other kinds of queries, such as `JOIN`s or `GROUP BY`.

Issuing a second `count(*)` for simple queries for that purpose does not seem to be much of an overhead to me.

Best,
Christian
