### ISSUE TITLE
Feature request: crash json format that is fully compatible with  COPY FROM

### ISSUE THREAD

**Issue by BernhardGruen** [crate/crate#2590]
At the moment the output of `crash --format json` is not fully compatible with the format that `COPY FROM` expects.
`crash` outputs JSON formatted into multiple lines but `COPY FROM` expects exactly one line per record (as per documentation).

This feature would greatly ease doing partial exports (like for creating incremental backups of timeseries data).

**Comment by chaudum** [comment]
hi @BernhardGruen 
this is a great idea and I've put it onto our backlog.
I cannot estimate when this going to be implemented because there are also a lot of other things in the queue. however, contributions are very welcome :)

**Comment by mfussenegger** [comment]
Would supporting a query clause in the COPY TO statement also solve your partial exports needs?

Exporting data with crash has several shortcomings. (slower than copy to because the data has to be merged on one node instead of writing from each node to file directly. And you might also run into memory issues if your result-set is large because we don't yet support streaming data to a client, so the whole result-set has to fit into memory on one node)

**Comment by BernhardGruen** [comment]
Hi,

@mfussenegger 
The memory consumption while exporting using `crash` is a valid point. I just thought that patching `crash` would be a lot easier than programming a whole new keyword into the `COPY TO` statement.

To answer your question, yes, I think supporting something like a `WHERE` clause in `COPY TO` would solve my needs too.

**Comment by dobe** [comment]
@BernhardGruen  partitioned tables might also be of interest for you in order to partition your table by week or day. copy to supports partitions for exactly your usecase. see https://crate.io/docs/stable/sql/partitioned_tables.html

**Comment by BernhardGruen** [comment]
@dobe we already use partitioned tables in our experiments. In our case we have about 2 Mio of new rows each night. Therefore I thought it would be much more efficient if we would only backup those new rows instead of a monthly partition that grows from 2 Mio rows on day 1 to about 60 Mio rows on the last day of the month.

**Comment by dobe** [comment]
you are right! but if your application would allow for weekly partitions, i would accept the overhead of the duplicate exports.

**Comment by joemoe** [comment]
hi @BernhardGruen, in 0.54 we added the `WHERE` clause to the `COPY TO` statement. 
https://crate.io/docs/reference/en/latest/sql/reference/copy_to.html#where-clause
does this match your requirements?

**Comment by mfussenegger** [comment]
Closing this.
In order to export stuff incrementally it is now possible to either use snapshots or COPY TO with the WHERE clause.
And Crash has also received a ``json_row`` output format, which is a format that is compatible with COPY FROM.
