### ISSUE TITLE
Feature request: Use slf4j as the logging facade

### ISSUE THREAD

**Issue by bquenin** [crate/crate#2591]
Hi,

It would be great if you guys can use slf4j as logging library so that one could plug any logging implementation (log4j, logback, JUL, etc.)

What do you think of this ?

Thanks

**Comment by celaus** [comment]
Hi! 

Thanks for your interest in Crate! The good news is: We already use slf4j. Sort of: We rely on elasticsearch's ESLogger facility, which uses slf4j in case log4j is not present: https://github.com/crate/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/logging/ESLoggerFactory.java#L43

For this reason, the slf4j dependency is also excluded in the client's gradle.build and including it won't change anything if log4j is still available. For explicitly supporting slf4j, we will need to take a closer look. However if you want to try it yourself, we are always happy with new insights and pull requests ;)

All the best, Claus

**Comment by bquenin** [comment]
Thanks! I'll take a closer look then ;)

**Comment by bquenin** [comment]
Looking into the crate-client-0.50.5.jar, it looks like log4j is shaded (not relocated though) inside the client. That's probably why the slf4j fallback doesn't trigger.
I don't know where log4j come from though.

**Comment by celaus** [comment]
Hi, 

sorry for the late response, but specifically regarding the client: As it depends on the ES  build, log4j (https://github.com/crate/crate/blob/master/es/build.gradle#L46) and slf4j would both be included in the jar. However, to avoid duplication the client build excludes slf4j with this line: https://github.com/crate/crate/blob/master/client/build.gradle#L26 

Essentially, what you can try is excluding log4j and including slf4j in the gradle build. I hope this helps!

All the best, Claus

**Comment by bquenin** [comment]
Sorry I'm a a bit confused because I think that's what my pull request is doing.

**Comment by celaus** [comment]
Hi, I think your pull request excludes both, slf4j and log4j. Anyway I have passed it on to our "jar dependency guru" (@mfelsche) :) He will take a (close) look. 

Cheers, Claus

**Comment by bquenin** [comment]
ok thanks :)

**Comment by bquenin** [comment]
Closing as it's not an issue (anymore).
