### ISSUE TITLE
Blob download incomplete?

### ISSUE THREAD

**Issue by Samuman** [crate/crate#2654]
Hey,

I followed following documentation to upload blobs:
https://crate.io/docs/projects/crate-python/stable/blobs.html

Somehow while doing executing .get() for blob, Im receiving incomplete results. I also tried to download blob using curl, but I get following error message:

    curl -sS 'node1:4200/_blobs/myblobs/e41ea8fa06f2f556107342bc470fd6f8fa4c5c2e'
    <stdout>
    curl: (18) transfer closed with 123137026 bytes remaining to read

Documentation says: "The result is a generator object which returns one chunk per iteration", but in my case generator iterates always only once, although my blob is few hundred megs in size.

Is this correct behaviour?

**Comment by mfussenegger** [comment]
This behaviour isn't correct.

Do you have a proxy or something inbetween your client and crate?
Which version of Crate are you using and are there any warnings or errors in the log?

**Comment by Samuman** [comment]
I'm using 0.50.6, without any proxy.

Ubuntu 14.04.3 LTS
3.16.0-30-generic

Nothing gets appended to /var/log/crate/crate.log while trying to download blobs, but I can see bunch of messages similar to this: 

    [2015-09-30 17:37:00,862][INFO ][io.crate.executor.transport.TransportCloseContextNodeAction] Couldn't find JobExecutionContext for jobId: 42af35da-be69-4d6c-a377-d4fe71d9c363

I tried some smaller blobs (few hundred kilobytes) and they work fine, but anything larger than few megabytes is still failing.

**Comment by mfussenegger** [comment]
The entries in the log are harmless (and I think in master they're already on debug or even trace level instead of info).

How many nodes do you have in your cluster - and if it is more than 1, can you run `curl` with `-v` and paste the output?

**Comment by Samuman** [comment]
2 nodes, this is the output from curl from both of the nodes:

```
* Connected to node1 (192.168.1.39) port 4200 (#0)
> GET /_blobs/myblobs/e41ea8fa06f2f556107342bc470fd6f8fa4c5c2e HTTP/1.1
> Host: node1:4200
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 123280378
< Accept-Ranges: bytes
< Expires: Thu, 31 Dec 2037 23:59:59 GMT
< Cache-Control: max-age=315360000
< 
{ [1448 bytes data]
* transfer closed with 123137026 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 123137026 bytes remaining to read
```

```
* Connected to node2 (192.168.1.191) port 4200 (#0)
> GET /_blobs/myblobs/e41ea8fa06f2f556107342bc470fd6f8fa4c5c2e HTTP/1.1
> Host: node2:4200
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 123280378
< Accept-Ranges: bytes
< Expires: Thu, 31 Dec 2037 23:59:59 GMT
< Cache-Control: max-age=315360000
< 
{ [1448 bytes data]
* transfer closed with 123238386 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 123238386 bytes remaining to read
```

I also tried to shut down one of the nodes but it didn't make any difference.

**Comment by mfussenegger** [comment]
Seems like this is a regression that slipped into 0.50.4 (and wasn't caught by our test-suite as it doesn't seem to occur if the client is on the same machine as the crate process)

We're working on a fix. Thanks for reporting

**Comment by mikethebeer** [comment]
Hi Samuman,

we have fixed this bug now (see https://github.com/crate/crate/commit/7945a7b55133e82dda28af3babac693098decc7f) and it will be released soon.

Regars,
Michael
