### ISSUE TITLE
Excessive use of first client listed in JDBC connection string

### ISSUE THREAD

**Issue by reversefold** [crate/crate#2733]
We are seeing one of our crate client nodes get many more connections than the other client nodes and I have tracked this down to how the nodes are selected by the internal elasticsearch transport class. The node with the larger number of connections is the first node listed in the JDBC connection string. I've submitted a very simple fix to the elasticsearch project but I'm hoping you can include it in your internal version.

https://github.com/elastic/elasticsearch/pull/14143

**Comment by joemoe** [comment]
it is fixed with crate-jdbc 1.9.2
https://github.com/crate/crate-jdbc/blob/master/CHANGES.txt#L8
https://bintray.com/crate/crate/crate-jdbc/1.9.2/view
