### ISSUE TITLE
LIKE queries not working properly when using the '|' character

### ISSUE THREAD

**Issue by boriel** [crate/crate#2760]
I'm experiencing some problems when using the pipe '|' character within a LIKE query, like this:
`select count(*) from source_venue where svid like '3|%';`
It always returns all rows. However, escaping the | character gives the right results:
`select count(*) from source_venue where svid like '3\|%';`

This seems to be a bug in the LIKE <pattern> parsing.

**Comment by mikethebeer** [comment]
@boriel thanks for the report. We are currently fixing the issue and fix it in current stable (v0.51) and testing (v0.52). I will inform you asap.

**Comment by mikethebeer** [comment]
bug is fixed in master https://github.com/crate/crate/commit/3ee3f69a3565e1129393161b10806af67418883d and v0.51 + 0.52 will get a hotfix.
