### ISSUE TITLE
Document Collection Types - Alternative to Joins

### ISSUE THREAD

**Issue by crudbug** [crate/crate#2821]
Crate provides a robust SQL layer on top of ES. 

Having Collection types - Doc, DocMap, DocList, DocSet, which links to other documents / rows will be very useful. 

This is similar to OrientDB Link types- http://orientdb.com/docs/last/Types.html

For this to work, the tables can be treated as "User Defined Types" and  collections can be defined. This generates a document graph model. 

```
(address: STRING, city: STRING, country : STRING) : ADDRESS_TABLE
(name: STRING, address : Doc<ADDRESS_TABLE>, friends : DocList<PERSON_TABLE> ) : PERSON_TABLE
```

For Query we can traverse the document graph using "." operator
```
SELECT * FROM PERSON_TABLE WHERE address.city = "NYC"
```

I can also query the ADDRESS_TABLE separate

```
SELECT * FROM ADDRESS_TABLE
````

**Comment by chaudum** [comment]
@crudbug 
Crate is not just a robust layer on top of ES. As of now, additionally to primitive types we also support  following data types:

**geographic types**
* geo_point
* geo_shape

**compound types**
* object
* array

`OBJECT` and `ARRAY` are probably the types you are looking for.
More info on data types: https://crate.io/docs/en/latest/sql/data_types.html

Additionally, we've also released a first implementation of [JOINs]
(https://crate.io/docs/en/latest/sql/joins.html) that you can use to join tables.

Best,
Christian
