### ISSUE TITLE
Live Query or Notification Support

### ISSUE THREAD

**Issue by crudbug** [crate/crate#2822]
Ability of push query results or any changes to table / row back to any registered clients. 

Similar to : https://www.pipelinedb.com

**Comment by joemoe** [comment]
Hi @crudbug, we are putting this on our Backlog, but as this isn't the direction we are heading to, we won't implement this in the near future. Johannes

**Comment by chaudum** [comment]
Possible duplicate of https://github.com/crate/crate/issues/1376 ?
