### ISSUE TITLE
If long  single statement entered into crash prompt, it's behavior is erratic.

### ISSUE THREAD

**Issue by ajaybhatnagar** [crate/crate#3041]
Crate Version 0.52.3

cr> CREATE TABLE crate_table (
      Id integer,
       Name  string,
       Address  string,
        Email  string,
        Phone  string,
        Company  string,
         Account string ,
         Ccard string ,
         Country  string,
         Remarks string ) ;

CREATE OK (0.930 sec)
cr> INSERT INTO crate_table (Id,Name,Address,Email,Phone,Company,Account,Ccard,Country,Remarks) VALUES (1,"Deborah","P.O. Box 148, 4229 Curae; Rd.","sem.Pellentesque.ut@cursusdiam.edu","1-323-316-2934","Sed Institute","LB72337709696122662164779536","7168","Côte D'Ivoire (Ivory Coast)","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");

Statement was cut and paste from note pad. Subsequent output with each enter was:

     select
     insert
     update
     delete
     table
     index
     from
     into
     where
     values
     and
     or
     set
     with
     by
     using

**Comment by chaudum** [comment]
hi @ajaybhatnagar 

thanks for reporting the issue. the list of keywords appears when there is a whitespace in the beginning of the line (just after the `cr>` prompt) and is part of the built in auto-completion.
you probably pasted a newline and/or an additional whitespace at the end of the last sql statement directly from notepad.

however, we will try to improve the auto-completion behaviour of the crate shell!

best,
christian

**Comment by ajaybhatnagar** [comment]
No entire long line was just one statement. I  notice if the the statement is longer than display , cut & paste did not cause it to roll to next   line automatically  where as manually typing the statement , it automatically moves to next line and works .
Manually typed command below with automatic roll:
cr> INSERT INTO crate_table (Id,Name,Address,Email,Phone,Company) VALUES (1,'Deborah','address','xx'
    ,'yy','zz');
INSERT OK, 1 row affected (0.057 sec).

Also is there any documentation to how to import data from Hadoop and other RDBMS ? Could not find on the website.

**Comment by chaudum** [comment]
@ajaybhatnagar we don't have any documentation about importing data from hadoop, however we have a guide for [mysql migration](https://crate.io/docs/reference/en/latest/best_practice/migrating_from_mysql.html)

**Comment by mfussenegger** [comment]
The copy & paste behaviour should be improved in the latest version of crash so I'm closing this.
