### ISSUE TITLE
Casting of time/date values to long

### ISSUE THREAD

**Issue by cltompkins** [crate/crate#3042]
When dynamically creating a column, via INSERT, with a value in MySQL date format, i.e. '2015-12-31', the column is created with data type 'long' and is treated as data type 'timestamp'. But all subsequent INSERT's that also include the data in MySQL date format fail to cast the value to data type 'long'.

Why cast the string at all? Dynamic columns seem to use only basic types, i.e. 'string','long','double', so why assume a 'timestamp' value and define it as a long. I understand that 'timestamps' are stored as 'long' values, but the default casting that 'timestamps' handle doesn't seem to work for 'longs'.

![screencapture](https://cloud.githubusercontent.com/assets/11198696/11573972/fbd27654-99d6-11e5-9a85-7dfeec9b8e57.png)

**Comment by kovrus** [comment]
@cltompkins we are working on this issue now. The only solution for that what you are trying to achieve now is to have the ``timestamp`` column defined beforehand.

**Comment by bogensberger** [comment]
@cltompkins thanks for reporting the issue. I disabled the type detection for timestamps. I've backported the fix to 0.52 and 0.53 so with the next hotfix releases the string in your usecase won't be converted to a timestamp and the column is created as a string column. So it won't be possible anymore to create a timestamp column dynamically and timestamp columns have to be defined explicitly.

**Comment by cltompkins** [comment]
That will work for us. But be aware that even though the type detection may see the string as a date and treat it like a timestamp, the column was actually created with type long. It is here the failure lies, as a timestamp column will continue to convert string dates to long timestamps, but a long column will not.
