### ISSUE TITLE
Returning _id after insert

### ISSUE THREAD

**Issue by lovasb** [crate/crate#3045]
Hi all,

A forked the python crate repository, and try to finish the Django bindigs. Is almost working, but I have an issue with the built in _id field: Is there any chance to return the generated value of the _id field after insert?
Like by Mysql: INSERT INTO "table" VALUES (.....) RETURNING "table"."_id"

Thanks forwards,
Bence
##

**Comment by joemoe** [comment]
Hi @lovasb, thanks for your suggestion. We don't support this feature at the moment, but we put it on the backlog. We already got quite a list there and I'm not sure when we could expect this to be implemented, but I'll keep you on track. 
Best Regards, Johannes

**Comment by Mmuzaf** [comment]
Hi @joemoe, I like this feature too. Can I contribute and implement this enhancement?

**Comment by joemoe** [comment]
hi @Mmuzaf, yes of course. whenever you have a pull request we're happy to review it.
just be sure to follow these instructions: https://crate.io/community/contribute

**Comment by mfussenegger** [comment]
This got implemented (https://github.com/crate/crate/pull/9624) and will be released as part of 4.2
