### ISSUE TITLE
Add regexp_find

### ISSUE THREAD

**Issue by notzippy** [crate/crate#3116]
A missing feature the regexp_matches needs is a function that would match multiple pattern groups. ie Global matches For example

```
regexp_find('me,it,they,why', '([^,]*),') 

Outputs
me
if
they
why
```

This could be a straight copy from the MatchesFunction with a small change to add the results of "matcher.find()" to an array together. And perhaps normalizing the results if the groups found equals one (so that the returned array would be just an array of items and not an array of an array of items).

thanks
##

**Comment by joemoe** [comment]
hi @notzippy, thanks, we'll add this on our backlog. will keep you up to date on that issue. best, johannes

**Comment by nsandeepa** [comment]
hi,
I would like to contribute this enhancement. Because currently I am interested in a Google Summer of Code project which is based on crate repository. I think contributing to this issue will make easier me to get familiar with the source. So anyone please guide me how to proceed forward on this issue.

**Comment by joemoe** [comment]
hi @nsandeepa, this is something that is harder than it looks at the first glance, because it is generating rows. we'll look into something that might be easier for a starting point and suggest it to you.

**Comment by joemoe** [comment]
@nsandeepa we were thinking of something like ceil and floor: http://www.postgresql.org/docs/8.4/static/functions-math.html
can you join our slack channel, so we could talk through this: https://crate.io/docs/support/slackin/

**Comment by nsandeepa** [comment]
@joemoe thanks for the reply. I will look into it soon.

**Comment by diyism** [comment]
It had been implemented:
https://crate.io/docs/crate/reference/en/latest/sql/scalar.html#regexp-matches-source-pattern-flags
