### ISSUE TITLE
Bulk insert results in SQLActionException[Aborted context preparation as an infinite loop was detected]

### ISSUE THREAD

**Issue by notzippy** [crate/crate#3120]
Version 0.54 testing
The following update using the bulk http method causes an error `SQLActionException[Aborted context preparation as an infinite loop was detected]`

    {"stmt":"update mytable set state='current' where _id = ?","bulk_args":[["AVGLbTb-EYiArH5Sm4MK"],["AVGdtqBBT4032NIh5CBh"]]}

Passing a single argument for the `_id` it works

    {"stmt":"update mytable set state='current' where _id = ?","bulk_args":[["AVGLbTb-EYiArH5Sm4MK"]]}

**Comment by seut** [comment]
Thanks for reporting. We were not able to reproduce your issue with a simple table and an update using the "_id" column in the where clause like you did. Can you please provide us more information like your create table statement, used JVM and OS ? Thanks.

**Comment by notzippy** [comment]
Sorry for delayed response... The table I was working with has 4.7 million records, across 40 shards at 4 shards/partition.

**Comment by adrpar** [comment]
In order to replicate the issue, could you please provide us the `CREATE TABLE` statement of your table and information about the used JVM and OS? Or are you able to provide us with a description on how to reproduce the error? Thanks for your help.

**Comment by adrpar** [comment]
If you could also provide a stack trace when the error occurs, that would help us a lot. A stack trace can be obtained (if you are using CRASH) by starting CRASH in verbose mode: ``crash -v``, or if you are using the HTTP REST endpoint by setting ``error_trace=True``: e.g. ``curl -sSXPOST '127.0.0.1:4200/_sql?pretty&error_trace=True' -d ...``

**Comment by joemoe** [comment]
hi @notzippy is this still an issue for you?
