### ISSUE TITLE
geo_point insert error

### ISSUE THREAD

**Issue by notzippy** [crate/crate#3131]
Given table 
geocity (
 geo geo_point
)
http Statement
{"stmt":"INSERT INTO \"geocity\" (\"geo\") VALUES (?) ",
"bulk_args":[[[1,1]]]} 

Results in
"SQLActionException[ArrayStoreException in java.util.Arrays.copyOf(Arrays.java:3213)]"

Yet the following works fine
{"stmt":"INSERT INTO \"geocity\" (\"geo\") VALUES (?) ",
"bulk_args":[["POINT(1 1)"]]} 

On an aside it would be nice if you also supported the mapped method of inserting the geo-point..

thanks

**Comment by mfussenegger** [comment]
Seems like it fails because the points should be double's and not integers.

See:
```
http -v localhost:4200/_sql stmt="insert into geocity (geo) values (?)" bulk_args:='[[ [1.0, 1.0] ]]'
POST /_sql HTTP/1.1
{
    "bulk_args": [
        [
            [
                1.0,
                1.0
            ]
        ]
    ],
    "stmt": "insert into geocity (geo) values (?)"
}

HTTP/1.1 200 OK
Content-Length: 51
Content-Type: application/json; charset=UTF-8

{
    "cols": [],
    "duration": 2,
    "results": [
        {
            "rowcount": 1
        }
    ]
}
```

I'm not sure if it makes sense to be more lenient in this case. But we should at least improve the error message.

What exactly do you mean with 

> On an aside it would be nice if you also supported the mapped method of inserting the geo-point..

**Comment by notzippy** [comment]
Well d'oh, it appears the encoder in go tends to use integers when possible ..

Re second point [see also](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-geo-point-type.html#_lat_lon_as_properties_5) Basically allow for a use of a mapped value for lat and lon

    {
        "bulk_args": [
            [
                {
                    "lat":1.0,
                    "lon":1.0
                }
            ]
        ],
        "stmt": "insert into geocity (geo) values (?)"
   }

**Comment by chaudum** [comment]
hi @notzippy 
we probably won't support the ES specific object notation for `GEO_POINT` type. since we use GeoJSON for `GEO_SHAPE` type, we could think about supporting that for `GEO_POINT`, too. will put that into our backlog and we'll discuss that internally.

**Comment by mfussenegger** [comment]
@notzippy The issue you reported has popped up again so've changed the behaviour and made it more lenient so that conversion from arrays of integers works too.

See https://github.com/crate/crate/pull/3294

**Comment by boriel** [comment]
Just for the record, I bumped into this issue today, and had to workaround it by using is string 'POINT(lon lat)' representation as @notzippy pointed out above. We're using javascript for this task, and it's pretty cumbersome to enforce "float type" in a typeless language like javascript (basically the JSON just encode the field as a number and does not add '.0' and the end).

Supporting "integers" (a.k.a. a subset of float numbers) directly from crate will ease many things to the developer. :+1:

**Comment by notzippy** [comment]
Ran into a rather bigger annoyance with this issue version .55

Inserting a geo_point into an array of geo_points - the only form you can do so is using the "point (1 1)" method. An error is thrown if you nest an array within the array. So in some cases you need to define one way others another..
