### ISSUE TITLE
copy from command duplication

### ISSUE THREAD

**Issue by notzippy** [crate/crate#3133]
When I use the [`copy from`](https://crate.io/docs/reference/en/latest/sql/reference/copy_from.html) command in a 4 node cluster every row imported is imported 4 times..
Version 5.4 test

**Comment by mfussenegger** [comment]
Are the files you're importing on a shared file system? If so you need to use the [shared option](https://crate.io/docs/reference/sql/reference/copy_from.html#shared)

**Comment by joemoe** [comment]
hi @notzippy, does this fix your problem?

**Comment by notzippy** [comment]
Sorry, yes it did.
