### ISSUE TITLE
Bulk API

### ISSUE THREAD

**Issue by afrozl** [crate/crate#3134]
Does crate provide an API for bulk inserts similar to the one elaticsearch provides? If not, is it acceptable to enable the elasticsearch API?

**Comment by mfussenegger** [comment]
Crate does provide a API for bulk inserts. 

- [HTTP Bulk api](https://crate.io/docs/reference/sql/rest.html#bulk-operations)

Most of the clients also expose this in some formt. As examples:

- [java client bulk operations](http://crate-java.readthedocs.org/en/latest/client.html#bulk-operations)
- [python executemany](http://crate-python.readthedocs.org/en/latest/client.html#inserting-data)

**Comment by afrozl** [comment]
Thanks,  I see this example in the docs:

<pre>
sh$ curl -sSXPOST '127.0.0.1:4200/_sql?pretty' -d@- <<- EOF
... {"stmt": "INSERT INTO locations (id, name, kind, description)
...          VALUES (?, ?, ?, ?)",
... "bulk_args": [
...     [1337, "Earth", "Planet", "An awesome place to spend some time on."],
...     [1338, "Sun", "Star", "An extraordinarily hot place."],
...     [1339, "Titan", "Moon", "Titan, where it rains fossil fuels."]
... ]
... }
... EOF
</pre>

Can the ids be auto-generated for bulk inserts?

**Comment by mikethebeer** [comment]
@afrozl crate does not support auto-increment. I would rather consider to remove the `id` column and use the auto-generated document-id column `_id` instead which is a [UUID](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) and therefore unique for each row.
