### ISSUE TITLE
'directory' cannot be used as object column name ? 

### ISSUE THREAD

**Issue by SpareShade** [crate/crate#3142]
Hello :)
I am getting the bellow error
```json
Client error: `POST http://localhost:4200/_sql` resulted in a `400 Bad Request` response:
{"error":{"message":"SQLActionException[line 1:80: no viable alternative at input 'directory']","code":4000}}
```
where I try to create a table as in eg.
```js
create table inv.products (
...
	profile_img object(dynamic) as (
		id string,
		directory string,
		filename string
	)
...
);
```

I can see that DIRECTORY keyword is used for COPY TO, but not within CRATE TABLE statement.

Is the above error really supposed to happen ?

**Comment by kovrus** [comment]
Hi @SpareShade,
_directory_ is a reserved word. If you want to use the reserved words as a column name you would need to escape it. Here is an example:
```
curl -sSXPOST 'localhost:4200/_sql?pretty' -d '{"stmt":"create table test (\"directory\" string)"}'
```

**Comment by kovrus** [comment]
@SpareShade you can see the list of reserved words [here].(https://crate.io/docs/reference/en/latest/sql/reference/lexical_structure.html#key-words-and-identifiers)
