### ISSUE TITLE
OOM during bulk operations with big data set

### ISSUE THREAD

**Issue by scanban** [crate/crate#3209]
We are using 2x node crate.io cluster to store telemetry information acquired from the cars. We have several large tables (more than 10M rows). During transition to the new HW we was forced to export (copy to) and import (copy from) those tables.

Unfortunately cluster was breaking after importing around 1M of records. Further analysis shows that we are getting OOM. Most of the heap was filled with **"io.crate.executor.transport.ShardUpsertRequest"** objects. Root cause of this is an uncontrolled submitting of records to the **"org.elasticsearch.action.bulk.BulkShardProcessor"** **"add"** method.

Cluster consists of the 2 amazon EC2 r3.large (2 vCPU, 15.25 GB ram, 256GB disk) instances. Test table has 4 shards. Tried it with 1 or 0 replicas. Pre and post patch tests were run on one of the mentioned instances. 

Same problem exists for the "insert into (select)" operation on big datasets. I'd added a throttling to the process of the pumping data to the elastic. Please see patch attached, patch was generated against 0.54 branch. After applying this patch I was able to successfully load with "copy from" and copy data to other table with "insert into (select)" 26M rows dataset.

[0001-Bulk-processing-throttling.patch.txt](https://github.com/crate/crate/files/103492/0001-Bulk-processing-throttling.patch.txt)
##

**Comment by mfussenegger** [comment]
Are you sure that the ShardUpsertRequest objects you were seeing were in the BulkShardProcessor (the sending node) and not in TransportShardUpsertAction (receiving node)?

How much memory did you assign as JVM HEAP?

We'll try to reproduce this and then see how we can fix this.
I don't think that we'll be able to use the patch you provided. Sleeping somewhere can lead to serious performance issues as we'd block a thread.

Thanks for the report and the effort you put into debugging this.

**Comment by scanban** [comment]
I was hit with this problem running 12G heap on 0.54.3 docker image. The high level view of this issue is: thread that loading records from the export file pumping at a much higher speed that elastic writer thread could write, which is lead to rapid growth of the **org.elasticsearch.common.util.concurrent.SizeBlockingQueue** . To track down this, and be able to analyze heapdump, I was running tests with 2G heap.

Sure, this patch is a quick problem solution. After applying it, I was able to import more than 26M rows of our exported data. Of course wait time must have better granularity or changed to the condition variable wait which may be set here https://github.com/crate/crate/blob/0.54/sql/src/main/java/org/elasticsearch/action/bulk/BulkShardProcessor.java#L405-L412 .

**Comment by mfussenegger** [comment]
I've tried to reproduce this with a 18M / 6.1GB data set on a 2 node cluster. I've set the HEAP size to 1GB but still wasn't able to reproduce the issue.

Did you by chance change the thread-pool settings? The writer thread pool size and queue sizes by default are fixed and limited which should prevent a unbound growth of the SizeBlockingQueue which you are seeing.
Once the Queue is full it will cause ExecutionRejectedExceptions which in turn will cause the BulkShardProcessor to start blocking and slow down the read operation.

**Comment by scanban** [comment]
No, I was run the docker image of the 0.53 (0.54 as well) with the cmdline below. How much CPU power do you have on your cluster ? I'd run it on the 2CPU AWS instance. 

> docker run -d \
>     -p 4200:4200 \
>     -p 4300:4300 \
>     --name cdrive-crate \
>     --volume /data01/crate:/data \
>     --env CRATE_HEAP_SIZE=10g \
>     --net="host" \
>     --ulimit nofile=262144:262144 \
>     crate-0.54:cdrive \
>     crate -Des.cluster.name=crate-aws \
>           -Des.node.name=cdrive-crate-aws-01 \
>           -Des.transport.publish_port=4300 \
>           -Des.network.publish_host=$PRIVATE_IP \
>           -Des.multicast.enabled=false \
>           -Des.discovery.zen.ping.unicast.hosts=$HOSTS \
>           -Des.discovery.zen.minimum_master_nodes=2 \
> 	  -Des.gateway.expected_nodes=2 \
> 	  -Des.gateway.recover_after_nodes=2
![dominator_tree](https://cloud.githubusercontent.com/assets/4647358/12760597/694df934-c9e7-11e5-9efc-34c7313840ef.png)
![retained](https://cloud.githubusercontent.com/assets/4647358/12760598/69513162-c9e7-11e5-9e5b-193960482d46.png)

**Comment by mfussenegger** [comment]
How large are your individual records? Would it be possible to provide a sample record (with the schema), or even a whole sample set?

I didn't test on EC2 but just tried again and throttled disk IO write speed and the number of CPUs the docker container can use to 2. Still no luck. 
But the data I used contains very small individual records so I assume that you have pretty large records.

The internal default bulk size is 10000, and the bulk thread-pool queue size is 50 which would fit with your 500k ShardRequestItems that are hold into memory. If those don't fit into memory it would explain your OOMs.

For copy from you could reduce the bulk_size using `copy <table> from 'source' with (bulk_size = 1000)`

But for `insert into from (select..` that's not possible. So we'll have to tweak the default and also include the size of the individual records.

**Comment by scanban** [comment]
IMHO need to have some global resource control on this queue, which 'll take into account available memory, record sizes and sessions count, because multiple sessions could run bulk operations in parallel.

I'd created python data generator script, generate data in export format.
[datagen.py.txt](https://github.com/crate/crate/files/117288/datagen.py.txt)

Table creation script:
```
create table cl_test_data (
 c integer,
 v integer,
 t timestamp,
 d object(dynamic)
) clustered by (v) into 4 shards;

```
Table structure with **d** fields:
```
cr> SHOW CREATE TABLE cl_test_data; 
+----------------------------------------------------------+
| SHOW CREATE TABLE doc.cl_test_data                       |
+----------------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."cl_test_data" (        |
|    "c" INTEGER,                                          |
|    "d" OBJECT (DYNAMIC) AS (                             |
|       "GPS"."SURFACE_KINETIC"."BEARING" DOUBLE,          |
|       "GPS"."SURFACE_KINETIC"."BEARING_ERROR" STRING,    |
|       "GPS"."SURFACE_KINETIC"."SPEED" DOUBLE,            |
|       "GPS"."SURFACE_KINETIC"."SPEED_ERROR" DOUBLE,      |
|       "GPS"."SURFACE_LOCATION"."LATITUDE" DOUBLE,        |
|       "GPS"."SURFACE_LOCATION"."LATITUDE_ERROR" DOUBLE,  |
|       "GPS"."SURFACE_LOCATION"."LONGITUDE" DOUBLE,       |
|       "GPS"."SURFACE_LOCATION"."LONGITUDE_ERROR" DOUBLE, |
|       "IMU"."ACCEL"."X" DOUBLE,                          |
|       "IMU"."ACCEL"."Y" DOUBLE,                          |
|       "IMU"."ACCEL"."Z" DOUBLE,                          |
|       "IMU"."COMPASS"."X" DOUBLE,                        |
|       "IMU"."COMPASS"."Y" DOUBLE,                        |
|       "IMU"."COMPASS"."Z" DOUBLE,                        |
|       "IMU"."FUSION_QPOSE"."S" DOUBLE,                   |
|       "IMU"."FUSION_QPOSE"."X" DOUBLE,                   |
|       "IMU"."FUSION_QPOSE"."Y" DOUBLE,                   |
|       "IMU"."FUSION_QPOSE"."Z" DOUBLE,                   |
|       "IMU"."GYRO"."X" DOUBLE,                           |
|       "IMU"."GYRO"."Y" DOUBLE,                           |
|       "IMU"."GYRO"."Z" DOUBLE,                           |
|       "IMU"."TEMP" DOUBLE,                               |
|       "OBDII"."LOAD" DOUBLE,                             |
|       "OBDII"."MAF" DOUBLE,                              |
|       "OBDII"."RPM" DOUBLE,                              |
|       "OBDII"."SPEED" LONG,                              |
|       "OBDII"."TEMP" LONG,                               |
|       "OBDII"."TPS" DOUBLE,                              |
|       "OBDII"."TRANSMISSION TEMP" LONG,                  |
|       "OBDII"."VOLTAGE" DOUBLE                           |
|    ),                                                    |
|    "t" TIMESTAMP,                                        |
|    "v" INTEGER                                           |
| )                                                        |
| CLUSTERED BY ("v") INTO 4 SHARDS                         |
| WITH (                                                   |
|    "blocks.metadata" = false,                            |
|    "blocks.read" = false,                                |
|    "blocks.read_only" = false,                           |
|    "blocks.write" = false,                               |
|    column_policy = 'dynamic',                            |
|    "gateway.local.sync" = 5000,                          |
|    number_of_replicas = '0',                             |
|    "recovery.initial_shards" = 'quorum',                 |
|    refresh_interval = 1000,                              |
|    "routing.allocation.enable" = 'all',                  |
|    "routing.allocation.total_shards_per_node" = -1,      |
|    "translog.disable_flush" = false,                     |
|    "translog.flush_threshold_ops" = 2147483647,          |
|    "translog.flush_threshold_period" = 1800000,          |
|    "translog.flush_threshold_size" = 209715200,          |
|    "translog.interval" = 5000,                           |
|    "unassigned.node_left.delayed_timeout" = 60000,       |
|    "warmer.enabled" = true                               |
| )                                                        |
+----------------------------------------------------------+
```

**Comment by mfussenegger** [comment]
Thanks for the schema and script. With that I was able to reproduce the issue.

For now as a workaround you can reduce the bulk thread queue size and in case of COPY also set a lower bulk_size (using `WITH (bulk_size = ...)`).

If you do initial imports using COPY FROM we also recommend to set the number_of_replicas to 0 and increase it after the initial import is done. This way the import is faster and it will also require less memory during the import.

**Comment by mfussenegger** [comment]
We've had made some changes to COPY FROM in 2.0/2.1 which should've solved this. So I'm closing this for now.
