### ISSUE TITLE
Small UPDATEs using & leaking a lot of memory

### ISSUE THREAD

**Issue by benjaminrigaud** [crate/crate#3274]
Dear Crate team,

I have many tables (one per month) with about 200M docs and 4 shards / 1 replica.
Crate 0.54.5 on Ubuntu 14.04

Am doing small updates (modifying few hundreds / thousands of documents) like:

UPDATE my_table SET field_id=1234 WHERE field_id=-1;

The first UPDATE are going well (still a bit slow).
Then it fails with errors such as:

CircuitBreakingException: [FIELDDATA] Data too large, data for [_uid] would be larger than limit of [22705287987/21.1gb]]
CircuitBreakingException: [PARENT] Data too large, data for [_uid] would be larger than limit of [22705287987/21.1gb]]

I increased indices.breaker.fielddata.limit and indices.breaker.total.limit : it works for few more UPDATEs.

But the HEAP Usage on a unique machine (it doesn't seem to be the master) increases at each UPDATE and doesn't decrease : I have to restart it.

It looks like each UPDATE is fetching a lot of data into memory and won't release it.

Ben

**Comment by joemoe** [comment]
Hi @benjaminrigaud, we are looking into this on Monday morning.

**Comment by joemoe** [comment]
hi @benjaminrigaud, as @chaudum told me this issue might be solved. Is it okay for you to close this issue? If this is happening again and you have more detailed information you can open a new one.

**Comment by benjaminrigaud** [comment]
Hello,

From our last discussion, @chaudum couldn't reproduce the memory leak issue. 

The high memory usage is the most concerning in my case: the UPDATE (of few thousands of documents) requires approximately the size of the table (20-25Go for ~ 200M documents) in memory: I don't know if this is expected. Do you have any idea?

I still have to TRACE the circuit breaker to get a better view: I should be able to do that this week.

**Comment by joemoe** [comment]
no. it is not expected and as @chaudum said we aren't able to reproduce it.
for you this is still an issue?
so i leave this open. when you have any further findings we're happy to investigate.

**Comment by benjaminrigaud** [comment]
It is still an issue for me at this time:
I'll try to build a docker / sandbox env with some fake data thanks to cr8 / faker.
I should be able to do it this week or next week. 

Thank you.

**Comment by joemoe** [comment]
hi @benjaminrigaud, have you been able to try this?

**Comment by benjaminrigaud** [comment]
Not yet: too much work at this time. It is still on my TODO list :)

**Comment by joemoe** [comment]
hi @benjaminrigaud, this should also be fixed with 0.54.9 and 0.55.0 as we refactored a lot of stuff in this part of crate. therefore i'm closing this issue. feel free to open it again, whenever you hit it again.
