### ISSUE TITLE
0.54.5 crash

### ISSUE THREAD

**Issue by l7s** [crate/crate#3302]
Hi,

One of the nodes in 3 node cluster started crashing shortly after start (30-120 sec.) leaving core dump as below:

https://dl.dropboxusercontent.com/u/3182365/crate/hs_err_pid20324.log

any suggestions how to fix this and make this node work again much appreciated.

Regards,
Chris

**Comment by jodok** [comment]
hi chris,
our team is investigating! will get back to you asap.
jodok

**Comment by mfussenegger** [comment]
Are you still running on OpenVZ? If so, this could be related to https://github.com/crate/crate/issues/2461

**Comment by l7s** [comment]
No, this cluster runs on KVM, not OpenVZ.

**Comment by l7s** [comment]
Hi, to give you an update: the node has been now rebooted and after re-start Crate is not crashing any more.

**Comment by mfussenegger** [comment]
It seems this is caused by the compress-lzf library.
I've only found similar issues that occured on Solaris / Sparc. So this might be worth reporting upstream.

In Crate we'll eventually remove LZF and switch to DEFLATE during the upgrade of ES to 2.X (which we're currently working on)

**Comment by l7s** [comment]
Thanks for an update. Looking forward to upcoming ES 2.x release.

Would switching `indices.recovery.compress` to `false` in configuration provide temporary workaround? Or is there any other config option to disable compression to avoid this issue?

**Comment by mfussenegger** [comment]
Yes it should provide a workaround.
The all other places which can use compression already default to false (at least currently - that will also change)
