### ISSUE TITLE
Logstash Integration

### ISSUE THREAD

**Issue by loms0815** [crate/crate#3371]
Is it possible to integrate logstash with crate.io?
If yes: 
How to create a daily index e.g. "logstash-2016.03.22"? (Is a daily index generally possible or supported under crate?)
Can the fields in an Elasticsearch TYPE ( or TABLE) be auto generated or is declaration the only way?
What must be considered if declaration is the only way?
Are there any examples?
Thanks a lot for your supply!
##

**Comment by joemoe** [comment]
hi @loms0815, we don't have a logstash integration at the moment. we'll put that onto the backlog.

**Comment by loms0815** [comment]
Hi @joemoe , is it possible in crate.io to store tables in an daily index, e.g. twitter-2016.03.01?
Eventually makes sense concerning datareorg and for big amount of data (I guess there is a size limit on lucene indices)?

**Comment by chaudum** [comment]
@loms0815 Partitions is probably what you are looking for. you can have a partition for each day for example: https://crate.io/docs/reference/sql/partitioned_tables.html

**Comment by mfussenegger** [comment]
Things have changed a bit since 2016 and we're putting more focus on SQL based tooling and also removed the ES API with 4.0.
