### ISSUE TITLE
Percentile Aggregation?

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3379]
Hi, is it possible to calculate "Percentile-Aggregations" like the one in Elasticsearch?

**Comment by joemoe** [comment]
hi @githubmui, as already answered on intercom. No not at the moment, but we put it on the backlog.

**Comment by githubmui** [comment]
Ok, thank you! 
BTW: Issue "Quantiles Aggregation" #1791 addresses the same enhancement.

**Comment by loms0815** [comment]
+1

**Comment by haoyixin** [comment]
+1

**Comment by bputt** [comment]
+100000000

**Comment by bogensberger** [comment]
Hi @githubmui, i just merged the percentile aggregation function to master: https://github.com/crate/crate/commit/0263df5614e885f339f83819c5ae494556ac5593

It will be released with the next feature release.

**Comment by joemoe** [comment]
hey @bputt, @haoyixin, @loms0815,
the percentile aggregation is in our 0.56 release.
https://github.com/crate/crate/blob/master/CHANGES.txt#L106
