### ISSUE TITLE
Auto generated Keys

### ISSUE THREAD

**Issue by loms0815** [crate/crate#3386]
Hi, I am investigating regarding auto generated keys (on server side). I tried the function "Random" to do the job but failed: 

cr> create table tt6 (
     id long,
     id2 double generated always as (random()), 
     title string, primary key (id2) );
CREATE OK (0.307 sec)
cr> insert into tt6 (id) values(1);
SQLActionException[Primary key is required but is missing from the insert statement]

Then I added also id to the expression and failed, too:

cr> create table tt6 (
     id double,
     id2 double generated always as (  id  +  random()),
      title string,
       primary key (id2) );
CREATE OK (0.300 sec)
cr> insert into tt6 (id) values(1);
SQLActionException[NoSuchElementException in java.util.ArrayList$Itr.next(ArrayList.java:834)]

But following expression is working:

cr> create table tt4 (
     id long,
     id2 long generated always as (id+1),
      title string,
      primary key (id2) );
CREATE OK (0.564 sec)
cr> insert into tt4 (id) values(11);
INSERT OK, 1 row affected (0.011 sec)

**Comment by loms0815** [comment]
Hi, the second approach to accomplished my usecase (autokey for log messages) was to search a hash function (e.g. MD5) as scalar function and use it in following way:

cr> create table tt4 (
    id long generated always as (HASH_FUNCTION(message)),
    message string,
    primary key (id) );
cr> insert into tt4 (message) values('bla bla');

But I couldn't find such a function and still have got the problem written in the former comment.
Do you know a way to solve my usecases with crate?

**Comment by joemoe** [comment]
hi @loms0815, crate already does this for you. every record has his own id. you can query it via ```_id```. It is not returned when doing a ```SELECT * FROM ...```, but when you explicitly query ```SELECT _id, * FROM...``` it is there.

**Comment by loms0815** [comment]
Hi @joemoe, thanks for the info!
