### ISSUE TITLE
Maybe Problem in Where-Clause of Delete Statement?

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3388]
In the WHERE clause of SELECT statements, terms can be exchanged. If I do the same in DELETE statements then I can see following behaviour in crate.io version "0.54.7".

First statement worked (TS is of type TIMESTAMP):
cr> DELETE FROM TestTable WHERE   TS < date_trunc('day', current_timestamp(0)-(1000*3600*100));
DELETE OK, -1 rows affected (0.008 sec)

Second statement (with exchanged terms in where clause) failed:
cr> DELETE FROM TestTable WHERE    date_trunc('day', current_timestamp(0)-(1000*3600*100)) > TS;
SQLActionException[io.crate.analyze.symbol.Reference cannot be cast to io.crate.analyze.symbol.Literal]

**Comment by bogensberger** [comment]
Hi,

thanks for reporting the issue. It's already fixed in our master branch and i applied a fix for 0.54.* (https://github.com/crate/crate/pull/3393) now. The fix will be released with the next crate release.
