### ISSUE TITLE
question: fielddata vs doc_values

### ISSUE THREAD

**Issue by perseo-dev** [crate/crate#3390]
Hi, i have a question.
I'm new to crate but i know a bit Elasticsearch. Latest versions of ES are pushing doc_values to bypass JAVA HEAP out-of-memory problems.
how does CRATE with this setting? creating a new TABLE, are all fields created with doc_values enabled or disabled? there is a way to control this behaviour?

thank in advance.

**Comment by perseo-dev** [comment]
I've found in "AnalyzedColumnDefinition.java" the following code:

`public boolean docValues() {
        return !isIndex()
                && collectionType == null
                && !dataType.equals("object")
                && index().equals("not_analyzed");
 }`

and

`public Map<String, Object> toMapping() {
        Map<String, Object> mapping = new HashMap<>();

        mapping.put("doc_values", docValues());
        ...
`

So it seems that doc_values is used fundamentally only for not indexed field.
doc_values relays on elasticsearch engine? if so, could be possible to specify in configuration file or in create table statement the flag to force the doc_values?

**Comment by joemoe** [comment]
hi, we'll look into this and provide an answer.

**Comment by dobe** [comment]
the `isIndex` means that the column is an index only column (e.g: for fulltext, see https://crate.io/docs/reference/sql/ddl.html#defining-a-named-index-column-definition) not that it is not indexed.

in crate any field that is not multivalued uses doc_values per default. analyzed fields are multivalued so no doc_values are used.

**Comment by perseo-dev** [comment]
thank you for the reply.
