### ISSUE TITLE
Problem with Full-Text-Search?

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3424]
Hi, 
I faced following strange situation:

1) Create table heartbeat with fulltext index (CreateTable.png)
2) Insert 10 identical rows (SelectTable.png)
3) Try match operator with message and also with message_ft. (FullTextSearchTable.png) 
Got always error: "SQLActionException[index (-1) must not be negative]"

Probably this is a "layer8"-problem? :-)
Do you have an idea?

![createtable](https://cloud.githubusercontent.com/assets/17704200/14455566/7bf35cf6-00a0-11e6-8767-01d22de63587.PNG)
![fulltextsearchtable](https://cloud.githubusercontent.com/assets/17704200/14455567/7bf41b78-00a0-11e6-9b97-921fdde91ca6.PNG)
![selecttable](https://cloud.githubusercontent.com/assets/17704200/14455568/7bf5e23c-00a0-11e6-9cf6-656d24023aa9.PNG)

**Comment by joemoe** [comment]
hi @githubmui, we'll have a look at it. thanks for reporting.

**Comment by kovrus** [comment]
Hi @githubmui, the fix is in master now. It is going to be released with the new 0.55 testing release.
Thanks for reporting!

**Comment by githubmui** [comment]
Hi kovrus,
thank you for super fast fix!
