### ISSUE TITLE
Changing number_of_replicas for a table affects more than 1 table

### ISSUE THREAD

**Issue by tellezb** [crate/crate#3428]
I'm attempting to change the number of replicas for my table. It successfully changes the setting for my table, but makes the same change to another (tweets) table.

Here are my table definitions:

```
CREATE TABLE IF NOT EXISTS "doc"."tweets" (
   "created_at" TIMESTAMP,
   "id" STRING,
   "retweeted" BOOLEAN,
   "source" STRING INDEX USING FULLTEXT WITH (
      analyzer = 'standard'
   ),
   "text" STRING INDEX USING FULLTEXT WITH (
      analyzer = 'standard'
   ),
   "user" OBJECT (STRICT) AS (
      "created_at" TIMESTAMP,
      "description" STRING INDEX USING FULLTEXT WITH (
         analyzer = 'standard'
      ),
      "followers_count" INTEGER,
      "friends_count" INTEGER,
      "id" STRING,
      "location" STRING INDEX USING FULLTEXT WITH (
         analyzer = 'standard'
      ),
      "statuses_count" INTEGER,
      "verified" BOOLEAN
   ),
   PRIMARY KEY ("id")
)
CLUSTERED BY ("id") INTO 5 SHARDS
WITH (number_of_replicas = '0-all');
```
```
CREATE TABLE IF NOT EXISTS "doc"."device_event" (
   "id" LONG,
   "reseller_id" INTEGER,
   "date_partition" STRING, 
   "value" FLOAT,
   PRIMARY KEY ("id", "reseller_id", "date_partition")
) 
CLUSTERED INTO 5 SHARDS
PARTITIONED BY ("reseller_id", "date_partition")
WITH (number_of_replicas='0-all');
```

![image](https://cloud.githubusercontent.com/assets/7115725/14469485/b798d968-0099-11e6-8eee-41cbe97bb69f.png)

Running the following statement to set number_of_replicas to 3 on the device_event table applies to change to both the device_event table **AND** the tweets table:

alter table device_event SET (number_of_replicas='3');

![image](https://cloud.githubusercontent.com/assets/7115725/14469509/d4be4e2e-0099-11e6-8300-336b50bfbe74.png)

This is happening In my (single-node) system running version 0.54.8 running in an Amazon Linux AMI. It happens every time, even after dropping and recreating the tables. Nothing else is connected to the database.

![image](https://cloud.githubusercontent.com/assets/7115725/14469610/60764bf6-009a-11e6-97a7-c4579f145137.png)

Any ideas?

**Comment by celaus** [comment]
Thanks - we can reproduce that and we'll have a look as soon as possible.

**Comment by seut** [comment]
@tellezb We've fixed this at our current master, see https://github.com/crate/crate/commit/d0bd531d085d2f93e04e2d5a823e8fd1b2f95de0. It will be released with the next hotfix release.
