### ISSUE TITLE
Error creating table with uppercase letters

### ISSUE THREAD

**Issue by faridjafri** [crate/crate#3438]
Creating table with uppercase letters gives an error saying "SQLActionException[table name "sch.myTable" is invalid.]"

 CREATE TABLE "sch"."myTable"(id string primary key);

![crateissue](https://cloud.githubusercontent.com/assets/17078085/14522928/aaf71dc6-024e-11e6-9641-a7e71d97d7cf.png)

**Comment by mfussenegger** [comment]
This is a limitation of Crate. Table names can't have uppercase characters. See [naming restrictions](https://crate.io/docs/reference/sql/ddl.html#naming-restrictions)

**Comment by faridjafri** [comment]
No I chose the table name, and yes I can switch to lower-case table names.
