### ISSUE TITLE
Weird Query Performance  (explain analyze - show query execution plan)

### ISSUE THREAD

**Issue by denisbetsi** [crate/crate#3442]
Running a query against a table with 500K entries.

This query

```
SELECT 
    distance(geo['salon'],[-118.4104684, 34.1030032])/1609.34 as distance  
FROM 
       users 
WHERE 
       isbanned != 'Y'  and usertype = 'S'
       and distance(geo['salon'],[-118.4104684, 34.1030032])/1609.34  < 30000.0 
order by distance 
limit 30;
```

takes anywhere from 2 to 6 seconds.

Minor tweak to the query

```
SELECT 
    distance(geo['salon'],[-118.4104684, 34.1030032])/1609.34 as distance  
FROM 
       users 
WHERE 
       isbanned != 'Y'  and usertype = 'S'
       and distance(geo['salon'],[-118.4104684, 34.1030032])   < 30000.0 
order by distance 
limit 30;
```

Note the the conversion to miles been has been removed /1609.34 in the WHERE clause. That takes the query from 2 to 6 seconds down to about 0.008 seconds.
##

**Comment by mfussenegger** [comment]
I think in the first case our query-rewrite doesn't detect that it can be optimized and utilize the Lucene index. This then results in something that is similar to a tablescan in a RDBMS.

In the second case the detection works, that's why it is a loter faster.

**Comment by denisbetsi** [comment]
That makes sense, though I don't know of an easy way to look up execution plan for either one of those things to see whats happening. But until this is addressed, it's probably a great Gotcha to note for people running into strange performance when running queries. 

Unless you can fix it and there's no gotchas to worry about :)

**Comment by mfussenegger** [comment]
Yep currently there isn't a way to look up the execution plan.

The `EXPLAIN` itself is already implemented in master - so that's going to be part of 0.55.
But unfortunately that won't be enough to detect such query issues, so we'll add something like `EXPLAIN ANALYZE` to our backlog.

**Comment by mfussenegger** [comment]
We've added `EXPLAIN ANALYZE` support in master and it will be part of the next feature release (`3.1`) this should help users to gain more insights into which parts of a query are slow.
