### ISSUE TITLE
Float Min/Max Value error

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#3449]
See: https://github.com/crate/crate-jdbc/issues/106

Attempt to insert a record with Float.MaxValue or MinValue yield an error while using Java client on Crate 54.7

```
[info] Cause: io.crate.action.sql.SQLActionException: float value out of range: -3.4028235E38 
[info] at io.crate.action.sql.TransportBaseSQLAction.buildSQLActionException(TransportBaseSQLAction.java:403) 
[info] at io.crate.action.sql.TransportBaseSQLAction$2.onFailure(TransportBaseSQLAction.java:270) 
[info] at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)

```

**Comment by kovrus** [comment]
hi @denisbetsi, 
I could not reproduce the reported issue. I have used the latest crate JDBC driver (1.11) which uses crate client version 0.54.4 and tried to insert max and min float values into crate (0.54.7). 

With JDBC driver:
```java
...
connection.createStatement().execute("create table foo (number1 float, number2 float)");
PreparedStatement stmt = connection.prepareStatement("INSERT INTO foo (number1, number2) VALUES (?, ?)");
stmt.setFloat(1, Float.MAX_VALUE);
stmt.setFloat(2, Float.MIN_VALUE);
stmt.executeQuery();
...
```

and using crate client directly:
```java
CrateClient client  = new CrateClient(...);
client.sql("create table test (number1 float, number2 float)").actionGet();
client.sql(new SQLRequest("insert into test (number1, number2) values (?, ?)", new Object[]{Float.MIN_VALUE, Float.MAX_VALUE})).actionGet();
```
Both ways of inserting max and min float values are working.

Could you please provide more detailed information so I can try to reproduce and fix the issue.
It would be nice to know about the version of the used crate JDBC driver. Also could you please provide the schema and steps you take to perform inserts.

**Comment by joemoe** [comment]
hi @denisbetsi, can you please provide is the information.
thanks.
johannes

**Comment by denisbetsi** [comment]
Hey Johannes, I am in a middle of a launch. There was a tool for Scala to connect the d.b. tables and make easy access to them. It was failing using that tool. I forgot which one it was, however the fellow who created a git hub issue as well on this subject. Sorry. I am busy for at least a month, I'd have to find the tools and attempt to build it again and right now I have no time. But I am certain you have a copy of this issue and someone is dealing with it or already delt with it.

**Comment by joemoe** [comment]
hi @denisbetsi, i'm not a 100 % sure what you mean. :)
good luck for your launch. whenever you have time to test things again and are able to reproduce the issue, feel free to reopen the issue again. i just want to make sure we keep our issue list clean.
