### ISSUE TITLE
Data path not being interpreted

### ISSUE THREAD

**Issue by VictorCano** [crate/crate#3464]
Hi,

We've been using crate for some time and currently have a couple billion of documents stored in it. Our nodes are configured to use multiple storages, mounted in /data/ dir as /data/data1 and /data/data2.

On the last update (0.54.8) when we're passing the -Des.path.data parameter to the Docker container it is not being interpreted:
```
docker run -d \
    -p 4200:4200 \
    -p 4300:4300 \
    --name=crate-server \
    --volume /data:/data \
    --env CRATE_HEAP_SIZE=20g \
    --log-opt max-size=50m \
    crate:$CRATE_VERSION \
    crate -Des.path.data="/data/data1,/data/data2"
...
```
Instead of reading the files from /data/data1 and /data/data2, it is creating a folder in /data (/data/data) as if I was running crate on a new server with no data on it, or without specifying the data paths. This happened in multiple nodes.

Rolling back to 54.7 has fixed the issue.

Thanks for the great work guys!

**Comment by joemoe** [comment]
hi @VictorCano, thanks. we'll have a look at it and fix it.

**Comment by chaudum** [comment]
hi @VictorCano 
the issue has been fixed (https://github.com/crate/crate/commit/1f9e67a3e16101b6ef10e5ab7992bfa3eca1ea90) and will be available with the next `0.54.x` release.

**Comment by VictorCano** [comment]
Thanks guys!!

**Comment by joemoe** [comment]
hi @VictorCano this is in 0.54.9.
