### ISSUE TITLE
Logstast JDBC Output plugin to Crate for Importing Data

### ISSUE THREAD

**Issue by preet20** [crate/crate#3483]
I would like to import many small tables from Oracle to crate and also keep the data in sync.The only option currently is to create json file and use the copy from to insert the data into crate.
One of the option is to use logstash and input data from Oracle and output to Crate.
With Elasticsearch and other DB it works but not with Crate
Below link for logstash jdbc output plugin
https://github.com/theangryangel/logstash-output-jdbc

Is it possible to include Crate also so one can easily output the data to Crate from multiple input sources

Thanks
Preet

**Comment by joemoe** [comment]
hi @preet20, thanks for using crate. can you tell us where this is failing?

**Comment by kovrus** [comment]
hi @preet20, have you set any additional parameters in logstash conf. It would be necessary to set ```driver_auto_commit``` to false.

**Comment by jodok** [comment]
@pree20, note that we're currently also working on a streamsets connection - that might be an option

**Comment by githubmui** [comment]
Hi,
it would be great to have a Logstash output plugin to Crate!

From my point of view the current Elasticsearch output plugin would be the best blueprint for it.
This plugin uses the bulk API of Elasticsearch and supports all the necessary retry policies for a reliable data transport from Logstash to Elasticsearch.
(e.g. retries forever if Elasticsearch is down or too busy).

Crate supports also a similar bulk api and has got the same retry policy needs. Therefore it should be possible to adapt the existing ES plugin?
Additionally there exists already a ruby driver for Crate.

**Comment by jodok** [comment]
@githubmui are you willing to work on that? we'd love to sponsor it!

**Comment by joemoe** [comment]
i will close this issue now. if you got any feedback for us @preet20 feel free to open it again.

@githubmui, @preet20 we got another issue concerning logstash integration: https://github.com/crate/crate/issues/3371
