### ISSUE TITLE
Order by bug

### ISSUE THREAD

**Issue by denisbetsi** [crate/crate#3529]
When issuing an order by in DESC order, item which has that column missing gets listed on the top

Example:
`select timestamp['added'] from posts where userid in ('5QeGZtqk3e0yYr'') order by timestamp['added'] desc limit 3;`

Results:
```
timestamp['added']
NULL
1463050779355
1463039553257
```

That null shouldn't qualify for a sort when column in dynamic table doesn't even exist.

**Comment by dobe** [comment]
hi @denisbetsi 

this is by intent, since nulls are by default considered larger than other values, use nulls last or filter out nulls in the query depending on what you need.

see also https://crate.io/docs/reference/sql/reference/select.html#order-by-clause
