### ISSUE TITLE
Introduction of UNION? 

### ISSUE THREAD

**Issue by githubmui** [crate/crate#3592]
Hi,
in the Elasticsearch domain it's a powerful feature to do a select over multiple types (~tables). 

The same usecase in the relational Crate domain is to have multiple tables called "logtable1"  to  "logtable9". (Let's say all tables have the same fields "message" and "timestamp"). So it would be great to have a syntax in Crate like 

"  select timestamp, message from logtable\*  "

Another approach for that (I guess the better one) would be an UNION pattern:

"  select timestamp, message from logtable1
   UNION
   select timestamp, message from logtable2
   UNION
   ...
   UNION
   select timestamp, message from logtable9   "

Cheers.
##

**Comment by joemoe** [comment]
hi @githubmui, we have this feature on our backlog and it is quite high prioritized, so the chances that this may be in crate in the future might be also quite high. but still we can't promise anything. :)
i'll keep you posted.

**Comment by matriv** [comment]
@githubmui `UNION ALL` has been implemented, merged to master: https://github.com/crate/crate/pull/6592 and will be available with the next minor release. Performance optimizations are soon to follow.
