### ISSUE TITLE
ANY operator with Arrays of type object.

### ISSUE THREAD

**Issue by mamod** [crate/crate#3653]
[documents](https://crate.io/docs/reference/sql/queries.html) says that ``ANY`` operator can't be used with ``Arrays of type object`` but doing a test, it seems supported to me, at least with crate version ``0.54.8``

here is a sample table used
````js
create table test (
	id String,
	projects array(object(dynamic)) /* array of type object */
) with (number_of_replicas = '0-all');
````

data sample

````js
insert into test (id, projects) values(
  'id', 
  [
    {id = 'project1_id', name = 'project 1'}, 
    {id = 'project2_id', name = 'project 2'}
  ]
), (
  'id2', 
  [
    {id = 'project3_id', name = 'project 3'}, 
    {id = 'project4_id', name = 'project 4'}
  ]
);
````
Now using ``ANY`` operator in a query against projects Array which is of type object, it gives perfect result :)

````js
select * from test where 'project4_id' = ANY(projects['id']) limit 100;

// returns
id   |  projects
----------------------------------------------------------------
id2  |  [{"name":"project 3","id":"project3_id"},{"name":"project 4","id":"project4_id"}]
````
I'm not sure if this is not the expected behavior, documentation error or if I'm missing something !!

Thanks

**Comment by mfussenegger** [comment]
The documentation is correct and this is expected behaviour. Although I guess it is a bit confusing and could be clarified a bit in the documentation

You're accessing `projects['id']` which in that context becomes a string array:

```
cr> select projects['id'] from test;
+--------------------------------+
| projects['id']                 |
+--------------------------------+
| ["project3_id", "project4_id"] |
| ["project1_id", "project2_id"] |
+--------------------------------+
```

That's why ANY works.  The thing that doesn't work is the following:

```
cr> select * from test where {id = 'project1_id', name = 'project 1'} = ANY(projects) limit 10;
SQLActionException[ANY on object arrays is not supported]
```

**Comment by mamod** [comment]
@mfussenegger thank you very much, that's clear enough. I've never thought any would use objects in WHERE clause to test against arrays directly, I also learned that we can select object properties within arrays too, which is another great feature of crate that I'm not sure if it's documented.
