### ISSUE TITLE
jdbc error Crate 55.0

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate#3655]
After fixing the classpath in the crate.bat fil to reflect dir structure in 55.0 it runs wihtout errors until I start a jdbc connection. In this case with Squirrel. Squirrel doesnt succeed in establishing a connection with 55.0 as it does with version 54.9. Attached is the errorlogs from Crate and Squirrel.

Single node
Crate 55.0
Windows 7 Pro sp1
jdk 1.8.0_74
crate jdbc driver 1.12.2

[squirrel_log_cratev550.txt](https://github.com/crate/crate/files/321976/squirrel_log_cratev550.txt)
[cratev550_log.txt](https://github.com/crate/crate/files/321977/cratev550_log.txt)
[crate.yml.txt](https://github.com/crate/crate/files/321985/crate.yml.txt)
[crate.bat.txt](https://github.com/crate/crate/files/321979/crate.bat.txt)

**Comment by chaudum** [comment]
hi @joalmjoalm 
the JDBC client `1.12.2` is using Crate version `0.54.9` and therefore not compatible with Crate server version `0.55.x`
there is no JBDC release yet that uses the `0.55.0` version, we only have JDBC for stable releases.
you would need to build the JDBC jar from source (first change the client version [here](https://github.com/crate/crate-jdbc/blob/master/build.gradle#L14)).
