### ISSUE TITLE
Proposal to combine efforts on an Elasticsearch SRV discovery plugin

### ISSUE THREAD

**Issue by chrismwendt** [crate/crate#3670]
I noticed that a DNS discovery plugin for Elasticsearch has been implemented in this repo, and since I have been working on the same thing as a standalone plugin, I'm wondering if it would make sense to combine efforts 😃 
- Crate: https://github.com/crate/crate/tree/d187eec372664459f86cbacb91e28de89ac166c9/dns-discovery/src/main/java/io/crate
- Standalone: https://github.com/github/elasticsearch-srv-discovery

Since Crate's version supports Elasticsearch 2 and github/elasticsearch-srv-discovery doesn't [yet](https://github.com/github/elasticsearch-srv-discovery/pull/22), perhaps Crate's version could be factored out into a standalone plugin and github/elasticsearch-srv-discovery could be deprecated.

Let me know your thoughts!

cc @adrpar 
##

**Comment by mfussenegger** [comment]
Personally I think that would make a lot of sense.
I could even imagine keeping elasticsearch-srv-discovery and us contributing to it & bundling it into Crate.

I'll talk to the rest of the team and see what they've to say about it.

**Comment by mfussenegger** [comment]
I'm closing this for now, we've no immediate plans to do something here. As it is it's working for us and low maintenance effort. 
If somebody would extract our code and make it a proper plugin we would probably consider integrating it and help out in keeping it up to date. But as things are we've no real motivation to do something here as our resources are focused on other things.
