### ISSUE TITLE
jdbc error on crate_0.54.11

### ISSUE THREAD

**Issue by jaykelin** [crate/crate#3749]
i would like to import some tables from hive to crate. use _sqoop export_ command. but it is not work.
**my env:**
centos/crate 0.54.11/crate jdbc 1.12.3/sqoop 1.4.5
**my cluster config:**
>      cluster.name: crate_hd
>      node.name: "hd25"
>      gateway.expected_nodes: 3
>      gateway.recover_after_nodes: 2
>      discovery.zen.minimum_master_nodes: 2
>      discovery.zen.ping:
>        multicast.enabled: false
>        unicast.hosts:
>          - hd24:4300
>          - hd25:4300
>          - hd26:4300

get an error info about that

> Caused by: io.crate.shade.org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

**Comment by chaudum** [comment]
hi @kjkhi 
how does your connection string look like?
do you also have server logs from the nodes the jdbc driver tries to connect to?
can you connnect to the cluster with plain jdbc (without sqoop)?

**Comment by kjkhi** [comment]
@chaudum thanks for you attention
my connection string like : jdbc:crate://my_server_ip:4300
i also try to connect crate with SQuirreL SQL, follow skips on this page :https://crate.io/docs/tools/squirrel/
it is work.（diff env，this time，SQuirreL client and crate server both running on my windows pc)

**Comment by mikethebeer** [comment]
@kjkhi have you configured the windows firewall correctly to allow i/o access to tcp `4300` and http `4200` (see https://crate.io/docs/install/local/windows/)

**Comment by kjkhi** [comment]
sqoop test result
**jdbc_client** and **crate_server** both centos 6.3
[sqlline](http://sqlline.sourceforge.net): _!connect jdbc:crate://10.1.80.195:4300 io.crate.client.jdbc.CrateDriver_  --- success!
sqoop: _sqoop list-tables --connect jdbc:crate://10.1.81.195:4300 --driver io.crate.client.jdbc.CrateDriver_  --- Failed 
sqoop cli got en exception：

> Caused by: io.crate.shade.org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

nothing info output on crate server log

**Comment by mikethebeer** [comment]
> sqlline: !connect jdbc:crate://10.1.80.195:4300 io.crate.client.jdbc.CrateDriver --- success!
sqoop: sqoop list-tables --connect jdbc:crate://10.1.81.195:4300 --driver io.crate.client.jdbc.CrateDriver --- Failed 

you have specified 2 different IPs. Is this `10.1.81.195:4300` correct? Shouldn't it be `10.1.80.195:4300`??

**Comment by kjkhi** [comment]
@mikethebeer i'm sorry,it's my fault.
10.1.80.195:4300 is working,both with plain jdbc and sqoop tools
