### ISSUE TITLE
Crate 0.55.2, Cannot allocate memory

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#3788]
I try to deploy a Crate cluster with 3 nodes upon Crate 0.55.2, yet when I load data using **COPY FROM**, error come out as follows:

> Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000dd990000, 30641946624, 0) failed; error='Cannot allocate memory' (errno=12)
> \#
> \# There is insufficient memory for the Java Runtime Environment to continue.
> \# Native memory allocation (mmap) failed to map 30641946624 bytes for committing reserved memory.
> \# An error report file with more information is saved as:
> \# /data1/upload/hadoop/hs_err_pid15016.log

I describe some details of softeware and configuration:

> Crate version: 0.55.2
> JDK version: "1.8.0_92"
> OS version: CentOS release 6.5 (Final)
> Machine memory: 64314M
> Crate config: **CRATE_HEAP_SIZE=30G**

See attachment for details of error log, thanks.

[hs_err_pid15016.txt](https://github.com/crate/crate/files/358790/hs_err_pid15016.txt)

Sincerely,
Robin

**Comment by celaus** [comment]
Hi! Since if you want, you can also post the answers to my questions here instead of the email. 

Cheers, Claus

**Comment by dbarobin** [comment]
Hi Claus,

1.This is table structure.

``` sql
CREATE TABLE dm_list_play_d(
etldate string,
plat string,
sty string,
source string,
singername string INDEX USING plain,
songname string INDEX USING plain,
singername_org string INDEX OFF,
songname_org string INDEX OFF,
filename string INDEX USING plain,
filename_org string INDEX OFF,
song_type string,
play_cnt integer,
complete_play_cnt integer
) PARTITIONED BY(etldate);
```

2.Crate is the only major program to use memory on my machine, the usage of memory is %4 on each machine, and the Crate 0.55.2 installed freshly.

3.Disk info

``` bash
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        20G  3.6G   16G  20% /
tmpfs            32G     0   32G   0% /dev/shm
/dev/sda1      1008M   60M  897M   7% /boot
/dev/sda4       1.1T  461G  555G  46% /data1

cat /proc/scsi/scsi
Attached devices:
Host: scsi0 Channel: 02 Id: 00 Lun: 00
  Vendor: DELL     Model: PERC H730P Mini  Rev: 4.25
  Type:   Direct-Access                    ANSI  SCSI revision: 05

dmesg | grep sda
sd 0:2:0:0: [sda] 2339373056 512-byte logical blocks: (1.19 TB/1.08 TiB)
sd 0:2:0:0: [sda] Write Protect is off
sd 0:2:0:0: [sda] Mode Sense: 1f 00 00 08
sd 0:2:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
 sda: sda1 sda2 sda3 sda4
sd 0:2:0:0: [sda] Attached SCSI disk
EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts:
dracut: Mounted root filesystem /dev/sda2
EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts:
EXT4-fs (sda4): mounted filesystem with ordered data mode. Opts:
Adding 8388600k swap on /dev/sda3.  Priority:-1 extents:1 across:8388600k
```

4.I import data via COPY FROM, each JSON file is about 5G, and 61 files total.

5.When I import data, this error occured immediately, there is no enough time to observe the status of memory, CPU and disk.

Thanks.

Sincerely,
Robin

**Comment by celaus** [comment]
Does Crate come up at all, i.e. is there any log output?

**Comment by dbarobin** [comment]
Hi Claus,

There is no error log, but there is some **WARN** log as follows:

> [2016-07-12 16:58:00,400][WARN ][bootstrap] unable to install syscall filter: seccomp unavailable: requires kernel 3.5+ with CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER compiled in

Thanks.

Sincerely,
Robin

**Comment by celaus** [comment]
what's the STDOUT output? journalctl etc?

**Comment by dbarobin** [comment]
STDOUT:

> Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000dd990000, 30641946624, 0) failed; error='Cannot allocate memory' (errno=12)
> \#
> \# There is insufficient memory for the Java Runtime Environment to continue.
> \# Native memory allocation (mmap) failed to map 30641946624 bytes for committing reserved > memory.
> \# An error report file with more information is saved as:
> \# /data1/upload/hadoop/hs_err_pid15016.log

See attachment for details of error log, thanks.

[hs_err_pid15016.txt](https://github.com/crate/crate/files/358790/hs_err_pid15016.txt)

**Comment by celaus** [comment]
Hmm this seems to be a JVM issue, which seems to be unable to start with the assigned heap size. can you try lower heap sizes (1g is default)

**Comment by dbarobin** [comment]
But I set **CRATE_HEAP_SIZE=32G** in Crate 0.54.11, there is no problem.

**Comment by dbarobin** [comment]
I try to set **CRATE_HEAP_SIZE=24G** and restart Crate 0.55.2, but there still have this problem.

**Comment by dbarobin** [comment]
Sorry, typo. I use **/data1/crate-0.55.2/bin/crate** instead of **/data1/crate-0.55.2/bin/crash** to load data, such a ridiculous mistake. Thanks Claus.

**Comment by celaus** [comment]
Hmm did earlier Crate versions also have this problem? Also, are you running in a virtualized environment like OpenVZ?
