### ISSUE TITLE
Load data raise SQLActionException[NotXContentException]

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#3801]
When I load data via **COPY FROM** on Crate 0.55.2, exception raised as follows:

> SQLActionException[NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]

What means of this exception? And How can I avoid this?

Thanks.

**Comment by chaudum** [comment]
Can you please provide a full stacktrace of the exception (if you're using crash start it with `-v` option).

Your `JSON` source is probably malformed and therefore its content type cannot be detected.
Can you provide both the `COPY FROM` statement and the start of your source?

**Comment by joemoe** [comment]
hi @dbarobin, can you provide us the full stacktrace or did this issue resolve itself?

**Comment by chaudum** [comment]
hi @dbarobin did you resolve your issue already? if yes, feel free to close this issue!

**Comment by dbarobin** [comment]
Thanks!
