### ISSUE TITLE
hunspell dictionaries not found after v 0.55.2

### ISSUE THREAD

**Issue by ghotikun** [crate/crate#3816]
In version 0.54.11 I was able to use the hunspell Token Filter by putting my en_US dictionary files in <path.conf>/hunspell/en_US per the documentation. Since version 0.55.2 I have not been able to do so. I get `ElasticsearchException[Could` not find hunspell dictionary [en_US]]`.

This is likely related to the upgrade to Elasticsearch 2.3. Elasticsearch may be handling the default hunspell directory differently. 

I am running crate in docker.

**Comment by joemoe** [comment]
hi @ghotikun, thanks for reporting. we will have a look into this.

**Comment by aelesbao** [comment]
@ghotikun could you please provide us the table schema and the analyzer settings that you are using?

**Comment by aelesbao** [comment]
@ghotikun we tested on tag 0.55.2 and couldn't reproduce the error. Could you check if on your setup the dictionaries are located in `config/hunspell`? Since Elasticsearch 2.0, this is the [only supported path](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_setting_changes.html#_hunspell_dictionary_configuration).

**Comment by ghotikun** [comment]
The en_US directory with corresponding .aff and .dic files are in /crate/config/hunspell
/crate/config is where crate.yml resides.

I also created /config/hunspell and put the en_US directory there as a test. I'm still getting the same error.

Table schema:
`CREATE TABLE hunspell_test (
  recordId STRING PRIMARY KEY,
  q2_2 STRING INDEX USING plain,
  INDEX q2_2_hunspell USING fulltext(q2_2) with (analyzer = 'hunspell_analyzer')
) with (column_policy='strict');`

Analyzer:
`create ANALYZER hunspell_analyzer (
	TOKENIZER standard,
	TOKEN_FILTERS (
		lowercase,
		my_hunspell WITH (
			type = 'hunspell',
			locale = 'en_US'
		)
	)
);`

**Comment by aelesbao** [comment]
@ghotikun how are you copying the files to the container? I started it with the following cmd, run your example and it works:

```
docker run -p 4200:4200 --volume $(pwd)/hunspell:/crate/config/hunspell crate
```

with the local folder `hunspell` containing:
```
hunspell
├── en_US
    ├── en_US.aff
    └── en_US.dic
```

**Comment by ghotikun** [comment]
I was using docker cp:
`docker cp hunspell c0:/crate/config/hunspell`

I started the node mounting the volume as you suggested and it worked. It appears that mounting the volume makes the owner of the files crate where as copying them makes the owner root. If I manually change the owner of the hunspell directory to crate:50 in the container, it works.

Thanks for your help!
