### ISSUE TITLE
Caused by: NoNodeAvailableException[None of the configured nodes are available]

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#3848]
When I use Crate via **JDBC** to execute query, it raise **exception** as follows:

> org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connect to '10.1.1.139:4300' failed
> Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.1.1.139}{10.1.1.139:4300}]]

Before troubleshooting this problem, it's necessary to make clear the **version** of related software.

* OS: CentOS release 6.5 (Final)
* Crate: 0.55.2
* crate-jdbc-standalone: 1.13.0
* JDK: 1.7.0_79

Finally, the log of Crate record nothing about this exception, and this exception caused during the query above 10%.

Thanks.

**Comment by mfussenegger** [comment]
The exception indices that the node is not available. Do you have network issues or very high load on the cluster?
