### ISSUE TITLE
cluster checks fail

### ISSUE THREAD

**Issue by eshubin** [crate/crate#3851]
I have following cluster checks failed with crate 0.54.9 on 4 nodes:

> CRITICAL The setting 'discovery.zen.minimum_master_nodes' must not be less than half + 1 of eligible master nodes in the cluster. It should be set to (number_master_nodes / 2) + 1
CRITICAL The value of the cluster setting 'gateway.expected_nodes' must be equal to the maximum/expected number of master and data nodes in the cluster.

Although on all nodes I have following values in config:

> discovery.zen.minimum_master_nodes: 3
...
gateway.expected_nodes: 4
gateway.recover_after_nodes: 3

**Comment by mfussenegger** [comment]
What output do you get if you query `select settings['discovery'], settings['gateway'] from sys.cluster` ?

**Comment by eshubin** [comment]
settings['discovery'] -> {"zen":{"minimum_master_nodes":2,"publish_timeout":"30s","ping_timeout":"3s"}}
settings['gateway'] -> {"recover_after_nodes":2,"expected_nodes":3,"recover_after_time":"5m"}

Seems like settings were not taken by cluster. Restart?

**Comment by mfussenegger** [comment]
How did you apply the settings?

 `gateway.expected_nodes` and `gateway.recovery_after_nodes` are no runtime settings. You have to define them in the `crate.yml` or via command line argument.

`discovery.zen.minimum_master_nodes` can be set using the `SET` statement.

**Comment by joemoe** [comment]
@eshubin i'm closing this ticket now. if this still is a problem, don't hesitate to open it again.
