### ISSUE TITLE
Moving Average Aggregation

### ISSUE THREAD

**Issue by mindbits** [crate/crate#3934]
Hello, 

I assume that the Moving Average aggregation is not supported? 

Is there a way to do such a calculation with crate otherwise?
##

**Comment by chaudum** [comment]
hi @mindbits 
Crate does not support *moving average* aggregations.
There are various other ways how to calculate moving average, e.g. using window function or [correlated subqueries](https://en.wikipedia.org/wiki/Correlated_subquery). however these are also not supported yet.
Right now there is no other way than calculating the moving average within your application.

**Comment by mfussenegger** [comment]
Moving averages can be calculated using window functions with CrateDB 4.0.

E.g.:

```
select avg(y) OVER (ORDER BY x) from unnest([1, 2, 3], [10.3, 27.3, 15.2]) as t (x, y);
```
