### ISSUE TITLE
Unexpected TableUnknownException when referencing compound primary key.

### ISSUE THREAD

**Issue by cltompkins** [crate/crate#3966]
After creating a new table that contains a compound primary key and is partitioned, any queries that reference either part of the primary key proceed as expected, but when both parts are used in the WHERE clause, an unexpected exception is thrown.

SQLActionException[TableUnknownException: Table '.partitioned.test.04130' unknown]

Further testing reveals that this occurs only when the partition doesn't exist, hence the unknown partition table, but since the base table is defined, returning an empty set would be ideal, not throwing an exception.

Also, a [SELECT * FROM] query throws the table unknown exception while a [SELECT COUNT(*) FROM] query returns 0 with no table unknown exception.

CLI code provided in attached screenshot.

![screenshot from 2016-08-10 17-18-57](https://cloud.githubusercontent.com/assets/11198696/17571648/1980ff50-5f1f-11e6-8fc1-059bc52577da.png)

**Comment by dobe** [comment]
hi @cltompkins, good catch ... we will asap fix this. thanks for the report!

**Comment by seut** [comment]
@cltompkins this was just fixed by https://github.com/crate/crate/commit/39e7f91e80fff6ac3b1c5947fc2f4ad35b59e7df and will be released with the next hotfix release. again, thanks for reporting!
