### ISSUE TITLE
Upgrade Crate to 0.55.4 raise java.io.FileNotFoundException

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#3992]
Hi, when I upgrade Crate from 0.55.2 to 0.55.4, the Crate start failed with following errors:

``` bash
java.io.FileNotFoundException: /data3/crate-0.55.4/lib/crate-app-0.55.2.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:174)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:171)
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:296)
        at io.crate.bootstrap.CrateF.main(CrateF.java:50)
```

I listed the `crate-0.55.4/lib` directory, there is **crate-app-0.55.4.jar**, no **crate-app-0.55.2.jar**.

Crate 0.55.4 need crate-app-0.55.2.jar? Compile error?

Thanks.

Sincerely,
Robin

**Comment by chaudum** [comment]
can you provide some more information on which system you're running Crate on and how you performed the upgrade.

**Comment by chaudum** [comment]
hi @dbarobin 
do you still have the issue? could you provide some more information about your setup and how you performed the upgrade please, so we can investigate the problem.

thanks,
christian

**Comment by dbarobin** [comment]
I just deploy Crate 0.55.4 and the log records this exception.

**Comment by chaudum** [comment]
@dbarobin does it also happend when you run `bash -c "$(curl try.crate.io)"` ?

**Comment by dbarobin** [comment]
I don't try this because our server is in intranet and can not connect to crate outer server.

**Comment by chaudum** [comment]
but how did you update crate then without access to the internet?
`bash -c "$(curl try.crate.io)"` just downloads the tarball, extracts it and runs `bin/crate` inside the extracted folder

**Comment by dbarobin** [comment]
I just download the offline tarball in my own PC and transfer it to remote IDC server.

**Comment by chaudum** [comment]
I assume, you've only replaced the lib folder.
You have to replace the whole distribution, not only the `$CRATE_HOME/lib` folder!

**Comment by dbarobin** [comment]
I extract it in the new directory. I'll try again.

**Comment by dbarobin** [comment]
I try again and this exception recur.

**Comment by chaudum** [comment]
The file `$CRATE_HOME/bin/crate.in.sh` holds the reference to the `crate-app-<VERSION>.jar`

`cat $CRATE_HOME/bin/crate.in.sh`:
```bash
...
CRATE_CLASSPATH=$CRATE_HOME/lib/crate-app-0.55.2.jar:$CRATE_HOME/lib/*
...
```

**Comment by dbarobin** [comment]
That is to say, it's a bug from compiling?

**Comment by chaudum** [comment]
Download the [crate-0.55.4](https://cdn.crate.io/downloads/releases/crate-0.55.4.tar.gz) tarball, extract it and  look at `crate-0.55.4/bin/crate.in.sh`
You will find the line
`CRATE_CLASSPATH=$CRATE_HOME/lib/crate-app-0.55.4.jar:$CRATE_HOME/lib/*`

Then compare it with the same file on your server.

**Comment by dbarobin** [comment]
Thanks, it's my problem.
