### ISSUE TITLE
feature: search by object field in array of objects

### ISSUE THREAD

**Issue by gmrodrigues** [crate/crate#4001]
Imagine i have the following data structure:
```
{ array_field: [{object_field:1 },{object_field:2}] }
```

I want to search all documents having object_field = 2 without knowing that its in array_field[1]

```
WHERE 2 = ANY(array_field[*]['object_field'])
```

Is this possible?

If not, continue reading...

As a work around I was thinking in an array column called object_fields in which i would store [1,2] and search WHERE 2 = any(object_fields).

```
{
  array_field: [{object_field:1 },{object_field:2}],
  object_fields:[1,2]
 }
```

It would be great if i could have this column generated by a function that from an array of objects, extract value of a property as array. Like in http://stackoverflow.com/questions/19590865/from-an-array-of-objects-extract-value-of-a-property-as-array

```
CREATE TABLE xyz (
...
object_field as my_new_func(object_fields, 'object_field')
...
)
```

Can I implement such function/are you interested?
Do you have any name suggestions for this function?
Is there another way?

Thank you for this great software

**Comment by mikethebeer** [comment]
hi @gmrodrigues,
if I understand your question correct this is already implemented. The `ANY` operator actually does this - it queries for rows where an element of an array is equal to or greater than etc. to some expression.

If you use this simple example you maybe get the point:
```sql
create table x (
       arr array(object as (
          obj object as (
             id int))));
```

`insert into x (arr) values ([{obj={id=1}}, {obj={id=2}}, {obj={id=3}}]);`
`insert into x (arr) values ([{obj={id=4}}, {obj={id=5}}, {obj={id=6}}]);`

if you want to get the row where the field `arr` contains at field `id=2` then do this:
```sql
cr> select * from x where 2 = any(arr['obj']['id']);
+--------------------------------------------------------------+
| arr                                                          |
+--------------------------------------------------------------+
| [{"obj": {"id": 1}}, {"obj": {"id": 2}}, {"obj": {"id": 3}}] |
+--------------------------------------------------------------+
SELECT 1 row in set (0.011 sec)
```

It only returns the row that contains the expression in its array.

**Comment by joemoe** [comment]
@gmrodrigues did the any operator help?

**Comment by gmrodrigues** [comment]
It worked. Thank you for clarifying with this example.

I read the documentation and could not get it until you show me this example.

Thank you again!
