### ISSUE TITLE
Failed get connection with Crate 0.55.2

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#4007]
I load data via [Sqoop](http://sqoop.apache.org), and raise this exception from Crate error log:

> [2016-08-25 15:44:07,608][DEBUG][action.bulk              ] create 1 pending indices in bulk...
> [2016-08-25 15:44:07,623][INFO ][action.admin.indices.create] [crate172] [.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0] creating index, cause [bulk], templates [.partitioned.t_zkp_test_crate5.], shards [10]/[1], mappings [default]
> [2016-08-25 15:44:07,890][INFO ][cluster.routing.allocation] [crate172] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0][9], [.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0][8]] ...]).
> [2016-08-25 15:44:08,154][DEBUG][action.bulk              ] create new coordinator for node Zjy_QolDSzWjVDn6_UpRsw and shard [.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0][1]
[2016-08-25 15:44:08,156][DEBUG][action.bulk              ] create new coordinator for node JIqOyYxfRDeKNu4S_TWi6g and shard [.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0][6]
> [2016-08-25 15:44:09,812][INFO ][cluster.routing.allocation] [crate172] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.partitioned.t_zkp_test_crate5.045j4c1h6omj0dhd60q0][8]] ...]).

The exception of **Sqoop** as follows:

> 16/08/25 15:46:18 INFO client.transport: [crate_client] failed to get node info for {#transport#-1}{10.1.113.172}{10.1.113.172:4300}, disconnecting...
> ReceiveTimeoutTransportException[[][10.1.113.172:4300][cluster:monitor/nodes/liveness] request_id [35] timed out after [5000ms]]
> at io.crate.shade.org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:675)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:744)
> 16/08/25 16:41:37 INFO mapreduce.Job: map 100% reduce 0%
> 16/08/25 16:41:38 INFO mapreduce.Job: Job job_1469759210389_165114 failed with state KILLED due to: Kill job job_1469759210389_165114 received from hadoop (auth:SIMPLE) at 10.1.81.168
> Job received Kill while in RUNNING state.
> 
> 16/08/25 16:41:39 INFO mapreduce.Job: Counters: 8
> Job Counters 
> Killed map tasks=10
> Launched map tasks=10
> Other local map tasks=10
> Total time spent by all maps in occupied slots (ms)=207702858
> Total time spent by all reduces in occupied slots (ms)=0
> Total time spent by all map tasks (ms)=34617143
> Total vcore-seconds taken by all map tasks=34617143
> Total megabyte-seconds taken by all map tasks=106343863296
> 16/08/25 16:41:39 WARN mapreduce.Counters: Group FileSystemCounters is deprecated. Use org.apache.hadoop.mapreduce.FileSystemCounter instead
> 16/08/25 16:41:39 INFO mapreduce.ExportJobBase: Transferred 0 bytes in 3,488.1937 seconds (0 bytes/sec)
> 16/08/25 16:41:39 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
> 16/08/25 16:41:39 INFO mapreduce.ExportJobBase: Exported 0 records.
> 16/08/25 16:41:39 ERROR tool.ExportTool: Error during export: Export job failed!

When raise this exception, the process of Sqoop hang and the log of Crate record nothing. The Sqoop command as follows:

``` bash
sqoop export -D mapred.job.queue.name=root.common \
--batch --num-mappers 10 \
--connect jdbc:crate://xxx.xxx.xxx.xxx:xxxx \
--driver io.crate.client.jdbc.CrateDriver \
--table t_zkp_test_crate5 \
--export-dir /user/hive/warehouse/temp.db/t_zkp_test_crate/dt=2016-07-04 \
--fields-terminated-by '|' \
--null-non-string '' \
--null-string '' \
--input-null-non-string '\\N' \
--input-null-string '\\N' \
--columns 'etldate,plat,play_cnt'
```

The maximum of mappers is **15**, and beyond 15 will raise above exception.

Version of related software:

> Crate: 0.55.2
> OS: CentOS release 6.5 (Final)
> Disk: SSD
> Sqoop: 1.4.5
> JDBC: Crate JDBC Driver 1.13

I try to tune thread pool, don't work. Then I try to tune connection parameters, yet I can't find related parameters. How to avoid this problem?

Thanks.

Sincerely,
Robin

**Comment by jaykelin** [comment]
@dbarobin I have solved this problem,like https://github.com/crate/crate/issues/3984 i try to explain.
Hope useful to you
