### ISSUE TITLE
SUBSTRING_INDEX() function support

### ISSUE THREAD

**Issue by dbarobin** [crate/crate#4028]
MySQL has a string function named **SUBSTRING_INDEX().**

In the official document, there is following explaination:

> SUBSTRING_INDEX()	Return a substring from a string before the specified number of occurrences of the delimiter

Could you please add this feature to Crate.

Thanks!
Sincerely

**Comment by joemoe** [comment]
hi @dbarobin, we added it to our backlog. i'll tell you when i got an update on this.

**Comment by joemoe** [comment]
@dbarobin this could also be an easy pick for a contribution or a plugin (https://crate.io/docs/reference/plugins.html). so if you'd like to give it a try we'd be very happy to help.

**Comment by dbarobin** [comment]
@joemoe Thanks!
