### ISSUE TITLE
v 55.4 custom config in docker-  issue or docs/usability issue

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate#4047]
Potential issue with the custom config feature with docker crate container. I didnt get any success neither with -des config or editing existing crate.yml file within container.

My environment Virtualbox, Ubuntu Server 1604 and Crate docker image 55.4. So Im in a Ubuntu env.

Tried to follow docs to set custom cluster name and node name. This happened. Maybe I misunderstood docs or its a usability issue.

a) crate -Des.cluster.name=testcluster
I used 'docker exec -it -u crate "containername" sh' to get into the container.
tried first as root but then elastic throws an error due to set default security level, changed to log into container as user 'crate' 
I went to dir /crate/bin and tried to run "crate -Des.cluster.name=testcluster"
Then a second crate db instance was launched inside the container at published port 4201.
I just wanted to change clustername, not launch a new crate.

b) Tried to edit the crate.yml directly in the container.  Its content was just three diff path infos compared to host-installations crate.ymls. I added inside the container 'cluster.name = "testcluster"'. Restarted the container but it closed down immediately.

My final solution which worked fine was to use the crate.yml file from crate host-installation which includes all options etc. Made changes inside this one and copied this file to the crate.yml inside the container. Restarted and it worked just ok.

Read that support of manual editing of crate.yml not supported after v55 but I either didnt understood docs or its a issue in the container implementation of custom config.

**Comment by chaudum** [comment]
There is no need to change into the container and modify existing files. NEVER do this!

The are 2 ways of specifying Crate settings:

1) using the `-Des.` command line arguments
```console
$ docker run crate:0.55.4 crate -Des.cluster.name=my_cluster_name -Des.node.name=node_1 ...
```

2) mounting the `crate.yml` configuration file as described here: https://github.com/crate/docker-crate#use-custom-crate-configuration

```console
$ docker run --volume /custom/path/to/crate.yml:/crate/config/crate.yml crate:0.55.4 crate
```

Usage instructions for the Crate docker container can be found on [DockerHub](https://hub.docker.com/_/crate/).

**Comment by joalmjoalm** [comment]
ok, thanks for answer.
