### ISSUE TITLE
Crash in jvm

### ISSUE THREAD

**Issue by eshubin** [crate/crate#4049]
A node in crate cluster crashed with 
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: # A fatal error has been detected by the Java Runtime Environment:
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: #  SIGSEGV (0xb) at pc=0x00007fdd76e7b759, pid=31901, tid=0x00007fdcfa16e700
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: # JRE version: OpenJDK Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
Sep 10 09:33:36 node189 crate: # Java VM: OpenJDK 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
Sep 10 09:33:36 node189 crate: # Problematic frame:
Sep 10 09:33:36 node189 crate: # J 19340 C2 org.apache.lucene.index.DocumentsWriter.doFlush(Lorg/apache/lucene/index/DocumentsWriterPerThread;)Z (515 bytes) @ 0x00007fdd76e7b759 [0x00007fdd76e7b1c0+0x599]
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: # An error report file with more information is saved as:
Sep 10 09:33:36 node189 crate: # /opt/crate/hs_err_pid31901.log
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:36 node189 crate: # If you would like to submit a bug report, please visit:
Sep 10 09:33:36 node189 crate: #   http://bugreport.java.com/bugreport/crash.jsp
Sep 10 09:33:36 node189 crate: #
Sep 10 09:33:37 node189 systemd: crate.service: main process exited, code=killed, status=6/ABRT
Sep 10 09:33:37 node189 systemd: Unit crate.service entered failed state.
Sep 10 09:33:37 node189 systemd: crate.service failed.

Is that a known issue or wrong jvm version?

**Comment by mikethebeer** [comment]
@eshubin Are you sure you set the ulimits correctly (see https://github.com/crate/distribute/blob/master/aptbuild/crate/SOURCES/debian/crate.init#L58-L59)? Do you use our `.rpm` or `.deb` package or have you started Crate via the Tarball?

**Comment by eshubin** [comment]
[eugene@node148 ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127203
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

I think in logs there is an issue with ulimit for coredump.
crate version is 0.54.9 installed from rpm.

Logs before the crash are pretty old. But can provide you any of them.

**Comment by mikethebeer** [comment]
what does `/opt/crate/hs_err_pid31901.log` shows? `ulimit -c` is not the reason for the crash.

**Comment by eshubin** [comment]
Compressed log file is attached.
[hs_err_pid31901.log.zip](https://github.com/crate/crate/files/469179/hs_err_pid31901.log.zip)

I understand that limit on coredump did not allow to create a full coredump.

**Comment by mikethebeer** [comment]
Do you run Crate on an virtualization environment like OpenVZ? It can be related to this issue https://github.com/crate/crate/issues/2461
Maybe try to disable `sigar` - remove it from the `libs` folder.

**Comment by eshubin** [comment]
Cluster is working on hardware servers. I found only sigar files, which go with crate distribution /opt/crate/lib/sigar. Is there an instruction on disabling it, or removal is disabling?

**Comment by mikethebeer** [comment]
@eshubin just remove the folder `libs/sigar`

**Comment by joemoe** [comment]
@eshubin did this work for you?
