### ISSUE TITLE
SQLActionException[NotXContentException

### ISSUE THREAD

**Issue by AlpOzSF** [crate/crate#4089]
I'm trying to migrate some data from an Access DB, so I've converted data sets to json files, encoded UTF-8.
then created a table on Crate.IO which has the same structure. following is the table I've created.
create table LU_CATEGORY (
  CATEGORY_ID INT primary key,
  CATEGORY_DESC STRING,
  CATEGORY_DESC_DE STRING,
  CATEGORY_DESC_FR STRING,
  CATEGORY_DESC_ES STRING,
  CATEGORY_DESC_IT STRING,
  CATEGORY_DESC_PO STRING,
  CATEGORY_DESC_JA STRING,
  CATEGORY_DESC_SCH STRING,
  CATEGORY_DESC_KO STRING);

so when I try to execute the `COPY LU_CATEGORY FROM '/home/alp/Downloads/LU_CATEGORY.json'; `,  following error is raised
**SQLActionException[NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]**

Crate version is 0.55.4

-adding the sample json file (named LU_CATEGORY) here as a txt file since couldn't upload as .zip or .json file.

[LU_CATEGORY.txt](https://github.com/crate/crate/files/482880/LU_CATEGORY.txt)

**Comment by AlpOzSF** [comment]
it seems my json file(s) format is not proper for the Crate.
I'm changing the format and will try again

**Comment by chaudum** [comment]
@AlpOzSF right, Crate requires a json string per line, e.g.

```json
{"col_a": 1, "col_b": "foo"}
{"col_a": 2, "col_b": "bar"}
```

**Comment by AlpOzSF** [comment]
confirmed that
