### ISSUE TITLE
join does not allow matching from both relations

### ISSUE THREAD

**Issue by anton-burtsev** [crate/crate#4091]
table:
`create table test(id long primary key, num long, txt string index using fulltext, jsn object);`

query:
`select t2.id from test as t1 inner join test as t2 on t1.num = t2.num where match(t1.txt, '1111') and match(t2.txt, '2222');`

error:
`SQLActionException[UnhandledServerException: java.lang.IllegalArgumentException: Cannot find implementation for function match({"txt"=NULL}, '1111', 'best_fields', {})]`

**Comment by celaus** [comment]
Just adding information from our conversation earlier: 0.55.5 still has the same issue

**Comment by matriv** [comment]
Hello @anton-burtsev!

The issue has been fixed and will be available in releases: **0.55.6** and **0.56.1**
Thanks for finding the issue and reporting.
