### ISSUE TITLE
Documentation misleading on IMPORT data

### ISSUE THREAD

**Issue by nibin** [crate/crate#4152]
Hi,

I was trying to understand how the data can be imported to crate. I used 'crash' to connect to a remote crate node. Then I populated a json file in my local machine (where crash is running). I tried to do COPY FROM providing the file:// URL and the data was never getting imported.

I had to re-read the documentation 5 times to catch on the point that the file to be imported should be locally present to the crate node to import. Can the documentation be made cleared regarding this aspect.

Not everyone would be running crate and crash on the same instance.

-Nibin
##

**Comment by chaudum** [comment]
hi @nibin 
thanks for the feedback! we'll try to improve the documentation about `COPY FROM`.
also, we're happy to take contributions 🤗
https://github.com/crate/crate/blob/master/blackbox/docs/sql/dml.txt#L378 would be the starting point

**Comment by celaus** [comment]
Hi, @nibin thanks for the feedback - we have improved our docs in that area, but since it is quite complex to explain we hope to have written something that is easier to understand :)

https://crate.io/docs/reference/en/latest/sql/reference/copy_from.html#file

Cheers!
