### ISSUE TITLE
Support strings for object inserts

### ISSUE THREAD

**Issue by herenow** [crate/crate#4165]
Hi,

I maintain a Go package for crate, but we are having issues complying with Go's `database/sql` interface.

Open issue: https://github.com/herenow/go-crate/issues/10

I know Crate only supports object inserts via prepared statements w/ the rest api, but I'm wondering why.

But I would like to make a case for supporting object inserts via raw sql :)

I'm trying to add support for the following in Go.

```
type Metadata struct {
    Count int `json:"count"`
}

stmt, _ := db.Prepare("insert into test (metadata) values (?)")
_, err := db.Exec(&Metadata{Count: 1})
```

The problem is Go's `database/sql` doesn't support structs, it mostly only supports primitives. So the metadata object never arrives to my crate driver.

IMO crate should accept something like:

`insert into test (metadata) values ("{count: 1}")`

I believe there are a number of benefits on supporting all operations via raw sql, such as being able to dump/restore our database's via sql.

Is this something worth supporting? Is it somewhere on the roadmap :)?
##

**Comment by mfussenegger** [comment]
Crate does have object literals: https://crate.io/docs/reference/sql/data_types.html?highlight=object#object-literals

So your statement needs just a minor change in order to work:

```insert into test (metadata) values ({count=1})```

**Comment by mfussenegger** [comment]
Closing this as we have support for this
