### ISSUE TITLE
TRY_CAST throws an exception under some invalid coordinates geo_point strings

### ISSUE THREAD

**Issue by boriel** [crate/crate#4189]
According to the [TRY_CAST documentation](https://crate.io/docs/reference/sql/data_types.html#type-conversion), it should return NULL on invalid conversions. However, under some circumstances, it throws an exception when casting invalid strings into geo_points:

`cr> SELECT TRY_CAST('POINT(0 182)' as geo_point) from mytable limit 1;
SQLActionException[InvalidShapeException: Bad Y value 182.0 is not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)]`

The function behaves correctly if the string is malformed, or uses NULL values in any of the POINT( ) arguments, though.

**Comment by joemoe** [comment]
hi @boriel, this seems to be a bug. we'll check that.

**Comment by kovrus** [comment]
@boriel the issue has been fixed. It will be released with 0.55.5 and 0.56.1
