### ISSUE TITLE
percolator doesn't work

### ISSUE THREAD

**Issue by yiguolei** [crate/crate#4217]
I down load the latest CRATE binary and tested the percolator api but it does not work. the test case is here https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-percolate.html.
##

**Comment by yiguolei** [comment]
Could anybody answer my question?

**Comment by mfussenegger** [comment]
Could you clarify what you mean with "does not work" ?

**Comment by celaus** [comment]
Hey @yiguolei - what was the response you got? (I also assume you have activated and used the es.api property)

**Comment by mfussenegger** [comment]
Closing this as there is no feedback
