### ISSUE TITLE
Implement the math function: power(a numeric, b numeric) 

### ISSUE THREAD

**Issue by andreidan** [crate/crate#4219]
Implement the power math function that given 2 parameters a and b returns a raised to the power b (as described here https://www.postgresql.org/docs/9.1/static/functions-math.html)

**Comment by chaudum** [comment]
hi @andreidan we'll put that feature on our backlog.
However, if you're interested in implementing the power scalar function, we're happy to help!

**Comment by celaus** [comment]
@andreidan https://github.com/crate/crate-example-plugin <- this should also help ;)

**Comment by dobe** [comment]
hi @andreidan you might want to look at https://github.com/crate/crate/tree/master/sql/src/main/java/io/crate/operation/scalar/arithmetic for examples

**Comment by mfussenegger** [comment]
This is now in master (See https://github.com/crate/crate/pull/4230)
