### ISSUE TITLE
Update docs with Crate Java client deprecation

### ISSUE THREAD

**Issue by varnerac** [crate/crate#4250]
Recent commits appear to deprecate the Crate Java client in favor of JDBC. The Crate.io website does not reflect this.
##

**Comment by joemoe** [comment]
hi @varnerac, yes this is true and we will communicate this, but as you said at the moment we are "just" working on it.

**Comment by celaus** [comment]
Hi @varnerac - we actually did this some time ago now :) Thanks for reporting! 

https://crate.io/docs/clients/java/
