### ISSUE TITLE
where IN / EXISTS (subquery) support

### ISSUE THREAD

**Issue by jannishuebl** [crate/crate#4304]
Hello, 

when i want to use the IN operator with a subquery I get an Error:

SQLActionException[ClassCastException: io.crate.sql.tree.SubqueryExpression cannot be cast to io.crate.sql.tree.InListExpression]

SELECT \* FROM "table1" WHERE "table1"."table2_id" IN (SELECT "table2"."id" FROM "table2" WHERE "table2"."id" = 3)

Is is kind of query not supported? 

I am running the 0.56.2 docker image of crate. 
##

**Comment by celaus** [comment]
Hi, No this is not yet supported, but we are working on it. Currently `IN` can only be used with lists.

Cheers, Claus

**Comment by jannishuebl** [comment]
Thanks for the information. Sounds great that you are planning to support it. Can you give a  rough estimation how long it will take? Until then I will find a workaround. :)

Cheers, Jannis

**Comment by mfussenegger** [comment]
Good news. This will be part of 2.2 (which is already available as testing release)
So I'm closing this
