### ISSUE TITLE
Getting error while trying to fetch it via curl

### ISSUE THREAD

**Issue by MSaifAsif** [crate/crate#4325]
``` bash
$ curl -O https://aur4.archlinux.org/cgit/aur.git/snapshot/crate.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
curl: (51) SSL: certificate subject name (wiki.archlinux.org) does not match target host name 'aur4.archlinux.org'
```

My System is : 

```
$ uname -a
Linux mean-VirtualBox 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
##

**Comment by mfussenegger** [comment]
Where did you get that link from?

https://aur.archlinux.org/packages/crate/ links to  https://aur.archlinux.org/cgit/aur.git/snapshot/crate.tar.gz which works.

**Comment by MSaifAsif** [comment]
Getting this error while trying to install it with this command `bash -c "$(curl -L install.crate.io)"` from the page https://crate.io/docs/install/local/linux/

**Comment by mfussenegger** [comment]
This was an issue in the install script. Should be fixed with https://github.com/crate/crate-utils/commit/9eb4077c62d50ed82aa066f77a9d19c6edbd4d95

**Comment by MSaifAsif** [comment]
@mfussenegger Works fine now. Thanks for looking into it. Closing this now.
