### ISSUE TITLE
left outer join does not return results if joined table is empty.

### ISSUE THREAD

**Issue by jayweinstein** [crate/crate#4328]
left outer join does not return results if joined table is empty. This behavior is the same on 0.56.0, 0.56.1, 0.56.2

Simple reproduction:

> CREATE TABLE doc.test1 (
>     id integer primary key,
>     name string);
> CREATE OK, 1 row affected  (0.184 sec)
> 
> CREATE TABLE doc.test2 (
>     id2 integer primary key,
>     name2 string);
> CREATE OK, 1 row affected  (0.184 sec)
> 
> cr> insert into doc.test1 (id, name) values(1, 'one');
> INSERT OK, 1 row affected  (0.018 sec)
> cr> insert into doc.test1 (id, name) values(2, 'two');
> INSERT OK, 1 row affected  (0.014 sec)
> cr> insert into doc.test1 (id, name) values(3, 'three');
> INSERT OK, 1 row affected  (0.014 sec)

When doc.test2 table is empty, query below does not return results

> cr> select \* from doc.test1 left outer join doc.test2 on doc.test1.id = doc.test2.id2;
> +----+------+-----+-------+
> | id | name | id2 | name2 |
> +----+------+-----+-------+
> +----+------+-----+-------+
> SELECT 0 rows in set (0.022 sec)

**Comment by mfussenegger** [comment]
Thanks for reporting. We'll take a look at this.

**Comment by mfussenegger** [comment]
We've a fix for this (https://github.com/crate/crate/pull/4362) which will be in the next 0.56.X and 0.57.X releases

**Comment by jayweinstein** [comment]
Thank you
