### ISSUE TITLE
Alter table table_name modify/drop column ?

### ISSUE THREAD

**Issue by wking1986** [crate/crate#4398]
Hi Guys：
   'alter table tweets add column column_name type' is well，but how do modify/drop column?

**Comment by celaus** [comment]
Hi @wking1986 - currently this is not available 😕 but if you are up for a challenge we are looking for contributors 😄

**Comment by wking1986** [comment]
O(∩_∩)O~，OK，I am honored to be one of you!

**Comment by wking1986** [comment]
@celaus  How automatically clean up expiration doc tables？

**Comment by celaus** [comment]
you could use a cron job that issues a curl request periodically: https://crate.io/docs/reference/en/latest/protocols/http.html

**Comment by wking1986** [comment]
Whether to consider this function into crate-admin ui?

**Comment by celaus** [comment]
well, the admin UI is a client side application and therefore won't be able to schedule things periodically, and it's too specialized a feature to go into the core ;)

**Comment by celaus** [comment]
@wking1986 I am closing this issue now, it would be great if you could ask further questions on https://stackoverflow.com/tags/crate so other users with similar problems are able to find answers as well! We will still answer there :)

**Comment by SneakyMax** [comment]
Since this issue was closed, does that mean this is "no plans to implement"?

**Comment by taliaga** [comment]
It's just a duplicate of #4457
