### ISSUE TITLE
array funtion unsupport count length

### ISSUE THREAD

**Issue by foreachsky** [crate/crate#4411]
hi, i check all the Array Functions
i can find the function for count array length

is that unsupport?

**Comment by celaus** [comment]
Hi, yes we currently don't have a scalar function for array length ... but we welcome contributions 😃

**Comment by diyism** [comment]
Duplicate of #882 since Jun 16, 2014,  Sql: Allow array counting https://github.com/crate/crate/issues/882

**Comment by mfussenegger** [comment]
Closing as duplicate of https://github.com/crate/crate/issues/882
