### ISSUE TITLE
Question: How to restore data from directory from another crate.io host.

### ISSUE THREAD

**Issue by UTH** [crate/crate#4439]
Hi,
am testing drive Crate.io here, very glad to have such great product to use.
I deployed one crate cluster with 2 nodes in docker container successfully,
and also have 5 GB test data to create a table and query function pretty well.

And then I destroyed the two containers, and the data directories are kept.
**Question** is:  
**Could the existing data directories /path/data/0,1 be used to used in the new crate cluster directly?**
As I tried to reconfigure one new container with -v path to data pointed to the existing ones, the 5 GB table just could not be seen. If so, how to make it?

Any help would be appreciated. Thank you! : )

**Comment by celaus** [comment]
Hi, yes - usually the data directories can and will be re-used and CrateDB. Can you check the logs and maybe if the directory was mounted correctly? 

Cheers, Claus

**Comment by UTH** [comment]
Thanks @celaus for you tips very much. Problem solved.

_JUST FOR FUTURE REFERENCE._
By checking the mounted directory, I logged into the docker and found this:
 **/data mount only in default crate.yml**
In the manual/doc, it used /data as container data directory, how it seems only functions when you use the default crate.yml, so if any one would like to set a self-defined crate.yml out of the container, may have to redefine the path:"path.data: /data" in crate.yml and then do some mount job <your path>:/data to container configuration.
