### ISSUE TITLE
Randomly failed to connect

### ISSUE THREAD

**Issue by qwertyx64** [crate/crate#4456]
**CrateDB version**: 0.56.2-1~jessie
**OS version / environment description**: Debian Jessie

Hello, we have randomly connection errors: 
Exception:No more servers available, exception from last server: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 

Network is OK, no connections loss. Logs are empty.

**Comment by qwertyx64** [comment]
Is it in configuration something like max connections?

**Comment by celaus** [comment]
Hi @qwertyx64 - That depends, can you tell us more about your cluster setup? While there are connection limits, this error seems to be a result of what is going on on the server :) Is the cluster busy?

Cheers, Claus

**Comment by qwertyx64** [comment]
Hi, we have few thousands request per second for crate. Server load average is about 0.5 , network is internal 10Gbps. Only few times i found in logs "Could not resolve host: crate:192.168.201.36" . Three nodes in cluster.

`gateway.recover_after_nodes: 2
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping:
  multicast.enabled: false
  unicast.hosts:
  - 192.168.201.35:4300
  - 192.168.201.36:4300
  - 192.168.201.37:4300
cluster.name: cratecluster
node.name: "node1"
network.bind_host: 0.0.0.0
network.publish_host: 192.168.201.35
transport.tcp.port: 4300
transport.tcp.compress: true
http.port: 4200
http.max_content_length: 100mb
http.enabled: true
gateway.expected_nodes: 3
indices.recovery.max_size_per_sec: 1000mb
indices.recovery.concurrent_streams: 8
indices.recovery.max_bytes_per_sec: 1000mb
indices.store.throttle.max_bytes_per_sec: 1000mb
threadpool.index.queue_size: 500
threadpool.bulk.queue_size: 1000`

**Comment by celaus** [comment]
What's your hardware setup? Are you connecting to all three nodes or just one?

**Comment by mfussenegger** [comment]
Closing this as there hasn't been any more feedback. Feel free to re-open if this is still an issue.
