### ISSUE TITLE
excuse me, Can Crate move shard manually by restful api like ElasticSearch ? 

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#4511]
**CrateDB version**: crate-0.56.2

**JVM version**: 1.7.0_71

**OS version / environment description**: CentOS 6.2

**Problem description**: Can Crate move shard manually by restful api like ElasticSearch ? 

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
hi @aaronhadoop 
CrateDB provides some settings that can be set via SQL to control routing allocation of shards (https://crate.io/docs/reference/configuration.html#routing-allocation) but you cannot move shards directly, except for example moving all shards off a single node (https://crate.io/docs/reference/configuration.html#cluster-wide-allocation-filtering).

**Comment by wking1986** [comment]
hi @chaudum 
We encountered the same problem, Will crate can support manual migration table partition?

**Comment by mfussenegger** [comment]
Could you explain your use cases a bit?

**Comment by aaronhadoop** [comment]
Hello, we have solved the problem by the method below just as what to do in ElasticSearch.
curl -XPUT 'http://ip:port/_cluster/reroute?pretty' -d '{
    "commands" : [ {
        "move" :
            {
              "index" : "table_name", 
              "shard" : 3,
              "from_node" : "Zitterklapfen",
              "to_node" : "Piz Tasna"
            } }]
}'

Migrating the Crate‘s shard manually is normal by looking at the web page.
done!

**Comment by joemoe** [comment]
hi @aaronhadoop, @wking1986. thanks for the issue. we will put that on our backlog. i'll keep you up to date.

**Comment by chaudum** [comment]
Hi @aaronhadoop @wking1986 
CrateDB 2.3.0 (currently testing) added the `ALTER TABLE ... REROUTE ...` statement that allows to move shards explicitly.
ALTER TABLE docs: https://crate.io/docs/crate/reference/en/latest/sql/statements/alter-table.html#reroute
Full release notes: https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/2.3.0.html
