### ISSUE TITLE
[Feature Request] To index array elements for quering "where any(int_arr)>123"

### ISSUE THREAD

**Issue by diyism** [crate/crate#4515]
**Feature description**:
if 'names' values is ['Peter', 'McCain', 'McDonalds', 'Jack']
select * from statis_user_success where any(names) like 'Mc%' limit 1

if 'int_arr'  is [98234, 33,1232,2394]
select * from statis_user_success where any(int_arr)>123' limit 1

Hope:
get the rows with any one in names matched
get the rows with any one in int_arr that is greater than 123

**Comment by celaus** [comment]
Hi, thanks for the feature request, we'll discuss it and add it to the backlog if it works (I am not totally sure this fits into the distributed architecture)

Cheers, Claus

**Comment by diyism** [comment]
Backed this, https://www.bountysource.com/issues/39611200-feature-request-support-array_matched-to-filter-elements-by-any-condition

**Comment by diyism** [comment]
Currently, i can do: select regexp_matches(concat(',',strings[1], ',', strings[2], ',', strings[3],','), ',(Mc[^,]*),'),* from test limit 100;
I need array_regexp_matches(...)

**Comment by mfussenegger** [comment]
This is supported using [ANY](https://crate.io/docs/crate/reference/en/latest/general/dql/selects.html#any-array)

```
↪  cr8 run-crate 2.x.x -- @crash <<EOF
    create table t (names array(string), int_array array(integer));
    insert into t (names, int_array) values(['Peter', 'McCain', 'McDonalds', 'Jack'], [98234, 33,1232,2394]);
    insert into t (names, int_array) values(['Arthur'], [399]);
    refresh table t;
    select * from t where 'Mc%' like any(names);
    select * from t where 123 < any (int_array);
EOF
```

```
CREATE OK, 1 row affected  (0.247 sec)
INSERT OK, 1 row affected  (0.077 sec)
INSERT OK, 1 row affected  (0.004 sec)
REFRESH OK, 1 row affected  (0.097 sec)
+-------------------------+------------------------------------------+
| int_array               | names                                    |
+-------------------------+------------------------------------------+
| [98234, 33, 1232, 2394] | ["Peter", "McCain", "McDonalds", "Jack"] |
+-------------------------+------------------------------------------+
SELECT 1 row in set (0.123 sec)
+-------------------------+------------------------------------------+
| int_array               | names                                    |
+-------------------------+------------------------------------------+
| [98234, 33, 1232, 2394] | ["Peter", "McCain", "McDonalds", "Jack"] |
| [399]                   | ["Arthur"]                               |
+-------------------------+------------------------------------------+
SELECT 2 rows in set (0.015 sec)
```
