### ISSUE TITLE
how to config in Crate, different time data stored in different machine with the different hardware configuration

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#4524]
**CrateDB version**: crate-0.56.4

**JVM version**: 1.7.0_71

**OS version / environment description**: CentOS 6.2

**Problem description**: 
hello, I have two machines with ssd hard disk and other machines with ordinary hard disk. The question is how to config in Crate, today's data stored in the ssd hard drive and old data stored in the ordinary hard disk ?

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by aaronhadoop** [comment]
I have solved the problem by the method just as what to do in ElasticSearch. Dividing into the following steps:
1. config the Crate
vi $CRATE_HOME/config/crate.yml
set the configuration item in the Crate node with ssd disk
node.tag: hot

set the configuration item in the Crate node with sata disk
node.tag: cold

2. crate table in Crate

3.move data partition to different Crate node
3.1 move today's data partition to the Crate node with ssd disk
curl -XPUT 'http://ip:port/.partitioned.table_name.045j4c1h6omj2c9d60og/_settings' -d ' {
        "index.routing.allocation.include.tag" : "hot"
    }'
3.2 move yesterday's data partition to the Crate node with sata disk
curl -XPUT 'http://ip:port/.partitioned.table_name.045j4c1h6omj2c9d60og/_settings' -d ' {
        "index.routing.allocation.include.tag" : "cold"
    }'

done!

**Comment by celaus** [comment]
Great that you figured it out yourself :)
