### ISSUE TITLE
[Feature Request] Show active queue length on localhost:4200/_plugin/crate-admin/#/nodes

### ISSUE THREAD

**Issue by diyism** [crate/crate#4528]
**Feature description**:

"select thread_pools[15] from sys.nodes" return:
{"largest":24,"rejected":49278,"name":"bulk","active":5300,"threads":24,"completed":5879392,"queue":18}

"select network['tcp']['connections']['curr_established'] from sys.nodes" return:
1547

I think "rejected", "active", "curr_established" are very important health indicators for CrateDB,
so we should display them on "CLUSTER" tab page in the admin console.

**Comment by seut** [comment]
Thanks for this suggestion, but as this is crate-admin related only, pls create an issue at https://github.com/crate/crate-admin.
