### ISSUE TITLE
CLA agreement is missing

### ISSUE THREAD

**Issue by marcosbarbero** [crate/crate#4565]
In the `CONTRIBUTING.rst` file there's a link to a CLA agreement that's missing.
The link is https://crate.io/community/contribute/agreements/ but it's not there.

Bye

**Comment by jodok** [comment]
thanks for reporting! we recently did some restructuring on our website and it seems this was forgotten. we'll fix it asap and get back to you.

**Comment by jodok** [comment]
the page has been re-added.

**Comment by marcosbarbero** [comment]
Thanks!
