### ISSUE TITLE
Postgres Emulation: catalog tables

### ISSUE THREAD

**Issue by WalternativE** [crate/crate#4607]
Hello!

I'm currently working on an evaluation project using CrateDB. Working on .NET applications I was interested to try to use Npgsql to connect to Crate, as it shouldn't have the HTTP overhead of the RESTful API which is used in the community driven .NET clients. Unfortnuately while starting up a connection Npgsql queries some catalog tables.

As the pg_catalog schema is read only I don't have the ability to "fake" the tables and views it would like to query.

Is there a plan to implement the rest of the catalogs (or at least the most important ones - besides pg_type) or is there a way for me to implement them without working on the core?

Regards
Gregor

**Comment by mfussenegger** [comment]
Npgsql is already on our radar and something we want to support.

I think the last time we talked about it we were considering adding support for views, so that we could provide create view statements to point towards information_schema tables were appropriate.

But I'm not sure about the current state - maybe @joemoe or @cleishm can give you more information.

**Comment by WalternativE** [comment]
Cool, thanks for the answer.
Are they likely to answer in this issue or should I contact them on another channel?

**Comment by joemoe** [comment]
hi @WalternativE, this is for exactly this usecase in our backlog. i can't promise yet when this will be done and how, but there are other things that have a higher priority at the moment.

we are also discussing a CrateDB npgsql fork at the moment as the pg-tables are not the only thing that doesn't work properly with CrateDB in npgsql.

i'll keep you up to date.

**Comment by WalternativE** [comment]
Hi @joemoe thanks for the information. Until Npgsql is supported I'll just hack around with one of the ADO.net Http Endpoint facades.

Regards
Gregor

**Comment by witwall** [comment]
with dbeaver and postgresql jdbc library, I got the following error

```
SQL Error [XX000]: ERROR: TableUnknownException: Table 'pg_catalog.pg_database' unknown
  org.postgresql.util.PSQLException: ERROR: TableUnknownException: Table 'pg_catalog.pg_database' unknown

```

<img width="796" alt="screen shot 2017-01-23 at 11 59 34 am" src="https://cloud.githubusercontent.com/assets/3222056/22191199/91944580-e163-11e6-8b16-99ba31f6b5e2.png">
<img width="533" alt="screen shot 2017-01-23 at 11 44 34 am" src="https://cloud.githubusercontent.com/assets/3222056/22191200/919ad616-e163-11e6-8f55-549b6bf48a13.png">

**Comment by chaudum** [comment]
@witwall When connecting a Java application you should use the [crate-jdbc](https://crate.io/docs/reference/jdbc/) driver instead. CrateDB does not fully emulate PostgreSQL, although some features (mainly [Postgres Wire Protocol](https://crate.io/docs/reference/en/latest/protocols/postgres.html)) are available.

**Comment by joemoe** [comment]
@WalternativE @witwall the npgsql driver is now available.
https://github.com/pircher-software/npgsql-cratedb
https://www.nuget.org/packages/Npgsql.CrateDB

**Comment by witwall** [comment]
@joemoe , thanks and let me check it.

**Comment by mfussenegger** [comment]
I'm going to close this as .NET users can use  [crate-npgsql](https://github.com/crate/crate-npgsql). We've also done some work for improved `pg_catalog` compatibility (coming in 3.2).

If some tables are still missing please open up a specific issue.
