### ISSUE TITLE
Official NodeJs Client For CrateDb!

### ISSUE THREAD

**Issue by shivarajnaidu** [crate/crate#4619]
Feature Request:

I have seen several community driven NodeJs Clients for CrateDB. But If we can have official client that will be good to  #see... Because NodeJS is one of the popular and rapidly evolving technology.. So please consider supporting it with official client.

**Comment by jodok** [comment]
unfortunately we don't have NodeJS know-how inhouse. however, we'd support and sponsor the NodeJS community to work on our NodeJS driver.

**Comment by shivarajnaidu** [comment]
Thanks for quick response.. You may support Node community explicitly to work on your nodejs driver, but official support is important for integrity and of course it's one of the factor to success ... Please at least consider official driver for nodejs...

**Comment by celaus** [comment]
Hi @shivarajnaidu - there are a few community maintained drivers for Node, however we don't know which works properly :) 

https://www.npmjs.com/package/crate-connect 
https://github.com/vincic/node-crate
https://www.npmjs.com/package/node-crate

let us know which works :)

**Comment by shivarajnaidu** [comment]
ya... There are some clients out there.. Still I too don't know which plays well with this new great db ... That's why i am saying to consider bringing officially supported driver for nodejs (at least in near future).. So that we can ensure nodejs-cratedb integrity .... Why i am telling to consider in bringing official node driver is because like java, php now node also one of the hot as well as rapidly growing technology.. supporting it officially is very important db ecosystem ... more or less all similar dbs has official nodejs driver for their db..

**Comment by joemoe** [comment]
@shivarajnaidu thanks for your suggestion. this is on our backlog and we will discuss this. i'll give you an update if there is something new.

**Comment by shivarajnaidu** [comment]
Thanks For Considering My Request and  Will Be Very Happy To Contribute To Develop Node Client For New Innovative Db. @joemoe

**Comment by ansarizafar** [comment]
Any new update?

**Comment by marregui** [comment]
Hi @shivarajnaidu ,

I hope you are well.

Just would like to let you know that as soon as this PR is merged, we will begin our journey with nodejs:
https://github.com/crate/crate-qa/pull/129

Happy coding!

**Comment by mfussenegger** [comment]
To elaborate a bit on what @marregui said:

Going forward we recommend to use [node-postgres](https://node-postgres.com/) with CrateDB. It will be the officially supported client.

We'll soon have our client pages updated to reflect that and we're creating some more content to illustrate how to use it.
