### ISSUE TITLE
crate not showing table in admin UI

### ISSUE THREAD

**Issue by fjblau** [crate/crate#4620]
**CrateDB version**: 1.0.1

**JVM version**:java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**OS version / environment description**: MacOS Sierra

**Problem description**:

Created a table successfully in crate. I can read and write from the table in the console. When I go to the "Table" tab it shows Tables [0].

**Steps to reproduce**:

create table locations (magZ int, magY int, magX int, temp float, timestamp string, accY int, accX int , sensorid string, accZ int, dtmin int, hPa float, temptime timestamp, topic string);

**Comment by celaus** [comment]
Hi, that is weird, and for me it works. What browser are you using? Can you see if there are any JS errors shown in the console? 

Cheers, Claus

**Comment by fjblau** [comment]
Well I rebooted everything and now the table is showing up... if it happens
again I'll check the console and let you know.

Thanks for everything, I love crate!

Frank

**Comment by fjblau** [comment]
OK, it is happening again... and this is the console error:

angular.c695c05d.js:2 URIError: URI malformed
    at decodeURI (<anonymous>)
    at XMLHttpRequest.send (xhrExtension.js:2)
    at angular.c695c05d.js:2
    at q (angular.c695c05d.js:2)
    at i (angular.c695c05d.js:2)
    at g (angular.c695c05d.js:3)
    at angular.c695c05d.js:3
    at o.$eval (angular.c695c05d.js:3)
    at o.$digest (angular.c695c05d.js:3)
    at o.$apply (angular.c695c05d.js:3)(anonymous function) @
angular.c695c05d.js:2
6angular.c695c05d.js:2 URIError: URI malformed
    at decodeURI (<anonymous>)
    at XMLHttpRequest.send (xhrExtension.js:2)
    at angular.c695c05d.js:2
    at q (angular.c695c05d.js:2)
    at i (angular.c695c05d.js:2)
    at g (angular.c695c05d.js:3)
    at angular.c695c05d.js:3
    at o.$eval (angular.c695c05d.js:3)
    at o.$digest (angular.c695c05d.js:3)
    at o.$apply (angular.c695c05d.js:3)

**Comment by m-kharbat** [comment]
thank you @fjblau we are looking into the issue

**Comment by m-kharbat** [comment]
I'm having a hard time to reproduce the issue.. which browser are you using @fjblau, and does one of your tables contain some special characters ?

**Comment by fjblau** [comment]
Chrome

No special characters

**Comment by bogensberger** [comment]
HI @fjblau, i also tried to reproduce this, but it never happened on my side. Which version of Chrome are you using?

**Comment by fjblau** [comment]
Version 54.0.2840.98 (64-bit)

**Comment by bogensberger** [comment]
@fjblau do you mind contacting me in the crate public slack channel, so we can issue a call on that?

**Comment by mfussenegger** [comment]
@bogensberger what's the status here?

**Comment by fjblau** [comment]
At this point the tables are showing up, but I am not sure what changed to make it so. But we can close this for now and I'll ping you if it happens again. Thanks for your attention to detail!
