### ISSUE TITLE
Invalid table name error message

### ISSUE THREAD

**Issue by mamod** [crate/crate#4630]
**CrateDB version**: 1.0.1
**JVM version**: 1.8.0_112

**Problem description**:

Creating a table with invalid name produces the following error

| Error Code | Error Message                                                                                                   |
|------------|----------------------------------------------------------------------------------|
| ``5000``       | InvalidIndexNameException[Invalid index name [_test], must not start with '\_']   |

Expected error message / previous versions produced

| Error Code | Error Message                                                                                                   |
|------------|----------------------------------------------------------------------------------|
| ``4002``       | SQLActionException[InvalidTableNameException: table name "_test" is invalid.]   |

This is not a big issue, but there is a mismatch between error code ``5000`` which documented as ``Unhandled server error.`` and the current error message when using the http end point

**Steps to reproduce**:

``create table _test (id int primary key);``

**Comment by joemoe** [comment]
thanks @mamod.

**Comment by bogensberger** [comment]
Hi @mamod,
thanks for reporting this issue. I fixed this with: https://github.com/crate/crate/pull/4640 and it will be released with the next hotfix release.

**Comment by mamod** [comment]
Thank you guys, that's great as usual :+1:
