### ISSUE TITLE
regex in generated columns ?

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate#4631]
Hi

Question on support for regex as function in generated columns

I tried to add a table with a "generated column" in addition to my standard columns. This column was described as:  

gencolumna AS (regexp_matches(columna, '^[^a-zA-Z0-9]?(.*)')[1])

I tried to remove non letter/number in first position in a new column used as index.

After error adding table with the column all table disapeared from the admin gui. From jdbc I can still access the db and do query on all but not any table operations. I guess my adding table w regex gen col screwed the table schema up or something.

Is it supported to use regex as function in generated columns? It mentions functions, any limitations to certain functions?

running docker crate 55.6.

/Jonas

**Comment by joemoe** [comment]
hi @joalmjoalm, this sounds like a really `special` behavior. we are looking into this.

**Comment by matriv** [comment]
@joalmjoalm The issues has been fixed and will be available with 1.0.2 release.
Thanks again for reporting!

**Comment by joalmjoalm** [comment]
Many thanks. Appreciate your work.
