### ISSUE TITLE
When to support elasticsearch 5/lucene 6?

### ISSUE THREAD

**Issue by frompinge** [crate/crate#4636]
I'd like to know what's the plan for new version integration?

**Comment by joemoe** [comment]
hi @frompinge, we are currently working on the migration, but it will take some time. expect it somewhen early next year.

why do you need es5/lucene6?

**Comment by joemoe** [comment]
hi @frompinge, there is a testing release out based on elasticsearch 5. the version is 1.2.0.
https://crate.io/docs/reference/en/1.2.0/release_notes/1.2.0.html
