### ISSUE TITLE
job removed from sys.jobs table before insert in partitioned table completed

### ISSUE THREAD

**Issue by devonkinghorn** [crate/crate#4656]
**CrateDB version**: 0.56.3

**JVM version**: 1.8.0_102

**OS version / environment description**: osx 10.12.1

**Problem description**: 
The job in sys.jobs is removed before an insertion into a partitioned table is completed. I want to insert into one table from another. and then delete the temporary table (textfields.en_temp) once the query is no longer in the jobs, however The job is not always completed when it is removed from sys.jobs
```    
INSERT INTO textfields.en (brandid, content, fieldsetid)
    (
	SELECT brandid, content, fieldsetid
        FROM textfields.en_us_temp
    );

select * from sys.jobs;

drop table textfields.en_temp;
```
Because of this, I can't tell when the job is done to delete the source table. If the source table is dropped before the finalTable insert completes then some data is lost (its always in the last few partitions alphabetically). This is a table of partitions from the admin/tables page. Before inserting all brandid's had 55515 values. After, zbalancorp4 had 51199. If I wait for a while after the job is completed then no records get lost.

|Health|	Ident |	Partition Values|	Conf. Replicas|	Conf. Shards|	Started Shards|	Missing Shards|	Underr. Shards|	Total Records|	Unavail. Records|	Underr. Records|	Size|
| --- |  --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
warning|	04562r31dphmusjg64|	alancorp1|	1|	5|	5|	0|	5|	55515|	0|	55515|	19.5 MB
warning|	04562r31dphmusjg68|	alancorp2|	1|	5|	5|	0|	5|	55515|	0|	55515|	20.0 MB
warning|	04562r31dphmusjg6c|	alancorp3|	1|	5|	5|	0|	5|	55515|	0|	55515|	19.2 MB
warning|	04562r31dphmusjg6g|	alancorp4|	1|	5|	5|	0|	5|	55515|	0|	55515|	19.4 MB
warning|	045m2obcc5n66rrie0q0|	aalancorp4|	1|	5|	5|	0|	5|	55515|	0|	55515|	19.0 MB
warning|	045m4obcc5n66rrie0q0|	balancorp4|	1|	5|	5|	0|	5|	55515|	0|	55515|	19.6 MB
warning	|0467koj1dhgmsorfe9o38	|zbalancorp4	|1	|5|	5|	0|	5|	51199|	0|	51199|	18.6 MB

**Steps to reproduce**:
We are running into this issue because we want to reindex a full template and this is our procedure.
This was all run through the python crate library.
1. have a table with partitions and analyzed etc.
2. enable stats `set global stats.enabled = true`
3. create a temporary table with the same fields. 
```
CREATE TABLE IF NOT EXISTS textfields.en_temp 
( "brandid" STRING, "content" STRING, "fieldsetid" STRING )
```
4. insert into the temporary table all of the data from the original
```
INSERT INTO textfields.en_temp ("brandid", "content", "fieldsetid")
    (
        SELECT "brandid", "content", "fieldsetid"
         FROM textfields.en
    )
``` 
5. wait for the job to finish with this`select count(*) from sys.jobs where stmt = {the previous insert statement}`
6. delete the original table.`drop table textfields.en;` (all the records make it into the temporary table)
7. create the new table 
```
CREATE TABLE IF NOT EXISTS "textfields"."en" (
    "brandid" STRING,
    "content" STRING,
    "recordid" STRING,
    PRIMARY KEY ("brandid", "recordid"),
    INDEX "exact" USING FULLTEXT ("content") WITH (
        analyzer = 'standard'
    )
    )
    CLUSTERED INTO 5 SHARDS
    PARTITIONED BY ("brandid")
```
8. insert from the temporary table into the new table. similar to step 4
9. wait for the job to finish same as step 5.
10. delete the temp table. Right here not all of the records are in the last few partitions, even though the job was removed from sys.jobs.

This needs to be run in a script. Otherwise the error won't be found because the insertion completes eventually. As the number of records increases the larger this problem becomes. With only a few thousand records the problem isn't seen.

**Comment by seut** [comment]
thx for reporting, we'll take a look

**Comment by matriv** [comment]
Hello @devonkinghorn,

The only way I can reproduce your issue is if I don't have `refresh table` statements in between. 
So please make sure that you run the following in your script:
before 4: `refresh table textfields.en`
before 8: `refresh table textfields.en_temp`

**Comment by matriv** [comment]
Hi @devonkinghorn, any update on this?

**Comment by matriv** [comment]
I'm closing the issue but feel free to reopen if you still experience any issues.
