### ISSUE TITLE
UnsupportedFeatureException: ORDER BY

### ISSUE THREAD

**Issue by l7s** [crate/crate#4662]
**CrateDB version**: 1.0.1

**JVM version**: 1.8.0_60

**OS version / environment description**: Debian 7 x64

**Problem description**:

In Crate 0.54.5 using the following schema:

```
CREATE TABLE queue_call (
  id long primary key,
  partner_id integer,
  customer_id integer,
  location_id integer,
  live_id long,
  queue_id integer,
  ddi string,
  cli string,
  callers integer,
  agents integer,
  start_time integer,
  hold_time integer,
  conn_time integer,
  final_dst_type string,
  final_dst_id string,
  src_call_id string,
  dst_call_id string,
  t_cause string
);
```

the following query worked just fine:
```
SELECT AVG(hold_time) AS avg FROM queue_call WHERE queue_id = 2 AND start_time > 1483833600 ORDER BY id DESC LIMIT 5000
```

after upgrading from 0.54.5 to 1.0.1 it throws error as below:
```
SQLActionException[UnsupportedFeatureException: ORDER BY expression 'id' must appear in the select clause when grouping or global aggregation is used]
```

Could you let me know why is that and how to fix this?

Regards,
Chris

**Comment by matriv** [comment]
@l7s 

Hello Chris, 

This is a valid behaviour since it doesn't make sense to order by a column that doesn't take part in the aggregation. You get the relevant message also in PostgreSQL for example:
```
ERROR:  column "queue_call.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...queue_id = 2 AND start_time > 1483833600 ORDER BY id DESC LI...
                                                             ^

********** Error **********

ERROR: column "queue_call.id" must appear in the GROUP BY clause or be used in an aggregate function
SQL state: 42803
Character: 102
```

**Comment by mfussenegger** [comment]
> Could you let me know why is that and how to fix this?

You can remove both, the ORDER BY and also the LIMIT clause. These two clauses are applied AFTER the aggregation. So for your statement any LIMIT > 0 doesn't have an effect. Similar, ORDER BY doesn't have any effect since you always get 1 row.

If you wanted to only get the average for the first 5000 rows you'd have to write the statement like this:

```
SELECT AVG(hold_time) AS avg FROM (select hold_time from queue_call WHERE queue_id = 2 AND start_time > 1483833600 ORDER BY id DESC LIMIT 5000) t
```

**Comment by l7s** [comment]
Hi, many thanks for this. Indeed I see now where the problem was. Best regards, Chris
