### ISSUE TITLE
Crate will not start on Windows if not installed on C:

### ISSUE THREAD

**Issue by tellezb** [crate/crate#4671]
**CrateDB version**: 
1.0.1

**JVM version**: 
1.8.0_51

**OS version / environment description**: 
Windows 10 Professional x64

**Problem description**:
I downloaded and expanded the tarball to D:\Crate. The only change made to crate.yml was to add a cluster name.

Running crate.bat results in error: **\Crate\Crate-1.0.1/lib/crate-app-1.0.1.jar was unexpected at this time.**

Moving the Crate folder to C:\Crate resolved the problem.

**Comment by chaudum** [comment]
hi @tellezb thanks for reporting. we'll have a look!

**Comment by mikethebeer** [comment]
@tellezb we are not able to reproduce the issue. Tested with Win 8.1 / 10 like you can see in the screen. Can you show us the console output / log output of your start procedure?

![crate-win](https://cloud.githubusercontent.com/assets/6863216/21842074/6e60234a-d7e5-11e6-949e-d0bce2f95224.PNG)

**Comment by tellezb** [comment]
Well, we seem to be unable to reproduce now. Wondering if we had a folder with insufficient privileges last time. Fresh setup on the secondary drive seems fine now...
