### ISSUE TITLE
Bug: ORDER BY inconsistent with subquery

### ISSUE THREAD

**Issue by bowenwr** [crate/crate#4673]
**CrateDB version**: 1.0.1

**JVM version**: Oracle JDK 8

**OS version / environment description**: Debian Jessie latest in Docker

**Problem description**:

I'm seeing some ordering behavior I consider unexpected. Using the query on a simple dataset:

```
select ds.string_full as string_full
from (select * from integration_tests.connector_test) as ds
where not (ds.string_full = 'Accessories Computers' or ds.string_full is null)
group by string_full
order by string_full asc
limit 5
```

Every time I execute it, I'm seeing the resulting 5 records in "random" order, changing each time. I would expect the `ORDER BY` to be respected and keep the order consistent for each run.

I asked in the Slack channel and Claus suggested this was a bug.

**Comment by matriv** [comment]
Hi @bowenwr,

The issue has been solved and the fix will be available with 1.0.3 release.
Thanks for reporting!
