### ISSUE TITLE
fulltext search fuzziness Auto

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate#4694]
Hi 

When doing fulltext search with fuzziness, AUTO seems to not be recognized any longer. It works with a fixed number but not w Auto any longer.

Auto worked in ver 55.6

error in 1.02:
"message": "SQLActionException[UnhandledServerException: java.lang.NumberFormatException: For input string: \"[41 55 54 4f]\"]",
    "code": 5000

41 55 54 4f  = AUTO
https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzziness.html

Ex. 
select xx from tableA where
match (xx_ft, 'yy') using most_fields with (prefix_length=2, fuzziness='AUTO', minimum_should_match='1<67% 5<3') 
_score >= 0 order by _score desc

crateDB docker 1.0.2
JVM Host - openjdk 1.8.0_111
host ubuntu 1604

**Comment by mfussenegger** [comment]
Thanks for reporting, we'll take a look at it.

**Comment by mfussenegger** [comment]
This has been fixed (https://github.com/crate/crate/pull/4714). The fix will be in the next 1.0. hotfix release
