### ISSUE TITLE
500 response under minimal load with no information in logs

### ISSUE THREAD

**Issue by bmwmaestoso** [crate/crate#4697]
**CrateDB version**: 1.0.1

**JVM version**: OpenJDK 1.8.0_111-b15

**OS version / environment description**:
ulimit -a
Linux db-int-03 3.10.0-327.36.3 el7.x86_64 #1 SMP
3 nodes each with 8cpu 64G mem
1 client node

**Problem description**:
I have created a Perl script that will read data from a file and populate a single table. The table has 23 entries and 5 values that compose the primary key. I have 100 million entries to pre-populate for this table. I was trying to perform this task in parallel by breaking the input file into multiple files and then running several instances of the Perl script to populate the data. Immediately after starting the second instance I started getting 500 errors. The error message is:
"Can't connect to 7.170.111.179:4200 (Cannot assign requested address)"

Once it hits this condition, there will be a rash of 500 responses and then it will start accepting requests again. After a period of being accepting requests, another window of 500 responses will occur. This cycle will continue as long as there is sufficient load.

Initially, I was sending all of the requests to the client. I then modified the url request to do a around robin approach for each server node. While this did allow me to run multiple instances, if I started too many instances in parallel, 500 responses will occur. The load on the servers is still very minimal.

I now have added code that has a backoff algorithm upon receiving a 500 response. However, I am not producing that great of a load on the system. Even with 3 instances running using a round robin approach to each of the nodes:
total cpu utilization is around 10-15%  (user-5-8) system (2-4)
io wait time is generally around 1-3%
disk utilization is varies between 0-40%
there are no system resources that i can see that are stressed
I used this command to monitor each of the shards: "iostat -cdmNtxyz 3"
Also used vmstat command to check for any blocked processes.

I also changed the threadpool configuration for bulk, index, search, and get to the following:
threadpool.xxx.queue_size = -1  (unbounded)
threadpool.xxx.size: 30
There shouldn't be an issue with the queue size or the number of threads to handle the requests.

The major problem here is that there is no way that I can resolve the problem. I have tried several options to see if it would resolve the problem:
- set the number of shards to 2 
- * set the number of replicas to 0
   

I have also used 2 different methods for populating the data without any difference:
- a single insert statement with multiple values   (insert .. values (..),(...),..)
- using bulk_args  (insert ... values (?...), bulk_args: [[...],[...],...])

I have modified the batch size for each request from 10 to 1000 entries and this doesn't seem to make a difference.

There are some Linux system tcp configuration changes that I can make to improce performance but I don't believe that these will make that big of a difference. I have used Mongo on the same systems without any system tcp changes to achieve very high throughput values.

There are no entries in the log file or any stack traces anywhere that I can find. All of the crate log files do not have any entries. I have looked in
/var/log/crate
/var/log/messages

**Steps to reproduce**:
1) generate an input file with 500k entries
2) write a program that will read the input file and send batches of entries to crate
3) run multiple instances using the same input file, just ignore duplicates

Fields that are of type string all contain data that is relatively short (2-10) characters in length).
I have to type this in by hand so there may be typos:

CREATE Table query {
  gm string PRIMARY KEY,
  domain string PRIMARY KEY,
  qid string PRIMARY KEY,
  user string PRIMARY KEY,
  ts timestamp PRIMARY KEY,
  cn string,
  audit string INDEX OFF,
  batch long NOT NULL,
  beginDate timestamp INDEX OFF,
  endDate timestamp INDEX OFF,
  duration long,
  durationBegin timestamp INDEX OFF,
  durationEnd timestamp INDEX OFF,
  qlimit long INDEX OFF,
  latest string INDEX OFF,
  name string INFEX OFF,
  project string INDEX OFF,
  status string,
  target string INDEX OFF,
  qType string INDEX OFF,
  resultCount long,
  proxdEntities string INDEX OFF,
  proxiedIssuers string INDEX OFF,
  baseTime timestamp,

  INDEX IdxUserID using fulltext(cn, domain, user),
  INDEX IdxStatus using fulltext(cn, domain status)
) CLUSTERED INTO 15 shards
  with (column-policy = 'strict',
           number_of_replicas = '0-all');

**Comment by mfussenegger** [comment]
Is the perl script by chance not re-using connections?

I suspect an issue with file descriptors - so that CrateDB cannot accept new connections.
Can you post the output of

```
select process, network['tcp']['connections'] from sys.nodes;
```

(once before you import, and once when you start getting 500 responses)

**Comment by bmwmaestoso** [comment]
I don't see much of a difference but I do see something that might be an issue, We have not changed any of the limits for the crate process. The default open file size is 1024 and the hard limit is 4096. For certain it won't be able to set the open files to 65535. I sent all requests to the client node in order to replicate the problem.

process.max_open_file_descriptors: 65535

network.dropped remained the same for before/after
network.embroynoic_dropped remained the same for before/after
network.curr_established remained the same for before/after
network.initiated on;y changed on the client

node                                       client    node-1  node-2  node-3
process
open_file_descriptors before      364      1037     1037     1041
open_file_descriptors after         364      1037     1031     1025
network
accepted before                     41339393  5956132  5956098  6318758
accepted after                        41433215  5972226  5972183 6334852
initiated before                       59603032
initiated after                          59745134

**Comment by bmwmaestoso** [comment]
I changed open files hard limit to 65535 on all of the nodes and client, restarted crate on each instance. Reran test and still getting 500 responses.

**Comment by joemoe** [comment]
@bmwmaestoso we will have a look at this!

**Comment by mfussenegger** [comment]
```
accepted before 41339393 5956132 5956098 6318758
accepted after 41433215 5972226 5972183 6334852
initiated before 59603032
initiated after 59745134
```

Indicate that you're creating tons of connections. Can you try to change the perl scripts to use HTTP 1.1 and re-use connections? 

What does ` select  network['tcp']['connections']['dropped'] from sys.nodes` say?
I assume you see a high number there?

**Comment by bmwmaestoso** [comment]
I would have assumed that Perl would use 1.1 by default. In fact it took some digging to see how to properly set the protocol. The interesting part is while searching for information I found this http://www.perlmonks.org/?node_id=308550

As for dropped connections, these values are all rather low (10-30) and did not change during testing.

Something must have changed in my code that is slowing things down. I can now run 4 instances but the input rate is very slow. Setting the protocol doesn't affect the input rate, all it does is delay when the 500 responses start. I have some other tables that I need to load. I will be working on converting these tables to see if I get a different input rate.

**Comment by bmwmaestoso** [comment]
There is something about this table that Crate does not like. I have another table that is being migrated that is composed of fewer fields and does not create any compound indexes, other than the primary key. The insertion rate for each instance is 2500 entries/sec and there were 6 instances executing in parallel writing to the same Crate client (2500 x 6 = 15000/sec). There were no 500 response errors from any of the instances.

CREATE TABLE hdfs {
  gm string PRIMARY KEY,
  finish timestamp PRIMARY KEY,
  name string PRIMARY KEY,
  bytes long PRIMARY KEY,
  dirs long INDEX OFF,
  files long INDEX OFF,
  blocks long INDEX OFF,
  bc long INDEX OFF,
  bb long INDEX OFF,
  cn string,
  ts timestamp
) CLUSTER INTO 8 chards
    with (column_policy = 'strict',
             number_of_replicas = '0-all');

**Comment by bmwmaestoso** [comment]
I was able to populate 7.5 million entries to the hdfs table using 16 single threaded perl instances in just around 12 minutes. There were no 500 response errors. I will play around with the problem table to determine where it is having problems. I suspect the compound indexes may be a problem.

**Comment by mfussenegger** [comment]
The error message (`"Can't connect to 7.170.111.179:4200 (Cannot assign requested address)"`) still indicates that there is a networking issue.

I first assumed that it could be the server which cannot accept the connection because of a lack of file descriptors and too many sockets.

But it might actually be the client that is running out of file descriptors. 
This could be the case because it's creating new connections on each request and doesn't close them properly.

Would it be possible to share the perl script?

I tried to reproduce the problem but wasn't able to. When I intentionally overload the cluster it results in different errors.

**Comment by bmwmaestoso** [comment]
After working on other aspects, I finally got back to this problem and was able to isolate the issue. The perl script is just run as a single threaded process that does the following:

read entries from input file until end of file
    get user from input data
    check for existence of user in table
    if user does not exist create new user in table
    add new entry to cached list of existing input data
    if max buffer size for cached entry list is reached then
        flush buffered data to database table
end while - read entries from file

The perl script does not need to be fast because most of the time the input files that are not that big. However, when initially converting the existing database, there are lots of entries (some tables have over 110 million entries). The problem area is the select statement that checks for the existence of the user. If I remove this check everything works just fine. This script can run where all of the users are known and it still has a problem, thus the insert is not the problem. I can resolve this problem within the script by loading the existing user table into a local cache but there is still an underlying issue here that should be examined.

It is going to be impossible to share the code as I have too many supporting Perl modules. All of the code is on an internal network and there is no connectivity for security purposes. However, I should be able to create a stripped down test case that will exhibit the problem.

Here is what I do know about the environment:
* The hard limit for the number of files for the crate user is set to 65535. The soft limit was not changed so if the crate process does not change the resource limit it will still be set at 1024.
* This runs as a standalone process, it doesn't run in a web server or is called used from other large Perl modules.  The code base is very small and the logic is simple. There is no manipulation of the data. It is simply read from file write to database. It only connects to the database and nothing else.
* The tcp wait timeout has not been modified (I believe the default is 120 seconds). This could be a potential issue if the Perl library only uses a specific range of ports. However, this should not result in a 500 response by the Perl library. The request is being issued.
* I believe I stated earlier that it didn't matter whether I connected to the client or one of the servers. The behavior does not change.

What I will do from here is:
* create a simple test case
* change the tcp wait timeout and add a comment later
* check the number of open files using lsof command and comment if needed but I don't expect this to be an issue, at a maximum there should only be 2 open files by the application, the input file and perhaps an http connection to crate (there may be other files opened by the os and perl framework)

**Comment by bmwmaestoso** [comment]
Here is a stripped down test case that causes the problem. I have to copy this by hand so there may be a typo. One should be able to replicate this in any language. I created 2 tables that only have a a single field. The tables really don't matter.

CREATE TABLE u (
   u string PRIMARY KEY
) clustered into 2 shards
  WITH (column_policy = 'strict');
CREATE TABLE target (
   rval string PRIMARY KEY
) clustered into 2 shards
  WITH (column_policy = 'strict');

#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use LWP::UserAgent;
use String::Random;

my $url = "http://.../_sql?pretty";
my $gen = new String::Random;
my $insert = "insert into target (rval) values ";
my $select = "select * from u where uid = ';
my $values;
my $num = 30000;
my $MaxBuf = 100;
my $buf = 0;
my $tot = 0;

for (my $n = 0; $n < $num; $n++) {
  my $val = $gen->randpattern("cncncncncn");
  buf++;
  tot++;
  my $sel = $select . "$val'";
  post($sel);
  $values .= "('" . $val . "'),";
  if ($buf >= $MaxBuf) {
    print "flush buffer $tot\n";
    chop $values;
    my $ins = $insert . $values;
    post($ins);
    $buf = 0;
    $values = "";
  }
}

sub post {
  my ($sql) = @_;
  my $req = HTTP::Request->new('POST' => $url);
  my $body = '{"stmt":"' . $sql . '"}';
  $req->content($body);
  $req->protocol('HTTP/1.1');
  my $ua = LWP::UserAgent->new(HTTPVersion => '1.1');
  my $resp = $ua->request($req);
  my $rCode = $resp->code;
  if (500 == $rCode) {
    print "500 response occurred\n";
  } elsif (400 <= $resp->code) {
    my $dump = Dumper($resp);
    print "$dump\n";
  }
}

**Comment by mfussenegger** [comment]
Thanks that's great. I'll take a closer look later today

**Comment by bmwmaestoso** [comment]
Forgot to mention. If run a single instance it will work. Run 3-4 instances and the 500 errors will occur.

**Comment by mfussenegger** [comment]
With your script I was able to reproduce the issue. As I suspected it's not
re-using connections properly.

In order to fix the script the following lines can be added **outside** the
loop:

    my $cache = LWP::ConnCache->new;
    my $ua = LWP::UserAgent->new(conn_cache => $cache);

In order to verify that it is working you can monitor 

    select network['tcp']['connections'] from sys.nodes;

Once all perl processes have started the `curr_established` value shouldn't go up.
Also, earlier when I asked about the number of `dropped` I was wrong: the
`embryonic_dropped` value shows how many connections couldn't be accepted.


Full script then looks as follows:

    #!/usr/bin/perl

    use warnings;
    use Data::Dumper;
    use LWP::ConnCache;
    use LWP::UserAgent;
    use String::Random;

    my $url = "http://localhost:4200/_sql?pretty";
    my $gen = new String::Random;
    my $insert = "insert into target (rval) values ";
    my $select = "select * from u where u = '";
    my $values;
    my $num = 30000;
    my $MaxBuf = 100;
    my $buf = 0;
    my $tot = 0;
    my $cache = LWP::ConnCache->new;
    my $ua = LWP::UserAgent->new(conn_cache => $cache);

    for (my $n = 0; $n < $num; $n++) {
    my $val = $gen->randpattern("cncncncncn");
    $buf++;
    $tot++;
    my $sel = $select . "$val'";
    post($sel);
    $values .= "('" . $val . "'),";
    if ($buf >= $MaxBuf) {
        print "flush buffer $tot\n";
        chop $values;
        my $ins = $insert . $values;
        post($ins);
        $buf = 0;
        $values = "";
    }
    }

    sub post {
    my ($sql) = @_;
    my $req = HTTP::Request->new('POST' => $url);
    my $body = '{"stmt":"' . $sql . '"}';
    $req->content($body);
    $req->protocol('HTTP/1.1');
    my $resp = $ua->request($req);
    my $rCode = $resp->code;
    if (500 == $rCode) {
        print "500 response occurred \n";
        my $dump = Dumper($resp);
        print "$dump\n";
    } elsif (400 <= $resp->code) {
        my $dump = Dumper($resp);
        print "$dump\n";
    }
    }

**Comment by bmwmaestoso** [comment]
I will incorporate that fix into the code base. Normally, I prefer to use Java but this project is using Perl for processing input data from files. I suspect that this issue is probably handled transparently by Java. I am wondering why this wouldn't be the default behavior for Perl.

**Comment by bmwmaestoso** [comment]
My test worked with the changes.
