### ISSUE TITLE
java.util.ArrayList cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by cweiske** [crate/crate#4708]
**CrateDB version**: 1.0.1, Build: 22739b2/2016-12-12T16:41:45Z, ES: 2.4.2, JVM: 

**JVM version**: 1.8.0_111-internal

**OS version / environment description**: official docker image, alpine 3.4.4

**Problem description**:

Selecting from a table crashed crate.

Query: `select * from sometable where (d = 153 limit 1`

```
SQLActionException: INTERNAL_SERVER_ERROR 5000 ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at io.crate.types.ObjectType.value(ObjectType.java:59)
	at io.crate.types.ObjectType.value(ObjectType.java:32)
	at io.crate.operation.reference.doc.lucene.DocCollectorExpression$1.value(DocCollectorExpression.java:72)
	at io.crate.operation.InputRow.get(InputRow.java:44)
	at io.crate.executor.transport.StreamBucket$Builder.add(StreamBucket.java:68)
	at io.crate.operation.fetch.FetchCollector.collect(FetchCollector.java:89)
	at io.crate.operation.fetch.NodeFetchOperation$CollectRunnable.run(NodeFetchOperation.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Steps to reproduce**:

Unfortunately I cannot provide steps to reproduce. Data in the table could not be accessed anymore, so I truncated it and started afresh. The problem then did not appear again.

Table structure:
```
CREATE TABLE IF NOT EXISTS "doc"."sometable" (
   "created_at" TIMESTAMP,
   "description" STRING,
   "id" LONG,
   "keywords" STRING,
   "media" OBJECT (DYNAMIC) AS (
      "logo" ARRAY(OBJECT (DYNAMIC) AS (
         "alttext" STRING,
         "caption" STRING,
         "copyright" STRING,
         "created_at" STRING,
         "id" LONG,
         "location" STRING,
         "mimetype" STRING,
         "ref_attribute" STRING,
         "ref_id" LONG,
         "ref_sort" LONG,
         "ref_table" STRING,
         "self" STRING,
         "updated_at" STRING,
         "url" STRING
      ))
   ),
   "parent_id" INTEGER,
   "slug" STRING,
   "sort" INTEGER,
   "title" STRING,
   "updated_at" TIMESTAMP
)
```

`media` was only defined as DYNAMIC when creating the table, the rest of the structure was defined by crate automatically.

It's ok if you close this issue immediately because there are no reproducing steps. I just wanted to have that error logged here.

**Comment by joemoe** [comment]
hi @cweiske, thanks for reporting. we will look into this and keep you up to date.

**Comment by kovrus** [comment]
Hi @cweiske 

It looks like that the `media` data payload is not uniform. Possibly, it is represented in your raw data by both an array and object.

You can get data into CrateDB by using, for instance, `inserts` and `copy from`. The difference is that the first tries to validate new values against the defined schema or the one which has been dynamically created, which is not the case for [`copy from`](https://crate.io/docs/reference/sql/dml.html#import-export).

For example, you cannot do something like that with inserts:    
```
create table some table (id long, media as object(dynamic));
insert into sometable (id, media) values (1, {});
insert into sometable (id, media) values (1, [{}]); // fails, it validates the new values
```

But it is possible to achieve that with `copy from`, such as the values won't be validated:
```
create table sometable (id long, media as object(dynamic));
copy sometable from '/tmp/test.json';

> cat /tmp/test.json
{"id": 1, "media": {}}
{"id": 1, "media": [{}]}
```

When you attempt to select from this table, the query will fail, and the reason would be exactly the casting exception:

```select * from sometable;
SQLActionException[ClassCastException: java.util.ArrayList cannot be cast to java.util.Map]`
```

Have you imported you date with `copy from`? If it is the case, you would probably have to do something about your data or make the schema more strict.

**Comment by cweiske** [comment]
- No, I did not use `copy from`.
- But my code actually may have issues that data get imported as object once, and as array on another run. That's my fault indeed.

**Comment by kovrus** [comment]
@cweiske that actually should not be the case such as the schema creation is a synchronous operation.

**Comment by cweiske** [comment]
Ok, then let's close this issue since I cannot help any further with reproducing it.
