### ISSUE TITLE
Probably a bug: Inconsistent select results from different nodes

### ISSUE THREAD

**Issue by donnaMathilda** [crate/crate#4711]
Probably a bug: Inconsistent results from different nodes for queries like "select count(*) from table" while inserts into this table are still running

**CrateDB version**: We use docker images of crate
 latest Version: 1.0.2 (running in Docker version 1.12.6,) on AWS with Linux 

**JVM version**:  (In crate docker image) : openjdk version "1.8.0_111-internal"
OpenJDK Runtime Environment (build 1.8.0_111-internal-alpine-r0-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version / environment description**: ( in crate docker image): Linux 83a8b36761c0 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 Linux

**Problem description**:
Quering "select count(*) from XY" while inserting data into the table  XY produces inconsistent results on 3-nodes cluster.
SQL (run as script): 
select count(*) from alltables.kdwsuch_kurz_idx_shard;
select count(*) from alltables.kdwsuch_kurz_idx_shard;
select count(*) from alltables.kdwsuch_kurz_idx_shard;
select count(*) from alltables.kdwsuch_kurz_idx_shard;
select count(*) from alltables.kdwsuch_kurz_idx_shard;
select count(*) from alltables.kdwsuch_kurz_idx_shard
Results:
6632881  <- ok for the beginning
6506790  <- why, now less than before???
6506790  <- not refreshed, ok
6506790  <- still not refreshed
6645186  <- ah, some more data in, nice
6506790  <- whooot??  

Seems the nodes won't synchronize properly.  

**Steps to reproduce**:
1. create a 3-node cluster from docker containers 
docker run -d -p 4200:4200 -p 4300:4300 -p 5432:5432 --name hombre1 -v /home/centos/crateDB/data:/crate/data  -v /home/centos/crateDB/config:/config --ulimit nofile=65536 --ulimit memlock=9223372036854775807 --env CRATE_HEAP_SIZE=16g crate crate -Ccluster.name=crate-cluster -Cnode.name=hombre1 -Cpath.conf=/config
docker run -d --name hombre2 -v /home/centos/crateDB/data:/crate/data  -v /home/centos/crateDB/config:/config --ulimit nofile=65535 --ulimit memlock=9223372036854775807 --env CRATE_HEAP_SIZE=16g crate crate -Ccluster.name=crate-cluster -Cnode.name=hombre2 -Cpath.conf=/config
docker run -d --name hombre3 -v /home/centos/crateDB/data:/crate/data  -v /home/centos/crateDB/config:/config --ulimit nofile=65535 --ulimit memlock=9223372036854775807 --env CRATE_HEAP_SIZE=16g crate crate -Ccluster.name=crate-cluster -Cnode.name=hombre3 -Cpath.conf=/config
 
with crate.yml:
path.data: /crate/data
gateway.expected_nodes: 3
gateway.recover_after_nodes: 3
discovery.zen.minimum_master_nodes: 3
es.api.enabled: true

2. create a table with ca. 70 columns, mostly STRINGS, some TIMESTAMPS
3. create a big (some 15 mio rows) .json file with data to insert in the table
4. run "copy from .... " from crash tool
5. wait a moment to get some data into the table
6. using a SQL - tool (I use Squirrel with crate-jdbc-standalone-2.1.3.jar) run "select count(*) from yourtable" many times in a row
8. check results.

**Comment by matriv** [comment]
Hello @donnaMathilda 

CrateDB is eventually consistent which means that until you ``refresh`` the table you don't see consistent results. Please read the relevant documentation [here](https://crate.io/docs/reference/en/stable/sql/refresh.html).

**Comment by donnaMathilda** [comment]
Hi Marios,
Thank you for the promp answer.
But unfortunately refresh table doesn't really help. At least not always.
Imagine following situation: the crateDB is running in a production environment as a ReadDB.
The content is filled up from whatever source in irregular intervals. Not necessary very often.
An unlucky client (person or an application) browses the table which is updating right now. He will receive different results!
It would be OK, if the results were not exactly up to date, as long as they are consistent. But it could be fatal if they are just different depending on answering node.

Forcing a client to call refresh table before every single select can't be a solution, can it?
Nods must have some mechanism to be able to deliver the same "last synchronized" result, even though the result is not up to date (yet).
Imagine a financial application. Transactions of the day are loading  into cratedb. Just in this moment a client asks for sum of his account and gets first 10.000 then 9.000 then 9.340 and 9.000 again. That's just an example, maybe not the perfect one, but I can think of many other use cases where nervous changing results would be at least irritating.
Or am I completely wrong? Misunderstood the usage of crateDB? Please help me out .:-)
Best regards
Elena



On Tue, Jan 17, 2017 at 10:13 PM +0100, "Marios Trivyzas" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @donnaMathilda<https://github.com/donnaMathilda>

CrateDB is eventually consistent which means that until you refresh the table you don't see consistent results. Please read the relevant documentation here<https://crate.io/docs/reference/en/stable/sql/refresh.html>.

**Comment by joemoe** [comment]
hi @donnaMathilda, we will take a look into your case. but CrateDB is a database that can handle tons of events in the machine data field. we will probably never operate as an accounting database for the financial industry, but we are there to provide fast results on hot data.

**Comment by mfussenegger** [comment]
> Forcing a client to call refresh table before every single select can't be a solution, can it?
Nods must have some mechanism to be able to deliver the same "last synchronized" result, even though the result is not up to date (yet).

Calling refresh isn't the solution - it would kill the performance.

The docs about [optimistic concurrency control](https://crate.io/docs/reference/sql/occ.html?highlight=_version) might be of interest.
