### ISSUE TITLE
Support for Views?

### ISSUE THREAD

**Issue by Ragin666** [crate/crate#4759]
**Use case**: Support for Table Views

**Feature description**:

I want to have some data normalization because of massive repeated data.
But if you want to use Metabase with such normalized tables you cannot use joins. At the end of the day they say that you need to add Views to get full access to all the data in your database.

Is there a chance for support of Table Views?

**Comment by tqyq** [comment]
+1

**Comment by cmdares** [comment]
+1

**Comment by on99** [comment]
+1

**Comment by matriv** [comment]
Support for views has been added. It is already available in `3.0.0` release.
