### ISSUE TITLE
insert by query causes system to hang

### ISSUE THREAD

**Issue by bmwmaestoso** [crate/crate#4772]
**CrateDB version**: 1.0.1

**JVM version**: OpenJDK 64-Bit Server build 1.8.0_112-b15

**OS version / environment description**: 
all OS instances are:
Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP
8 CPUs
64G mem

1 Crate client
3 Crate nodes

**Problem description**:
I am trying to copy the contents of one table to another using the insert by query command. The source table has over 90 million entries. When I tried the copy, about 5 million entries were copied before the system became unresponsive. Any attempt to connect to the database would just hang. After 20 minutes, I had to restart all of the nodes and client. All of the nodes indicated that there was no disk or cpu activity.

I am going to try to disable updates to replicas while it is populating the table and see if this will resolve the problem. I am also going to try smaller tables to see if the problem still occurs.

**Steps to reproduce**:
- create and populate a table with 10 million entries
- execute the insert from query

This is the table I am using but I suspect any table will probably cause the problem to occur.

CREATE Table query {
gm string PRIMARY KEY,
domain string PRIMARY KEY,
qid string PRIMARY KEY,
user string PRIMARY KEY,
ts timestamp PRIMARY KEY,
cn string,
audit string INDEX OFF,
batch long NOT NULL,
beginDate timestamp INDEX OFF,
endDate timestamp INDEX OFF,
duration long,
durationBegin timestamp INDEX OFF,
durationEnd timestamp INDEX OFF,
qlimit long INDEX OFF,
latest string INDEX OFF,
name string INFEX OFF,
project string INDEX OFF,
status string,
target string INDEX OFF,
qType string INDEX OFF,
resultCount long,
proxdEntities string INDEX OFF,
proxiedIssuers string INDEX OFF,
baseTime timestamp,

INDEX IdxUserID using fulltext(cn, domain, user),
INDEX IdxStatus using fulltext(cn, domain status)
) CLUSTERED INTO 15 shards
with (column-policy = 'strict',
number_of_replicas = '0-all');

**Comment by bmwmaestoso** [comment]
I set the number of replicas to 0 and this seems to have resolved the problem.  It seems to be running just fine but it is not close to being done just yet.

**Comment by mfussenegger** [comment]
Hi, thanks for the report.
Two more questions:

What's the heap size? (Set via CRATE_HEAP_SIZE environment variable)
Are there any warnings/errors in the logs?

**Comment by bmwmaestoso** [comment]
Setting the number of replicas to 0 did not resolve the problem. All it did was allow more entries to be inserted into the target table before it went in an unresponsive state. I am not familiar with the GC format of OpenJDK but it appears that the system is under heavy major GC. It seems as if all GCs are major GCs with a duration greater than 1minute and it doesn't appears to recover much data. Here is a sample from /var/log/messages:

duration[1m], collections [1]/[1m], total [1m/14.2m], memory [29.7gb]->[29.8gb]/[29.9gb], all_pools {[young] [422.2mg]]->[532.5mg]}{[survivor] [0b]->[0b]/66.5mg]}}{[old] [29.3gb]/[29.3gb/[29.3gb]}

I am much more familiar with the HotSpot JVM but Crate seems to automatically pick the OpenJDK. I could see what happens if I change the configuration to use the HotSpot JVM but it shouldn't matter.

**Comment by bmwmaestoso** [comment]
Th CRATE_HEAP SIZE is set to 30g on all of the nodes. However, on the client it is set to 10g. Eventually, the insert by query request caused an OOM condition on the client. The client does not have anything in the crate logs or /var/log/messages. I believe the problem is related to the number of GC threads on the nodes. I forced a thread dump and from what I can see there are:

41 total threads
37 elasticsearch threads
3 compiler threads
1 service thread

I have to assume that the single service thread is the GC thread. The HotSpot JVM specifically labels these threads. I may just switch to the HotSpot JVM unless there is a specific reason why Crate should use the OpenJDK on Linux. I have tried to enable GC loggin by setting CRATE_USE_GC_LOGGING but some of the JVM args set for logging are not valid for the OpenJDK and Crate fails to start. Looking at the GC JVM parameters that are set in crate.in.sh I see:

-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC

If the OpenJDK JVM accepts these JVM arguments, there should be more GC threads.

**Comment by mfussenegger** [comment]
You mentioned in the other issue (https://github.com/crate/crate/issues/4697) that you've set the thread_pool size to unlimited. Is this still the case?
That could be a cause for the OOM as the queue can then grow unbound and our insert-from-query throttle mechanism won't work.

**Comment by bmwmaestoso** [comment]
Yes, it is still set to unlimited. I can reset these values and try again. However, I am wondering how many people are using the OpenJDK. Even though the OpenJDK is an rpm for Linux, most projects here us the Oracle HotSpot JVM. Seems to me that the OpenJDK is not creating GC threads based upon the JVM arguments. There is another project here that is using Crate and I will ask them which JVM they are using but they usually don't get in to work for a few hours.

**Comment by bmwmaestoso** [comment]
I have changed the queue sizes and it seems to be working properly. So far the insert has well past the location where it had the problem. I am monitoring the log files as well as the the cpu/disk on each of the nodes. So far there are no messages in /var/log/messages for the jvm. I can see the heap usage from crate console and it seems to varying between 10-20g.

I was also able to generate another thread dump and see all of the GC threads. I don't know why they weren't in the original thread dump.

**Comment by bmwmaestoso** [comment]
The target table now has 85 million of the 91 million from the source table. Setting the queue size seems to have fixed the problem. No warning messages in /var/log/messages or any entries in the crate logs.
