### ISSUE TITLE
crate.client.exceptions.ProgrammingError: Invalid server response of content-type 'unknown'

### ISSUE THREAD

**Issue by kietly** [crate/crate#4806]
**CrateDB version**:
1.0.2
**JVM version**:
1.8.0u111
**OS version / environment description**:
Amazon Linux, Kernel 3.3 
**Problem description**:
If I changed http port 4300 or transport port (4200) to different port then this exception is thrown
crate.client.exceptions.ProgrammingError: Invalid server response of content-type 'unknown'
Restore to the default port (4200/4300) then there is no issue.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment]
Hi, can you elaborate a bit on how you produce that error? 

>If I changed http port 4300 or transport port (4200)

This seems mixed up. 
Http defaults to 4200
Transport defaults to 4300

**Comment by mfussenegger** [comment]
Closing this, if this is still a problem feel free to re-open the issue
