### ISSUE TITLE
sum aggregation on timestamp

### ISSUE THREAD

**Issue by floggi83186** [crate/crate#4819]
Hi there,

the documentation for version 1.0.2 states that it should be possible to us the aggregation **sum** on numeric and timestamp columns. Works fine on numeric columns, but when used on a timestamp column an **UnsupportedFeatureException** is thrown.

I just wanted to know "who is wrong"

**Comment by joemoe** [comment]
hi @floggi83186, we will look into this.

**Comment by chaudum** [comment]
hi @floggi83186 I'd like to hear your use-case of summing up timestamps. I can see there's a use case for other aggregations such as `avg` or `min` or `max`.

**Comment by floggi83186** [comment]
Hi @chaudum.

Well, my use-case is to create a frontend where you can "click" your querie together, and to give the user all possibilities (aggregations, operators, where/having, grouping, scalar functions etc.) depending on the column. And I use the documentation to know "what is possible".  
So I don't really know if there is a user that has a special use-case where he could use that. In respect to timestamps, I can only think of an aggregation like sum(endtime-starttime), what works.

So my "problem" is that the documentation states that it should be possible, but it's not. So I'm fine if the documentation is wrong and gets corrected or the other way round.

**Comment by chaudum** [comment]
@floggi83186 I see your point.
the documentation is incorrect and we will update it. `SUM()`aggregation is only possible with primitive numeric types, whereas `MIN()`, `MAX()` for example are possible with all primitive types.

**Comment by floggi83186** [comment]
@chaudum Thanks!

**Comment by mfussenegger** [comment]
@chaudum what's the state here? Did we fix the docs?

**Comment by chaudum** [comment]
@mfussenegger @floggi83186 seems like this slipped under the radar. I will make sure this is is tracked and gets done asap.

**Comment by christianbader** [comment]
@floggi83186 we updated the documentation regarding this issue.
Thanks for pointing it out!
