### ISSUE TITLE
Ability to set a ttl to a table

### ISSUE THREAD

**Issue by bputt** [crate/crate#4828]
**Use case**: It would be helpful to setup a ttl to a table to help remove data after a certain period of time.

**Feature description**: When creating a table, specifying a ttl (in seconds) that data would get removed after being inserted/updated. Got the inspiration from cassandra's documentation :)

**Comment by joemoe** [comment]
hi @bputt, we were discussing something like this recently and have already implemented things that will make this possible, however we don't have an eta yet. i will keep you posted.
thanks for reporting.

**Comment by mfussenegger** [comment]
Closing this for now, see https://github.com/crate/crate/issues/6877#issuecomment-654709694
