### ISSUE TITLE
Order By on Group Bys with Partitioned Column Key not working

### ISSUE THREAD

**Issue by burnes** [crate/crate#4835]
**CrateDB version**: 1.0.2

**JVM version**: 8

**OS version / environment description**: Lovely Crate Cluster

**Problem description**:

Order by month partition

UnsupportedOperationException[cannot use partitioned column month in ORDER BY clause]

**Steps to reproduce**:

CREATE TABLE test (
	ts TIMESTAMP,
    month TIMESTAMP GENERATED ALWAYS AS date_trunc('month', "ts"),
    value STRING
) 
PARTITIONED BY ("month");

INSERT INTO test (ts, "value") values ('2016-01-01', 'A');
INSERT INTO test (ts, "value") values ('2016-02-01', 'B');

SELECT month, count(*) FROM test
GROUP BY month 
ORDER BY month;

**Use case**:

Displaying diagrams with aggregations per month

**Feature description**:

**Comment by bogensberger** [comment]
Hey @burnes, thanks for reporting.

I removed that limitation and backported the change to our 1.0 branch, so it should be released with 1.0.4
Here is the commit: https://github.com/crate/crate/commit/5270ce9d2a117ea9886f294013c6332f44d9dd2a
