### ISSUE TITLE
Query priority

### ISSUE THREAD

**Issue by bputt** [crate/crate#4837]
**Use case**: Set the priority of queries that modify data

**Feature description**: When I issue an update statement and it may affect a large number of rows, it would be great if I could set the priority. The idea is to allow expected long running queries to be ran in the background without causing noticeable performance degradation.

```UPDATE TABLE SET colA = someVal priority=2;```

**Comment by joemoe** [comment]
hi @bputt, thanks for your suggestion. we put it on the backlog. i'll keep you up to date.
