### ISSUE TITLE
Date_trunc and having

### ISSUE THREAD

**Issue by burnes** [crate/crate#4856]
**CrateDB version**:
1.0.2

**JVM version**:
8

**OS version / environment description**:
OSX/Linux

**Problem description**:

A valid query with `date_trunc` and `having` returns the following error stacktrace:

Error!

SQLActionException[SQLParseException: Cannot use column timestamp outside of an Aggregation in HAVING clause. Only GROUP BY keys allowed here.]

**Steps to reproduce**:

```sql
CREATE TABLE events_kuenz (
    thing STRING,
    timestamp TIMESTAMP
);
SELECT date_trunc('quarter', 'Europe/Vienna', event."timestamp")
FROM "events_kuenz" AS "event"
GROUP BY date_trunc('quarter', 'Europe/Vienna', event."timestamp")  
HAVING   date_trunc('quarter', 'Europe/Vienna', event."timestamp") > 1481127360000 
ORDER BY date_trunc('quarter', 'Europe/Vienna', event."timestamp") ASC limit 100;
```

**Comment by burnes** [comment]
Same error message also appears on  a  group by/having with an arithmetic function.

**Comment by seut** [comment]
@burnes 
Thanks for reporting. We've fixed this by https://github.com/crate/crate/commit/d8b09e37185eb17dce23173c13b6e4a9c481b99d, it will be part of the next hotfix release.

**Comment by burnes** [comment]
@seut Nice, have you also checked for arithmetics as this also made problems?
 
```
SELECT value_a * value_b
FROM table
GROUP BY value_a * value_b
HAVING value_a * value_b < 10
```

**Comment by seut** [comment]
@burnes the issue was related to any scalar function, so yes arithmetics will work as well.
