### ISSUE TITLE
Restore of partitioned table failed with TableUnknownException

### ISSUE THREAD

**Issue by tellezb** [crate/crate#4872]
**Environment**
Crate 1.0.2
Amazon Linux AMI 2016.09.0.20160923 x86_64 HVM GP2
3 AWS t2.micro nodes

**Snapshot strategy**
A new snapshot is made every evening to a S3 repository named openeye_devmon_test.

**Problem description**:
I attempted to restore a partitioned table (Alert) from a snapshot using the following syntax:

> RESTORE SNAPSHOT openeye_devmon_test.openeye_devmon_test_1486575002087 table openeye_devmon_test.alert WITH (wait_for_completion=true);

and received the following exception:

> TableUnknownException: Table 'openeye_devmon_test.alert' unknown

After receiving this error I attempted to restore all tables (including Alert) from the snapshot, which was successful:

> RESTORE SNAPSHOT openeye_devmon_test.openeye_devmon_test_1486575002087 ALL WITH (wait_for_completion=true);

**Details of the repository:**

{"bucket":"crate-snapshot-storage","secret_key":"<secret_key_is_here>","base_path":"/OE-CRATE/openeye_devmon_test","server_side_encryption":"false","compress":"true","access_key":"<access_key_is_here>"}

**Details of the snapshot:**

![image](https://cloud.githubusercontent.com/assets/7115725/22796185/41ca83ae-eeae-11e6-8c82-58ef3e8ba100.png)

with concrete_indices:

["openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c9d64q0","openeye_devmon_test..partitioned.alert.045j4c1h6smj0chd60og","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6omj2chd60og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c9d68og","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c9d60rg","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6omj2c9d60og","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0c9d60p0","openeye_devmon_test..partitioned.camera_status_image.045j4c1h6omj2c1d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0c9d6co0","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c1d6cog","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6smj0chd60og","openeye_devmon_test.schema_version_lock","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.alert.045j4c1h6omj2chd60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2chd68r0","openeye_devmon_test.reference_image","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6omj2c1d60og","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2chd64p0","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6omj0e1d60og","openeye_devmon_test.active_device_event","openeye_devmon_test..partitioned.alert.045j4c1h6omj2c9d60og","openeye_devmon_test..partitioned.alert_summary_by_day.045j4c1h6omj2c9d60og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0chd60r0","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0c9d68pg","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c9d68s0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2chd64sg","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c1d64rg","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0c9d64r0","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0c9d60sg","openeye_devmon_test..partitioned.alert_summary_by_day.045j4c1h6smj0chd60og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2chd68r0","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2chd60qg","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c9d68s0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0c9d60sg","openeye_devmon_test.notification_data","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c1d68q0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0c9d60p0","openeye_devmon_test..partitioned.alert.045j4c1h6gmj0c9d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c9d60rg","openeye_devmon_test..partitioned.alert_summary_by_day.045j4c1h6omj2chd60og","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2chd64sg","openeye_devmon_test..partitioned.device_event.045j4c1h6omj0e1d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2chd64p0","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0chd60r0","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6omj0e9d60og","openeye_devmon_test..partitioned.camera_status_image.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6omj2c9d60og","openeye_devmon_test..partitioned.alert.045j4c1h6omj2c1d60og","openeye_devmon_test..partitioned.alert_summary_by_day.045j4c1h6omj2c1d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6cmj2chd6co0","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0c9d68pg","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6omj2chd60og","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0c9d60sg","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0c9d64r0","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6smj0chd60og","openeye_devmon_test..partitioned.camera_status_image.045j4c1h6smj0chd60og","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c9d68og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2chd60qg","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2chd68r0","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c9d64q0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c1d68q0","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0c9d60p0","openeye_devmon_test.camera_status_most_recent_image","openeye_devmon_test..partitioned.camera_status_image.045j4c1h6omj2c9d60og","openeye_devmon_test..partitioned.system_metric_summary_by_day.045j4c1h6omj2c1d60og","openeye_devmon_test..partitioned.system_metric.045j4c1h6smj0c9d6co0","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c1d6cog","openeye_devmon_test..partitioned.notification.045j4c1h6smj0chd60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c9d68og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2chd64p0","openeye_devmon_test..partitioned.alert_device_events.04cj4c1h6smj0c9d60ol8c1g78o30ehg60n30c1gb8","openeye_devmon_test..partitioned.alert_device_events.045j4c1h6gmj0c9d60og","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2c1d68q0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0c9d6co0","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c9d64q0","openeye_devmon_test..partitioned.system_metric.045j4c1h6omj2chd64sg","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c9d60rg","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6cmj2chd6co0","openeye_devmon_test..partitioned.device_event.045j2e9m74mj2chd68sg","openeye_devmon_test..partitioned.device_event.045j4c1h6smj0chd60r0","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0c9d68pg","openeye_devmon_test..partitioned.device_event_alerts.04cj4c1h6smj0c9d60sl8c1g78o30ehg60n30c1gb8","openeye_devmon_test.schema_version","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6smj0c9d64r0","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2c1d64o0","openeye_devmon_test.system_most_recent_metric","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c1d6cog","openeye_devmon_test..partitioned.alert_summary_by_day.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.camera_status_image.045j4c1h6omj2chd60og","openeye_devmon_test..partitioned.notification.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.device_event.045j4c1h6omj2chd60qg","openeye_devmon_test..partitioned.alert.045j4c1h6smj0c9d60og","openeye_devmon_test..partitioned.device_event_alerts.045j4c1h6omj2c9d68s0"]

**Comment by m-kharbat** [comment]
Hi @tellezb ,
is `openeye_devmon_test` your schema name too ? if it's not then the correct syntax is:

```RESTORE SNAPSHOT openeye_devmon_test.openeye_devmon_test_1486575002087 table alert WITH (wait_for_completion=true);```

**Comment by tellezb** [comment]
Thanks for the feedback. The schema name is `openeye_devmon_test`. You can see the schema name in the snapshot's concrete_indices list.

**Comment by bogensberger** [comment]
HI @tellezb, could you please try to restore the table again with setting the `ignore_unavailable` option to `true` while i'm investigating further?

**Comment by tellezb** [comment]
Since I'm using a newer snapshot I tested the restore without the `ignore_unavailable` option (like before):
> RESTORE SNAPSHOT openeye_devmon_test.openeye_devmon_test_1487179801271 table openeye_devmon_test.alert WITH (wait_for_completion=true);

**Failed.** TableUnknownException: Table 'openeye_devmon_test.alert' unknown.

Then I added the `ignore_unavailable` option:

> `RESTORE` SNAPSHOT openeye_devmon_test.openeye_devmon_test_1487179801271 table openeye_devmon_test.alert WITH (wait_for_completion=true, ignore_unavailable=true);

**Success.** The partitioned table has been restored.

**Comment by bogensberger** [comment]
Hi @tellezb, i fixed that issue so it's  now possible to restore a full partitioned table without running into this error: https://github.com/crate/crate/commit/3da6bb4adb33d0846ecaa943e3f6524b1e465cb0

The fix will be available with the next crate release. Thanks for reporting.
