### ISSUE TITLE
Generated column with `current_timestamp` does not change value on UPDATE

### ISSUE THREAD

**Issue by tellezb** [crate/crate#4883]
Crate 1.0.2
Amazon Linux AMI 2016.09.0.20160923 x86_64 HVM GP2

Table definition:

> CREATE TABLE IF NOT EXISTS "doc"."test" (
>    "id" LONG,
>    "inserted" TIMESTAMP GENERATED ALWAYS AS current_timestamp(3),
>    "message" STRING
> )

**Problem description**:

According to documentation, generated columns "are computed upon INSERT and UPDATE":
[Generated Columns](https://crate.io/docs/reference/sql/ddl.html#generated-columns)

This is not the current case for generated columns with `current_timestamp`. UPDATE does not compute a new value for the column.

**Steps to reproduce**:

> insert into test (id, message) values (1, 'test');

Record after insert:
![image](https://cloud.githubusercontent.com/assets/7115725/22834920/b4564602-ef6b-11e6-98d3-21e89916352b.png)

> update test set message = 'test update';

Record after update:
![image](https://cloud.githubusercontent.com/assets/7115725/22834938/c96b9664-ef6b-11e6-9024-b0d928a97303.png)

`inserted` column has the same value as before. The UPDATE statement should have updated the value to the timestamp of the UPDATE.

**Comment by mfussenegger** [comment]
Thanks for reporting, we'll take a look at it

**Comment by kovrus** [comment]
Hi @tellezb, the fix for this issue will be available in the next hotfix release.

Thanks for reporting!

**Comment by joemoe** [comment]
hi @tellezb, this fix is now out in 1.0.4.
https://github.com/crate/crate/blob/1.0/CHANGES.txt#L39-L41
