### ISSUE TITLE
Table Copy Behaviour

### ISSUE THREAD

**Issue by burnes** [crate/crate#4919]
**CrateDB version**: 1.0.3

**JVM version**: 8

**OS version / environment description**: OSX

**Problem description**:

If null values are explicitely set on dynamic columns you can't see them on the table schema. Furthermore the table copy (with an insert statement with select) does not throw an exception, but fails silently. Only the Crate logs show the exception:

`ShardUpsert Item 0 failed: Failure{id=AVpGYof2y6LlAQTMBWdi, message=StrictDynamicMappingException[mapping set to strict, dynamic introduction of [c] within [data] is not allowed], versionConflict=false}`

Want to use strict mapping for a table and therefore copied the table into another table. Actually I just realized that this went wrong by checking the count of total rows and the error message in the Crate logs.

Don't know if this is a bug, but maybe the user should be informed about that somehow.

**Steps to reproduce**:

CREATE TABLE c (data OBJECT(DYNAMIC) AS (a STRING));
INSERT INTO c (data) VALUES ({a='test'});
INSERT INTO c (data) VALUES ({a='test3', b=null});
SHOW CREATE TABLE c;
CREATE TABLE d (data OBJECT(STRICT) AS (a STRING));
INSERT INTO d (data) (SELECT data FROM c);

SELECT * FROM d limit 100;

**Comment by seut** [comment]
@burnes 
Do the `rows affected` number reflect the successfully inserted items? If so, then this is not a but but expected behaviour. Returning an error to the user would leave the user in an unknown state about how much documents were written...

**Comment by burnes** [comment]
The row count is one. Actually there's no information about that anything went wrong. Maybe it's the user's responsibility to check the number of total rows in the source table first.

INSERT OK.
{"cols":[],"rows":[[]],"rowcount":1,"duration":5.636081}

**Comment by seut** [comment]
Yes. Consistency knowledge here has a higher precedence than the reason of a failure. One must always rely on the row count. Only if 1 document is known to be affected (which is never the case for insert-by-query, but single inserts and primary key updates), the failure reason will be responded.
