### ISSUE TITLE
Admin UI Read only permissions

### ISSUE THREAD

**Issue by bputt** [crate/crate#4921]
**Use case**: Limiting who can add/modify data via the admin ui

**Feature description**: Let's say we have a proxy in front of Crate for the admin ui and authentication is done at that layer. Nginx could use proxy_pass to provide a parameter that Crate is looking for to enforce read only.

I would make this an optional enforcement...If a parameter was passed in via the proxy, you would honor it, otherwise, you'd let the user access Crate like they do today. Example: I have a cluster, all my nodes are using stunnel, so in order to issue HTTP API commands, I'd need a cert. Nginx would be used as an authentication mechanism to provide access to the admin ui, and I'd only need access controls to be enforced at this level.

**Comment by chaudum** [comment]
hi @bputt 
you can use the `node.sql.read_only` [setting](https://crate.io/docs/reference/configuration.html#read-only-node) on the node you run the admin ui on. if set to `true` the node  (and therefore also the admin ui) will only allow SQL statements which are resulting in read operations.

**Comment by bputt** [comment]
Thanks, that'll work just nice

**Comment by chaudum** [comment]
and as you've also already mentioned it is also possible to proxy pass the http endpoint
you can look at https://crate.io/a/readonly-crate-with-nginx-and-lua/ if you are interested.
