### ISSUE TITLE
Problem with initiating crash

### ISSUE THREAD

**Issue by varshithr** [crate/crate#4930]
**CrateDB version**:
1.2
**JVM version**:
1.8.0_121
**OS version / environment description**:
Ubuntu 16.04
**Problem description**:
We were trying to initiate crash terminal, but we were getting a syntax error

**Steps to reproduce**:
Step 1: start crate service
Step 2: run crash
Step 3 : See the error

![selection_004](https://cloud.githubusercontent.com/assets/5567676/23118487/5b9a28f0-f77a-11e6-9980-264936f81378.png)

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
hi @varshithr what python version is installed?

**Comment by varshithr** [comment]
Its Python 2.7.13



Thanks and Regards
Varshith Ramachandra Manchikanti
Mob : +91- 7416-760-120

**Comment by chaudum** [comment]
thanks, we'll have a look!

**Comment by mikethebeer** [comment]
@varshithr thanks for reporting. This issue has been fixed and it will be available on the next upcoming release of CrateDB.
