### ISSUE TITLE
Cast operation not working as expected

### ISSUE THREAD

**Issue by bputt** [crate/crate#4986]
**CrateDB version**: 1.0.2

**JVM version**: 1.8.0_92-b14

**OS version / environment description**: CentOS 7

**Problem description**:
When executing the query below, I'd expect the statement to work as it appears to be a valid expression.

Error:
```
SQLActionException[UnsupportedFeatureException: op_isnull predicate cannot be selected]
```

**Steps to reproduce**:

SQL statement:
```
SELECT count(*), cast(columnA is not null as boolean) as colA FROM table GROUP BY colA;
```

Table:
```
CREATE TABLE table (
    columnA STRING
);
```

This SQL statement doesn't throw an error, but doesn't return the results that I'm expecting
```
SELECT count(*), cast(columnA != null as boolean) as colA FROM table GROUP BY colA;
```

**Comment by joemoe** [comment]
hi @bputt, we don't allow `is not null` in select statements at the moment. 

one option could be this:
```
select count(*), columnA = 'a string that doesnt occur' as colA from table group by colA;
```

**Comment by joemoe** [comment]
hi @bputt, predicates in select lists will be supported in 1.1.0.
