### ISSUE TITLE
Postgre SQL error code support

### ISSUE THREAD

**Issue by w-p** [crate/crate#5027]
**CrateDB version**: 1.0.3

**JVM version**: ?

**OS version / environment description**: Ubuntu 16.10, Docker 1.12.6

**Problem description**: Error information is not correctly returned when using the node [pg](https://github.com/brianc/node-postgres) library. The non-native driver's `code` field and the native driver's `sqlState` field are always `XX000`.
```
{ Error: ERROR:  SQLParseException: line 1:20: mismatched input '<EOF>' expecting '('

    at Client._readError (/data/projects/forklift.js/node_modules/pg-native/index.js:80:13)
    at Client._read (/data/projects/forklift.js/node_modules/pg-native/index.js:121:19)
    at emitNone (events.js:86:13)
    at PQ.emit (events.js:185:7)
  severity: 'ERROR',
  sqlState: 'XX000',
  messagePrimary: 'SQLParseException: line 1:20: mismatched input \'<EOF>\' expecting \'(\'',
  sourceFile: 'Exceptions.java',
  sourceLine: '168',
  sourceFunction: 'esToCrateException' }
```

**Steps to reproduce**: Send anything that generates an error via Postgre.

**Comment by joemoe** [comment]
hi @w-p, thanks for your issue. we'll add this to our backlog. we are constantly working on improving our postgres support. cheers, johannes

**Comment by mfussenegger** [comment]
Are there any specific codes that would help? There are quite a lot of error codes in postgres (https://www.postgresql.org/docs/9.4/static/errcodes-appendix.html ) and we probably don't always have a clean 1:1 mapping

**Comment by w-p** [comment]
Understood, I don't expect a 1:1. However anything is better than `sqlState: 'XX000'` for every error. Personally, I'd like connection, data, and statement errors but I realize that this constitutes a lot of work. We don't need to have PG error codes specifically. Any set of documented, identifiable error codes would suffice.  Trying to parse the `messagePrimary` field, while doable, seems a bit... hacky.
