### ISSUE TITLE
Hope to add new data type(s) to support exact results when applying sum or avg aggregate functions.

### ISSUE THREAD

**Issue by Danthunder** [crate/crate#5030]
**Use case**:
Hope to add new data type(s) to support exact results when applying sum or avg aggregate functions. Thanks
**Feature description**:
Hope to add new data type(s) to support exact results when applying sum or avg aggregate functions. Thanks

**Comment by seut** [comment]
Your description is not really clear to us, our aggregations always return exact results. Can you describe this more detailed please?

**Comment by Danthunder** [comment]
In "DATA TYPES" section in the crate's reference (https://crate.io/docs/reference/sql/data_types.html#numeric-types). The "float" and "double" data types are inexact, variable-precision numeric types.  The result of applying sum or avg aggregate functions may slightly vary between query.   So, are there any alternative ways to return exact results when applying aggregate functions with numeric data types like "double" ?      Thanks~~

**Comment by seut** [comment]
Ah yes, we're currently missing a arbitrary precision numeric type like postgres's decimal type (https://www.postgresql.org/docs/9.6/static/datatype-numeric.html). We'll put it on our backlog. Any contributions are always welcome. If you need some help, please for it on our slack channel.

**Comment by mfussenegger** [comment]
We added a `numeric` type that can be used in the context of aggregations (at runtime) (See https://github.com/crate/crate/pull/10854).

We also made a change to use the kahan summation algorithm to have more accurate sums. (See https://github.com/crate/crate/pull/10674)

Having a numeric type where a user can configure the precision is tracked via https://github.com/crate/crate/issues/11119.
