### ISSUE TITLE
CrateDBAdmin UI re-orders json object properties

### ISSUE THREAD

**Issue by cweiske** [crate/crate#5035]
**CrateDB version**: 1.0.4

**JVM version**: 1.8.0_121

**OS version / environment description**: Official crate/crate docker image

**Problem description**:

CrateDBAdmin re-orders data in nested/JSON columns so they appear different than they are actually stored in the database. It would be better if it showed the original data as they are coming from crate.

In our case the `media` is of type object and has properties 0, 1, 2, ... 11 that are itself objects (I know that we should use an array instead. We didn't.)

As seen on the screenshot, crate returns property `11` first, but CrateDBAdmin shows property `0` first.
This makes debugging issues very hard; I had to resort to Wireshark to see how crate actually orders the property.

![2017-03-03 create webinterface reorders](https://cloud.githubusercontent.com/assets/59036/23553978/6b22726c-0023-11e7-8008-0d618701b2ff.png)

**Comment by chaudum** [comment]
hi @cweiske ,

when selecting `*` or an object (= no specific order) the columns are returned in their ordinal position. the ordinal position can be determined by querying the information schema:

```sql
SELECT column_name, ordinal_position
FROM information_schema.columns
WHERE table_name = 'production_producerdb_news';
```

with Javascript the properties order objects is not guaranteed, however, when displayed/stringified again, the keys are usually (but also not guaranteed) sorted in ascending order, in your case starting with `0`. wireshark may have a different implementation of how to de-serialize JSON strings (the response from CrateDB) and therefore can display the "object" differently.

if in doubt, you should change your query to

```sql
SELECT media['0'], media['1'], ... FROM production_producerdb_news;
```

**Comment by cweiske** [comment]
Wireshark has nothing to do with it; it displays the data as they are coming from crate. Manually curling crate also gives the same result (`11` first).

I'm just wondering why cratedbadmin is parsing the fields if it only displays them as json string anyway. This seems superfluous to me.

**Comment by chaudum** [comment]
I have to correct myself: "subcolumns" of objects do not have ordinal positions, since an object is a map which does not have a deterministic ordering of its keys. the "order" you get from CrateDB is just the way Java dumps the map to JSON.

we discovered a bug that the `information_schema.columns` is actually listing an ordinal position, but this is wrong and we will both fix this and update the documentation.

**Comment by cweiske** [comment]
> an object is a map which does not have a deterministic ordering of its keys

This is an explanation I can accept :)

**Comment by joemoe** [comment]
closed because of accepted explanation.
