### ISSUE TITLE
excuse me, when i killed any one of the two clients, another client can not provider read and write services ?

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#5038]
**CrateDB version**: crate-1.0.1

**JVM version**: 1.8.0_111

**OS version / environment description**: CentOS 6.2

**Problem description**:
hello, there are two clients in my CrateDB cluster which configured by "node.master: true, node.data: false". But when i killed any one of the two clients, another client can not provider service, causing the cluster to provide read and write services failed. maybe a bug in crate-1.0.1 ?

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @aaronhadoop,

can you provide more details on the following questions:

* so you're running two nodes, which are accessed by your clients?
* when you take one of the cluster, the other doesn't respond anymore?
* how many nodes do you have in total?
* what does "can not provide service" mean? is there an error on the client? is there a timeout? how does CrateDB answer?

cheers, johannes

**Comment by joemoe** [comment]
hey @aaronhadoop, do you have more information on the issue? otherwise i'd close it and you can open a new one whenever you're able to provide more insights.
cheers, 
johannes

**Comment by joemoe** [comment]
@aaronhadoop i'm closing this for now. feel free to reopen it, whenever you have feedback for us.
