### ISSUE TITLE
excuse me, is there a faster method to get the number of records and the capacity of the table

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#5045]
**CrateDB version**: crate-1.0.4

**JVM version**: 1.8.0_111

**OS version / environment description**: CentOS 6.2

**Problem description**:
hello, is there a faster method to get the number of records and the capacity of the table from sys table ? getting the result, like "table1, 1000000, 2.6GB", 

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @aaronhadoop, no we don't support something like this at the moment. to only way is to use `sum`. cheers, johannes

**Comment by seut** [comment]
I guess you mean: `SELECT schema_name, table_name, sum(size), sum(num_docs) FROM sys.shards GROUP BY 1, 2;`

**Comment by joemoe** [comment]
@seut thanks for making it explicit.

**Comment by aaronhadoop** [comment]
yeah, thank you !
