### ISSUE TITLE
Fatal crash on 1.0.4

### ISSUE THREAD

**Issue by rps-v** [crate/crate#5078]
**CrateDB version**: 1.0.4

**JVM version**: 25.121-b13 (JRE: 8.0_121-b13)

**OS version / environment description**: Windows Server 2012 R2

**Problem description**: Fatal crash

Log:
[hs_err_pid9872.log.txt](https://github.com/crate/crate/files/838292/hs_err_pid9872.log.txt)

NOTE: There is an additional .mdmp file (~700mb) if needed

**Steps to reproduce**:

Unfortunately I do not have any logs of what was executing (SQL-wise), just the crash log.

**Comment by joemoe** [comment]
hi @rps-v, we will investigate this.

**Comment by mikethebeer** [comment]
@rps-v it seems that this is a bug in Sigar, a plugin that we use for cpu and memory monitoring. Can you tell us when this crash happens (on heavy load, etc.) ? 

A workaround would be if you remove the `sigar` directory from the plugins located in `$CRATE_HOME/plugins/`. We encountered a bug that prevents you from starting a node after removing the folder (see https://github.com/crate/crate/commit/408c6a117d555b3782dfd2db6891f5e8fbe49efb). In your case you need to remove the sigar-path as shown in the commit manually in your `crate.bat`.

**Comment by rps-v** [comment]
@mikethebeer
It was a one time crash and it happened overnight (should have been very light / no load on the server).
The setup was a machine running 2 instances of Crate (a cluster with 2 nodes).

Here is a snippet from the logs at the moment of the crash (doesn't contain much):
[crate.log.txt](https://github.com/crate/crate/files/843990/crate.log.txt)

Thanks for the quick response and workaround, will report back if it happens again !

**Comment by mikethebeer** [comment]
@rps-v thanks, tell us if it happens again 👍 probably it has something to do with https://github.com/hyperic/sigar/issues/77
