### ISSUE TITLE
Please optimise aggregation algorithm for [query] Data too large

### ISSUE THREAD

**Issue by tqyq** [crate/crate#5082]
**CrateDB version**: 1.0.3

**JVM version**: java version "1.8.0_121" Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13)

**OS version / environment description**: Linux - 3.13.0-100-generic (amd64)
memory: 4G, CPU:4core

**Problem description**:

```
cr> select sum(cost),province,age from user_buy group by province,age;
SQLActionException[CircuitBreakingException: [query] Data too large, data for [collect: 0] would be larger than limit of [582706790/555.7mb]]
```

I've tested other sql database, such sql works as expected without extra memory,so it should do in cratedb, thanks.

**Steps to reproduce**:

- create table user_buy as follow sample
- insert into user_buy total 10M records
- run sql:  select sum(cost),province,age from user_buy group by province,age;

```
cr> select * from user_buy limit 10;
+--------+-------+-------+--------+---------------------+----------+-------+
| active | age   | city  |   cost | ct                  | province |   uid |
+--------+-------+-------+--------+---------------------+----------+-------+
| 否      | 20-30 | 海口市   | 490.23 | 2016-09-17 07:03:50 | 海南       | 42000 |
| 否      | 30-40 | 成都市   |  39.5  | 2015-10-02 11:10:59 | 四川       | 42004 |
| 否      | 20-30 | 兰州市   | 645.6  | 2016-04-17 03:16:49 | 甘肃       | 42009 |
| 否      | 20以下  | 哈尔滨市  | 570.66 | 2015-11-05 04:54:02 | 黑龙江      | 42010 |
| 否      | 20-30 | 北京    |  20.21 | 2015-04-13 06:42:32 | 北京       | 42011 |
| 是      | 20-30 | 南京市   | 428.02 | 2014-02-20 02:26:43 | 江苏       | 42012 |
| 否      | 20-30 | 呼和浩特市 | 463.73 | 2016-01-02 06:17:15 | 内蒙古      | 42018 |
| 否      | 20-30 | 武汉市   | 316.47 | 2015-02-18 01:59:29 | 湖北       | 42027 |
| 是      | 30-40 | 昆明市   |  32.64 | 2015-12-02 02:17:35 | 云南       | 42037 |
| 否      | 20-30 | 香港岛   | 239.16 | 2016-04-13 06:48:17 | 香港       | 42045 |
+--------+-------+-------+--------+---------------------+----------+-------+
```

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
hi @tqyq 
can you provide the full schema of the table (e.g. with `SHOW CREATE TABLE user_buy`) and also the result of this query:

```sql
select count(*), sum(num_docs), sum(size) from sys.shards where table_name = 'steps_test' group by "primary";
```

you have 4GB of memory, how much heap did you assign to CrateDB?
e.g.:
```sql
select heap['free'] / 1024.0 / 1024.0 as heap_free_mb, heap['max'] / 1024.0 / 1024.0 as heap_total_mb from sys.nodes;
```

**Comment by tqyq** [comment]
+-----------------------------------------------------+
| SHOW CREATE TABLE doc.user_buy                      |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "doc"."user_buy" (       |
|    "active" STRING,                                 |
|    "age" STRING,                                    |
|    "city" STRING,                                   |
|    "cost" FLOAT,                                    |
|    "ct" STRING,                                     |
|    "province" STRING,                               |
|    "uid" INTEGER                                    |
| )                                                   |
| CLUSTERED INTO 4 SHARDS                             |
| WITH (                                              |
|    "blocks.metadata" = false,                       |
|    "blocks.read" = false,                           |
|    "blocks.read_only" = false,                      |
|    "blocks.write" = false,                          |
|    column_policy = 'dynamic',                       |
|    number_of_replicas = '1',                        |
|    "recovery.initial_shards" = 'quorum',            |
|    refresh_interval = 1000,                         |
|    "routing.allocation.enable" = 'all',             |
|    "routing.allocation.total_shards_per_node" = -1, |
|    "translog.disable_flush" = false,                |
|    "translog.flush_threshold_ops" = 2147483647,     |
|    "translog.flush_threshold_period" = 1800000,     |
|    "translog.flush_threshold_size" = 209715200,     |
|    "translog.interval" = 5000,                      |
|    "translog.sync_interval" = 5000,                 |
|    "unassigned.node_left.delayed_timeout" = 60000,  |
|    "warmer.enabled" = true                          |
| )                                                   |
+-----------------------------------------------------+
SHOW 1 row in set (0.122 sec)

`cr> select count(*), sum(num_docs), sum(size) from sys.shards where table_name = 'user_buy' group by "primary";`
+----------+---------------+--------------+
| count(*) | sum(num_docs) |    sum(size) |
+----------+---------------+--------------+
|        4 |           0.0 |          0.0 |
|        4 |    10000000.0 | 1177982845.0 |
+----------+---------------+--------------+
SELECT 2 rows in set (0.028 sec)

`cr> select heap['free'] / 1024.0 / 1024.0 as heap_free_mb, heap['max'] / 1024.0 / 1024.0 as heap_total_mb from sys.nodes;`
+-------------------+---------------+
|      heap_free_mb | heap_total_mb |
+-------------------+---------------+
| 812.9157180786133 |      926.1875 |
+-------------------+---------------+
SELECT 1 row in set (0.003 sec)

BR

**Comment by chaudum** [comment]
@tqyq sorry for the late follow up.
the amount of memory required for the aggregation is dependent on the amount of records, the cardinality of the grouping fields (age, province) and the amount of shards.

in your case the query requires more than 555MB heap memory to execute. since you've only assigned 926MB heap to cratedb and the [query circuit breaker breaks at 60%](https://crate.io/docs/reference/configuration.html#query-circuit-breaker) this is expected behaviour.
you have 4GB of memory on the node, so you should assign 2GB to cratedb. this will probably already solve your issue. otherwise you can also increase the limit at which the breaker should break.

hope this helps.

**Comment by tqyq** [comment]
Thanks for reply
