### ISSUE TITLE
FileNotFoundException even if both the file and the folder exist

### ISSUE THREAD

**Issue by popovvasile** [crate/crate#5151]
**CrateDB version**:
1.00
**JVM version**:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version / environment description**:
Linux Mint 8
**Problem description**:
Try to run` COPY servers to DIRECTORY '/json/ ` from a python 2.7 file. I created a /jon/ folder, as well as a servers_0_.json file. I suppose that here can be a bug. 

**Steps to reproduce**:
`crate.client.exceptions.ProgrammingError: UnhandledServerException[Failed to open output: '/json/servers_0_.json (No such file or directory)']; nested: FileNotFoundException[/json/servers_0_.json (No such file or directory)]; `

The entire Traceback if needed:
`Traceback (most recent call last):
  File "test.py", line 25, in <module>
    testing_2()
  File "/home/vasile/heili/db_core/crate_model.py", line 80, in wrapper
    return method_to_decorate(*args, **kwargs)
  File "test.py", line 16, in testing_2
    self.execute("COPY servers to DIRECTORY '/json/'")
  File "/usr/local/lib/python2.7/dist-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 304, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 416, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 170, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: UnhandledServerException[Failed to open output: '/json/servers_0_.json (No such file or directory)']; nested: FileNotFoundException[/json/servers_0_.json (No such file or directory)]; 
`

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
hi @popovvasile did you create the directory on the server where crate is running and does the crate process have the right permissions to write to that directory (`sudo chown crate:crate /json/`)?
you don't need to create the `servers_0_.json` file - this will be created by CrateDB (file name layout is: `<table_name>_<shard_id>.json`).

**Comment by popovvasile** [comment]
I changed the owner to crate, crate db is running on the same machine as the python code. I deleted the file that I created- still doesn't work

**Comment by mfussenegger** [comment]
Just tried to reproduce this in both 1.0.0 and 1.0.5

Both yield this:

```
cr> copy t1 to directory '/mnt/';
UnhandledServerException[Failed to open output: '/mnt/t1_0_.json (Permission denied)']; nested: FileNotFoundException[/mnt/t1_0_.json (Permission denied)]; 

cr> copy t1 to directory '/tmp/json/';
COPY OK, 1 row affected  (0.020 sec)
```

Is this a single node & local filesystem?

**Comment by popovvasile** [comment]
Yes, it is. Strange thing- why when we use /tmp/ everything works great  but when we use a custom folder- it gives an error?

**Comment by mfussenegger** [comment]
I just used `/tmp/` as an example for a folder where the crate process has write permission. It also works for other folders if I set the permissions correctly.

Can you try to create a file in the folder you want to export to in a shell as the user the crate process is running as? Does that work?

**Comment by popovvasile** [comment]
Yes, it's working, thank you guys for help! Just a small question- why is carte creating every time 4 files? In my case they look like servers_0_.json servers_1_.json servers_2_.json servers_3_.json. How to make it to store everything in one file?

**Comment by joemoe** [comment]
hi @popovvasile, it's creating a file for each shard on each node. see our documentation https://crate.io/docs/reference/sql/reference/copy_to.html#description

> Each node with at least one shard of the table will export its contents onto their local disk.

you can't write this to one file. you'd need a script to merge stuff together.
