### ISSUE TITLE
About on timestamp

### ISSUE THREAD

**Issue by sansom** [crate/crate#5166]
**CrateDB version**:1.5

**JVM version**:1.8

**OS version / environment description**: linux 6.5

When the field type is timestamp, the input data is 8 hours apart from the current time, and I'm from China.

**Comment by mfussenegger** [comment]
Are you referring to the current_timestamp function or where do the values come from? Please provide some examples to showcase what you mean

**Comment by sansom** [comment]
CREATE TABLE IF NOT EXISTS "canal_test"."user_info" (
   "create_time" TIMESTAMP,
   "id" INTEGER,
   "name" STRING,
   "num" DOUBLE,
   "ps" STRING,
   "pw" STRING,
   PRIMARY KEY ("id")
)
CLUSTERED BY ("id") INTO 4 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.disable_flush" = false,
   "translog.flush_threshold_ops" = 2147483647,
   "translog.flush_threshold_period" = 1800000,
   "translog.flush_threshold_size" = 209715200,
   "translog.interval" = 5000,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true
)

insert into canal_test.user_info(name,num,create_time,id) values ('sansom ', 20.02 , '2017-03-17T19:34:19' , 7);

select  * from canal_test.user_info where id=7;

the result:
     create_time	         id	       name	                num	
2017-03-18 03:34:19.0	 7      	sansom 	      20.02

**Comment by joemoe** [comment]
@sansom can you check what timezone is set on the nodes.

**Comment by mfussenegger** [comment]
It looks like your client with which you're doing the select statement is converting the timestamp to localtime.

In your insert `2017-03-17T19:34:19` is UTC,
You'll see that if you do a query like this:

```
cr> select date_format('%y-%m-%d -%H:%i', create_time), cast(create_time as long), create_time from can
    al_test.user_info;
+---------------------------------------------+---------------------------+---------------+
| date_format('%y-%m-%d -%H:%i', create_time) | CAST(create_time AS long) |   create_time |
+---------------------------------------------+---------------------------+---------------+
| 17-03-17 -19:34                             |             1489779259000 | 1489779259000 |
+---------------------------------------------+---------------------------+---------------+
```

**Comment by joemoe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[crate/crate] wrong timestamp #5166](https://trello.com/c/7tJm4WxY/322-crate-crate-wrong-timestamp-5166)

**Comment by sansom** [comment]
@mfussenegger Yes, you are right. and thanks guys.
