### ISSUE TITLE
SQL Query slowness issue

### ISSUE THREAD

**Issue by shaunoconnell** [crate/crate#5188]
**CrateDB version**: 1.0.0

**JVM version**: 1.8.0_31

**OS version / environment description**: centos7.0.1406

**Problem description**:

Periodically I have issues where crate will become slow.  Response times are usually < 10ms but then when things become slow response times take 5+ minutes.  When recreating the query and hitting just the ES api it seems like response times are still fast.

Running jstack on the crate nodes we see a lot of BLOCKED threads on this line 

https://github.com/crate/crate/blob/1.0.0/sql/src/main/java/io/crate/operation/reference/sys/shard/blob/BlobShardSizeExpression.java#L49

**Steps to reproduce**:

The issue seems non-deterministic.  I use crate both for the SQL interface as well as the blob interface.  

I run an 11 node cluster, and use daily rolling blob tables (2017-03-01, 2017-03-02).  each table will have about 2 - 3 million records, and be just under 1 TB.  Each table has 24 shards and 1 Replicas.  

Originally I was keeping 5 days worth of data, but now have trimmed that to 1.  When I experienced slowness I would drop a few blob tables then crate seemed to recover.

Sometimes a cluster restart is required to fully recover too.  Crate will be up for weeks then become unhealthy and unresponsive.  Keep in mind that because of our rolling drop of tables we always have approximately the same amount of data and same number of shards in our crate instance.  thanks.

**Comment by andreidan** [comment]
Thanks for reporting, we'll look into it.

**Comment by andreidan** [comment]
One question @shaunoconnell 
You mentioned you have about 2-3 million records / table. How many tables do you have in this setup?

**Comment by shaunoconnell** [comment]
@andreidan we have 7 Tables and 6 blob tables.  

all tables have 22 || 24 shards.  There are about 55 GB in regular tables and a 2.4ish TBs in the blob tables.

On my end i'm working to setup some experiments to test things out, but have been unsuccessful thus far.

**Comment by andreidan** [comment]
@shaunoconnell We addressed this issue with PR https://github.com/crate/crate/pull/5270 and the fix will be available with the next feature release.
Thanks again for reporting
