### ISSUE TITLE
blob table directories stick around after drop table 

### ISSUE THREAD

**Issue by shaunoconnell** [crate/crate#5189]
**CrateDB version**: 1.0.0

**JVM version**: 1.8.0_31

**OS version / environment description**: centos7.0.1406

**Problem description**:

crate does not fully clean up the blob data directory when tables are dropped.

**Steps to reproduce**:

  * create blob table foo_tbl;
  * drop blob table foo_tbl;
  * ls -lart {blobs.path}/blobs/nodes/0/indices/

The directory should still exist.  Not sure if this is related to [5188](https://github.com/crate/crate/issues/5188)

(The actual data is removed though)

**Comment by christianbader** [comment]
Hi @shaunoconnell 

Do you have configured a custom location for storing blob data or are you using the default location?

I assume that you experience the issue running the same cluster/configuration that you mentioned in the issue [5188](https://github.com/crate/crate/issues/5188)?

**Comment by shaunoconnell** [comment]
@christianbader yes there is a custom location for this data.  

it's a local harddrive.  i.e. not NFS.

**Comment by christianbader** [comment]
@shaunoconnell 

Thanks for the information.
This seems only to occur when a custom blob location is configured.
We will have a look on it closer.

**Comment by christianbader** [comment]
@shaunoconnell 

This issue is fixed and will be part of the next release.

**Comment by shaunoconnell** [comment]
@christianbader great.  thanks for your help.
