### ISSUE TITLE
Could not initialize class io.crate.client.jdbc.CrateDriver

### ISSUE THREAD

**Issue by sansom** [crate/crate#5223]
**CrateDB version**:1.0.5

**JVM version**:1.8
 
I use streamsets-datacollector-all-2.4.1.0 and additional drivers crate-jdbc-standalone-2.1.6 alway  point out:
Pipeline Status: START_ERROR: java.lang.NoClassDefFoundError: Could not initialize class io.crate.client.jdbc.CrateDriver

**Comment by chaudum** [comment]
It would be helpful if you could provide a bit more information.
Also, JDBC related issues should be posted on the [crate/crate-jdbc](https://github.com/crate/crate-jdbc) repo.
From the information there is, I assume the crate-jdbc-standalone-2.1.6.jar is not in the Java classpath of Streamsets.

**Comment by mfussenegger** [comment]
Closing this as there hasn't been any feedback and this is likely crate-jdbc related anyway.
