### ISSUE TITLE
SELECT count(*) count FROM business_order

### ISSUE THREAD

**Issue by sansom** [crate/crate#5224]
**CrateDB version**: 1.0.5

**JVM version**:1.8

**Use case**:
SELECT count(*) count
FROM business_order
the count=735503

and exec this sql:
select sum(count) from (
SELECT member_id,count(*) count
FROM business_order
group by member_id
)a

the count=267549676

**Comment by mfussenegger** [comment]
Sorry but for us to make sense of this you'll have to explain a but more instead of just writing down 2 statements

**Comment by mfussenegger** [comment]
Closing this as there hasn't been any feedback
