### ISSUE TITLE
Admin plugin compatible with elasticsearch or not

### ISSUE THREAD

**Issue by vus520** [crate/crate#5266]
I need a SQL2ES plugin on my elasticsearch cluster. 

I found this project, but i have a es cluster already that i can't transfer data from es to crate.

I want to know if admin plugin compatible with elasticsearch or not.

**Comment by celaus** [comment]
Hi @vus520 - although we use some ES parts in CrateDB, we are not compatible. If you like our admin Ui better, thanks - but it was created for CrateDB. Let us know if you get it to work with Elasticsearch 😃

**Comment by mfussenegger** [comment]
Closing this as the question has been answered.

CrateDB is not a SQL2ES plugin that can be installed on a Elasticsearch Cluster. It doesn't translate SQL into the ES query language but instead has it's own execution engine. To use CrateDB you've to install CrateDB.
(And to extend on what @celaus said, the Admin UI won't work with ES as it is using SQL to query the information that is displayed)
