### ISSUE TITLE
CHANGES.txt is missing a lot of content

### ISSUE THREAD

**Issue by mindscratch** [crate/crate#5304]
Looks like the [CHANGES.txt](https://github.com/crate/crate/blob/master/CHANGES.txt) file got chopped (its only 38 lines at the moment)

**Comment by mfussenegger** [comment]
We've changed the CHANGES.txt so that it only contains unreleased changes. As
stated in the file:

> This file collects *unreleased* changes only.
> 
> For release notes, see:
> 
>   https://crate.io/docs/reference/en/latest/release_notes/index.html

In the source tree the release-notes are now here:

https://github.com/crate/crate/blob/master/blackbox/docs/release_notes/index.txt

**Comment by joemoe** [comment]
hi @mindscratch i hope this answers your question. i'll close this issue. if you want to discuss further feel free to reopen it.
