### ISSUE TITLE
[Feature] SQL functions for computing hash sums

### ISSUE THREAD

**Issue by mxm** [crate/crate#5403]
**Use case**: 

Users might want to compute hash sums using common hash algorithms like MD5, SHA1, SHA256, and SHA512.

**Feature description**: 

The features introduces new SQL functions MD5(string), SHA1(string), SHA256(string), and SHA512(string). String can be a literal or a column name.

**Comment by mfussenegger** [comment]
Closing because you added some of the functions with https://github.com/crate/crate/pull/5405

**Comment by mxm** [comment]
Thanks, there is no sha256 and sha512 yet but basic hashing is there for now.
