### ISSUE TITLE
Copy From with partitioned tables/generated fields fails

### ISSUE THREAD

**Issue by burnes** [crate/crate#5418]
**CrateDB version**:
1.1.2

**JVM version**:
8
**OS version / environment description**:
Linux
**Problem description**:

A partitioned table with generated columns as partitioned key can't be restored with copy from, as it has to be a primary key too and is not saved in the copied JSON file.

The copy from statement fails with:

`IllegalArgumentException[A primary key value must not be NULL]`

**Steps to reproduce**:

create table copy_test (
  ts timestamp,
  v string,
  "gen_month_partition" STRING GENERATED ALWAYS AS date_format('%Y%m', "ts"),
  PRIMARY KEY ("v", "gen_month_partition")
)
PARTITIONED BY ("gen_month_partition");

insert into copy_test (ts, v) values ('2017-01-01T12:00', 'John'), ('2017-01-04T11:00', 'Mary');

copy copy_test to directory '/tmp/';

delete from copy_test;

copy copy_test from '/tmp/copy_test_*.json';

**Use case**:

**Feature description**:

**Comment by andreidan** [comment]
@burnes thanks for reporting. This is now fixed with https://github.com/crate/crate/pull/5487
