### ISSUE TITLE
how to upgrade?

### ISSUE THREAD

**Issue by sansom** [crate/crate#5440]
How to upgrade from 1.0.5 to 1.1.2 version? It can directly replace JRA package under the LIB directory ?

**Comment by joemoe** [comment]
hi @sansom, which installation path did you chose? are you using the tar or one of our distributions?
no matter what the process should be:
* do a graceful stop of all nodes in the cluster as this is not a rolling upgrade.
* update crate using the distribution you chose in the first place.
* restart cluster.

**Comment by sansom** [comment]
@joemoe Thank you,I have completed the upgrade, and hope that the 1.2 binary release as soon as possible, the compiler is a bit difficult for us.

**Comment by joemoe** [comment]
hi @sansom, the 1.2 is at the moment `testing` only. though it is available on our cdn: https://cdn.crate.io/downloads/releases/
but be aware this is *not production ready* yet.
