### ISSUE TITLE
Object column changes from 'STRICT' to 'DYNAMIC' when adding column 

### ISSUE THREAD

**Issue by floggi83186** [crate/crate#5446]
**Version:** official docker image 1.1.2

**Problem description**:

When I add a column to a strict object, the object changes from **OBJECT (STRICT)** to **OBJECT (DYNAMIC)**

**Steps to reproduce**:

1. Create a table with an strict object column
```sql
CREATE TABLE IF NOT EXISTS t(
	o Object (Strict) AS(
		r1 string,
		r2 Integer
	)
);
```

2. Add column to object column
```sql
Alter table t add column o['r3'] integer;
```

3. Generate SQL-Create statement
```sql
show create table t;
```
**Result**
```sql
CREATE TABLE IF NOT EXISTS "doc"."t" (
   "o" OBJECT (DYNAMIC) AS (
      "r1" STRING,
      "r2" INTEGER,
      "r3" INTEGER
   )
)
```

The column type of o has changed to **OBJECT (DYNAMIC)**

**Use case**:<br>
We define the object columns as strict because we don't want the user to insert columns that were not defined before in<br>
another system (with some metadata), and also because we need the correct datatypes in crate (e.g. timestamp).

**Comment by joemoe** [comment]
thanks @floggi83186, we will have a look into this.

**Comment by andreidan** [comment]
Thanks for reporting @floggi83186 
This issues was fixed with https://github.com/crate/crate/pull/5472 and will be available with the next release.
