### ISSUE TITLE
Test for  GROUP BY on joins via #5339 version 1.2

### ISSUE THREAD

**Issue by sansom** [crate/crate#5467]
For example:
test contains the following columns:

CREATE TABLE IF NOT EXISTS "huyong"."test" (
   "create_time" TIMESTAMP,
   "create_time1" STRING,
   "remark" STRING
)
simple query:
select count(*) from  huyong.test
Result from query： 1988

time_test contains the following columns:

CREATE TABLE IF NOT EXISTS "huyong"."time_test" (
   "create_time" TIMESTAMP,
   "remark" STRING
)
simple query:
select count(*) from  huyong.time_test
Result from query: 4603

Example query:
select a.remark,count(*) from 
huyong.test a
left join  huyong.time_test b on a.remark=b.remark
group by a.remark

Result from query
  remark	          count(*)
hello world	  9150764

I got the wrong result.

**Comment by christianbader** [comment]
Hi @sansom,

since you closed this issue, does it work as expected for you?

**Comment by sansom** [comment]
Yes, it's what I expected
