### ISSUE TITLE
float accuracy on math functions

### ISSUE THREAD

**Issue by liujie20087349** [crate/crate#5485]
**CrateDB version**:1.1.2

**JVM version**:1.8

**OS version / environment description**:redhat 7.3

**Problem description**:datatype 'float' accuracy

**Steps to reproduce**:

create table cash(date string, spend float);
insert into cash(date, spend) values ('2017-05-03', 55.55);
insert into cash(date, spend) values ('2017-05-03', 34.55);
insert into cash(date, spend) values ('2017-05-03', 87.55);
select (0 - spend) sp,* from cash limit 100;

select (spend + 1.34) sp,* from cash limit 100;
**Use case**:
![date](https://cloud.githubusercontent.com/assets/14345551/25699150/937c8a70-30f4-11e7-804c-01bf22afeeef.png)

**Feature description**:
as you can see, math operation such as + - * /  would produce many decimal points, I cant find any function in scalar (https://crate.io/docs/reference/sql/scalar.html) can help me with this, is there any suggestions?
thanks

**Comment by seut** [comment]
this looks like a bug, we'll have a look into it, thx for reporting.

**Comment by mikethebeer** [comment]
@liujie20087349 fixed and released with Crate 1.1.3. Thanks for reporting.
