### ISSUE TITLE
Crate SQL HTTP endpoint error code were outdated.

### ISSUE THREAD

**Issue by Kaizhe** [crate/crate#5681]
**CrateDB version**: 1.13

**JVM version**:

**OS version / environment description**:

**Problem description**:

**Steps to reproduce**:

**Use case**:
The error code from https://crate.io/docs/reference/en/1.1.3/protocols/http.html#error-handling is outdated. 
For example: Error A document with the same primary key exists already is now 5000, not 4091 in the document

**Feature description**:

**Comment by mikethebeer** [comment]
@Kaizhe is it possible to provide us some details about the error? e.g. which query you run? which version of CrateDB you use?

**Comment by joemoe** [comment]
@Kaizhe thanks for updating the issue. have you recognized other error codes that are wrong? i tested a couple of them and this seems to be a primary key exists already issue only.

**Comment by Autophagy** [comment]
Hi @Kaizhe - this was a bug and the HTTP error codes will be correct in our 1.1.5 hotfix. Thank you for reporting!
