### ISSUE TITLE
NULL insertion stuck problem

### ISSUE THREAD

**Issue by qzren1982** [crate/crate#5740]
**CrateDB version**:1.1.3

**JVM version**:1.8.05

**OS version / environment description**:centos7.3

**Problem description**:
I wrote data to crate through the spark SQL tool, using JDBC, but I found a problem. If a field value is null, the write will get stuck, don't make a mistake, and stop there. If I replace this field with '', you can write successfully. Look at my code:
`var sqlStr=“select inf_note from abc”
var crateUrl="jdbc:postgresql://172.6.10.121:15432/“
val prop:Properties=new Properties()
sqlContext.sql(sqlStr).write.mode("append").jdbc(crateUrl,“test",prop)”
`
result:
running no stop
if i replace inf_note to  '' as inf_note or  nvl(inf_note,'')  the result is ok
this field inf_note's value is NULL

who can help me!

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by qzren1982** [comment]
I  guess THE PROBLEM AT jdbc Driver 
BECAUSE I  USE INSERT CAUSE to insert to Null VALUE TO A TABLE IS Ok.

**Comment by qzren1982** [comment]
if the field is integer，insert null is not permision
i use crate version  1.1.5 ，this issue is keep

**Comment by joemoe** [comment]
hi @qzren1982, we are looking into this. thanks for reporting.

**Comment by matriv** [comment]
Hi @qzren1982,

I'm familiar with Spark but I don't get why you're using a select query to write data.
Please try to it with a DataFrame as here: http://bigdatums.net/2016/10/16/writing-to-a-database-from-spark/

Aslo please check this post here: https://stackoverflow.com/questions/34643200/spark-dataframes-upsert-to-postgres-table .

Let us know of your outcome.

**Comment by matriv** [comment]
@qzren1982 

I also see that you're using `postgresql` in your URL
can you please change to: `var crateUrl="jdbc:crate://172.6.10.121:15432/`

**Comment by matriv** [comment]
@qzren1982 

Could you please update us on the status of this issue?

**Comment by matriv** [comment]
I'm closing this issue for now.
Feel free to re-open if you have more information and issue still exists.
