### ISSUE TITLE
Empty result if all columns of primary key are part of the WHERE conditions

### ISSUE THREAD

**Issue by nook24** [crate/crate#5763]
**CrateDB version**: 1.1.2 and 1.1.5 

**JVM version**: Java 8
````
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
````
**OS version / environment description**:
Ubuntu 14.04.5 LTS - amd64

**Problem description**:
If I try to run a SELECT or DELETE statement, where all columns of the primary key are part of the WHERE condition, Crate always return an empty result or don't delete the record.

**Steps to reproduce**:

Create schema and import testing data
````sql
create table statusengine_host_scheduleddowntimes_test (
    hostname string,
    entry_time timestamp,
    author_name string,
    comment_data string,
    internal_downtime_id int,
    triggered_by_id int,
    is_fixed boolean,
    duration int,
    scheduled_start_time timestamp,
    scheduled_end_time timestamp,
    was_started boolean,
    actual_start_time timestamp,
    node_name string,
    PRIMARY KEY ("hostname", "node_name", "scheduled_start_time", "internal_downtime_id")
) CLUSTERED INTO 4 shards with (number_of_replicas = '1-all');

INSERT INTO statusengine_host_scheduleddowntimes_test (hostname, entry_time, author_name, comment_data, internal_downtime_id, triggered_by_id, is_fixed, duration, scheduled_start_time, scheduled_end_time, was_started, actual_start_time, node_name)VALUES
('hplj2605dn', 1497981544, 'Anonymous', '60sekunden111', 12, 0, true, 60, 1497981638, 1497981698, true, 1497981638, 'Crowbar'),
('hplj2605dn', 1497903139, 'Anonymous', '300sekunden111', 7, 0, true, 300, 1497903501, 1497903801, true, 1497903501, 'Crowbar'),
('hplj2605dn', 1497982034, 'Anonymous', '60sekunden222', 14, 0, true, 300, 1497982068, 1497982128, true, 1497982068, 'Crowbar');

````

Query i like the execute, which always return nothing
````sql
select * from statusengine_host_scheduleddowntimes_test where hostname='hplj2605dn' and node_name='Crowbar' AND scheduled_start_time=1497981638 and internal_downtime_id=12;
````
As you can see, i use all primary key columns in the WHERE condition...

I also noticed, that a SELECT count(*) will return 1.
````sql
select Count(*) from statusengine_host_scheduleddowntimes_test where hostname='hplj2605dn' and node_name='Crowbar' AND scheduled_start_time=1497981638 and internal_downtime_id=12 limit 100;
````

As workaround i need to add a random column from the table as well
````sql
select * from statusengine_host_scheduleddowntimes_test where hostname='hplj2605dn' and node_name='Crowbar' AND scheduled_start_time=1497981638 and internal_downtime_id=12 and duration=60 limit 100;
````

Did i just miss something?

//Update
Same results on a 3 node CrateDB cluster on Version 1.1.2 as on my single node dev system at 1.1.5

**Comment by chaudum** [comment]
hi @nook24 thanks for reporting. we will have a look at it!

**Comment by grestocla** [comment]
hi @nook24 
It seems to me that the problem is the comparison of the timestamp value. Try casting the column to a timestamp. This worked for me in the given example.

```sql
SELECT *
FROM statusengine_host_scheduleddowntimes_test
WHERE
  hostname = 'hplj2605dn'
  AND node_name = 'Crowbar'
  AND cast(scheduled_start_time as timestamp) = 1497981638
  AND internal_downtime_id = 12;
```

**Comment by seut** [comment]
@nook24 we can reproduce this bug and coming up with a fix soon.

**Comment by seut** [comment]
@nook24 this issue is related to the order of the primary key columns inside the where clause.
a workaround is to define the columns in the same order like the primary key definition, in your case: 
`... where hostname = ... and node_name = ... and scheduled_start_time = ... and internal_downtime_id ...`

**Comment by nook24** [comment]
@seut, I'm not sure if i got you right. Did you mean that I need to define the columns in the same order in my crate table statement:
````sql
create table statusengine_host_scheduleddowntimes_test (
    hostname string,
    node_name string,
    scheduled_start_time timestamp,
    internal_downtime_id, int
    <rest of columns/>
PRIMARY KEY ("hostname", "node_name", "scheduled_start_time", "internal_downtime_id")
````

Or did you mean, that I need to pass the columns in the WHERE condition in the same order, as they are defined in the PK?
Because in my example query, they are already in the same order as in the PK definition...
>````sql
> PRIMARY KEY ("hostname", "node_name", "scheduled_start_time", "internal_downtime_id")
>
>select * from
>statusengine_host_scheduleddowntimes_test where hostname='hplj2605dn'
>and node_name='Crowbar' AND scheduled_start_time=1497981638
>and internal_downtime_id=12;
>````
and this is returning an empty result set.

@grestocla 
Nice idea.
Based on this i found an other workaround. I just need to cast the `internal_downtime_id` from integer to integer, this works as well
````sql
select * from
statusengine_host_scheduleddowntimes_test
where hostname='hplj2605dn' and node_name='Crowbar'
AND scheduled_start_time=1497981638 and cast(internal_downtime_id as integer)=12
````

**Comment by seut** [comment]
@nook24 @grestocla this isssue has been fixed by https://github.com/crate/crate/commit/919fec3c4e47f61336d8db9970b42a9bb7b408ed and will be released with the next hotfix releases.
