### ISSUE TITLE
Sum up a generated column will got an error

### ISSUE THREAD

**Issue by 0i** [crate/crate#5792]
**CrateDB version**: 1.1.5

**JVM version**: 1.8.x

**OS version / environment description**: Ubuntu 16.04.2 LTS

**Problem description**:

I am trying to sum up a generated column but getting an error.

**Steps to reproduce**:
Table Schema:
``` sql
create table test_table (
    cost integer,
    revenues integer,
    profit integer generated always as ("revenues" - "cost")
) with (
    number_of_replicas = 1,
    refresh_interval = 1000,
    column_policy = 'strict'
);
```
Insert data
``` sql
insert into test_table(cost, revenues) values(900, 1000);
```
sum(profit)
``` sql
select sum(profit) from test_table;
```
Got error
```
SQLActionException[UnsupportedFeatureException: Can't handle Symbol revenues]
```

**Comment by matriv** [comment]
The issue has been fixed and will be available with the next hotfix releases.

Thank you for reporting!
