### ISSUE TITLE
execuse me, how to visit Crate with username and password authentication ?

### ISSUE THREAD

**Issue by aaronhadoop** [crate/crate#5806]
**CrateDB version**: 1.0.4

**JVM version**: 1.8.0_111

**OS version / environment description**:

**Problem description**:

**Steps to reproduce**:

execuse me, how to visit Crate with username and password authentication ?

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @aaronhadoop, that is at the moment not possible. we added host based authentication in the most recent version. https://crate.io/docs/reference/administration/auth_methods.html
there will be a certificated based authentication in 2.1. which will be released in july.
you could also use ngnix to setup user/pw auth.

**Comment by joemoe** [comment]
@aaronhadoop i forgot to point out that the authentication features are part of the enterprise edition. you can fine information on that matter on this page: https://crate.io/pricing/

**Comment by seut** [comment]
@aaronhadoop We've recently released CrateDB v2.3.0 (testing release) which includes support for username/password authentication as an enterprise feature, see [Release Notes](https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/2.3.0.html) and [Password Authentication Documentation](https://crate.io/docs/crate/reference/en/latest/admin/auth/methods.html#password-authentication-method).
