### ISSUE TITLE
JOIN with sub queries is not supported

### ISSUE THREAD

**Issue by ManeeshSharma17** [crate/crate#5815]
**Use case**: 
I want to perform joins over sub queries

**Feature description**: 
I have two tables, where I want to perform some operation like --

```sql
SELECT a.*, subquery1.total as "total"
FROM a, (SELECT b.name, count(*) as total from b group by  b.name) subquery1
WHERE a.name = subquery1.name; 
```

But the above query is returning error 
`
-- SQLActionException[UnsupportedFeatureException: JOIN with sub queries is not supported]
`

**Question/Feature Request**:
Could you please confirm if this functionality is in roadmap. If not, request you to add the same.

**Comment by mfussenegger** [comment]
joins with sub queries will be supported with the next feature release (2.1) (https://github.com/crate/crate/blob/934c470d11fcc2c9346d4236d78e17f930c5e2c2/CHANGES.txt#L51)

**Comment by ManeeshSharma17** [comment]
Thanks
