### ISSUE TITLE
Support S3 as a Blob storage medium

### ISSUE THREAD

**Issue by ManeeshSharma17** [crate/crate#5818]
**Use case**:  
I want to use AWS S3 as a medium to storage blob data. 

**Feature description**:
While creating blob table can we give S3 URL as a blob path. Sample query is as below:

`create blob table data clustered into 2 shards with (blobs_path='S3://example-bucket/crate_blob_data');`

**Advantages**:
Through this approach we will have common file system for storage and retrieval of blob data across cluster.
We will not run into storage problem.

**Comment by joemoe** [comment]
hi @ManeeshSharma17, why don't you use s3 directly? wouldn't this be easier than piping that through CrateDB?

**Comment by ManeeshSharma17** [comment]
hi @joemoe, 

We are trying to use Crate as an interface between Client layer and S3. As we don't want to make the blob object on S3 as public or don't want to provide credentials to the client.

Also, in this way we can combine data with other columnar table data. User will be able to download specific file only, using blob id and in a single call. We do the sequential calls at the Crate level.
Right now we are doing this with multiple API calls between RDBMS and S3. We feel that this can be simplified (if this can be achieved) through Crate.

**Comment by joemoe** [comment]
hi @ManeeshSharma17, 

i understand your usecase, but still our intention behind the blob storage is being able to distribute data within the cratedb cluster. usually our users who want to handle files like you describe use s3 directly. i put your request on our backlog, but it is not very likely that we put this into the product soon, as this differs from our core idea. maybe you can achieve this by mounting your s3 bucket as local disc, but then you'd need a bucket for each node.

i'll keep you up to date.

thanks.

**Comment by mfussenegger** [comment]
Closing this for now - we currently have no plans to support this.
