### ISSUE TITLE
Renamed the partitioned table and Internal insert and drop it, the data will be dropped.

### ISSUE THREAD

**Issue by 0i** [crate/crate#5823]
**CrateDB version**: 2.0.2

**JVM version**: 1.8.x

**OS version / environment description**: Ubuntu 16.04.2 LTS
**Problem description**:
If table is partitioned, and rename, and ```insert into T (select * from T_old)``` and drop T_old table, the T table data will be dropped.

**Steps to reproduce**:
1: Create partitioned table
```sql
create table test_table (
    id string primary key,
    partition_id string primary key
) clustered by ("id") into 4 shards
partitioned by ("partition_id")
with (
    number_of_replicas = 1,
    refresh_interval = 3000,
    column_policy = 'strict'
);
```

2: Insert data
```sql
insert into test_table(id, partition_id) values ('a', 'p'),('b', 'p'),('c', 'p'),('d', 'p'),('e', 'p');
select count(*) from test_table limit 1; -- 5 records
```

3: Rename table
```sql
alter table test_table rename to test_table_old;
select count(*) from test_table_old limit 1; -- 5 records
```

4: Create table again
```sql
create table test_table (
    id string primary key,
    partition_id string primary key
) clustered by ("id") into 4 shards
partitioned by ("partition_id")
with (
    number_of_replicas = 1,
    refresh_interval = 3000,
    column_policy = 'strict'
);
select count(*) from test_table limit 1; -- 0 record
```

5: Internal insert
```sql
insert into test_table (select * from test_table_old);
select count(*) from test_table limit 1; -- 5 records
```

6: Drop old table
```sql
drop table test_table_old;
select count(*) from test_table limit 1; -- 0 record 😂😂😂, Where is my data?
```

> This is a sad BUG😂😂😂, How can I restore my data? Thanks very much!
> This is a sad BUG😂😂😂, How can I restore my data? Thanks very much!
> This is a sad BUG😂😂😂, How can I restore my data? Thanks very much!

**Comment by joemoe** [comment]
hi @0i, thanks for reporting this. we were able to reproduce this and looking now deeper into this.

**Comment by seut** [comment]
@0i We've fixed this by https://github.com/crate/crate/pull/5839, will be released with the next 2.0 hotfix release. Unfortunately there is no way to recover the data beside using a backup 😢.

Thank you a lot for reporting!

**Comment by jodok** [comment]
@0i sorry again for the inconvenience - we have issued a new release yesterday evening. right now it's on the testing channel, but we will push it to the stable channel later today.

**Comment by Autophagy** [comment]
@0i The fix for this issue is now in the latest CrateDB stable version - 2.0.3.

**Comment by 0i** [comment]
@jodok It is luckily that this table can be recovered from other logs, I hope that other people do not lose important data. And CrateDB is a good database.
加油。ｂ（￣▽￣）ｄ
