### ISSUE TITLE
Requesting Open Source Features

### ISSUE THREAD

**Issue by obaidcuet** [crate/crate#5835]
**Use case**:
I understand crate.io has some kind of business model. However, I would request below features to be part of opensource version. 
It will make cartedb a complete opensource database, as these are basic database features. 

**Feature description**:
1. basic authentication (password), like mysql/postgres
2. authorization (role based access control), like mysql/postgres
3. SQL Window functions, like postgres
4. UDF based on SQL/python/java/C, like mysql/postgres
5. option to read from delimited ascii file (csv), similar to postgres COPY command
6. native connector for Spark, that will enable parallel data movement between spark workers and cratedb nodes(please correct me if cratedb already have it).

Note: 
- I mentioned mysql/postgres as they are also opensource.
- point 5 & 6, I am requesting enhancement and keeping is part of opensource version.

**Comment by andyellicott** [comment]
Hi Obaidcuet. Thanks for your input. We will continue to enhance the open source version of CrateDB with new features, and we pledge that open source features will remain open source. 

Our business model includes a commercial enterprise edition with premium features. If you are a non-profit or part of an educational institution you can use the enterprise edition features freely. We currently list the enterprise features (current and near-future) here: https://crate.io/enterprise-edition/. 

Features 1-4 in your list are already Enterprise features for now. Numbers 5 & 6 are not scheduled on our new feature roadmap, so those are possibilities for open source. 

Thanks again for the feature suggestions; let us know if you have others or would like to discuss the product roadmap in more detail.

**Comment by obaidcuet** [comment]
@andyellicott thanks for considering my comments.

**Comment by jodok** [comment]
@obaidcuet small correction - window functions will be part of the open source edition.

**Comment by obaidcuet** [comment]
Thanks all :)
