### ISSUE TITLE
Query Optimizer for JOIN

### ISSUE THREAD

**Issue by obaidcuet** [crate/crate#5836]
**Use case**:
As per [join](https://crate.io/docs/reference/sql/joins.html) documentation 

> Joining more than 2 tables can result in execution plans which perform poorly as there is no query optimizer in place yet

In terms of SQL based analytics, it is common to have dimensional model or start schema. Requesting to add query optimizer to JOIN. Any planned date for that ?
 
**Feature description**:
Query optimizer to "JOIN" for star schema and large tables joins.

**Comment by joemoe** [comment]
hi @obaidcuet, yes, that's on our backlog. we don't have an eta yet. i'll keep you up to date.

**Comment by obaidcuet** [comment]
@joemoe kindly update, at least, your planned date.

**Comment by rookie7799** [comment]
+1

**Comment by joemoe** [comment]
sry @obaidcuet, totally overlooked your comment. we don't have a planned date.

**Comment by SneakyMax** [comment]
I'd just like to say that this is one of the couple things that's been annoying with crate. We have a 70 million row table, and we can't join it against any other table because the query never ends. We have to aggregate the table, and then join against other tables - which isn't too much of a problem most of the time, but we have to always be careful.

**Comment by mfussenegger** [comment]
Short update here. CrateDB 3.0 will have support for hash joins which should significantly speed up joins in certain cases. It's already been merged to master and could be tried if using a [nightly build](https://crate.io/download/#testing)

We'd be happy to hear your feedback

**Comment by matriv** [comment]
CreateDB `3.0.0` has been released (currently testing, not stable) which includes support for execution of Equi-joins (inner joins with equality join conditions) with the HashJoin algorithm.

**Comment by matriv** [comment]
@obaidcuet Have you managed to test the behavior of your queries with CrateDB `3.0.x` version?

**Comment by rookie7799** [comment]
We tested v 3.0.0 and works like a charm with 2+ joins. Our query times when from 15 seconds to sub-1s.
Thank you!

**Comment by matriv** [comment]
@rookie7799 Great to hear that!

**Comment by matriv** [comment]
Closing the issue, feel free to reopen if you experience more issues here.
