### ISSUE TITLE
"generated column" with integer and timestamp causes error

### ISSUE THREAD

**Issue by ramach** [crate/crate#5841]
**CrateDB version**:
Version: 0.57.5
**JVM version**:
1.8
**OS version / environment description**:
linux
**Problem description**:
not able to create a generated column for partitioning using a Int and Timestamp
something like this gives error,

"partition_column" STRING GENERATED ALWAYS AS concat(cast (unique_id as String), to_char(fromtime, 'YYYYY-MM-DD')),
fails with sql exception while creating a table

please provide an example for efficient way to generate such a column

"partition_column" STRING GENERATED ALWAYS AS concat(cast (tenant_id as String), to_char(fromtime, 'YYYY-MM-DDD')),

**Steps to reproduce**:

CREATE TABLE IF NOT EXISTS "updated"."testtable" (
"unique_id" INTEGER,
"fromtime" TIMESTAMP,
.....
"partition_column" STRING GENERATED ALWAYS AS concat(cast (unique_id as String), 

PARTITIONED BY ("partition_column")
.........

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment]
I think something like this works?

```
create table if not exists t1 (
        id int,
        fromtime timestamp,
        pc string generated always as concat(cast( id as string), date_format('%y-%m-%d', fromtime))
        ) partitioned by (pc);
```

Keep in mind that the `id` here shouldn't be unique, otherwise it will create 1 partition **per** row, which will be super inefficient and slow. 
Partitioning by day is likely to also result in too many partitions.
Keep in mind that you'll end up with `number_of_configured_shards * number_of_partitions`, and that value shouldn't become too large.

**Comment by ramach** [comment]
I will try. Yes I am aware.  id here is more like a group id  not 1 per row
- maximum I expect is 300 and fromtime is not more than 45 days

thanks for your help

regards
Krishna

**Comment by joemoe** [comment]
hi @ramach, did this help you?

**Comment by ramach** [comment]
Yes! thank you. I have another related issue
After updating the partition column am not able to insert rows from an existing table - same table with additional generated partition column

crash -c "insert into  updated_table (select * from original_table)” I get this error,

SQLActionException[SQLParseException: Number of target columns of insert statement doesn't match number of source columns

I thought partition_column need not be explicitly included at it is generated using 2 fields from original tables + a new column for partitioning (replace old day based partitioning with a combination)

What is the best way to do a bulk insert? I do not want to read and insert 1 row at a time as the table is very big

**Comment by ramach** [comment]
I figured out as to how to bulk insert into modified table  please ignore my last question
