### ISSUE TITLE
Inefficient Storage Usage

### ISSUE THREAD

**Issue by obaidcuet** [crate/crate#5842]
**CrateDB version**: 2.0.2

**JVM version**: 1.8.0_131

**OS version / environment description**: ubuntu 16.10 (desktop)

**Problem description**:
Inefficient storage usage. I loaded 1G csv file. But in database size becomes 4.4G (with one node, so no replication).
If we consider replication, it will become worse and super costly in terms of storage and eventually performance.

**Steps to reproduce**:

```
1. download files from s3://big-data-benchmark/pavlo/text/1node/rankings/
2. convert csv files to JSON a file(rankings.json) using below code:
#!/usr/bin/python
import csv
import json
import sys

fieldnames = ("pageURL","pageRank","avgDuration")
for row in csv.DictReader(sys.stdin, fieldnames):
    json.dump(row, sys.stdout)
    sys.stdout.write('\n')

3. create target table:
create table Rankings (
 "pageURL" STRING PRIMARY KEY,
 "pageRank" INT,
 "avgDuration" INT
)
CLUSTERED BY ("pageURL") INTO 2 SHARDS ;

4. load to target table
COPY rankings FROM 'file:///tmp/dataset/rankings.json' WITH(bulk_size=100000);

5. check size of the table from admin UI
```

**Comment by jodok** [comment]
can you optimize the table and see whether it uses less space? https://crate.io/docs/reference/sql/optimize.html

**Comment by obaidcuet** [comment]
> can you optimize the table and see whether it uses less space? 

Yes, I have tried with optimize (`optimize table Rankings;`), still 4.4G.
By the way, loading also very very slow, took 10min to load only 1GB data.

**Comment by seut** [comment]
@obaidcuet 
Every field by default has an index, which will increase the overall storage size of an table.
Additionally, all fields defined as a `PRIMARY KEY` will be encoded inside the internal `_id` field. If no primary keys are defined, the  `_id` is a generated UUID. This `_id` field must be always indexed to do lookups by id/primary key.
So in your examples 4 indices will be created, 2 rather small ones on the integers, and 2 on the rather big pageURL values. If you don't need uniqueness on the `pageURL` column, removing the primary key definition would reduce the size.
This could be improved indeed (e.g. don't create 2 indices if just 1 primary key is defined). I've put it on our roadmap, but as storage is the cheapest related resource, reducing the size is currently not one of our top priorities.

**Comment by joemoe** [comment]
hi @obaidcuet, i hope that helps you understand the matter. i'm closing the issue for now. if you have still some questions feel free to open it again.

**Comment by obaidcuet** [comment]
@joemoe @seut @jodok thank you!
