### ISSUE TITLE
Range Queries on _id field

### ISSUE THREAD

**Issue by burnes** [crate/crate#5845]
**CrateDB version**:
2.0.2

**JVM version**:
8

**OS version / environment description**:
OSX / Linux

**Problem description**:

In Crate 2.0.2 it's not possible anymore to do range queries on the `_id` field. This was possible in Crate version 1.1.6. 

The error message:
`SQLActionException[UnhandledServerException: java.lang.IllegalArgumentException: Field [_uid] of type [_uid] does not support range queries]`

A quick fix for the problem is to use a cast to string, but this will probably make the query slow on large tables:

`SELECT ts, _id FROM test WHERE CAST(_id AS STRING) > 'AVz32Sa6bDpzOF_VFngM' ORDER BY ts, _id LIMIT 1`

Use case is to batch process data based on a timestamp and be able to handle data with same timestamp exactly once.

**Steps to reproduce**:

CREATE TABLE test (ts TIMESTAMP);
INSERT INTO test (ts) VALUES ('2017-01-01'), ('2017-01-01'), ('2017-01-02');
SELECT ts, _id FROM test ORDER BY ts, _id LIMIT 1;
SELECT ts, _id FROM test WHERE _id > 'AVz32Sa6bDpzOF_VFngM' ORDER BY ts, _id LIMIT 1;

**Comment by seut** [comment]
@burnes We've fixed this by https://github.com/crate/crate/pull/5848, will be released with the next 2.0 hotfix release.

Thanks for reporting!

**Comment by burnes** [comment]
@seut Always a pleasure ;)
