### ISSUE TITLE
strange bug with _score in combination with LIMIT

### ISSUE THREAD

**Issue by monosize** [crate/crate#5904]
**CrateDB version**: 2.0.4

**OS version / environment description**: crate docker installation

**Problem description**:
_score >= 10.0 with LIMIT is not working.

**Steps to reproduce**:
SELECT name, _score FROM products WHERE MATCH((name_tri, name_ft 15.0, alltext_tri, alltext_ft 
5.0), 'X2100') AND _score >= 10.0 ORDER BY _score DESC LIMIT 5;

The result contains 5 items and not 1!

Gefütterte Sommerjacke | 26.480024
Leinenshirt mit Knopfleiste | 5.912343
Strickjacke | 5.912343
Paisleyschal | 5.912343
Tunika Ausbrenner-Ranken | 5.912343

In the result are rows with a _score lower then 10.0!

Strange behavior: When set LIMIT to 4 or 5 the result is wrong.
LIMIT with 1,2,3 or greater than 5 are correct.
Table is clustered into 4 shards.

**Comment by joemoe** [comment]
hi @monosize, we will look into that, thanks for reporting.

**Comment by mfussenegger** [comment]
We've a fix for this which will be part of the next 2.0.y hotfix release (https://github.com/crate/crate/pull/5932)
