### ISSUE TITLE
Ubuntu 14.04 LTS Install Issue

### ISSUE THREAD

**Issue by kylebush** [crate/crate#5918]
**CrateDB version**: 2.0.4

**JVM version**: 
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
**OS version / environment description**: 
```
AWS EC2 - `Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-4b133c5d
```

**Problem description**:  
```
proc/self/fd/9:` 15: ulimit: Illegal option -u
```
in 
```
/var/log/upstart/crate.log
```
 after installing Crate 2.0.4

**Steps to reproduce**:  
```
bash -c "$(curl -L install.crate.io)"
```

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @kylebush, thanks for reporting we will check that and keep you up to date.

**Comment by Taliik** [comment]
hi @kylebush , i have been trying to reproduce the issue with a clean ubuntu 14.04 LTS installation and the same java version but i couldn't reproduce it. I've seen that you are using a special ec2 ami, does this have any uncommon configurations?

**Comment by kylebush** [comment]
No special configuration, it is the AWS provided AMI - ami-4b133c5d.

**Comment by chaudum** [comment]
Hi we could not find the AMI `ami-4b133c5d`, but we used another official Ubuntu 14.04 LTS (HVM) and we are able to reproduce the problem. We'll keep up updated.
I would however recommend to use a newer version of Ubuntu, e.g. 16.06 LTS.

**Comment by chaudum** [comment]
We've identified the issue in the upstart script and we'll provide a new revision of the package.

**Comment by chaudum** [comment]
@kylebush CrateDB `2.0.5-2` for Ubuntu is now available from the PPA.
https://launchpad.net/~crate/+archive/ubuntu/stable
