### ISSUE TITLE
Upgrade to 2.0.4 fails with Directory not empty errors

### ISSUE THREAD

**Issue by rps-v** [crate/crate#5923]
**CrateDB version**:
2.0.4

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:
Failure to start node after upgrade to 2.0.4 from 1.1.3. No Admin UI, nothing.

Log file:
[crate-log.txt](https://github.com/crate/crate/files/1136633/crate-log.txt)

**Steps to reproduce**:

Try to start Crate after upgrade to 2.0.4 from 1.1.3

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @rps-v, thanks for reporting we will look into that.

**Comment by celaus** [comment]
Hi @rps-v, it's terrible that this happend 😱 .  After some investigation: The procedure is done on start up of 2.0 and it applies a new scheme for organizing indices. If these indices have not been upgraded with [Optimize](https://crate.io/docs/crate/reference/en/latest/sql/optimize.html#segments-upgrade) in 1.x, this error will unfortunately occur. In this case the only solution is to recover from a backup.
