### ISSUE TITLE
in CREATE TABLE, NOT NULL on object(dynamic) ignored

### ISSUE THREAD

**Issue by erik777** [crate/crate#5954]
**CrateDB version**:  2.0.4

**JVM version**: 8

**OS version / environment description**: crate Docker image

**Problem description**:

You can declare a field of an object(dynamic) to be NOT NULL.  It creates the table wtihout error.  However, in columns is_nullable is set to TRUE.  It does not require the field on INSERT.  Checked documentation, and can't find anything regarding NOT NULL on column object fields.  

    `CREATE TABLE mytable (
        owner_id string NOT NULL,
        core object(dynamic) as (
            doctype string NOT NULL
        ) NOT NULL,
        ext object(ignored),
        meta object(dynamic) as (
            created timestamp
        )
    ) PARTITIONED BY (core['doctype']) ;`

    cr> select table_name, column_name, data_type, column_default, is_nullable from  information_schema.columns where table_name like 'mytable%';
    +------------+-----------------+-----------+----------------+-------------+
    | table_name | column_name     | data_type | column_default | is_nullable |
    +------------+-----------------+-----------+----------------+-------------+
    | mytable    | core            | object    |           NULL | FALSE       |
    | mytable    | core['doctype'] | string    |           NULL | TRUE        |
    | mytable    | ext             | object    |           NULL | TRUE        |
    | mytable    | meta            | object    |           NULL | TRUE        |
    | mytable    | meta['created'] | timestamp |           NULL | TRUE        |
    | mytable    | owner_id        | string    |           NULL | FALSE       |
    +------------+-----------------+-----------+----------------+-------------+

core['doctype'] should not be nullable

**Comment by joemoe** [comment]
hi @erik777, thanks for reporting, we will look into this.

**Comment by matriv** [comment]
The issue has been fixed and will be available with the next hotfix releases.

@erik777 Thanks for reporting!
