### ISSUE TITLE
Slow CREATE TABLE on v. 2.0.4

### ISSUE THREAD

**Issue by l7s** [crate/crate#5956]
**CrateDB version**: 2.0.4

**JVM version**: 1.8.0_60

**OS version / environment description**: Debian 7 64bit

**Problem description**: `CREATE TABLE...` is around 10x slower in v. 2.0.4 compared to v. 1.0.1. 

**Steps to reproduce**:

Get two identical VMs 2x CPU core, 1 GB RAM and run Crate.io v. 1.0.1 using config below:
[cfg-1.0.1.tar.gz](https://github.com/crate/crate/files/1150405/cfg-1.0.1.tar.gz)

open Web Console and copy/paste statement below:

```
CREATE TABLE stats (
  "id" long primary key,
  "partner_id" integer,
  "web_product_id" integer,
  "customer_id" integer,
  "user_id" integer,
  "country" string,
  "metric" string,
  "value" float,
  "timestamp" timestamp,
  "object_class" string,
  "object_id" string
);
```

Console will report execution time around 70-80ms.

Now stop v. 1.0.1 and using config below run v. 2.0.4

[cfg-2.0.4.tar.gz](https://github.com/crate/crate/files/1150406/cfg-2.0.4.tar.gz)

open Web Console and copy/paste statement above. Console will report execution time around 800-900ms.

Regards,
Chris

**Comment by joemoe** [comment]
hi @l7s, thanks for reporting the problem. we will look into this. this clearly shouldn't happen.

**Comment by mfussenegger** [comment]
In 2.0 the behaviour of CREATE TABLE changed in that it will now wait for all shards to become active before returning. So that it's a bit slower than in 1.1 is kind of expected.

How much slower depends on the number of shards, number of replicas and of course the environment.

**Comment by joemoe** [comment]
Given @mfussenegger s explanation, I'm closing this. We will update our documentation to explain this.
