### ISSUE TITLE
crate web administration interface

### ISSUE THREAD

**Issue by jyyun** [crate/crate#5960]
CrateDB version: 1.1.4

JVM version: 1.8.0_102

OS version : RedHat 7.3
web administration interface  can set login authentication?How do I configure my user name and password

**Comment by joemoe** [comment]
hi @jyyun, if you want to go with username and password authentication you need to setup a proxy. in 2.1., which we released recently as testing, we added the possibility to do cert auth. 
see our documentation: https://crate.io/docs/crate/reference/en/2.1.0/administration/auth_methods.html#client-certificate-authentication-method
https://crate.io/docs/crate/reference/en/2.1.0/administration/ssl.html
