### ISSUE TITLE
Full cluster crash on backup

### ISSUE THREAD

**Issue by web64** [crate/crate#5964]
**CrateDB version**:
2.0.4 & 2.0.5

**JVM version**:
1.8.0

**OS version / environment description**:
Ubuntu 16.04
Dedicated servers(no VMs), two servers running on SSDs and two on spinning disks.

**Problem description**:
Between 2 and all 4 nodes in cluster crash on heavy loads such as backup or copy table(insert by query).
Recently upgraded from v0.55 to 2.0.4, and that is when this started happening.
Upgraded to 2.0.5 and problem still persists.

Logs: [crate-logs.zip](https://github.com/crate/crate/files/1152774/crate-logs.zip)
The logs shows each server being restarted before running the backup sql:
CREATE SNAPSHOT s3_crate_snaps."2017-07-17-all" ALL WITH (wait_for_completion=true);
and then crashing before being started up again.

Server 5,7 and 8 have similar logs with only a few entries before the crash with the error:
[2017-07-17T12:19:13,664][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Hintere Schwärze] fatal error in thread [elasticsearch[Hintere Schwärze][snapshot][T#4]], exiting
java.lang.OutOfMemoryError: Java heap space

Server 6 has a long list of warnings such as:
[2017-07-17T12:21:05,446][WARN ][o.e.g.GatewayAllocator$InternalReplicaShardAllocator] [SERVER6] [sb.users_temp][7]: failed to list shard for shard_store on node 

There should be several GB of free memory available on each server:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         12G        4.4G        1.3G         14G         17G
Swap:           31G        1.5G         30G
```
CrateDB is not under heavy load, about 30 queries per second (SELECT: 15, INSERT: 5, UPDATE: 10).
Cluster has 30 million records with about 30GB of data.

**Steps to reproduce**:
I haven't got the server capacity at the moment to set up another cluster to try and reproduce the problem, and I'm not able to make a backup of the data anyway, but if the log files doesn't give a clue as to what is causing this I can see if I can find a way to try and replicate the issue.

Please let me know if there is any other info I can provide to identify the cause of this issue.

**Comment by joemoe** [comment]
hi @web64, did you follow the upgrade notes? https://crate.io/docs/crate/reference/release_notes/2.0.5.html
https://crate.io/docs/crate/reference/release_notes/1.1.5.html
what was your upgrade path?
did you do full cluster restarts?

**Comment by web64** [comment]
Thank you for your reply, I think that could be it.
I think I misread the upgrade notes. I read: "If you want to upgrade from a version prior to this .... will require a Full Restart Upgrade" to mean it was not possible with a rolling upgrade so I upgraded directly from 0.55 to 2.04 using full restart upgrade.

**Comment by joemoe** [comment]
ok, @web64. hope you can sort the issue out. i'll check if we can make our upgrade notes clearer.

**Comment by web64** [comment]
I upgraded using:
```
sudo apt-get install --only-upgrade crate
```
and that went without any warnings:
```
100%(Reading database ... 50427 files and directories currently installed.)
Preparing to unpack .../crate_2.0.4-1~xenial_all.deb ...
Unpacking crate (2.0.4-1~xenial) over (1.0.5-1~xenial) ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up crate (2.0.4-1~xenial) ...

Configuration file '/etc/crate/crate.yml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Keeping old config file as default.
Installing new version of config file /etc/default/crate ...
Installing new version of config file /etc/init.d/crate ...
Installing new version of config file /etc/init/crate.conf ...
vm.max_map_count = 262144
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
```

If it is possible it would be good if the package manager could do some basic version checks before upgrading.

**Comment by joemoe** [comment]
hi @web64, this is not possible. it is hard to do that on cratedb side. we have version checks for rolling upgrades, but not yet for full stop upgrades.

**Comment by web64** [comment]
Turns out problem was related to CRATE_HEAP_SIZE.
CRATE_HEAP_SIZE wasn't being defined as I thought it was, and it was using the default 512m.
Defined the variable directly in /usr/share/crate/bin/crate.in.sh and restarted nodes, and backups are working fine now.
