### ISSUE TITLE
Crate version shown not right

### ISSUE THREAD

**Issue by liujie20087349** [crate/crate#5980]
**CrateDB version**: 2.0.5

**JVM version**: 1.8

**OS version / environment description**: redhat 7.3

**Problem description**:

as you can see in the pic, the version in the table below is 5.0.2, but the correct version is 2.0.5

![image](https://user-images.githubusercontent.com/14345551/28355810-30c335d4-6c98-11e7-929f-4e8d5909537c.png)

**Comment by joemoe** [comment]
hi @liujie20087349, yes. this is the version of the underlaying storage format, but this is wrong as we documented it differently and doesn't give the user a benefit.

**Comment by seut** [comment]
@liujie20087349 we've updated our documentation to describe this version number as an internal one. updated documentation will be available with the next hotfix release
