### ISSUE TITLE
[ERROR]  NPE when retriving node's information

### ISSUE THREAD

**Issue by buom** [crate/crate#6001]
**CrateDB version**:
 2.0.6

**JVM version**: 
openjdk version "1.8.0_111"

**OS version / environment description**:
CentOS Linux release 7.2.1511 (Core)

**Problem description**:

Execute:
```
SELECT * FROM sys.nodes;
```

Return:
```
SQLActionException[NullPointerException in io.crate.operation.reference.sys.node.NodeStatsContextFieldResolver.lambda$new$1(NodeStatsContextFieldResolver.java:87)]
```

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @buom, can you tell us a litte bit more?
did you just instal cratedb?
how big is your cluster?
which upgrade path did you take?

**Comment by mxm** [comment]
Hi @buom! We managed to reproduce the error. As a workaround, you can set `psql.enabled: true` in the config if possible. The next minor release will contain a fix.

PR: https://github.com/crate/crate/pull/6002
