### ISSUE TITLE
CrateDB Task

### ISSUE THREAD

**Issue by ezarisheva** [crate/crate#6011]
**CrateDB version**:

**JVM version**:
1.8.

**OS version / environment description**:
macOS Sierra
**Problem description**:
Creating scale Scalar function

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by mikethebeer** [comment]
@ezarisheva can you define your issue in detail?

**Comment by jodok** [comment]
elina is working on an assessment and created a pull request for the coding task. closing the issue here
