### ISSUE TITLE
`bash -c "$(curl -L try.crate.io)"` not working

### ISSUE THREAD

**Issue by senchi** [crate/crate#6034]
**CrateDB version**: latest (not able to install due to "script won't execute" problem :) )

**JVM version**: 
```
senchimac:repos senchi$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**OS version / environment description**: macOS Sierra 10.12.5 (16F73)

**Problem description**: Trying to install latest Crate.IO for local development via `bash -c "$(curl -L try.crate.io)"` and getting following in the console:

```
senchimac:repos senchi$ bash -c "$(curl -L try.crate.io)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6010  100  6010    0     0  49890      0 --:--:-- --:--:-- --:--:-- 50083

It looks like you hit an issue when trying Crate.

Troubleshooting and basic usage information for Crate are available at:

    https://crate.io/docs/
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Steps to reproduce**:
1. open terminal
2. type `bash -c "$(curl -L try.crate.io)"`
3. watch it happen :)

**Use case**:

**Feature description**:

**Comment by turbo-ele** [comment]
@senchi Thank you for reporting the issue. 

We already fixed this. You now can tryout crate with `bash -c "$(curl -L try.crate.io)"`

Really glad you pointed that out! Thanks again! 👍

**Comment by senchi** [comment]
@turbo-ele cool tnx, works now! :)
