### ISSUE TITLE
Unable to configure number_of_replicas

### ISSUE THREAD

**Issue by mindscratch** [crate/crate#6060]
**CrateDB version**: 2.0.6

**JVM version**: jdk 8 (whatever version is installed by [docker-crate](https://github.com/crate/docker-crate/blob/master/Dockerfile#L31))

**OS version / environment description**: alpine:3.5 (using image provided by docker-crate)

**Problem description**:

Crate won't start if `number_of_replicas` setting exists in crate yaml configuration file.

**Steps to reproduce**:

1. docker run crate:2.0.6 -Cnumber_of_replicas=0
2. a stacktrace will be printed and crate will stop, the error reads: `java.lang.IllegalArgumentException: unknown setting [number_of_replicas] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`.

**Use case**:

**Feature description**:

**Comment by matriv** [comment]
@mindscratch 

`number_of_replicas` cannot be set globally, it's a setting that must be specified for every table. Check relevant documentation here: 
https://crate.io/docs/crate/reference/en/2.0/sql/ddl/replication.html and here: https://crate.io/docs/crate/reference/en/2.0/sql/reference/create_table.html#number-of-replicas

**Comment by mindscratch** [comment]
@matriv Thanks for the quick response. I understand what you're saying, however, we've had that setting in our configuration since we began using crate (back to 0.5x). Also, the [documentation](https://crate.io/docs/crate/reference/en/2.0/configuration.html#table-settings) for the setting has remained the same so I assumed it worked as it had always been.

**Comment by matriv** [comment]
The link that you provided states that it's a setting for the CREATE TABLE.

The thing that has changed is that in 2.0.x there is a strict validation of the cluster/node settings you provide, while before they were ignored.

**Comment by mindscratch** [comment]
Oh I see. I thought it was a global setting for tables, which could also be overridden when using `create table`. I think the confusion came from the fact that this setting is documented in the "configuration" section, which seemed to me to imply that you set it up when configuring crate.

I appreciate the clarification, perhaps something can be done in the docs to make it more clear that the "table settings" in the "configuration" section are only for use when doing `create table`, or perhaps, just move the documentation of those settings so its only in the `create table` portion of the docs.

**Comment by matriv** [comment]
@mindscratch 

We have already removed any reference to the table settings from the configuration section in 2.1, you can check here: https://crate.io/docs/crate/reference/en/2.1/configuration.html

**Comment by mindscratch** [comment]
thanks
