### ISSUE TITLE
INSERT ignores primary key when using unnest()

### ISSUE THREAD

**Issue by felixge** [crate/crate#6094]
**CrateDB version**: CrateDB version[2.0.4]

**JVM version**: JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]

**OS version / environment description**: Docker for Mac

**Problem description**:

INSERT ignores primary key when using unnest(). Instead returning an error (like INSERT + VALUES) does, it indicates that 0 rows were inserted (i.e. silently ignores the error).

**Steps to reproduce**:

```
psql (9.6.3, server 9.5.0)
Type "help" for help.

test=> CREATE TABLE my_table (val int PRIMARY KEY);
CREATE 1
test=> INSERT INTO my_table (SELECT * FROM unnest([1]));
INSERT 0 1
test=> INSERT INTO my_table (SELECT * FROM unnest([1]));
INSERT 0 0
test=> INSERT INTO my_table VALUES (1);
ERROR:  DuplicateKeyException: A document with the same primary key exists already
```
**Use case**:

Be more compliant with Postgres.

```
psql (9.6.3)
Type "help" for help.

felixge=# CREATE TABLE my_table (val int PRIMARY KEY);
CREATE TABLE
felixge=# INSERT INTO my_table (SELECT * FROM unnest(ARRAY[1]));
INSERT 0 1
felixge=# INSERT INTO my_table (SELECT * FROM unnest(ARRAY[1]));
ERROR:  duplicate key value violates unique constraint "my_table_pkey"
DETAIL:  Key (val)=(1) already exists.
felixge=# INSERT INTO my_table VALUES (1);
ERROR:  duplicate key value violates unique constraint "my_table_pkey"
DETAIL:  Key (val)=(1) already exists.
```

**Comment by mikethebeer** [comment]
@felixge this is an expected behavior since every operation in Crate is [atomic on document level](https://crate.io/docs/crate/guide/overview/storage_consistency.html#atomic-on-document-level). In this case we decided at least to write every successful operation and ignore the once who failed.  The important thing is still that the `row_count` returns the correct value of how many records have been persisted.

PostgreSQL is not strictly atomic on document level and therefore can be atomic on multiple rows. Indirectly this has something to do with "transactions". So they could do a "rollback" after raising the first error and have the possiblity to avoid any write operation.

**Comment by felixge** [comment]
I'm not sure I follow your argument. Postgres is atomic (the A in ACID) on both the row as well as the transaction level. You can't do anything that will cause a partial row to be written in Postgres.

That being said, I don't see how atomicity is relevant for this discussion. If anything, this is related to the consistency (the C in ACID) that enforces the invariant of the primary key remains unbroken before/after each interaction with the database.

CrateDB doesn't exactly fail the consistency guarantees of a primary key here, but it does seem to perform an implicit `ON CONFLICT (val) DO NOTHING` when using the unnest syntax.

I'm actually okay if this is a won't-fix due to implementation details, I just wanted to raise this issue in case a higher level SQL compatibility is desired. That being said, I'm not entirely sure what the SQL standard actually says about this situation, but usually PostgreSQL follows it very closely unless noted otherwise in the docs.

**Comment by mikethebeer** [comment]
@felixge in Crate it is partly related to atomicity because we are not atomic on multiple rows. This is why its hard for us to revert/rollback changes which is indeed a matter of consistency where we differ from PostgreSQL which is strict on single and multi-row operations. I just saw that I made a typo there in the previous answer.

Anyway, thanks for mention this. We are keeping an eye on that already in our product backlog.

**Comment by felixge** [comment]
@mikethebeer I'm afraid I still don't understand the underlaying issue. From my (naive) point of view crate's query planner's root node should be same "insert node" regardless of whether `unnest` or `VALUES` is used. The only thing that should be different is the node below it. This is what Postgres does:

```sql
EXPLAIN INSERT INTO my_table (SELECT * FROM unnest(ARRAY[1]));
```
```
Insert on my_table  (cost=0.00..1.00 rows=100 width=4)
  ->  Function Scan on unnest  (cost=0.00..1.00 rows=100 width=4)
```
```sql
EXPLAIN INSERT INTO my_table VALUES (1);
```
```
Insert on my_table  (cost=0.00..0.01 rows=1 width=4)
  ->  Result  (cost=0.00..0.01 rows=1 width=4)
```

And if the root node ("insert node") is the same for both queries, shouldn't the error handling be the same when the plan gets executed?

Let me know if this makes sense or not : )

**Comment by felixge** [comment]
I think I found the answer. It seems that crate has separate "InsertFromSubQuery" and "InsertFromValues" nodes. So there isn't a single "insert node" like there is in Postgres. So that explains why the executor may execute them differently, causing the difference in behavior:

```sql
EXPLAIN INSERT INTO my_table (SELECT * FROM unnest([1]));
```
```
ERROR:  UnsupportedFeatureException: EXPLAIN is not supported for InsertFromSubquery{table=Table{only=false, my_table, partitionProperties=[]}, columns=[], subquery=Query{with=Optional.empty, queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[*]}, from=[TableFunction{functionCall=unnest([1])}], where=Optional.empty, groupBy=[], having=Optional.empty, orderBy=[], limit=Optional.empty, offset=Optional.empty}, orderBy=[], limit=Optional.empty, offset=Optional.empty}, assignments=[]}
```

```sql
EXPLAIN INSERT INTO my_table VALUES (1);
```
```
ERROR:  UnsupportedFeatureException: EXPLAIN is not supported for InsertFromValues{table=Table{only=false, my_table, partitionProperties=[]}, columns=[], values=[ValuesList{values=[1]}], assignments=[]}
```

**Comment by seut** [comment]
@felixge Yes exactly. On an `insert-by-sub-query` we don't know upfront how much rows will be affected/inserted. As @mikethebeer already pointed out, we do not support `transactions` and so cannot rollback any operations. The only thing we can to according to SQL is to adjust the affected row count. If we would throw an error, you wouldn't be informed that some inserts were successfully done.

I agree that we could be smarter when using `unnest` with an array literal as here the planner could figure out the number of rows and behaves different for 1 row only in case of error handling. But I'm not quite sure if this is worth doing related to the code complexity this would result in.

**Comment by mikethebeer** [comment]
@felixge 👍 correct. Crate uses a different executor because the `InsertFromSubQuery` produces a bulk insert internally.

**Comment by felixge** [comment]
@seut thanks, that explanation makes sense. I agree that returning the row count makes sense if you you don't know if more than 1 row is going to inserted, and things aren't atomic across rows. I also think that making the query planner more aware of static `unnest()` operations is probably not worth it.

Feel free to close this issue :).
