### ISSUE TITLE
Some INSERTs seem to fail randomly using PHP

### ISSUE THREAD

**Issue by christophpe** [crate/crate#6104]
**CrateDB version**: 2.0.6

**JVM version**: OpenJDK 1.8.0_131

**OS version / environment description**: CentOS 7 (3.10.0-514.26.2.el7.x86_64)

**Problem description**:
Using PHP, some INSERT statements seem to fail randomly.

Relations are to be inserted, and it seems like about 50% of the queries pass, while the rest fails.

The error message is:
Crate Prepare Error: Code = 4000, Message = SQLActionException[SQLParseException: line 1:number: no viable alternative at input ',']

If you copy the queries without any change into the console in the AdminUI, every query succeeds.

The driver we use is the crate database driver (crate-pdo-0.6.3 (composer package)).

**Steps to reproduce**:
CREATE TABLE IF NOT EXISTS "company"."relation" (
   "id_from" STRING,
   "id_to" STRING,
   PRIMARY KEY ("id_from", "id_to")
)
CLUSTERED BY ("id_from") INTO 8 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)

_INSERT that SUCCEEDS:_
INSERT INTO company.relation (id_from, id_to) VALUES ('413462662023162', '1691996757702397'), ('413462662023162', '359532474088827'), ('413462662023162', '1591614901072190');

_INSERT that FAILS:_
INSERT INTO company.relation (id_from, id_to) VALUES ('413462662023162', '1691996757702397'), ('413462662023162', '359532474088827'), ('413462662023162', '1591614901072190'), ('413462662023162', '42199325465'), ('413462662023162', '440195839442412'), ('413462662023162', '106197822745388');

**Comment by seut** [comment]
@christophpe as this seems to be PHP driver related (you already mentioned it, same query on the admin-ui passes), could you pls open a issue at https://github.com/crate/crate-pdo? thx
