### ISSUE TITLE
Problem Inserting data using crate API

### ISSUE THREAD

**Issue by ajayvenugopal1** [crate/crate#6112]
**CrateDB version**: 2.0.6

**JVM version**: 1.8

**OS version / environment description**: Ubuntu 14.04

**Problem description**:
Unable to insert data into crate db using the API. I believe this would be usage issue. 
Please suggest.

Command executed:
`curl -sSXPOST 'http://10.169.45.91:4200/_sql?pretty' -d '{"stmt":"insert into doc.catalogs (product, start_time, start_time_epoch_sec, end_time, end_time_epoch_sec, test_id) values(\"SampleApp\", \"2017-08-11 15:24:12\", 1502442652, \"2017-08-11 16:07:22\", 1502445242, \"Test3\")"}'`

Output:
```
$ curl -sSXPOST 'http://10.169.45.91:4200/_sql?pretty' -d '{"stmt":"insert into doc.catalogs (product, start_time, start_time_epoch_sec, end_time, end_time_epoch_sec, test_id) values(\"SampleApp\", \"2017-08-11 15:24:12\", 1502442652, \"2017-08-11 16:07:22\", 1502445242, \"Test3\")"}'
{
  "error" : {
    "message" : "SQLActionException[ColumnValidationException: Validation failed for product: Invalid value 'to_string(\"SampleApp\")' in insert statement]",
    "code" : 4003
  }
}
```

**Comment by seut** [comment]
string literals must be single quotes not double quoted. see https://crate.io/docs/crate/reference/sql/reference/lexical_structure.html#string-literal

**Comment by ajayvenugopal1** [comment]
Still facing below error.
`curl -sSXPOST 'http://10.169.45.91:4200/_sql?pretty' -d '{"stmt":"insert into doc.catalogs (product, start_time, start_time_epoch_sec, end_time, end_time_epoch_sec, test_id) values('SampleApp', '2017-08-11 15:24:12', 1502442652, '2017-08-11 16:07:22', 1502445242, 'Test3')"}'`

```
{
  "error" : {
    "message" : "SQLActionException[Failed to parse source [{\"stmt\":\"insert into doc.catalogs (product, start_time, start_time_epoch_sec, end_time, end_time_epoch_sec, test_id) values(SampleApp, 2017-08-11]]",
    "code" : 4000
  }
}
curl: (6) Couldn't resolve host '15:24'
curl: (3) [globbing] unmatched close brace/bracket in column 30
```

**Comment by seut** [comment]
As the error indicates, this has nothing to do with crate but with the usage of `curl`. Please check curl/bash documentation on how to quote single quotes.
Example:
```
curl -sSXPOST 'http://10.169.45.91:4200/_sql?pretty' -d '{"stmt":"insert into t1 (str1) values('\''SampleApp'\'')"}'
```

Anyway I recommend you to use parameter substitution always instead, see http://crate.readthedocs.io/en/latest/protocols/http.html#parameter-substitution

**Comment by ajayvenugopal1** [comment]
@seut Thanks a lot, it works fine.
