### ISSUE TITLE
Insert data using crate API

### ISSUE THREAD

**Issue by ajayvenugopal1** [crate/crate#6115]
@seut Still I am not able to insert the data. Could you please have a look at it? Details present in the below issue.
#6112

**Comment by seut** [comment]
@ajayvenugopal1 please reopen existing issues if you want to add something or if it is not solved for your case instead of creating new duplicates. also commenting on closed issues is also possible and we will get notified.

**Comment by ajayvenugopal1** [comment]
@seut Thanks for the update. I have posted comment here #6112 , please suggest.
BTW, I was not able to re-open the above issue.
