### ISSUE TITLE
is it recommended to use some form of connection pooling while accessing Crate using JDBC

### ISSUE THREAD

**Issue by ramach** [crate/crate#6132]
**CrateDB version**:

**JVM version**:

**OS version / environment description**:

**Problem description**:
this is just a question. What is the recommendation for connection pooling? is there any documentation on this?

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @ramach, if you have way more connections then nodes it makes sense. most of our users  - and also skyhigh - are using hikari. we don't have any documentation on this, but this should work with our jdbc driver like with every other jdbc driver.

**Comment by joemoe** [comment]
hi @ramach, did this answer your question?
as i didn't hear back i'm closing this ticket now. feel free to reopen it if there are still questions.

**Comment by ramach** [comment]
Thanks Johannes! am fine with closing
