### ISSUE TITLE
crate start up script error on ubuntu 14.04.5

### ISSUE THREAD

**Issue by leomkkwan** [crate/crate#6134]
**CrateDB version**: 2.1.5

**JVM version**:OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)

**OS version / environment description**: ubuntu 14.04.5

**Problem description**: 
When starting crate with 
./crate -d -Cpath.conf=/crate-data/config

It will generate this error

/usr/local/crate/bin/crate: 116: /usr/local/crate/bin/crate: [[: not found

And will not read the configuration file.

Here is what inside the crate file

launch_service()
{
    pidpath=$1
    daemonized=$2
    javaProperties=$3
    if [[ $4 == *"-Cpath.home="* ]]; then
        props="$4"
    else
        props="-Cpath.home=$CRATE_HOME $4"
    fi

**Comment by matriv** [comment]
@leomkkwan 
Thanks for reporting, as a workaround until it's fixed you can change the 1st line in .../bin/crate executable from `#!/bin/sh` to `#!/bin/bash`

**Comment by leomkkwan** [comment]
Thanks for the workaround. 

I've changed the first line of the script to bash; however, it seems like all configuration is ignore except cluster.name

Here is my crate.yml
---------------------
cluster.name: Crate
bootstrap.memory_lock : true
node.name: "ClickTrackPC4"
path.conf: /crate-data/config
path.data: /crate-data/data
path.logs: /crate-data/log
network.host: 172.24.16.171
license.enterprise : false
gateway.expected_nodes: 3
gateway.recover_after_nodes: 2
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping:
  unicast.hosts:
   - 172.24.16.168:4300
   - 172.24.16.208:4300
   - 172.24.16.171:4300
----------- 

When I start the first node by 
./crate -d -Cpath.conf=/crate-data/config

I will get this error

crate@813729-ClickTrack:/crate-data/config$ 2017-08-16 22:30:02,845 main ERROR Unable to create file /usr/local/crate/logs/Crate.log java.io.IOException: Could not create directory /usr/local/crate-2.1.5/logs

The node will be started, but all my configuration excpet cluster name is not load. Including the path.logs and path.data

**Comment by matriv** [comment]
@leomkkwan Are you sure your crate.yml file is readable by the system user owning the crate process (normally crate) and resides under /crate-data/config?

**Comment by matriv** [comment]
@leomkkwan the bug in the startup file has been fixed and will be available with the next hotfix release. If you still have issues feel free to reopen .

**Comment by leomkkwan** [comment]
@matriv  Not sure if you close this for the "bash" script or if the config wasn't load.
"Are you sure your crate.yml file is readable by the system user owning the crate process (normally crate) and resides under /crate-data/config?"

Yes, I was upgrade from 2.0.5, so all file permission should be ok. If I rollback the 2.0.5, everything will be to normal.

**Comment by matriv** [comment]
@leomkkwan Could you please apply the change as shown here:
https://github.com/crate/crate/pull/6138/files
to your startup script and try again?

**Comment by leomkkwan** [comment]
Yes, it fixed the original error.

but

It looks like the path.logs setting in crate.yml file is ignored. It always try to write to installation directory/logs

Real thanks for the quick fix.

Leo

**Comment by matriv** [comment]
@leomkkwan We'll investigate the issue with `path.logs` too and come back to you.

**Comment by matriv** [comment]
@leomkkwan meanwhile you can try to define the logs path from command line with `-Cpath.logs=/path/to/logs`

**Comment by mxm** [comment]
Sorry for the inconvenience @leomkkwan. We have fixed the problem and the next hotfix release will contain the fix. It should be out tomorrow. Here is the corresponding PR: #6165.
