### ISSUE TITLE
ProcessClusterEventTimeoutException

### ISSUE THREAD

**Issue by xiaolongge904913** [crate/crate#6197]
**CrateDB version**: 2.1.5

**JVM version**:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
OS of virtual machine : Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Problem description**:
```
cr> alter table usr_sod.surf_wea_chn_pre_min_tab set (number_of_replicas = '2');
SQLActionException[ProcessClusterEventTimeoutException: failed to process cluster event (update-settings) within 30s]
```
    I hava a partitioned table with 2.5 billion records and 120 partitions ,every partition has 240 shards.
I imported from json file ,and set replicas to 0 when the table was created  , after the import succeeds, 
I adjust the number of replicas to 2 using "alter table usr_sod.surf_wea_chn_pre_min_tab set `(number_of_replicas = '2')`" ,
an "ProcessClusterEventTimeoutException" occor...  I can't find any relevant configuration items on the doc page,can someone help me ,thanks!

**Comment by joemoe** [comment]
how does your cluster look? how many nodes do you run?

**Comment by xiaolongge904913** [comment]
## Hardware configuration
nodes num : 5
cpu : 48 cores
mem : 64G

# Tables status
Health : warning
Configured Replicas : 0
Configured Shards : 53280
Underrepl. Shards : 103083

**Comment by seut** [comment]
@xiaolongge904913 For a 5 nodes cluster with 48 cores this setup creates way to much shards, which can result in this exception as it takes too much time to process all this 50k shards. Please see https://crate.io/docs/crate/guide/best_practices/sharding.html to figure out the best shard definition for your use case. Also note that on a partitioned table, one can adjust the number of shards for new partitions anytime (see https://crate.io/docs/crate/reference/sql/partitioned_tables.html#alter). This is great for scaling out later when needed.
Anyway we'll look into this issue and check if we can improve here even with that very high number of shards ratio vs number of nodes/cores.

**Comment by seut** [comment]
I'm closing this ticket now as we don't see how we can improve this and we're thinking your setup would lead to different issues (performance etc.) as well.

**Comment by xiaolongge904913** [comment]
Thanks very much !
