### ISSUE TITLE
Joins on subqueries

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6235]
This might be the same as #4759. Joins on subqueries allow a lot of advanced SQL queries and aggregation. I've already ran into that limitation. Are there any plans for supporting it?

**Comment by joemoe** [comment]
hi @SneakyMax, we are heading towards that direction, but need to continue working on the whole subselects implementation. so we don't have an ETA yet.

**Comment by SneakyMax** [comment]
Cool glad to hear it's coming eventually! Can close if you'd like

**Comment by joemoe** [comment]
i'll leave it open and close it once implemented.

**Comment by joemoe** [comment]
hi @SneakyMax, just recognized I was wrong. This was released with CrateDB 2.1. I mixed something up. 
See `Added support for joins on virtual tables.` in https://crate.io/docs/crate/reference/release_notes/2.1.0.html.

**Comment by SneakyMax** [comment]
Oh nice! I should upgrade my cluster!
