### ISSUE TITLE
INSERT: ON DUPLICATE KEY DO NOTHING

### ISSUE THREAD

**Issue by hatzibod** [crate/crate#6323]
According to: 
https://crate.io/docs/crate/reference/sql/reference/insert.html
there is support for ON DUPLICATE KEY UPDATE when inserting data.
It would also be convenient and enhance performance for some use-cases if  something like ON DUPLICATE KEY DO NOTHING existed.
Much like the ON CONFLICT DO NOTHING in postgres.
https://www.postgresql.org/docs/current/static/sql-insert.html

**Comment by joemoe** [comment]
thanks @hatzibod, at the moment there is not too much buzz around that feature, but i'll put it on the backlog and keep you up to date.

**Comment by asicoe** [comment]
We would be interested in this feature as well! Super useful for writing to Crate from a parallel app with at least once semantics end to end which I imagine a lot of people are doing. This feature is a must for efficient upserts!!!

**Comment by asicoe** [comment]
Note, I was having a separate conversation with @matriv from Crate.io on this gist:
 [https://gist.github.com/matriv/0ca76afceb35c419ac8c57d741539e88](url) where we were looking at fine grained exception handling for doing batch upserts into CrateDB but really it doesn't seem to be possible. Even if it was ON CONFLICT DO NOTHING is really the fix! What do you guys say?

**Comment by joemoe** [comment]
thanks for your inputs @asicoe. we'll count that as an upvote.

**Comment by dobe** [comment]
since it is not possible to distinguish between a duplicate key and any other exception when using unnest it would be very helpful

**Comment by venks61176** [comment]
Can we change these syntax as per POSTGRES. It often causes issue in terms of using JDBC with Postgress dialect especially with frameworks like JOOQ

**Comment by mfussenegger** [comment]
@venks61176 do you have a code sample for JOOQ or can paste a snippet of the generated SQL? There is work in progress to support the postgres syntax, but we'd like to get a better picture of which options we would need to support.

**Comment by mxm** [comment]
`ON CONFLICT DO NOTHING` is now implemented in the latest master as per https://github.com/crate/crate/pull/7094. `ON CONFLICT (..) DO UPDATE SET` was also added beforehand.

The first release containing these features will be Crate 3.0. Please keep us posted if you try it out.
