### ISSUE TITLE
JOIN of 2 tables with a lot of data is not optimized

### ISSUE THREAD

**Issue by tellezb** [crate/crate#6326]
**Environment**:
Crate 1.0.5
Amazon Linux AMI 2016.09.0.20160923 x86_64 HVM GP2
3 AWS t2.small nodes
CrateDB version 1.1.6

**Problem description**:
The following query joins 2 tables. When the tables have dozens or hundreds of records (per partition) then the query returns just fine (and relatively quickly).  When the tables have roughly 2 million records each with about 100,000 records per partition then the query starts taking a couple of minutes to return and often results in an exception.

The query filters both tables by their partition value which should result in a single partition being queried. The target partition has 135,239 records. Furthermore, the other filters against table1 filter the data down to less than 5,000 records. And the query only requests a small handful of column. A join of 5,000 records should not result in a "data too large" exception.

When running this same test on a cluster with less data and larger/powerful nodes (c4.large) the exception does not occur ... but the join still takes a couple of minutes to return data.

It seems that the JOIN operation is not optimized for tables which have a lot of data. NOTE: I have not run this same test against non-partitioned tables.

**Query**:
> SELECT table1.id, table1.partition_value, date, table1.device_time_zone, table2.table3_date as first_date 
FROM my_schema.table1
	LEFT JOIN my_schema.table2
		ON table1.id = table2.table1_id             
			AND table2.table1_partition_value = '2017-09-01'
WHERE first_date IS NULL     
  AND table1.filter_id = 1427
  AND table1.partition_value = '2017-09-01'
  AND table1.day = 1504224000000
LIMIT 100;

**Exception**:
> SQLActionException[CircuitBreakingException: [query] Data too large, data for [nl-merge: 3] would be larger than limit of [573584179/547mb]]

**Table definitions**:

>  -- Partitioned by month
CREATE TABLE IF NOT EXISTS "my_schema"."table1" (
   "filter_id" LONG,
   "date" TIMESTAMP,
   "day" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', "date"),
   "device_time_zone" STRING,
   "first_date" TIMESTAMP,
   "id" LONG,
   "partition_value" STRING,
   PRIMARY KEY ("id", "partition_value")
)
CLUSTERED INTO 6 SHARDS
PARTITIONED BY ("partition_value")
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   number_of_replicas = '0-2',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.disable_flush" = false,
   "translog.flush_threshold_ops" = 2147483647,
   "translog.flush_threshold_period" = 1800000,
   "translog.flush_threshold_size" = 209715200,
   "translog.interval" = 5000,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true
)

> -- Partitioned by month
CREATE TABLE IF NOT EXISTS "my_schema"."table2" (
   "table1_date" TIMESTAMP,
   "table1_id" LONG,
   "table1_partition_value" STRING,
   "table3_date" TIMESTAMP,
   "table3_id" LONG,
   "table3_partition_value" STRING,
   PRIMARY KEY ("table1_id", "table1_partition_value", "table3_id")
)
CLUSTERED INTO 6 SHARDS
PARTITIONED BY ("table1_partition_value")
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   number_of_replicas = '0-2',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.disable_flush" = false,
   "translog.flush_threshold_ops" = 2147483647,
   "translog.flush_threshold_period" = 1800000,
   "translog.flush_threshold_size" = 209715200,
   "translog.interval" = 5000,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true
)

**Comment by joemoe** [comment]
hi @tellezb, yes this is true. there is potential to improve that. it is on our roadmap but has no eta yet.

**Comment by olivertheobald** [comment]
Hi, I also reported this on slack. The biggest problem is joining multiple columns.

**Comment by mfussenegger** [comment]
Could you retry this in the latest 3.0 version and report back? We made a lot of improvements in the JOIN area since 1.0
