### ISSUE TITLE
XPack errors when using Kibana with Crate

### ISSUE THREAD

**Issue by dsmithson** [crate/crate#6353]
I'm trying to get extra use from our Crate Cluster by putting Kibana over top for log aggregation - both applications running in stock Docker containers.  I get 'X-Pack plugin is not installed on Elasticsearch cluster' messages in Kibana (see image below) after running a simple [docker-compose.yml](https://github.com/crate/crate/files/1354135/docker-compose.yml.txt) to setup a Crate and Kibana.  In my compose file I'm setting a number of environment variables  on the Kibana container to disable XPack extensions. 

The Crate website has a [Kibana question page](https://crate.io/faq/visualization/can-i-use-kibana-with-crate/) which states that Kibana can work with Crate.  Does anyone have any experience with getting the Crate and Kibana Docker container images to work together?

![image](https://user-images.githubusercontent.com/334865/31153641-29f11b5e-a857-11e7-96ed-f0a736a4082a.png)

**Comment by joemoe** [comment]
hi @dsmithson, does this work with your docker setup?

as we don't officially support using CrateDB via the Elasticsearch API we also don't officially support using Kibana with CrateDB. We have users doing that, but we don't run any automated tests on that.

**Comment by dsmithson** [comment]
Hi @joemoe, I am trying to use it with my Docker setup, and in my issue I attached a docker-compose file that will create a single crate and a single Kibana container to reproduce the xpack issue shown in the screenshot.  Hopefully someone running Kibana against Crate can chime in with how they are running it?

**Comment by joemoe** [comment]
ok, i'll check if there's someone. i can't promise anything.

**Comment by dsmithson** [comment]
I was able to get Kibana working and connecting to CrateDB's ElasticSearch API endpoint by making a new container from the official Kibana container which uninstalls the X-Pack stuff.  In case it comes up for anyone else, I'm attaching the Dockerfile I used to build this, as well as a sample docker-compose.yml file that will stand up a working Crate and Kibana instance for testing.

The Dockerfile is pretty simple:

FROM docker.elastic.co/kibana/kibana:5.4.3
RUN bin/kibana-plugin remove x-pack && \
    kibana 2>&1 | grep -m 1 "Optimization of .* complete" # [1]

[Kibana - Dockerfile And Compose.zip](https://github.com/crate/crate/files/1451052/Kibana.-.Dockerfile.And.Compose.zip)
