### ISSUE TITLE
unable to use properties other than number_of_replicas in create/alter statment

### ISSUE THREAD

**Issue by craig8** [crate/crate#6374]
**CrateDB version**:
2.0.7

**JVM version**:

**OS version / environment description**:
ubuntu 16.0.4

**Problem description**:
Issue with properties in create table statement.  The following code produces Invalid property "number_of_shard_copies" passed to [ALTER | CREATE] TABLE statement]  Or whatever property except for number_of_replicas.  What am I doing incorrect with the following: 

**Steps to reproduce**:

CREATE TABLE IF NOT EXISTS foo.data(
            ...        
       )
       CLUSTERED BY (topic) INTO 10 SHARDS PARTITIONED BY (week_generated)
        with (number_of_replicas = 3, number_of_shard_copies = 1);

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @craig8, how does the error manifest? is there an error shown?

**Comment by joemoe** [comment]
@craig8 did you try anything else then `number_of_shard_copies` because `number_of_shard_copies` is no real setting. i know this is in the documentation but it's just there to illustrate how many shards are there. (https://crate.io/docs/crate/reference/en/latest/sql/reference/create_table.html#write-wait-for-active-shards)

**Comment by craig8** [comment]
Yes I tried min_replicas, max_replicas and refresh_interval with the same result.

**Comment by joemoe** [comment]
@craig8, can you please show me the query you run and the corresponding error output? this would really help.

**Comment by craig8** [comment]
All of the following produce 
````
Error!

SQLActionException[SQLParseException: Invalid property "min_replicas" passed to [ALTER | CREATE] TABLE statement]
````

````
CREATE TABLE IF NOT EXISTS foo.data(
  source string,
  topic string primary key,
  ts timestamp NOT NULL primary key,
  -- Full texted search index on the topic string
  INDEX topic_ft using fulltext (topic),
  -- must be part of primary key because of partitioning on monthly
  -- table and the column is set on the table.
  month as date_trunc('month', ts) primary key)
partitioned by (month)
CLUSTERED INTO 6 SHARDS
with (number_of_replicas = 3, min_replicas = 1);
````
or
````
CREATE TABLE IF NOT EXISTS foo.data(
  source string,
  topic string primary key,
  ts timestamp NOT NULL primary key,
  -- Full texted search index on the topic string
  INDEX topic_ft using fulltext (topic),
  -- must be part of primary key because of partitioning on monthly
  -- table and the column is set on the table.
  month as date_trunc('month', ts) primary key)
partitioned by (month)
CLUSTERED INTO 6 SHARDS
with (min_replicas = 1);
````
or
````
CREATE TABLE IF NOT EXISTS foo.data(
  source string,
  topic string primary key,
  ts timestamp NOT NULL primary key,
  -- Full texted search index on the topic string
  INDEX topic_ft using fulltext (topic),
  -- must be part of primary key because of partitioning on monthly
  -- table and the column is set on the table.
  month as date_trunc('month', ts) primary key)
partitioned by (month)
CLUSTERED INTO 6 SHARDS
with (number_of_replicas = 3, number_of_shard_copies = 1);
````

**Comment by mfussenegger** [comment]
`number_of_shard_copies` and `min_replicas` are both invalid table-settings. The error message you're getting is expected.

Did you try those because of the documentation https://github.com/crate/crate/blob/b70eda7cc66c5407d73b96de987453f05c1d2a77/blackbox/docs/sql/reference/create_table.txt#L284 and https://github.com/crate/crate/blob/b70eda7cc66c5407d73b96de987453f05c1d2a77/blackbox/docs/sql/reference/create_table.txt#L242 ?

**Comment by matriv** [comment]
@craig8 `min_replicas` and `number_of_shard_copies` are not valid settings for `CREATE TABLE` and `ALTER TABLE` statements. In your DDL statements, only `number_of_replicas` is a valid setting. Please check the [documentation page](https://crate.io/docs/crate/reference/en/latest/sql/reference/create_table.html#with-clause) where you can see all valid settings as light blue section headers.

**Comment by craig8** [comment]
@mfussenegger Yes that is exactly why I used those.  

@matriv I have read that documentation page...I even tried (the blue heading write.wait_for_active_shards) however that didn't work either.

**Comment by joemoe** [comment]
@craig8 can you provide the output when using `write.wait_for_active_shards`.

**Comment by joemoe** [comment]
hi @craig8, i'm closing this issue for now. feel free to reopen it whenever you can provide the output i asked for and this is still an issue to you.
