### ISSUE TITLE
field name bug while using subquery

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6387]
**CrateDB version**: 2.2.0

**JVM version**: 1.8.0_131

**OS version / environment description**: Linux Mint 18.1 Serena

**Problem description**:

![image](https://user-images.githubusercontent.com/2795798/31434208-acaa5b04-aeb6-11e7-8353-43dab7169b38.png)

first query has a bug. it is showing wrong field name when I use subquery.

I think first query should show field names as ( dst_ip, test, cnt1, cnt2 ).

but second query is showing correct field name when I use simple query.

I think two fields are referencing same field object.

thanks.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @nicetip, yes this looks wrong. we'll fix that.

**Comment by matriv** [comment]
@nicetip thanks for reporting. The fix will be available with the next hotfix releases.
