### ISSUE TITLE
Admin UI: Better copy pasting of values

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6441]
Really trivial thing here:

When copying a value in the admin UI from a query result, like this:

![selection_102](https://user-images.githubusercontent.com/342540/31961819-c04a4076-b8b0-11e7-8617-977d0532299a.png)

If I triple click the value, it copies three newlines too:

```


AV4bRY-6MQ2-7oh-NVTT

```

It would be great if that only copied the value!

**Comment by m-kharbat** [comment]
Hey @SneakyMax, I'm not able to reproduce this issue. Can you give me more information on your crate version, your browser version and what editor you are pasting this into ?

**Comment by SneakyMax** [comment]
Oh weird! We're on crate 2.1.6, and I'm using Firefox 57. I tried in chrome and it behaves a lot better - only one newline copied. I'm usually pasting it into sublime, but I tried several places and it does the same thing.

Oh, also it wasn't happening when I tried copying timestamps. Only string values.

**Comment by mxm** [comment]
Can confirm the bug (also Firefox 57), copying a string leads to the following output:

```


Copied String

```

**Comment by m-kharbat** [comment]
@SneakyMax the issue has been fixed and will be available in 2.1.9 release

**Comment by mxm** [comment]
Just curious, could you post the hash to the commit which fixes this?
