### ISSUE TITLE
problem of enable es with crate

### ISSUE THREAD

**Issue by xycloud** [crate/crate#6461]
version: lastest version
env: docker

I enable the elasticsearch by add ```es.api.enabled: true``` in crate.yml, but nothing happend, cannot still access port 4300

**Comment by joemoe** [comment]
hi @xycloud,

as stated in our documentation `es.api.enabled` only enables the elasticsearch api via http.
https://crate.io/docs/crate/reference/en/latest/configuration/node.html#elasticsearch-http-rest-api

so you can use the http port 4200 and run stuff like `GET /_cat/master?v`.

4300 is used for internal cluster communication.

what do you want to do via 4300?

**Comment by xycloud** [comment]
thanks man!
