### ISSUE TITLE
Query on unknown columns?

### ISSUE THREAD

**Issue by abrenneke** [crate/crate#6553]
**Use case**:

Dynamic columns are great, you can add them without worrying about adding them beforehand. However, for SELECTS, you still have to add columns beforehand.

I'd like the ability (as NoSQL stuff often does) to query on columns that don't (yet) exist.

RethinkDB for example, doesn't care about this:

```
r.db('db').table('MyTable').filter({ doesnt_exist: 'foo' })
```

It just returns no rows.

**Feature description**:

I'm not sure if this would be a table-level option, or some special SQL syntax like `OPTIONAL nonexistent_column`. It'd return NULL for that column, obviously.

---

**Related issues**

- [Query syntax to check for existence of a key in a dynamic object column](https://github.com/crate/crate/issues/9383)

**Comment by mfussenegger** [comment]
This would certainly be possible.

Could you elaborate on your use case a bit? Why would you want to write queries which use columns which may not exist? - What's the reason to not include it in the table schema?

We'd like to understand this a bit better to be able to prioritize / decide if we want to support something like this. So far the reason for the current behaviour is that it prevents typo-bugs.

**Comment by SneakyMax** [comment]
It's not hugely important. For us:

- Event taxonomy is written beforehand in a separate spreadsheet
- Phone apps implement this and send fields based on that taxonomy
- What they send with events (which gets translated to a `object['column']`) isn't populated in the DB until they actually send data
- I'd like to write queries expecting that data to come in the future once apps start sending it

But I can certainly think of hypothetical scenarios where it's actually user input that translates into columns, and where the columns are completely dynamic. Whether that's a good idea, hard to say :P

It's easy enough to run an `ADD COLUMN` right now (though it's very frustrating to not be able to modify or delete columns)
