### ISSUE TITLE
Throwing Exceptions on DELETE when records not present.

### ISSUE THREAD

**Issue by jeffnappi** [crate/crate#6556]
**CrateDB version**: 2.2.3

**JVM version**: OpenJDK 1.8.0_151

**OS version / environment description**: Ubuntu 16.04

**Problem description**:

`DELETE` throws an SQLActionException when a document is not present. This is far from standard SQL behavior.

**Steps to reproduce**:

Try to `DELETE` a non-existent record from a table.

![peek 2017-11-20 14-03](https://user-images.githubusercontent.com/393868/33041476-a8bf5080-cdfb-11e7-9530-77ed877328ff.gif)

**Comment by mfussenegger** [comment]
Crazy that this regression wasn't caught by our test suite. Thanks for reporting.

(This seems only to happen when the filter is on a primary key column, other delete queries seem to work as expected)

**Comment by jeffnappi** [comment]
At least there will be test coverage for this now :smile:

**Comment by mfussenegger** [comment]
Fixed this via https://github.com/crate/crate/pull/6558  - will be part of the next hotfix release (2.2.4) which will probably go out sometime this week or early next week.
