### ISSUE TITLE
Error when using IN with _id and aggregation

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6564]
**CrateDB version**: 2.1.6 (can't test 2.2.x, maybe it's been fixed)

**JVM version**:

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version / environment description**: Ubuntu 16.04 LTS

**Problem description**:

I get an error when using IN in combination with `_id` and aggregation/grouping:

```
SQLActionException[SQLParseException: invalid argument for ANY expression]
```

**Steps to reproduce**:

```
SELECT COUNT(*) FROM table WHERE _id IN ('some_id')
```

**Comment by mxm** [comment]
Thanks for reporting. The problem has been identified and is about to be fixed.
