### ISSUE TITLE
object type query on system table (information_schema.table_partitions)

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6601]
**CrateDB version**: 2.2.4 (stable)

**JVM version**: openjdk version "1.8.0_151"

**OS version / environment description**: CentOS Linux release 7.4.1708 (Core)

**Problem description**:

I can't query values['@partition'] from information_schema.table_partitions table.

other normal table works well.

I thought '@' cause exception, so I did it again without '@'.

But it's not working also.

I think it's a bug.

![image](https://user-images.githubusercontent.com/2795798/33471715-ffec0ccc-d6b1-11e7-9afc-99b16c457fbd.png)

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment]
Thanks for reporting. We'll take a look at this.

**Comment by mfussenegger** [comment]
We've fixed this with https://github.com/crate/crate/pull/6611 - the fix will be part of the next hotfix release (2.2.5)
