### ISSUE TITLE
insert delay when a data node leave

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6618]
**CrateDB version**: 2.2.4 (stable)

**JVM version**: openjdk version "1.8.0_151"

**OS version / environment description**: CentOS Linux release 7.4.1708 (Core)

**Problem description**:

I'm testing how crate cluster is stable.

With 1 master, 3 data nodes.

Every data nodes inserts about 20k records per second with copy from query.

About 10 minutes later after indexing start, I killed 1 data node.

Then other data node's copy from query stopped occuring exception.

I can understand until here, cause 1 node is disappeared.

Then I tried to restart copy from query or insert query.

But inserting is very very slowly processed. 

I found, when a data node leave, cluster status change to yellow, and about 2 minutes later in my case,

it changes back to green.

Then, when cluster is green status, I could insert data.

Is this normal?

I expected, inserting will keep going with almost same rate (20k/s).

I can't sure whether it is bug or normal operation.

If it's a normal operation, How can I minimize delay of inserting?

Sorry for my poor english. 

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by seut** [comment]
@nicetip Can you please paste your table creation statement?
It could be related to our recent change to wait for all active shards by default, see http://crate.readthedocs.io/en/latest/sql/statements/create_table.html#sql-ref-write-wait-for-active-shards. This was done do be reliable at most by default.
I guess that in your scenario, at least 1 replica is defined and so the inserts will only continue after new replica shards are created on the still running nodes (or the inserts will run into timeouts, default 30s, while waiting for the replica shards to become active again).
Changing the `write.wait_for_active_shards` to 1 (just required the primary shard to be active) should result in continuous fast successful writes even with a configured replica while a node drops out of the cluster. Be aware that by this, writes to replicas are not ensured.

**Comment by nicetip** [comment]
Thank you very much.

I just finished test with option you said.

As you pointed, it's exactly working with same insert rate. 

That's what I've expected.

I checked my table options with 'show create table' query and 'write.wait_for_active_shards' was set 'all'.

I had to study more, sorry bothering you and thanks again.

**Comment by seut** [comment]
you're welcome 🙂
