### ISSUE TITLE
Admin panel SQL input: inconsistent tabbing

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6639]
**CrateDB version**: 2.2.3

**JVM version**: `Java(TM) SE Runtime Environment (build 1.8.0_144-b01)`

**OS version / environment description**: Ubuntu 16.04

**Problem description**: 

The tab-key and auto-indentation are inconsistent when editing SQL:

- Pressing tab inserts a `\t`
- Auto-indentation adds spaces

**Steps to reproduce**:

- Enter `<tab>SELECT<enter>FROM`
- You now have SQL that looks like this (but appears aligned):

```
\tSELECT
    FROM
```

Super minor, a bit annoying is all :D. I guess I'd prefer that tab inserts spaces, but I'm sure others disagree

**Comment by m-kharbat** [comment]
Hi @SneakyMax which browser are you using ?

**Comment by SneakyMax** [comment]
@m-kharbat I generally use Firefox Developer Edition (currently on 58)

But I tried Chrome and it exhibits the same behaviour.

**Comment by m-kharbat** [comment]
hey @SneakyMax this behaviour is fixed and will be available in 2.3
