### ISSUE TITLE
SQL Input shows horizontal scrollbar

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#6640]
When we updated to Crate 2.2, this horizontal scroll bar started appearing for me on the SQL input:

![selection_116](https://user-images.githubusercontent.com/342540/33735937-b5330314-db45-11e7-9260-fcbb9955a8e4.png)

Appears for me in both:
- Firefox 58.0b7 in Linux
- Chrome 62 on Mac OS

**Comment by joemoe** [comment]
hi @SneakyMax we are working on this.

**Comment by m-kharbat** [comment]
hey @SneakyMax this is fixed in 2.2.5
