### ISSUE TITLE
disabling _doc, _raw system columns

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6643]
**CrateDB version**: 2.2.4 (stable)

**JVM version**: openjdk version "1.8.0_151"

**OS version / environment description**: 

**Problem description**:

Hello?

Is it possible to disable saving _doc, _raw columns?

I think in many case, _doc, _raw columns are useless, just increasing IO load.

And in my case, I don't need that columns.

So I tried to find how to disable, but I couldn't.

If there is no way to do it yet, I hope it's implemented in future.

Thanks.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by seut** [comment]
@nicetip CrateDB is using the _doc(which is a map view of the source _raw document)/_raw column  internally e.g. to implement query-then-fetch strategies. there is no way to disable it nor is it planned for the future.
