### ISSUE TITLE
Filebeat integration or another way to ingest JSON formatted logs

### ISSUE THREAD

**Issue by bradleat** [crate/crate#6646]
I tried to see if the es.api would enable filebeat compatability out of the box, but it does not.

Currently I am getting an index_not found exception from filebeat:

`logcollector_1  | 2017/12/08 22:13:47.074725 client.go:447: WARN Can not index event (status=404): {"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"filebeat-2017.12.08","index_uuid":"_na_","index":"filebeat-2017.12.08"}`

I guess one problem would be that crate expects a fixed schema while es mappings can change on the fly as new data comes in?

Does anyone know a quick way of getting filebeat working with crate or otherwise a method of sending json formatted logs to crate (hopefully in bulk with something that is aware of back pressure)?

**Comment by chaudum** [comment]
Hi @bradleat 
To load load JSON files into CrateDB you can use the `COPY FROM` statement.

From the docs:
> The nodes in the cluster will attempt to read the files available at the URI and import the data. These files have to be UTF-8 encoded and contain a single JSON object per line. Any keys in the object will be added as columns, regardless of the previously defined table. Empty lines are simply skipped.
 https://crate.io/docs/crate/reference/en/latest/sql/statements/copy_from.html
