### ISSUE TITLE
Count query with sub selecting WHERE false returns invalid value

### ISSUE THREAD

**Issue by burnes** [crate/crate#6653]
The `WHERE false` query used in a sub select of a count query returns the total and ignores the filter. 

**CrateDB version**:
2.2.4

**JVM version**:
8

**OS version / environment description**:
OSX

**Problem description**:

To gain a query which returns no results in SQLAlchemy I used `query.filter(sql.false())`. The result set is OK for normal queries, but the count query returns more results than expected. I realized that the raw query does not work in Crate.

**Steps to reproduce**:

```
CREATE TABLE test (a STRING);
INSERT INTO test (a) VALUES ('Hello World');
SELECT * FROM test WHERE false;  // returns 0 rows
SELECT COUNT(*) FROM test WHERE false limit 100;  // <-- returns 0
SELECT COUNT(*) FROM (SELECT * FROM test WHERE false) AS anon limit 100;  // <-- returns 1
```

**Comment by matriv** [comment]
@burnes Thanks for reporting.

It's easily reproducable and will investigate.

**Comment by matriv** [comment]
@burnes The fix will be available with the next hotfix release.
