### ISSUE TITLE
Update Kubernetes documentation

### ISSUE THREAD

**Issue by mindscratch** [crate/crate#6667]
**Use case**:

Deploy a production-ready Crate cluster to Kubernetes.

**Feature description**:

[Documentation](https://crate.io/docs/crate/guide/en/latest/scaling/kubernetes.html) already exists but is out-of-date. For example, PetSet has been [replaced](https://kubernetes.io/docs/tasks/run-application/upgrade-pet-set-to-stateful-set/) by StatefulSets, etc.

**Comment by joemoe** [comment]
hi @mindscratch, we will check and update that. thanks for reporting.

**Comment by Autophagy** [comment]
Hi @mindscratch - thanks for bringing this to our attention. I've updated the Kubernetes documentation (https://github.com/crate/guide/commit/51beb3a18c47a65438fca2e90eca333ab0730b6b) to be more in line with the current state of Kubernetes and CrateDB. This includes changing the pod type from PetSet to StatefulSet, including an init container for setting a value needed to pass the bootstrap checks, as well as exposing the postgres endpoint. Please let us know if you spot anything else :slightly_smiling_face:

**Comment by mindscratch** [comment]
Thanks.
