### ISSUE TITLE
build

### ISSUE THREAD

**Issue by chengxuwei** [crate/crate#6668]
**CrateDB version**:

**JVM version**:

**OS version / environment description**:

**Problem description**:

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
@chengxuwei can you be a little bit more specific?

**Comment by joemoe** [comment]
closing this for now, when you have more information feel free to reopen it.

**Comment by chengxuwei** [comment]
![image](https://user-images.githubusercontent.com/1515544/33928832-3d15dea6-e022-11e7-8b4e-58c78a7d4295.png)
gradlew distInstall can't find symbol for "org.elasticsearch.cluster*" I'am build on windows7 or Centos7.4

**Comment by Autophagy** [comment]
This happens if you do not check out the upstream branches in the repository. Try `git submodule update --init` and building again.
