### ISSUE TITLE
feature request: values list

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6691]
**Use case**:

In my case, I hope to join fixed values with query result.
But I think there is no way to generate multiple record by query in crate.
Though I can solve this by creating/inserting data into a table, It is tiresome.
So I think this feature will be very useful.

**Feature description**:

following link describes well.
https://www.postgresql.org/docs/9.4/static/queries-values.html

**Comment by mfussenegger** [comment]
Maybe you could use unnest (https://crate.io/docs/crate/reference/en/latest/general/builtins/table-functions.html#unnest-array-array) as an alternative?

VALUES is something we do want to support eventually, but we currently have no ETA.

**Comment by nicetip** [comment]
Thank you. it's very helpful.

**Comment by mfussenegger** [comment]
We added [VALUES](https://crate.io/docs/crate/reference/en/latest/sql/statements/values.html) in 4.1
