### ISSUE TITLE
group by IP type column with null value

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6701]
**CrateDB version**: 2.2.5

**JVM version**: 1.8.0_151

**OS version / environment description**: Ubuntu 16.04.1

**Problem description**:

group by query occurs error when null-IP type value exists. Maybe bug?

Other column types look like work well. 

Thanks.

**Steps to reproduce**:

![image](https://user-images.githubusercontent.com/2795798/34352856-4dff3b2c-ea68-11e7-9a65-c227ee2293af.png)

**Use case**:

**Feature description**:

**Comment by chaudum** [comment]
Hi, this definitely looks like a bug.
If you are interested in contributing a fix, lets us know and we can help you where to start.
Otherwise we will have a look once we get back from christmas holidays.

**Comment by nicetip** [comment]
Of course, I hope to be more helpful.
But I can't sure, I could be.
I've not been using java so long time and crate looks complex for me.
If you teach me how to, I'll try next time.

**Comment by matriv** [comment]
The fix has been merged and will be available with the next hotfix releases.
Thanks for reporting!
