### ISSUE TITLE
Pagination for client support

### ISSUE THREAD

**Issue by taliaga** [crate/crate#6703]
**Use case**:

Are there current plans to support any kind of pagination for the client requests?

If so, do you have any details to share?

**Feature description**:

A simple offset+limit kind of pagination would be useful. I see [elasticsearch uses size&from](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html) but I wanted to know if you have something in mind for the Crate roadmap.

Thanks!

**Comment by matriv** [comment]
CrateDB supports `OFFSET` & `LIMIT`.

If you use the jdbc driver you can use the `fetchSize` and retrieve the results in "batches". For more information check [here](https://jdbc.postgresql.org/documentation/head/query.html)

**Comment by taliaga** [comment]
Thanks for the fast reply and for pointing me out the `OFFSET` option, I totally missed it.
In fact I'm using the python driver, but having `OFFSET` & `LIMIT` should do. 
Cheers & Thanks
