### ISSUE TITLE
Crate docker for 2.2.5 not available

### ISSUE THREAD

**Issue by burnes** [crate/crate#6714]
**CrateDB version**:
2.2.5
**JVM version**:
8
**OS version / environment description**:
OSX
**Problem description**:

Crate docker for version 2.2.5 not available on official `crate` docker hub. `crate/crate` repo delivers a container, but UI shows version 2.2.4 (and version probably is 2.2.4 as a bug fixed in 2.2.5 is still there) 

**Steps to reproduce**:

`docker pull crate:2.2.5`
Error response from daemon: manifest for crate:2.2.5 not found

**Comment by vishuPPatel** [comment]
hii....burnes

can you help me how to modify (add some configuration) crate.yml in docker .

and can you give me demo of  how to use  external (.yml) use in cratedb and use you want to modify the (.yml) this how to work in docker (can you help me how to do that)

**Comment by mikethebeer** [comment]
@vishuPPatel pls check our documentation https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html on how to deploy and manage CrateDB on a docker env.

**Comment by vishuPPatel** [comment]
i Read the document but i want to change multiple time in (.yml) file multiple configuration change here in don't understand the how to follow the for docker (.yml) file ????

**Comment by burnes** [comment]
Thanks for fixing, it's working now.
