### ISSUE TITLE
Where can I find indices for a table?

### ISSUE THREAD

**Issue by mindscratch** [crate/crate#6721]
I'd like to figure out the indices defined for a table. I've been looking at [information_schema](https://crate.io/docs/crate/reference/en/2.1/sql/information_schema.html) but haven't found what I'm looking for.

Thanks

**Comment by mikethebeer** [comment]
We don't expose this information explicitly right now. So in case you want to check if a column is a fulltext index or not there is no other possibility than doing

```sql
show create table my_table;
```

**Comment by mindscratch** [comment]
Thanks. I'm looking at adding support for Crate to [xorm](http://xorm.io/).

**Comment by mxm** [comment]
Cool. Let us know how that works out @mindscratch.
