### ISSUE TITLE
Disabling 32766 limit with Column Store fails

### ISSUE THREAD

**Issue by taliaga** [crate/crate#6733]
**CrateDB version**: 1.0.5 (also 2.2.5)

**JVM version**:

**OS version / environment description**: Official Docker Image

**Problem description**:

I reached the 32766 maximum for a string column as explained [here](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#string), so to work around this according to the documentation [here](https://crate.io/docs/crate/reference/en/latest/general/ddl/storage.html#column-store), I tried to disable `columnstore` and indexing.

The given example to disable storage fails. I believe either the documentation is outdated or maybe I'm missing something :)

**Steps to reproduce**:
Trying to create table as instructed [here](https://crate.io/docs/crate/reference/en/latest/general/ddl/storage.html#column-store)...

`CREATE TABLE t1 (id INTEGER, url STRING INDEX OFF STORAGE WITH (columnstore = false));`

Fails with...

`SQLActionException: BAD_REQUEST 4000 SQLParseException: line 1:51: extraneous input 'STORAGE' expecting {',', ')', 'NOT', 'PRIMARY KEY', 'INDEX'}
`

**Comment by chaudum** [comment]
Hi @taliaga 
The `STORAGE` option for `STRING` columns to disable the column store was only introduced in CrateDB 2.3.0 (which is currently testing).
The links to the documentation are pointing to "latest"; you'd need to select your version of the documentation.

**Comment by seut** [comment]
@taliaga This limitation was introduced with CrateDB 2.0. On versions below (like 1.0.5) turning indexing of by `INDEX OFF` on the related column will support strings > 32kb.

**Comment by taliaga** [comment]
Thank you guys!, I thought 2.2 was the latest since I didn't see pointers to 2.3, sorry about that :)
