### ISSUE TITLE
Go postgresql drivers cannot parse date from crate

### ISSUE THREAD

**Issue by on99** [crate/crate#6735]
**CrateDB version**: 2.2.5

**JVM version**: 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12

**OS version / environment description**: Ubuntu 16.04

**Problem description**:

go drivers cannot parse date from both [pg](https://github.com/lib/pq) and [pgx](github.com/jackc/pgx)

log from lib/pq
`expected end of input, got  +00 AD []`

log from pgx
`parsing time "2018-01-10 00:00:00.000 +00 AD" as "2006-01-02 15:04:05.999999999Z07:00": cannot parse " +00 AD" as "Z07:00" []`

**Steps to reproduce**:

Run crate by 
`docker run -d -p 4200:4200 -p 4300:4300 -p 5432:5432 crate crate -Cnetwork.host=_site_`

Execute the go code
```go
package main

import (
	"log"
	"time"

	_ "github.com/jackc/pgx/stdlib"
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
)

func main() {
	db := sqlx.MustConnect("postgres", "postgres://crate:@localhost:5432/doc?sslmode=disable").Unsafe()
	// db := sqlx.MustConnect("pgx", "postgres://crate:@localhost:5432/doc?sslmode=disable").Unsafe()

	db.MustExec("drop table if exists test")
	db.MustExec("create table if not exists test ( t timestamp )")
	db.MustExec("insert into test values ('2018-01-10T00:00:00Z')")

	time.Sleep(time.Second) // wait until data is queryable, raise the value if no error is printed

	result := []struct {
		T time.Time `db:"t"`
	}{}
	log.Println(db.Select(&result, "select * from test"), result)
}
```

**Use case**:

**Feature description**:

**Comment by mikethebeer** [comment]
@on99 thx for filing this issue. @felixge is it possible that there is an issue with parameter type hints with `pgx` ?

**Comment by mikethebeer** [comment]
I just came across this: 

```go
const pgTimestampFormat = "2006-01-02 15:04:05.999999999"
```

So it seems that `pgx` does not use ISO date format?

**Comment by felixge** [comment]
@mikethebeer I'll try to have a look this weekend.

**Comment by mikethebeer** [comment]
@felixge fyi does the timestamp format in pgx need to be `2006-01-02T15:04:05.999-0700` ?

(got from https://github.com/influxdata/telegraf/pull/3210/files#diff-eb01d7dda9a893d212aaa28bd6073f40R125)

**Comment by felixge** [comment]
@mikethebeer my analysis is that CrateDB's text output format is not confirming to the SQL standard (which requires ISO 8601) and therefor also incompatible with PostgreSQL.

https://www.postgresql.org/docs/10/static/datatype-datetime.html#DATATYPE-DATETIME-OUTPUT

Specifically CrateDB seems to output the timestamp as `2018-01-10 00:00:00.000 +00 AD` here, which is not a valid ISO 8601 format unless I'm mistaken.

So I think CrateDB needs to change here.

**Comment by chaudum** [comment]
@felixge you are right, the TIMESTAMP type is transferred incorrectly from server to client. It has been introduced with a change I did to support also timestamps of dates before Christ, see: https://github.com/crate/crate/commit/a1b1e71346542a43b8e5537bf72a24144b2596dc

**Comment by mikethebeer** [comment]
@felixge thanks for pointing that out. We will take a look on this. 👍

**Comment by matriv** [comment]
Issue has been fixed and will be released with the next hotfix releases.
