### ISSUE TITLE
Can't query

### ISSUE THREAD

**Issue by nicetip** [crate/crate#6740]
**CrateDB version**: 2.3.0 (testing)

**JVM version**: 1.8.0_151

**OS version / environment description**: CentOS Linux release 7.4.1708 (Core)

**Problem description**:

Hello?

Today, suddenly I can't query on crate. look following image.

![image](https://user-images.githubusercontent.com/2795798/34802658-1e6b90d0-f6b2-11e7-8f95-e0eaa8b252c9.png)

Following is crate's log.

![image](https://user-images.githubusercontent.com/2795798/34802769-b76c3870-f6b2-11e7-9c75-8ac16ecf79cb.png)

I think error message means invalid data inserted for some field.

And I tried to track on this.

Maybe it's a our partition field, following image prove this.

![image](https://user-images.githubusercontent.com/2795798/34802974-eee4ec2e-f6b3-11e7-93f7-19a4d9c90d53.png)

As I know, partition_ident is made by hashing partition value.

But long partition_ident(.partitioned.logs.05e32d9h6kqjge9i60o30c1gehp62pj6d5hlq82r64rj4bhh6on30bhhbkp30c9o5ko32b9h60g34chq6cpjkc1o5h76at33e9qnknq3cln78pbibt35eb1j68m42j2c9tbioc9c6oq2oc9c6cono) on image, has small size (may be inserted 1 record) and only one having only long partition name.

I'm inserting data by "copy from" query and table's partition field is defined with timestamp type.

I think "1515589200000traffic] [172.16.0.1]2018-01..." like value inserted for partition field (timestamp type) and made trouble.

This problem solved by deleting that partition by using ES API.

But I can't understand why this happened.

there are 2 of problems.

1. wrong value inserted for timestamp type, this should not inserted.

2. in this situation, can't query for the table at all

Thanks.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by nicetip** [comment]
I could reproduce this again like following.

After define partition field with timestamp type, I inserted wrong value.

![image](https://user-images.githubusercontent.com/2795798/34804865-22026230-f6be-11e7-841b-85659ad79b3a.png)

I think my data was wrong, But still I think it should be possible to query by closing or ignoring that partition(index).

Thanks.

**Comment by mikethebeer** [comment]
@nicetip nice to hear that you solved your issue. This is a known/expected behavior since `copy from` does not validate your data (that's why inserts with `copy from` are so fast). Whereas normal `insert` statements validate the data and convert them if needed.
You will find this information in our [documentation](https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-from.html?#type-casts-and-constraints).

> CrateDB does not check if the column’s data types match the types from the import file. It does not cast the types but will always import the data as in the source file.

**Comment by nicetip** [comment]
Yes! I understand, So I think so too it doesn't need to validate.
But I think it should be possible to query even that situation happened by closing index.
Thanks.

**Comment by seut** [comment]
@nicetip you can close a single partition by:
`ALTER TABLE table_name PARTITION(part_col = val) CLOSE`
see http://crate.readthedocs.io/en/latest/sql/statements/alter-table.html. 

Or you could try to delete the whole partition by:
`DELETE FROM table_name WHERE part_col = val`

**Comment by nicetip** [comment]
I knew that queries.
My point was auto recovery by crate for users.
Your saying also right, I'll close.
Thanks for your comment.
