### ISSUE TITLE
"INSERT INTO SELECT" issue on partitioned table.

### ISSUE THREAD

**Issue by fanwu72** [crate/crate#6744]
**CrateDB version**: 2.2.5

**JVM version**: 1.8.0_74

**OS version / environment description**:  CentOS 6.5

**Problem description**:

I am not able to insert data into a partitioned table. Please refer to the following steps to reproduce.

**Steps to reproduce**:

`cr> create table test_domain_1(ymd string, domain string, area string, isp string, h int, primary key(ymd, domain, area, isp)) partitioned by (ymd, isp);`
`CREATE OK, 1 row affected  (0.133 sec)`
`cr> insert into test_domain_1(ymd, domain, area, isp, h) select '20180109' as ymd, 'dd1.com' as domain, 'cn' as area, 'dx1' as isp, 1 as h;`
`INSERT OK, 0 rows affected  (1.079 sec)`
`cr> select * from test_domain_1;`
+------+--------+---+-----+-----+
| area | domain | h | isp | ymd |
+------+--------+---+-----+-----+
+------+--------+---+-----+-----+
SELECT 0 rows in set (0.009 sec)

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment]
Thanks for reporting. 

I'm not able to reproduce the issue's with the step's you've provided.
```
create table test_domain_1(ymd string, domain string, area string, isp string, h int, primary key(ymd, do
    main, area, isp)) partitioned by (ymd, isp);
CREATE OK, 1 row affected  (0.127 sec)
cr> insert into test_domain_1(ymd, domain, area, isp, h) select '20180109' as ymd, 'dd1.com' as domain, 'cn' 
    as area, 'dx1' as isp, 1 as h;
INSERT OK, 1 row affected  (0.337 sec)

cr> select * from test_domain_1;
+------+---------+------+-----+----------+
| area | domain  |    h | isp | ymd      |
+------+---------+------+-----+----------+
| cn   | dd1.com | NULL | dx1 | 20180109 |
+------+---------+------+-----+----------+
SELECT 1 row in set (0.067 sec)

```
Note that the `INSERT OK` already outputs 1 rows affected instead of 0 as in your case. 

Also note that data is not always immediately visible, to force immediate visibility you'd have to invoke a `REFRESH TABLE test_domain_1` before the SELECT statement. (But I don't think that was the problem in your case, as the INSERT count is already wrong)

Did you test this with a single node or with multiple nodes? Can you also reproduce this on your side if you run this against a fresh node / cluster?

**Comment by fanwu72** [comment]
@mfussenegger Thanks for your quick response.

I just tried the REFRESH command and it didn't work.
I test this with multiple node. Let me setup a single node cluster and try this again.
Will get back to you later.

Best regards,
Ryan

**Comment by fanwu72** [comment]
@mfussenegger 

I am not able to reproduce on a new single node cluster as well. Bad luck.

Best regards,
Ryan

**Comment by mfussenegger** [comment]
Ok thanks for the quick response. I can reproduce this now on a 3 node cluster. We'll investigate it.

**Comment by mfussenegger** [comment]
We've a fix for this which will be part of the upcoming releases (2.2.6, 2.3.1).

As a workaround you could also use the VALUES clause:

```
insert into test_domain_1 (ymd, domain, area, isp, h) values ('20180109', 'dd1.com', 'cn', 'dx1', 1)
```
