### ISSUE TITLE
distinct and object fields

### ISSUE THREAD

**Issue by bolobox** [crate/crate#6754]
**CrateDB version**: 2.2.5

**JVM version**:1.8.0_151

**OS version / environment description**: Linux

**Problem description**:

I am trying to use hibernate 4.3.11.Final as ORM but i finded some problems with some sql sentences hibernate generate.

I have a test table with the following schema:
CREATE TABLE IF NOT EXISTS "doc"."sensor" (
   "description" STRING,
   "id" STRING,
   "metadata" OBJECT (DYNAMIC) AS (
      "a" STRING,
      "b" STRING
   ),
   PRIMARY KEY ("id")
)

and hibernate try to fetch data using this select statement:

select distinct id,description,metadata from sensor

but Crate throws this error:

SQLParseException: Cannot GROUP BY 'metadata': invalid data type 'object'

Is this an expected behaviour or is it a bug?

Thanks for your help

**Comment by seut** [comment]
@bolobox This is somehow expected as a global `distinct` is internally rewritten to a group-by query which does not support object (or array) columns. We will improve the error message to make it less confusing and also update our `distinct` documentation. Thanks for reporting.

**Comment by seut** [comment]
just fyi: using the object keys directly like `select distinct metadata['a'], metadata['b']` will work.

**Comment by seut** [comment]
@bolobox We've improved the error message and also the documentation by https://github.com/crate/crate/commit/ee9d414bf696e911444c4c9827c55ee7282bdd36.

**Comment by bolobox** [comment]
thanks for your support @seut !
