### ISSUE TITLE
Subselect with no result results in slow query

### ISSUE THREAD

**Issue by jukart** [crate/crate#6773]
**CrateDB version**: 2.3.0 (offical crate docker)

**Problem description**:

This query results in high load making crate unresponsive for minutes if the subselect provides no result:

```
SELECT
    CAST(regexp_matches(o_weight['cavity_mold'], '^(.*)-(.*)')[1] AS INTEGER) AS "Cavity",
    regexp_matches(o_weight['cavity_mold'], '^(.*)-(.*)')[2] AS "Mold",
    o_weight['value'] AS "Weight",
    (ROUND((o_weight['value'] - o_weight['target'])*100)/100.0) AS "Deviation"
FROM alpla.metric
WHERE
          type = 'weight'
      AND location['site'] = :site
      AND location['line'] = :line
      AND o_weight['name'] = (
        SELECT o_weight['name']
        FROM alpla.metric
        WHERE
              type = 'weight'
          AND location['site'] = :site
          AND location['line'] = :line
          -- only look back 7 days (performance)
          AND ts >= (CURRENT_TIMESTAMP - 7 * 24 * 60 * 60 * 1000)
        ORDER BY ts DESC
        LIMIT 1
      )
      AND ts >= (CURRENT_TIMESTAMP - 7 * 24 * 60 * 60 * 1000)
ORDER BY "Mold", "Cavity";
```
The query runs against a table with 165 Million rows.

**Comment by seut** [comment]
@jukart as I cannot reproduce it could you please provide us the table schema or at least what columns are used by the primary key and partitioned by if any?

**Comment by seut** [comment]
@jukart also could you maybe check if there is any performance deviation when execution the subquery stand-alone?

**Comment by jukart** [comment]
Hi Sebastian,
sorry for the delay, I am currently at the customer site and can't answer immediately.

I ran the subquery and can not see any performance issues with it.

I'm sorry that I can not provide you a simple and reproducable setup.

**Comment by seut** [comment]
@jukart we've found the issue and are working on a fix. 
jfyi: the issue is that if the subquery returns no row, the where clause of the outer query is still executing using a table scan and a generic filter instead of switching to a no-match as expected. this explains the high load you were observing.

**Comment by jukart** [comment]
@seut thanks great to hear you could already fix it

**Comment by seut** [comment]
@jukart We've fixed this issue by https://github.com/crate/crate/pull/6799, will be release with the next hotfix release. Thanks for reporting.

**Comment by seut** [comment]
@jukart I've forgot to mention that meanwhile this could be handled by putting the subquery inside a `coalesce` function.
Example:
```
AND o_weight['name'] = coalesce((
        SELECT o_weight['name']
        FROM alpla.metric
        WHERE
              type = 'weight'
          AND location['site'] = :site
          AND location['line'] = :line
          -- only look back 7 days (performance)
          AND ts >= (CURRENT_TIMESTAMP - 7 * 24 * 60 * 60 * 1000)
        ORDER BY ts DESC
        LIMIT 1
      ), 'non-matching-dummy-value')
```
