### ISSUE TITLE
CrateDB on Raspberry Pi

### ISSUE THREAD

**Issue by danjal** [crate/crate#6776]
**CrateDB version**: 2.2.5

**JVM version**:
openjdk 9-Raspbian
OpenJDK Runtime Environment (build 9-Raspbian+0-9b181-4bpo9rpt1)
OpenJDK Server VM (build 9-Raspbian+0-9b181-4bpo9rpt1, mixed mode)

**OS version / environment description**: Rasbian 9 Stretch

**Problem description**:
I am trying to learn and evaluate the CrateDB.

I tried installing CrateDB on a Raspberry Pi, following the Linux-Debian instructions, which seemed to work.

Then I changed the /usr/share/crate/config/crate.yml, so that I can access the Admin UI remotely by IP, with this setting network.host: _eth0_

When I restarted the Crate service, I get the error: ERROR: [1] bootstrap checks failed

And examining the logs, I see this: java.lang.UnsupportedOperationException: seccomp unavailable: 'arm' architecture unsupported

Can CrateDB run on Raspberry Pi?

**Comment by mfussenegger** [comment]
One of our dependencies is phasing out support for 32 bit ARM. It currently should still work if seccomp is disabled. (Add `bootstrap.seccomp: false` to the crate.yml)

Please note though that we don't actively test this and don't recommend it as a production system.

**Comment by danjal** [comment]
Thank you,

That worked!
