### ISSUE TITLE
Deallocate function (To close prepared statements - for libpg based clients)

### ISSUE THREAD

**Issue by bputt** [crate/crate#6785]
**Use case**: Add the deallocate function for postgresql compatibility

**Feature description**: I'm currently using [amphp/postgres](https://github.com/amphp/postgres) library to query Crate (2.2.5) and it throws an exception stating that I need a deallocate function. I'm currently catching/ignoring that specific error, but wanted to report to see if it's something you could add.

**Comment by mfussenegger** [comment]
Currently this doesn't have a high priority on our side. Prepared statement functionality is implemented on a protocol level already and most postgres clients utilize them at that level. 

Afaik `PREPARE` and `DEALLOCATE` as implemented in postgres also conflict with the SQL Standard description.

Maybe you could also create an issue in the https://github.com/amphp/postgres repository, asking them to switch to the protocol level prepared statement functionality? (I'd at least be interested in learning why they choose not to use it)

**Comment by DaveRandom** [comment]
Hi o/

To clarify a couple of things:

1) we do (indirectly) use protocol-level statement preparation, both of the underlying APIs we use do that underneath. There does not appear to be any such thing as protocol-level deallocation, or at least libpq does not have an API for it.
2) We attempt to automatically deallocate the statement when it is destroyed, to release server resources when a statement is no longer needed but the connection is left open. [Per libpq documentation](https://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-PQPREPARE), we do this be executing a `DEALLOCATE <statement name>` query.
3) We will look into making this behaviour optional. In the interim, try/catch/forget is an acceptable approach on the client side if it does not cause problems on the server.

**Comment by mfussenegger** [comment]
> There does not appear to be any such thing as protocol-level deallocation, or at least libpq does not have an API for it.

I was referring to the `Close` message (see [extended query protocol flow](https://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY) and [message formats](https://www.postgresql.org/docs/current/static/protocol-message-formats.html))

Here the relevant part:

> The Close message closes an existing prepared statement or portal and releases resources. [..]

I wasn't aware that libpg doesn't expose this. In this case I guess we'll have to prioritize this higher. Thanks for the inputs.

@bputt Be aware that if prepared statements are not properly closed this is similar to a memory leak. The statements will stick around until the client closes the connection.

**Comment by bputt** [comment]
@mfussenegger Any updates on this?

**Comment by mfussenegger** [comment]
@bputt no, unfortunately not and I also can't give an ETA yet. 

Will let you know once I know more

**Comment by bputt** [comment]
@mfussenegger Looking at the PDO documenation: https://crate.io/docs/clients/pdo/en/latest/usage.html#fetch-modes

Since the PDO client is communicating with the HTTP endpoint, does the HTTP endpoint support cursors? Until this issue is resolved, I'd be most interested in the ```fetch``` function which would allow me to pull the rows individually rather than trying to get all of the data.

**Comment by mfussenegger** [comment]
We've no statement level cursor support, so it cannot be used via HTTP.

It's likely that we'll have `DEALLOCATE` in the next release (which will be 3.0)

**Comment by matriv** [comment]
@butt do you maybe have some sample code where you use the `DEALLOCATE` statement?

**Comment by DaveRandom** [comment]
@matriv the use case that led to this bug report is effectively in the tear-down/destructor of a `Statement` handle. Because libpq does not expose a way to send a protocol-level deallocation instruction, both of the PHP extensions that wrap it deal with graceful destruction of a statement handle by issuing a `DEALLOCATE` [ref1](https://lxr.room11.org/xref/php-src%407.2/ext/pdo_pgsql/pgsql_statement.c#80) [ref2](https://github.com/m6w6/ext-pq/blob/1f290da645b717f8f5f15ea647ab9010176088a2/src/php_pqstm.c#L40-L42).

**Comment by bputt** [comment]
Reference to a sample bit of code using the amphp/postgresql lib https://github.com/amphp/postgres/issues/7#issuecomment-360537376

Will this be in a 2.3.x release?

**Comment by matriv** [comment]
@bputt @DaveRandom thank you!

@bputt I'm afraid not, this would be most probably part of the 3.0 release.

**Comment by matriv** [comment]
This feature is implemented and already available in nightly builds.
