### ISSUE TITLE
Percentile cast error

### ISSUE THREAD

**Issue by bputt** [crate/crate#6801]
**CrateDB version**: 2.2.5

**JVM version**: 1.8.0_131

**OS version / environment description**: CentOS 7.latest

**Problem description**: When running a percentile query, if I pass it an array with one value, it throws an error:

```
SQLActionException[ClassCastException: java.lang.Double cannot be cast to [Ljava.lang.Object;]
```

I know I can run ```PERCENTILE(myfield, 0.95)```, but I have a feeling ```[ 0.95 ]``` should work.

**Steps to reproduce**:

```SELECT PERCENTILE(myfield, [ 0.95 ]) FROM mytable```

myfield has a type LONG

**Comment by mfussenegger** [comment]
Thanks for reporting. You're right that ` [ 0.95 ]` should work as fractions argument. We've a fix for this (https://github.com/crate/crate/commit/c8cf423e19b3d7eecdaad7d21c842937c869f660) which will be released with the next `2.3` release
