### ISSUE TITLE
Incorrect handling of object_array (not null condition)

### ISSUE THREAD

**Issue by gwierzchowski** [crate/crate#6834]
I think I found regression bug introduced in 2.3 version, see following SQL statements:
``` sql
CREATE TABLE bag (
    id short PRIMARY KEY,
    ob array(object)
);
INSERT INTO bag(id) VALUES(1);
INSERT INTO bag(id,ob) VALUES(2, [{bbb = 2}]);

SELECT COUNT(*) FROM bag WHERE ob IS NULL;
-- returns 1 in all cases - correct
SELECT COUNT(*) FROM bag WHERE ob IS NOT NULL;
-- returns 0 on crate 2.3.2 - BUG ?!?
-- returns 1 on crate 2.2.6 - correct
```
I'm using in both cases official docker images (1 box "cluster").

**Comment by mfussenegger** [comment]
Thanks for reporting. This is indeed a regression. We've a fix (https://github.com/crate/crate/pull/6838) which will be in the next 2.3 hotfix release.
