### ISSUE TITLE
Optional generated column for insert/update (default constraint)

### ISSUE THREAD

**Issue by bputt** [crate/crate#6842]
**Use case**: I have a field ```createdat``` which is auto generated. I'd expect it to maintain its value regardless of when I update it. Basically looking for a way to enforce a generated column to NOT update its value when an ```UPDATE``` command is issued.

**Feature description**:

Table schema
```
CREATE TABLE mytable(
    somefield STRING,
    createdat TIMESTAMP GENERATED ALWAYS AS CURRENT_TIMESTAMP(3)
)
````

```
INSERT INTO mytable (somefield) VALS ('some string')

'some string', 1517615548000
```

```
UPDATE mytable SET somefield = 'another string' WHERE somefield = 'some string'

'another string', 1517615548000
```

In the above example, it'd be great to persist the original value even if any of the other column values are updated.

**Comment by mxm** [comment]
Hi @bputt! You can just use

```UPDATE mytable SET createdat = createdat, somefield = 'another string' WHERE somefield = 'some string';```

This will keep the initially generated value of the generated column.

**Comment by mxm** [comment]
Closing but feel free to re-open if the answer didn't solve your problem.

**Comment by mfussenegger** [comment]
I guess to support this use case in a better way we'd have to implement the [default constraint](https://www.w3schools.com/sql/sql_default.asp) (which we currently don't support)?

**Comment by bputt** [comment]
I agree, the default constraint would be the preferred option.

**Comment by cmdares** [comment]
ref: apache phoenix for hbase
http://phoenix.apache.org/language/index.html#upsert_values

**Comment by mfussenegger** [comment]
We added support for DEFAULT in 4.0 (https://github.com/crate/crate/pull/8794)
