### ISSUE TITLE
CURRENT_TIMESTAMP doc issue

### ISSUE THREAD

**Issue by bputt** [crate/crate#6843]
**CrateDB version**: 2.2.5

**JVM version**: 1.8.latest

**OS version / environment description**: Centos 7.latest

**Problem description**:
Per your documentation: https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#current-timestamp

Using the ```CURRENT_TIMESTAMP()``` function, it defaults to 3, but if I don't pass anything into that function, I get an error.

```
SQLActionException[SQLParseException: line ....: missing INTEGER_VALUE at ')']
```

That error is valid, but I'm guessing you want to either update the documentation OR allow nothing to be passed into the function and default to 3

**Steps to reproduce**: Creating a table using ```CURRENT_TIMESTAMP()```

Table schema
```
CREATE TABLE mytable(
    somefield STRING,
    createdat TIMESTAMP GENERATED ALWAYS AS CURRENT_TIMESTAMP()
)
````

**Comment by chaudum** [comment]
hi @bputt 
the documentation describes the synopsis of the function correctly:
```
CURRENT_TIMESTAMP [ ( precision ) ]
```
which means that that the part inside `[ ]` is optional.
so you can write either `CURRENT_TIMESTAMP` or `CURRENT_TIMESTAMP(precision)`, however if you use parenthesis, the `precision` is required.
