### ISSUE TITLE
Does shinkansen still exist?

### ISSUE THREAD

**Issue by RVN-BR** [crate/crate#6853]
If so, where can one obtain a copy?

**Comment by mfussenegger** [comment]
shinkansen was a 3rd-party project by skyhigh-networks, but apparently they took the repository offline. On Pypi there is still a source tarball available: https://pypi.python.org/pypi/shinkansen-python

**Comment by RVN-BR** [comment]
Got it...  I assumed this much but thought it would be worthwhile to ask... Does anyone have a mirror?  It seemed like a good project... and worthwhile to help test crate in production... :(

**Comment by mxm** [comment]
There is a download link to the sources on the page posted above. You can just install that one locally or copy it into your project.
