### ISSUE TITLE
Function vs Plugin

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#6856]
I know functions for crate are written in javascript and plugins are written in scala but when would/should I use which? any performance difference?

**Comment by mfussenegger** [comment]
The functions written in javascript are going to be a bit slower. We initially did some benchmarking to compare the performance of functions written in javascript vs functions written with Java. Unfortunately I don't have the results anymore, but the gist was that it depends on how you use them. Or rather, how often the scalars need to be evaluated in the query execution.
In case the scalar functions are only used in the select-list they're usually applied very late. For example

```
select your_function(x), .. from t where [..] order by y limit 100
```

Should result in a plan that causes `your_function(x)` to be evaluated 100 times (after the limit is already applied). In this case the performance difference would be negligible.

On the other hand, if the scalar function is applied before any filtering / result set limitation, you'd very likely be able to see quite a difference.

Also keep in mind that it's generally bad for performance if scalar functions are used in the wrong places in a ``WHERE`` clause. No matter if written as plugin or via javascript.

```
WHERE x = your_function(?)       /// this is cheap, it will utilize the index for `x` and only evaluate the scalar function once

WHERE your_function(x) = ?       /// this is very expensive as it will have to evaluate the scalar *per* row. Won't be able to utilize the index of `x`
```

**Comment by meash-nrel** [comment]
very helpful nuance in that post that should be added to the docs
