### ISSUE TITLE
Time To Live (auto delete) for rows and blobs (with an option to remove the TTL from a row/blob after it was set if possible)

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#6877]

**Comment by chaudum** [comment]
If you submit a feature request here on Github, please be more specific and describe a use-case for your feature.

**Comment by CheyenneForbes** [comment]
for example if I am using crate to store the status of IoT devices and want each record to be available for only 5 minutes then get deleted

**Comment by seanlook** [comment]
Influxdb have option `duration` for a table to set TTL. OpenTSDB could achive this by seting HBbase.

I think deleting partition by partition key with datetime could get to this:
https://crate.io/docs/crate/reference/en/latest/general/ddl/partitioned-tables.html#delete

**Comment by mfussenegger** [comment]
Closing this for now.

We don't have plans to add this any time soon as it can usually be done outside of CrateDB via some form of cronjob that invokes DELETE statements.

We may create some more documentation on how to do that and that's tracked separately.
