### ISSUE TITLE
CrateDB on Raspberry Pi

### ISSUE THREAD

**Issue by danjal** [crate/crate#6886]
**CrateDB version**:

**JVM version**:

**OS version / environment description**: Rasbian 9 Stretch

**Problem description**: Some weeks ago, I installed CrateDB on a Raspberry Pi with this: bash -c "$(curl -L install.crate.io)"
It worked after fixing some seccomp issue.
Now weeks later when I do the same thing, installing CrateDB on Raspberry Pi, I get a message saying this architecture is not supported.
Is it because it is not 64 bit?
Are there any minimum requirements regarding memory and speed?

**Steps to reproduce**:

**Comment by mxm** [comment]
Thanks for reporting. Could you please state the exact error message?

**Comment by danjal** [comment]
Your OS or distribution raspbian is not supported by this install script.
Please visit

    https://crate.io/docs/

For help.

**Comment by mxm** [comment]
Thanks, we have a fix coming up.

**Comment by mxm** [comment]
Should be fixed. Please have a try and feel free to re-open if you encounter difficulties.
