### ISSUE TITLE
Cross Data Centre Replication

### ISSUE THREAD

**Issue by sahil98541** [crate/crate#6901]
How to do this across 2 data centres for version 1.0.2?
I have a lab instance consisting 6 nodes across 2 zones as described in
https://crate.io/docs/crate/guide/en/latest/scaling/multi-zone-setup.html

When i start replication (number of replication =3 ) shard suppose 100 should start 400 shards .
But replication isnt working only 25% replicated data (i.e original copy with 100 shrads running)

Please advic

**Comment by sahil98541** [comment]
How to do this across 2 data centres for version 1.0.2?
I have a lab instance consisting 6 nodes across 2 zones as described in
https://crate.io/docs/crate/guide/en/latest/scaling/multi-zone-setup.html

When i start replication (number of replication =3 ) shard suppose 100 should start 400 shards .
But replication isnt working only 25% replicated data (i.e original copy with 100 shrads running)

Please advice

**Comment by joemoe** [comment]
hi @sahil98541, 

why are you using 1.0.2?
can't you use a more recent version like our latest stable 2.3? 
1.0.2 was released a year ago and we don't support it anymore.

thanks,
joe

**Comment by chaudum** [comment]
Hi @sahil98541 
In order to help you we would need more details about your setup and also the output of log files, as well as the current state of your shards.
I will close this in the meantime until we have further information.
