### ISSUE TITLE
udf arguments error:

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6905]
udf error [2.3.2]:

```sql
CREATE OR REPLACE FUNCTION multiply(long,long,long) RETURNS long LANGUAGE JAVASCRIPT AS 'function multiply(a,b,c){return a*b*c; }';

SELECT multiply(2,3,4)A;
```

`SQLActionException[SQLParseException: The number of arguments is incorrect. Provided: 3 arguments. The following arguments are valid: [2]]`

then

```sql
SELECT multiply(2,3)A;
```

the result is 6

???

**Comment by chaudum** [comment]
Hi @cmdares 
Thanks for reporting. I can confirm the incorrect behaviour, there seems to be a regression in 2.3.x since it works as expected with 2.2.x
We'll investigate.

**Comment by chaudum** [comment]
There seems to be a problem with function overloading when using the default routine schema (doc).
If you specify the routine schema explicitly, if works (as is does not use the built-in `multiply` function:

```sql
SELECT doc.multiply(2, 3, 4) A;
```
Also, if you specify a different function name than the built-in function, it works as expected.

**Comment by cmdares** [comment]
thank you very match! 
I was careless!

**Comment by chaudum** [comment]
@cmdares We added some clarification to the documentation: https://github.com/crate/crate/pull/6913
