### ISSUE TITLE
Group by Concat

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6906]
new feature requirement for group by
1. GROUP BY ROLLUP,CUBE,GROUPING Functions and GROUPING SETS
ref oracle     https://oracle-base.com/articles/misc/rollup-cube-grouping-functions-and-grouping-sets
2. GROUP BY CONCAT
ref mysql      http://www.mysqltutorial.org/mysql-group_concat/
or ref oracle  https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions089.htm#SQLRF30030

**Comment by joemoe** [comment]
closing this till use case is clarified.
