### ISSUE TITLE
window function for analytics

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6907]
window function for analytics
ref oracle     https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions004.htm#SQLRF06174
or ref mssql   https://docs.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql

Hope to give priority to support
sum()
count()
row_number()
over(partition by order by )

**Comment by mfussenegger** [comment]
Thanks for the request, window functions are already on our radar as it was already requested in https://github.com/crate/crate/issues/3934.

Do you have any specific use cases which you would solve with window functions?

**Comment by joemoe** [comment]
closing this till, there is more information.
