### ISSUE TITLE
support euclidean distance function

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6910]
support euclidean distance function

the sql should be:
select info_id,euclidean_dist(fv1,fv2,fv3,fv4,1.22,0.33,0.51,0.58)score from tbl_vector 
where field_1='1' and euclidean_dist(fv1,fv2,fv3,fv4,1.22,0.33,0.51,0.58)<0.03 order by euclidean_dist(fv1,fv2,fv3,fv4,1.22,0.33,0.51,0.58)

or array field fv_array

select info_id,euclidean_dist(fv_array,'1.22,0.33,0.51,0.58')score from tbl_vector 
where field_1='1' and euclidean_dist(fv_array,'1.22,0.33,0.51,0.58')<0.03 order by euclidean_dist(fv_array,'1.22,0.33,0.51,0.58')

ref
es:https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-by-distance.html
solr:https://lucene.apache.org/solr/guide/7_2/function-queries.html     section "dist Function"

**Comment by joemoe** [comment]
thanks @cmdares, we also have that already on our backlog. can you elaborate on your usecase?

**Comment by cmdares** [comment]
dna sequence high dimensionality storage.
comparison similarity with euclidean distance and levenshtein distance.

**Comment by JackyWangCN** [comment]
similarity search and clustering of dense vectors is very  basic operation in many photo search.
see: https://github.com/facebookresearch/faiss
so support euclidean distance function  is very  useful

**Comment by hlcianfagna** [comment]
Just a quick note to mention that the `vector_distance` and `n_dimensional_distance` functions from https://community.crate.io/t/a-collection-of-useful-user-defined-functions-udfs/773 can be used as a workaround.

**Comment by BaurzhanSakhariev** [comment]
> comparison similarity with euclidean distance

> similarity search and clustering of dense vectors 

CrateDB 5.5.0 has [KNN_MATCH](https://cratedb.com/docs/crate/reference/en/5.5/general/builtins/scalar-functions.html#scalar-knn-match) function that can find K vectors that are closest to the given vector.
https://github.com/crate/crate/issues/14319

**Comment by amotl** [comment]
On this matter, we would like to see it supported by actually having the similarity distance function available.

- https://github.com/crate/crate/issues/14801

**Comment by BaurzhanSakhariev** [comment]
Tracked by https://github.com/crate/crate/issues/15835 (it also includes other types of distances in addition to euclidean)
