### ISSUE TITLE
how to intergrate 3th party analyzer?

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6932]
the third party analyzer to es https://github.com/medcl/elasticsearch-analysis-ik
and how to use it in cratedb?
thanks!

**Comment by chaudum** [comment]
3rd party (Elasticsearch) plugins might be compatible with CrateDB, but *are not supported*. Use at own risk.

You can find information how to use fulltext indices for search in our docs:
* https://crate.io/docs/crate/reference/en/latest/general/ddl/fulltext-indices.html
* https://crate.io/docs/crate/reference/en/latest/general/dql/fulltext.html

**Comment by chaudum** [comment]
In the future, if you have single questions, please write in our [public Slack channel](https://crate.io/docs/support/slackin/). Github is used for filing bug reports and feature requests.
