### ISSUE TITLE
insert table drop table not work strange!

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6939]
![000](https://user-images.githubusercontent.com/5292190/36469739-39ccdd34-1723-11e8-9b5a-998928391ef7.png)

when i exec another table name for the same ddl and dml is ok.
create table test1 (
first_column string INDEX using fulltext with (analyzer = 'cjk')
);
insert into test1(first_column)values('hi yours!');
drop table test1;
is ok
do you came up against the problem 
"SQLActionException[ClusterBlockException: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]"

and 
es ref                       https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282
stackoverflow ref     https://stackoverflow.com/questions/48032661/transporterror403-ucluster-block-exception-ublocked-by-forbidden-12-inde

**Comment by matriv** [comment]
@cmdares 
 - Have you played around with the ES api?
 - Which create version are you using?
 - Did you have any issue with disk space in your cluster?
 - Can you execute `ALTER TABLE my_table1e_cjk OPEN` and then try to insert/drop after that?

**Comment by matriv** [comment]
@cmdares Do you still have issues?

**Comment by matriv** [comment]
I'm closing this for now. @cmdares Please feel free to reopen if you still has issues.

**Comment by Jigar3195** [comment]
@matriv 
Facing same issue. i am running 3 node.

> Did you have any issue with disk space in your cluster ?

How to check ?

Crate Version: Latest

55% Disk Space remaining so there is no issue with disk space.

````
alter table node_health add column temp_process_count INT;
````
Above command cause the following issue.


````
SQLActionException[ClusterBlockException: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
````

**Comment by mfussenegger** [comment]
@Jigar3195 

Were you temporarily low on disk?

See our [docs on disk based shard allocation](https://crate.io/docs/crate/reference/en/latest/config/cluster.html?highlight=disk%20watermark#disk-based-shard-allocation)

Specifically the following:

> Defines the threshold on which CrateDB enforces a read-only block on every index that has at least one shard allocated on a node with at least one disk exceeding the flood stage. Note, that the read-only blocks are not automatically removed from the indices if the disk space is freed and the threshold is undershot. To remove the block, execute ALTER TABLE ... SET ("blocks.read_only_allow_delete" = FALSE) for affected tables (see blocks.read_only_allow_delete).
