### ISSUE TITLE
information_schema should be recode more statistics

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6940]
like the monitor panel in admin console,it should be save the statistics value into information_schema.table or other stat table.
thanks. 
In my porj the apps show all table count and filezise and last timestamp for insert or update.

**Comment by joemoe** [comment]
hi @cmdares, almost all the required information can be found in `sys.shards`. last timestamp for insert and update needs to be solved on table level.

**Comment by cmdares** [comment]
thanks!
