### ISSUE TITLE
csv copy command for data migration from hdfs

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6944]
our datacenter builded on the hadoop system and i wanna mak to try with cratedb.
and there has the work how to import csv from hive /hdfs.

should be support copy csv command simplify the work! thanks!
someon mention the issue on the stackoverflow ref:
https://stackoverflow.com/questions/24378071/importing-data-from-csv-files-into-cratedb
there has 1000+ tables in the hive to do it with hive "concat" funcion or other method.
 and it is very tedious for me . 
shuould support :
copy zip_codes(ZIP,CITY,STATE) FROM '/path/to/csv/*.txt' DELIMITER ',' CSV
or like this
copy quotes from '/tmp/import_data/*' with (bulk_size = 4) DELIMITER ',' format=CSV;

**Comment by joemoe** [comment]
hi @cmdares, there's already an pr out. https://github.com/crate/crate/pull/6830
we are improving this at the moment and it might end up in one of the next CrateDB releases.

**Comment by mfussenegger** [comment]
https://github.com/crate/crate/pull/6830 has been merged and is part of `3.0`
