### ISSUE TITLE
intergration with hive

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6945]
intergration with  hadoop (especially “hive” ) has strategic and growth significance.

ref es:
https://www.elastic.co/guide/en/elasticsearch/hadoop/current/hive.html

it well be very convenient migration data from hadoop to cratedb.
in future the etl will be:
beeline>
insert into hive_crate_ext_table select * from hive_table; --- ingest data from hive text/orc file
insert into hive_crate_ext_table select * from hive_hbase_ext_table;----- ingest data from hbase(hive native intergrated with hbase)

thanks！

**Comment by joemoe** [comment]
thanks for your suggestion, not too many users have asked for the feature. we'll track it.

**Comment by mfussenegger** [comment]
Closing this in favour of https://github.com/crate/crate/issues/12686
