### ISSUE TITLE
crate intergration with rdbms

### ISSUE THREAD

**Issue by cmdares** [crate/crate#6954]
ref:
postgresql fwd:
https://github.com/EnterpriseDB/mysql_fdw
https://laurenz.github.io/oracle_fdw/

h2 database table link
http://www.h2database.com/html/grammar.html#create_linked_table

For the time being, it's no necessary consider pushing down feature and remote join .
prioritize for simple the foreign table feature and make to 
1."INSERT INTO CRATE_TABLE SELECT F1,F2,F3 FROM FDW_ORACLE_TABLE WHERE ROWNUM<100"  to simplify the migration to crate plateform.
PLSQL native sql grammar support should be the hard work，to ref H2 source code is useful.The normal data type can be solved first.
Hope to develop priority! oracle is priority!
thanks!

2."select * from FDW_ORACLE_TABLE WHERE ROWNUM<100" should be support JDBC .

**Comment by joemoe** [comment]
at the moment this has no priority to us as cratedb has a different take on structuring data than oracle and mysql have. we are a distributed database and you need to invest some thought work and not just migrate the data. using `JSON` to achieve that should be a good option.
