### ISSUE TITLE
date_format type

### ISSUE THREAD

**Issue by bputt** [crate/crate#6955]
**Use case**: Provide capability to cast date_format output

**Feature description**:
When using the ```date_format``` function, it currently returns a string, but if I'm interested in storing integer like values, it'd be beneficial to convert the value that gets stored into crate.

```
Stores as a string, so "0" for example instead of 0
startdateweekday AS date_format('%w', startdate)

Ideally, if it could support:
startdateweekday BYTE AS (date_format('%w', startdate) * 1)
```

**Comment by seut** [comment]
This can already be done by adding an explicit cast to the generated column expression: `startdateweekday AS cast(date_format('%w', startdate) as byte)`
