### ISSUE TITLE
Aliasing keeping case

### ISSUE THREAD

**Issue by bputt** [crate/crate#6956]
**Use case**: When running ```SELECT myfield as myField``` I'd expect the results to match the alias that I gave it

**Feature description**:
Since I'm lower casing all of my column names and am using them as output to the user, it'd be great if they use the alias that I provided matching its case.

```
SELECT myfield as myField

Returns
myfield
...

Would like it to return
myField
...
```

**Comment by matriv** [comment]
@bputt If you want to keep the case sensitivity you need to put your alias into double quotes:
``SELECT myfield as "myField"``. You can find further info here:
https://crate.io/docs/crate/reference/en/latest/sql/general/lexical-structure.html
