### ISSUE TITLE
Protobuf instead of JSON for CrateDB

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#6973]
I believe using protobuf instead of json would more benefit cratedb

**Comment by joemoe** [comment]
hi @CheyenneForbes, why do you think so and on what level?
we are using json in several places. 

would be nice if you could give us more background information.

**Comment by bputt** [comment]
If I had to guess, it'd be added in addition to json for your HTTP endpoint for queries [ingest single/bulk]

**Comment by CheyenneForbes** [comment]
thats correct @bputt

**Comment by chaudum** [comment]
This suggestion is highly opinionated and subjective. I close the issue as there are no objective arguments that support your suggestion.

**Comment by CheyenneForbes** [comment]
Transport of database data is a lot fast when using Protobuf instead of JSON

**Comment by chaudum** [comment]
If you are worried about the performance of the HTTP protocol, you can use the Postgres Wire Protocol, which is a binary protocol for client server communication. https://crate.io/docs/crate/reference/en/latest/interfaces/postgres.html Our JDBC driver, for example, uses this protocol.
