### ISSUE TITLE
Table Data with CrateDB - Limited events shown based on time for Grafana?

### ISSUE THREAD

**Issue by Johnlin1226** [crate/crate#6979]
Hi all,

I have a table in Grafana pointing to CrateDB - with about 1mil data inserted incrementally starting from 24th January 18’ till today (insertion still ongoing from connected devices).

Here I have a question: when I select the Time Range starting from January 2018 till now not all data is being shown… (the date range for data is from 24th Jan to 16th Feb) (Max of 100k data)

When I change the Time Range starting from February 2018 onward, the most recent data now appears…(date range for data is from 2nd Feb to 26th Feb) (Max of 100k data)

Question here is, why is this such? and how can I enable such that in selecting any Time Range situation, the Table would show all the data with no limitations?

**Comment by chaudum** [comment]
Hi, @Johnlin1226 
I commented on https://github.com/raintank/crate-datasource/issues/49#issuecomment-369173454
