### ISSUE TITLE
converting datetime to json gives wrong time

### ISSUE THREAD

**Issue by mojovski** [crate/crate#6992]
**CrateDB version**: 2.2.6

**JVM version**:

**OS version / environment description**:

**Problem description**:

**Steps to reproduce**:

**Use case**: saving time in a table. 
* select time from data;
then use the returned time value
* select time from data where time<=? order by time desc limit 1;
The returned time is different to the time received from the first query.

**Feature description**:

Propose to change th line client/http.py:86 to
```
return int(o.timestamp()*1e3) #delta.microseconds / 1000.0 + (delta.seconds + delta.days * 24 * 3600) * 1000.0)
```

Tested with python 3.6

**Comment by christianbader** [comment]
Hi @mojovski 
unfortunately, i'm not able to reproduce this issue. Can you provide me with some additional information (e.q. the code causing this behaviour and the timestamps you are using)?
Thanks, Christian.

**Comment by mikethebeer** [comment]
@mojovski is it possible that you forget to do a `refresh table xx` after insert? This needs to be done because of CrateDBs eventually consistent approach (see https://crate.io/docs/crate/reference/en/latest/general/dql/refresh.html).

**Comment by christianbader** [comment]
@mojovski does this work for you now?
