### ISSUE TITLE
Expose cluster health via JMX

### ISSUE THREAD

**Issue by quodt** [crate/crate#7024]
**Use case**: I like to monitor the cluster health with prometheus via JMX

**Feature description**: 

Please expose the cluster health (`GREEN|YELLOW|RED`), shards count and nodes cound via JMX so that these metrics are available to the prometheus JMX exporter.

**Comment by mfussenegger** [comment]
JMX properties are usually node specific, so global cluster health is something we probably won't do.
But I can imagine that we expose the local shard health per node.

**Comment by quodt** [comment]
From operations perspective the cluster health is one of the most important information of a crate cluster. If this information is not available via JMX what do you recommend to get the health state into prometheus?

**Comment by quodt** [comment]
Is there any update on this? I still like to monitor the health of a cluster.
