### ISSUE TITLE
copy from - undocumented dependancy on table status

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate#7034]
**CrateDB version**: 2.3.4

**Environment description**: docker 2.3.4

**Problem description**:
this happened. a) I upgraded from earlier release to 2.3.4 by taking out the schema by show create table. b) created new tables in 2.3.4 with these schemas. c) tried to import by copy from json files. Nothing happened and no error message. It turned out that the table had a warning due to the fact that the dev node only was running one node and the schema had replicas = 1. When setting replica to 0-1 or default it was possible to import to 2.3.4. But no clear message that this was the cause. It was possible in earlier release. Maybe some info  doc under migration chapter would clearify this. /Jonas

-->

error message or info in the docs under migration. I see a warning on the table but had to figure out that warning was due to replicas/nr of node and that this stopped the import. 

maybe info in docs under copy from that table must not have this warning/cause to make import possible,

/Jonas

**Comment by mfussenegger** [comment]
In the next feature release (`3.1`) there will be `COPY FROM .. RETURN SUMMARY` which can be used to get a description of errors that happened. 

I think that'll help a lot to get more insights into what's going on. I'll close this for now but we'd also gladly accept PRs that improve our documentation in various places.
