### ISSUE TITLE
Queries against table with table.field_name != table.field_name failing

### ISSUE THREAD

**Issue by jeffnappi** [crate/crate#7058]
**CrateDB version**: 2.1.5

**JVM version**: OpenJDK 1.8.0_151

**OS version / environment description**: Ubuntu / AWS / Local SSD Raid-0

**Problem description**:
On the (admittedly silly) query including the condition `posts.domain_id != posts.domain_id` I am seeing a significant number of timeout errors.

ex:
```
(crate.client.exceptions.ConnectionError) No more Servers available, exception from last server:
HTTPConnectionPool(host='api02.voicegraph.org', port=4200):
 Read timed out. (read timeout=30) [SQL: 'SELECT posts.id AS posts_id, posts.by_line AS posts_by_line
    FROM posts
 WHERE posts.domain_id != posts.domain_id
       AND posts.by_line IS NOT NULL 
       AND posts.created_at > ?'] [parameters: ('2018-02-19T00:01:19.000000Z',)]
```

**Comment by mfussenegger** [comment]
Thanks for the report. We do currently not detect this as a no-op and so it's resulting in a very expensive table-scan. Priority wise we tend to focus on optimizations that users cannot do easily on the client side. So I'm not sure if we'll change that soon.

Can you show us the SQLAlchemy query? It would be interesting to see if it makes sense to fix the query generation on that level.

**Comment by jeffnappi** [comment]
That is completely valid :smile: We're no longer running the query if the `domain_id` list is empty.

Here's the query:
```
 posts = cdb.query(cm.Post).options(
            load_only(
                cm.Post.id.name,
                cm.Post.by_line.name
            )
        ).filter(
            cm.Post.domain_id.in_(domain_ids),
            cm.Post.by_line != null(),
            cm.Post.created_at > since
        ).all()
```
