### ISSUE TITLE
Problems handling float from JSON using JS (Mixed dataTypes inside a list are not supported)

### ISSUE THREAD

**Issue by rps-v** [crate/crate#7067]
**CrateDB version**:
2.3.4

**Environment description**:
- JVM version: java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- Kernel: Windows 10

**Problem description**:

When trying to insert floating point numbers (from `JSON.stringify()` in JS) using the `_sql` HTTP endpoint, the following error is thrown:
`SQLActionException[SQLParseException: Mixed dataTypes inside a list are not supported]`

**Steps to reproduce**:

```sql
create table "test" (
  "a" ARRAY(FLOAT)
);
```

```js
var req = {
  stmt: 'INSERT INTO test VALUES (?)',
  args: [
    [ 0.0, 1.0, 1.2345 ]
  ]
} 
console.log(JSON.stringify(req))
// make request: axios.post('http://localhost:4200/_sql', req)
```
Outputs:
```json
{ "stmt": "INSERT INTO test VALUES (?)",
  "args": [ [ 0, 1, 1.2345 ] ] }
```
**Notice that the first 2 numbers are now integers.**

Trying to send this payload to Crate will generate an error:
```bash
curl -d '{"stmt":"INSERT INTO test VALUES (?)","args":[[0,1,1.2345]]}' -H "Content-Type: application/json" -X POST http://localhost:4200/_sql
{"error":{"message":"SQLActionException[SQLParseException: Mixed dataTypes inside a list are not supported]","code":4000}}
```

If we modify the JSON to include a decimal point for the integers, then it will work:
```bash
curl -d '{"stmt":"INSERT INTO test VALUES (?)","args":[[0.0,1.0,1.2345]]}' -H "Content-Type: application/json" -X POST http://localhost:4200/_sql
{"cols":[],"rows":[[]],"rowcount":1,"duration":5.371508}
```

Is there a workaround for this problem, since there doesn't seem to be a way to customize the output of `JSON.stringify()` to always include decimal points ?
Maybe allow mixed values for HTTP only ?

**Use case**:

**Feature description**:

**Comment by rps-v** [comment]
This problem also affects GEO_POINT when coordinates are sent as array in JSON (only if coordinates happen to be "exact" floats / integers).

```sql
create table "geo_test" (
  "point" GEO_POINT
);
```

This works:
```json
{
  "stmt": "INSERT INTO geo_test VALUES (?)",
  "args": [
    [ 8.49, 50.12 ]
  ]
}
```

This fails
```json
{
  "stmt": "INSERT INTO geo_test VALUES (?)",
  "args": [
    [ 8.49, 50 ]
  ]
}
```

The workaround for this is to send coordinates as WKT string (`POINT (8.49, 50)`) instead of an array.

**Comment by m-kharbat** [comment]
Thank you for reporting this issue, we will look into it.

**Comment by mfussenegger** [comment]
We've made this a bit more lenient (see https://github.com/crate/crate/commit/dd74441fffad332b966364230f13b5e9e6e35b99) 

This will be part of the next releases (2.3.x and 3.0)
