### ISSUE TITLE
How to connection in expressjs with cratedb??

### ISSUE THREAD

**Issue by vishuPPatel** [crate/crate#7077]
Below mention connection trick apply but not connected 

file:-typings.ts

declare module 'node-crate'{
   var crate : any;
   export default crate;
}

file:- app.js

import crate from "node-crate";

crate.connect('localhost', 4200);

Any body know how to connected  to cratdb in Expressjs

error accrued like this:--

[Node] TypeError: Cannot read property 'connect' of undefined 

Thanks!!!............

**Comment by mfussenegger** [comment]
This seems to be a client related question/problem. Could you please open that up in [node-crate](https://github.com/megastef/node-crate)? (assuming that's the client you're using)

The repo and issue tracker here is mainly for server side related issues or feature requests. See also [other support options](https://crate.io/support/)
