### ISSUE TITLE
Document Crate's Features & Storage Details

### ISSUE THREAD

**Issue by robertjpayne** [crate/crate#710]
Crate looks extremely exciting! While evaluating it, and I'm sure others too, there is little information provided on some of the following:

* ACID Properties
* Consistency Guarantees (How is replication done…)
* Transactional Support (If any…)
* Storage Durability (In what scenarios could data loss occur due…)
* Index Types (Geo, Full Text, Composite etc…)

I've tried to find any of the above through the web docs or the Github repo but have not found much other than Full Text support.

**Comment by chaudum** [comment]
this information can be found in the latest documentation: https://crate.io/docs/en/latest/storage_consistency.html (will be in the stable section as soon as 0.46 is stable)
