### ISSUE TITLE
Query count(*) with timestamp field in where clause use to generate value to partition table error

### ISSUE THREAD

**Issue by DLT1412** [crate/crate#7105]
Just happen with non empty table
**CrateDB version**:
2.3.5

**Steps to reproduce**:
```
CREATE TABLE IF NOT EXISTS "doc"."t" (
   "f" TIMESTAMP,
   "p" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', '+07:00', "f")
)
CLUSTERED INTO 1 SHARDS
PARTITIONED BY ("p");

select count(*) from t where f>10; #SUCCESS

insert into t values ('2018-03-28T00:00:00+07:00');

select count(*) from t where f>10; #SQLActionException[SQLParseException: Cannot search on field [p] since it is not indexed.]
```

**Comment by chaudum** [comment]
I can confirm the incorrect behaviour. The regression has been introduced with 4f9c2a1fe876ee8a415232e782cdc202e4235b6d in CrateDB version 2.3.4.

**Comment by bputt** [comment]
Will you be adding any tests that would catch this error in case it happens in future versions?

**Comment by matriv** [comment]
@bputt: https://github.com/crate/crate/pull/7110/files#diff-905c1f033e3ac48b0b2d69130f44df24R2160

**Comment by matriv** [comment]
Fixed will be available with the next hotfix release.
