### ISSUE TITLE
insert into select too slow!

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7107]
3 nodes vmware  (every node cpu:8C E5 2.6G/mem:16G/hdd:7200RPM)   CRATE 2.3.4

table:T_TEST   100million   3 column (int,String,Timestamp)
8 threads concurrent jdbc insert 20000 row/s
and at the same time use crash sql line to execute:
“insert into T_TEST select * from T_TEST;”  ----self insert to self
......too slow and execution can't be done！

**Comment by bputt** [comment]
@cmdares you may want to provide more details like: heap_size, how many records you insert per batch, what your refresh_interval is, how many shards, how many replicas, and overall, just explain the issue better.

I myself am not with crate, but do share the same interest into this issue as you.

**Comment by joemoe** [comment]
hi @cmdares, 
as @bputt already commented we would need more information. 
what do you mean by `too slow and execution can't be done!`.
also out of interest what is the use case to do a `self insert`?

**Comment by chaudum** [comment]
Closing this as there has not been any feedback for more than 2 weeks. Please feel free to open it again if you can provide any more information.
