### ISSUE TITLE
Is crate db supports batch job?

### ISSUE THREAD

**Issue by Gompangs** [crate/crate#7139]
Hi, I'm just wonder about Is crate db supports batch schedule now or later?

I'm trying crate db for time-series db to save statistics data.

I think It can be useful feature when using continuous query for data aggregation(by time) or down-sampling, delete out-of-date data. (like influxDB, it supports)

+ additional questions.

I'm using crate db 2.3.6, jdbc client 2.3.0
but, can't pooling connection because jdbc datasource isn't supported.

I was add crate db connection in Hikari DBCP forcely, although it seems not working properly.
max-connection-pool :  32
min-idle connection : 16 
when data insertion started, only 5 connections wake up(active).

Can not find any documentation for use crate db with mybatis.

Is there additional features  in next version to supports batch job or jdbc datasource?

**Comment by joemoe** [comment]
Hi @Gompangs,

no batch jobs won't be in the next version of CrateDB, also not JDBC datasource.
We have customers working successfully with CrateDB and Hikari, although we don't test and document it ourselves.
There is no documentation about CrateDB and mybatis. I'm also not aware of any users using it.

Thanks,
Joe

**Comment by Gompangs** [comment]
Okay. Thanks !
