### ISSUE TITLE
Kubernetes documentation - not good default recommendations

### ISSUE THREAD

**Issue by peterlauri** [crate/crate#7171]
Relates to documentation here: https://crate.io/docs/crate/guide/en/latest/scaling/kubernetes.html

I could not find that documentation in the sources, so I added an issue instead of a PR.

- The default configuration should not set it up with LoadBalancer, as a new Kubernetes user might not understand that he would expose the database on the external ip (public). I would say type=NodePort
- Using memory volume is not recommended, as a service restart at configuration update could (and most probably will) get crate into a bad state. I tested a few times, and shards were lost etc. I persistent volume claim would probably be better. This creates a new persistent volume for each node. Note that for performance there are different options of the type one can use, ssd, local ssd etc, depending on cluster provider.

Diff of how I changed it to function in GKE (Google Kubernetes Engine).

```diff
diff --git a/crate.yml b/crate.yml
index 4612ada..43423c8 100644
--- a/crate.yml
+++ b/crate.yml
@@ -12,7 +12,7 @@ spec:
     name: cluster
   - port: 5432
     name: postgres
-  type: LoadBalancer
+  type: NodePort
   selector:
     app: crate
 ---
@@ -54,7 +54,7 @@ spec:
           - -Clicense.enterprise=false
         volumeMounts:
             - mountPath: /data
-              name: data
+              name: crate-persistent-storage
         resources:
           limits:
             memory: 2Gi
@@ -73,7 +73,12 @@ spec:
           value: "3"
         - name: CLUSTER_NAME
           value: "spine-cratedb-cluster"
-      volumes:
-        - name: data
-          emptyDir:
-            medium: "Memory"
+  volumeClaimTemplates:
+  - metadata:
+      name: crate-persistent-storage
+    spec:
+      accessModes:
+        - ReadWriteOnce
+      resources:
+        requests:
+          storage: 10Gi
```

**Comment by chaudum** [comment]
cc @Autophagy @turbo-ele @christianbader

**Comment by peterlauri** [comment]
@chaudum I don't mind doing a PR, but where if so? :)

**Comment by Autophagy** [comment]
@peterlauri If you'd like to create this as a PR, it currently exists wtihin our CrateDB guide repository https://github.com/crate/guide/blob/master/docs/scaling/kubernetes.txt

I agree with your points, especially about switching out the memory storage for a persistent volume claim. I think the usage of memory was just to get users up-and-running, but that isnt very useful.

**Comment by joemoe** [comment]
hi @peterlauri, when you create the pr, please also sign our cla: https://crate.io/community/contribute/cla/.

**Comment by chaudum** [comment]
@peterlauri Do you need any help contributing to the CrateDB guide? /cc @Autophagy
