### ISSUE TITLE
Missing Builds in CDN

### ISSUE THREAD

**Issue by JAC2703** [crate/crate#7175]
Recently we're missing some of the newer builds for older distros - in my case Debian Xenial. Currently only Artful builds are being produced on each new Crate version. 

https://cdn.crate.io/downloads/deb/stable/pool/main/c/crate/

**Comment by joemoe** [comment]
hi @JAC2703, we are aware of that and already working on a fix. we'll keep you posted. thanks.

**Comment by chaudum** [comment]
Hi @JAC2703 
2.3.6 packages are now again available for Artful, Trusty, Xenial, Yakkety and Zesty
