### ISSUE TITLE
is there a odbc or jdbc driver in the making?

### ISSUE THREAD

**Issue by tinkerbotfoo** [crate/crate#718]

**Comment by jodok** [comment]
just for completeness. we now have an ODBC driver as well.

**Comment by cgvarela** [comment]
Wow!!  This a great news!!!  thnx guys!!   Now for the Microstrategy's support certification!!  jajaja  ; )p

**Comment by everlytics** [comment]
Hi, Can you provide a link to the odbc driver.I can't seem to be able to find it on your website.

**Comment by chriswue** [comment]
@everlytics As per https://github.com/crate/crate/issues/6604 it seems the ODBC support has come and gone again ...
In the linked issue it is recommended to us the posgres .NET driver - makes me wonder if you can just install the postgres ODBC driver to talk to crate (they do claim that they speak the postgres wire-protocol)

**Comment by everlytics** [comment]
We switched to Greenplum for Tableau connectivity
