### ISSUE TITLE
Crate JDBC - Can't install from Maven

### ISSUE THREAD

**Issue by rsadyhov** [crate/crate#7184]
Error: [WARNING] The POM for io.crate:crate-jdbc:jar:2.3.0 is missing, no dependency information available

Steps: https://mvnrepository.com/artifact/io.crate/crate-jdbc/2.3.0

**Comment by rsadyhov** [comment]
https://crate.io/docs/clients/jdbc/en/latest/getting-started.html#install

**Comment by mxm** [comment]
Yes, we use JCenter instead of Maven Central. Glad you found the pointer 👍
