### ISSUE TITLE
Http calls to a blob that return 404 causes incorrect results on all future calls

### ISSUE THREAD

**Issue by mjwall** [crate/crate#7185]
**CrateDB version**: tested on 2.1.6, 2.3.3 and 2.3.6

**Environment description**:
 - JVM version: Java 8
 - Kernel: 3.10.0-693.17.1.el7.x86_64
 - Distribution: CentOS
 - Number of nodes; One to many

**Problem description**:

See https://github.com/mjwall/crate-blob-error.  Description from the repo pasted here

> What is happening is this:

> 1. a call to a crate blob that doesn't exist returns a 404
> 2. the next call, no matter to what returns the same 404 response
> 3. the next call returns whatever was the response in #2
> 4. the next call returns whatever was in the response in #3 and so on

> From that point on any call that hits the same IP address is one response behind.

> And if you get another 404, the calls become 2 behind as seen in [testSeveralCallsAfterMultiple404](https://github.com/mjwall/crate-blob-error/blob/master/src/test/java/com/mjwall/crate/BlobTest.java#L111).

**Steps to reproduce**:

Clone the repo and run `mvn clean test`

**Comment by joemoe** [comment]
hi @mjwall, thanks for the comprehensive bug description.
we'll look into that and keep you posted.

thanks, joe

**Comment by chaudum** [comment]
Hi @mjwall 
Thanks to your detailed report we were able to identify an issue with keep-alive connections. The problem will be fixed with https://github.com/crate/crate/pull/7191 and will be available with the next hotfix release.

**Comment by mjwall** [comment]
thanks @chaudum, I pulled and built master with your fix.  Then tweaked my test to use that and everything passed.  Looks good.

Leaving the ticket open, assuming you will close when you are ready.

**Comment by chaudum** [comment]
I close the issue as it is confirmed to be fixed with the next release.

**Comment by chaudum** [comment]
@mjwall 2.3.7 has been released last friday https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/2.3.7.html
