### ISSUE TITLE
Tempermental performance on query with JOIN and subquery

### ISSUE THREAD

**Issue by SneakyMax** [crate/crate#7203]
**CrateDB version**: 2.3.2 (we need to update, yeah)

**Environment description**:
 - JVM version: `1.8.0_144`
 - Kernel: `Linux ip-172-31-4-175 4.4.0-1039-aws #48-Ubuntu SMP Wed Oct 11 15:15:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
 - Distribution: Ubuntu 16.04.2 LTS
 - Number of nodes: 2

**Problem description**:

So I have a query like this:

```sql
SELECT COUNT(*) FROM (
  QUERY_A
) AS g
INNER JOIN content ON g.some_id = content._id
```

This returns `654`

Where QUERY_A is a slightly complex query, but for the purposes of this ticket, I'm _guessing_ it doesn't matter?

QUERY_A by itself takes almost no time, here are execution time numbers:
```
0.029
0.022
0.023
0.025
0.027
0.022
```

However, the query times for the full query above were:
```
17.277
18.944
3.205
21.056
0.233
0.667
0.220
0.220
16.56
19.532
17.063
```

Sometimes it was instant. Sometimes it took over 20 seconds.

`QUERY_A` returns ~600 rows
The `content` table has ~3000 records

An inner join between those two results should definitely not take 20 seconds, even if it is just running a nested loop, right?

**Steps to reproduce**:

I'm really not sure how I can help with this. I can run any commands you'd like. I sent the full query & explain to @matriv

Maybe this is just the normal join performance in crate being bad but...it's weird because sometimes it's instant.

**Comment by chaudum** [comment]
Hi @SneakyMax 

I can have a look at your fluctuating JOIN performance. However I'd need some more information:
* How many rows does the left table (the one from the subselect) have?
* How exactly did you measure the query times?
* Was this the only query that run in that time when you tested?
* Did you observe any noticeable patterns in cpu/memory/heap usage during the tests?

On a side note: please always post all relevant information in public and not poke specific people as they can be on holiday or even have left the company. Thanks!

**Comment by SneakyMax** [comment]
Sorry @chaudum, be happy to email you the same stuff to you but I can't post it here

1. The left table has 167 million records. The subquery by itself returns about 600 rows.
2. The timer that shows in the Crate admin UI (e.g. SELECT OK, X rows in set (0.022 sec))
3. Probably not, but the timing is very consistently inconsistent. The subquery is always instant.
4. The CPU usage goes very high during the query. It starts with all 4 cores but then only one core is 100% until the end of the query. When the query is "instant" (<2 seconds) the CPUs went to about 25% for a brief moment. The subquery only does not touch the CPU

**Comment by SneakyMax** [comment]
Actually I have found perhaps a much simpler way to reproduce it:

```sql
SELECT COUNT(*) FROM
(
    SELECT table_2_id FROM table_1 LIMIT 100
) AS inner
INNER JOIN table_2 ON inner.table_2_id = table_2._id
```

Query timings:
2.54
2.53
2.54
0.064
0.065
0.166
2.839
0.064
0.116
0.064
2.541

**Comment by chaudum** [comment]
It's probably related to https://github.com/crate/crate/issues/7017#issuecomment-373620835 ? Can you try to set the replicas to 0 and run the queries again? How does the shard distribution look like?

**Comment by SneakyMax** [comment]
Shard distribution:

`table_1` (subquery, ~100m rows total):
```
doc.events | true | S'chn T'gai Spock | 1 
doc.events | true | James Tiberius Kirk | 3
doc.events | false | S'chn T'gai Spock | 3
doc.events | false | James Tiberius Kirk | 1
```

`table_2` (outer query/join, ~6000 rows total): 
```
doc.content | true | S'chn T'gai Spock | 2
doc.content | true | James Tiberius Kirk | 2 
doc.content | false | S'chn T'gai Spock | 2 
doc.content | false | James Tiberius Kirk | 2
```

**Comment by SneakyMax** [comment]
I changed the # of replicas for both tables to 0, and that appears to have fixed the problem. Thank you for that! I guess you can close this since the other issue talks about it in detail.
