### ISSUE TITLE
Performance degradation when using aliases with date_format in order by clause

### ISSUE THREAD

**Issue by bputt** [crate/crate#7210]
**CrateDB version**:
3.0.0-SNAPSHOT-01a5fae

**Environment description**: Centos 7.4

**Problem description**:
When using aliases and ordering by them, query times take longer to return results. This appears to be an issue when using the date_format function. We haven't tried other functions.

**Steps to reproduce**:

```
SELECT colA, date_format('%Y-%m-%dT%H:%i:%s.%fZ', startdate) as start_date FROM table ORDER BY start_date desc
```

This query takes ~8s

```
SELECT colA, date_format('%Y-%m-%dT%H:%i:%s.%fZ', startdate) as start_date FROM table ORDER BY startdate desc
```

This query takes <1s

startdate's type: timestamp

**Comment by mfussenegger** [comment]
If you sort on the timestamp column it can internally utilize a column store data structure to do efficient sorting. If instead you sort on the `date_format` function it has first to evaluate that function on all records, this is expected to be slower.

**Comment by bputt** [comment]
@mfussenegger Makes sense....I'll close unless you think further action is needed.
