### ISSUE TITLE
Backup For Multi Node System

### ISSUE THREAD

**Issue by sahil9854** [crate/crate#7213]
**CrateDB version**: 2.1.6

**Environment description**: 4 physical servers with each node having crate version 2.1.6.
How to take backup for a multi node system ?

**Problem description**:

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @sahil9854,

see our documentation:
you could either use `SNAPSHOTS` or `COPY TO`.
https://crate.io/docs/crate/reference/en/latest/admin/snapshots.html
https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-to.html

Joe

**Comment by sahil9854** [comment]
This only talks about taking a snapshot if its 1 node.
I wanted to know a strategy to take backup of 4 nodes on each server.When i do that it gives me an error saying that cannot connect to other servers

**Comment by sahil9854** [comment]
Basically i want to know how to connect everything using fs Type Shared file location.
If i have /home/crate/Snapshots on all the 4 nodes
