### ISSUE TITLE
Add not null constraint

### ISSUE THREAD

**Issue by corck** [crate/crate#723]
Working on the active record adapter and having a "not null" constraint is assumed from the abstract adapter. Currently impleming a work around to get migrations working.

**Comment by joemoe** [comment]
hi @corck, we are happy to announce that the "NOT NULL" constraint will be in 0.56.x
https://github.com/crate/crate/blob/master/CHANGES.txt#L49
https://crate.io/docs/reference/en/latest/sql/ddl.html#not-null
