### ISSUE TITLE
Feature  request: server side compute blob sha digest

### ISSUE THREAD

**Issue by junphine** [crate/crate#7240]
**Use case**:
use browser to upload file direct to crate blob table.
use user defined string as pk instead digest. because most time file name is useful than digest.
for move some store system to crate blob like: gridfs，db.blob.

**Feature description**:
support file name as pk for blob table.
add post rest api for upload file to blob table. and this api return degist of file, so other api should  no change.

**Comment by joemoe** [comment]
hi @junphine, thanks for your suggestion. 
there is already an issue for that: https://github.com/crate/crate/issues/2981
i'm closing this, as this is duplicate.
thanks, joe

**Comment by chaudum** [comment]
The SHA hash is required for the distribution and the locating of the blobs in the cluster. A hash identifies a BLOB uniquely and if the contents of a file changes, also the SHA hash changes.

**Comment by junphine** [comment]
hi @chaudum , I understand that digest use as content identity is necessary and very comfortable. so I real suggestion is to make the blob api easy to use.
maybe use two table to store blob info. 
the first table look like this:
filepath(pk), degest,  mimetype, filesize.
the second table same as current blob table.
