### ISSUE TITLE
Facing problem with table_parameter

### ISSUE THREAD

**Issue by subodhexzeo** [crate/crate#7242]
**CrateDB version**: 2.3.7

**Environment description**:

**Problem description**:
I am trying to create table with following query.
CREATE TABLE IF NOT EXISTS test (
communityId long 
,w_closedDate timestamp 
,w_createdDate timestamp 
,w_id long 
,w_lastModified timestamp 
,w_number string INDEX USING FULLTEXT WITH (ANALYZER = 'case_insensitive_match_analyzer')
) WITH (translog.flush_threshold_ops = 5000);

Everything works fine until I used translog.flush_threshold_ops. I got SQLActionException[SQLParseException: line 8:17: mismatched input '.' expecting '='] while executing query. Although this property is listed in documents.
When I used property number_of_replicas = 0 It executed fine.
What is wrong I am doing?
Also I need to provide multiple property using "WITH" clause. How to do that as well

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by matriv** [comment]
@subodhexzeo 

Closing the issue, feel free to reopen if something else pops up.
