### ISSUE TITLE
batch insert

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7247]
how to speed up
“insert into bigtable(a,b,c,d) select a,b,c,d from smalltable”
16G,8C/per node  all:16Nodes
bigtable:5billion
smalltable:50million
poor performance, job not finished.

**Comment by m-kharbat** [comment]
hi @cmdares - this issue tracker is for the core development of CrateDB. 
Please refer to StackOverFlow or the community slack channel for this kind of questions. 
https://crate.io/support/
