### ISSUE TITLE
Review changes to Npgsql NodaTime plugin

### ISSUE THREAD

**Issue by roji** [crate/crate#7251]
A while ago @apircher added floating point timestamp support to Npgsql (https://github.com/npgsql/npgsql/pull/1668), which followed the same encoding/decoding pattern I had there.

However, NodaTime makes it much simpler to encode/decode PostgreSQL timestamps. I just pushed a commit (https://github.com/npgsql/npgsql/commit/db0f080a7000c216c688331462158ea27f9bf2fa) which vastly simplifies and optimizes the code; I've also made changes to your floating-point code, but I have no way of testing this.

Can you guys please take a look and align the floating point encoding/decoding with the new integer logic, which is much simpler?

On a more general note, is there any plan to get CrateDB to use the standard integer format instead? CrateDB is the only DB I know that still uses floating point, PostgreSQL 10 have removed the option entirely. I'd love to get rid of this code which I can't test.

/cc @apircher @mikethebeer @joemoe

**Comment by mikethebeer** [comment]
@roji thanks for pointing this out. We will take a look into this.

**Comment by mikethebeer** [comment]
@roji We tested our custom type bindings and upgrade our submodule dependency with https://github.com/crate/npgsql-cratedb/pull/6

Your changes look fine for CrateDB 👍 

Regarding the integer timestamp format I could say that we are going to change this soon or later in CrateDB as well. This is addressed in our backlog/roadmap.

**Comment by roji** [comment]
@mikethebeer ok, great and thanks for confirming. You may want to simplify the NodaTime code like I've done, the method became a one-liner. On the other hand if you're planning to get rid of floating point timestamps that's even better.
