### ISSUE TITLE
How to set Cratedb  Docker container volume()and how backup that Cratedb running container ????

### ISSUE THREAD

**Issue by vishuPPatel** [crate/crate#7259]
Hello...Cratedb Team

I want to Cratedb set docker volume and how backup Cratedb schema and import & Export  that Cratedb?

Thanks!!!!..

**Comment by chaudum** [comment]
Github is used as a bug report and issue tracker for the core development of CrateDB.
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/crate) or the [CrateDB Community](https://crate.io/docs/support/slackin/) Slack channel for these kind of questions. https://crate.io/support/
