### ISSUE TITLE
copy csv grammar, configurable deliminator

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7260]
copy csv should be support “fields terminated by” and  "lines terminated by" grammar
for example:
copy test_tbl from 'file:///tmp/*.csv' fields terminated by ':' lines terminated by '\n'
thanks!
version:crate-3.0.0-20180516

**Comment by joemoe** [comment]
thanks for your suggestion.
not sure if and when this will be added.

**Comment by cmdares** [comment]
+1

**Comment by cmdares** [comment]
+1
