### ISSUE TITLE
group by having problem

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7261]
```
select userid,count(1)c from test_tbl where type='a' group by userid having userid='user0001'
```

```
select * from (select userid,count(1)c from test_tbl where type='a' group by userid)t where userid='user0001'
```

The result is not the same? why?
env:16 node,2billion rows   
version:crate-3.0.0-20180516

**Comment by joemoe** [comment]
hi @cmdares,

thanks for reporting, we will look into that.

thanks,
joe

**Comment by mfussenegger** [comment]
Is the result deterministically different?

CrateDB is eventually consistent, if you're inserting while you're executing the queries it could be that sometimes the query hit the replicas and sometimes primaries - that could explain a difference in the result.
