### ISSUE TITLE
update performance poor

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7289]
cratedb 3.0
16 node (4C 2.2G cpu   16G mem   7200RPM hdd)
6.3Billin 15 field
update table1 set field1='xx',field2='eee',field3='yyy' where userid='id0000001'
----- update 20 row ok! ------ 3s
update performance poor. how to speed up?
thanks!

**Comment by chaudum** [comment]
Github is used as a bug report and issue tracker for the core development of CrateDB.
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/crate) or the [CrateDB Community](https://crate.io/docs/support/slackin/) Slack channel for these kind of questions. https://crate.io/support/
