### ISSUE TITLE
cluster scale

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7292]
How many nodes can a cluster install in a relatively stable datacenter environment?

**Comment by chaudum** [comment]
Github is used as a bug report and issue tracker for the core development of CrateDB.
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/crate) or the [CrateDB Community](https://crate.io/docs/support/slackin/) Slack channel for these kind of questions. https://crate.io/support/
