### ISSUE TITLE
white-space issue when using PostgreSQL Wire Protocol

### ISSUE THREAD

**Issue by nicetip** [crate/crate#7312]
**CrateDB version**: 3.0.0

**Environment description**:

**Problem description**:

I found some difference between v2.3.x and v3.0.0

When using python with postgresql driver (not web API based driver), if there is some white-spaces after semi-colon, crate occurs error.

```python

import psycopg2
conn = psycopg2.connect("dbname='mydb' host='127.0.0.1' port=5432")
cs = conn.cursor()
cs.execute('select * from table1 limit 1;  ')  # white-space after semi-colon

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.InternalError: SQLParseException: line 1:3: no viable alternative at input '<EOF>'
```

In 2.3.x version, It worked well.

Sometimes, some python user may use like this (me).

Following case also occurs error, cause new-line charater after semicolon.

if there is no semi-colon, error not occurs.

```python
query = """
select * from table1
where 1=1
order by column1 asc;
"""
cursor.execute(query)
```

Of course, It's easy to fix in users code by removing white-space or semi-colon. 

But I think ignoring white-space is more comfortable to use in this case (just tried single query). 

Thanks.

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by mxm** [comment]
Fixed and will be part of 3.0.1. Thank you for the good description.
