### ISSUE TITLE
Securing crate admin interface with userid and password

### ISSUE THREAD

**Issue by ksasi** [crate/crate#732]
Is it possible to secure create admin interface with login credentials?
##

**Comment by devoncrouse** [comment]
How about Shield support with ES 1.4.2? Granted, this only helps those willing to pay for it. Just wondering if this will be supported naturally when Crate reaches that version.

**Comment by salyh** [comment]
I created some security stuff for elasticsearch, maybe i can help:
https://github.com/salyh/elasticsearch-security-plugin
https://github.com/salyh/elastic-defender

**Comment by seti123** [comment]
@dobe maybe you can try it during Snowsprint Hackathon? Regards to the other Snowsprinters ...

**Comment by chaudum** [comment]
CrateDB 2.3.0 (currently testing, https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/2.3.0.html) added support for username/password authentication over HTTP protocol - which is used by the Admin UI.
You can find information how to secure the Admin UI in the "Authentication" docs https://crate.io/docs/crate/reference/en/latest/admin/auth/hba.html#authenticating-to-admin-ui and https://crate.io/docs/crate/reference/en/latest/admin/auth/index.html
User Authentication is an Enterprise feature.
