### ISSUE TITLE
Count queries returning inconsistent results on timeseries tables.

### ISSUE THREAD

**Issue by nocturnaltortoise** [crate/crate#7354]
**CrateDB Version**: 2.3.9

**Environment description**:

    JVM version: 1.8.0_171
    Kernel: Linux 4.4.38
    Distribution: Ubuntu 16.04
    Number of nodes: 3

**Problem description**:
Running a COUNT query on a timeseries table returns different results. Only seems to happen on one table. Nothing is regularly inserting into it, but data has been recently deleted and inserted.

**Steps to reproduce**:
Create a table like:
```sql
CREATE TABLE IF NOT EXISTS "armada"."meter_proportions" (
   "meter_uuid" STRING,
   "proportion" FLOAT,
   "site_uuid" STRING,
   "timestamp" TIMESTAMP,
   PRIMARY KEY ("site_uuid", "meter_uuid", "timestamp")
)
CLUSTERED INTO 6 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)
```

Run a query like:
```sql
SELECT COUNT(*) FROM armada.meter_proportions limit 100;
```
Sometimes I get 12552, sometimes 12553. The crate admin count says 12553.
Pulling all the timestamps out of the table, sometimes one row is missing (i.e. one timestamp), sometimes it isn't. So even running a normal SELECT sometimes returns slightly different results. 
I have tried running ```REFRESH TABLE``` but to no avail.

**Comment by nocturnaltortoise** [comment]
Running without the limit in Crash seems to make no difference.
The optimize query succeeded but didn't fix the issue.

**Comment by matriv** [comment]
Can you please try:
`alter table armada.meter_proportions set (number_of_replicas=0);`
and then
`alter table "tracknamic"."notification" set (number_of_replicas=0-1);`

**Comment by nocturnaltortoise** [comment]
So I dropped the table, recreated it and re-inserted the data, and the issue has gone away. Unfortunately that also means that I can't really test this suggestion. I haven't encountered it on any other table either.

**Comment by matriv** [comment]
I would suggest that you move to 2.3.11 (latest stable) which contains a bug fix that can be related to the situation you experienced.

**Comment by nocturnaltortoise** [comment]
Ok, thanks for your help. :)
