### ISSUE TITLE
Use BigInt lib for returning large numbers

### ISSUE THREAD

**Issue by bputt** [crate/crate#7373]
I understand that the LONG datatype can't be larger than 64bit. It'd be great if you could return a number larger than 64 bit when aggregating numeric datatypes.

**Problem description**:
When calculating the SUM of a LONG field, I get an exception: ```NotSerializableExceptionWrapper: arithmetic_exception: long overflow```

**Steps to reproduce**:
```CREATE TABLE testa(aa LONG)```

Run this query multiple times:
```INSERT INTO testa(aa) VALUES (8888888888888888888)```

```SELECT SUM(aa) FROM testa```

**Comment by manikanta-kondeti** [comment]
Hi, 

Yes, I have tried to reproduce the same. Created a table and 150 records of values 9999999999999999. Tried to do an aggregation "SUM" on this particular table and got "ArthimeticException error". Added the screenshot. 

<img width="1338" alt="screen shot 2018-06-04 at 5 19 10 pm" src="https://user-images.githubusercontent.com/5001881/40915982-a65f0b18-681b-11e8-8bce-16a4c2593a87.png">

I started working on a fix and will create a PR soon. I will share the link here and we can discuss further.

Look forward

**Comment by joemoe** [comment]
hey @bputt, thanks for your suggestion. we agree that this would be a good addition.
thanks @manikanta-kondeti for doing the contribution. you are more than welcome.
if you have any questions please let us know.

**Comment by bputt** [comment]
@mfussenegger how's this looking on the backlog? any chance it would get into 3.2 release :)

**Comment by bputt** [comment]
@mfussenegger how's this going if at all...no rush, just a friendly check in

**Comment by bputt** [comment]
@mfussenegger any updates yet

**Comment by seut** [comment]
We've implemented this by https://github.com/crate/crate/pull/10854, which will be part of the next CrateDB 4.4 feature release.
