### ISSUE TITLE
casting timestamp column to long returns string

### ISSUE THREAD

**Issue by quodt** [crate/crate#7403]
**CrateDB version**: 3.0.1, 2.3.7

**Environment description**: MacOS, crate running as docker container, Docker version 18.03.0-ce-mac60 (23751)

**Problem description**:

I'm trying to retrieve a timestamp column as raw unix timestamp (in ms). In versions >= 3 i can do this by `extract(EPOCH from ts)` but not in versions < 3. So i tried to `cast` the column which shows a 
strange behaviour. Casting a timestamp column to long returns a formatted datetime as string. If i cast the timestamp to string i'm getting the unix timestamp (in ms) as string. It's the same behaviour in versions <> 3

**Steps to reproduce**:

```
crate=> CREATE TABLE IF NOT EXISTS test (ts TIMESTAMP) CLUSTERED INTO 1 SHARDS WITH (number_of_replicas = '0', column_policy='strict');
crate=> insert into crate.test (ts) values (1528727127000);

crate=> -- formatted datetime
crate=> select cast(ts as long) from test;
      CAST(ts AS long)
----------------------------
 2018-06-11 14:25:27.000+00

crate=> -- unix timestamp as string
crate=> select cast(ts as string) from test;
 CAST(ts AS string)
--------------------
 1528727127000

crate=> -- double cast gives me the value i actually like to get
crate=> select cast(cast(ts as string) as long) from test;
 CAST(CAST(ts AS string) AS long)
----------------------------------
                    1528727127000
```

**Comment by andreidan** [comment]
@quodt support for `extract(EPOCH )` was added with version 3.0.0. I just tested and it works with 3.0.0, 3.0.1 and 3.0.2 so wherever possible please upgrade to 3.0.X
Formatting the timestamp to string is actually a PSQL specific behaviour and other clients (eg crash) don't exhibit this behaviour.

**Comment by andreidan** [comment]
We should handle the cast as LONG and not as timestamp though. Reopening to look into that.

**Comment by andreidan** [comment]
@quodt We fixed the cast issue and the fix will be available with the next minor release. Casting Timestamp to Long will return the Long type ( https://github.com/crate/crate/pull/7414 )
