### ISSUE TITLE
Cluster performance degradation in Kubernetes

### ISSUE THREAD

**Issue by gree-gorey** [crate/crate#7408]
Hi guys! Can someone help me out?

I have a 3-node Crate cluster installed in Kubernetes.
In the beginning cluster performance is fine and memory usage is about 16% of container limit.
But after some time (maybe a day of writing data to it) it begins to slow dramatically and process about 1 request/second. Memory usage becomes 90% of container limit.
But when I restart all three containers it starts to work fine again.
I suspect that it is smth memory related but cannot find it. Heap size set correctly -- 50% of container memory limit.
Cluster health is fine, and no errors nor in UI not in container logs.

**OS**: Ubuntu 16.04
**Image**: crate:2.3.2
**CPU container limit**: 4000m
**Memory limit**: 6Gi
**CRATE_HEAP_SIZE**: 3Gi
**Node count**: 3

Command to run crate:
```
- /docker-entrypoint.sh
- -Ccluster.name=mycluster
- -Cdiscovery.zen.hosts_provider=srv
- -Cdiscovery.zen.minimum_master_nodes=2
- -Cdiscovery.srv.query=_cluster._tcp.crate.mynamespace.svc.cluster.local
- -Cgateway.recover_after_nodes=2
- -Cgateway.expected_nodes=3
- -Clicense.enterprise=false
- -Cnetwork.host=_site_
- -Cpath.repo=/repo
```

**Comment by joemoe** [comment]
hi @gree-gorey, thanks for reporting the issue. we have indeed another user reporting a similar behaviour, we will look into that and keep you up to date if this is something cratedb related.

**Comment by dominikmoosbrugger** [comment]
Hi @gree-gorey it seems we have gotten wound up within our processes. The other user reporting this behaviour was actually you. We're closing this here and track it in your enterprise support channel.
