### ISSUE TITLE
Cannot Query distinct in Crate

### ISSUE THREAD

**Issue by sahil9854** [crate/crate#7410]
**CrateDB version**:
2.1.6

**Environment description**:
6 node multinode crate server

**Problem description**:
select distinct attributes['location'] from gra.transactions limit 100;
ERROR:

SQLActionException[SQLParseException: Cannot GROUP BY 'attributes['location']': grouping on analyzed/fulltext columns is not possible]

**Steps to reproduce**:

Table Schema :-

**Comment by chaudum** [comment]
The error message says exactly what the problem is: You try to do a DISTINCT (which is basically a GROUP BY) on a STRING column with FULLTEXT analyzer. That is not possible.
