### ISSUE TITLE
Add slowlog

### ISSUE THREAD

**Issue by bputt** [crate/crate#7452]
**Use case**: Add ability to change slow log settings since the es.api.enabled option is going away

The following does not work
```
SET GLOBAL 'index.search.slowlog.threshold.query.warn' = '3s'
```

**Feature description**:
I'd like to configure the options available per the ES docs

https://www.elastic.co/guide/en/elasticsearch/reference/6.1/index-modules-slowlog.html

**Comment by chaudum** [comment]
@bputt We've just recently implemented a feature do log certain queries to file, however it is more general than just for slow queries. You can provide an expression that needs to match.
See https://github.com/crate/crate/commit/031ad7607908be45fd12183648252b8a4ac5c4d7
This will be available with CrateDB 3.1
