### ISSUE TITLE
IntegrationTest Failure: io.crate.integrationtests.ArithmeticIntegrationTest 

### ISSUE THREAD

**Issue by vibhutisawant** [crate/crate#7520]
**CrateDB version**:
working on master branch

**Environment description**

 - JVM version: openjdk version "1.8.0_171"
 - Kernel: ppc64le GNU/Linux
 - Distribution: Ubuntu:16.04

**Problem description**:
Test Failure: io.crate.integrationtests.ArithmeticIntegrationTest fails for the following method:
testSelectWhereArithmeticScalarTwoReferenceArgs. The row count value returned by the query should be 2L,however it appears to be 1L. Is it anything related to the data type of the Value returned by the query?

Stack trace for failure:
Attached a log file along with the issue.
[Github issue logfile.txt](https://github.com/crate/crate/files/2179876/Github.issue.logfile.txt)

**Produced with**:
./gradlew -Dtest.single=ArithmeticIntegrationTest sql:test --stacktrace

**Comment by mfussenegger** [comment]
Is this really on latest master? I can't reproduce this locally and our CIs (Travis + Jenkins) are good. 

The attached logfile contains `test@c74b29e97513` but `c74b29e97513` isn't a commit I can find in our repo?

**Comment by vibhutisawant** [comment]
@mfussenegger  hi
The issue is with the latest master branch for **ppc64le** architecture.
the cratedb is being installed inside a docker container(c74b29e97513 is the container id and has nothing to do with the commit id)
The python version installed is 3.6.6.

**Comment by mfussenegger** [comment]
We currently don't have any ppc64le infrastructure so we can't take a closer look at this. We also don't support it officially (yet).

But we're happy to accept contributions that would improve the support or fix this.

If this blocks the adaption of an enterprise offering and you're part of a company that would be willing to pay for ppc64le support, I guess it would be worth to [Contact our sales](https://crate.io/pricing/#contactsales) team.

**Comment by vibhutisawant** [comment]
Hi @mfussenegger 
I have a workaround to the test case failure:
In io.crate.integrationtests.ArithmeticIntegrationTest.java ,the following change is introduced at testSelectWhereArithmeticScalarTwoReferenceArgs function:


@@ -1 +1 @@
-Subproject commit 38c45a68fcb24f0d4fef2bb1abd20e8c58a0cd57
+Subproject commit 38c45a68fcb24f0d4fef2bb1abd20e8c58a0cd57-dirty
diff --git a/sql/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java b/sql/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
index 0912925..c38929b 100644
--- a/sql/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
+++ b/sql/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
@@ -163,14 +163,14 @@ public class ArithmeticIntegrationTest extends SQLTransportIntegrationTest {
         });
         execute("refresh table t");

-        execute("select x, base, log(x, base) from t where log(x, base) = 2.0 order by x");
+        execute("select x, base, round(log(x, base)) from t where round(log(x, base)) = 2 order by x");
         assertThat(response.rowCount(), is(2L));
         assertThat((Long) response.rows()[0][0], is(9L));
         assertThat((Long) response.rows()[0][1], is(3L));
-        assertThat((Double) response.rows()[0][2], is(2.0));
+        assertThat((Long) response.rows()[0][2], is(2L));
         assertThat((Long) response.rows()[1][0], is(144L));
         assertThat((Long) response.rows()[1][1], is(12L));
-        assertThat((Double) response.rows()[1][2], is(2.0));
+        assertThat((Long) response.rows()[1][2], is(2L));
     }


The change was done due to the following reason
for the instance t(x,base)=t(9,3) the value of log(x,base) returned is 2.0000000000000004 instead of 2
PFA the images for reference 
![data present in table t](https://user-images.githubusercontent.com/41043754/43898719-57e37d82-9bfd-11e8-8832-8d5620b8c6d8.png)
![output of log guery](https://user-images.githubusercontent.com/41043754/43898720-5815d4b2-9bfd-11e8-864f-6f9a52810fb2.png)
![values](https://user-images.githubusercontent.com/41043754/43898721-5844e630-9bfd-11e8-9973-5ae1bf436c45.png)


Would it be advisable to introduce such a change?
