### ISSUE TITLE
Running a SELECT query with a NOT IN and a subquery with a large result gives an error.

### ISSUE THREAD

**Issue by nocturnaltortoise** [crate/crate#7539]
**CrateDB version**: 2.3.11

**Environment description**:

 - JVM version: openjdk 1.8.0_171
 - Kernel: Linux 4.4.38
 - Distribution: Ubuntu 16.04.3 LTS
- Number of nodes: 3

**Problem description**:
Running a query like this:
```sql

SELECT * FROM armada.wind_turbine_data 
    WHERE timestamp NOT IN (
        SELECT date_trunc('minute', timestamp) FROM armada.wind_turbine_data 
            WHERE device_uuid = 'a8cb6363-52ae-4123-9978-5edf0005e369' 
            GROUP BY date_trunc('minute', timestamp) HAVING COUNT(*) > 1) 
     AND device_uuid = 'a8cb6363-52ae-4123-9978-5edf0005e369';
```

Gives this error:
```
SQLActionException[UnhandledServerException: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 8192]
```
The subquery does return a lot of results (30,243 rows), so it's understandable, I'm just wondering if there's a way round it - can I set the lucene maxClauseCount somehow? In any case this error is a little opaque - can I just not run queries with subqueries this large, or am I meant to be able to?

I don't see anything in the crate logs.

Here's the query to create the table, which has 27 million records in.
```sql
CREATE TABLE IF NOT EXISTS "armada"."wind_turbine_data" (
   "activity" FLOAT,
   "availability" FLOAT,
   "availability_true" FLOAT,
   "device_uuid" STRING,
   "direction_wind" FLOAT,
   "energy" FLOAT,
   "energy_cumulative" FLOAT,
   "interval_duration" INTEGER,
   "power_active" FLOAT,
   "power_theoretical" FLOAT,
   "rpm_generator" FLOAT,
   "rpm_rotor" FLOAT,
   "seconds_observed" INTEGER,
   "status" STRING,
   "timestamp" TIMESTAMP,
   "wind_speed" FLOAT,
   "wind_speed_max" FLOAT,
   PRIMARY KEY ("timestamp", "device_uuid")
)
CLUSTERED INTO 4 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)
```

**Comment by matriv** [comment]
@nocturnaltortoise you can change the setting in your crate.yml file check: https://crate.io/docs/crate/reference/en/latest/config/node.html#queries

Also if you have a really large result set in your subquery that cannot fit into memory you might consider using our experimental semi joins feature by setting a session variable: ``set enable_semijoin = true``. Notice this can only be used with Postgres Wire Protocol clients which support the session concept.

**Comment by matriv** [comment]
Closing for now, please feel free to re-open if you experience more issues here.
