### ISSUE TITLE
ERROR: Couldn't read log4j2.properties configuration file.

### ISSUE THREAD

**Issue by MohamedElqdusy** [crate/crate#7543]
When running crate like `$ ./gradlew runDebug` I got 

```
> Task :app:runDebug
Listening for transport dt_socket at address: 5005
ERROR: Couldn't read log4j2.properties configuration file.
> Task :app:runDebug FAILED
FAILURE: Build failed with an exception.

```

**Comment by matriv** [comment]
Are you using current `master`? Because for me it works:

```
~/crate/crate:master ✗ ➭ ./gradlew runDebug
...
> Task :app:runDebug
Listening for transport dt_socket at address: 5005
<============-> 99% EXECUTING [4m 33s]
> :app:runDebug
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
```

**Comment by MohamedElqdusy** [comment]
I have checked my current branch:
```
$ git branch
* master

```
other details may be relevant, running on Ubuntu 16.04

**Comment by MohamedElqdusy** [comment]
The error happens after trying to connect by IntelliJ:
`Connected to the target VM, address: 'localhost:5005', transport: 'socket'`
then I have the error by Gradle:
```
> Task :app:runDebug
Listening for transport dt_socket at address: 5005
ERROR: Couldn't read log4j2.properties configuration file.

> Task :app:runDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runDebug'.
> Process 'command '/usr/lib/jvm/java-9-oracle/bin/java'' finished with non-zero exit value 1
```
and on intelliJ:
`Disconnected from the target VM, address: 'localhost:5005', transport: 'socket'
`

**Comment by MohamedElqdusy** [comment]
I have found the variables in CrateDB.java have the values:
```
crateHomePath = /crate/app/build/runDebug
confPath = /crate/app/build/runDebug/config
```
which don't exist!

**Comment by mfussenegger** [comment]
Did you follow the instructions in the [developer docs](https://github.com/crate/crate/blob/master/devs/docs/basics.rst) ?

If you're using Intellij a simpler way to launch CrateDB for debugging is to use the `./gradlew idea` task which adds a `Crate` `Run/Debug` configuration which can be used to launch CrateDB from within intellij.

**Comment by MohamedElqdusy** [comment]
I have created the directory myself with its copied config content, the server side works fine but, when trying access webUI
`http://localhost:4200/`, It gives me the error 
`Requested file [/home/user/eclipse-workspace/crate/app/build/run/lib/site/index.html] was not found`
I have preserved it asks for the directory name as the gradle task name, so when using run task, it asks for `/crate/app/build/run`, when using runDebug task, it asks for` /crate/app/build/runDebug`

**Comment by MohamedElqdusy** [comment]
But, why I should create the directory by myself and then copy the config to make it work? when I use runDebug task it asks for the directory `/crate/app/build/runDebug/config` and when using run task `/crate/app/build/run/config`, is that behaviour related to Gradle?

**Comment by seut** [comment]
@MohamedElqdusy Our developer documentation was outdated and not correct anymore. We've updated it and also fixed the gradle setup in order to run `run` & `runDebug` without any additional steps. See https://github.com/crate/crate/pull/7714.
Thanks for reporting.
