### ISSUE TITLE
jdbc batch insert error

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7547]
table1（id integer），use jdbc execute batch method to insert data，error！
According to my test .The problem is the  field type int.

**Comment by mfussenegger** [comment]
Could you please provide some more information?

1) Which version of CrateDB are you using
2) Which version of crate-jdbc are you using
3) Can you provide a sample snippet that triggers the error
4) What is the exact error message?

**Comment by chaudum** [comment]
Duplicate of https://github.com/crate/crate-jdbc/issues/284

**Comment by cmdares** [comment]
After testing:
3.0.3 release error.
3.1 snapshot ok.

**Comment by chaudum** [comment]
@cmdares please provide answers to *all* questions. otherwise we will not be able to provide any help!
