### ISSUE TITLE
create table xxx as select * from yyy

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7551]
support:  create table xxx as select * from yyy
To improve the convenience of syntax, create temporary tables, use data ETL and so on.
Migration of compilation from traditional database (oracle/mysql/hive) to cratedb.
it is useful,thanks!

**Comment by chaudum** [comment]
duplicate of https://github.com/crate/crate/issues/7396

**Comment by mfussenegger** [comment]
Duplicate of https://github.com/crate/crate/issues/9999 - keeping the other issue because it has a more detailed description.
