### ISSUE TITLE
build archive  zip source code error

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7569]
**CrateDB version**:
archive 3.0.5 zip source code.

**Environment description**:
win7 x64 jdk 1.8
centos x64 jdk 1.8

**Problem description**:
Unzip the source code package and execute gradlew compileJava
the console throws: org.elasticsearch.common.io.stream not found
how to build ?
thanks.

**Comment by mfussenegger** [comment]
You're missing the submodules. You'll have to clone the repo using git and initialize the submodules.

Our [developer docs](https://github.com/crate/crate/blob/master/devs/docs/basics.rst) should get you started.

**Comment by cmdares** [comment]
The problem is that i can not clone complete, the network is unstable, and it often  error.
so how to compile with the archive  source code?

**Comment by mfussenegger** [comment]
You could download the source zip for [es/upstream](https://github.com/crate/crate/tree/master/es)  at the right commit separately and extract it into the right place in the `crate/crate` sources.
