### ISSUE TITLE
how to reduce disk space comsume in cratedb

### ISSUE THREAD

**Issue by seanlook** [crate/crate#7581]
I've reported the same data to OpenTSDB, InfluxDB and CrateDB:
CrateDB takes disk space about 2 times bigger than OpenTSDB, OpenTSDB takes about 2-3 times than InfluxDB.

Is there any practices that I can make the disk space smaller in CrateDB?  
1. Setting `INDEX OFF` on fields that not for search, or make the field names shorter?
2. Changing mapping in elasticsearch like disabling `_source` and `_all`?

**Comment by izloop** [comment]
Hi there @seanlook ,

You can Optimise CrateDB in various ways - have you experimented with the two issues you suggested? 

Here is also more documentation on Optimisation within CrateDB...

https://crate.io/docs/crate/reference/en/latest/admin/optimization.html

https://crate.io/docs/crate/reference/en/latest/sql/statements/optimize.html#sql-ref-optimize

Please do feedback to me with your results and any further queries.

Thanks.
Peter

**Comment by seanlook** [comment]
I'm not talking about query performance, but the storage space it takes.
