### ISSUE TITLE
update bigdata too slow

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7582]
cratedb 3.0.5  
os centos 6.5 x64  
server:(Xeon E5 cpu 2.8G  mem:128G hdd:2T )*4
node:16nods   4node/per server  crate jvm heap:16G
table_a:10 billion
update table_a set xxx='111',yyy='2222' where userid='xxx' 
update 20rows.
the speed is too slow. 10s.

**Comment by izloop** [comment]
Hi there @cmdares ,

Could you please provide more information like `table_a` schema? 

Best Regards,
