### ISSUE TITLE
Joins performance with Order By

### ISSUE THREAD

**Issue by thirtysixmm** [crate/crate#7592]
**CrateDB version**: 2.2.4

**Environment description**:
java version "1.8.0_121"
OS : Windows 10
Nodes : 1

**Problem description**:
Performance of joins with order by clause is poor. 

**Steps to reproduce**:
Query
`select p1.ID, p1.post_title,t1.name, t1.value from wp_posts p1, table_t1 t1 WHERE t1.post_id = p1.ID  ORDER BY t1.created_date DESC limit 10; `

 The table wp_posts has almost 25 columns and the t1 table has ~25 columns too. wp_posts table has around 90K data and table_t1 table has around 12K data.

When I execute that query, my CPU usage was 100% and the time taken to get results was more than 15 minutes . If I remove the order by clause, the time taken to get results has become ~10 seconds.

**Comment by izloop** [comment]
Hi there @thirtysixmm - 

The `order by` clause is really important and will yield a greater and more accurate return! 
As anything without `order by` will only yield the first 10.000 rows produced by the join.

**Comment by izloop** [comment]
I forgot to mention that it would be preferential if you could look into upgrading to 3.0 as you would be able to take advantage of HashJoins which will eliminate this issue and increase performance.

I hope this helps!

**Comment by thirtysixmm** [comment]
Thanks the same query works really fast in version 3.0.5
