### ISSUE TITLE
support “DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP”

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7628]
eg.
CREATE TABLE USER(
  id INT PRIMARY KEY,
  name STRING,
  age INT, 
  updatetime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

**Comment by izloop** [comment]
You encounter this issue when you are creating a table user @cmdares?

**Comment by cmdares** [comment]
According to the requirements of system construction, database tables need a column of system timestamp. When this row of data is inserted or updated, the timestamp field needs to be updated dynamically to the current system time.
MySQL can support this requirement natively.  support insert and update
CREATE TABLE `timestampTest` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8

and postgresql support insert
https://stackoverflow.com/questions/9556474/how-do-i-automatically-update-a-timestamp-in-postgresql

and how about cratedb? 
expected!

**Comment by seut** [comment]
You can make use of GENERATED COLUMNS (https://crate.io/docs/crate/reference/en/latest/general/ddl/generated-columns.html) to solve that:

```
create table t1 (id int, last_modified_time as current_timestamp);
insert into t1 (id) values (1);
select last_modified_time from t1;
update t1 set id = 2;
select last_modified_time from t1;
```

**Comment by cmdares** [comment]
Well done! Graceful !
thanks!
