### ISSUE TITLE
Add ability to sort on alias with subscript expr

### ISSUE THREAD

**Issue by bputt** [crate/crate#7644]
**Use case**: If I am querying multiple percentiles, it would be great if I could order by a specific index

**Feature description**: When executing a query like:
```
SELECT count(*), PERCENTILE(field, [ .90, .95, .99 ]) as fieldper ORDER BY fieldper[0]
```
It'd be great if it provided me the ability to order the results by ```.90, .95, or .99```

**Comment by izloop** [comment]
Let me have a look at this for you!

**Comment by mfussenegger** [comment]
Looks like we've an issue detecting that `fieldper` is an alias if a subscript expression is also there.
If you use the full function name in the ORDER BY it works:

```
select 
    count(*), percentile(x, [.90, .95, .99]) as fieldper 
from 
    t 
group by country 
order by  percentile(x, [.90, .95, .99])[1] desc;
```

We'll have a closer look why addressing it by alias doesn't work.

**Comment by mfussenegger** [comment]
This is unfortunately more complex to support than initially expected.
We'll have to change some internal representations. It's something we want to do but it has no immediate priority.

We're keeping this open as feature addition for the future. Meanwhile the workaround by addressing the expression directly without alias can be used.
