### ISSUE TITLE
Streaming and queries

### ISSUE THREAD

**Issue by ondrejtomcik** [crate/crate#7658]
Dear crateDB team,
as we are evaluating storage technology for our measurements, I would like to ask you few questions I am not sure about from your documentation.

 **Use case** 
Our devices has attached sensors and are streaming data with high sampling rate. That means hundreds of thousands samples per second (e.g. 200 000 from one device). On the backend we are processing these data, selecting specific section if condition based on value or time is met,

 **Questions** 

- Is the 1 crate node capable of such a throughput?
- Do you have thresholds configuration for stream transfer - how many messages are transfered at once (batching) (e.g. how long they can stay in the buffer on the device, time or size constants)
- Can we on the backend subscribe to the stream coming directly from the device to render real-time graph?
- Can we specify the query on the stream and receive the data when the condition is met during active streaming ? Or we have to actively poll the data?

Thanks a lot for your answers.

**Comment by izloop** [comment]
Hi there @ondrejtomcik - I will forward this to one of our PreSales Engineers @yash2.

Thank you!

**Comment by yash2** [comment]
Hi @ondrejtomcik - Could you please share your email id or contact info to connect via email and discuss more specific details on this usecase?

**Comment by ondrejtomcik** [comment]
@yash2 please contact me @ tomcik.ondrej@gmail.com
