### ISSUE TITLE
Add "replace" to update queries, just like in SQL

### ISSUE THREAD

**Issue by hnstbndr** [crate/crate#7679]
**Use case**: Update several entries, where I need to replace a certain string value. There is no need to select the items.

**Current solution**: Select all desired entries and update one by one. This is a performance nightmare.

**Feature description**: When updating an entry, use the following syntax (works in "normal" SQL):
`UPDATE myTable set someValue=REPLACE(someValue, 'old text', 'new text')
WHERE someID='71AD3D9C-7755-474D-BA78-B23AF9968030'`

Would be great if this would work with crate as well.

**Additional info**: Should also be made available for updating arrays, where one could remove or add an item to the array(s if multiple entries), without actually fetching them.

**Comment by izloop** [comment]
Hi @hnstbndr 
I will forward this on to the right department and keep you updated on how this progresses,
is that OK?

**Comment by hnstbndr** [comment]
@izloop thanks, sounds like a plan. any idea on an ETA?

**Comment by izloop** [comment]
@hnstbndr I will update you once I know more!

**Comment by mfussenegger** [comment]
As a workaround, by using [UDF](https://crate.io/docs/crate/reference/en/latest/general/user-defined-functions.html?highlight=udf) it would be possible to quickly implement a `replace` function in Javascript.

We've no concrete plans to add this, but would very much like to have this function - so contributions would be great.
We might squeeze this in some time anyhow otherwise, but we can't give an ETA

**Comment by hnstbndr** [comment]
@mfussenegger finally got around to check out the proposed quick solution with JS. Unfortunately, this is only available with the enterprise edition. We are not there yet, to get a license, still in the "finding the right database" phase. I thought enterprise features are enabled by default and only need to be purchased after one goes live... so there is no chance to try it out?

**Comment by mfussenegger** [comment]
>  I thought enterprise features are enabled by default and only need to be purchased after one goes live... so there is no chance to try it out?

CrateDB currently launches by default in enterprise mode. It's allowed to use the enterprise features for trial/evaluation. But javascript language support for UDF has to be enabled separately (`lang.js.enabled: true` in `crate.yml`)

**Comment by hnstbndr** [comment]
@dominikmoosbrugger has this been implemented? or why did you close the issue?

**Comment by dominikmoosbrugger** [comment]
@hnstbndr Sorry for this, it seems this happened in error. We will reopen this, of course @mfussenegger also notified me about that.

**Comment by mfussenegger** [comment]
We've merged a `replace` scalar with https://github.com/crate/crate/pull/7924, it will be available with 3.2
