### ISSUE TITLE
Add ability to add multiple columns in one alter table statement

### ISSUE THREAD

**Issue by bputt** [crate/crate#7687]
**Use case**: Let's say I have 10 columns that need to be added, instead of having to manually alter the table and add a column at a time, it'd be great to add the columns needed in one statement.

**Feature description**:
```
ALTER TABLE mytable ADD COLUMN x STRING, ADD COLUMN Y LONG
```

**Comment by izloop** [comment]
Thanks for this @bputt,
I will forward this on to the right department and keep you updated on how this progresses,
is that OK?

**Comment by bputt** [comment]
@izloop yup, that's fine

**Comment by jeeminso** [comment]
can this issue be assigned to me?

**Comment by seut** [comment]
@jeeminso Yes sure, go ahead. Thanks!

**Comment by rijnhard** [comment]
Just as a note regarding the broader ecosystem. This breaks Hevo Data's Schema mapper.

**Comment by seut** [comment]
@rijnhard Thanks for this insight. Please also upvote, this will help us on future prioritization.

**Comment by BaurzhanSakhariev** [comment]
Support for adding multiple columns in a single ALTER TABLE statement has been implemented in https://github.com/crate/crate/pull/13383 and will be available in the next release (CrateDB 5.2)
