### ISSUE TITLE
/_blobs not taking cors settings into account -> missing Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#7719]
I had set the following in crate.yml but its still not sending the `Access-Control-Allow-Origin` to the client
```
http.cors.enabled: true

http.cors.allow-origin: "*"
```

**Comment by izloop** [comment]
Could you please post more information on this @CheyenneForbes?

Thanks

**Comment by CheyenneForbes** [comment]
This is the code I am using for testing:
```
$.ajax({
   url: "http://192.168.1.4:4200/_blobs/uploads/0a1fe268ba9121acec271665ce5cafb2ecd37cab",
   beforeSend: function (xhr) {
        xhr.setRequestHeader ("Authorization", "Basic " + btoa("username:password"));
   },
   success: function(result){
        window.returnedData = result;
   }
});
```
but I am getting back:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.4' is therefore not allowed access.
```

I then used Postman to view the response but the only returned header is `content-length` and no 'Access-Control-Allow-Origin' header is present

**Comment by CheyenneForbes** [comment]
Based on further observations, Crate is also requiring authentication for the `OPTIONS` method which if I am correct http client libraries dont "do" authentication for the `OPTIONS` method when the request is a "pre-flight" request to check if the server supports CORS before the real request is sent since its used to get what a server allows/supports... I came to this conclusion after disabling the CORPS security feature in chrome then checking the server terminal, I saw `[2018-10-03T07:31:33,510][WARN ][i.c.p.h.HttpAuthUpstreamHandler] unauthorized http chunk`

**Comment by izloop** [comment]
Sorry, I should have asked this earlier but where exactly are you encountering this issue?

Is this in relation to Docker?

**Comment by CheyenneForbes** [comment]
No, installed it directly

**Comment by CheyenneForbes** [comment]
any update?

**Comment by mfussenegger** [comment]
Looks like all resources beneath `/_blobs` are not handling the CORS settings / headers correctly.

Thanks for reporting. We'll have a closer look at that.

**Comment by CheyenneForbes** [comment]
the headers are now sent but the OPTIONS method which browsers send first when doing cross origin requests is requiring authentication which is causing it to fail still in browsers, the HTTP specs says authentication should not be required for OPTIONS

**Comment by CheyenneForbes** [comment]
https://fetch.spec.whatwg.org/#cors-protocol-and-credentials

**Comment by mfussenegger** [comment]
Ah right, sorry I had skipped over the OPTIONS remark. We'll have a look at that as well

**Comment by mfussenegger** [comment]
We've merged another fix for this (https://github.com/crate/crate/pull/7768) so this should work now.
