### ISSUE TITLE
Doc on using Crate with Docker - cannot mount crate.yml

### ISSUE THREAD

**Issue by biglobe** [crate/crate#7724]
Hi all, I'm new to Crate and Docker. I was meddling around running Crate on Docker and found that I cannot easily modify the configuration file to adjust how Crate is run in Docker. 

Today I found the following instructions on how crate.yml can be mounted for persistence sake and for modification.
[https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html#custom-configuration](url)

However the instructions given cannot be run successfully. I received the following error.
<img width="1059" alt="screen shot 2018-10-04 at 12 56 06 am" src="https://user-images.githubusercontent.com/4609085/46427409-f4618b80-c773-11e8-9223-bfdfba9a03ba.png">

Would appreciate if someone can point me in the right direction to configure crate in Docker. Thanks!

**Comment by izloop** [comment]
Hey @biglobe - 
have you looked into this https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html?

Let me know!

**Comment by biglobe** [comment]
Hi @izloop 
yes i was following instructions in that page.

are you by any chance trying to say that all steps under "Best practices" must be followed?


> Hey @biglobe -
> have you looked into this https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html?
> 
> Let me know!

**Comment by izloop** [comment]
Hi @biglobe well, they are recommended for best performance so I would look into that as well :) 

Let me know how that works for you!

**Comment by mfussenegger** [comment]
Are you setting `path.data` in your config file? `/crate` in the container contains the crated installation. `/data` is for the data. That's probably why you're seeing a permission error
