### ISSUE TITLE
Data Type for currency

### ISSUE THREAD

**Issue by biglobe** [crate/crate#7732]
Hi, 

**Feature description**:
According to docs on supported [Data Types](https://crate.io/docs/crate/reference/en/3.1/general/ddl/data-types.html#numeric-types), `float` and `double` are singled out as not suitable for precision use cases, eg currency.

Since CrateIO is developed in Java, why not implement the BigDecimal equivalent data type as well. IEEE 754 decimal 128-bit precision is already implemented in many languages and database. It should be an important feature to be supported by CrateIO for many more use cases.

**Comment by izloop** [comment]
Thanks for this @biglobe  - I will look into this and let you know the outcome!

**Comment by biglobe** [comment]
> Thanks for this @biglobe - I will look into this and let you know the outcome!

looking forward!

**Comment by mfussenegger** [comment]
We added storage support for numeric: https://github.com/crate/crate/pull/16471
