### ISSUE TITLE
Timestamp data retrieved via jdbc is 1 microsecond off

### ISSUE THREAD

**Issue by tellezb** [crate/crate#7741]
**CrateDB version**:
Crate 2.3.11
Crate-jdbc 2.3.1

**Environment description**:
Crate running in docker (image crate:2.3.11)

**Problem description**:
When pulling timestamp data from Crate, there is often (if not always) a microsecond missing from the expected value. When this is converted to a java DateTime, the microseconds get truncated, resulting in a DateTime object short by a full millisecond.

**Jdbc query**
`jdbcTemplate.query("SELECT END_DATE FROM TABLE", args, new CrateRowMapper());`

**Column definition**
`"end_date" TIMESTAMP`

**Returned java.sql.Timestamp value**
`2018-10-05 09:50:50.052999`

**Expected value (as persisted in Crate, and shown on Admin UI)**
`1538758250053 (2018-10-05T16:50:50.053Z)`

This occurs for all of my timestamp columns.

**Comment by izloop** [comment]
Thanks for this! 

Is it a possibility to upgrade the version of crate and see if this continues @tellezb?

**Comment by tellezb** [comment]
I performed additional tests using the following environments:

1. (failed) Crate 2.3.11, Crate-jdbc 2.3.1
2. (failed) Crate 2.3.11, Crate-jdbc 2.4.0
3. (passed) Crate 3.1.1, Crate-jdbc 2.3.1
4. (passed) Crate 3.1.1, Crate-jdbc 2.4.0

It appears that this is no longer an issue in Crate 3.1.1. Hopefully 2.3 can be fixed?

**Comment by mfussenegger** [comment]
We're usually only backporting to the last stable release unless it's something critical. That's currently 3.1.
I'm afraid you'll have to update to receive the fix
