### ISSUE TITLE
windows copy from csv fault

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7781]
env: win10 x64  jdk 1.8.0_181  crate 3.1.1  single node
crate install dir: 
E:\crate
csv file path:
D:\date\data1.csv(utf-8)
csv file content:
id,name,sdate
1,"test","2018-01-01T23:59:59"
2,"test","2018-01-01T23:59:59"

CRATE TABLE test1(id integer,name string,sdate timestamp);

COPY test1 FROM 'D:\data\data1.csv';

Error
SQLActionException[SQLParseException: Illegal character in opaque part at index 2: D:\learn\crate\testdata2.csv]

COPY test1 FROM 'D:/crate/data1.csv'  RETURN SUMMARY;
COPY OK, 0 rows affected (0.004 sec)
Finish but 0 rows！
and return summary message say: "unknown protocol: d:"
So through analysis and research，the csv file must  be placed  on the same partition with the cratedb installation. 
Then copy the csv file to e:\data\    and  exec
COPY test1 FROM '/data/data1.csv';  --is ok data can be insert.

**Comment by seut** [comment]
You must use a valid file URI, on windows see e.g.: https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/
