### ISSUE TITLE
[Feature Request] To support "discovery.zen.fd.ping_retries: -1"

### ISSUE THREAD

**Issue by diyism** [crate/crate#7784]
**Use case**:
I'm building a cratedb cluster with my friends all around the world throud Wireguard VPN,
but some peer's network maybe is behind NAT, their IP-Ports always are changing,
so currently i need tell them to set this in their /etc/crate/crate.yml:
discovery.zen.fd.ping_retries: 259200    //from: https://gist.github.com/diyism/529947bb497a18530347c5449992d491#file-install-cratedb-in-kali-L38

Although everyone will share their dynamic ip-port through a CrateDB table with a signed field, but if even one peer node is down, ping_retries will exhausted in one month, and eventually many friend's nodes will be off the cratedb cluster.

**Feature description**:
So i wish CrateDB to support "discovery.zen.fd.ping_retries: -1", the "-1" means retry infinitely.

Thanks.

**Comment by izloop** [comment]
Thanks, @diyism - I will raise this with the team! 👍

**Comment by joemoe** [comment]
@diyism see my comment here: https://github.com/crate/crate/issues/7785#issuecomment-431262315
