### ISSUE TITLE
[Feature Request] To enable us to disable master-node initial connection when insert-only use case

### ISSUE THREAD

**Issue by diyism** [crate/crate#7785]
**Use case**:
I'm building a cratedb cluster with my friends all around the world through Wireguard VPN.

The network connection is unstable, for example:   node A connected node B, while node B connected node C,   but node A and node C cannot connect directly (both A and C is behind a symetric NAT, so that Wireguard can not break through).
On "http://B:4200/" i can see B and C is connected and status are green, and C is the master node.
On "http://A:4200/" i can see only A, and in crate.log of A i saw "failed to connect to master [C], retrying...", but it will retrying connect to [C] forever, because both A and C is behind symetric NAT.

I've tried setting "discovery.zen.minimum_master_nodes: 0"   in crate.yml of A.

**Feature description**:
So i wish there's a setting item to enable us to disable initial-connection to master-node when in insert-only use case.

**Comment by diyism** [comment]
If enable node A to connect node B first without forever retrying connect to the master node C,   node A maybe can get the exposed IP:port of node C from the crate table of node B, and eventually node A can connected node C directly with the exposed IP:port.

**Comment by diyism** [comment]
In http://crate.io,  "Masterless architecture with auto-sharding & replication. Simple to scale and to keep running, 24x7",   it seems not so masterless,  in the upper case,  master node C can be seen by node B but can not be seen by node A,  that lead to node A won't connect node B, even if the network between A and B is good.

**Comment by diyism** [comment]
my config:
```
#=====crate config: /etc/crate/crate.yml:
network.host: 10.1.0.3
discovery.zen.ping.unicast.hosts:
   - 10.1.0.1:4300
   - 10.1.0.5:4300

node.name: 10.1.0.3

discovery.zen.fd.ping_timeout: 9s
discovery.zen.fd.ping_retries: 259200         #Fault Detect,  if only one peer node is down, ping_retries will exhausted in one month
discovery.zen.fd.ping_interval: 10s

auth.host_based.enabled: true
auth.host_based.config.0.user: crate
auth.host_based.config.0.address: 10.1.0.3
auth.host_based.config.0.method: trust
```

**Comment by izloop** [comment]
Thanks for this @diyism - again I will raise this with the team! 👍

**Comment by joemoe** [comment]
Hi @diyism, 

the usecase CrateDB is built around assumes a by default stable network connection between the nodes. CrateDB is perfectly able to balance high loads and its intend is to handle it by distributing it through a network over several nodes. 
We need to be rather strict about which nodes can be part of a cluster and which not to guarantee consistency and avoiding split brain scenarios, that's the only purpose of the so called master.
Although your use case seems legit this is not an priority for us at the moment. Most of our customers run a CrateDB cluster in a dedicated network with the nodes being provisioned in the same cloud region. That's what we put most of our effort in at the moment.
I'm closing this issue for now.

I'm sorry for not having better news for you.

Thanks, Joe
