### ISSUE TITLE
copy  from with(shared=true),i can not get data from csv file

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7792]
i use copy from without option (shared=true),i can get the date of csv file,but when i use the option (shared=true),i can not get the data

**Comment by seut** [comment]
Please provide us more information, like steps to reproduce like our issue template tells you to do.

**Comment by izloop** [comment]
Can you please elaborate on this issue @gongweibiao1986 ? Can you provide more information on the current CrateDB setup you are using and OS as well as more regarding the issue?

Thank you,
Peter

**Comment by gongweibiao1986** [comment]
> Please provide us more information, like steps to reproduce like our issue template tells you to do.
I used Linux's 64-bit server, 8 machines, and built 32 nodes in total. My version of crateDB is 3.0.5.
Configuration information,I just configured cluser. Name, node. The name, node. Max_local_storage_nodes: 32, the network. The host and gateway. Recover_after_nodes: 2, gateway. Recover_after_time: 5 m, gateway expected_nodes: 32, discovery. Zen. Ping. Unicast. Hosts and discoveryMinimum_master_nodes :17, psql.enabled:true, psql.port.
The problem I had was,
When I used copy from to get the data in the CSV file, I got duplicate data.
When I use the option Shared =true, I can't read any more data in the CSV file

**Comment by mfussenegger** [comment]
Do *all* nodes have access to the data location? If you use `shared=true` only a single node will attempt the read operation. If you're able to upgrade to `3.1.x` you could also use the [RETURN SUMMARY](https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-from.html#return-summary) clause to get more information about what is going on.
