### ISSUE TITLE
add Commonly used system functions

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7800]
Some commonly useful system functions are very necessary for the database.
Most sinario will be applied to these function，so expect official  add to the system library.

- [x] REPLACE
- [x] LPAD/RPAD
- [ ] TRIM/RTRIM/LTRIM

regard!
thanks!

**Comment by mfussenegger** [comment]
I've removed [regexp_replace](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html?highlight=regexp_replace#regexp-replace-source-pattern-replacement-flags) and [coalesce](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#coalesce-first-arg-second-arg) from your feature request as those already exist
