### ISSUE TITLE
Zombie queries left in crate.io after using crate JDBC driver

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#7808]
CrateDB v3.0.3

**Environment description**:
 - Debian 8 (jessie) on AWS
 - OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
 - OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
 - Crate.io v3.0.3-1~jessie
 - 3 nodes per cluster
 - Kernel 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

**Problem description**:
The following components are installed:
Splunk:
 - Debian 8 (jessie) on AWS
 - Splunk 7.2.0
 - Splunk DB Connect
 - Java 18.9 build 11+28 in 64 bit
 - Crate JDBC standalone driver (crate-jdbc-standalone-2.4.0.jar) in Splunk as a JDBC driver
Crate:
 - Debian 8 (jessie) on AWS
 - OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
 - OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
 - Crate.io v3.0.3-1~jessie
 - 3 nodes per cluster

We are connecting through the JDBC driver from Splunk to the Crate instance (in the same AWS VPC) accessing the Crate DB through the JDBC driver. Our purpose is to copy the data from one table gradually into Splunk using chunks of the content into splunk. We are running the following query on a large table (1M records):
SELECT * FROM Table_A WHERE timestamp > ? ORDER BY timestamp ASC LIMIT 5000
where ? is a checkpoint that gets increased after each execution to receive the next 5000 rows. On Driver Level, the timeout is set to 180, row limit to 5000 and fetch size to 5000 as well. This SQL command is executed every 5min, returns the data successfully to Splunk within 1s, but we see the SQL statement still orphaned on Crate:

cr> select * from sys.jobs where id in ('8de58512-28ed-4145-8ddc-6fdf3e9810e4','374a58fc-7fa6-4ea8-bd4f-4b368bda870f');
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| id                                   | node                                                |       started | stmt                                                                     | username |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| 374a58fc-7fa6-4ea8-bd4f-4b368bda870f | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540381680223 | SELECT * FROM Table_B where timestamp > $1 order by timestamp Limit 1000 | crate    |
| 8de58512-28ed-4145-8ddc-6fdf3e9810e4 | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540364400037 | SELECT * FROM Table_A where timestamp > $1 order by timestamp Limit 5000 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
SELECT 2 rows in set (0.098 sec)
cr> select current_timestamp-1540364400037;
+-------------------------------------+
| (current_timestamp - 1540364400037) |
+-------------------------------------+
|                            25134092 |
+-------------------------------------+
SELECT 1 row in set (0.001 sec)
cr> kill '374a58fc-7fa6-4ea8-bd4f-4b368bda870f';
KILL OK, 3 rows affected  (0.009 sec)
cr> kill '8de58512-28ed-4145-8ddc-6fdf3e9810e4';
KILL OK, 0 rows affected  (0.113 sec)
cr> select * from sys.jobs where id in ('8de58512-28ed-4145-8ddc-6fdf3e9810e4','374a58fc-7fa6-4ea8-bd4f-4b368bda870f');
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| id                                   | node                                                |       started | stmt                                                                     | username |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| 374a58fc-7fa6-4ea8-bd4f-4b368bda870f | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540381680223 | SELECT * FROM Table_B where timestamp > $1 order by timestamp Limit 1000 | crate    |
| 8de58512-28ed-4145-8ddc-6fdf3e9810e4 | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540364400037 | SELECT * FROM Table_A where timestamp > $1 order by timestamp Limit 5000 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
SELECT 2 rows in set (0.002 sec)
cr> kill '374a58fc-7fa6-4ea8-bd4f-4b368bda870f';
KILL OK, 0 rows affected  (0.001 sec)
cr> kill '8de58512-28ed-4145-8ddc-6fdf3e9810e4';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id in ('8de58512-28ed-4145-8ddc-6fdf3e9810e4','374a58fc-7fa6-4ea8-bd4f-4b368bda870f');
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| id                                   | node                                                |       started | stmt                                                                     | username |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
| 374a58fc-7fa6-4ea8-bd4f-4b368bda870f | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540381680223 | SELECT * FROM Table_B where timestamp > $1 order by timestamp Limit 1000 | crate    |
| 8de58512-28ed-4145-8ddc-6fdf3e9810e4 | {"id": "X0tHPJ8pQhuoAYDwx8wioA", "name": "crate01"} | 1540364400037 | SELECT * FROM Table_A where timestamp > $1 order by timestamp Limit 5000 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+--------------------------------------------------------------------------+----------+
SELECT 2 rows in set (0.002 sec)
cr> select count(*) from Table_B;
+----------+
| count(*) |
+----------+
|    19938 |
+----------+
SELECT 1 row in set (0.001 sec)
cr> select count(*) from Table_A;
+----------+
| count(*) |
+----------+
|  1314699 |
+----------+
SELECT 1 row in set (0.001 sec)

As you can see from above snippet, queries started through crate JDBC driver cannot be killed. First kill attempt returns "KILL OK, 3 rows affected" and further attempts returns "KILL OK, 0 rows affected". 
The only way to make them disappear from sys.jobs is to restart crate service.

**Comment by mfussenegger** [comment]
Thanks for reporting.

1) Would it be possible to try to reproduce this with a couple less components
involved? Ideally only JDBC and CrateDB with a minimal app.


2) Is it possible to reproduce this with CrateDB 3.1.2 as well? We've done some
fixes in that area, but I'm not sure if they're already in 3.0.3 or not.

**Comment by daniel11c** [comment]
Thank you for suggestions!
1. We have just tried with SQuirreL and crate JDBC driver with simple queries. Result is the same: sometimes the query hangs and cannot be killed.
cr> select * from sys.jobs where id='b2c323a6-c404-4130-8534-b2aa57e16eef';
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| id                                   | node                                                |       started | stmt                            | username |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| b2c323a6-c404-4130-8534-b2aa57e16eef | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540459644931 | select * from Table_A limit 100 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr> kill 'b2c323a6-c404-4130-8534-b2aa57e16eef';
KILL OK, 0 rows affected  (0.002 sec)
cr> select * from sys.jobs where id='b2c323a6-c404-4130-8534-b2aa57e16eef';
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| id                                   | node                                                |       started | stmt                            | username |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| b2c323a6-c404-4130-8534-b2aa57e16eef | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540459644931 | select * from Table_A limit 100 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr> kill 'b2c323a6-c404-4130-8534-b2aa57e16eef';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id='b2c323a6-c404-4130-8534-b2aa57e16eef';
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| id                                   | node                                                |       started | stmt                            | username |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| b2c323a6-c404-4130-8534-b2aa57e16eef | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540459644931 | select * from Table_A limit 100 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
SELECT 1 row in set (0.001 sec)
cr> kill 'b2c323a6-c404-4130-8534-b2aa57e16eef';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id='b2c323a6-c404-4130-8534-b2aa57e16eef';
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| id                                   | node                                                |       started | stmt                            | username |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| b2c323a6-c404-4130-8534-b2aa57e16eef | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540459644931 | select * from Table_A limit 100 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
SELECT 1 row in set (0.002 sec)

2. We will try with latest version too, but it will take some time.
We are more puzzled by the fact that kill 'pid' doesn't work rather than the fact that some queries do not return data.

**Comment by daniel11c** [comment]
Including details from sys.operations too
cr> select * from sys.jobs where id='fb24ea84-d7a2-4501-afa2-e1c22b790dea';
    select * from sys.operations where job_id='fb24ea84-d7a2-4501-afa2-e1c22b790dea';
    select current_timestamp;
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| id                                   | node                                                |       started | stmt                            | username |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
| fb24ea84-d7a2-4501-afa2-e1c22b790dea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540465609975 | select * from Table_A limit 500 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+---------------------------------+----------+
SELECT 1 row in set (0.001 sec)
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
| id | job_id                               | name           | node                                                |       started | used_bytes |
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
| 1  | fb24ea84-d7a2-4501-afa2-e1c22b790dea | mergeOnHandler | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540465609975 |       NULL |
| 2  | fb24ea84-d7a2-4501-afa2-e1c22b790dea | fetchPhase     | {"id": "wW-FKHkISNetAuyi86G6lg", "name": "crate02"} | 1540465609977 |       NULL |
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
SELECT 2 rows in set (0.002 sec)
+-------------------+
| current_timestamp |
+-------------------+
|     1540469232601 |
+-------------------+
SELECT 1 row in set (0.000 sec)

**Comment by daniel11c** [comment]
Even with no table involved:
cr> select * from sys.jobs where stmt='SELECT 1';
    select * from sys.operations where job_id in (select id from sys.jobs where stmt='SELECT 1');
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
| id                                   | node                                                |       started | stmt     | username |
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
| 6c3e780b-10b4-4199-9816-0835f273b8c5 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484202808 | SELECT 1 | crate    |
| 59202b00-67a2-4f48-9456-4abbd69507bc | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540482885321 | SELECT 1 | crate    |
| f04cc64a-6a06-4a6b-b74f-4bc07d637892 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484058236 | SELECT 1 | crate    |
| 085a9cfd-d882-44d6-b579-475821c03404 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540483856460 | SELECT 1 | crate    |
| d77d1798-9804-49c5-952b-5b0611668ff5 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540483592376 | SELECT 1 | crate    |
| adc45ddb-bc00-474d-b8fa-9ff4cd2beac8 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484913038 | SELECT 1 | crate    |
| 1f2f6745-9c83-4eb1-b659-cce0e25357e6 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484806979 | SELECT 1 | crate    |
| 1ed40831-6904-4eed-9dc6-e54878d76cb9 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540481993314 | SELECT 1 | crate    |
| addcaeeb-2af4-4f89-bc9e-567d6cebdbb3 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540482706491 | SELECT 1 | crate    |
| 12dc72bc-4e99-499e-8815-0f2f9bc412ea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484428506 | SELECT 1 | crate    |
| 541e84e9-df79-4538-b693-f0d8d2872d06 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484673915 | SELECT 1 | crate    |
| 18b4111e-303e-467d-9c6a-e98be3e0ea16 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540535514413 | SELECT 1 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
SELECT 12 rows in set (0.002 sec)
+----+--------------------------------------+-----------+-----------------------------------------------------+---------------+------------+
| id | job_id                               | name      | node                                                |       started | used_bytes |
+----+--------------------------------------+-----------+-----------------------------------------------------+---------------+------------+
| 0  | 6c3e780b-10b4-4199-9816-0835f273b8c5 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484202808 |       NULL |
| 0  | 59202b00-67a2-4f48-9456-4abbd69507bc | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540482885321 |       NULL |
| 0  | f04cc64a-6a06-4a6b-b74f-4bc07d637892 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484058236 |       NULL |
| 0  | 085a9cfd-d882-44d6-b579-475821c03404 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540483856460 |       NULL |
| 0  | d77d1798-9804-49c5-952b-5b0611668ff5 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540483592376 |       NULL |
| 0  | adc45ddb-bc00-474d-b8fa-9ff4cd2beac8 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484913038 |       NULL |
| 0  | 1f2f6745-9c83-4eb1-b659-cce0e25357e6 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484806979 |       NULL |
| 0  | 1ed40831-6904-4eed-9dc6-e54878d76cb9 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540481993314 |       NULL |
| 0  | addcaeeb-2af4-4f89-bc9e-567d6cebdbb3 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540482706491 |       NULL |
| 0  | 12dc72bc-4e99-499e-8815-0f2f9bc412ea | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484428506 |       NULL |
| 0  | 541e84e9-df79-4538-b693-f0d8d2872d06 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484673916 |       NULL |
| 0  | 18b4111e-303e-467d-9c6a-e98be3e0ea16 | empty_row | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540535514413 |       NULL |
+----+--------------------------------------+-----------+-----------------------------------------------------+---------------+------------+
SELECT 12 rows in set (0.003 sec)
cr> kill '6c3e780b-10b4-4199-9816-0835f273b8c5';
KILL OK, 1 row affected  (0.001 sec)
cr> kill '6c3e780b-10b4-4199-9816-0835f273b8c5';
KILL OK, 0 rows affected  (0.003 sec)
cr> kill '6c3e780b-10b4-4199-9816-0835f273b8c5';
KILL OK, 0 rows affected  (0.001 sec)
cr> kill '6c3e780b-10b4-4199-9816-0835f273b8c5';
KILL OK, 0 rows affected  (0.001 sec)
cr> kill '6c3e780b-10b4-4199-9816-0835f273b8c5';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id='6c3e780b-10b4-4199-9816-0835f273b8c5';
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
| id                                   | node                                                |       started | stmt     | username |
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
| 6c3e780b-10b4-4199-9816-0835f273b8c5 | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1540484202808 | SELECT 1 | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+----------+----------+
SELECT 1 row in set (0.001 sec)

**Comment by andreidan** [comment]
Hi @daniel11c I was unable to reproduce this. 

Can you please tell me the jdbc url you're using to connect to crate?

Can you also please upgrade to CrateDB 3.1.2, as there are a few improvements in the jobs management area part of the 3.1 release, and try again?

Thanks.

**Comment by daniel11c** [comment]
We upgraded to 3.1.2 and the issues is still present in this version:

cr> select * from sys.jobs where id='345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| id                                   | node                                                |       started | stmt                        | username |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1541408279532 | select * from ourdb.Table_C | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr> select * from sys.operations where job_id='345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
| id | job_id                               | name           | node                                                |       started | used_bytes |
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
| 1  | 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | mergeOnHandler | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1541408279532 |       NULL |
| 2  | 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | fetchPhase     | {"id": "wW-FKHkISNetAuyi86G6lg", "name": "crate02"} | 1541408279532 |       NULL |
+----+--------------------------------------+----------------+-----------------------------------------------------+---------------+------------+
SELECT 2 rows in set (0.005 sec)
cr> select count(*) from ourdb.Table_C;
+----------+
| count(*) |
+----------+
|     1993 |
+----------+
SELECT 1 row in set (0.001 sec)
cr> kill '345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
KILL OK, 2 rows affected  (0.010 sec)
cr> select * from sys.jobs where id='345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| id                                   | node                                                |       started | stmt                        | username |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1541408279532 | select * from ourdb.Table_C | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr> kill '345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id='345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| id                                   | node                                                |       started | stmt                        | username |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1541408279532 | select * from ourdb.Table_C | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr> kill '345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
KILL OK, 0 rows affected  (0.001 sec)
cr> select * from sys.jobs where id='345e0404-bb64-4ad5-9ac1-8e4a8de7cfea';
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| id                                   | node                                                |       started | stmt                        | username |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
| 345e0404-bb64-4ad5-9ac1-8e4a8de7cfea | {"id": "I9k3mVUJQlSx-g49Fv4CzQ", "name": "crate01"} | 1541408279532 | select * from ourdb.Table_C | crate    |
+--------------------------------------+-----------------------------------------------------+---------------+-----------------------------+----------+
SELECT 1 row in set (0.002 sec)
cr>

~# dpkg -l crate | grep ^ii
ii  crate          3.1.2-1~jessie all          The fast, scalable, easy to use SQL database

URL jdbc:crate://10.9.100.61:5432/ourdb

**Comment by andreidan** [comment]
Thanks for the information. How did you get this job id "345e0404-bb64-4ad5-9ac1-8e4a8de7cfea"? Did you start crate, open your client (sqllite), connect to crate and then execute `select * from ourdb.Table_C` followed by `select * from sys.jobs` ? Or were there any other steps involved? 

Can you send me your `crate.yml` file at andrei [at] crate.io? (and if it doesn't contain any sensitive information your `data` folder?

**Comment by daniel11c** [comment]
Config file was sent via email.
The job id was found in sys.jobs after a couple of query runs via JDBC driver (not all queries fail - actually most of them works fine, but just now and then there are queries that fail)

**Comment by daniel11c** [comment]
I have just installed v3.1.3 (which includes fix for #7868 ) but issue is still here. I have zombie queries in sys.jobs and I cannot kill them.
