### ISSUE TITLE
multiple replicas export json file overwrite

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7822]
Export files to FTP
1.mount FTP to the server where each crate node is located, the export path is /data_export/ is derived.
curlftpfs -o codepage=utf8 ftp://user:passwd@ip:port /data_export/
2. execute export command
copy mytable  to /data_export/
if there is one replica of the table,it is very well.Perfect export!
And If there are multiple replicas of the table in the crate cluster, it is found in practice that the exported file will overwrite. (Although the result is right.)
Whether it can execute an export command to ensure that only one replica is exported, or add a parameter to the export command to control that only one replica is exported.
thanks.

**Comment by mfussenegger** [comment]
Which CrateDB version are you using?

We've made the `DIRECTORY` keyword in `COPY TO` mandatory to avoid such issues. In the past this wasn't caused by replicas (`COPY TO` only reads from primaries) but by different shards exporting to the same file.
