### ISSUE TITLE
bigdata table join poor performance

### ISSUE THREAD

**Issue by cmdares** [crate/crate#7830]
crate 3.1.2
32 nodes（16g sata 7200rpm per）
150million join 100million  calculate count.   80s.
how to tuning.
thanks.

**Comment by mfussenegger** [comment]
Could you please post your JOIN statement?

**Comment by cmdares** [comment]
SELECT COUNT(0) FROM T1 ---RESULT 100million ROWS.
SELECT COUNT(0) FROM T1 WHERE T1.FIELD1 = '12313123' ---RESULT 28 ROWS.

SELECT COUNT(0) FROM T1 ---RESULT 150million ROWS.
SELECT COUNT(0) FROM T2 WHERE T2.FIELD2 IN ('01','02','03')  ---RESULT 15million ROWS.

JOIN statement:
SELECT COUNT(0) FROM T1,T2 WHERE T1.FIELD1 = '12313' AND T2.FIELD2 IN ('01','02','03') AND T1.PK= T2.FK

T1:T2 data ratio  is  1:1.5
80~100S  so poor！

T1 and T2 table shard key use default ,not the join key.

**Comment by cmdares** [comment]
SELECT COUNT(0) FROM 
(SELECT PK FROM T1 WHERE FIELD1 = '12313123' )A,
(SELECT FK FROM T2 WHERE T2.FIELD2 IN ('01','02','03') )B
WHERE A.PK = B.FK

Similarly slowly

**Comment by mfussenegger** [comment]
Could you also post the output of `EXPLAIN <your-statements>` or post the table schema of your tables?
