### ISSUE TITLE
RFC: USR2 signal replacement for graceful shutdown.

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#7833]
Currently we're using `USR2` signals to trigger the decomissioning of a node.

Using signals has a couple of problems:

- Not supported on Windows
- The flight recorder uses the same signal, so trying to profile using the
  flight recorder causes a node to be decomissioned.
- Signal API has an unclear future. It's not yet marked for removal, but usage
  is not encouraged.
- IntelliJ doesn't include the `sun.misc.Signal` and `sun.misc.SignalHandler`
  packages if JDK9+ is used on the project.

We want to move along with Java developments, so sooner or later we'll likely
require JDK 11 (as it's the current LTS version). We'll also want to be able to
utilize developments from project Loom and Valhalla. That raises the question
of how to move along with the signal handling.

Some options that come to mind:

1) Expose the node decomissioning via SQL statements (E.g. `ALTER CLUSTER
DECOMMISSION <nodeId>`)

Being able to stop nodes via `SQL` may be a bit harsh. Especially for users of
the community edition which lacks user and privilege management.

An option to address that might be to "prepare a node for shutdown" via SQL,
and then have to manually stop CrateDB. That makes the workflow for users more
complicated. They'd have to check/wait for the decomissioning to be done. 

2) Expose the node decomissioning via JMX

Would require that people always setup JMX (which is recommended for production
deployments anyway). And they'd have to use jmx clients to trigger it.

3) Get rid of the decomissioning feature altogether

[![](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20SQL%20(full%20decommission))](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20SQL%20(full%20decommission)/vote)
[![](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20SQL%20(without%20node%20shutdown))](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20SQL%20(without%20node%20shutdown)/vote)
[![](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20JMX)](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Expose%20via%20JMX/vote)
[![](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Not%20using%20it%2C%20remove%20altogether)](https://api.gh-polls.com/poll/01CV4QAMEFGEVDBZ3Z9B7VK3CS/Not%20using%20it%2C%20remove%20altogether/vote)

**Comment by andreidan** [comment]
I'd like to possibly propose a 4th option where we'd ship a `stop` script (that can sit next to `bin/crate`) that'll trigger the decommissioning (over http, postgres wire protocol or whatever other mean to communicate with crate we choose) and stop the process when that's done. I think operational wise it'd be cool to have an easy way to automate and execute this operation (and both jmx and sql seem a bit hairy).

**Comment by seut** [comment]
@andreidan If the `stop` script you propose is using a public available API how would you prevent non-admin users from using it?

**Comment by andreidan** [comment]
@seut through the ACL mechanism we already have in place (host based auth, username/pass)

**Comment by seut** [comment]
@andreidan yep but privileges support is an enterprise feature, how would a community admin prevent that?

**Comment by andreidan** [comment]
@seut for community the api would be protected the same way the data is (via securing the cluster - vpc or whatnot)

**Comment by mfussenegger** [comment]
@andrei as I understand it 4th would be an extension to option 1) and 2), with the limitation that @seut raised: Privilege support is only available in enterprise.

We could combine 1) and 2) -> Make a node (not runtime) setting that specifies what should be done when the commissioning is done. 
This could be set to `nothing` or `shutdown` or something like that. Enterprise users would additionally have the privilege system, so the `alter cluster decomission ...` command would only be usable by super users.

**Comment by andreidan** [comment]
@mfussenegger but that still begs the question of how you trigger decommissioning (unless I'm missing something? or are we entertaining the idea of decommissioning being optional/an enterprise feature?)

**Comment by andreidan** [comment]
Thinking about this some more, maybe we're expanding the options field too much (let me know if this is not the right medium), but we would be talking about graceful shutdown-ing and decommissioning in production environments where I'd assume most people run crate as a service, or if not, if this sounds good, we can move into the direction of recommending that (and providing the necessary guidance in our documentation). That being said, graceful shutdown (ie decommission on shutdown) can be something as easy as handling `SIGTERM` which should be easily maintained cross-platform (by virtue of the JVM respecting it)

**Comment by mfussenegger** [comment]
Closing this. We implemented [ALTER CLUSTER DECOMMISSION <nodeId | nodeName>](https://github.com/crate/crate/pull/8163). 

If it turns out to be troublesome that it automatically shuts down a node we can later on add a setting to turn the auto-shutdown off.
