### ISSUE TITLE
SQLActionException[SQLParseException: Setting 'indices.store.throttle.type' is not supported]

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7869]
**CrateDB version**: 3.1.0

**Environment description**:centos6.5 64bit

**When I read the IMPORTING HUGE DATASETS INTO CRATEDB ¶, the contents of this chapter, I use the articles mentioned in "SET GLOBAL TRANSIENT indices. The store. The throttle. The type = 'none';", but an error: SQLActionException [SQLParseException: Setting 'indices. The store. The throttle. Type' is not supported], is this why?Is this setting invalid?**:

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
`indices.store.throttle.type` has been removed (I think in 3.0). Could you post the link to the article you're referring to so that we can update it accordingly?

**Comment by mfussenegger** [comment]
Thank you for the link. 
We're adding a note that the `store.throttle` settings only apply to versions < 30. ([PR](https://github.com/crate/guide/pull/111))

**Comment by gongweibiao1986** [comment]
thanks




| |
宫伟彪
邮箱：gongweibiao1986815@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 17:39, Mathias Fußenegger wrote:

Closed #7869.
