### ISSUE TITLE
Join query results are inconsistent

### ISSUE THREAD

**Issue by jqsl2012** [crate/crate#7870]
Found a bug: the same sql query results are inconsistent, this occasion happens! The frequency of occurrence is higher!

Environment: table refresh_interval=10, number_of_replicas=1

![image](https://user-images.githubusercontent.com/6802595/48185081-ef918800-e36e-11e8-8547-c13094da4e02.png)

After the environment changes to number_of_replicas=0, it does not appear

**Comment by seut** [comment]
Please be aware that CrateDB is eventually consistent, new writes will not be immediately available for queries.
Also please provide us the information we ask in our general template, like version, steps to reproduce etc.

**Comment by jqsl2012** [comment]
@seut Thank you.

crate version：crate-3.2.0-201809160202-a729590。

No new data is written during query.

**Comment by seut** [comment]
It would be great if you could provide us with most information possible.
As the template writes:
 - JVM version: java -version 
 - Kernel: uname -a
 - Distribution: cat /etc/os-release
 - Docker: docker \-\-version
 - Number of nodes; Please mention special master/data/client node configuration

**Comment by jqsl2012** [comment]
1. java version "1.8.0_151"
2. Linux nn01 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
3. No docker
4. Cluster of two nodes , execute sql query using crash


[crate@nn01 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

crate.yml add only ， others are default
network.bind_host: 172.18.18.30
network.publish_host: 172.18.18.30
network.host: 172.18.18.30

@seut

**Comment by seut** [comment]
@jqsl2012 Thanks for that information, we'll look into this asap.

**Comment by seut** [comment]
@jqsl2012 I'm not able to reproduce this issue. Could you please provide steps to reproduce?
Does this also happen if you just issue the `SELECT` you used for the insert?

**Comment by jqsl2012** [comment]
@seut  Sorry, business data is not available to you.

Complex join query will have the above problem

Tens of millions of data join hundreds of thousands of ， Is there a problem with query timeouts?

**Comment by seut** [comment]
I'm sorry but without any more information on how to reproduce, we're not able to help here.
