### ISSUE TITLE
When I use copy...When the form gets the data from the CSV file, if there is an error data in the CSV file, it will stop pulling the data.

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7882]
**Use case**:
When I use copy...When the form gets the data from the CSV file, if there is an error data in the CSV file, it will stop pulling the data.
**Feature description**:
 If this problem is encountered in other databases such as mysql, the error data will be written to the log file to help us solve the problem. Can this mechanism be adopted in crateDB?

**Comment by mfussenegger** [comment]
We've the [RETURN SUMMARY](https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-from.html?highlight=return%20summary#return-summary) option so that more information on what went wrong is returned.

**Comment by gongweibiao1986** [comment]
When the amount of data is small, reports will be generated. After the amount of data is about 100 million, no reports will be generated
