### ISSUE TITLE
3 billion, sid base 100 million or so Select sid,count(0) from table1 group by sid order by count(0)desc limit 10 The entire cluster gc is severe, the cluster is inaccessible, and other normal business statements are not executed.What's going on here?How do I optimize or fix this bug

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7883]
**CrateDB version**:

3.1.0
**Environment description**:
contos6.5 64bit 

**Problem description**:

3 billion, sid base 100 million or so
Select sid,count(0) from table1 group by sid order by count(0)desc limit 10
The entire cluster gc is severe, the cluster is inaccessible, and other normal business statements are not executed.What's going on here?How do I optimize or fix this bug

**Steps to reproduce**:

**Comment by robd003** [comment]
How much heap space (env CRATE_HEAP_SIZE) did you allocate for each node? How many nodes are you running? Can you do a "SHOW CREATE TABLE table1" and paste the results here?

**Comment by gongweibiao1986** [comment]
32nones，heap_size=16g for every node




| |
宫伟彪
邮箱：gongweibiao1986815@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 16:40, Robert Palmer wrote:

How much heap space (env CRATE_HEAP_SIZE) did you allocate for each node? How many nodes are you running? Can you do a "SHOW CREATE TABLE table1" and paste the results here?

**Comment by mfussenegger** [comment]
An option would be to try to *lower* the heap. For aggregations we utilize off-heap column-store oriented structures. So the heap needs only be large enough to hold the live-set in memory. A lower heap usually helps in reducing GC durations.

This doesn't seem like a bug, but rather looks like performance tuning. More support for that is available on different channels
