### ISSUE TITLE
Incompatible data type in conversion

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#7885]
**CrateDB version**:
Latest docker image

**Environment description**:

 - JVM version: java 8 
 - Kernel: Linux 4.15.0-36-generic #39-Ubuntu
 - Distribution: 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

 - Docker: Docker version 18.06.1-ce,
 - Number of nodes : 3

**Problem description**:

As mention in documentation CrateDB supports a set of numeric types: integer, long, short, double, float and byte. All types have the same ranges as corresponding Java types. You can insert any number for any type

**I am assuming its also support same data rage as java has.**  While inserting large value to the column which has DOUBLE data type its throw the exception but same value stored in java with double data types

**Steps to reproduce**:

1) Create table with double datatype coulmn
2) Insert 1844674407370955161 value

**Comment by mfussenegger** [comment]
Your example seems to work:

```
↪  crash
CONNECT OK
cr> create table t (x double);
CREATE OK, 1 row affected  (0.390 sec)
cr> insert into t (x) values (1844674407370955161);
INSERT OK, 1 row affected  (0.084 sec)
cr> select * from t;
+------------------------+
|                      x |
+------------------------+
| 1.8446744073709553e+18 |
+------------------------+
SELECT 1 row in set (0.049 sec)
cr>
```

Could you post more information on how to reproduce the problem?

**Comment by bhagujava** [comment]
@mfussenegger  Thanks for the quick reply.

Seems not working for me. This is how i have replicated.
1) create table 
CREATE TABLE IF NOT EXISTS statistic_data (
mac STRING,
interface STRING,
retries double);

2) Insert query 

INSERT INTO statistic_data  values('aa:bb:cc:dd','demo',1844674407370955161)

3) select * from statistic_data;

![demo](https://user-images.githubusercontent.com/25981184/48394149-64cad780-e738-11e8-93aa-923dafaf5af9.png)

You can see the warning. **Not sure whether its issue of dashboard while displaying the data in table**

**Comment by bhagujava** [comment]
@mfussenegger Got it, Its  Dashboard GUI issue while displaying data in table.

I have checked after installing crate shell and seems working properly.

Thanks.
