### ISSUE TITLE
HTTP Endpoint Inbuild Loadbalance 

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#7900]
**Use case**:
Just like JDBCtemplate provide in build load balance. It would be more powerful if crate has inbuild rest endpoint fail-over. 

**Feature description**:
Postgressql provide inbuilt capability for multiple node fail-over. The same way crate should have gateway which can handle the http endpoint request which can redirect based on round-robin (as default) algo.

so is there any plan for this ? or its already available ? Or its recommended to used LB server ?

**Comment by bhagujava** [comment]
Ok. Something like In-build Load balancer for crate-client. I have read the documentation where crate has mention one particular URL like http://crate01:4300/_sql?.

Now lets say i have 5 node running.

Now the issue is if suppose the **crate01** down for some reason then what happen ? I have to bring nginx or haproxy for this to manage. so instead of talking LB server into the picture is it possible to have in build load balancer which is contain getaway(virtual IP) which handle  the http endpoint request which can be redirect based on round-robin (as default) algo.

**Comment by mfussenegger** [comment]
Which client are you referring to? As I said, this is not something that can be done on the server side and most of our maintained clients include some form of fail over already.
