### ISSUE TITLE
Helm Chart for CrateDB

### ISSUE THREAD

**Issue by taliaga** [crate/crate#7904]
**Use case**:

I opened a PR to have a simple helm chart to ease installation of CrateDB in Kubernetes. 

Anyone interested in reviewing it? How about being listed as main or co-maintainers?

See https://github.com/helm/charts/pull/8432.

**Comment by mfussenegger** [comment]
Thanks for bringing this up. I'll forward this to our Kubernetes people and ask them to have a look at it.

**Comment by autophagy** [comment]
@taliaga Thank you so much for writing this! I've left a couple of comments and suggestions on the PR, based on our experiences with running CrateDB in Kubernetes. I hope they prove helpful.

**Comment by taliaga** [comment]
Thank you @autophagy for your comments! With luck I'll be able to get back to it in a week, but for sure I'll include your suggestions.

**Comment by mfussenegger** [comment]
Going to close this since further discussion can happen in the PR in the helm charts repo.

**Comment by OJFord** [comment]
@autophagy @mfussenegger Could I draw your attention to helm/charts#16318?

The above mentioned PR was closed due to inactivity, but I opened another with Taliaga's commits and bumped the version to v4.

**Comment by chaudum** [comment]
@OJFord I left a few comments on your PR to the Helm charts repo. Please feel free to ask more questions there if you need more help!
