### ISSUE TITLE
There can be only indexes without store in elasticsearch. Can crateDB achieve the same function?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7908]
**CrateDB **:

3.1.0
**Environment description**:
centos6.5 64bit

**Problem description**:
There can be only indexes without store in elasticsearch. Can crateDB achieve the same function?

**Steps to reproduce**:

**Comment by seut** [comment]
Yes, see https://crate.io/docs/crate/reference/en/latest/general/ddl/fulltext-indices.html#disable-indexing.
