### ISSUE TITLE
Allow renaming of tables.

### ISSUE THREAD

**Issue by jeffnappi** [crate/crate#792]
The ability to rename tables can make it easier to handle schema changes, restores from backup, etc.

Would be nice to have the same syntax as Postgres:

```
ALTER TABLE table_name RENAME TO new_name
```
##

**Comment by Autophagy** [comment]
Hi @jeffnappi - We've merged support for renaming tables and partition tables as part of #5574, and it will now part of our 2.0 release!

**Comment by jeffnappi** [comment]
Hi @Autophagy that's great! Thanks :+1:

**Comment by seut** [comment]
@jeffnappi we finally could take care of that feature, and implemented it with the recently released 2.0 release. thx for being patient, happy renaming :)
