### ISSUE TITLE
Crate in Docker does not work

### ISSUE THREAD

**Issue by philippos-isaia** [crate/crate#7922]
**CrateDB version**: 3.1.2

**Environment description**: Ubuntu 18.04.1 using Docker

 - JVM version: 1.8.0_191
 - Kernel: Linux 4.15.0-29-generic
 - Distribution: Ubuntu 18.04.1 LTS
 - Docker: 18.09.0 build 4d60db4

**Problem description**:

crate does not work when using docker.  Cannot access it either using commands or even on the web browser using the localhost:4201

I am using `sudo docker network create crate` which works because the result of the command `sudo docker network ls` give
```
NETWORK ID          NAME                DRIVER              SCOPE
34cbc4b7b1bc        bridge              bridge              local
630b802ef3d1        crate               bridge              local
5bd9f212f4c3        host                host                local
2c63202ab0ea        none                null                local
```

Then I run the command 
```
sudo docker run -d --name=crate01 \
      --net=crate -p 4201:4200 --env CRATE_HEAP_SIZE=2g \
      crate -Cnetwork.host=_site_
```

This also works, and the `sudo docker ps` command gives the following output in the first seconds
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS                                        NAMES
e89574eeefcf        crate               "/docker-entrypoint.…"   4 seconds ago       Up 2 seconds (health: starting)   4300/tcp, 5432/tcp, 0.0.0.0:4201->4200/tcp   crate01

```

But I cannot access docker through `http://localhost:4201/`, it says unable to connect.
Also if I re-run the `sudo docker ps` command after 20-30 seconds the output becomes
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by mfussenegger** [comment]
Do you have some logs? It looks like the process dies for some reason
