### ISSUE TITLE
gc

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7961]
Cluster information
Cluster version: 3.1.0
Cluster size: 8 servers, 128g memory per server, 4 nodes per server, 32 nodes in total
Problems encountered:
Using regexp_replace to replace '\r\n 'in the string field of the table, the size of the table is 200g, with 400 million pieces of data, the task will run for a period of time and there will be gc exception (at this time only the current task is executing), how can I configure to solve this problem, or can you help me provide better advice to deal with this problem

**Comment by gongweibiao1986** [comment]
16G per node
the table have 32 shards，every node has one

**Comment by mfussenegger** [comment]
Please also answer the second question.
