### ISSUE TITLE
Comment is not supported with crateDB. Do you support it?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7975]
**Use case**:

**Feature description**:
Comment is not supported with crateDB.
Do you support it?

**Comment by seut** [comment]
We do support comments in SQL statements, see also https://github.com/crate/crate/blob/master/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java#L50.
Can you please describe what your issue is?

**Comment by gongweibiao1986** [comment]
The syntax I want is something like oracle comment on,
Do we have support at the moment?

**Comment by cmdares** [comment]
+1
support! Grammatically consistent with PostgreSQL.
comment on column user.userid is 'The user ID';

**Comment by mfussenegger** [comment]
We appreciate your feedback, but if you want us to add features it would be great if we wouldn't have to pull out information from you. We've an issue template for feature requests, please fill them out accordingly.
