### ISSUE TITLE
The cluster cannot be restored to green health

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#7989]
**CrateDB version**:
3.1.0
**Environment description**:
centos 6.5 64 bit
32nodes

My cluster has 8 servers, each server has 128g of memory, 40 core CPU, each server has 4 nodes, now has 200 tables, when I restart the cluster, I have 50% of the tables only returned to the yellow state, did not return to the green health state, how do I deal with this situation?Can you give me some advice?

**Steps to reproduce**:

**Comment by robd003** [comment]
Could you run the query "select * from sys.shards" and paste the results here?

**Comment by mfussenegger** [comment]
The information from [sys.allocations](https://crate.io/docs/crate/reference/en/latest/admin/system-information.html?highlight=sys%20allocations#allocations) should also help in figuring on why shards are not being allocated. 

Could you post the output here?
