### ISSUE TITLE
When I create a table and set replicas to 1, and then I change 1 to 0 again, does the replicas get deleted?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8002]
**CrateDB version**:
3.1.0
**Environment description**:
centos6.5 64bit
Eight servers, each with 128 gigabytes of memory
Each server has four nodes installed, and the JVM heap for each node is 16g

**Problem description**:
When I create a table and set replicas to 1, and then I change 1 to 0 again, does the replicas get deleted?

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
Yes the replica gets deleted
