### ISSUE TITLE
ECS Task IAM profile credentials ignored in repository-s3 plugin

### ISSUE THREAD

**Issue by jeffnappi** [crate/crate#8005]
ECS Task IAM roles do not currently work in CrateDB 3.1.3. 

This has been fixed upstream in Elastic:
https://github.com/elastic/elasticsearch/pull/31864

**Comment by mfussenegger** [comment]
Thank you for pointing this out, we'll have a look at it.

**Comment by seut** [comment]
@jeffnappi We've included this fix on our 3.1 branch, will be released with the next 3.1 hotfix release. Thanks for reporting!

**Comment by jeffnappi** [comment]
Thanks for the quick fix!
