### ISSUE TITLE
install.crate.io not working for centos

### ISSUE THREAD

**Issue by protosam** [crate/crate#8006]
I'm not 100% sure where to put this issue. Please point me in the right direction if this is not the best place.

When following the getting started guide for installing cratedb on linux from here:
https://crate.io/docs/crate/getting-started/en/latest/install-run/special/linux.html

Upon running:
```
# bash -c "$(curl -L install.crate.io)"
```

You'll receive this error on CentOS systems:
```
Your OS or distribution centos is not supported by this install script.
Please visit

    https://crate.io/docs/

For help.
```

CentOS should be completely RedHat Enterprise Linux compatible. This should be possible to resolve by modifying this line in the bash script:
```
if [ "$OS" = "redhat" ] || [ "$OS" = "amazon" ] || [ "$OS" = "amzn" ];
```
To:
```
if [ "$OS" = "redhat" ] || [ "$OS" = "amazon" ] || [ "$OS" = "amzn" ] || [ "$OS" = "centos" ];
```

I was able to successfully run the installer script after this change and begin using this on CentOS 7.

Is it possible to get this change made to the downloaded script?

**Comment by mfussenegger** [comment]
The script is in https://github.com/crate/crate-utils/blob/master/easy/install.sh  - maybe you could make a PR against that repo?

**Comment by robd003** [comment]
https://github.com/crate/crate-utils/pull/42

**Comment by seut** [comment]
The suggested fix is now merged into https://github.com/crate/crate-utils, thanks @robd003.
