### ISSUE TITLE
support common window function for statistical analysis

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8013]
window statement support:    over partition by order by 

sliding  statement  support:
rows between unbounded preceding and unbounded following
rows between unbounded preceding and current row
rows between 1 preceding and unbounded following
rows between 1 preceding and 1 following
rows between current row and unbounded following
rows between current row and 1 following
range between interval '3' day preceding and interval '3' day following

agg statement support:   sum|max|min|avg|row_number|rank|dense_rank|lag|lead

e.g.
select 
field1,field2,field3,field4,
sum|max|min|avg(field1) over (partition by field2,field3 order by field4)fx1,
row_number()|rank()|dense_rank()over (partition by field2,field3 order by field4)fx2,
lag(field2,1,0)|lead(field2,1,0)over(partition by field2,field3 order by field4 desc)fx3
from table1 where 1=1 and ....

**Comment by asdf2014** [comment]
Hi, @cmdares @seut . Is there any new progress to update?

**Comment by seut** [comment]
@asdf2014 @cmdares 
We've implemented general window function support with CrateDB 4.0, see https://crate.io/docs/crate/reference/en/4.0/general/builtins/window-functions.html.

With the next 4.1 release we'll also release more advanced window definitions like `rows` and `offset preceding` and additional window functions like `lead` and `lag`.
See https://crate.io/docs/crate/reference/en/latest/general/builtins/window-functions.html.

So from the list of features pasted above, at today, following are not implemented yet:
- interval support for window definition (e.g. `'3 day'::interval preceding`)
- rank()
- dense_rank() 

We plan to implemented these missing features as well at some point but we cannot make any estimate. As always, any contributions are more than welcome :-)

**Comment by mfussenegger** [comment]
Created two dedicated issues for the two missing functions mentioned here:

- [rank](https://github.com/crate/crate/issues/10507)
- [dense_rank](https://github.com/crate/crate/issues/10508)
