### ISSUE TITLE
java 11 and zgc

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8032]
Whether cratedb supports Java 11 and ZGC to improve the efficiency of GC or not, at present, the amount of cluster data is large and the GC time is long. I wonder if it is feasible to improve the performance through zgc.

**Comment by mfussenegger** [comment]
We are keeping an eye on GC developments, but so far haven't done any testing with ZGC and we're not supporting it officially.
Note that ZGC is still experimental in Java 11 and it usually takes a while to iron out all bugs. For example for G1GC there have been bugs up to Java9 that could lead to index corruption with Lucene.

In case you decide to evaluate it on a test environment or something - we'd be curious to hear back on your experiences.

**Comment by mfussenegger** [comment]
Closing this for now as we don't have any plans to look into zgc as long as it is marked as experimental.

Note though that 3.2 supports java 11 and that you might already see improvements using G1GC instead of ConcMarkSweepGC
