### ISSUE TITLE
copy to flush disk

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8034]
crate/sql/src/main/java/io/crate/execution/engine/export/FileWriterCountCollector.java  

@Override
        @SuppressWarnings("unchecked")
        public void write(Row row) {
            for (CollectExpression<Row, ?> collectExpression : collectExpressions) {
                collectExpression.setNextRow(row);
            }
            Map doc = (Map) row.get(0);
            XContentHelper.update(doc, overwrites, false);
            try {
                builder.map(doc);
                builder.flush();			--------------------------------------------------------------？In doubt

                outputStream.write(NEW_LINE);
            } catch (IOException e) {
                throw new UnhandledServerException("Failed to write row to output", e);
            }
        }

-----？In doubt-------
Do you need to flush every row(record) to disk after writing? Can you consider using a buffer to wait for the buffer to be full for disk writing? At present, it is found that when executing the command of exporting larger table to files, the server writes to disk simultaneously because of more fragments and multiple threads. The operating system often finds the state of being stuck and considers whether it can be optimized.

**Comment by seut** [comment]
@cmdares Can you please elaborate a bit more what stuck state your OS is running into? Buffering the output stream is a valid option but without any buffer the system should not get stuck either.

**Comment by seut** [comment]
@cmdares We've implemented a buffer for the output streams of `COPY TO` as suggested, see https://github.com/crate/crate/pull/8054 for details. It will be released with the next feature release. Thanks for the suggestion.
