### ISSUE TITLE
Stress test the crateDB cluster using HTTP and JDBC There is a large difference in response speed between the two, with JDBC's response time approximately HTTP Ten times the way. Why is that?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8035]
**CrateDB version**:
3.1.0

**Environment description**:

Stress test the crateDB cluster using HTTP and JDBC
There is a large difference in response speed between the two, with JDBC's response time approximately HTTP
Ten times the way. Why is that?

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
We'll need more information to have any clue what's going on.
Please describe exactly how you're running your stress tests and how you take measurements.
