### ISSUE TITLE
Use the copy...The to...Where statement, when exporting data, the exported data is empty, When you do a query using the same where condition, you can look up the data. May I ask what caused this problem?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8036]
**CrateDB version**:

3.1.0
**Environment description**:

Use the copy...The to...Where statement, when exporting data, the exported data is empty,
When you do a query using the same where condition, you can look up the data.
May I ask what caused this problem?

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
Could you please provide some reproduction steps so we have something to start looking into this?

**Comment by gongweibiao1986** [comment]
This is my construction sentence:
CREATE TABLE IF NOT EXISTS "doc"."test" (
   
)
CLUSTERED BY ("asjbh") INTO  64  SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)  

This table has 15 billion data points,primary key is asjbh

**Comment by seut** [comment]
@gongweibiao1986 The column definitions are missing from your supplied table creation statement, could you please add them? Can you also provide us the `COPY TO` and the query which succeeds please?
