### ISSUE TITLE
create table my_table_arrays (      tags array(string) ); insert into my_table_arrays(tags) values(['1000','2000','3000']); insert into my_table_arrays(tags) values(['1000','3000','4000']); select tags,count(0)c from my_table_arrays where '1000'=any(tags) group by tags --- tags,c ------- 1000,2 2000,1 3000,1 4000,1

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8091]
**Use case**:

**Feature description**:
Hopefully, this syntax will be supported in a future release
create table my_table_arrays (
     tags array(string)
);
insert into my_table_arrays(tags) values(['1000','2000','3000']);
insert into my_table_arrays(tags) values(['1000','3000','4000']);
select tags,count(0)c from my_table_arrays where '1000'=any(tags) group by tags
---
tags,c
-------
1000,2
2000,1
3000,1
4000,1

**Comment by mfussenegger** [comment]
If I'm understanding your use-case correctly you can use `unnest` for this. 

```
select tag, count(*) from 
    (select unnest(tags) tag from my_table_arrays where '1000' = any(tags)) t 
group by tag;
+------+----------+
| tag  | count(*) |
+------+----------+
| 1000 |        2 |
| 2000 |        2 |
| 3000 |        2 |
+------+----------+
```

(Requires `3.2.x`, which is not in the stable release-channels yet)

Or am I missing something?

**Comment by cmdares** [comment]
is ok！grate！
by the way，how about the performance in the bigdata？on mytest table 1b rows，3 datanode（8c 16g） result：30s. it is too slowly.

**Comment by mfussenegger** [comment]
> how about the performance in the bigdata

Could you post the output of `EXPLAIN yourquery` and `EXPLAIN ANALYZE yourquery` so that we can have a closer look?
