### ISSUE TITLE
NullPointerException when doing LEFT OUTER JOIN

### ISSUE THREAD

**Issue by robd003** [crate/crate#8103]
**CrateDB version**: 3.2.0

**Environment description**:

java version "1.8.0_181" Oracle Corporation OpenJDK 64-Bit Server VM (build 25.181-b13)
Using the docker image crate/crate:3.2.0
Docker version: 18.09.1, build 4c52b90

**Problem description**:

When trying to do a LEFT OUTER JOIN I get a NullPointerException:

SQLActionException[NullPointerException in io.crate.expression.symbol.SymbolVisitor.process(SymbolVisitor.java:32)]

Might be related to this prior bug fix: https://github.com/crate/crate/issues/6478

**Steps to reproduce**:

 SELECT 
        n.title, 
        n.blog_url, 
        CASE 
            WHEN e.event_type = 'alexaplay' THEN 'smart_speaker' 
            WHEN e.event_type = 'podcastplay' THEN 'podcast' 
            WHEN e.event_type = 'podcastplay' THEN 'podcast' 
            WHEN (e.event_type = 'play' AND e.library_type IS NULL) THEN 'embeddable' 
            WHEN (e.event_type = 'play' AND e.library_type IS NOT NULL) THEN 'library' 
        END AS "player_type" 
        FROM voxsnap.narrations n
        LEFT OUTER JOIN voxsnap.events_2018 e ON (n.id = e.narration) 
        WHERE (
            e.event_type = 'play' OR 
            e.event_type = 'alexaplay' 
            OR e.event_type = 'podcastplay');

+------------------------------------------------------+
| SHOW CREATE TABLE voxsnap.events_2018                |
+------------------------------------------------------+
CREATE TABLE IF NOT EXISTS "voxsnap"."events_2018" (
   "audio_time" FLOAT,
   "browser" STRING,
   "build_num" INTEGER,
   "customer" STRING,
   "delta_time" LONG,
   "device" STRING,
   "event_name" STRING,
   "event_time" TIMESTAMP,
   "event_type" STRING,
   "ip_addr" IP,
   "library_genre" STRING,
   "library_type" STRING,
   "location" GEO_POINT,
   "location_city" STRING,
   "location_country" STRING,
   "location_state" STRING,
   "narration" INTEGER,
   "os" STRING,
   "pin" ARRAY(FLOAT),
   "play_ranges" ARRAY(FLOAT),
   "playlist" INTEGER,
   "referrer" STRING,
   "seek_from" FLOAT,
   "session_id" STRING,
   "share_type" STRING,
   "tot_play_time" INTEGER,
   "user_id" STRING
)
CLUSTERED INTO 8 SHARDS
WITH (
   column_policy = 'dynamic',
   number_of_replicas = '0-1',
   refresh_interval = 30000,
   "write.wait_for_active_shards" = 'ALL'
)

+-----------------------------------------------------+
| SHOW CREATE TABLE voxsnap.narrations                |
+-----------------------------------------------------+
CREATE TABLE IF NOT EXISTS "voxsnap"."narrations" (
   "audio_length" STRING,
   "audio_url" STRING,
   "blog_url" STRING,
   "content" STRING INDEX USING FULLTEXT WITH (
      analyzer = 'english'
   ),
   "created" STRING,
   "customer_id" INTEGER,
   "description" STRING,
   "expiry_date" STRING,
   "featured_image" STRING,
   "gen_description" BOOLEAN,
   "id" INTEGER,
   "in_sitemap" BOOLEAN,
   "keywords_string" STRING,
   "meta_title" STRING,
   "narrator_id" INTEGER,
   "notes" STRING,
   "preferred_gender" STRING,
   "public_library" BOOLEAN,
   "publish_date" STRING,
   "short_url" STRING,
   "site_id" INTEGER,
   "slug" STRING,
   "status" INTEGER,
   "title" STRING,
   "updated" STRING,
   "uuid" STRING
)
CLUSTERED INTO 4 SHARDS
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-1',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'ALL'
)

**Comment by robd003** [comment]
If you need sample data what's the best way to provide it? Snapshot? .sql file with a few inserts?

**Comment by seut** [comment]
@robd003 Thanks for reporting, we'll looking into this. It would be very helpful if you could provide exact steps (minimum data set which leads to this error) to reproduce this and maybe a complete stacktrace of the error.

**Comment by robd003** [comment]
Also interesting, if I don't specify fields in the SELECT statement it works.

SELECT *, CASE WHEN ... works

**Comment by robd003** [comment]
@seut https://github.com/crate/crate/issues/8103#issuecomment-454289560

This is the entirety of the output from crash. The crate daemon doesn't log anything.

cr> SELECT n.title, n.blog_url,
        CASE 
            WHEN e.event_type = 'alexaplay' THEN 'smart_speaker' 
            WHEN e.event_type = 'podcastplay' THEN 'podcast' 
            WHEN e.event_type = 'podcastplay' THEN 'podcast' 
            WHEN (e.event_type = 'play' AND e.library_type IS NULL) THEN 'embeddable' 
            WHEN (e.event_type = 'play' AND e.library_type IS NOT NULL) THEN 'library' 
        ELSE '' END AS "player_type"
        FROM voxsnap.narrations n
        LEFT OUTER JOIN voxsnap.events_2018 e ON (n.id = e.narration) 
        WHERE (
            e.event_type = 'play' OR 
            e.event_type = 'alexaplay' 
            OR e.event_type = 'podcastplay');
SQLActionException[NullPointerException in io.crate.expression.symbol.SymbolVisitor.process(SymbolVisitor.java:32)]

**Comment by seut** [comment]
@robd003 If you pass `-v` (or `--verbose`)  as an arg to the `crash` cmd, you should get a stacktrace.

**Comment by seut** [comment]
@robd003 Great, thx.

**Comment by robd003** [comment]
@seut What's the best way to send you guys the data set? Snapshot on a public S3 bucket?

**Comment by seut** [comment]
@robd003 Yes our just exported via `COPY TO`. At best, the data set only contains the minimum data to reproduce this issue. E.g. it may already happen with only 1 row on each table.

**Comment by seut** [comment]
@robd003 I can reproduce this issue even without any data, so nothing is needed from your side. Thanks for the detailed information, we'll come up with a fix asap.

**Comment by robd003** [comment]
Thanks for jumping on this @seut

**Comment by seut** [comment]
@robd003 We've fixed this by https://github.com/crate/crate/pull/8104. It will be released with the next hotfix releases. Thanks again for reporting.
Btw. as you may already noticed, your query could be rewritten to an inner join which would not run into an error.
