### ISSUE TITLE
What is the default Admin UI login username and password?

### ISSUE THREAD

**Issue by aaamitsingh** [crate/crate#8107]
After installation when I'm trying to open the AdminUI page there a popup box is asking for the username and password, is there any default login password?

**Comment by mfussenegger** [comment]
With the default configuration included in the tarball you shouldn't receive a popup unless you're accessing the admin-ui from another host.

See the [Host based authentication](https://crate.io/docs/crate/reference/en/latest/admin/auth/hba.html) is enabled. It needs to be configured to suit your needs. 

By default there is a `crate` super-user (no password, connections are only allowed from the same host). This can be used to create other users with password.
