### ISSUE TITLE
For a table of 1.4 billion data, do a field update operation, resulting in the node memory resources insufficient downtime, how to solve this problem?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8114]
**CrateDB version**:
3.1.0

**Environment description**:
8 servers, the memory size of each server is 128g, four nodes are built on each server, and the crate_heap_size allocated by each node is 16g

**Problem description**:
For a table of 1.4 billion data, do a field update operation, resulting in the node memory resources insufficient downtime, how to solve this problem?

-->

**Steps to reproduce**:

**Comment by seut** [comment]
@gongweibiao1986 Can you please add some hints to reproduce (e.g. update query you're using, table schema)? What do you mean by "*resulting in the node memory resources insufficient downtime*", the node crashes?
Could you maybe provide us a stacktrace when this the incident happens?

**Comment by gongweibiao1986** [comment]
yes,Node crashes
