### ISSUE TITLE
Whether dynamic columns can specify a word splitter

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8115]
**Use case**:
User behavior analysis table, will be in later use, increase the different behavior column, in the dynamic increase column
**Feature description**:
Whether dynamic columns can specify a word splitter
dynamic columns can specify a word splitter

**Comment by joemoe** [comment]
what would you want to do with a word splitter? can you provide an example?
there are already some features included.
see 
https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#string-functions
https://crate.io/docs/crate/reference/en/latest/general/ddl/analyzers.html

**Comment by gongweibiao1986** [comment]
I want to use the Chinese word splitter to query the behavioral population with the same keyword and do statistical sampling

**Comment by joemoe** [comment]
we support the chinese language in the analyzer: 
https://crate.io/docs/crate/reference/en/latest/general/ddl/analyzers.html#language

**Comment by mfussenegger** [comment]
@gongweibiao1986 did our [docs](https://crate.io/docs/crate/reference/en/latest/general/ddl/analyzers.html#language) answer your question or could you explain your requirement further if not?
