### ISSUE TITLE
User profile table, with 200 columns, upsert data using spark concurrency, please advise if the scheme is feasible?What's the catch?

### ISSUE THREAD

**Issue by gongweibiao1986** [crate/crate#8116]
**Use case**:
User profile table, with 200 columns, upsert data using spark concurrency, please advise if the scheme is feasible?What's the catch?
**Feature description**:

**Comment by joemoe** [comment]
hi @gongweibiao1986, 200 columns shouldn't be a problem.
for more detailed support on schema setup please refer to our paid offerings. https://crate.io/pricing/
