### ISSUE TITLE
UPSERT INTO 

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8151]
support  "UPSERT INTO "

UPSERT INTO employee (emp_id, lastname, firstname, title, department) 
VALUES (145303, 'Public', 'Jane', 'Manager', 'HR'),(145303, 'Public', 'Jane', 'Manager', 'HR')

UPSERT INTO employee (emp_id, lastname, firstname, title, department) 
SELECT emp_id, lastname, firstname, title, department FROM employee2

ref:
https://docs.voltdb.com/UsingVoltDB/sqlref_upsert.php
http://phoenix.apache.org/language/index.html#upsert_values

**Comment by mfussenegger** [comment]
We support [ON CONFLICT DO UPDATE SET](https://crate.io/docs/crate/reference/en/latest/sql/statements/insert.html?highlight=duplicate#on-conflict-do-update-set) which can be used to do upserts and don't have any plans to support additional syntax for it.
