### ISSUE TITLE
NPE in unnest function

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8177]
**CrateDB version**:
3.2.1

**Environment description**:
openjdk version "1.8.0_181"
4.4.0-133-generic #159-Ubuntu x86_64
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

**Problem description**:
NPE raised when selecting data from table with NULL-able array column.

`SQLActionException[NullPointerException in io.crate.expression.tablefunctions.UnnestFunction.maxLength(UnnestFunction.java:190)]`

**Steps to reproduce**:
*Example №1:*
`SELECT UNNEST(NULL);`

*Example №2:*
`create table test(x array(int));`
`insert into test (x) values ([1,2,3]);`
`insert into test (x) values (null);`
`select unnest(x) from test;`

**Comment by mfussenegger** [comment]
Thank you for the bug report, we'll have a fix for this in the next 3.2 release
