### ISSUE TITLE
Potential slowdown with multiple snapshots

### ISSUE THREAD

**Issue by bputt** [crate/crate#8191]
**CrateDB version**: 3.1.1

**Environment description**:
Java 1.8
Centos 7.6
3 master nodes, 2 query nodes, 2 ingest nodes, and a decent number of data nodes

**Problem description**:
We're backing up data once a day using the snapshot feature and ever since enabling snapshots, we've noticed our query times taking longer than usual. Also noticing the following query take considerably longer each day we run it: ```SELECT state from sys.snapshots where name = ? and repository = ? limit 1```

We're submitting this ticket to see if there's anything obvious that points out to you for whether or not this makes sense.

**Steps to reproduce**:
Have a script that produces a daily snapshot

```
TIMESTAMP=$(date +%s+%3N)

CREATE SNAPSHOT mydb.backup_$TIMESTAMP ALL
```

**Comment by mfussenegger** [comment]
1) Does the query performance degrate during the time the snapshot is being created, or also keep being degraded afterwards?

2) Where do you store the snapshots, S3?

3) Do you notice a speed difference between `select count(*) from sys.snapshots` and `SELECT state from sys.snapshots where name = ? and repository = ? limit 1` ? We made a [change](https://github.com/crate/crate/commit/6b7383041) in 3.2.0 that might improve the performance of your query, but the worst case would still equal the `select count(*).. ` variant.

**Comment by bputt** [comment]
@mfussenegger thanks for getting back

1. The performance is degraded during and after the snapshot. Queries are noticeably slower since we began enabling snapshots.

2. S3

3. No, there isn't a speed difference (took 45s to run the count(*) statement)

**Comment by mfussenegger** [comment]
Thank you for the answers.

One more question: How many snapshots do you currently have?

**Comment by mfussenegger** [comment]
Didn't have the time to look into this yet too closely. But one aspect that I could imagine affecting the performance for a bit longer is that the snapshot process requires disk accessed which compete with the file system cache for the regular queries. It might take a bit until the query related parts are back in the fs cache.

Can you observe that the performance eventually improves again after taking a snapshot?
