### ISSUE TITLE
SQLActionException[RelationUnknown: Relation 'emp_table' unknown]

### ISSUE THREAD

**Issue by ashutoshkr9329** [crate/crate#8243]
copy emp_table from 'file:/Users/akumar43/setup/repo/dashboardmonitoring/flask/webapp/samplesdb/employee.json';

SQLActionException[RelationUnknown: Relation 'emp_table' unknown]
Getting the following error and i also saw case#6716 but its not working

**Comment by mfussenegger** [comment]
Did you create the table up-front? 

Please fill out the information we request in our issue template:

```
CrateDB version:

Environment description:

Problem description:

Steps to reproduce:
```

**Comment by ashutoshkr9329** [comment]
So for importing dataset also shown in the following link https://crate.io/docs/crate/reference/en/latest/general/dml.html#importing-data
I have to create a table beforehand?

**Comment by ashutoshkr9329** [comment]
ok that helped a lot.
Thank you for the hint.You can close the case
