### ISSUE TITLE
poor performance in upsert select

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8251]
8 server  2 nodes/per server   16 nodes in total.
server:centos7 x64 jdk 1.8  32C 128G 8T(HDD)
node config: heap 30G
sql:
insert into tbl
select ID,c1,c2,c3..c10 from temp_etl_tbl
on conflict(ID)
do update
set
c1=excluded.c1,
c2=excluded.c2,
c3=excluded.c3;
..
c10=excluded.c3;

tbl 1billion 32shards wiht "ID" hash
temp_etl_tbl 2billion 32shards wiht "ID" hash
run one hour and server "top" is very high and centos stuck.
Repeated execution several times, all the same. and this requirement is almost impossible to accomplish.
This performance issue needs to be evaluated and optimized within the official community.
thanks!

**Comment by bputt** [comment]
You should check iostat to see if your I/O bound which means your disks aren't fast enough for the number of CPUs to be able to do anything effectively

**Comment by gongweibiao1986** [comment]
You mean a normal HDD drive can't do this, can it?

**Comment by mfussenegger** [comment]
> You mean a normal HDD drive can't do this, can it?

Write latency is usually bound by the speed of the underlying disks. So yes switching to SSDs will improve things.

**Comment by mfussenegger** [comment]
We've some other issues that track things we can do to improve performance, like https://github.com/crate/crate/issues/9810 so I'm closing this here
