### ISSUE TITLE
Stable packages for debian (apt) are not built together with other packages

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#8257]
**CrateDB version**:
From time to time (right now 3.1.6 and 3.2.3)

**Environment description**:
Debian (ALL)

**Problem description**:
Some package versions are missing from https://cdn.crate.io/downloads/apt/stable/pool/main/c/crate/ (but they are built for Ubuntu or Centos/RHEL)

**Steps to reproduce**:
curl https://cdn.crate.io/downloads/apt/stable/pool/main/c/crate/
(v3.1.6 or v3.2.3 are missing)

**Comment by mfussenegger** [comment]
Thank you for pointing out.
We dropped support for some of the older distributions and this caused our publish step to break.

crate_3.2.3-1~stretch_all.deb is now there.
