### ISSUE TITLE
Query with multiple joins returns different results based on number of nodes

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#8267]
**CrateDB version**:
3.1.3

**Environment description**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
Linux demo-crate01 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

1 node or 3 nodes

**Problem description**:
Query with multiple joins is not consistent over the same data (no insert/updates are performed).

**Steps to reproduce**:
3 nodes cluster, same data:
SELECT company1_.id AS company_id, dossiermod2_.id AS dossier_id, assetmodel0_.id AS asset_id,assetmodel0_.archived FROM db.asset assetmodel0_ LEFT JOIN db.company company1_ ON assetmodel0_.company_id=company1_.id LEFT JOIN db.dossier dossiermod2_ ON assetmodel0_.id=dossiermod2_.asset_id WHERE (assetmodel0_.id='68d35eaa-7970-41d4-9be9-04bfc7a432b6' AND assetmodel0_.archived IS NULL);
returns proper result (1 row)

3 nodes cluster, same data:
SELECT company1_.id AS company_id, dossiermod2_.id AS dossier_id, assetmodel0_.id AS asset_id,assetmodel0_.archived FROM db.asset assetmodel0_ LEFT JOIN db.company company1_ ON assetmodel0_.company_id=company1_.id INNER JOIN db.dossier dossiermod2_ ON assetmodel0_.id=dossiermod2_.asset_id WHERE (assetmodel0_.id='68d35eaa-7970-41d4-9be9-04bfc7a432b6' AND assetmodel0_.archived IS NULL);
returns proper result (1 row)

1 node cluster, same data:
SELECT company1_.id AS company_id, dossiermod2_.id AS dossier_id, assetmodel0_.id AS asset_id,assetmodel0_.archived FROM db.asset assetmodel0_ LEFT JOIN db.company company1_ ON assetmodel0_.company_id=company1_.id LEFT JOIN db.dossier dossiermod2_ ON assetmodel0_.id=dossiermod2_.asset_id WHERE (assetmodel0_.id='68d35eaa-7970-41d4-9be9-04bfc7a432b6' AND assetmodel0_.archived IS NULL);
returns wrong result (number of rows equals number of entries in db.asset)

1 node cluster, same data:
SELECT company1_.id AS company_id, dossiermod2_.id AS dossier_id, assetmodel0_.id AS asset_id,assetmodel0_.archived FROM db.asset assetmodel0_ LEFT JOIN db.company company1_ ON assetmodel0_.company_id=company1_.id INNER JOIN db.dossier dossiermod2_ ON assetmodel0_.id=dossiermod2_.asset_id WHERE (assetmodel0_.id='68d35eaa-7970-41d4-9be9-04bfc7a432b6' AND assetmodel0_.archived IS NULL);
returns proper result (1 row)

Every time the cluster was started with no data, big sql applied to populate the cluster, wait some time and then try the query. No data was migrated from 1 node to 3 nodes cluster or back.
Some times restarting the service will temporary fix (from max 30 minutes) issues when crate is running as single node.

**Comment by mkleen** [comment]
I didn't manage to reproduce it. Do you think you could provide a testdata set ?
