### ISSUE TITLE
Duplicate results to query because of replication

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#8277]
**CrateDB version**:
v 3.1.3

**Environment description**:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
Linux crate01 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Problem description**:
In very rare cases crate returns duplicate responses (we suppose this is because of replication)

**Steps to reproduce**:
cr> select id, username from db.user_account where username = 'system';
[
  {
    "id": "f871c485-a872-3fa6-fba2-4a70903fc3ce",
    "username": "system"
  },
  {
    "id": "f871c485-a872-3fa6-fba2-4a70903fc3ce",
    "username": "system"
  }
]
SELECT 2 rows in set (0.002 sec)

**Comment by seut** [comment]
@daniel11c Could you please paste your table schema, number of nodes inside the cluster, etc? I guess `id` is a primary key, any more columns part of the PK?

**Comment by daniel11c** [comment]
+-----------------------------------------------------+
| SHOW CREATE TABLE db.user_account                   |
+-----------------------------------------------------+
| CREATE TABLE IF NOT EXISTS "db"."user_account" (    |
|    "active" BOOLEAN,                                |
|    "archived" TIMESTAMP,                            |
|    "created" TIMESTAMP NOT NULL,                    |
|    "default_company_id" STRING,                     |
|    "email" STRING NOT NULL,                         |
|    "first_name" STRING,                             |
|    "id" STRING,                                     |
|    "last_name" STRING,                              |
|    "last_password_change" TIMESTAMP,                |
|    "modified" TIMESTAMP NOT NULL,                   |
|    "password" STRING NOT NULL,                      |
|    "username" STRING NOT NULL,                      |
|    PRIMARY KEY ("id")                               |
| )                                                   |
| CLUSTERED BY ("id") INTO 6 SHARDS                   |
| WITH (                                              |
|    "allocation.max_retries" = 5,                    |
|    "blocks.metadata" = false,                       |
|    "blocks.read" = false,                           |
|    "blocks.read_only" = false,                      |
|    "blocks.read_only_allow_delete" = false,         |
|    "blocks.write" = false,                          |
|    column_policy = 'dynamic',                       |
|    "mapping.total_fields.limit" = 1000,             |
|    number_of_replicas = '0-1',                      |
|    refresh_interval = 1000,                         |
|    "routing.allocation.enable" = 'all',             |
|    "routing.allocation.total_shards_per_node" = -1, |
|    "translog.durability" = 'REQUEST',               |
|    "translog.flush_threshold_size" = 536870912,     |
|    "translog.sync_interval" = 5000,                 |
|    "unassigned.node_left.delayed_timeout" = 60000,  |
|    "warmer.enabled" = true,                         |
|    "write.wait_for_active_shards" = 'all'           |
| )                                                   |
+-----------------------------------------------------+

Cluster has 3 nodes.
Just fount out that "system" is the only duplicate entry so it looks to be PK violation but not because of replication:
+--------+----------+---------------+--------------------------------------+----------------------+---------------+
| active | archived |       created | id                                   | last_password_change |      modified |
+--------+----------+---------------+--------------------------------------+----------------------+---------------+
| TRUE   |     NULL | 1549638275209 | f871c485-a872-3fa6-fba2-4a70903fc3ce |        1549638275209 | 1549638275209 |
| TRUE   |     NULL | 1549638275209 | f871c485-a872-3fa6-fba2-4a70903fc3ce |        1549638275209 | 1550828732584 |
+--------+----------+---------------+--------------------------------------+----------------------+---------------+
The other "id"s are unique.

**Comment by seut** [comment]
Thanks for this information, yes replication will never result in duplicates as either a primary or a replica shard is queried. One more question, how did you insert your duplicate records (insert from values/subquery or copy from)?

**Comment by daniel11c** [comment]
Most probable it was inserted by this:
insert into db.user_account(id, created, modified, username, email, first_name, last_name, last_password_change, password)
(
  select 'f871c485-a872-3fa6-fba2-4a70903fc3ce',
         current_timestamp,
         current_timestamp,
         'system',
         'xxxxxx',
         'xxxxxx',
         'xxxxxx',
         date_trunc('second', current_timestamp),
         'xxxxxx'
)

**Comment by seut** [comment]
@daniel11c Did you maybe deleted the document with id `f871c485-a872-3fa6-fba2-4a70903fc3ce` and re-inserted it at some point? (If so you've probably hit https://github.com/elastic/elasticsearch/pull/29619 which has been fixed by CrateDB > 3.2.0)
