### ISSUE TITLE
Incompatible minimum and maximum heap sizes specified

### ISSUE THREAD

**Issue by sydekumf** [crate/crate#828]
Hi,
I downloaded crate and started it on console `bin/crate`. I run it on Mac OS.
Unfortunately I get the following error:

Error occurred during initialization of VM
Incompatible minimum and maximum heap sizes specified

Any ideas?

**Comment by mfsi-sandeepagrawal** [comment]
I had java installed even then i was also getting the same error in my mac system and i just installed "Java SE Development Kit 8u60"(jdk-8u60-macosx-x64.dmg) for "Mac OS X x64" and then the issue got fixed. http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

so i think just installing "Java SE Development Kit 8u60" for right system from above link may fix this issue for others who ever faces this problem.
