### ISSUE TITLE
Stable packages for debian are not available in repository

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#8305]
**CrateDB version**:
3.2.4

**Environment description**:
ALL debian versions.

**Problem description**:
Issue #8257 is not resolved.
v3.2.4 is not available for jessie (neither for stretch)

**Steps to reproduce**:
"curl https://cdn.crate.io/downloads/apt/stable/pool/main/c/crate/"

**Comment by seut** [comment]
Thanks for reporting, we'll fix this asap.

**Comment by autophagy** [comment]
@daniel11c Thank you for the report - 3.2.4 is now there for `stretch`. `jessie` is no longer supported.
