### ISSUE TITLE
Unable to INSERT or RESET table after updating to Crate 3.2.2

### ISSUE THREAD

**Issue by tellezb** [crate/crate#8308]
**CrateDB version**:
3.2.2

**Environment description**:
Amazon Linux
3 AWS c4.large nodes

**Problem description**:
I receive the following exception when I try to INSERT into my table or when I try to ALTER TABLE [...] RESET my table. This occurs on 2 of the tables in my cluster, but not all tables. Cluster restart does not help.

> SQLActionException[SQLParseException: unknown setting [index.recovery.initial_shards] please check that any required plugins are installed or `license.enterprise` is enabled, if the plugin(s) require(s) it, or check the breaking changes documentation for removed settings]

The table version details are:

`elasticsearch
:
5.6.8
cratedb
:
2.3.11`

SHOW CREATE TABLE returns:

> CREATE TABLE IF NOT EXISTS "tracking_test"."login_activity" (
   "id" STRING,
   "partition" STRING,
[ ... ]
   PRIMARY KEY ("id", "partition")
)
CLUSTERED BY ("id") INTO 4 SHARDS
PARTITIONED BY ("partition")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-2',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 209715200,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'ALL'
)

**Steps to reproduce**:

1. Run 2.3.11 cluster
2. Create table and insert data
3. Upgrade to Crate 3.2.2 (latest available yum version)
4. OPTIMIZE TABLE ... WITH (upgrade_segments = true)
5. Attempt to insert into table

**Comment by mfussenegger** [comment]
The `index.recovery.initial_shards` setting has been deprecated in 2.1.0 and was removed in 3.0.0. But I guess we didn't mention in the release notes how to get rid of this setting from existing tables.

Is it possible for you to create a new table and copy over the data using insert from query and then rename/swap the tables?

**Comment by tellezb** [comment]
I would really like to avoid having to drop and recreate the tables as there are millions of records in the production tables and that would cause a fairly long downtime when we update. We already went through the process of dropping and recreating every table when we migrated to version 2.0 from version 1.0.

I didn't initially create my tables with an explicit value for `index.recovery.initial_shards`. I'm confused why this is only affecting a handful of tables vs all of them.

What other options do I have besides dropping and recreating? This can't be a requirement every time Crate deprecates/removes a table setting.

**Comment by mfussenegger** [comment]
> I didn't initially create my tables with an explicit value for index.recovery.initial_shards. I'm confused why this is only affecting a handful of tables vs all of them.

Do these tables come from an earlier version than 2.3? I wasn't able to reproduce the issue *without* explicitly adding the `recovery.initial_shards` setting.

> What other options do I have besides dropping and recreating? This can't be a requirement every time Crate deprecates/removes a table setting.

We'll work on a fix for this for the next 3.2 hotfix release.

**Comment by tellezb** [comment]
> Do these tables come from an earlier version than 2.3? I wasn't able to reproduce the issue without explicitly adding the recovery.initial_shards setting.

After further research:
These tables were recreated after the 1.0.5 to 2.3.11 upgrade. Our upgrade routine used 'SHOW CREATE TABLE' to generate the script for the creation of a new table to put the existing data in, before dropping the original table. It looks like 'SHOW CREATE TABLE' includes settings in the table creation script which were not originally used to create the table...ultimately leading to `recovery.initial_shards` being included in the table creation.

> We'll work on a fix for this for the next 3.2 hotfix release.

Fantastic, this is great news!

**Comment by mfussenegger** [comment]
We've a fix for this (https://github.com/crate/crate/pull/8315) which will be in the next 3.2 release.

Thank you for the bug report.

**Comment by tellezb** [comment]
I have another table with `SQLActionException[MapperParsingException: Failed to parse mapping [default]: Could not convert [week.index] to boolean]` for inserts, etc. Is this related and resolve via this bug or should I file another bug?

Table definition:
```
CREATE TABLE IF NOT EXISTS "test"."image" (
   "day" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', "image_date"),
   "id" LONG,
   "image_date" TIMESTAMP,
   "month" TIMESTAMP GENERATED ALWAYS AS date_trunc('month', "image_date"),
   "partition" STRING,
   "week" TIMESTAMP GENERATED ALWAYS AS date_trunc('week', "image_date"),
   PRIMARY KEY ("id", "partition")
)
CLUSTERED INTO 6 SHARDS
PARTITIONED BY ("partition")
WITH (
   column_policy = 'strict',
   number_of_replicas = '0-2'
)
```

Table version['created'] info:
`elasticsearch: 2.4.2, cratedb:1.1.6`

**Comment by mfussenegger** [comment]
This might already be resolved by https://github.com/crate/crate/pull/8236. We'll double check to be sure.

**Comment by mfussenegger** [comment]
> I have another table with SQLActionException[MapperParsingException: Failed to parse mapping [default]: Could not convert [week.index] to boolean] for inserts, etc. Is this related and resolve via this bug or should I file another bug?

Does this error also happen in 3.2.2? You mention that the table was created in 1.1.6, but that would require that they're going to be migrated in a 2.x version before being able to move to 3.x.

Creating the table in 2.3.x and moving to 3.2.2 (without any of the fixes mentioned applied) doesn't trigger the issue for me.

**Comment by tellezb** [comment]
Yes, both of the issues mentioned here (`Could not convert [week.index] to boolean` and `recovery.initial_shards`) are occurring on our 3.2.2 cluster. The cluster was recently upgraded from 2.3.11.

`elasticsearch: 2.4.2, cratedb:1.1.6` was obtained by querying:
```
select version['created'] from information_schema.tables
```

The cluster had no issues before the 3.2.2 upgrade.

**Comment by tellezb** [comment]
I've check our other clusters (test, stag, prod, etc) and this is the only table in any cluster which has a version['created'] of `1.1.6`. All other tables have `2.3.11` which is what is expected given that we recreated all tables after the 2.3.11 upgrade in preparation for Crate version 3+. 

(Odd that cluster check `https://cr8.is/d-cluster-check-5` was not warning about this table prior to the upgrade)

If you were unable to reproduce for a table created in 2.3.x then I think we can chalk this one up to the table not having been recreated in version 2.x like required, and this bug can be re-resolved.

**Comment by mfussenegger** [comment]
Okay, I'm closing this then.
