### ISSUE TITLE
Leumi Card System not functioning

### ISSUE THREAD

**Issue by philipyg1960** [crate/crate#8309]
**CrateDB version**:
2.3.9-1

**Environment description**:
System up but does not listen on port 3200, only on port 4300
All three nodes on same segment

**Problem description**:

**Steps to reproduce**:

**Comment by philipyg1960** [comment]
We use Bomgar, through which you can connect to us.
 Please call me +972 52 2428365 and I will start the software.
The link is:
https://rs.leumicard.co.il
The Bomgar will download an agent to your PC,
Once connected I will provide a numeric code over the phone.

Best regards,
                    Phil.

**Comment by seut** [comment]
Please use our private customer repository at https://github.com/crate/c-leumicard/.

**Comment by philipyg1960** [comment]
Hi,
Updated as instructed

Best regards,
                        Phil.

**Comment by philipyg1960** [comment]
Hi 
We are happy with the default port configuration and do not require it changed
Assistance is required to get the system up and running

Best regards

Phil
