### ISSUE TITLE
INSERT AS SELECT failed without error

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8312]
**CrateDB version**:
3.2.4

**Problem description**:

Insert as select query returned '0 rows inserted' for object columns, when data convertion of one of the fields is failed.

**Steps to reproduce**:

`create table test.a1 ( obj object as (x integer) );`
`create table test.a2 ( obj object as (x long) );`

`insert into test.a2 (obj) values ({ x = '-9223372036854775808' });`
(1 rows inserted)

`select * from test.a2;`
(1 rows selected)

`insert into test.a1
select * from test.a2;`
(0 rows inserted) - *some data were lost now without any error*

`insert into test.a2 (obj) values ({ x = 42 });`
(1 rows inserted)

`insert into test.a1
select * from test.a2;`
(1 rows inserted) - *some data were lost now without any error*

`select * from test.a1;`
(1 rows selected)

**Comment by seut** [comment]
This is a known behaviour and not a bug, see https://crate.io/docs/crate/reference/en/latest/general/dml.html#inserting-data. 
If one is inserting multiple rows some rows maybe already written when the error occurs.
If we would throw the error, it would be unknown how much records were already successfully written.
We agree that the different behaviour of single- vs. multi-row-insert is not ideal and consistent, we're planning to change this in the future in one direction.

**Comment by shm-dmitry** [comment]
@seut , thank you for a reply.
May be it is possible to raise 'Query particuly executed, you have to check results' error in this case?
In this case, the error will be much easier to find.
I can create a new feature request, if you need.

**Comment by seut** [comment]
@shm-dmitry The problem here is to compatible with SQL, on an error no affected row count can be returned, how would one find out how much records were successfully written with your proposal? INSERT statements are expected to return only an affected row count and no result set. We are still investigating for a good solution, any suggestions which are SQL compatible are really welcome.

**Comment by shm-dmitry** [comment]
@seut , I think than my proposal is compatible with SQL standart:

1. (all nodes processed all insert parts successfully, no errors was raised) - ok, return 'inserted rows count' as standard required and as now works.
2. (some data parts failed to insert, some data inserted successfully) - raise SQL exception 'Failed to insert some data, please, check consistency manually'

In this case I will catch this error - and I will understand - something wrong, and I have to try to select/validate data. 

At now I don't understand - my request processed.. or not? 

Some pseudo-code when this logic may be useful:
I have 2 tables: PRIMARY and REVIEW.
When somebody pressed button 'Accept' - I execute code like this:
`INSERT INTO primary SELECT * FROM review WHERE ID in (......)`
`DELETE FROM review WHERE ID in (......)`

At now I silently lost data in some cases based on row content.
Yes, I can try to check row count against awaited (if I know awaited row count) - but I have to do it everywhere..
In my proposal I will catch SQL Exception (perfectly - with some special SQL CODE), and I can start some business-logic to fix this error at real-time or notify user.

**Comment by seut** [comment]
@shm-dmitry Ok seems like I have misunderstood your proposal, yes this solution would be possible.
That's what I meant with, "align it in one direction". 
I'm not quite sure how feasible it is to find out the successfully written records afterwards.
Using a session var to change the behaviour in general is an interesting option.
I may create a dedicated issue about this to describe the problem and collect more input (preferences).
Thanks for your input!
