### ISSUE TITLE
poor performance when using any

### ISSUE THREAD

**Issue by bputt** [crate/crate#8514]
**CrateDB version**:
3.1.1

**Environment description**:
centos 7.latest
openjdk 1.8

**Problem description**:
We're seeing a huge performance degradation when adding filters to our sql. The query takes ~5s to run prior to adding this filter below which takes the query ~6 minutes to run. The arrays only have ~5 values in them and the values are no more than 80 characters long

```
AND NOT 'some-value' = ANY(tags['somearray1'])
```

Final query
```
SELECT startdatehour as "start", count(*) as COUNT, tags['somestr1'] as "someField" FROM thedatas WHERE ( partitionkey >= ? AND partitionkey <= ? ) AND ( startdate >= ? and startdate <= ? and sysid = ? and  createdat <= ?) AND (tags['somestr2'] NOT LIKE ? AND tags['somestr3'] = ? AND tags['somestr1'] = ? AND ( NOT ? = ANY(tags['somearray1'])) AND ( NOT ? = ANY(tags['somearray1']) )) GROUP BY "start", "someField"
```

**Steps to reproduce**:

Simplified schema:

```
CREATE TABLE thedatas (
    startdate TIMESTAMP,
    startdatehour TIMESTAMP,
    enddate TIMESTAMP,
    createdat TIMESTAMP,
    sysid STRING,
    tags OBJECT(STRICT) AS (
        somestr1 STRING,
        somestr2 STRING,
        somestr3 STRING,
        somelong1 LONG,
        somelong2 LONG,
        sometimestamp1 TIMESTAMP,
        sometimestamp2 TIMESTAMP,
        somearray1 ARRAY(STRING),
        somearray2 ARRAY(STRING),
        somebool1 BOOLEAN,
        somebool2 BOOLEAN
    ),
    partitionkey TIMESTAMP
) CLUSTERED INTO 1 SHARDS PARTITIONED BY (partitionkey)
WITH (
    number_of_replicas = 1,
    refresh_interval = 30000,
    column_policy = 'strict'
)
```

**Comment by mfussenegger** [comment]
Have you tried using the [ignore3vl](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#ignore3vl) function that is mentioned in the [any docs](https://crate.io/docs/crate/reference/en/latest/general/builtins/array-comparisons.html?highlight=any#any-some-array-expression) ?

**Comment by bputt** [comment]
@mfussenegger  thanks for the link, we have not tried it....Just to make sure I understand it correctly, as long as we're not storing null values in the array, it's fine to use that function?

**Comment by mfussenegger** [comment]
> Just to make sure I understand it correctly, as long as we're not storing null values in the array, it's fine to use that function?

It can also be used if there are `null` values inside the array, but the semantics change:

```
cr> select 5 = ANY ([1, 2, null]);
+-----------------------+
| 5 = ANY([1, 2, NULL]) |
+-----------------------+
|                  NULL |
+-----------------------+


cr> select ignore3vl(5 = ANY ([1, 2, null]));
+----------------------------------+
| ignore3vl(5 = ANY([1, 2, NULL])) |
+----------------------------------+
| FALSE                            |
+----------------------------------+
```
