### ISSUE TITLE
Disabled Indexing and Column Store: Any way to check for NULL-Columns?

### ISSUE THREAD

**Issue by fetzerms** [crate/crate#8524]
I have a column "content" that stores data that is >32kb. Hence I turned off indexing and the column store. Is there any way to find rows that do not have any value in that column?

If I query for ".. and content is null" all rows seem to be returned. If I query for "content is not null" none are returned. I am aware, that I cannot search in that column, tho is there a way to check if it even contains a value?

**Comment by seut** [comment]
This is not possible at the moment as we do not support a fallback to a generic function filter for `IS NULL` predicates. Just to mention that using this possible fallback would result in a full table scan with an additional filter, but I guess that's what you'd targeting to.
We'll put it on our backlog, thanks for highlighting.

**Comment by fetzerms** [comment]
Thank you very much for the feedback. So I guess there is no other way than going through all the records and actually selecting the column in order to check whether it contains data or not.

**Comment by mfussenegger** [comment]
A possible workaround would be to add a generate column that tracks if the content contains something:

```sql
CREATE TABLE tbl (
    id int PRIMARY KEY,
    content text INDEX OFF STORAGE WITH (columnstore = FALSE),
    has_content AS (content IS NOT NULL AND content != '')
);
```
