### ISSUE TITLE
Update from query

### ISSUE THREAD

**Issue by Crazy1van** [crate/crate#8540]
Updated based on additional troubleshooting
============================

It appears that update from a select query doesn't work correctly if the select query contains where-in clauses.  

Example:
select count(myentity) from myschema.permissions where filepath in (select distinct(executablepath) from myschema.services);

The above query returns a count of ~427 million.

Using the same query to update a field:

update myschema.totals set entitycount=(select count(myentity) from myschema.permissions where filepath in (select distinct(executablepath) from myschema.services) limit 1);

This updates the field to just ~10 million records (instead of 427 million).

**Comment by mfussenegger** [comment]
1) Which version of CrateDB are you using
2) What's the result of `SELECT COUNT(*) FROM tableB` ?

I can't reproduce the issue, for me it behaves as expected.

**Comment by Crazy1van** [comment]
Crate version is 3.2.2.

I did some more troubleshooting and it appears that the issue is related to nested queries (I originally oversimplified for demo purposes).  The results are inconsistent between a select and update-select.  

Example:
select count(computername) from myschema.permissions where filepath in (select distinct(executablepath) from myschema.services);

The above query returns a count of ~427 million.

Using the same query to update a field:

update myschema.totals set computercount=(select count(computername) from myschema.permissions where filepath in (select distinct(executablepath) from myschema.services) limit 1);

This updates the field to just ~10 million records (instead of 427 million).

Additional where clauses (removed from this example) further reduce the number to 1 where the select query actually gets ~45 thousand.

**Comment by kovrus** [comment]
Hi @Crazy1van, thank you for reporting the issue. It was addressed and the fix will be a part of 3.2.8 and 3.3.2 releases.
