### ISSUE TITLE
insert into select bug

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8550]
**CrateDB version**:
3.2

**Environment description**:
 - JVM version: java1.8
 - Distribution: centos 6.5
 - Number of nodes; 4 node

**Problem description**:
table a 200 record
table b 0 record

insert into b select * from a limit 10
and the result is 40 records has been insert !!!!(my cluster has 4 nodes)
What's the matter?

**Comment by mfussenegger** [comment]
Could you post the exact query you're using? Currently the query clause of a `INSERT INTO` isn't allowed to contain a limit at all. The query you posted would result in an error: ` Using limit, offset or order by is not supported on insert using a sub-query`

**Comment by cmdares** [comment]
insert into b select * from (select * from a limit 10)c

**Comment by mfussenegger** [comment]
Thank you for the bug report, we've a fix for this (https://github.com/crate/crate/pull/8555) which will be part of the next 3.2 and 3.3 releases.
