### ISSUE TITLE
SQLActionException[MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 75875]

### ISSUE THREAD

**Issue by suhaibaffan** [crate/crate#8606]
**CrateDB version**: 3.2.6

**Environment description**:

**Problem description**: This occurs when I tried inserting data which exceeds more than 32766 bytes.
`SQLActionException[MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 75875]`

**Steps to reproduce**:Try inserting a huge JSON object into a table.

**Comment by seut** [comment]
See https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#data-type-text and https://crate.io/docs/crate/reference/en/latest/general/ddl/storage.html#ddl-storage-columnstore on how to work around the 32766 bytes limitation.
