### ISSUE TITLE
Amazon Corretto

### ISSUE THREAD

**Issue by robd003** [crate/crate#8662]
**Use case**: Switch the JDK to Amazon Corretto to gain long term support and performance

**Feature description**:
Amazon Corretto is an Amazon supported freely available JDK build with performance fixes along with backported bug fixes.
https://github.com/corretto/corretto-11

**Comment by mfussenegger** [comment]
You're free to use Amazon Corretto. For the time being we'll continue testing and recommending the OpenJDK releases.

**Comment by mfussenegger** [comment]
We've extended some of our tests to also run with [adopt opendjk](https://adoptopenjdk.net/)

**Comment by robd003** [comment]
Great work, thanks!
