### ISSUE TITLE
Crate latest fails to install due to openjdk-11 issue

### ISSUE THREAD

**Issue by CJCShadowsan** [crate/crate#8677]
**CrateDB version**:
3.3.2-1

**Environment description**:

centos 7.6

**Problem description**:

https://bugzilla.redhat.com/show_bug.cgi?id=1709904

OpenJDK install on java-11-openjdk fails to install due to the provides on the openjdk package now no longer specifying jre as a provides:

Additional info:

---> Package crate.noarch 0:3.3.2-1 will be installed
--> Processing Dependency: jre >= 11 for package: crate-3.3.2-1.noarch
--> Finished Dependency Resolution
Error: Package: crate-3.3.2-1.noarch (crate)
           Requires: jre >= 11
           Available: 1:java-1.7.0-openjdk-1.7.0.191-2.6.15.5.el7.x86_64 (base)
               jre = 1.7.0
           Available: 1:java-1.7.0-openjdk-1.7.0.201-2.6.16.1.el7_6.x86_64 (updates)
               jre = 1.7.0
           Available: 1:java-1.7.0-openjdk-1.7.0.211-2.6.17.1.el7_6.x86_64 (updates)
               jre = 1.7.0
           Available: 1:java-1.7.0-openjdk-1.7.0.221-2.6.18.0.el7_6.x86_64 (updates)
               jre = 1.7.0
           Available: 1:java-1.8.0-openjdk-1.8.0.181-7.b13.el7.i686 (base)
               jre = 1.8.0
           Available: 1:java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.i686 (updates)
               jre = 1.8.0
           Available: 1:java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i686 (updates)
               jre = 1.8.0
           Available: 1:java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64 (updates)
               jre = 1.8.0
           Available: 1:java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.i686 (updates)
               jre = 1.8.0
           Available: 1:java-1.8.0-openjdk-debug-1.8.0.181-7.b13.el7.i686 (base)
               jre = 1.8.0-debug
           Available: 1:java-1.8.0-openjdk-debug-1.8.0.191.b12-0.el7_5.i686 (updates)
               jre = 1.8.0-debug
           Available: 1:java-1.8.0-openjdk-debug-1.8.0.191.b12-1.el7_6.i686 (updates)
               jre = 1.8.0-debug
           Available: 1:java-1.8.0-openjdk-debug-1.8.0.201.b09-2.el7_6.x86_64 (updates)
               jre = 1.8.0-debug
           Available: 1:java-1.8.0-openjdk-debug-1.8.0.212.b04-0.el7_6.i686 (updates)
               jre = 1.8.0-debug
           Available: 1:java-11-openjdk-11.0.ea.28-7.el7.i686 (base)
               jre = 11
           Available: 1:java-11-openjdk-debug-11.0.ea.28-7.el7.i686 (base)
               jre = 11-debug
           Installed: 1:java-11-openjdk-11.0.3.7-0.el7_6.i686 (@updates)
               Not found
           Installed: 1:java-11-openjdk-debug-11.0.3.7-0.el7_6.i686 (@updates)
               Not found
           Available: 1:java-11-openjdk-11.0.1.13-3.el7_6.i686 (updates)
               Not found
           Available: 1:java-11-openjdk-11.0.2.7-0.el7_6.i686 (updates)
               Not found
           Available: 1:java-11-openjdk-debug-11.0.1.13-3.el7_6.i686 (updates)
               Not found
           Available: 1:java-11-openjdk-debug-11.0.2.7-0.el7_6.i686 (updates)
               Not found

# repoquery --provides java-11-openjdk
java-11 = 1:11.0.3.7-0.el7_6
java-11-openjdk = 1:11.0.3.7-0.el7_6
java-11-openjdk(x86-32) = 1:11.0.3.7-0.el7_6
jre-11 = 1:11.0.3.7-0.el7_6
jre-11-openjdk = 1:11.0.3.7-0.el7_6
libjawt.so
java-11 = 1:11.0.3.7-0.el7_6
java-11-openjdk = 1:11.0.3.7-0.el7_6
java-11-openjdk(x86-64) = 1:11.0.3.7-0.el7_6
jre-11 = 1:11.0.3.7-0.el7_6
jre-11-openjdk = 1:11.0.3.7-0.el7_6
libjawt.so()(64bit)

This also isn't fixed in the rolling openjdk 12 release either.

The ea release fails bootstrap checks so won't start up for security purposes.

**Steps to reproduce**:

Use CentOS 7.6
Install crate after installing java-11-openjdk

**Comment by mfussenegger** [comment]
Thank you for the report, we'll have a look at this.

**Comment by mfussenegger** [comment]
Given the upstream response (https://bugzilla.redhat.com/show_bug.cgi?id=1689062) we've decided to change `Requires` to `jre-11` (We unfortunately can't use `OR` declarations with RPM 4.11 which is available in CentOS 7.6).

This might rule out pulling in OpenJDK 12, but should be good enough for now as OpenJDK 12 isn't available in the default repos anyway.

We've rebuild the packages (`3.3.2-3` should be available in the repositories)
