### ISSUE TITLE
Node stuck with 100% CPU

### ISSUE THREAD

**Issue by rps-v** [crate/crate#8728]
**CrateDB version**:
3.3.2

**Environment description**:

 - JVM version:
> openjdk version "1.8.0_201-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_201-1-ojdkbuild-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

 - Distribution: Windows Server 2012 R2
 - Number of nodes; 1

**Problem description**:

Node get stuck with 100% CPU usage after certain queries are run (involving JOINs maybe ?) and the only way to recover is via restart. Admin UI shows "No Data Available.".
Unfortunately I cannot get the last queries ran because the node becomes unresponsive.

_Heap dump available via email if needed._

[threaddumps.zip](https://github.com/crate/crate/files/3211845/threaddumps.zip)

![Annotation 2019-05-23 140804](https://user-images.githubusercontent.com/26383032/58248973-4c321e80-7d66-11e9-8d88-13ac8e16e71c.jpg)
![Annotation 2019-05-23 140826](https://user-images.githubusercontent.com/26383032/58248974-4ccab500-7d66-11e9-90c5-e48484d8cd3d.jpg)

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
Could you share the queries, and ideally the table schemas, that lead to the node becoming stuck? The thread-dump implies it's a left join, but it would help to have the exact query so that we can investigate further.
