### ISSUE TITLE
CircuitBreakingException, might be leaking memory problem.

### ISSUE THREAD

**Issue by suhaibaffan** [crate/crate#8780]
**CrateDB version**: 3.2.6

**Environment description**:
- JVM version: Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
- Kernel: Linux ip-172-31-4-175 4.4.0-1066-aws #76-Ubuntu SMP Thu Aug 16 16:21:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: NAME=“Ubuntu”
VERSION=“16.04.2 LTS (Xenial Xerus)”
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=“Ubuntu 16.04.2 LTS”
VERSION_ID=“16.04"
HOME_URL=“http://www.ubuntu.com/”
SUPPORT_URL=“http://help.ubuntu.com/”
BUG_REPORT_URL=“http://bugs.launchpad.net/ubuntu/”
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Number of nodes: 2

**Problem description**:
There is no error for a certain of time when the crate is started.
The `CircuitBreakingException`  will occur once the db is used for 4-5 days.
When the db is started initial queries never throw error but it will start throwing error after a week.
```SQLActionException[CircuitBreakingException: [parent] Data too large, d ata for [&lt;transport_request&gt;] would be [6741628353/6.2gb], which is larger tha n the limit of [6740167884/6.2gb], usages [request=0/0b, fielddata=0/0b, in_fl  ight_requests=354/354b, query=6199499639/5.7gb, jobs_log=0/0b, operations_log=  469773196/448mb, accounting=72355164/69mb]]```
. The only solution right now we are trying to solve is just restart the db.
It feels like there is a memory leak problem.

**Steps to reproduce**: This happens for every query once the memory is not freeing. We have like 59.3 million records in the DB.

**Comment by mfussenegger** [comment]
Would it be possible to provide us with heap dumps? One taken a day after a restart, and another one after 3 days or so?

**Comment by suhaibaffan** [comment]
Okay I can send but I tried setting the path for heap dump but I am getting an error after setting `CRATE_HEAP_DUMP_PATH`: 
```06 04:28:22 ip-172-31-4-175 crate[6340]: [2019-06-06T04:28:22,064][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [S'chn T'gai Spock] uncaught exception in thread [main]
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]: org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [CRATE_HEAP_DUMP_PATH] please check that any required plug
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]:         at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:31) ~[crate-app-3.2.6.jar:3.2.6]
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]:         at io.crate.bootstrap.CrateDB.init(CrateDB.java:159) ~[crate-app-3.2.6.jar:3.2.6]
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]:         at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) ~[crate-app-3.2.6.jar:3.2.6]
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) ~[crate-app-3.2.6.jar:3.2.6]
Jun 06 04:28:22 ip-172-31-4-175 crate[6340]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:3.2.6]```

**Comment by suhaibaffan** [comment]
I have set the `CRATE_HEAP_DUMP_PATH=/crate/heap_dump` in `/root/etc-default-crate`. This should work right to get the heap dumps on db failure?

**Comment by mfussenegger** [comment]
> This should work right to get the heap dumps on db failure? 

Yep that should work.

**Comment by suhaibaffan** [comment]
Can I have your email @mfussenegger? Once I have the `heap dump` I will mail you.

**Comment by mfussenegger** [comment]
> Can I have your email @mfussenegger? Once I have the heap dump I will mail you.

You can send it to `mathias {at} crate.io`

**Comment by suhaibaffan** [comment]
> > Can I have your email @mfussenegger? Once I have the heap dump I will mail you.
> 
> You can send it to `mathias {at} crate.io`

Sure thanks I will be sharing the heap dump when it is available.
