### ISSUE TITLE
Second SELECT request failed while using ODBC connection

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8782]
**CrateDB version**: 3.3.3

**OS version**: 
>> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Used PostgreSQL ODBC driver**:
>> apt show odbc-postgresql
Package: odbc-postgresql
Version: 1:11.01.0000-1.pgdg18.04+1

**odbc.ini / odbcinst.ini**
>> cat /etc/odbc.ini
[crate]
Driver = PostgreSQL ANSI
Host = crate00
Server = crate00
ServerName = crate00
Database = doc
Port = 5432
Trace=yes
TraceFile=/tmp/odbc.log

>> cat /etc/odbcinst.ini
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=psqlodbca.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
>>
>>[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=psqlodbcw.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1

**Problem description**:
I trying to connect to crate via ODBC.
I successfully connected to crate, and first SELECT successfully executes.
But second SELECT is always failed.
Odbc trace file and tcpdump in attachment.
Exception raised from `BatchPortal.java:199`

[odbc.log](https://github.com/crate/crate/files/3265217/odbc.log)
[odbc.pcap.txt](https://github.com/crate/crate/files/3265223/odbc.pcap.txt) (rename it into odbc.pcap before open)

**Steps to reproduce**:

`iodbctest "DSN=crate;UID=crate;"`
`iODBC Demonstration program`
`This program shows an interactive SQL processor`
`Driver Manager: 03.52.0812.0326`
`Driver: 11.01.0000 (psqlodbca.so)`
` `
`SQL>select 1+2 as x;`
` `
`x`
`--------------------`
`3`
` `
` result set 1 returned 1 rows.`
` `
` `
`SQL>select 2+3 as x;`
**`1: SQLExec = ERROR: Only write operations are allowed in Batch statements;`
`Error while executing the query (1) SQLSTATE=0A000`**
` `
`SQL>some invalid statement will raise error`
`1: SQLExec = ERROR: SQLParseException: line 1:1: mismatched input 'some' expecting {'SELECT', 'DEALLOCATE', 'CREATE', 'ALTER', 'KILL', 'BEGIN', 'COMMIT', 'EXPLAIN', 'SHOW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'DROP', 'INSERT', 'DELETE', 'UPDATE', 'SET', 'RESET', 'COPY', 'GRANT', 'DENY', 'REVOKE'};`
`Error while preparing parameters (1) SQLSTATE=XX000`
` `
`SQL>select 3+4 as x;`
` `
`x`
`--------------------`
`7`
` `
` result set 1 returned 1 rows.`
` `
` `
`SQL>select 4+5 as x;`
**`1: SQLExec = ERROR: Only write operations are allowed in Batch statements;`
`Error while executing the query (1) SQLSTATE=0A000`**
` `
`SQL>`

**Comment by mfussenegger** [comment]
Thank you for the report, we'll have a closer look at this.

**Comment by mfussenegger** [comment]
This is due to us not being 100% compliant with the protocol spec.
We're currently not closing portals implicitly if a prepared statement is closed and it was the last reference to the portal.

`iodbctest` is making use of that behavior.

We'll work on a fix and should have it ready for the next `3.3` release. 

As far as I can tell this is not Postgres-ODBC specific, but specific to `iodbctest`, as I wasn't able to produce it with `pyodbc`.

**Comment by mfussenegger** [comment]
We've merged a [fix](https://github.com/crate/crate/pull/8805) for this which will be available with the next 3.3 release
