### ISSUE TITLE
Inconsistent results using WHERE in JOIN

### ISSUE THREAD

**Issue by Crazy1van** [crate/crate#8798]
CrateDB version: 3.2.2

The below query does not actually return all results matching the timestamp.

`select * from tableA A full join tableB B on A.fieldname=B.fieldname where A.datetime>'<timestamp>' and B.datetime>'<timestamp'`

But if I do the following, it works fine.

`select * from (select * from tableA where datetime>'<timestamp>') A full join (select * from tableB where datetime>'<timestamp>') B on A.fieldname=B.fieldname`

I would expect both queries to work the same.  I also tried to use 0 (zero) for the timestamp in the top  query and it did not return all results that I get from the same query without a where clause.  So the top query definitely doesn't seem to work correctly.

**Comment by mfussenegger** [comment]
Could you post the table schemas and the output of `EXPLAIN` of both statements?
