### ISSUE TITLE
NPE when updating object column for NULL object

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8832]
**CrateDB version**: 3.3.3

**Problem description**:
`SQL Error: ERROR: SQLParseException: Object a is null, cannot write b = c into it` raised when updating nested attribute in NULL object.

**Steps to reproduce**:
`create table test (a object as (b string), id int);`
*`>>Table TEST created.`*
`insert into test (id) values (0);`
*`>> 1 row inserted.`*
`update test set a['b'] = 'c';`
*`>> 1 row updated.`*
`update test set a = null;`
*`>> 1 row updated.`*
`update test set a['b'] = 'c';`
**`SQL Error: ERROR: SQLParseException: Object a is null, cannot write b = c into it`**
`update test set a = {};`
*`>> 1 row updated.`*
`update test set a['b'] = 'c';`
*`>> 1 row updated.`*

**Comment by mfussenegger** [comment]
This is currently expected behavior.

I assume you'd expect the object to be implicitly created with a single key set
to the provided value?

**Comment by shm-dmitry** [comment]
Yes, I expected to see same result from all updates in sample.
Otherwise I have to control it manually, and it's more difficult in real case:
There are 2 ways to do it and both are bad:
1. Update  one field of object -> catch exception -> update full object
2. Update full object with copy all other fields (but when new field added - i have to re-check all SQLs)
