### ISSUE TITLE
Support  lastest  aws sdk version.

### ISSUE THREAD

**Issue by piedro** [crate/crate#8845]
**CrateDB version**:
3.3.3.1

**Environment description**:
I was wondering if Cratedb supports the latest AWS SDK  1.11.340 or upper version.
it fixed the AWS meta bugs and can guess the metadata from the AWS EC2
https://github.com/elastic/elasticsearch/issues/27924

but, Currently, I found the 1.11.223 AWS SDK from the CRatedb, Does Cratedb has the updated plan?

**Comment by seut** [comment]
@piedro We'll upgrade the AWS SDK on MASTER to the latest version soon, thanks for highlighting.

**Comment by seut** [comment]
@piedro We've upgraded the AWS SDK by https://github.com/crate/crate/pull/8848, it will be part of the next major (4.0) release. Thanks again for reporting.
