### ISSUE TITLE
Unable to sort by constant column when using subquery with UNION ALL

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8851]
**CrateDB version**: 3.3.3

**Problem description**:
`ERROR: NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.UnsupportedOperationException: Using a non-integer constant in ORDER BY is not supported` error raised when trying to sort subquery with union-all.
I trying to find some workarounds but not found any usable.

Exception raised at SortSymbolVisitor.java:188

**Steps to reproduce**:

`create table test (a string);`
`>> Table TEST created.`

`insert into test (a) values ('s');`
`>> 1 row inserted.`

`select * from (`
`    select 1 as x, * `
`    from test`
`    union all`
`    select 2, * `
`    from test`
`) c`
`order by x`
**`ERROR: NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.UnsupportedOperationException: Using a non-integer constant in ORDER BY is not supported`**

`select * from (`
`    select cast(1 as integer) as x, * `
`    from test`
`    union all`
`    select cast(2 as integer), * `
`    from test`
`) c`
`order by x`
**`ERROR: NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.UnsupportedOperationException: Using a non-integer constant in ORDER BY is not supported`**

`select * from (`
`    select (select count(*) from test) as x, * `
`    from test`
`    union all`
`    select (select count(*) from test), * `
`    from test`
`) c`
`order by x`
**`ERROR: NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.UnsupportedOperationException: Using a non-integer constant in ORDER BY is not supported`**

**Comment by shm-dmitry** [comment]
I found workaround for this problem, maybe it will be helpfull for somebody:

`select * from (`
`    select char_length(a) * 0 + 1 as x, *`
`    from test`
`    union all`
`    select char_length(a) * 0, *`
`    from test`
`) c`
`order by x`

**Comment by seut** [comment]
@shm-dmitry Thanks for reporting, we'll have a closer look into this.

**Comment by seut** [comment]
@shm-dmitry We‘ve fixed it on master and will also backport it to 3.3. Thanks again for reporting.
