### ISSUE TITLE
Convert String to timestamp

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#8874]
**Use case**:

Assume we are storing data based on UTC which is coming from different places from particular time-zone. Now we just want to compare that timestamp by converting it to specific timezone with current timestamp. there is function which convert timestamp to specific date which return type string  but again we have to make it back to timestamp to compare with timestamp. 

**Feature description**:

**Comment by kovrus** [comment]
Hi @bhagujava ,

Please take a look at the [date_format](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#date-format-format-string-timezone-timestamp) function. Then, depends on your requirements, you might want to cast the result to timestamp with/without timezone and compare it against the current timestamp.

**Comment by bhagujava** [comment]
@kovrus 
Thanks for quick reply.

date_format will return string as far as i know. Now same string i want to compare with current timestamp. How could i do that ?

I havent  seen any method or function which can cast string to timestamp ? 

am i on the right path ?

**Comment by kovrus** [comment]
@bhagujava an expression might look like 
`date_format(...) :: timestamp with time zone <cmp operator> current_timestamp`

**Comment by marregui** [comment]
@belringer in addition you might want to have a look at the scalar function [timezone](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html?highlight=timezone#timezone-timezone-timestamp)
