### ISSUE TITLE
How to increase the memory max_map_count=262144 permanently

### ISSUE THREAD

**Issue by Georger2323** [crate/crate#8930]
I am running docker toolbox on windows and every time I restart my computer I always need to run the following commands: docker-machine ssh
sudo sysctl -w vm.max_map_count=262144	

Where should I write these settings to be stored permanently?

**Comment by seut** [comment]
I think this would do the trick: https://forums.docker.com/t/how-do-i-make-persistent-settings-sysctl-conf-and-others-changes-to-the-virtual-machine/13149/7
Otherwise may consider asking at the CrateDB community forum https://community.crate.io/.
