### ISSUE TITLE
Crate's automatic timestamp is wrong

### ISSUE THREAD

**Issue by Georger2323** [crate/crate#8936]
I'm using the Fiware platform to send data to Crate DB from Orion Context Broker, using docker.
Crate automatically creates a timestamp column ("time_index"), however, the time indicated is wrong. It is 3 hours behind.

Is there any way to fix this?
![ts](https://user-images.githubusercontent.com/52736731/61473996-56505200-a990-11e9-8c24-bb3c37dc4d87.png)

Thank you.

**Comment by mfussenegger** [comment]
This sounds like a timezone issue. The timestamp values that are send to CrateDB are considered to be UTC. 

You could for example use the `date_format` function to get the formatted time in a specific time zone:

```
cr> select date_format('%Y-%m-%d %H:%i', 1563466040084) as utc, date_format('%Y-%m-%d %H:%i', 'Europe/Vienna', 1563466040084) as vienna;
                                                                                                                                        
+------------------+------------------+
| utc              | vienna           |
+------------------+------------------+
| 2019-07-18 16:07 | 2019-07-18 18:07 |
+------------------+------------------+
```
