### ISSUE TITLE
SQLActionException[UnsupportedFeatureException: Cannot use table functions inside aggregates]

### ISSUE THREAD

**Issue by sugengsuprayogi** [crate/crate#8937]
**Use case**:
When i query select count( distinct unnest("col"['id'])) FROM table where id = 8499;
got error SQLActionException[UnsupportedFeatureException: Cannot use table functions inside aggregates]
**Feature description**:

**Comment by mfussenegger** [comment]
You've to rewrite the query slightly:

```
SELECT
    count(x)
FROM ( SELECT DISTINCT
        UNNEST(xs) AS x
    FROM
        t1
    WHERE
        id = 8499) tv;
```
