### ISSUE TITLE
Enable data compression in lucene indices

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#8938]
I want to enable compression for stored data in lucene indices.
ES supports [this](https://www.elastic.co/blog/store-compression-in-lucene-and-elasticsearch)

It can help to save data space on HDD and decrease time of data querying.

This option can be customized via new table parameter.

**Comment by mfussenegger** [comment]
Thank you for pointing this out, we've exposed it now (https://github.com/crate/crate/pull/9023) and it will be part of 4.1
