### ISSUE TITLE
navicat for pg connetion error

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8961]
**CrateDB version**:
4.0.2
navicat for pg client 12.1.20
------connection form-------
cratedb
localhost
5432
doc
crate

test connection is ok
but open connection "ERROR:Unknow session setting  name 'datestyle' "
and crate console echo 
[2019-07-30T12:43:53,176][INFO ][i.c.p.s.SetSessionPlan   ] [Bivare] SET SESSION STATEMENT WILL BE IGNORED: client_encoding

**Comment by mfussenegger** [comment]
Could you post the output of `select * from sys.jobs_log where error is not null order by ended desc;` after trying to connect with navicat so that we see the exact queries that were being invoked?

**Comment by masterkain** [comment]
I have the same issue with navicat.
I'm also trying another utility called `pgsync` to check if I can transfer some records from a normal postgres to crate but it's failing with:

```
/usr/src/app # bundle exec pgsync --list
To: sys on cratedb01:5432
ERROR:  line 3:17: no viable alternative at input 'SELECT\n  table_schema AS schema,\n  table_name AS table'
```

**Comment by mfussenegger** [comment]
@masterkain thank you for getting back to us on this issue.

@seut  created a [new issue](https://github.com/crate/crate/issues/10818) to track the root cause of the error you got.
