### ISSUE TITLE
match and or exp

### ISSUE THREAD

**Issue by cmdares** [crate/crate#8978]
how to support
select * from table1 where match(full_text_filed,'(word1 OR word2 OR word3) AND (word4 OR word5 OR word6)  AND (word7 OR word8 OR word9) AND NOT (text1 OR text2 OR text3)')

And not to usage method:
SELECT * FROM TABLE1 WHERE
MATCH.. AND MATCH.. OR MATCH.. AND MATCH.OR..Many Many match.
In that case the statements are very complex, and the performance is not high probably.

thanks.

**Comment by seut** [comment]
See the documentation of the `match` predicate https://crate.io/docs/crate/reference/en/latest/general/dql/fulltext.html, specially description of the `query_term` argument and `operator` option.
