### ISSUE TITLE
Http status page

### ISSUE THREAD

**Issue by marksugar** [crate/crate#9005]
In my environment I use the cratedb 2.0 version.
Program monitoring is done by monitoring port 4200. But this is not ideal. CrateDB Admin Ui is normally good to use.
But in many scenarios, you only need to monitor status information instead of CrateDB Admin Ui.
When I tried to get from the `curl http://hostIP:4200` port, I only returned a simple page.
```
[root@node ~]# curl http://IP:4200/?nodes
{
  "ok" : true,
  "status" : 200,
  "name" : "crate_node_3",
  "cluster_name" : "his321tory_bet_cluster",
  "version" : {
    "number" : "2.1.8",
    "build_hash" : "####################",
    "build_timestamp" : "2017-10-12T12:37:43Z",
    "build_snapshot" : false,
    "es_version" : "5.4.3",
    "lucene_version" : "6.5.1"
  }
}
```

Is there a possibility to get some resource information in CrateDB Admin Ui by `curl http://hostIP:4200`?
For example: Cluster health status, number of nodes, additions, deletions, and changes！
thanks

**Comment by mfussenegger** [comment]
Not sure what you mean with `additions, deletions and changes`. 

In later version of CrateDB you could query `sys.health` and `sys.nodes`, depending on what exact data you want. E.g. something like:

```
SELECT
  (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health,
  (SELECT sum(missing_shards) FROM sys.health) AS missing_shards,
  (SELECT count(*) FROM sys.nodes) AS num_nodes;
```

```
curl -XPOST localhost:4200/_sql -d "$(mkjson stmt="'SELECT (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health, (SELECT sum(missing_shards) FROM sys.health) AS missing_shards, (SELECT count(*) FROM sys.nodes) AS num_nodes;'")"
```

**Comment by marksugar** [comment]
Sql at CrateDB Admin Ui is ok 

at use `curl -XPOST 127.0.0.1:4200/_sql`error

```
[root@node /data]# curl -XPOST localhost:4200/_sql -d "$(mkjson stmt="'SELECT (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health, (SELECT sum(missing_shards) FROM sys.health) AS missing_shards, (SELECT count(*) FROM sys.nodes) AS num_nodes;'")"
-bash: mkjson: command not found
{"error":{"message":"SQLActionException[SQLParseException: Missing request body]","code":4000}}
```

```
[root@node /data]# curl -XPOST 127.0.0.1:4200/_sql -d stmt=$"("'SELECT (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health,(SELECT sum(missing_shards) FROM sys.health) AS missing_shards,(SELECT count(*) FROM sys.nodes) AS num_nodes;'")"
{"error":{"message":"SQLActionException[SQLParseException: Failed to parse source [stmt=(SELECT (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health,(SELECT sum(missing_shards) FROM sys.health) AS missing_shards,(SELECT count(*) FROM sys.nodes) AS num_nodes;)]]","code":4000}}
```

  
  
Community edition:

```
[root@node /data]# curl -XPOST '127.0.0.1:4200/'
{
  "ok" : true,
  "status" : 200,
  "name" : "crate_node_1",
  "cluster_name" : "history_bet_cluster",
  "version" : {
    "number" : "4.0.3",
    "build_hash" : "1b7058faxxxxxx63c105c202f3",
    "build_timestamp" : "2019-08-09T01:20:38Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0"
  }
}
```  
  
My intention is to discuss whether a separate status page can be provided.
The status page contains, cluster information, real-time sql information statistics.
Finally, the information of the status page is captured for CrateDB monitoring.

**Comment by mfussenegger** [comment]
The correct curl call would be:

```
curl -XPOST localhost:4200/_sql -d '{"stmt":"SELECT (SELECT health FROM sys.health ORDER BY severity DESC LIMIT 1) AS health, (SELECT sum(missing_shards) FROM sys.health) AS missing_shards, (SELECT count(*) FROM sys.nodes) AS num_nodes;"}'
```

> My intention is to discuss whether a separate status page can be provided.
The status page contains, cluster information, real-time sql information statistics.

We currently have no intention to provide a separate status page. We recommend to either use SQL in some form to get the required information or to use JMX (enterprise edition).

Some monitoring systems provide ways to get metrics using SQL, e.g. for prometheus there is https://github.com/justwatchcom/sql_exporter and https://github.com/free/sql_exporter

**Comment by marksugar** [comment]
understand
Thanks
