### ISSUE TITLE
Distributed Systems Tests

### ISSUE THREAD

**Issue by bytearchive** [crate/crate#9015]
Do you know about Kyle Kingsbury

Can you have Kyle Kingsbury (https://aphyr.com/about) do a test on your system using https://jepsen.io/analyses.

I am only using the services that he has passed.

**Comment by mfussenegger** [comment]
Kyle did a test of CrateDB a while back, since then we've fixes some of the issues found. There is a [resiliency](https://crate.io/docs/crate/guide/en/latest/architecture/resilience.html#known-issues) page where you can find the known-issues / latest state)
