### ISSUE TITLE
Match predicate does not work when table alias used

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9041]
**CrateDB version**: 4.0.3

**Problem description**:
Fulltext search failed when table alias used.
In 3.3.5 this request executes successfully.

**Steps to reproduce**:

`create table doc.test (keywords TEXT INDEX USING FULLTEXT WITH (analyzer = 'standard'));`
`>> Table DOC.TEST created.`

`SELECT * FROM doc.test c where match(c.keywords, 'a') ;`
**`>> ERROR: UnhandledServerException: java.lang.UnsupportedOperationException: Can't build query from symbol MATCH{Field{AliasedAnalyzedRelation{qualifiedName=c, relation=DocTableRelation{doc.test}}.keywords, pointer=Field{DocTableRelation{doc.test}.keywords, pointer=Reference{ident=<RefIdent: doc.test->keywords>, granularity=DOC, position=1, default expression=null, type=text, index type=ANALYZED, nullable=true, columnstore enabled=false}}}}`**

`SELECT * FROM doc.test where match(keywords, 'a') ;`
`>>(request successfull)`

**Comment by mfussenegger** [comment]
Thank you for reporting.

We've a fix for this pending (https://github.com/crate/crate/pull/9047) which will be released with 4.0.4
