### ISSUE TITLE
number precision limit 

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#9044]
**Use case**:
User should be able control the limit of the number of  precision. i.e if i have select query which has decimal number let say 4.02023365122 than it would be  allow to limit 2 or 3 precision like 4.02

**Feature description**:

**Comment by mfussenegger** [comment]
You could use the [format](https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html?highlight=format#format-format-string-parameter-parameter) function for that:

```
select format('%.2f', 4.02023365122);                                                      
+-------------------------------+
| format('%.2f', 4.02023365122) |
+-------------------------------+
| 4.02                          |
+-------------------------------+
``` 

```
select format('%.2f', 4.02023365122)::double;                                              
+-----------------------------------------------+
| CAST(format('%.2f', 4.02023365122) AS double) |
+-----------------------------------------------+
|                                          4.02 |
+-----------------------------------------------+
```

**Comment by bhagujava** [comment]
Thanks for solution. Need to improve document which can show  possible example to use with function
