### ISSUE TITLE
How often do we upgrade the version of ElasticSearch?

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9054]
**Problem description**:

May I ask a question? How often do we upgrade the version of ElasticSearch? In other words, what conditions are met and we will upgrade ElasticSearch?

And why not plug-in to support ElasticSearch so that we can support access to external ElasticSearch clusters?

**Comment by mfussenegger** [comment]
Starting with 4.0 we won't upgrade ES anymore at all. We've integrated the code we used and removed everything else (so only about 1/3rd, maybe a bit more, of ES is left). This makes it easier for us to adapt pieces to our requirements.

We're occasionally cherry-picking individual changes from upstream that still make sense for us. But that is mainly focused on the networking / clustering layer.

**Comment by asdf2014** [comment]
@mfussenegger Thanks for your comments. It's very helpful to me.

**Comment by mfussenegger** [comment]
> And why not plug-in to support ElasticSearch so that we can support access to external ElasticSearch clusters?

If this is about being able to run queries against a remote ES cluster, you
might want to create another issue as a feature request.

Other SQL DBs have the concept of remote servers. In our case it would be
feasible to add arbitrary servers as long as there is a JDBC driver available.
Given that ES has also added SQL, that might then be an option to run queries
against a remote ES cluster.

But it's currently not high on our priority list.


Given that the initial question is answered I'm closing this.

**Comment by asdf2014** [comment]
@mfussenegger Thanks again. As you said, I raised a new feature request in https://github.com/crate/crate/issues/9065 .
