### ISSUE TITLE
Support a plug-in approach to plug in existing ElasticSearch clusters

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9065]
**Use case**:
In the case of an existing ElasticSearch cluster, if we can connect CrateDB directly to an existing ElasticSearch cluster, we will reduce the cost of maintenance.

**Feature description**:
CrateDB should support a plug-in approach to plug in existing ElasticSearch clusters and be as compatible as possible with more ElasticSearch versions.

**Comment by mfussenegger** [comment]
This is also somewhat related to https://github.com/crate/crate/issues/8914
