### ISSUE TITLE
Concatenate function does not cast non-string columns to string in some cases

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9067]
**CrateDB version**: tested on 3.3.5 and 4.0.4

**Steps to reproduce**:
`create table test (a string, b int);`
`>>  CREATE TABLE OK, 1 row affected (0.793 sec)`
`insert into test (a, b) values ('x', 1);`
`>>  INSERT OK, 1 row affected (0.023 sec)`

`select a || b from test`
**`>> SQLActionException[SQLParseException: Cannot cast 'x' to type integer]`** (expected result: string **x1**)

`select b || 2 from test`
`>> (select ok, result '12')`

`select b || a from test`
**`>> SQLActionException[SQLParseException: Cannot cast 'x' to type integer]`** (expected result: string **1x**)

`select b || 5 || a from test`
`>> (select ok, result '15x')`

`select a || 5 || b from test`
**`>> SQLActionException[SQLParseException: Cannot cast 'x5' to type integer]`** (expected result: string **x51**)

**Comment by shm-dmitry** [comment]
Workaround:
`select a || cast(b as string) from test`

**Comment by mfussenegger** [comment]
Thank you for the report.

We're making a change so that implicit casts work in the future (4.1) (https://github.com/crate/crate/pull/9074)
