### ISSUE TITLE
crate vs greenplum

### ISSUE THREAD

**Issue by cmdares** [crate/crate#9069]
What are the performance advantages？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joemoe** [comment]
hi @cmdares, we don't have any benchmarks for this tool yet.
greenplum looks like a fantastic product. given the architecture i assume cratedb is faster at doing writes and aggregations. but this is an assumption. for a profound answer we would need to do a proper benchmark. when talking to users and potential users  greenplum wasn't mention to often. if you will gather any insights we are happy to learn about them.
i'm closing this issue as we are using github to track issues with our product cratedb.
thanks, joe
