### ISSUE TITLE
Connecting CrateDB with PowerBI for Direct Query

### ISSUE THREAD

**Issue by Georger2323** [crate/crate#9080]
[I posted my question on Power BI](https://community.powerbi.com/t5/Desktop/Direct-Query-for-PostgreSQL/m-p/777336#M374448), with no results. 

That's why I am asking it here as well maybe there's a workaround solution for this issue. If you check the post I created on power bi you can see the supported data sources for direct query, and I was wondering if I can somehow move the data from Crate to a supported DB for direct query?

Thank you.

**Comment by seut** [comment]
@Georger2323 
As this is a PowerBI client issue, there is nothing which could be done at CrateDB.
Did you try out https://github.com/sgoley/DirectQuery-for-ODBC-in-PowerBI?
