### ISSUE TITLE
Why the health status of the instance is not recorded in the sys.health table

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9084]
**CrateDB version**:
4.0.4

**Environment description**:

Standalone CrateDB instance on MacOS

**Problem description**:

![image](https://user-images.githubusercontent.com/8108788/63917116-7897be00-ca6c-11e9-8b5f-21ff66afaf84.png)

After the CrateDB is started, the health status of the instance is not recorded in the `sys.health` table, but the `Health` flag is still visible on the Admin UI.
Want to know if this is a special treatment for the stand-alone version, or is there any other way to judge the health status of the instance?

**Steps to reproduce**:

```sql
SELECT health FROM sys.health limit 1;
```

**Comment by seut** [comment]
@asdf2014 
While querying the `sys.health` table, internally it will issue this statement:
```
select table_name, schema_name, partition_ident, routing_state, \"primary\", relocating_node, count(*)
 from sys.shards 
 group by 1, 2, 3, 4, 5, 6;
```

When a cluster is started, cluster/shard recovery may not already be done when this query will be fired. The AdminUI is currently not using the `sys.health` table but the underlaying statement, so its more a timing issue. The AdminUI query was sent after the recovery was done while the manual query against `sys.health` may not.

**Comment by asdf2014** [comment]
@seut SGTM. Thanks a lot.

![](https://user-images.githubusercontent.com/8108788/63927747-e51cb800-ca80-11e9-997f-e6a16adc2da9.png)

**Comment by seut** [comment]
Good to hear, I'll close this then.
