### ISSUE TITLE
Post Twitter Authentication Issue

### ISSUE THREAD

**Issue by iambudi** [crate/crate#9095]
**CrateDB version**:
4.0.4

**Environment description**:
MacOS Mojave
 - JVM version: java -version 
```
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
 - Kernel: uname -a
```
Darwin mbp.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
 - Distribution: cat /etc/os-release
 - Number of nodes; Please mention special master/data/client node configuration
0

**Problem description**:
After Authorizing Twitter `Authorize CrateDB to access your account?` for Twitter Sample Data, redirecting to page `http://127.0.0.1:4200/?start_twitter=true` gives message `Requested file [/Users/iambudi/Applications/crate-4.0.4/lib/site/?start_twitter=true] was not found` 

**Steps to reproduce**:
Go to Help Page, and press Import Tweet for Testing button and follow the Authorization screen.

**Comment by m-kharbat** [comment]
Thank you for reporting, the issue has been fixed.
