### ISSUE TITLE
Debian Buster 10 release?

### ISSUE THREAD

**Issue by electic** [crate/crate#9129]
Are there any plans to release a distribution for Debian 10 buster? The site:

https://cdn.crate.io/downloads/apt/stable 

only seems to have up to 9.

**Comment by electic** [comment]
So it also seems to not work on Debian 9 either because it is expecting a higher version of JRE which you don't get from the default JRE installation from APT.

**Comment by mfussenegger** [comment]
Debian 9 requires to install JDK 11 from another repo. E.g.:

```
echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee /etc/apt/sources.list.d/stretch-backports.list
sudo apt-get -y update
sudo apt-get -y install openjdk-11-jre-headless curl
```

We're going to integrate Debian 10 into our release pipeline as well.

**Comment by mfussenegger** [comment]
We've extended our release pipeline. We're now also building packages for Debian Buster starting with CrateDB 4.0.6 (which is already available in the testing channel).
