### ISSUE TITLE
Cannot connect to CrateDB using JDBC driver

### ISSUE THREAD

**Issue by yuemingl** [crate/crate#9132]
**CrateDB version**:
Don't know. I use the shell command:
bash -c "$(curl -L https://try.crate.io/)"

**Environment description**:
MacOS

 - JVM version: java -version 
java version "11.0.4" 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)

**Problem description**:

JDBC driver reports:
Cannot connect to the database: FATAL: role "crate" does not exist

**Steps to reproduce**:

I used go pgx and java jdbc drivers. Both of them report the same error.

**Comment by seut** [comment]
For JDBC, please ensure that your using crate-jdbc, see https://crate.io/docs/crate/getting-started/en/latest/start-building/index.html. Other then that, more details like connection config would be required to help you, our community discourse is the right place for asking for support see https://community.crate.io/.

**Comment by yuemingl** [comment]
Figured out the problem now. I have Postgres installed and the port 5432 is used. CrateDB used port 5433 instead.
