### ISSUE TITLE
Subselect does not work when table alias used

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9158]
**CrateDB version**: 4.0.5

**Problem description**:
Exception raised when table alias used with sub-select query.
Also tested on 3.3.5 - all works fine.

**Steps to reproduce**:
`create table test (a int);`
`>> Table TEST created.`

`create table test1 (b int, c int);`
`>> Table TEST1 created.`

`select (case when t.a in (select b from test1 where c = 1) then 1 else 0 end) as fav from test t`
**`ERROR: UnsupportedFeatureException: Can't handle Symbol SelectSymbol{integer_array}`**

`select (case when a in (select b from test1 where c = 1) then 1 else 0 end) as fav from test ;`
`>> (successfull)`

**Comment by mfussenegger** [comment]
Thank you for the bug report.

It looks like we've fixed this already in master, but we're missing a backport to 4.0 for the change that fixes this.
We'll look into it.

**Comment by kovrus** [comment]
@shm-dmitry Thank you for reporting the bug. The fix will be available in the upcoming `4.0.6` hot fix release.
