### ISSUE TITLE
Feature Request: Querying of IP fields via CIDR notation

### ISSUE THREAD

**Issue by robd003** [crate/crate#9210]
**Use case**: Currently the IP field doesn't accept CIDR notation queries and only works when querying from distinct ip addresses. ElasticSearch does this just fine and I think it'd be pretty easy to port over the functionality: https://www.elastic.co/guide/en/elasticsearch/reference/current/ip.html

**Feature description**: Being able to filter a set of IP addresses by CIDR mask is a lot more efficient than having to do a long WHERE (ip = '1.1.1.1' or ip = '1.1.1.2' or ip = '1.1.1.3'...) clause including each IP address that exists in the block.

Steps to reproduce:
CREATE TABLE test ( "ip_addr" IP );
INSERT INTO TABLE test ("ip_addr") VALUES ('192.168.1.1', '10.0.0.1', '192.168.1.20', '8.8.8.8');
SELECT ip_addr FROM test WHERE ip_addr = '192.168.1.0/24';

**Comment by mfussenegger** [comment]
Thank you for the suggestion.

The problem this doesn't work already is that our `EqOperator` (`=`) forces both operands to be of the same type. So we try to cast `192.168.1.0/24` to an IP which fails.

The `EqQuery` implementation itself would generate the correct lucene query and match correctly. But we'd also have to add a non-lucene query variant for `ip = string`.

A potential solution for this is to extend the `EqOperator` with a dedicated overload for `ip, string` arguments.

**Comment by mfussenegger** [comment]
Test case I used (for later pick-up):

```
+public class EqQueryTest extends CrateDummyClusterServiceUnitTest {
+
+    @Test
+    public void test_ip_column_can_be_queried_using_cidr_notation() throws Throwable {
+        QueryTester.Builder builder = new QueryTester.Builder(
+            createTempDir(),
+            THREAD_POOL,
+            clusterService,
+            Version.CURRENT,
+            "create table t (ip_addr ip)"
+        );
+        builder.indexValues("ip_addr", "192.168.1.1", "192.168.1.8", "10.0.0.1", "1.1.1.1");
+        try (QueryTester tester = builder.build()) {
+            assertThat(
+                tester.runQuery("ip_addr", "ip_addr = '192.168.1.0/24'"),
+                contains(
+                    "192.168.1.1",
+                    "192.168.1.8"
+                )
+            );
+        }
+    }
+}
```

**Comment by marregui** [comment]
Hey @robd003 

I hope all is well. Just an update, your request is implemented and the PR is in pretty good shape, however we might expose this functionality via `>>=` and related operators, for compatibility with postgresq (https://www.postgresql.org/docs/current/functions-net.html), no promises here, it will be discussed, decided. In any case you will get something useful merged to master within October. 

Do you have a cool use case?, do you store the ips to track connections to your voice service?, you store lots of data?, own cluster?, let me know, I am curious.

Have a great weekend,

**Comment by marregui** [comment]
Hi @robd003 

We have just merged https://github.com/crate/crate/pull/9218 which gives you the ``<<`` operator, to achieve exactly what you describe. 

We will leave the case open for a few days and then will consider it closed.

Best regards,
