### ISSUE TITLE
Feature request: calculate area of geo shape

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9231]
**Use case**:
I have a few overlapping geo shapes. 
I want to find the smallest of them.
This function can return an approximate result with some accuracy.

**Feature description**:
```
FUNCTION calculate_geo_area(shape: geo_shape) : double
```

```
SELECT *, calculate_geo_area(t.shape) as area
FROM tbl t
WHERE match(t.shape, 'POINT(1.1 2.2)') 
ORDER BY calculate_geo_area(t.shape) ASC
```

**Comment by seut** [comment]
@shm-dmitry The requested feature was just merged and will be released with our next feature release, probably 4.7.
Thank you for suggesting it.
