### ISSUE TITLE
Drop sub-column from dynamic column

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9238]
**Use case**:

As more points are written, if we can't remove a sub-column from a dynamic column, it will cause the entire dynamic column to contain too many sub-columns.

Related to https://github.com/crate/crate/issues/4457

**Feature description**:

Drop sub-column from dynamic column.

**Comment by BaurzhanSakhariev** [comment]
Implemented in https://github.com/crate/crate/pull/14824 and will be available in 5.5.0 release.

Data deletion is tracked by https://github.com/crate/crate/issues/14254.

**Comment by asdf2014** [comment]
> Implemented in #14824 and will be available in 5.5.0 release.
> 
> Data deletion is tracked by #14254.

@BaurzhanSakhariev What wonderful news! :smile:
