### ISSUE TITLE
JDBC Duplicates

### ISSUE THREAD

**Issue by bputt** [crate/crate#9265]
Looking for clarification on the JDBC driver as we want to make sure we're accounting for errors / dups accordingly.

When using BULK prepared statement operations, when looking at the rows coming back, this is our current logic, the question is are we correctly accounting for what the row's value will be?

```
Arrays.stream(rows).forEach(i -> {
    if (i >= 1) incrementSuccess();
    else if (i == 0) incrementDuplicates();
    else if (i == java.sql.PreparedStatement.SUCCESS_NO_INFO) incrementSuccess();
    else if (i == java.sql.PreparedStatement.EXECUTE_FAILED) incrementFailures();
    else incrementFailures();
});
```

**Comment by seut** [comment]
Yes this look accurate, although the row count could be 0 for other reasons like: no document found.

I've also added this answer to your community post which is the right place for such questions.
