### ISSUE TITLE
geo-polygon-query

### ISSUE THREAD

**Issue by cmdares** [crate/crate#9289]
**Use case**:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-polygon-query.html

*****A query returning hits that only fall within a polygon of points. Here is an example:
GET /_search
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "geo_polygon" : {
                    "person.location" : {
                        "points" : [
                            {"lat" : 40, "lon" : -70},
                            {"lat" : 30, "lon" : -80},
                            {"lat" : 20, "lon" : -90}
                        ]
                    }
                }
            }
        }
    }
}
**Feature description**:
how to do the geo-polygon-query in cratedb?
thanks.

**Comment by mfussenegger** [comment]
Did you have a lookt at our [Geo search](https://crate.io/docs/crate/reference/en/latest/general/dql/geo.html?highlight=match#match-predicate) documentation?
