### ISSUE TITLE
SHOW CREATE TABLE SqlException with TIMESTAMP WITHOUT TIME ZONE

### ISSUE THREAD

**Issue by heyoka** [crate/crate#9311]
**CrateDB version**: 4.0.4

**Environment description**:

Crate DB on single node Docker (vs. 18.06.1-ce) running on Ubuntu 18.04 VM

**Problem description**:

SHOW CREATE TABLE returns the following error, when used on a  table, that has a TIMESTAMP WITHOUT TIME ZONE field:
`SQLActionException[SQLParseException: line 1:14: mismatched input 'without' expecting {<EOF>, '[', 'OR', 'AND', 'IN', 'NOT', 'BETWEEN', 'LIKE', 'IS', '=', NEQ, '<', '<=', '>', '>=', '~', '!~', '~*', '!~*', '+', '-', '*', '/', '%', '||', '::'}]`
The created table can be used normally, I can insert, query, update.

**Steps to reproduce**:
Create table like so:
`CREATE TABLE create_test2 (
    ts TIMESTAMP WITHOUT TIME ZONE,
    ts_hour TIMESTAMP WITHOUT TIME ZONE DEFAULT date_trunc('hour', CURRENT_TIMESTAMP),
    id STRING,
    vst INT,
    dif STRING,
    topic STRING,
    data_obj OBJECT
) PARTITIONED BY (ts_hour);`
then
`SHOW CREATE TABLE create_test2` 
gives the error.
If I create the table with TIME ZONE, the SHOW CREATE TABLE query works, but this is not what I want.

**edit**:
actually the line:
`ts_hour TIMESTAMP WITHOUT TIME ZONE DEFAULT date_trunc('hour', CURRENT_TIMESTAMP)`
is what seems to cause the error

**Comment by seut** [comment]
@heyoka Thanks for reporting, we'll have a look into this. Indeed it seems to be a bug related to using `TIMESTAMP WITHOUT TIME ZONE` in conjunction with a `DEFAULT` expression.

**Comment by seut** [comment]
@heyoka We've solved this, the fix will be part of the next 4.0 hotfix release.
Thanks again for reporting.
