### ISSUE TITLE
Array comparison parameter

### ISSUE THREAD

**Issue by OJFord** [crate/crate#9313]
**Use case**:
Use [array comparison (`WHERE IN`)](https://crate.io/docs/crate/reference/en/4.0/general/builtins/array-comparisons.html#sql-array-comparisons) in conjunction with [parameter references](https://crate.io/docs/crate/reference/en/4.0/sql/general/value-expressions.html#parameter-reference)

**Feature description**:

Presently:
```sql
select * from tbl where "id" in ?
```

with an array given as parameter results in:
> SQLActionException[SQLParseException: line n:m : no viable alternative at input

I couldn't find any mention of how else this should be done (such as numbered `${1..10}` and passing scalars only, not an array) in the docs, so I assume it's a feature request.

**Comment by mfussenegger** [comment]
You could use 

```
select * from tbl where id = ANY(?)
```

**Comment by seut** [comment]
Also one could use

```
select * from tbl where id in (select col1 from unnest(?))
```
