### ISSUE TITLE
Column unknown exception raised from ON CONFLICT statement when column name in upper case 

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9332]
**CrateDB version**: 4.0.7

**Problem description**:
Exception 'ERROR: ColumnUnknownException: Column ... unknown' raised from `ON CONFLICT (..) DO UPDATE SET` when column name wrote in upper case.

**Steps to reproduce**:
`create table test (a int, b int, primary key(a)) ;`
`>> Table TEST created.`

`insert into test (a, b) values (1, 2) ON CONFLICT (A) DO UPDATE SET b = excluded.b`
**`>> ERROR: ColumnUnknownException: Column A unknown`**

`insert into test (a, b) values (1, 2) ON CONFLICT (a) DO UPDATE SET b = excluded.b`
`>> 1 row inserted.`

**Comment by mkleen** [comment]
Thank you for reporting, I created a fix for that.

**Comment by mfussenegger** [comment]
Closing this, the fix will be released as part of 4.0.9. (https://github.com/crate/crate/pull/9352)
