### ISSUE TITLE
Can i get the timestamp when a record is stored?

### ISSUE THREAD

**Issue by AngeloIapichino** [crate/crate#9361]
Hi guys, 
for benchmark purpose i need to measure the delay between the write request and effectively "landing" on the database.

Is it possible?

I have already a timestamp column that represent the write request timestamp (i use a python script to do that)

Thanks in advance

**Comment by seut** [comment]
I think using a generated column using `CURRENT_TIMESTAMP` will suit your needs.
Example:
```
CREATE TABLE t1 (ts TIMESTAMP, ts_internal TIMESTAMP AS CURRENT_TIMESTAMP);
```

If this suggestion doesn't work for you, you are very welcomed to open a discussion at https://community.crate.io. 
We use the issue tracker exclusively for bug reports and feature requests.
