### ISSUE TITLE
Unusually large snapshots size

### ISSUE THREAD

**Issue by kunz07** [crate/crate#9373]
**CrateDB version**:
v3.3.4

**Environment description**:
**JVM version**
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

**Kernel**
Linux chiphub 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Distribution**
18.04.3 LTS (Bionic Beaver)

**Problem description**:

I have setup a python script which creates a crate db snapshot everyday at noon. The query I ran to initially setup the repo is:
`CREATE REPOSITORY repo_name TYPE FS WITH (LOCATION='/path/to/folder', compress=true);`
The query I run everyday in order to create the snapshot is:
`CREATE SNAPSHOT repo_name.{} ALL WITH (wait_for_completion=true, ignore_unavailable=true);`
On the initial run, the snapshot directory size was same as the database size (30GB).
After about a month, the database has grown to 40GB while the snapshot directory size has grown to ~120GB (almost thrice the size of the database!).
Is this normal?
If yes, are there any options/optimizations I can try out to reduce the size of the snapshots?

**Comment by marregui** [comment]
Hi @kunz07 ,

With compression true, each full snapshot would be around 1/3 to 1/4 of the size of the original data. 
What kind of data do you have?, how is it updated?
What does the python script do exactly?
What other snapshots are happening, if any?
What does `select * from sys.snapshots` report?
Do you still have this issue?
Would you consider upgrading to version 4.x?

Best regards,

**Comment by kunz07** [comment]
Hello @marregui 

Thanks for the reply!

1. There are around 20 tables which do not have much data and take up negligible space. 
I do have 1 table with an `array(float)` column, which takes up most of the space. There are ~10 inserts/min into this table. Each insert has around 50kb of data. There are no updates which happen to this table, just 1 time inserts.

2. The python script just creates a snapshot everyday at a configured time.
```
from crate import client
from contextlib import contextmanager
import datetime

@contextmanager
def dbCursor():
    try:
        conn = client.connect('localhost:4200')
        cursor = conn.cursor()
        yield cursor
    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    try:
        timestamp = datetime.datetime.now()
        snapshot_name = 'cratesnap_' + timestamp.strftime('%Y%m%d%H%M%S')
        print('initiated snapshot at ' + timestamp.strftime('%Y-%m-%dT%H:%M:%S'))
        sql = "CREATE SNAPSHOT crunch.{} ALL WITH (wait_for_completion=true, ignore_unavailable=true);".format(snapshot_name)
        print('executed query is: ' + sql)
        with dbCursor() as cursor:
            cursor.execute(sql)
        end_ts = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
        print('snapshot successfully created at ' + end_ts)
    except Exception as e:
        print(str(e))
```

3. There are no other snapshots happening.

4. There is a `success` state for each of the snapshosts.
```
cr> select * from sys.repositories;
+--------+-------------------------------------------------------------------+------+
| name   | settings                                                          | type |
+--------+-------------------------------------------------------------------+------+
| crunch | {"compress": "true", "location": "/path/to/backup_folder/"}       | fs   |
+--------+-------------------------------------------------------------------+------+

cr> select * from sys.snapshots;
+-------------------------------+---------------+---------------------------+------------+---------------+---------+---------+
| concrete_indices              |      finished | name                      | repository |       started | state   | version |
+-------------------------------+---------------+---------------------------+------------+---------------+---------+---------+
| [list of tables...  ]         | 1564381808612 | crunchsnap_20190729120001 | crunch     | 1564381801803 | SUCCESS | 6.5.1   |
| [list of tables...  ]         | 1564468212075 | crunchsnap_20190730120002 | crunch     | 1564468202094 | SUCCESS | 6.5.1   |
| [list of tables...  ]         | 1564554610453 | crunchsnap_20190731120002 | crunch     | 1564554602140 | SUCCESS | 6.5.1   |
| [list of tables...  ]         | 1564641205943 | crunchsnap_20190801120001 | crunch     | 1564641001458 | SUCCESS | 6.5.1   |
| [list of tables...  ]         | 1564727415035 | crunchsnap_20190802120001 | crunch     | 1564727401293 | SUCCESS | 6.5.1   |
            .                           .                      .                  .              .            .         .
            .                           .                      .                  .              .            .         .
            .                           .                      .                  .              .            .         .
+-------------------------------+---------------+---------------------------+------------+---------------+---------+---------+
```

5. Yes, I'm still facing this issue.

6. If the issue is resolved in 4.x, then would be open to upgrading.

Regards,
Kunal

**Comment by kunz07** [comment]
Hello @marregui 

Thanks for the reply!

1. There are around 20 tables which do not have much data and take up negligible space. 
I do have 1 table with an `array(float)` column, which takes up most of the space. There are ~10 inserts/min into this table. Each insert has around 50kb of data. There are no updates which happen to this table, just 1 time inserts.

2. The python script just creates a snapshot everyday at a configured time.
```
from crate import client
from contextlib import contextmanager
import datetime

@contextmanager
def dbCursor():
    try:
        conn = client.connect('localhost:4200')
        cursor = conn.cursor()
        yield cursor
    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    try:
        timestamp = datetime.datetime.now()
        snapshot_name = 'cratesnap_' + timestamp.strftime('%Y%m%d%H%M%S')
        print('initiated snapshot at ' + timestamp.strftime('%Y-%m-%dT%H:%M:%S'))
        sql = "CREATE SNAPSHOT repo_name.{} ALL WITH (wait_for_completion=true, ignore_unavailable=true);".format(snapshot_name)
        print('executed query is: ' + sql)
        with dbCursor() as cursor:
            cursor.execute(sql)
        end_ts = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
        print('snapshot successfully created at ' + end_ts)
    except Exception as e:
        print(str(e))
```

3. There are no other snapshots happening.

4. There is a `success` state for each of the snapshosts.
```
cr> select * from sys.repositories;
+-----------+-------------------------------------------------------------------+------+
| name      | settings                                                          | type |
+-----------+-------------------------------------------------------------------+------+
| repo_name | {"compress": "true", "location": "/path/to/backup_folder/"}       | fs   |
+-----------+-------------------------------------------------------------------+------+

cr> select * from sys.snapshots;
+-----------------------+---------------+---------------------------+---------------+---------------+---------+---------+
| concrete_indices      |      finished | name                      | repository    |       started | state   | version |
+-----------------------+---------------+---------------------------+---------------+---------------+---------+---------+
| [list of tables...  ] | 1564381808612 | cratesnap_20190729120001  | repo_name     | 1564381801803 | SUCCESS | 6.5.1   |
| [list of tables...  ] | 1564468212075 | cratesnap_20190730120002  | repo_name     | 1564468202094 | SUCCESS | 6.5.1   |
| [list of tables...  ] | 1564554610453 | cratesnap_20190731120002  | repo_name     | 1564554602140 | SUCCESS | 6.5.1   |
| [list of tables...  ] | 1564641205943 | cratesnap_20190801120001  | repo_name     | 1564641001458 | SUCCESS | 6.5.1   |
| [list of tables...  ] | 1564727415035 | cratesnap_20190802120001  | repo_name     | 1564727401293 | SUCCESS | 6.5.1   |
            .                           .                      .                  .              .            .         .
            .                           .                      .                  .              .            .         .
            .                           .                      .                  .              .            .         .
+-----------------------+---------------+---------------------------+---------------+---------------+---------+---------+
```

5. Yes, I'm still facing this issue.

6. If the issue is resolved in 4.x, then would be open to upgrading.

Regards,
Kunal

**Comment by marregui** [comment]
HJi @kunz07 ,

Bizarre, so far I have not managed to reproduce this issue, on your version 3.3.4.
I have done this, to try to understand what may be going wrong in your use case. 

1) I have created a fairly vanilla table "logs":

```
CREATE TABLE logs (
  log_time timestamp NOT NULL,
  client_ip ip NOT NULL,
  request string NOT NULL,
  status_code short NOT NULL,
  object_size long NOT NULL
)
```
2) I have a file called "bench2_500K.csv" which contains 500000 records, the first 5 lines of which look like this:

```
log_time,client_ip,request,status_code,object_size
2012-01-01T00:00:00Z,25.152.171.147,/books/Six_Easy_Pieces.html,404,271
2012-01-01T00:00:03Z,243.180.100.114,/slideshow/1.jpg,304,0
2012-01-01T00:00:03Z,149.60.38.76,/courses/cs100/finalprojects/adventure/javadocs_/index.html?index-filesindex-16.html,200,705
2012-01-01T00:00:10Z,243.180.100.114,/slideshow/2.jpg,304,0
2012-01-01T00:00:11Z,134.121.15.97,/courses/cs101/old/2002/syllabus.html,404,277
2012-01-01T00:00:17Z,243.180.100.114,/slideshow/3.jpg,304,0
...
```
3) I have a repo, like yours, but with a better name :) : `create repository crate_repo type fs with(location='/..../..../crate_repo', compress=true)`
 
4) `copy logs from 'file:///../../bench2_500K.csv';`
     `refresh table logs;`
     `create snapshot crate_repo.s1 all with (wait_for_completion=true, ignore_unavailable=true);`

5)  From terminal window, check the size on disk for both the **crate_repo** and **data** folders.

Repeat steps 4) to 5) eight times, each time changing the name of the snapshot s1..s8. This is my data:

|records| data size | snapshots size |
|--------|-----------|----------------|
| 500K    |  163M      |    52M                 |
| 1000K  |  362M     |  144M                |
| 1500K  |  561M      |   233M                |
| 2000K |  646M     |  298M                |
| 2500K |  790M     |  361M                |
| 3000K |  987M     |  448M                |
| 3500K |  1.1G        |  540M                |
| 4000K |  1.2G       |  622M                |
|--------|-----------|----------------|

In both cases, data and snapshot folders, I see linear growth, consistent with the increment in the data (which always comes in increments of 500K), and also, in this scenario, the snapshots take about 50% of the size of the original data (it cannot compress more).

Could I please see the `show create table` for the offending table?
Could you please dump about 5-10 rows into a csv file so that I can have a look?
Maybe there is something about the data, I just need more input to progress in my understanding. 

Best regards,

**Comment by kunz07** [comment]
Hey @marregui 

Appreciate the quick response! :)

Yes, the procedure you have done is similar to my setup.

Here is the table schema you requested
```
CREATE TABLE "test_table" (
    "m_id" STRING,
    "p_timestamp" TIMESTAMP,
    "p_value" ARRAY(FLOAT)
);
```

I have attached the test_data.json here [https://gist.github.com/kunz07/82b990f1e282b05887aee713befe09ed](url)

Regards,
Kunal

**Comment by marregui** [comment]
Hey @kunz07 

Ok, I think I have a picture of what is going on,

1) You have an index on **test_table** (you know, one or more shards, where each shard contains one or more segments - a segment being the storage unit. This information is available when you run `show create table test_table`)
2) You make a snapshot (all the segments of the index are saved into the repo)
3) You bang out a further 700MB worth of data the next day, which results in the index to evolve, with segment merges occurring, new segments being created
4) You make a new snapshot. All the segments which exist in the repo at this moment, do remain there. The new segments from the index are copied into the repo, no merge happens at this end. Result, you have duplicated data in the repo

What to do?. What I would do is to delete that repository, create a new one, and make the first snapshot. Tomorrow at noon, your python script will create a new snapshot, it should delete the previous one (today's) once this has happened. I assume you are simply trying to have a backup of the database. 

If your setup can afford it, maybe OPTIMIZE the index prior to taking the snapshot (https://crate.io/docs/crate/reference/en/latest/sql/statements/optimize.html?highlight=optimize).

I would encourage you to upgrade to the latest major version, which will give you a great use case while you are testing the snapshots (https://crate.io/docs/crate/reference/en/latest/appendices/release-notes/4.0.10.html).

Under the hood, what is valid for ES, is usually valid for CrateDB, please have a look at:

- https://discuss.elastic.co/t/backup-repository-size-is-much-bigger-than-indices-size/47469
- https://www.elastic.co/blog/found-elasticsearch-snapshot-and-restore

What is all this data?, a cool personal project ?

Best regards,

**Comment by mfussenegger** [comment]
To append on what @marregui already mentioned:

Snapshots are incremental and if you keep all the snapshots you could also restore an earlier snapshot, that's why it needs to keep the data around.

Instead of creating a new repository an alternative is to use `DROP SNAPSHOT` on older snapshots, so that files that become unreferenced can be cleaned up.

**Comment by marregui** [comment]
Hi @kunz07 

All good?, if you are happy with the answer, would you please close the issue.
If you have more issues do not hesitate to contact us!

Best regards,

**Comment by kunz07** [comment]
Hey @marregui @mfussenegger,

Apologies for the delayed response.
Thanks a lot for your inputs. I'll fine-tune my python script to delete the prior snapshots once a new one is created as suggested and see how it goes. Will reopen in case I run into the issue again.

Regards,
Kunal
