### ISSUE TITLE
ALTER TABLE failed when primary key with nested object column used

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9386]
**CrateDB version**: 4.0.7

**Problem description**:
ALTER TABLE ADD COLUMN failed when table contains PRIMARY KEY, created from object nested columns.

**Steps to reproduce**:

`create table test (pk object as (a int, b int), primary key (pk['a'], pk['b']));`
`> Table TEST created.`

`alter table test add x int;`
**`ERROR: SQLParseException: column "pk" specified more than once`**

**Comment by mfussenegger** [comment]
Thank you for the bug report. We've a fix which will be part of `4.0.10`
