### ISSUE TITLE
Feature request: new operator matches empty objects

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9398]
**Use case**:
I have ARRAY column with some data.
Some rows contains empty array `[]` , some rows contains `null`
I want to find both.
At now I have to use query like `.... AND (column is NULL OR column = []) .....`.

**Feature description**:
New operator IS EMPTY, can be applied to column with any type:

1. `[] IS EMPTY == TRUE`
2. `NULL IS EMPTY == TRUE`
3. `{} IS EMPTY == TRUE`
4. `[123] IS EMPTY == FALSE`
5. `42 IS EMPTY == FALSE`
6. `{'x' = 42} IS EMPTY == FALSE`

Optional: if you can to check the full content of column to NULL - it will be perfect:
1. `[NULL, NULL, NULL] IS EMPTY == TRUE`
2. `{'x' = NULL, 'y' = {'z' = NULL}} IS EMPTY == TRUE`
3. `[NULL, {'a' = {'b' = NULL}}] IS EMPTY == TRUE`
4. `[NULL, {'a' = {'b' = 42}}] IS EMPTY == FALSE`

**Comment by seut** [comment]
Filter on empty arrays can be already done using the `array_length` scalar function, see https://crate.io/docs/crate/reference/en/latest/general/builtins/scalar.html#array-length-anyarray-dimension.
So your query would be: `... AND (column is NULL or array_length(column, 1) = 0) ... `

**Comment by seut** [comment]
Hm I'm wrong, `array_length` on an empty array returns `NULL`. Also the `IS NULL` predicate will match on empty arrays  as well.

**Comment by shm-dmitry** [comment]
@seut , ок, thank you

**Comment by mfussenegger** [comment]
Closing this given that there is a solution:

```
cr> create table tbl (id int primary key, xs int[]);
CREATE OK, 1 row affected  (0.482 sec)
cr> insert into tbl (id, xs) values (1, [1, 2, 3]), (2, null), (3, []);
INSERT OK, 3 rows affected  (0.072 sec)

cr> select * from tbl where xs is null or array_length(xs, 1) = 0;
+----+------+
| id | xs   |
+----+------+
|  3 | []   |
|  2 | NULL |
+----+------+
```

There is no need to add a specialized operator.

**Comment by amotl** [comment]
Hi,

for the sake of completeness, I would like to add a small thing to this discussion.

Coming from the other discussion at #12714, I figure that this would be the right expression to solve what @shm-dmitry was aiming for, specifically after this expression has been optimized with #12696.

```sql
select * from tbl where xs is null or xs = [];
```

With kind regards,
Andreas.
