### ISSUE TITLE
ARRAY function failed with NPE when object column returned in subquery

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9406]
**CrateDB version**: 4.0.9

**Problem description**:
Exception `ERROR: UnhandledServerException: java.lang.NullPointerException` raised when using array function with subquery returns object column from table

**Steps to reproduce**:
`create table test (x int);`
`>> Table TEST created.`

`insert into test (x) values (1);`
`1 row inserted.`

`select array(select {a = x} from test);`
**`ERROR: UnhandledServerException: java.lang.NullPointerException`**

`select array(select {a = 1} from test);`
`>> (success)`

`select array(select {a = 1} );`
`>> (success)`

**Comment by shm-dmitry** [comment]
Additional:
Sometimes I receive `ERROR: NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.NullPointerException`

**Comment by seut** [comment]
@shm-dmitry Thanks for reporting, we've identified the root cause and working on a fix.

**Comment by seut** [comment]
@shm-dmitry We've fixed this issue, it will be part of the upcoming 4.0.10 release.
Thanks again for reporting.
