### ISSUE TITLE
How can I setup the `index.merge.scheduler.max_thread_count` configuration?

### ISSUE THREAD

**Issue by asdf2014** [crate/crate#9475]
**CrateDB version**:

The latest CrateDB, last commit: https://github.com/crate/crate/commit/5173b655a9fbf72028876ae7b6eb5c4d2431e307

**Environment description**:

MacOS

**Problem description**:

Cannot set it by create or alter clause, nor can make it through modify crate.yml..

1. Invalid property "merge.scheduler.max_thread_count" passed to [ALTER | CREATE] TABLE statement
2. Index settings found. These have been unsupported since CrateDB 2.0 and should've been migrated.

**Comment by mfussenegger** [comment]
We currently don't expose that setting. Can you elaborate on 2) ? I think we never did expose it so I'm wondering how you were able to set it in the past. What version are you upgrading from and when were the tables created that have those settings?

**Comment by asdf2014** [comment]
Hi, @mfussenegger . Yes, it is true that this configuration item is not exposed in CreatDB, but there are a few scenarios where it needs to be configured. For example, a cluster that only has non-ssd type disk. May I ask why we do not expose these configuration items?

**Comment by mfussenegger** [comment]
No particular reason other than that we didn't have the requirement so far.

Due to 2) I was under the impression you're having an issue with this on an existing cluster. So this is not the cas?

We're happy to take a contribution that exposes the setting. (E.g. see https://github.com/crate/crate/commit/021335400b8dcfc6c797a7f29e3acf3da1da9f13 where we exposed a different setting to have an idea how to do that)

**Comment by asdf2014** [comment]
> Due to 2) I was under the impression you're having an issue with this on an existing cluster. So this is not the cas?

Yes, it's similar to that case.

> We're happy to take a contribution that exposes the setting.

Thanks. I raised up https://github.com/crate/crate/pull/9492, PTAL.

**Comment by asdf2014** [comment]
Closed by https://github.com/crate/crate/pull/9492
