### ISSUE TITLE
NPE rised when selecting data from view by timestamp column with CURRENT_TIMESTAMP function

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9476]
**CrateDB version**: 4.0.9

**Problem description**:

NPE raised when I query view with filter by timestamp column

**Steps to reproduce**:

`create table test (x timestamp, y int);`
`>> Table TEST created.`

`insert into test (x,y) values (current_timestamp, 1);`
`>> 1 row inserted.`

`select * from test where x > current_timestamp - 1000 * 60 * 60 * 24;`
`>> (success)`
`select * from test where y > 0;`
`>> (success)`

`create or replace view v_test as select * from test;`
`>> View VIEW created.`

`select * from v_test where x > current_timestamp - 1000 * 60 * 60 * 24;`
**`>> ERROR: UnhandledServerException: java.lang.NullPointerException`**
`select * from v_test where y > 0;`
`>> (success)`

**Comment by shm-dmitry** [comment]
Additional:
NPE raised only when `current_timestamp` function used.

**Comment by seut** [comment]
@shm-dmitry 
We've a fix in review which will be released with the next upcoming 4.0.11 hotfix release.
Thanks a lot for reporting.
