### ISSUE TITLE
SQLParseException raised when selecting data from view with group-by by nested field

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9477]
**CrateDB version**: 4.0.9

**Problem description**:
I cant group-by selected data from view when nested column used in GROUP BY statement

**Steps to reproduce**:
`create table test (x object as (a int));`
`>> Table TEST created.`

`create view v_test as select * from test;`
`>> View VIEW created.`

`select x['a'] from v_test;`
`>> (success)`

`select x['a'], count(*) from v_test group by x['a'];`
**`>> ERROR: SQLParseException: Couldn't find Field{AnalyzedView{qualifiedName=doc.v_test, relation=QueriedTable{DocTableRelation{doc.test}}}.x['a'], pointer=Field{QueriedTable{DocTableRelation{doc.test}}.x['a'], pointer=Field{DocTableRelation{doc.test}.x['a'], pointer=Reference{ident=<RefIdent: doc.test->x['a']>, granularity=DOC, position=null, default expression=null, type=integer, index type=NOT_ANALYZED, nullable=true, columnstore enabled=false}}}} in SourceSymbols{inputs={Field{AnalyzedView{qualifiedName=doc.v_test, relation=QueriedTable{DocTableRelation{doc.test}}}._fetchid, pointer=Field{QueriedTable{DocTableRelation{doc.test}}._fetchid, pointer=Reference{ident=<RefIdent: doc.test->_fetchid>, granularity=DOC, position=null, default expression=null, type=bigint, index type=NOT_ANALYZED, nullable=false, columnstore enabled=false}}}=IC{0, bigint}}, nonDeterministicFunctions={}}`**

**Comment by seut** [comment]
@shm-dmitry Thank you for reporting. We can reproduce it and are working on a fix.

**Comment by mfussenegger** [comment]
Thank you for the bug report.

We've a fix for this which we'll release with 4.0.12 and 4.1.1. 

But the way it is currently implemented the query on the view will have slower performance than the query on the table.

So

    select x['a'], count(*) from test group by x['a'];

will execute faster than

    select x['a'], count(*) from v_test group by x['a'];


We'll address this eventually, but it won't make it into 4.0 or even 4.1.
