### ISSUE TITLE
Can't add node to new crate cluster

### ISSUE THREAD

**Issue by patristein** [crate/crate#9501]
I am trying to create a new crate cluster with three nodes.

**Config of node:**

_gateway.expected_nodes: 3
gateway.recover_after_nodes: 2
network.host: _site_
discovery.seed_hosts:
    - srvccl02:4300
    - srvccl01:4300
cluster.initial_master_nodes:
    - srvccl01
    - srvccl02
auth.host_based.enabled: true
auth:
  host_based:
    config:
      0:
        user: crate
        address: _local_
        method: trust
      1:
        user: crate
        address: 172.30.99.99
        method: trust
      99:
        method: password
node.name: "srvccl01"_

For first test we installed two nodes with same config (instead ip ;) but it seems they are not talking to each other. Log files don't show anything about any failures. But output of "lsof -i" shows connections between these two nodes similar to this

_srvccl01:40014->srvccl02:4300 (ESTABLISHED)_

Did someone see any failures in my config or have a idea how to solve this? I am searching on this for days but can't find anything.

If I define different cluster names on these two nodes an error occur telling "_handshake failed, mismatched cluster name_". So it seems that the nodes are communicating. After setting cluster names to the same value again the message doesn't appear any more but in web GUI only one node is displayed. And if I try to add a new table to one node following error appears: MasterNotDiscoveredException: ClusterBlockException 

--------------------------------------------------------
**CrateDB version**: 4.0.10
**Environment description**: Ubuntu 18.04.3 (bionic)
 - JVM version: OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
 - Kernel: Linux srvccl01 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marregui** [comment]
Hi @patristein,

Must be down to config, here is an example setup to run 3 nodes as a cluster in your localhost.

Let's assume a root folder `/Users/marregui/workspace/mgbench/DATA`, which contains:

- ./data
- ./conf/n1/crate.yml
- ./conf/n1/log4j2.properties
- ./conf/n2/crate.yml
- ./conf/n2/log4j2.properties
- ./conf/n3/crate.yml
- ./conf/n3/log4j2.properties
- crate -> crate-4.1.0-SNAPSHOT-380f1d02f5

Where

**./conf/n1/crate.yml**

```
cluster.name: happy-ending
node.name: n1
stats.service.interval: 0
network.host: _local_
node.max_local_storage_nodes: 3

path.repo: /Users/marregui/workspace/mgbench/DATA/crate_repo
path.data: /Users/marregui/workspace/mgbench/DATA/data

http.cors.enabled: true
http.cors.allow-origin: "*"

transport.tcp.port: 4301
gateway.expected_nodes: 3
gateway.recover_after_nodes: 2
discovery.seed_hosts:
- 127.0.0.1:4301
- 127.0.0.1:4302
cluster.initial_master_nodes:
- 127.0.0.1:4301
- 127.0.0.1:4302
```

**./conf/n2/crate.yml**

```
cluster.name: happy-ending
node.name: n2
stats.service.interval: 0
network.host: _local_
node.max_local_storage_nodes: 3

path.repo: /Users/marregui/workspace/mgbench/DATA/crate_repo
path.data: /Users/marregui/workspace/mgbench/DATA/data

http.cors.enabled: true
http.cors.allow-origin: "*"

transport.tcp.port: 4302
gateway.expected_nodes: 3
gateway.recover_after_nodes: 2
discovery.seed_hosts:
- 127.0.0.1:4301
- 127.0.0.1:4302
cluster.initial_master_nodes:
- 127.0.0.1:4301
- 127.0.0.1:4302
```

**./conf/n3/crate.yml**

```
cluster.name: happy-ending
node.name: n3
stats.service.interval: 0
network.host: _local_
node.max_local_storage_nodes: 3
path.data: /Users/marregui/workspace/mgbench/DATA/data
path.repo: /Users/marregui/workspace/mgbench/DATA/crate_repo

http.cors.enabled: true
http.cors.allow-origin: "*"

transport.tcp.port: 4303
gateway.expected_nodes: 3
gateway.recover_after_nodes: 2
discovery.seed_hosts:
- 127.0.0.1:4301
- 127.0.0.1:4302
cluster.initial_master_nodes:
- 127.0.0.1:4301
- 127.0.0.1:4302
```

Then you can start the nodes, each from its own terminal window:

- ./crate -Cpath.conf=/Users/marregui/workspace/mgbench/DATA/conf/n1
- ./crate -Cpath.conf=/Users/marregui/workspace/mgbench/DATA/conf/n2
- ./crate -Cpath.conf=/Users/marregui/workspace/mgbench/DATA/conf/n3

And you can go to a browser [localhost:4200](localhost:4200) and see the cluster formed and a master elected.

Might there be something in the logs providing useful clues?

Best regards

**Comment by patristein** [comment]
Hi marregui,

starting separate instances on one host with local bindings works well.
Tested 4.1.0 nightly and 4.0.10 stable.

Next I tried to bind to site (by IP address) but it fails with error "bootstrap checks failed".
I set options like described here
[https://crate.io/docs/crate/guide/en/latest/admin/bootstrap-checks.html](https://crate.io/docs/crate/guide/en/latest/admin/bootstrap-checks.html)
but this doesn't work and startup fails with same error.

In the logs there isn't any useful hint - as far as I can tell.

Might there be a problem or any special parameter to be set for binding to global IP address?

Regards

**Comment by marregui** [comment]
Hi,

What fails?, is it the heap?, have you tried to set the heap to what the error message reports?

`export CRATE_HEAP_SIZE=size e.g. 8589934592  e.g. 500m`

As per the `network.host` setting, have a look at what `ifconfig -a` (or equivalent) reports in your system, I have chosen to use the **en0** interface:

```
**en0**: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether a4:83:e7:60:d4:83
	inet6 fe80::1860:472d:391c:d29b%en0 prefixlen 64 secured scopeid 0x6
	inet 192.168.1.56 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```
thus:

**network.host: \_**en0**\_**

Best regards,

**Comment by patristein** [comment]
Hi,

setting the var CRATE_HEAP_SIZE manually worked great and CRATE started.
Also with (network.host) IP-binding or with interface binding discovery works well on one host.
So one step in the right direction ;)

Now I adopted theses settings to different hosts like mentioned in my first post.
After all a warning appeared in logs:

[2020-01-14T10:59:32,553][WARN ][o.e.c.c.ClusterFormationFailureHelper] [srvccl01] master not discovered or elected yet, an election requires a node with id [bC5F-O2SQTishRIeNkxOoQ], have discovered [{srvccl02}{ue_jfkEOTcmKaR4ll4RBqA}{3TsofqSVQ9WPCGS7iVLDSw}{172.30.99.109}{172.30.99.109:4302}{http_address=172.30.99.109:4200}] which is not a quorum; discovery will continue using [172.30.99.109:4302, 172.30.99.110:4303, 172.30.99.109:4302, 172.30.99.110:4303] from hosts providers and [{srvccl01}{hZqlDEASQKm1oy5kRtQBlA}{BI7jTD7_Roq7rP8yIJcIZQ}{172.30.99.99}{172.30.99.99:4301}{http_address=172.30.99.99:4200}] from last-known cluster state; node term 25, last-accepted version 37249636 in term 25

Did you know why this node requires the mentioned node id bC5F...?
Where did it come from?

In config I defined all three hosts in option seed_hosts and initial_master_nodes with IP and port and also tried with hostname and with both hostname and IP like this:

**discovery.seed_hosts:**
- srvccl01:4301
- srvccl02:4302
- srvccl03:4303
- 172.30.99.99:4301
- 172.30.99.109:4302
- 172.30.99.110:4303
**cluster.initial_master_nodes:**
- srvccl01:4301
- srvccl02:4302
- srvccl03:4303
- 172.30.99.99:4301
- 172.30.99.109:4302
- 172.30.99.110:4303

Regards

**Comment by patristein** [comment]
OK, it is working now.
I removed everything under path.data-path in all nodes and restarted.

I didn't realize that some config options are held in this path.

Thanks for your help!

**Comment by marregui** [comment]
Cluster state!

Any time, best regards.
