### ISSUE TITLE
Support for USING clause for joins

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9551]
**Use case**:

The PostgreSQL JDBC client invokes the following query when using
`conn.getMetaData().getVersionColumns(...)`.

Part of the query uses `JOIN (...) as r USING (nspname)`. This triggers an
error in CrateDB: `UnsupportedFeatureException: join criteria JoinUsing not
supported`

`USING` is a short-hand for equi-joins when the columns of both relations have
the same name. See [Simplifying Joins with the USING
keyword](http://www.java2s.com/Tutorial/Oracle/0140__Table-Joins/SimplifyingJoinswiththeUSINGKeyword.htm)

The full query:

```
SELECT
    typinput = 'array_in'::regproc,
    typtype
FROM
    pg_catalog.pg_type
    LEFT JOIN (
        SELECT
            ns.oid AS nspoid,
            ns.nspname,
            r.r
        FROM
            pg_namespace AS ns
            JOIN (
                SELECT
                    s.r,
                    (current_schemas(FALSE))[s.r] AS nspname
                FROM
                    generate_series(1, array_upper(current_schemas(FALSE), 1)) AS s (r)
            ) AS r USING (nspname)) AS sp ON sp.nspoid = typnamespace
WHERE
    typname = $1
ORDER BY
    sp.r,
    pg_type.oid DESC
LIMIT 1
```

**Comment by marregui** [comment]
https://github.com/crate/crate/pull/9629
