### ISSUE TITLE
Nested geo_shape column returned in select statement as primary column

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9555]
**CrateDB version**: 4.0.11

**Problem description**:
I created table with nested `geo_shape` column in object.
After I call `select * from table` - this column returned in resultset in first level.

**Steps to reproduce**:
`create table test (x int, y object as (z geo_shape));`
`>> Table TEST created.`

`select * from test;`
`>> Result set with columns: y['z'], x, y`
Expected columns in result set: `x, y` (see screanshots):

table view:
![table view](https://user-images.githubusercontent.com/19342331/72884523-52bece80-3d17-11ea-99f7-3a12a33aee67.png)

result set columns:
![result set columns](https://user-images.githubusercontent.com/19342331/72884575-68cc8f00-3d17-11ea-839e-df595c82ce61.png)

**Comment by mfussenegger** [comment]
Thank you for the report. 

We can reproduce this and are working on a fix.
