### ISSUE TITLE
Add mod scalar function

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9582]
PostgreSQL JDBC returns `mod` (among others) when calling
`getNumericFunctions()` on the DB metdata object.

If we switch from our custom JDBC fork and advice users to use
PostgreSQL JDBC we should support all functions that are returned by
`getNumericFunctions()`

[PostgreSQL math functions](https://www.postgresql.org/docs/current/functions-math.html)

```
mod(y, x) -> same as argument types

returns the remainder of y/x

mod(9, 4) -> 1
```

**Comment by seut** [comment]
Implemented by https://github.com/crate/crate/pull/9640
