### ISSUE TITLE
Add radians scalar function

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9583]
PostgreSQL JDBC returns `radians` (among others) when calling
`getNumericFunctions()` on the DB metdata object.

If we switch from our custom JDBC fork and advice users to use
PostgreSQL JDBC we should support all functions that are returned by
`getNumericFunctions()`

[Escaped scalar functions](https://jdbc.postgresql.org/documentation/head/escaped-functions.html)
[PostgreSQL math functions](https://www.postgresql.org/docs/current/functions-math.html)

```
radians(dp) -> dp

degrees to radians

radians(45.0) -> 0.785398163397448
```

**Comment by seut** [comment]
Implemented by https://github.com/crate/crate/pull/9638.
