### ISSUE TITLE
Add current_time expression

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9662]
**Use case**:

Getting the current time

**Feature description**:

`current_time` is part of the [SQL 99 Standard](https://crate.io/docs/sql-99/en/latest/chapters/08.html?highlight=current_time#niladic-datetime-functions)

PostgreSQL JDBC lists `curtime` as supported escaped function. It is translated to `current_time`

```
cr> select current_time;
SQLActionException[UnsupportedFeatureException: Unsupported expression current_time]
```

```
# select current_time, pg_typeof(current_time);
   current_time   |      pg_typeof      
------------------+---------------------
 11:19:58.1347+01 | time with time zone
(1 row)

Time: 3.757 ms
```

- [JDBC escaped functions](https://jdbc.postgresql.org/documentation/head/escaped-functions.html)

**Comment by pooja1pathak** [comment]
Hi @marregui are you working on this issue? Is PR https://github.com/crate/crate/pull/9855 raised to resolve this? If not, I want to contribute in this issue, please assign it to me.

**Comment by mfussenegger** [comment]
> Hi @marregui are you working on this issue? Is PR #9855 raised to resolve this? If not, I want to contribute in this issue, please assign it to me.

Yes to both. @marregui is working on this and https://github.com/crate/crate/pull/9855 will resolve this. It  turned out to be a bit more difficult because a new type is needed

**Comment by marregui** [comment]
Merged https://github.com/crate/crate/pull/10061
