### ISSUE TITLE
Grafana 6.6.x Support - Add server_version_num setting.

### ISSUE THREAD

**Issue by h4xmd** [crate/crate#9673]
When using Grafana 6.6.x, the PostgreSQL driver cannot be used with CrateDB as Grafana tries to read the server version and fails with the following error:

`
{"results":{"tempvar":{"error":"pq: SQLParseException: Unrecognised Setting: server_version_num","refId":"tempvar","meta":{"sql":"SELECT current_setting('server_version_num')::int/100"},"series":null,"tables":null,"dataframes":null}},"message":"pq: SQLParseException: Unrecognised Setting: server_version_num"}
`

Means we cannot use Grafana to build dashboards or explore the data.

**Comment by mfussenegger** [comment]
Thank you for the report. We'll add the `server_version_num` setting.

Any chance to use an older Grafana version in the meantime? I think 6.4 and 6.5 should work.
