### ISSUE TITLE
group query over union all subquery result

### ISSUE THREAD

**Issue by geronimo00** [crate/crate#9732]
**CrateDB version**: 4.1.1

**Environment description**: Ubuntu 18.04.4 LTS

**Problem description**:

I've the following subquery:

```sql
SELECT
    id_asset,
    sum(fields['contador_total:dx']) AS hora,
    0 AS dia,
    0 AS mes
FROM
    zmx.metrics
WHERE
    id_asset IN ('1580233926786', '1580233906413')
    AND name = '_0_state'
    AND tags['tml'] = date_format ('%Y%m%d-%H', CURRENT_TIMESTAMP - 3600000)
GROUP BY
    id_asset
UNION ALL
SELECT
    id_asset,
    0 AS hora,
    sum(fields['contador_total:dx']) AS dia,
    0 AS mes
FROM
    zmx.metrics
WHERE
    id_asset IN ('1580233926786', '1580233906413')
    AND name = '_0_state'
    AND tags['ymd'] = try_cast (date_format ('%Y%m%d', CURRENT_TIMESTAMP) AS integer) - 1
GROUP BY
    id_asset
UNION ALL
SELECT
    try_cast (id_asset AS bigint) AS id_asset,
    0 AS hora,
    0 AS dia,
    sum(sum_contador_total_dx) AS mes
FROM
    zmx.t0_state
WHERE
    id_asset IN ('1580233926786', '1580233906413')
    AND ym = try_cast (date_format ('%Y%m', CURRENT_TIMESTAMP) AS integer) - 1
GROUP BY
    id_asset
```

the result is OK:

```
id_asset       | hora    | dia    | mes
1580233926786  | 0       | 0      | 1442
1580233906413  | 0       | 116    | 0
1580233906413  | 0       | 0      | 0
1580233906413  | 0       | 0      | 1330
```
 
but if I do a group by over that subquery, result is not as expected:

```sql
SELECT
    id_asset,
    sum(hora),
    sum(dia),
    sum(mes)
FROM (
    SELECT
        id_asset,
        sum(fields['contador_total:dx']) AS hora,
        0 AS dia,
        0 AS mes
    FROM
        zmx.metrics
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND name = '_0_state'
        AND tags['tml'] = date_format ('%Y%m%d-%H', CURRENT_TIMESTAMP - 3600000)
    GROUP BY
        id_asset
    UNION ALL
    SELECT
        id_asset,
        0 AS hora,
        sum(fields['contador_total:dx']) AS dia,
        0 AS mes
    FROM
        zmx.metrics
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND name = '_0_state'
        AND tags['ymd'] = try_cast (date_format ('%Y%m%d', CURRENT_TIMESTAMP) AS integer) - 1
    GROUP BY
        id_asset
    UNION ALL
    SELECT
        try_cast (id_asset AS bigint) AS id_asset,
        0 AS hora,
        0 AS dia,
        sum(sum_contador_total_dx) AS mes
    FROM
        zmx.t0_state
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND ym = try_cast (date_format ('%Y%m', CURRENT_TIMESTAMP) AS integer) - 1
    GROUP BY
        id_asset) AS subquery
GROUP BY
    id_asset
```

result:

```
id_asset      | sum(hora) | sum(dia) | sum(mes)
1580233906413 | 0         | 1330     | 1330
1580233926786 | 0         | 1442     | 1442
```

**Steps to reproduce**:

**Comment by mfussenegger** [comment]
I tried to reproduce this, but wasn't able to. Could you post the output of the following query?


<details>
  <summary>EXPLAIN <query></summary>

```sql
EXPLAIN SELECT
    id_asset,
    sum(hora),
    sum(dia),
    sum(mes)
FROM (
    SELECT
        id_asset,
        sum(fields['contador_total:dx']) AS hora,
        0 AS dia,
        0 AS mes
    FROM
        zmx.metrics
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND name = '_0_state'
        AND tags['tml'] = date_format ('%Y%m%d-%H', CURRENT_TIMESTAMP - 3600000)
    GROUP BY
        id_asset
    UNION ALL
    SELECT
        id_asset,
        0 AS hora,
        sum(fields['contador_total:dx']) AS dia,
        0 AS mes
    FROM
        zmx.metrics
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND name = '_0_state'
        AND tags['ymd'] = try_cast (date_format ('%Y%m%d', CURRENT_TIMESTAMP) AS integer) - 1
    GROUP BY
        id_asset
    UNION ALL
    SELECT
        try_cast (id_asset AS bigint) AS id_asset,
        0 AS hora,
        0 AS dia,
        sum(sum_contador_total_dx) AS mes
    FROM
        zmx.t0_state
    WHERE
        id_asset IN ('1580233926786', '1580233906413')
        AND ym = try_cast (date_format ('%Y%m', CURRENT_TIMESTAMP) AS integer) - 1
    GROUP BY
        id_asset) AS subquery
GROUP BY
    id_asset
```

</details>


Does the same issue also occur if you reduce the inner query to one UNION ALL instead of two?

**Comment by geronimo00** [comment]
Thanks for the quick response.

I have simplified the query:

Subquery:

cr> SELECT
            id_asset,
            sum(fields['contador_total:dx']) AS hora,
            0 AS dia,
            0 as mes
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset
        UNION ALL
        SELECT
            id_asset,
            0 AS hora,
            sum(fields['contador_total:dx']) AS dia,
            0 as mes
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset limit 100;
+---------------+------+-----+-----+
|      id_asset | hora | dia | mes |
+---------------+------+-----+-----+
| 1580233906413 |  834 |   0 |   0 |
| 1580233906413 |    0 | 834 |   0 |
| 1580233926786 |    0 | 137 |   0 |
| 1580233926786 |  137 |   0 |   0 |
+---------------+------+-----+-----+
SELECT 4 rows in set (0.058 sec)

as expected.

With the group by:
SELECT
        id_asset,
        sum(hora),
        sum(dia),
        SUM(mes)
    FROM (
        SELECT
            id_asset,
            sum(fields['contador_total:dx']) AS hora,
            0 AS dia,
            0 as mes
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset
        UNION ALL
        SELECT
            id_asset,
            0 AS hora,
            sum(fields['contador_total:dx']) AS dia,
            0 as mes
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset
        ) AS subquery
    GROUP BY
        id_asset limit 100;
+---------------+-----------+----------+----------+
|      id_asset | sum(hora) | sum(dia) | sum(mes) |
+---------------+-----------+----------+----------+
| 1580233906413 |       834 |        0 |        0 |
| 1580233926786 |       137 |        0 |        0 |
+---------------+-----------+----------+----------+
SELECT 2 rows in set (0.018 sec)

so sum(dia) is not OK.

Explain plan:

{"UnionExecutionPlan": {"left": {"Merge": {"mergePhase": {"MERGE": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["CBqjkzoZTy-1EBnVBhXu6A", "q2DoY5JxQF6mb2Eau_oEXQ"], "id": 1, "projections": [{"aggregations": "Aggregation{sum, args=[IC{1, bigint}], filter=true}", "keys": "IC{0, bigint}", "type": "HashAggregation"}, {"outputs": "IC{0, bigint}, IC{1, bigint}, 0, 0", "type": "Eval"}], "type": "executionPhase"}}, "subPlan": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "MODULO"}, "executionNodes": ["CBqjkzoZTy-1EBnVBhXu6A", "q2DoY5JxQF6mb2Eau_oEXQ"], "id": 0, "projections": [{"aggregations": "Aggregation{sum, args=[IC{0, bigint}], filter=true}", "keys": "IC{1, bigint}", "type": "HashAggregation"}], "routing": {"CBqjkzoZTy-1EBnVBhXu6A": {"zmx.metrics": [0, 2, 3]}, "q2DoY5JxQF6mb2Eau_oEXQ": {"zmx.metrics": [1]}}, "toCollect": "Ref{zmx.metrics.fields['contador_total:dx'], bigint}, Ref{zmx.metrics.id_asset, bigint}", "type": "executionPhase", "where": "Ref{zmx.metrics.name, text} = _0_state AND op_not(op_isnull(Ref{zmx.metrics.id_asset, bigint}))"}}, "type": "executionPlan"}}, "type": "executionPlan"}}, "mergePhase": {"MERGE": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["W0o0eqKCSXCBWTb-ZeAxjA"], "id": 4, "projections": [{"aggregations": "Aggregation{sum, args=[IC{1, bigint}], filter=true}, Aggregation{sum, args=[IC{3, bigint}], filter=true}", "keys": "IC{0, bigint}", "type": "HashAggregation"}, {"limit": 100, "offset": 0, "outputs": "IC{0, bigint}, IC{1, bigint}, IC{2, bigint}", "type": "TopN"}, {"outputs": "IC{0, bigint}, IC{1, bigint}, IC{2, bigint}, IC{2, bigint}", "type": "Eval"}], "type": "executionPhase"}}, "right": {"Merge": {"mergePhase": {"MERGE": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["CBqjkzoZTy-1EBnVBhXu6A", "q2DoY5JxQF6mb2Eau_oEXQ"], "id": 3, "projections": [{"aggregations": "Aggregation{sum, args=[IC{1, bigint}], filter=true}", "keys": "IC{0, bigint}", "type": "HashAggregation"}, {"outputs": "IC{0, bigint}, 0, IC{1, bigint}, 0", "type": "Eval"}], "type": "executionPhase"}}, "subPlan": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "MODULO"}, "executionNodes": ["CBqjkzoZTy-1EBnVBhXu6A", "q2DoY5JxQF6mb2Eau_oEXQ"], "id": 2, "projections": [{"aggregations": "Aggregation{sum, args=[IC{0, bigint}], filter=true}", "keys": "IC{1, bigint}", "type": "HashAggregation"}], "routing": {"CBqjkzoZTy-1EBnVBhXu6A": {"zmx.metrics": [0, 2, 3]}, "q2DoY5JxQF6mb2Eau_oEXQ": {"zmx.metrics": [1]}}, "toCollect": "Ref{zmx.metrics.fields['contador_total:dx'], bigint}, Ref{zmx.metrics.id_asset, bigint}", "type": "executionPhase", "where": "Ref{zmx.metrics.name, text} = _0_state AND op_not(op_isnull(Ref{zmx.metrics.id_asset, bigint}))"}}, "type": "executionPlan"}}, "type": "executionPlan"}}, "type": "executionPlan"}}

But if I remove the "mes", then result is OK:

cr> SELECT
        id_asset,
        sum(hora),
        sum(dia)
    FROM (
        SELECT
            id_asset,
            sum(fields['contador_total:dx']) AS hora,
            0 AS dia
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset
        UNION ALL
        SELECT
            id_asset,
            0 AS hora,
            sum(fields['contador_total:dx']) AS dia
        FROM
            zmx.metrics
        WHERE
            name = '_0_state' and id_asset is not null
        GROUP BY
            id_asset
        ) AS subquery
    GROUP BY
        id_asset limit 100;
+---------------+-----------+----------+
|      id_asset | sum(hora) | sum(dia) |
+---------------+-----------+----------+
| 1580233906413 |       834 |      834 |
| 1580233926786 |       137 |      137 |
+---------------+-----------+----------+
SELECT 2 rows in set (0.017 sec)

**Comment by mfussenegger** [comment]
Thank you for trimming down the example, that made it easier to reproduce.

We merged a fix (https://github.com/crate/crate/pull/9736) which we release as part of 4.1.3
