### ISSUE TITLE
Bundle JDK with the CrateDB tarball.

### ISSUE THREAD

**Issue by kovrus** [crate/crate#9754]
**Use case**:

Bundle JDK with the CrateDB tarball to be able to utilize the newest JDK features
and reduce the amount of testing we have to do (JDK test matrix) without putting
the burden of keeping users systems up to date.

**Master branches across repositories:**
- [x] Bundle JDK in crate/crate
   It has to be changed once 4.2 is released and declared as stable.
- [x] Docker builds
- [x] Documentation in various places (mentioning Java requirement):
  - [x] crate/crate
- [x] Remove JvmVersionNodeCheck
- [x] Remove Bootstrap check (G1GCCheck)
- [x] Release pipeline:
  - [x] Adjust the build Tarball Jenkins job and add additional job(s) to build CrateDB packages for mac os, windows, linux(aarch64, amd64). 
  - [x] Adjust build/test distributions jobs and distribution packages builds.
  - [x] Drop JRE dependencies in distribution packages and tests.
- [x] CrateDB Docker image multi architecture support. 

**Post testing release:**
- [x] cr8
- [x] Documentation in various places (mentioning Java requirement):
  - [x] Guide in https://crate.io/docs/crate/guide/en/latest/deployment/linux/ubuntu.html
- [x] Enable [aarch64_linux](https://github.com/crate/docker-crate/blob/master/.github/workflows/main.yml#L11) tests in the [crate-docker](https://github.com/crate/docker-crate) repository.

**Post stable release:**
- [x] Add the section to [official-images/library/crate](https://github.com/docker-library/official-images/blob/master/library/crate) to reflect the multi architecture support, see the description https://github.com/crate/docker-crate/pull/174.
- [x] https://github.com/crate/crate-utils/blob/master/easy/try.sh

**Pre-sales:**
- [x] Update the website download section

**Comment by kovrus** [comment]
@scjimenez fyi

Regarding the `Update the website download section`. Starting from the
version `4.2.0` we are going to package CrateDB for the following platforms:
- x64_linux
- aarch64_linux 
- x64_windows
- x64_mac

Once the `4.2.0` testing version is released `CrateDB` tar and zip files can be found on our CDN
under the https://cdn.crate.io/downloads/releases/cratedb/. The folder names correspond
to names of the targeted platforms. The name pattern of the CrateDB builds stays the same
as it was in https://cdn.crate.io/downloads/releases/ . For example:

```
- releases
     - cratedb
         - x64_linux
             crate-4.2.0.tar.gz         
         - aarch64_linux
             crate-4.2.0.tar.gz         
         - x64_windows
             crate-4.2.0.zip
...
```

The nightly releases will be built only for `x64_linux` and still reside under https://cdn.crate.io/downloads/releases/nightly/.

CrateDB builds for versions < `4.2.0` still reside at the same location.

**Comment by msbt** [comment]
@kovrus currently we're parsing https://crate.io/releases.json for downloads. Will this json also include the new releases and if so, how will the pattern be, the same as you stated above?

**Comment by kovrus** [comment]
@msbt yes, it should include new releases. You can check out the pattern once this PR is merged https://github.com/crate/distribute/pull/369
