### ISSUE TITLE
support "upsert into" Grammatical sugar

### ISSUE THREAD

**Issue by cmdares** [crate/crate#9806]
issue ref: https://github.com/crate/crate/issues/8151
In order to achieve the purpose of simple use and optimization, we hope that the official can support the features of this syntax. Currently, many high-performance distributed databases support this syntax.
Although support “ON CONFLICT DO UPDATE SET”,Hope to provide the "upsert into" syntax
Logic corresponding to es:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts

Thanks again!

**Comment by mfussenegger** [comment]
We try to stick to SQL Standard (which would mean adding the MERGE syntax) and PostgreSQL syntax and would need a more compelling reason than "more pleasant to write" (which is subjective) to add another variation.

The reason for PostgreSQL syntax is that we implemented the postgres wire protocol and many tools that are PostgreSQL specific "just work" if we also support their syntax.
