### ISSUE TITLE
Jigsaw modularize CrateDB 

### ISSUE THREAD

**Issue by kovrus** [crate/crate#9819]
## Use case

Use the Java Platform Module System, specified by [JSR 376](https://openjdk.java.net/projects/jigsaw/spec/) and implemented by [JEP 261](https://openjdk.java.net/jeps/261), to modularize `CrateDB`.

## Feature description

`CrateDB` versions starting from `4.2` will be shipped with the bundled `JDK` (https://github.com/crate/crate/issues/9754 https://github.com/crate/crate/pull/9746). At the time of writing the `JDK 14` is used. Starting with the `JDK 9` the distinction between `JDK` and `JRE` was eliminated due to their restructure and modularization, see [JEP 200](https://openjdk.java.net/jeps/200) and [JEP 220](https://openjdk.java.net/jeps/220). It means that `CrateDB` bundles the `JDK` with the components that might not be needed to run the application. 

The `CrateDB` project was started prior to the `JDK 9` release, and have not been migrated to the new modular form of Java applications organisation. Also, the [Java Platform Module System](https://openjdk.java.net/jeps/261) introduces the new `JDK` specific [jlink]( https://openjdk.java.net/jeps/282) tool, to generate the Java runtime images based on the modules, that is not used as well.

It follows from the current state of the project that the `CrateDB` application does not utilize the module system at all and does not benefit from the existing Java platform toolset and concepts. Therefore, the modularisation of the `CrateDB` application is required and will result in improvements of maintainability, performance, security, packaging by simplifying and reducing the size of the application, also, in the foreseeable future some work (introduction of `jlink`) towards modularization will allow us to use tools like [jpackage ](https://openjdk.java.net/jeps/343) to support native packaging formats, and keep the project up to date with the modern Java platform modular organisation of applications that provide the reliable configuration and strong encapsulation of modules.

Some work for `CrateDB` modularization can be done relatively fast and without big investments that would lead to immediate improvements. For example, we can use the `jlink` tool to build the non-modular `CrateDB` application and benefit from the modular nature of `JDK`. On the other hand, there are some more substantial changes required, like defining the modular structure of the application and all follow-up tasks that will require more time. Therefore, it would make sense to split the work into two phases. 

#### Prepare the `CrateDB` build infrastructure for migration to the modular form 

The modules system can compile and run an application composed of Jar files in the classpath even though the platform itself is composed of modules. It is possible due to the compatibility and migration mechanism that would attempt to load types from the defined modules first and if they are not part of the module definition, they will be loaded from the classpath and allocated into the special module known as the `unnamed module`. It enables the possibility of a smooth migration of the non-modular application to the modular form. 

As for the first step, we mostly want to focus on the tooling around the modular system and prepare the non-modular `CrateDB` application and build infrastructure for the gradual migration into the modular form by introducing the `jlink` tool into the build infrastructure.

This change should affect the size of the `CrateDB` package such as build system should assemble and optimise the size of modular bundled `JDK` by producing the `JRE` runtime-image tailored to the `CrateDB` requirements.

#### Migrate `CrateDB` to the modular form

Incrementally migration the member of the unnamed module into the named modules. 

This task includes the definition of the modular graph of the `CrateDB` application and potential reorganisation of the project structure.

## Resources
* https://openjdk.java.net/jeps/261
* https://openjdk.java.net/projects/jigsaw/spec/sotms/
* https://openjdk.java.net/projects/jigsaw/

**Comment by mfussenegger** [comment]
Btw. before I forget it: I think it might still be beneficial to have tools like `jcmd` included in the distribution. (Also for the Docker image). This has been very helpful to quickly trigger JFR

**Comment by mfussenegger** [comment]
Since https://github.com/crate/crate/pull/13651 jlink is in use.
Attempts to use the module system ran into issues with test visibility. (https://github.com/mfussenegger/maven-lucene-jpms-test contains a minimal example where the `LuceneTestCase` dependency isn't visible in the tests)

Currently there are no further plans to follow up on it, as the return on investment doesn't seem worth it.
