### ISSUE TITLE
IP Type Group by Select Sorting Issue

### ISSUE THREAD

**Issue by yongyi82** [crate/crate#9842]
CrateDB version : 4.1.4

OS version / environment description: CentOS 7.4

Problem description:

The result of Group by select order by IP type is not displayed correctly.

If I select without Group by, it is displayed normally. May be Bug?

Even if I order by using TYPE CAST, it is not displayed correctly.

== result of group by select == 

```sql
select ipaddr, bytes from (
select ipaddr, sum(byte) as bytes from test_hist group by ipaddr
) A order by A.ipaddr asc limit 100
```

```
10.200.1.100, 100
10.220.1.120, 200
10.220.1.20, 140
```

== result of no group by select == 

```sql
select ipaddr, byte from test_hist order by ipaddr asc limit 100
```

```
10.220.1.20, 10
10.200.1.100, 20
10.220.1.120, 100
```

== result of group by select with type cast ==

```sql
select ipaddr, bytes from (
select ipaddr, sum(byte) as bytes from test_hist group by ipaddr
) A order by A.ipaddr::ip asc limit 100
```

```
10.200.1.100, 100
10.220.1.120, 200
10.220.1.20, 140
```

**Comment by mfussenegger** [comment]
> The result of Group by select order by IP type is not displayed correctly.
> 
> If I select without Group by, it is displayed normally. May be Bug?
> 
> Even if I order by using TYPE CAST, it is not displayed correctly.

Depends on which ordering you consider correct.

```
10.200.1.100, 100
10.220.1.120, 200
10.220.1.20, 140
```

Is sorted alphanumerically. Which would be the expected ordering (we currently expose IPs as string or text to clients).

The order returned by `select ipaddr, byte from test_hist order by ipaddr asc limit 100` is wrong.
