### ISSUE TITLE
OFFSET not working as expected with UNION ALL queries

### ISSUE THREAD

**Issue by chicco785** [crate/crate#9854]
**CrateDB version**: 4.1

**Environment description**:

**Problem description**:

It seems that OFFSET is not working in UNION ALL queries.

**Steps to reproduce**:

Let's create two tables on top of which we want to run UNION ALL:

```
CREATE TABLE table1 (
  id STRING,
  time_index TIMESTAMP
)

CREATE TABLE table2 (
  id STRING,
  time_index TIMESTAMP
)
```

Let's insert some data:

```
INSERT INTO table1 (id, time_index)
VALUES ('index_1',1586176952);
INSERT INTO table1 (id, time_index)
VALUES ('index_1',1586175952);
INSERT INTO table2 (id, time_index)
VALUES ('index_2',1586156952);
INSERT INTO table2 (id, time_index)
VALUES ('index_2',1586155952);
```

Let's run this query

```
select id, max(time_index) as time_index FROM table1 group by id union all select id, max(time_index) as time_index FROM table2 group by id order by time_index asc limit 100;
```

result:

| id	| time_index |
| --- |-------------|
|index_1|	 1586176952 |
|index_2|	 1586156952 |

All looks fine!

Let's introduce offset:

```
select id, max(time_index) as time_index FROM table1 group by id union all select id, max(time_index) as time_index FROM table2 group by id order by time_index asc limit 100 offset 1;
```

result no data!

The expected result:
| id	| time_index |
| --- |-------------|
|index_1|	 1586176952 |

**Comment by c0c0n3** [comment]
What the heck :-)
I've had a quick look at Crate 4.1 docs and it could have something to do with where we put order by/limit/offset in the query:

* https://crate.io/docs/crate/reference/en/4.1/sql/statements/select.html#union-all

they say they should follow the last statement which they do in your example query, so it could be a bug or we may have to use parens.

Yet another backward incompatibility from Crate 3 to 4. Oh dear.

**Comment by chicco785** [comment]
Not even using chained queries works as expected

```
SELECT * FROM (select id, max(time_index) as time_index FROM table1 group by id union all select id, max(time_index) as time_index FROM table2 group by id) as result order by time_index asc limit 100 OFFSET 1;
```

**Comment by chicco785** [comment]
Removing ORDER BY resolve the problem...

**Comment by chicco785** [comment]
I replicated the expected behaviour in fiddle:
http://sqlfiddle.com/#!17/8ad08/2

I think this confirms that's a bug from a SQL standing point.

**Comment by mfussenegger** [comment]
Thank you for the very detailed report :+1: 

Looks like it was working in CrateDB 3.3 and regressed in 4.0. We'll have a closer look

**Comment by chicco785** [comment]
@mfussenegger i can confirm it was working with CrateDB 3.3
