### ISSUE TITLE
How to view the number of real-time connections

### ISSUE THREAD

**Issue by wangDong524** [crate/crate#9866]
I want to see the number of connections to the cratedb and how to do it
thanks

**Comment by kovrus** [comment]
Hi @wangDong524 ,

You can get it from the [JMX API](https://crate.io/docs/crate/reference/en/latest/admin/monitoring.html#connections-mbean) or by querying the [sys.nodes connection](https://crate.io/docs/crate/reference/en/latest/admin/system-information.html?highlight=sys%20nodes#connections), e.g. `select connections from sys.nodes`
