### ISSUE TITLE
Add a VARCHAR type

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9868]
**Use case**:

Main use case is better compatibility with both [SQL Standard](https://crate.io/docs/sql-99/en/latest/chapters/07.html#character-varying) and [PostgreSQL](https://www.postgresql.org/docs/current/datatype-character.html).

Increases the chance that `CREATE TABLE` statements "just work" - although for production settings they'll likely still want to be extended with sharding or partitioning.

As of CrateDB 4.1.x:

- CrateDB already has `string` and `text. `string` is an alias for `text`
- We map `text (DataTypes.STRING)` to `varchar (pg)` in the pgwire layer. So clients already receive `text (cratedb)` columns as `varchar (pg)`. We would ideally introduce a separate `varchar (cratedb)` type, and change `text (cratedb)` streaming to `text (pg)` but that would introduce a backward incompatibility and currently there is no known advantage of doing that - other than being "more correct". So probably not going to happen.
- We reverse map the text oid (25) to `DataTypes.STRING`, so that clients can sent arguments as `text (pg)`

**Feature description**:

## Minimal version

(Done via https://github.com/crate/crate/pull/9869)

Using the `varchar` type without value length limitation in DDL statements, like `CREATE TABLE`:

```sql
CREATE TABLE users (
  name varchar
);
```

## Extended version

Using the `varchar` type with value length limit that is validated on writes in DDL statements, like `CREATE TABLE`:

```sql
CREATE TABLE users (
  name varchar(2)
);

INSERT INTO users (name) VALUES ('a');      -- Inserted
INSERT INTO users (name) VALUES ('Arthur'); -- Fails
```

(Without storage optimization)

## Casts to varchar with length

```
INSERT INTO users (name) VALUES ('too long'::varchar(2)); -- explicit truncation
```

**Comment by joemoe** [comment]
one example is qlik failing to connect via the postgres connector.

```
select CAST(NULL AS VARCHAR(124)) AS "TABLE_CAT", CAST(nspname AS VARCHAR(124)) AS "TABLE_SCHEM", CAST(NULL AS VARCHAR(124)) AS "TABLE_NAME", CAST(NULL AS VARCHAR(124)) AS "TABLE_TYPE", CAST('' AS VARCHAR(250)) AS "REMARKS" FROM pg_catalog.pg_namespace n ORDER BY 2
```
