### ISSUE TITLE
Sorting on the basis of Index of String

### ISSUE THREAD

**Issue by ekanshdubey** [crate/crate#9883]
let's say I have a table 'test' which contains a column 'col1' which i have created with ngram analyzer.

assuming it has data such as -

    65123
    81234
    12304
    87541

and i query for '123'
such as 

    select col1 from test where col1 = '123';

**It's giving me results with arbitrary sorting.**
how can I achieve sorting as per the index of the matched phrase such as 

     12304 
     81234 
     65123

There Is a Function or a reserved value "POSITION" present In the system which I assumed resembled the position function in postgresql but It doesn't works the similar way and I couldn't find any Implementation for It in the documentation either.

additionally, i found a sort parameter " _score " which scores every match and we can sort on the basis of this match. However, _score doesn't account for the index of the string in the matching score. What that means is it doesn't matter on which index 123 appears in the result set it won't affect the matching score. Is there anything i can add as a column which additionally helps me sort this better ? @mfussenegger  can you help me gain clarity if this is possible currently or is there a way to achieve it ?

**Comment by mfussenegger** [comment]
I think currently there is no good way to achieve what you want, but I didn't have a closer look yet, it's on my todo list.

**Comment by mkleen** [comment]
Hello @ekanshdubey,

Unfortunately it is not possible to score on the index position of the query string. However you can try to following approach as a workaround:

Index your data with an edge_ngram analyzer:
```
create analyzer edge_ngram_analyzer (TOKENIZER my_ngram with (type = edge_ngram, min_gram = 3, max_gram =5));

create table test (values text INDEX using fulltext with (analyzer = 'edge_ngram_analyzer'));

insert into test(values) values('65123') , ('81234') , ('12304'), ('87541');
```
Use a fuzzy query and sort by score:
```
select values, _score from test where match(values,'123') using best_fields with (fuzziness='AUTO') order by _score desc;

+--------+------------+
| values |     _score |
+--------+------------+
| 12304  | 0.26152915 |
| 81234  | 0.17435277 |
| 65123  | 0.04358819 |
+--------+------------+
```
This seems to be the behaviour you are looking for, but the scoring is not based on the index position 
of your query term. It is based on the number of matches of your query term '123' with the edge ngrams from your data using
 https://en.wikipedia.org/wiki/Okapi_BM25 scoring. The fuzzy query will allow expansion/replacements of up to 2 character of the matching string, so this will only work for reasonable small strings. This method also adds storage overhead to the table and processing overhead to the query, so you want to be careful to use this with large data sets.
