### ISSUE TITLE
WITHIN function for multiple polygons

### ISSUE THREAD

**Issue by mav-erick** [crate/crate#9884]
I am able to run query for a single polygon like so:
```
select count(*) from <table> where within(current_geo_position, 'POLYGON((...))') and timestamp >= x and timestamp <= y;
```

It results in
```
-------
count(*)
-------
500
-------
```

Is it possible to run a query for multiple polygons and group the counts by polygons? I don't have the polygons stored in the DB, I supply it in the query.
In this case, the table has a column `current_geo_coordinates` that are of type `geo_point`.

**Comment by mfussenegger** [comment]
One way would be to use `unnest` to create a virtual table with the provided polygons and then join on `within`. Something like this: 

```sql
drop table tbl;
create table tbl (id int primary key, current_pos geo_shape);
insert into tbl (id, current_pos) values (1, 'POLYGON ((5 5, 10 5, 10 10, 5 10, 5 5))');
insert into tbl (id, current_pos) values (2, 'POLYGON ((5 2, 10 5, 10 10, 5 10, 5 2))');
insert into tbl (id, current_pos) values (3, 'POLYGON ((5 8, 10 5, 10 10, 5 10, 5 8))');


SELECT 
  count(*),
  polygons.polygon
FROM
  tbl inner join 
    (SELECT polygon FROM unnest(['POLYGON ((5 5, 10 5, 10 10, 5 10, 5 5))']) as t (polygon)) as polygons
    on within(tbl.current_pos, polygons.polygon)
GROUP BY
  polygons.polygon;

```


Another option would be to generate a `UNION ALL` with 1 additional select per supplied polygon.

Both of these options may not perform well with large data sets but I don't think there is currently a better option given the requirements.
