### ISSUE TITLE
Improve COPY FROM .. RETURN SUMMARY output

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#9890]
Importing a file that contains thousands of lines that cannot be imported using `COPY .. FROM .. RETURN SUMMARY` outputs the errors like:

```
errors: {
  "<error-message>": {
    "count": n,
    "line_numbers": [ ... ]
  }
}
```

Having thousands of line numbers within `line_numbers` currently [kills the admin ui](https://github.com/crate/crate-admin/issues/664). But even in `crash`, where it is output (eventually, depending on your terminal), it is barely helpful because you end up scrolling a long time until you see the error.

I think we should trim the `line_numbers` to a maximum. Maybe 50, or 100?

**Comment by seut** [comment]
> I think we should trim the line_numbers to a maximum. Maybe 50, or 100?

Yep valid points, agree. Maybe 50 is already enough?

**Comment by joemoe** [comment]
can/should we indicate somehow that this is an limited output? or is the gap count vs number of line_numbers plus documentation enough?

**Comment by mfussenegger** [comment]
> can/should we indicate somehow that this is an limited output? or is the gap count vs number of line_numbers plus documentation enough?

I think changing the response format in shape is problematic because of BWC. But we can extend the documentation
