### ISSUE TITLE
Returning statement on update expecting {<EOF>, ';'}

### ISSUE THREAD

**Issue by dmrgrg** [crate/crate#9947]
on CrateDb console i put this command

UPDATE messagetobroker SET status = 4 WHERE status = 2
RETURNING *;

Response:
UPDATE ERROR (0.000 sec)

Error!

SQLActionException[SQLParseException: line 2:1: mismatched input 'RETURNING' expecting {<EOF>, ';'}]

First line of error trace
SQLActionException: 400 Bad Request 4000 SQLParseException: line 2:1: mismatched input 'RETURNING' expecting {<EOF>, ';'}

on documentation (https://crate.io/docs/crate/reference/en/latest/sql/statements/update.html) i see

The optional RETURNING clause for UPDATE causes the query to return the specified values from each row that was updated. Any expression using the table’s columns can be computed. The new (post-update) values of the table’s columns are used. The syntax of the RETURNING list is identical to that of the output list of SELECT.

thanks

**Comment by kovrus** [comment]
@dmrgrg which CrateDB version are you using? The `RETURNING` clause hasn't been released yet. The https://crate.io/docs/crate/reference/en/latest/sql/statements/update.html documentation points to the `master`. You have to select the doc version you are currently on, e.g. for `4.1` see https://crate.io/docs/crate/reference/en/4.1/sql/statements/update.html.

**Comment by dmrgrg** [comment]
> 
> 
> @dmrgrg which CrateDB version are you using? The `RETURNING` clause hasn't been released yet. The https://crate.io/docs/crate/reference/en/latest/sql/statements/update.html documentation points to the `master`. You have to select the doc version you are currently on, e.g. for `4.1` see https://crate.io/docs/crate/reference/en/4.1/sql/statements/update.html.



i use version 4.1.5 
![immagine](https://user-images.githubusercontent.com/10920712/81832350-ae1f0180-953e-11ea-960b-707dbe582412.png)

ok, now it's clear to me.
but how could I currently achieve the same result efficiently?

thanks

**Comment by mfussenegger** [comment]
> but how could I currently achieve the same result efficiently?

In 4.1 the only option is to query the data afterwards.

**Comment by dmrgrg** [comment]
ok now i am doing exactly as suggested. I hope to update soon to the new version for a correct implementation

thanks
