### ISSUE TITLE
RepositoryVerificationException

### ISSUE THREAD

**Issue by michabbb** [crate/crate#9961]
hi there,

i just want to verify my assumption here, because i´m not 100% sure. while creating a repository of type "fs" i get this error:

```
RepositoryVerificationException[[where_my_snapshots_go] a file written by master to the store [/backup/repo] cannot be accessed on the node [{Nummer 2}{puTLI66RTRGO-HWRuxMoaw}{UAcdFOgmRpWlK7K6xboAkQ}{xxxxxxx}{xxxxxxxx:4300}{http_address=xxxxxx:4200}]. This might indicate that the store [/backup/repo] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];']]
````

so if i understand this correctly, the folder needs to be shared folder like a NAS where every node is able to write to ???

thanks!

**Comment by mfussenegger** [comment]
> so if i understand this correctly, the folder needs to be shared folder like a NAS where every node is able to write to 

Yes. 

[From the docs](https://crate.io/docs/crate/reference/en/latest/sql/statements/create-repository.html#fs)

> A repository storing its snapshots to a shared filesystem that must be accessible by all master and data nodes in the cluster.
