### ISSUE TITLE
Diagram incorrect

### ISSUE THREAD

**Issue by doreilly257** [crate/crate#9969]
###  Documentation feedback

 
- Page title: Joins
- Page URL: https://crate.io/docs/crate/reference/en/latest/concepts/joins.rst
- Source: https://github.com/crate/crate/blob/master/docs/concepts/joins.html

---

The png diagram for Figure 5, is incorrect for the right hand side join. It should be Y<10 not Y>100

**Comment by infoverload** [comment]
@doreilly257 Thanks for your contribution! A PR has been made to fix this issue. :)
