### ISSUE TITLE
Azure Blob storage support is not documented

### ISSUE THREAD

**Issue by dominikmoosbrugger** [crate/crate#9986]
###  Documentation feedback

 
- Page title: COPY FROM
- Page URL: https://crate.io/docs/crate/reference/en/latest/sql/statements/copy-from.rst
- Source: https://github.com/crate/crate/blob/master/docs/sql/statements/copy-from.html

---

On the page for the command there is no mention that CrateDB also supports Azure blob storage.

**Comment by mfussenegger** [comment]
Azure blob storage is only supported for snapshots (`CREATE REPOSITORY .. TYPE azure`). For COPY FROM `HTTPS` could be used, but that is not exclusive to azure blob storage.

Could you clarify what is missing?

**Comment by dominikmoosbrugger** [comment]
I think I was wrong here in that case - we have been using `HTTPS` with an Azure Storage Account / blob service through the file `URI`.
