### ISSUE TITLE
Default schema for protocol wire is not defined

### ISSUE THREAD

**Issue by marregui** [crate/crate#9991]
Currently, running a crate node on master (port 5433), and accessing it with command:

```
psql -h localhost -p 5433 -U crate
```

```
crate=> show tables;
 table_name
------------
 json
 t
(2 rows)

crate=> drop table doc.json;
DROP 1
crate=> drop table t;
ERROR:  Relation 't' unknown
```
Should the default schema be `doc`, to allow the latter drop to succeed?.

In crash doc is implicit:

```
cr> drop table t;
DROP OK, 1 row affected  (0.069 sec)
```

**Comment by mfussenegger** [comment]
For PostgreSQL the default schema is inherited via the database name. [See the PostgreSQL](https://crate.io/docs/crate/reference/en/latest/interfaces/postgres.html?highlight=postgres#database-selection) section in the docs.

`psql` defaults the database to the user, in your case `crate`.

```
❮ psql -h localhost -p 5433 -U crate
You are connected to database "crate" as user "crate" on host "localhost" (address "127.0.0.1") at port "5433".
crate=> show search_path;
      setting
-------------------
 pg_catalog, crate
(1 row)

Time: 69.959 ms
crate=>
```
