### ISSUE TITLE
CREATE TABLE AS

### ISSUE THREAD

**Issue by joemoe** [crate/crate#9999]
## Use case

Convenience to shift data around in one step without thinking about the details of the table structure.

## Feature description

```
CREATE TABLE new_table
  AS (SELECT * FROM old_table);
```
this creates an table with the structure based on the result of the query and ingests the query output.

https://www.techonthenet.com/sql/tables/create_table2.php
https://www.postgresql.org/docs/current/sql-createtableas.html

## Out of scope

- Adding any new functionality to the underlying CREATE TABLE (temporary, unlogged.. etc)

**Comment by jeeminso** [comment]
I have been working on this issue and have an initial commit on my local repo. Currently it can create tables with column constraints and insert the query results. I am hoping someone could have a look before I work on it any further. Thank you.

**Comment by seut** [comment]
@jeeminso Awesome! I'd suggest to create a Draft PR with your current state in order to gather early feedback.

**Comment by jeeminso** [comment]
@seut Thank you created a draft PR #10700
